### ISSUE TITLE
[Portuguese Windows10]: No logs available under Agent logs tab for Windows 10 Portuguese agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1005]
**Kibana version:**  8.4.0 Kibana cloud Released-Production environment

**Host OS:**  Portuguese Windows10

**Build details:**
VERSION: 8.4.0 Released-Production
BUILD: 55395
COMMIT: 1922ab0b6f8dc2906ef10f3fb65fc4d0e0076f90

**Integrations:**
SYSTEM

**Preconditions:**
1. 8.4.0 Kibana cloud Released-Production environment should be available.
2. Windows agent should be installed on Portuguese Windows 10 platform.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Observe no logs available under agent Logs tab.
3. Restart elastic-agent service and observe logs are still not available.

**Screenshots:**
![9](https://user-images.githubusercontent.com/77374876/186586347-5c1fcecb-d161-4db9-b5a4-72c4cafc43a9.JPG)

**What's working fine:**
- Data for integrations available under Data Streams tab.
![10](https://user-images.githubusercontent.com/77374876/186587896-762dc92b-4f29-46cb-bc46-ba87bef0aff3.JPG)

**Logs:**
[elastic-agent-diagnostics-2022-08-25T05-57-11Z-00.zip](https://github.com/elastic/elastic-agent/files/9421785/elastic-agent-diagnostics-2022-08-25T05-57-11Z-00.zip)

**Expected Result:**
Logs should be available under Agent logs tab for Windows 10 Portuguese agent.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on 8.6.0 release kibana cloud-production environment and found it **fixed** now.

**Host:**
Portuguese Windows 10

**Observations:**
- Logs are available under Agent logs tab for Windows 10 Portuguese agent.

**Build details:**
BUILD: 58852
COMMIT: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.6.0-windows-x86_64.zip

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/212032012-5536c8e4-4fe4-4f18-b723-3e8d55e53f18.mp4


Hence we are **closing** this issue and marking it as **QA:Validated**.

Thanks
