### ISSUE TITLE
Elastic Agent not configured with environment variables

### ISSUE THREAD

**Issue by mreinders** [elastic/elastic-agent#108]
Within the filebeat operator, we can use evironment variables to extend information on the container. With this option, we can set the container to immutable to prevent users from changing the agent configuration. For example:

tags: [container,${TAGS:unassigned}]

We are trying to introduce the new Elastic Agent on kubernetes and want to set this option on different inputs. For Example: 

      - name: container-log
        type: logfile
        use_output: default
        meta:
          package:
            name: log
            version: 0.4.6
        data_stream:
          namespace: kubernetes
        streams:
          - data_stream:
              dataset: test
              type: logs
            symlinks: true
            paths:
              - /var/log/containers/*${kubernetes.container.id}.log
            exclude_lines: ["^\\s+[\\-`('.|_]"]
            **tags: [${env.TAGS}]**

But it seems not to be working if we try to add the above, it shows the next error:
_Error: could not read configuration file /etc/elastic-agent/elastic-agent.yml: yaml: line 135: did not find expected ',' or ']'
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/7.15/fleet-troubleshooting.html_

When trying to add quotation, containers are getting up and running, but when we start analyzing logs, the added tags are displayed as string and not as array. So Logstash cannot route information on different tags.

As workarround, we can split the different tags  on comma separated values, but it would be nice to get this functionality back.

**Comment by jlind23** [comment]
[Clean up] Closing this one as stalle, will reopen later if required.
cc @ycombinator
