### ISSUE TITLE
[Self-managed]: No data is available under Data streams for Standalone agent.

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/elastic-agent#1086]
**Kibana version**: 8.5 Snapshot Kibana **self-managed** environment

**Host OS and Browser version**: All, All

**Build details:**
BUILD: 55993
COMMIT: 436b2874794a6ffc05ad3b9ef28c298ff5384ca4

**Preconditions:**
- 8.5 Snapshot Kibana **self-managed** environment should be available.

**Steps to reproduce:**
1. On fresh Kibana setup navigate to Fleet tab.
2. Create a new Policy.
3. Update 'elastic-agent.yml'.
4. Install agent in Standalone mode.
5. Observe No data under Data streams tab.

**Expected Result:**
- Data under Datastream tab should be display for Standalone agents.

**What is working fine:**
Data for standalone agent is available under Data streams tab on Cloud staging 8.5 Snapshot.

**Screenshots:**
![image](https://user-images.githubusercontent.com/102019374/188417640-ed4bed16-7a18-433d-a787-f475d3ac1cd0.png)

**elastic-agent.yml:** 
[elastic-agent.zip](https://github.com/elastic/elastic-agent/files/9488735/elastic-agent.zip)

**elastic-agent diagnostics:**
[elastic-agent-diagnostics-2022-09-05T09-24-43Z-00.zip](https://github.com/elastic/elastic-agent/files/9488637/elastic-agent-diagnostics-2022-09-05T09-24-43Z-00.zip)

**Comment by dikshachauhan-qasource** [comment]
Secondary review is done

**Comment by simranvaseer-qasource** [comment]
Hi Team,
We have revalidated this issue on latest 8.5 BC6 kibana self-managed environment and found it **fixed** now.

- Data under Datastream tab is available for Standalone agents.

```
VERSION: 8.5.0
BUILD: 57022
COMMIT: 0b06c1437f38a9eb9a4273003d8d2ce2c8905189
```

Screenshot:
![image](https://user-images.githubusercontent.com/102019374/196378813-e142bbdf-f27e-478c-94de-4d95f3b32d76.png)

Hence, marking this as QA:Validated.
Thanks
