### ISSUE TITLE
`mage notice` command hangs infinitely

### ISSUE THREAD

**Issue by ChrsMark** [elastic/elastic-agent#1107]
From latest `main` the `mage notice` command hangs forever like below:

```conosle
➜  elastic-agent git:(hints_based_autodiscovery_mappings) ✗ mage notice
>> Generating NOTICE
>> fmt - go mod tidy
>> fmt - go mod download
>> fmt - go list
>> fmt - go run

```

This blocks us from updating any dependencies cause we cannot update the `NOTICE.txt` file accordingly and the CI will fail in any case (ie at https://github.com/elastic/elastic-agent/pull/698).

**Comment by belimawr** [comment]
I did some investigating and found two issues:

**Comment by belimawr** [comment]
I know very little about `go-licence-detector`, so I can't help much to fix the issue with it. Maybe @cmacknz knows more or could help to find someone to look at it.

**Comment by cmacknz** [comment]
This problem feels familiar and I suspect it might have been fixed in the magefile of another project, let me try to track that down.

**Comment by cmacknz** [comment]
This what beats does: https://github.com/elastic/beats/blob/cf10d315d0f4d7fbe5893d65532078c3adbbd6b7/Makefile#L171

**Comment by cmacknz** [comment]
We also implement this different in elastic-agent-libs which is what most of the new repositories use: https://github.com/elastic/elastic-agent-libs/blob/ee6ce69b6f17a29307878527768f687d4d77faef/magefile.go#L83

**Comment by belimawr** [comment]
Thanks @cmacknz! I had looked at the `magefile.go` from Beats/Filebeat and it looks to be the same as the Elastic-Agent is doing in terms of parameters to `go-licence-detector` :/

Anyway, I'll give it another shot.
