### ISSUE TITLE
[V2]: Elastic Agent Install is broken.

### ISSUE THREAD

**Issue by aleksmaus** [elastic/elastic-agent#1125]
The Elastic Agent V2 install is broken and install seems to be hanging forever and never completes.

Was able to reproduce on the latest V2 branch on Linux build. 
The clean install never finishes, seems like hangs forever.

<img width="1942" alt="Screen Shot 2022-09-08 at 10 46 01 AM" src="https://user-images.githubusercontent.com/872351/189195957-976198ab-717c-47f2-a678-9527053e16c7.png">

The agent "enroll" works and runs from the terminal just fine.

**Comment by cmacknz** [comment]
PR is already up for this https://github.com/elastic/elastic-agent/pull/1331

**Comment by aleksmaus** [comment]
Closing as the PR is merged now.
