### ISSUE TITLE
Add Elastic Agent tags to events

### ISSUE THREAD

**Issue by drenze-athene** [elastic/elastic-agent#1128]
# Use Case

As a user, I would like to be able to utilize Elastic Agent tags in ingest pipelines (e.g., assign a tag to a field, if present) or search on it from within Kibana.

# Proposal

Send Elastic Agent tags as part of the event. The preferred method would be to send tags as part of the event metadata, so that they can be extracted and copied into the appropriate place in the event schema within the pipeline. An alternative would be to append them to the event's `tags:` field.

**Comment by drenze-athene** [comment]
This may be related to #76844, #78118.

**Comment by nimarezainia** [comment]
We plan to provide the ability to add tags and processors at the Policy level that would apply to all agents in that policy. https://github.com/elastic/elastic-agent-shipper/issues/160  this should address the requirement once available.

**Comment by drenze-athene** [comment]
> We plan to provide the ability to add tags and processors at the Policy level that would apply to all agents in that policy. [elastic/elastic-agent-shipper#160](https://github.com/elastic/elastic-agent-shipper/issues/160) this should address the requirement once available.

After thinking about this and coming back to it today, while the ability to add tags and processors at the policy level is similar (and welcome!), what I am requesting would be more like adding a `tags` key to the [agent provider](https://www.elastic.co/guide/en/fleet/master/agent-provider.html).

E.g.:

| Key | Type | Description |
|----|----|----|
| `agent.tags` | `list` | Tags assigned to current agent. |

The purpose of this would be to allow processing or conditional integrations based on tags assigned to specific agents.
