### ISSUE TITLE
Set default log level for gathering Elastic Agent logs for all agents in policy

### ISSUE THREAD

**Issue by renzedj** [elastic/elastic-agent#1129]
# Use Case

As a user, I would like to be able to set a default log level for gathering Elastic Agent log data from agents associated with a policy, so that I can limit the number of logs I collect from Agents (e.g., set log level to `warn` or `error`).

# Additional Information

Currently I can set the log level for Elastic Agent on an agent-by-agent basis, but I have no easy way to set it for all agents at once, nor can I set a default log level (e.g., `warn`), which means that as new agents are added, I have to set the log level for them, which is difficult to manage and creates the risk that some agents may get missed as they are added to policies. This may help mitigate the risk of writing logs to the `/opt` filesystem identified in #407.

**Comment by jlind23** [comment]
Closing this as done thanks to https://github.com/elastic/elastic-agent/pull/3090
