### ISSUE TITLE
Setting the log level via SETTINGS action can cause an agent to be re-enrolled

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#1137]
Currently, if you try to set the log level for the hosted "Elastic Cloud agent policy" agents via the UI, the entire agent will restart, causing a new agent to be enrolled and for the setting to not be applied to the new agent.

This means that is not possible to change the log level for the hosted agent via the UI, which especially problematic for clusters running APM in standalone mode, because the UI was the only way to do this.

I'm not yet sure if this is a regression or not.

**Comment by joshdover** [comment]
FYI @simitt

**Comment by joshdover** [comment]
We need to investigate why agent is restarting in the container to determine how to fix this.

**Comment by cmacknz** [comment]
I don't think the underlying [logp](https://github.com/elastic/elastic-agent-libs/tree/main/logp) logger the agent uses allows changing the log level at runtime.

**Comment by amirbenun** [comment]
I opened a pr that adds the `SetLevel` functionality on a global level.
https://github.com/elastic/elastic-agent-libs/pull/82

Let me know what you think @cmacknz

**Comment by cmacknz** [comment]
Thanks! We will need to integrate that change into the agent, and make a separate change to rely on the new `SetLevel` method to change the log level instead of restarting the agent.

**Comment by cmacknz** [comment]
The agent log level is changed in an action that triggers an agent restart: https://github.com/cmacknz/elastic-agent/blob/329cc5ef683f63d5b2466d43482277eed5ecae4d/internal/pkg/agent/application/pipeline/actions/handlers/handler_action_settings.go#L55-L67

I believe we would need to change the implementation of the agent's internal `SetLogLevel` to use the new `SetLevel` in elastic-agent-libs/logp and remove the call to `ReExec` to stop restarting the agent. It looks like the `LogLevel` is the only setting controlled by this action: https://github.com/cmacknz/elastic-agent/blob/329cc5ef683f63d5b2466d43482277eed5ecae4d/internal/pkg/fleetapi/action.go#L281-L286

@michalpristas does that sound right? I see your name in the commit log in this area of the code so hopefully you are familiar with it.

**Comment by michalpristas** [comment]
the problem here is that we cannot change log level without restarting an agent, restarting agent kicks restart of container resulting in a previous state of log level and maybe whole enroll machinery to be repeated.
only real fix to this one is making log level reloadable by changing logger used inside an agent. 
I believe the one used in fleet server can dynamically change it
I remember very vividly I created an issue but I cannot find it so it can be I just talked about it with ph.

**Comment by amitkanfer** [comment]
So what is the path forward @cmacknz ?

**Comment by jlind23** [comment]
Looking at @michalpristas it seems to be a more complex change than what we thought.

**Comment by michalpristas** [comment]
it is a tedious change and does not affect only the agent.
we should aim to unify loggers used across our stack (agent, fleet server and beats) as we currently use probably 3 different libraries
i believe the one used in fleet server is the best choice but this would require more thorough comparison. 
making some space for this in our plan would be great. we're dealing with this for a long time and have a lot of special cases for handling logger changes in agent specifically

**Comment by jlind23** [comment]
After discussing with @joshdover this one shouldn't be a high priority for now, better take time to work on other things.

**Comment by cmacknz** [comment]
For when we prioritize this again:

Amir's change in https://github.com/elastic/elastic-agent-libs/pull/82 should allow the log level to be changed dynamically for the logger used by Agent and Beats. 

We will need to update both Beats and Agent with https://github.com/elastic/elastic-agent-libs/pull/82, and then follow up with APM server and Endpoint to see if they already support dynamically changing the log level. When we stop restarting the agent due when the log level changes, we will also stop restarting the child processes that inherit their log level from the agent. See below. The child processes need to use dynamic log levels as well as far as I can tell.

https://github.com/elastic/elastic-agent/blob/a0a3ed1aae5436b720b8065199afc629fe8930d6/internal/pkg/agent/operation/operator.go#L394-L401

Unifying the loggers we use is a good idea but I think too much work to fold into this issue, certainly changing the Beats logger would not be a good use of time right now.

**Comment by simitt** [comment]
>and then follow up with APM server and Endpoint to see if they already support dynamically changing the log level. 

Currently the APM Server is using `logp.NewLogger` for creating a logger. Please keep us in the loop for any changes that are required aside of updating libbeat, once the libbeat changes are merged.

**Comment by cmacknz** [comment]
This was resolved as part of the agent V2 work in 8.6: https://github.com/elastic/elastic-agent/pull/1914

Adding support for dynamic log level changes in Beats is being tracked separately under https://github.com/elastic/beats/issues/34046 as a follow up.
