### ISSUE TITLE
Implement a sub-command to show or follow the Elastic Agent logs

### ISSUE THREAD

**Issue by ruflin** [elastic/elastic-agent#114]
Debugging Elastic Agent is currently not as easy as it should be. In case of issue, the right paths for the logs have to be found and read one by one. It would be very convenient if elastic agent would offer a command to get the logs and metrics.

To tail all the logs, something like the following would be useful:

```
elastic-agent logs -f
```

Maybe later support for filtering logs from only a specific process could be added. One step further would be, that on the fly the logging level could be changed.

The same is true for metrics. Would be nice of a snapshot of the metrics could be gathered with something like the following:

```
elastic-agent metrics
```

**Comment by cmacknz** [comment]
With the new unified log file we should be able to implement `elastic-agent logs -f`. This has annoyed me on many occasions now.

Getting the metrics might be a bit trickier but we can definitely do this for logs.
