### ISSUE TITLE
Fix `mage notice`

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#1141]
The `mage notice` command has never been finalised (probably due to the lack of time), but we have a make rule that replaces it for the time being.

This issue is about using the implementation present on https://github.com/elastic/elastic-agent-libs to avoid code duplication and fixing all related issues.

One attempt has already been made on https://github.com/elastic/elastic-agent/pull/1108, but due to time constraints, it was dropped in favour of the currently working make implementation.

**Comment by jlind23** [comment]
Mage notice has been removed in https://github.com/elastic/elastic-agent/pull/1108 hence closing this.
