### ISSUE TITLE
Report the status `message` field to Fleet Server checkins

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#1151]
We should report an agent's reason for being in the status it's in to Fleet Server rather than only relying on Agent logs. This will make it easier to debug why an agent is in a particular status.

Related changes need to be made to Fleet Server to save this state in the .fleet-agents index.

**Comment by joshdover** [comment]
@jen-huang It'd also be great to have this reported in Fleet's agent status telemetry in the UI. Maybe counts by unique message with some cap.

**Comment by juliaElastic** [comment]
@joshdover @jen-huang Is this issue intended to be fixed for 8.5? 
Does it require change in `elastic-agent` codebase? Maybe someone could help out who is familiar with this flow.

I noticed that for actions, there is already an error message saved in `.fleet-actions-results`, I'm not sure if there is already an error reason sent by agents to FS on ack.

**Comment by juliaElastic** [comment]
@joshdover can I use the existing `last_checkin_message` agent field for this, that was introduced for this `[feature](https://github.com/elastic/elasticsearch/issues/89574)`?

And to confirm, are we looking to store the `message` or `error.message` field from the agent logs?
The `message` field is not very specific, but could be more suitable for displaying on the UI.

Some examples:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/90178898/192815732-b18d2970-b043-442a-a5f7-8f6d06f1d4f4.png">

**Comment by joshdover** [comment]
Makes total sense, yes let's use that since v2 should be shipping in this release as well.

**Comment by simranvaseer-qasource** [comment]
Hi @juliaElastic,

We have created below **04** test cases for this feature.

- [C168347](https://elastic.testrail.io/index.php?/cases/view/168347)
- [C168348](https://elastic.testrail.io/index.php?/cases/view/168348)
- [C168349](https://elastic.testrail.io/index.php?/cases/view/168349)
- [C168350](https://elastic.testrail.io/index.php?/cases/view/168350)

Please let us know if we are missing anything.
Thanks

**Comment by simranvaseer-qasource** [comment]
Hi Team,

We have executed **04** testcases for this feature under our Fleet Test run at [Fleet Team 8.6 New features test plan](https://elastic.testrail.io/index.php?/plans/view/5072) and found that it's **working fine**.

Build Details:
```
Version: 8.6.0 BC5
BUILD: 58693
COMMIT: ed40c16ce9999cc47ad55c11bb097d2e443b31a6
Artifact link: https://staging.elastic.co/8.6.0-8cf9e954/summary-8.6.0.html
```

Below are the test cases.

- [T1872624](https://elastic.testrail.io/index.php?/tests/view/1872624&group_by=cases:section_id&group_order=asc&group_id=30789)
- [T1872625](https://elastic.testrail.io/index.php?/tests/view/1872625&group_by=cases:section_id&group_order=asc&group_id=30789)
- [T1872626](https://elastic.testrail.io/index.php?/tests/view/1872626&group_by=cases:section_id&group_order=asc&group_id=30789)
- [T1872627](https://elastic.testrail.io/index.php?/tests/view/1872627&group_by=cases:section_id&group_order=asc&group_id=30789)

Please let us know if we are missing anything.
Thanks
