### ISSUE TITLE
Revive the Fleet and Upgrade E2E tests

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1174]
The agent E2E tests have not been stable for a long time, which has made them ineffective as a quality check for agent PR and releases. The E2E tests no longer act as a gate for agent releases for this reason. 

Fixing all of the flaky E2E tests is too large of a task for a single issue, but to ensure we get some value from end to end tests we can restore the most valuable test suites and make them reliable on a reduced set of platforms as a start point.

The scope of this issue is to reduce the set of E2E tests triggered by agent builds to just the [Fleet Mode](https://github.com/elastic/e2e-testing/blob/main/e2e/_suites/fleet/features/fleet_mode.feature) and[ Upgrade Agent](https://github.com/elastic/e2e-testing/blob/main/e2e/_suites/fleet/features/upgrade_agent.feature) test suites and make them reliable when run on Ubuntu and Windows. The E2E test framework already supports custom test run profiles based on the repository that triggers them, see the existing profile for the agent [here](https://github.com/elastic/e2e-testing/blob/main/.ci/.e2e-tests-for-elastic-agent.yaml).

The work that needs to be done is also tracked in the following [issue](https://github.com/elastic/e2e-testing/issues/3053) created by the obs-robots team.

**Comment by joshdover** [comment]
I went aggressive and tried making a quick adjustment to the test matrix to turn off a bunch of tests and reduce the platforms tested to ubuntu and windows. If this is stable, we should merge it: https://github.com/elastic/e2e-testing/pull/3054

We should still use this time to revisit the tests that were disabled and see which are valuable enough to enable again. IMO the wide number of platforms we're testing is probably not very valuable and I'd be ok only running 1 of each platform (windows, linux, macos)

**Comment by jlind23** [comment]
Agree! A weekly job should be enough.

**Comment by cachedout** [comment]
@joshdover
@jlind23 
@cmacknz 

I pulled some quick stats to see what gains we might be making.

Here's the last 90 days with a marker showing the day after Josh's changes went in to heavily restrict the number of tests which are being run:

<img width="992" alt="Screenshot 2022-10-24 at 15 39 09" src="https://user-images.githubusercontent.com/111616/197540379-14efeb7f-9e97-4b29-998f-b4483e19be9d.png">

Also attached is a CSV showing the test failure _since_ Josh's changes. From here, it should be quite clear where resources should be directed in order to further stabilize things.

[E2E main test failures(1).csv](https://github.com/elastic/elastic-agent/files/9852130/E2E.main.test.failures.1.csv)

AFAIK, there is not any documentation on how to gather these stats. They can't go in a public repo, so I will create them elsewhere and folks can contact me privately for them.

**Comment by aleksmaus** [comment]
Having problems with ```create-stack```, fleet server setup fails, opened an issue:
https://github.com/elastic/e2e-testing/issues/3159

**Comment by joshdover** [comment]
+1 we also need to look at the Endpoint Automation Framework and see if extending that suite would make sense as well. I'd like to make a comparison of the suites against our requirements before we choose where to invest.

**Comment by AndersonQ** [comment]
This are my draft ideas for how to re-enable the e2e tests and the priority:

My take:
 - (Re)enable on for the branch feature-debug-e2e-tests the ci job, for a single platform, in the following order the tests:
   - Upgrade tests -> ensure it runs for the latest version: add 8.5, 8.6, 8.7-SNAPSHOT
   - Endpoint integration
   - System Integration
   - Linux Integration
   - Standalone mode

 - With the job enabled, find flaky tests and fix or remove them
 - Start adding more systems and Linux flavours as the tests become stable

 - Clean up / readability improvements:
   - a .go file for every .feature file, both in the same folder
   - under _suites/[suite-name]/*.go, .go files that are generic, shared code. No test code

 - Replace APM and Endpoint integration with a single feature (.feature file) ensuring the agent starts and stops all programs it can run
   - the agent starts with a policy containing everything it can run
   - remove the agent and ensure everything else was removed as well.
 - Create specific features for specific programs (eg. Endpoint Security)

it's on a notes file on my branch feature-debug-e2e-tests that gathers Josh's comment and add a wee more thoughts. This notes file is more a brain dump than anything else.

**Comment by joshdover** [comment]
> * (Re)enable on for the branch feature-debug-e2e-tests the ci job, for a single platform, in the following order the tests:

👍 from me on this. It should be separate from the main job so we can keep the main job as stable as possible and enable tests on that job over time as tests stabilize.

> * With the job enabled, find flaky tests and fix or remove them

What should the process for making this happen? How should we treat flaky and failing e2e tests in terms of priority/urgency?

> Clean up / readability improvements:
> 
>     * a .go file for every .feature file, both in the same folder
> 
>     * under _suites/[suite-name]/*.go, .go files that are generic, shared code. No test code

What do you think about removing Gherkin / feature files completely? It seems we could simplify development by making it easier to step through code and understand stack traces with that abstraction layer removed. At this point I don't think we're getting any value out of this, but I don't know the complexity involved in removing it.

> Replace APM and Endpoint integration with a single feature (.feature file) ensuring the agent starts and stops all programs it can run
> 
>     * the agent starts with a policy containing everything it can run
> 
>     * remove the agent and ensure everything else was removed as well.

I'm not sure I agree with this one. I want to make sure that when a test fails, it's fairly clear which team should own the failure and where to start investigating. If we have separate tests per-process I think this will be easier to accomplish. We could also have a single "kitchen sink" test like you described, but I'm not sure how valuable it will be.

What's your reasoning for having a single test?

> * Create specific features for specific programs (eg. Endpoint Security)

👍

**Comment by cachedout** [comment]
I would also like the chance to take a step back here and mention that we (@pazone @kuisathaverat and myself) are starting to discuss more concretely about the future of the E2E test suite. 

We would like to transition to a world where we only provide a framework for bootstrapping the stack infrastructure and individual product teams are responsible for using that framework within the structure of their own test frameworks to test features that they're developing.

Ideally, the end result is that we'd retire the existing E2E test suite entirely at some point in the next six months to a year.

I don't, as of today, have detailed timelines or even a proposal document to share on this. I've asked @pazone to have a document ready by mid-January for review, but I do want to start to prepare folks for this discussion, especially given the challenges posed by debugging and fixing the existing E2E test framework.

Apologies that this isn't a more well-formed comment, but I wanted to share how we're thinking about this in the long-run in case it helps shape some of the shorter-term priorities for the Fleet and Agent folks. Happy to chat more, as always.
