### ISSUE TITLE
[Fleet] Improve status reporting for Agents

### ISSUE THREAD

**Issue by nchaulet** [elastic/elastic-agent#120]
## Description

Currently we report a very basic status during checkin.
To allow us to give users more details on the status of their agents we want to send more complete policy status (Format is defined here https://github.com/elastic/kibana/issues/82298)

The status will be send during agent checkin:
* This will allow Fleet Kibana (and Fleet Server in the future) to update the agent saved object and allow user to search per agent status, input status
* A future coordinator process to take actions after a status change

## Questions

How we persist status in ES?
* I was thinking of updating the current agent SO with the actual status

Open question should the agent also send that data to ES directly? 
Is this already the case if status change are in the agent logs? if yes are this log data will be searchable

Pro:
* Allow to have agent status for agent non managed per Fleet
* Allow to have historical data of agent status.
* Have agent status when the connection Agent -> fleet is broken

@blakerouse @ruflin I am curious to have your thoughts here on how this can work with the future Fleet Server too

**Comment by jlind23** [comment]
Closing this as done, we implement a more detailed status reporting already.
cc @ycombinator
