### ISSUE TITLE
[APM/Fleet] Upgrade to 8.5.0-SNAPSHOT is failing on cloud

### ISSUE THREAD

**Issue by liza-mae** [elastic/elastic-agent#1238]
**Describe the bug**
Upgrade paths terminating with 8.5.0-SNAPSHOT are failing when API/Fleet is enabled.

**To Reproduce**
1. Create 8.4.2-SNAPSHOT instance 
2. Upgrade 8.5.0-SNAPSHOT 
3. Observe APM/Fleet does not come up

**Expected behavior**
It is expected upgrade path will work.  

**Debug logs**

Deployment:
https://admin.staging.foundit.no/deployments/3756fa5f360fd01ec5e54582c5404f4d

**Comment by cmacknz** [comment]
@kpollich do you recognize the Fleet error here?

**Comment by kpollich** [comment]
@cmacknz Yes - this error is throwing when a "hosted" policy (one with `is_managed: true`) has an update attempted. Seems like somewhere during setup we're attempting to update the `schema_version` field of the managed `Elastic Agent on Cloud` policy. Looks like a result of https://github.com/elastic/kibana/pull/137355 (cc @joeypoon). 

I thought we were handling this through this "migration service" here: https://github.com/elastic/kibana/blob/main/x-pack/plugins/fleet/server/services/setup/upgrade_agent_policy_schema_version.ts - but I don't actually see logic in here to update the `schema_version` field, so I'll keep investigating. 

@joeypoon could you also take a look here if you have some time? Seems like we should probably be "force updating" managed policies during this migration logic.

**Comment by liza-mae** [comment]
Thank you this is confirmed fixed with elastic/kibana#141109
