### ISSUE TITLE
Add a way to unenroll an Elastic Agent from the client side

### ISSUE THREAD

**Issue by jamiesmith** [elastic/elastic-agent#125]
**Describe the enhancement:**

Currently there's no way to unenroll an elastic-agent from the client side

**Describe a specific use case for the enhancement or feature:**

When running ephemeral instances (containers, for example) each can enroll, but when the container is stopped we end up with stranded offline instances in fleet, which then takes two commands per host on the Fleet screen (unenroll and force unenroll, because they never unenroll), for a total of 6 clicks, plus delays, for each host.  

If there were an `unenroll` subcommand for `./elastic-agent` it could be called in the container teardown

![image](https://user-images.githubusercontent.com/220994/93346535-15f19b80-f802-11ea-8c9e-5ff487b73fc2.png)

**Comment by jlind23** [comment]
Closing for now as it never was prioritized. Can be reopened later on if needed. cc @nimarezainia

**Comment by ulab** [comment]
I am a little flabbergasted, why an uninstall does not include an unenroll. There should at least be both options available.

**Comment by nimarezainia** [comment]
@ulab we would prefer to rely on our state machine to unenrol the agent from Fleet when the un-installation at the remote host has occurred. When uninstalled, the agent will miss checkins and transition to OFFLINE and INACTIVE and eventually removed. these changes have been implemented i the upcoming release.
