### ISSUE TITLE
V2: Add integration tests for the agent v2 control protocol

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1275]
There is an extensive set of unit tests for the control protocol defined in https://github.com/elastic/elastic-agent/blob/feature-arch-v2/pkg/component/runtime/manager_test.go that use a fake input interacting directly with the agent manager. These provide good coverage for the component and unit state transitions but bypass several layers of the agent (notably the gRPC server) that are involved in running a real input.

To ensure we have no gaps in our test coverage we we should implement integration tests of the v2 control protocol using a fake input binary communicating with the compiled agent binary. We should try to cover the test cases below, which include a basic functional test of an input in normal operation and several important error cases.

- [ ] The input process starts normally, checks in, processes at least one action, acknowledges it, and then shuts down normally.
- [ ] The input process exits unexpectedly. The agent should restart the input and recover it to a healthy state.
- [ ] The agent process restarts unexpectedly. The input process should exit and a new input process instance should start when the agent restarts.
- [ ] The input process attempts to connect to the agent using an invalid certificate or TLS configuration. The agent should refuse the connection and log an obvious error about an unauthenticated connection attempt.

**Comment by cmacknz** [comment]
Relates to https://github.com/elastic/elastic-agent/issues/56

**Comment by cmacknz** [comment]
We can use https://github.com/elastic/ingest-dev/issues/977 as prior art for how to set this up. That approach uses containers, but we do not necessarily need containers for these tests. We could just start and control the binaries directly.

**Comment by cmacknz** [comment]
This may overlap with https://github.com/elastic/elastic-agent/issues/1272 in terms of deciding how the integration tests will be setup and run.

**Comment by cmacknz** [comment]
Much of this is already unit tested in https://github.com/elastic/elastic-agent/blob/feature-arch-v2/pkg/component/runtime/manager_test.go. I am going to re-scope this to just writing integration tests using the agent process for a few key scenarios, with most of the coverage living in the existing manager tests.

**Comment by jlind23** [comment]
@cmacknz this task was a tech def, can we consider this as done and ready to be worked on?

**Comment by cmacknz** [comment]
Technical definition complete, added to sprint 2.

**Comment by blakerouse** [comment]
This was completed, the unit tests communicate with a real binary over the real GRPC protocol.
