### ISSUE TITLE
[Elastic Agent] Overwrite global processor settings

### ISSUE THREAD

**Issue by kvch** [elastic/elastic-agent#129]
At the moment the logs of Filebeat started by the Agent is polluted with the debug logs of the `add_docker_metadata` processor. Example log line:
```
{"log.level":"error","@timestamp":"2020-07-23T16:00:00.372+0200","log.logger":"add_docker_metadata.docker","log.origin":{"file.name":"docker/watcher.go","file.line":320},"message":"Error watching for docker events: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?","ecs.version":"1.5.0"}
```

As I am not trying to test anything Docker related, these lines are distracting. Normally I just remove all processors when debugging Filebeat issues. However, as the Agent manages the configuration of these Filebeat instances, I do not have access to these global processors. Also, the `inspect` subcommand does not show if these processors are included or not. (Or at least I am not aware of any flags which could show it.) But based on the logs, these processors are enabled.

```shell
$ ./elastic-agent inspect output -o default -p filebeat
Action ID: 856251a6-a6f8-40e9-b71b-af54738c3280
[default] filebeat:
filebeat:
  inputs:
  - exclude_files:
    - .gz$
    id: logfile-postgresql.log
    index: logs-postgresql.log-default
    meta:
      package:
        name: postgresql
        version: 0.1.0
    multiline:
      match: after
      negate: true
      pattern: '^\d{4}-\d{2}-\d{2} '
    name: postgresql-1
    paths:
    - /home/n/go/src/github.com/elastic/beats/filebeat/module/postgresql/log/test/*.log
    processors:
    - add_fields:
        fields:
          ecs:
            version: 1.5.0
        target: ""
    - add_fields:
        fields:
          name: postgresql.log
          namespace: default
          type: logs
        target: dataset
    - add_fields:
        fields:
          dataset: postgresql.log
        target: event
    type: log
output:
  elasticsearch:
    api_key: {{key}}
    hosts:
    - {{outputhost}}
```

This not only impacts developers but users as well, as the logs of their agent managed Beat instances will be full of these docker/aws/etc. processor logs even if those are irrelevant.

**Comment by jlind23** [comment]
cc @ph should be included inside the V2 architecture.

**Comment by MichaelKatsoulis** [comment]
@jlind23 is this issue closed because the problem can now be tackled somehow or because it is decided that the global processors won't be overridden ?

The need for editing/configuring global settings of filebeat or metricbeat like processors ([add_cloud_metadata issue](https://github.com/elastic/beats/issues/31022)) or kubernetes provider is still around.

**Comment by cmacknz** [comment]
We have always had this tracked as part of the shipper project since that is the key dependency that allows us to implement this in an intuitive way https://github.com/elastic/elastic-agent-shipper/issues/160

**Comment by MichaelKatsoulis** [comment]
Thanks @cmacknz
