### ISSUE TITLE
[Agent] Remove dependencies on errwrap and go-multierror

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent#132]
In the Agent code we are using `errwrap` and `go-multierror`, theses dependencies are not necessary and we should remove them.

**Comment by jlind23** [comment]
@ph multierror is used magefile.go for example.
Thus I think this old issue should be closed.

**Comment by ph** [comment]
Agree, errwrap is an indirect dependencies of go-multierror.


```
 ❯ go mod why github.com/hashicorp/errwrap v1.0.0                                                                                                                           [10:24:51]
# github.com/hashicorp/errwrap
github.com/elastic/elastic-agent
github.com/hashicorp/go-multierror
github.com/hashicorp/errwrap
