### ISSUE TITLE
Agent fails to update new Fleet Server hosts if the first host fails

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#1328]
The Elastic Agent fails to update the fleet-server hosts when the first host is unreachable.

### Steps to Reproduce:

1. configure fleet-server hosts to have 2 hosts. The first must NOT work, the second should work. (Suggestion, make the first host be `https://localhost:8220`)
1. I enroll agent by using the working fleet-server URL, the second one
1. the agent successfully installs
2. The agent shows unhealthy on fleet-ui
3. in the agent logs, a error log like the following is found
```
{"log.level":"error","@timestamp":"2022-09-27T13:38:46.667Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":202},"message":"failed to dispatch actions, error: fail to communicate with updated API client hosts: Get \"https://localhost:8220/api/status?\": dial tcp 127.0.0.1:8220: connect: connection refused","ecs.version":"1.6.0"}
```

### Affected versions

- Version: 8.2.2, 8.6-SNAPSHOT (2b6cfdc0a764529633f55ea51cd3405232af3ebe)
- Operating System: all
- Discuss Forum URL: N/A

**Comment by amolnater-qasource** [comment]
Hi @AndersonQ 
We have revalidated this issue on 8.5.1 BC1 cloud-production environment and found it **working fine**.

**Steps:**
1. Added second fleet-server URL: `https://localhost:8220`.
2. Installed an agent using working fleet-server url.

**Observations:**
- No errors under agent Logs tab.
- Agent remains Healthy throughout.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/201897999-c646dc88-1675-42c9-b8da-08f2f4e74e5c.mp4

**Build details:**
BUILD: 57136
COMMIT: 87149bfd06f4fe41dbfa7e95461294e9dadfb1d8

Hence marking this issue as **QA:Validated**.

Please let us know if we are missing anything here.

Thanks
