### ISSUE TITLE
[Agent] How we could reduce the need for root privileges for beats.

### ISSUE THREAD

**Issue by elasticmachine** [elastic/elastic-agent#134]
*Original comment by @ph:*

The Agent starts the beats process with the same user as the agent process which means **root**. This is less than ideal if we want to lock down the process and reduce the risk.

TODO: 
Define stories

- Behavior of Metricbeat
- Behavior of Auditbeat
- Behavior of Packetbeat.

**Comment by jlind23** [comment]
Closing this as done now that there is an unprivileged Elastic Agent experience. Example on Mac: https://github.com/elastic/elastic-agent/issues/3867
