### ISSUE TITLE
Panic crash in reporter.go crashes in managed mode

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1340]
**Description:**
Hosted Fleet Server not available on Healthy deployment of 8.4.3 BC-1 when deployed from:
- https://cloud.elastic.co/
- https://staging.found.no/

**Screenshots:**

![15](https://user-images.githubusercontent.com/77374876/192687184-c67af28d-1a20-44b0-9b63-3468ca4b25b8.JPG)

![14](https://user-images.githubusercontent.com/77374876/192686765-08ecafa9-d68f-4054-94a5-eb70946b23ee.JPG)

**Comment by amolnater-qasource** [comment]
Hi Team
Thank you for looking into this.

We are now successfully able to setup 8.4.3 BC2 Kibana cloud environment.

**Screenshot:**
![image (1)](https://user-images.githubusercontent.com/77374876/192958586-545b7f39-5e13-4403-bc9d-5171e216129a.png)

Hence marking this as **QA:Validated**.

Thanks

**Comment by simranvaseer-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/149907&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=25985

Thanks
