### ISSUE TITLE
Create an integration test to ensure the agent can communicate with Fleet server

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1356]
## Issue

We need to create a basic integration test in the agent repository to ensure that the agent binary can start and communicate with fleet server.

## Suggested path

Likely the simplest test to write will be to start the agent, fleet-server and Elasticsearch and ensure that the agent can enroll and check-in. 
This will overlap somewhat with the functionality that is already in https://github.com/elastic/e2e-testing/blob/main/e2e/_suites/fleet/features/fleet_mode.feature, but having at least one test scenario that runs easily inside the agent repository will shorten the feedback loop when finding problems.

## Definition of done

- [ ] Test that Agent is able to enroll into Fleet
- [ ] Test that Agent is not missing its checkin
- [ ] The agent can execute and acknowledge an action returned from Fleet Server

**Comment by cmacknz** [comment]
We can complete https://github.com/elastic/elastic-agent/issues/1174 first to revive the existing end to end fleet mode test suite, and perhaps consider if the e2e tests are stable and convenient enough to work with to provide the necessary test coverage here.

**Comment by cmacknz** [comment]
I think we should include a sanity check that the agent can execute an action, doesn't really matter which one is used for the purposes of the test. The upgrade test technically covers this, but the upgrade action implementation is likely to diverge from the implementation of the other actions in the near future.

**Comment by cmacknz** [comment]
This is more or less a duplicate of https://github.com/elastic/elastic-agent/issues/2402 after reading both of them.

If that test can change the agent log level as part of its implementation we'll have proven action processing works, which was suggested here. https://github.com/elastic/elastic-agent/issues/2402#issuecomment-1496502376

@pierrehilbert I don't think we need both of these issues since they test the same thing, https://github.com/elastic/elastic-agent/issues/2402 has been in progress longer so it might be the one to keep.

**Comment by pierrehilbert** [comment]
Thanks for seeing this. I close this number to keep only https://github.com/elastic/elastic-agent/issues/2402
