### ISSUE TITLE
Add automated test coverage for service based components

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1357]
This work pairs with https://github.com/elastic/elastic-agent/issues/1069 and the implementation PR https://github.com/elastic/elastic-agent/pull/1087 to add support from running agent components as separate services.

Currently we only have unit test coverage for this functionality, but considering the importance and cross-platform nature of the feature we should also add integration or end to end tests ensuring the agent binary can start, supervise, and stop services on each major operating system. We should also try to test situations likely to cause problems: killing either the agent or the service it is supervising unexpectedly, uninstalling the agent service, uninstalling the supervised service, upgrading the agent with a supervised service, interrupting the upgrade, etc.

The simplest way to test this is to allow downloading the endpoint-security binary and adding it to the components directory when a service integration test is run ([PR discussion](https://github.com/elastic/elastic-agent/pull/2747#issuecomment-1576764434).

**Comment by cmacknz** [comment]
There appears to be an existing E2E test suite that installs endpoint security we could try to revive: https://github.com/elastic/e2e-testing/blob/main/e2e/_suites/fleet/features/endpoint_integration.feature

We could also consider using a trivial stub service that is guaranteed to always be well behaved so we don't have to debug endpoint failures in the tests. As an E2E test though, catching problems with endpoint is probably valuable considering the entire service management feature exists just for endpoint.

**Comment by cmacknz** [comment]
Bumping this to P1, we recently had a change that broke the service runtime because there are no tests with a real service. The original change in https://github.com/elastic/elastic-agent/pull/2845 resulted in endpoint being unable to start.

**Comment by jlind23** [comment]
Postponing this one for now and we will rather focus on https://github.com/elastic/elastic-agent/pull/2963

**Comment by cmacknz** [comment]
I think we can just close this it is covered by the PR you linked, which has a separate issue tracked for that specific test.
