### ISSUE TITLE
Add integration and unit test coverage for the Elastic agent upgrade process.

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1359]
We currently rely on manual testing and [end to end testing](https://github.com/elastic/e2e-testing/blob/main/e2e/_suites/fleet/features/upgrade_agent.feature) to find problems with the agent upgrade process. The feedback loop during develop from these tests is too slow, and they do not adequately test the various upgrade failure modes the agent can encounter in the field. Add a set of automated upgrade tests local to the agent repository that:

- [ ] Tests that the normal upgrade process can proceed without issues.
- [ ] Tests that the upgrade process can successfully roll back to the previous version when the newly installed agent version fails to start.
- [ ] Tests that the agent reliably restarts with the current version when an upgrade to a new version is interrupted unexpectedly.
- [ ] Tests that the upgrade process can detect corrupted or unsigned upgrade packages.
- [ ] Tests that the upgrade process either detects or automatically recovers from corrupted agent installations (missing directories, symlinks, files, etc.).

For reference the majority of the upgrade process is defined in https://github.com/elastic/elastic-agent/tree/main/internal/pkg/agent/application/upgrade.

**Comment by amitkanfer** [comment]
@pierrehilbert i've changed the priority of this one to P0

**Comment by pierrehilbert** [comment]
Part of it is already started by @blakerouse here: https://github.com/elastic/elastic-agent/issues/2176

**Comment by pierrehilbert** [comment]
Closing to have only one issue for upgrades: https://github.com/elastic/elastic-agent/issues/2176
