### ISSUE TITLE
Windows Agents goes to unhealthy state on installation with system Integration.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#1361]
**Kibana version:** 8.4.3 BC2 Kibana cloud environment

**Host OS:** WINDOWS 

**Build details:**
VERSION: 8.4.3 BC2
BUILD: 55572
COMMIT: 1ceb607762eaafa726c61d6eee5b95359142d4c4
Artifact link: https://staging.elastic.co/8.4.3-c9575cad/downloads/beats/elastic-agent/elastic-agent-8.4.3-windows-x86_64.zip

**Preconditions:**
1. 8.4.3 BC2 Kibana cloud environment should be available.
2. Windows agent v8.4.3 should be installed.

**Steps to reproduce:**
1. Navigate to Fleet> Create new Agent Policy .
2. Enroll windows agent with policy having system Integration.
3. Observe after 4-5 minutes agent went unhealthy.
4. Observe that no agent  logs available under agent->logs tabs

**Screenshot:**
![image](https://user-images.githubusercontent.com/101545338/192941495-39c2de43-3d2b-4573-9f35-4b104f49b7f0.png)

**Logs:**
[elastic-agent-diagnostics-2022-09-29T05-04-57Z-00.zip](https://github.com/elastic/elastic-agent/files/9671134/elastic-agent-diagnostics-2022-09-29T05-04-57Z-00.zip)

**Expected Result:**
Agent should come up with Healthy Status.

**Additional Notes:**
- This issue is not reproducible for MAC and Linux .tar agent.

**Comment by harshitgupta-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @jlind23

**Comment by jlind23** [comment]
@AndersonQ @fearful-symmetry @cmacknz can one of you take a look at this one? It seems to be a metricbeat_monitoring failure
`{"log.level":"error","@timestamp":"2022-09-29T05:04:55.073Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":204},"message":"failed to dispatch actions, error: operator: failed to execute step sc-run, error: 2 errors occurred:\n\t* \"metricbeat_monitoring\" failed to prepare monitor for \"Metricbeat\": failed to create a directory \"\": mkdir : The system cannot find the path specified.\n\t* \"metricbeat_monitoring\" failed to prepare monitor for \"Metricbeat\": failed to create a directory \"\": mkdir : The system cannot find the path specified.\n\n: 2 errors occurred:\n\t* \"metricbeat_monitoring\" failed to prepare monitor for \"Metricbeat\": failed to create a directory \"\": mkdir : The system cannot find the path specified.\n\t* \"metricbeat_monitoring\" failed to prepare monitor for \"Metricbeat\": failed to create a directory \"\": mkdir : The system cannot find the path specified.\n\n","ecs.version":"1.6.0"}
`

**Comment by AndersonQ** [comment]
I'm looking at it

**Comment by AndersonQ** [comment]
hey, could you look at this issue https://github.com/elastic/elastic-agent/issues/1361

Below are my findings, but I'm not sure about the expected behaviour, perhaps @michalpristas knows better.

The problem is [here](https://github.com/elastic/elastic-agent/blob/8.4/internal/pkg/core/monitoring/beats/sidecar_monitor.go#L105-L107):
 - `monitorDrop` returns `""`, then 
 - `SidecarMonitor.Prepare` calls `os.MkdirAll("", 0775)`, which breaks.

I don't know what is the expected behaviour, what is the expected drop here :/

**Comment by michalpristas** [comment]
looking at it behavior is incorrect, code should check for drop != ""
only handle IO when it returns some normal path. 
"" is a valid scenario for cases when metrics are not exposed using pipes/sockets

**Comment by michalpristas** [comment]
fix here: https://github.com/elastic/elastic-agent/pull/1371
fix is a simple guard on drop path.
drop path can be empty if metrics endpoint is published over
- network (possible if configured in a spec file)
- NamedPipe (default on windows)

**Comment by michalpristas** [comment]
Fix backported to 8.4

**Comment by simranvaseer-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/150195&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=35226
 
Thanks!

**Comment by amolnater-qasource** [comment]
Hi Team,

Currently agents gets temporarily Unhealthy on installation and then gets Healthy after sometime on latest 8.7.0 BC3.
This issue is being tracked under:
- https://github.com/elastic/elastic-agent/issues/2145

**Build details:**
8.7.0 BC3
BUILD: 60804
COMMIT: abbdcf43f4e89f6fc085360252514aed7c032b4b

Hence, we are marking this issue as QA:Validated.
Thanks
