### ISSUE TITLE
Enable download of Elastic Agent directly from the fleet server

### ISSUE THREAD

**Issue by aarju** [elastic/elastic-agent#137]
**Describe the enhancement:**
Provide a an API endpoint on the Fleet server where the appropriate versions of elastic agent can be directly downloaded. This URL should be static between Fleet versions so agent deployment scripts do not have to be updated every time the Elastic Stack is updated.

Example:
`GET https://fleetserver:443/api/fleet/installers` to retrieve a list of available installers
`GET https://fleetserver:443/api/fleet/installers/windows_x86_64.zip` to download the windows x86_64 installer package.

**Describe a specific use case for the enhancement or feature:**
When admins want to deploy Elastic Agent within an enterprise they need to create scripts to download and deploy the agent to all of their systems. At this time to do this they need to write their scripts to download the correct version from `artifacts.elastic.co`, but every time they update the fleet server they will need to update all of their deployment scripts to download the newer version of the installer. For example, the current version for windows is `https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.15.2-windows-x86_64.zip`, but when 7.15.3 or 7.16 is released all of their installer scripts will need to be updated.

**Comment by jlind23** [comment]
@aarju is this one still required now that we have [this](https://github.com/elastic/kibana/issues/100413)?
