### ISSUE TITLE
Support for custom fields in fleet integrations

### ISSUE THREAD

**Issue by jguay** [elastic/elastic-agent#138]
**Describe the enhancement:**
Currently as off 7.15, it is not supported for fleet integrations (beside custom logs) to customize ingest pipelines per [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/ingest.html#pipelines-for-fleet-elastic-agent)
Also using [logstash output](https://www.elastic.co/guide/en/fleet/7.15/logstash-output.html) is only supported with standalone agent 

Link to Github issues (if available):
* https://github.com/elastic/kibana/issues/121118
* https://github.com/elastic/elasticsearch/issues/61185

**Describe a specific use case for the enhancement or feature:**
Adding a custom field when using fleet integration is explicitly not supported, we would need to introduce and document a way to do this

**Comment by nimarezainia** [comment]
we plan to add processors globally which I believe would address this
