### ISSUE TITLE
Add automated test coverage for 8.4 to 8.5+ upgrades on MacOS

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1399]
We need to add automated test coverage for the changes in https://github.com/elastic/elastic-agent/pull/1392. The lack of test coverage for upgrades on Mac led to us finding out that upgrades from 8.4.x to 8.5.x were broken late in the testing cycle via manual QA.

The logical place to to add this test coverage is in the existing E2E upgrade test suite: https://github.com/elastic/e2e-testing/blob/main/e2e/_suites/fleet/features/upgrade_agent.feature

However it doesn't look like the E2E tests currently support running on Mac per the list of platforms defined here: https://github.com/elastic/e2e-testing/blob/main/.ci/.e2e-platforms.yaml. We would need to add support for Macs to the E2E test framework for this approach to work.

If we cannot get Mac support added to the E2E test framework in the near future, we should explore adding integration and unit tests for this upgrade path to the agent repository itself. There is support for MacOS in the agent repository's CI process, but it is currently disabled due to instability (an internal investigation was started in the internal elastic/ci repository): https://github.com/elastic/elastic-agent/blob/90c2c00beaf50c9ab11d048188bc210905c4cc1d/.ci/Jenkinsfile#L91-L96

In the event that we cannot get reliable support for Macs in the E2E tests, or CI, then just having a set of tests can be executed by developers and testers on a Mac still has value over the zero test coverage for this case we currently have.

- Relates https://github.com/elastic/e2e-testing/issues/2339

**Comment by cmacknz** [comment]
@cachedout is it possible to add support for Macs to the E2E test framework? If it is, is it likely they'll suffer from the same instability we see with the Orka Jenkins workers?

**Comment by cmacknz** [comment]
The E2E framework does not currently support Macs. We either need to wait for that, or cover this upgrade path in a different way.

**Comment by jlind23** [comment]
Closing this as the e2e testing framework does not exist anymore.
cc @ycombinator
