### ISSUE TITLE
Download proxy URL on install

### ISSUE THREAD

**Issue by CruzMarcio** [elastic/elastic-agent#1421]
Please add a command line argument to install and enroll that allows us to set the download.proxy_url setting. On our company the fleet and elasticsearch servers are internal so it does not need a proxy, only to download from artifacts.elastic.co. When using the current --proxy_url parameter it sets the proxy for all.

**Comment by cmacknz** [comment]
Fleet now allows configuring the download proxy directly in the UI. https://www.elastic.co/guide/en/fleet/current/fleet-agent-proxy-managed.html

This uncovered a bug in this functionality that was fixed in 8.12.2 https://github.com/elastic/elastic-agent/issues/4237
