### ISSUE TITLE
Fleet managed: enable debug mode 

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-agent#143]
Hi Team,

while investigating the root cause of https://github.com/elastic/integrations/issues/1566 , we confirmed that's really useful to enable debug logs for filebeat and metricbeat running as Docker containers (under CI). The ideal option would involve an extra property in policy to enable debug logging or at least a special Docker image ENV which can be hardcoded in system tests.

**Comment by oren-zohar** [comment]
The debug logging option is also crucial for cloudbeat. We are less concerned about log level per input and even a log level that's inherited from the agent log level / env var would be helpful. Maybe we can start with that and reiterate once we have a complete definition? 
I would happy to help with implementing some basic way of controlling the log level to speed things up.

**Comment by jlind23** [comment]
@oren-zohar starting with a global log level sounds good as a first step. If you give a first try at it let me know and i'll find someone to help you out if needed.

**Comment by jlind23** [comment]
Closing this as duplicate as it will be covered by [#3090](https://github.com/elastic/elastic-agent/pull/3090)
cc @ycombinator
