### ISSUE TITLE
[elastic-agent] managed apm-server doesn't know its elasticsearch cluster_uuid

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/elastic-agent#145]
When apm-server is managed by elastic-agent, it doesn't know its elasticsearch cluster_uuid, which is necessary for being properly displayed in the stack monitoring ui.

- Version: 7.15
- Operating System: Ubuntu 21.06
- Steps to Reproduce: 
1. Start elastic-agent with a config that spawns apm-server
2. Check the `/state` endpoint on the apm-server:
    ```
    $ curl -s --unix-socket /usr/share/elastic-agent/state/data/tmp/default/apm-server/apm-server.sock http:/state | jq .outputs
    {
      "elasticsearch": {
        "cluster_uuid": ""
      }
    }
    ```
Compare that to a standalone apm-server:

```
# curl -s http://localhost:5066/state | jq '.outputs.elasticsearch'
{
  "cluster_uuid": "JYUVz_CMSkaQvxV6xl4jPg"
}
```

**Comment by ruflin** [comment]
Lets close this issue. @jasonrhodes Can you take the lead on opening a new issue around the usage of cluster_uuid ?
