### ISSUE TITLE
Enhancement: password protection to allow/block the uninstall of Agent

### ISSUE THREAD

**Issue by jguay** [elastic/elastic-agent#1524]
**Describe the enhancement:**
At the moment, any local administrator can uninstall Elastic Agent. There is no built-in way to prevent uninstallation
**Describe a specific use case for the enhancement or feature:**
A password in the policy that would need to be provided for the uninstall of the agent (or any other solution)
Example: if part of the policy include Endpoint Security, we might not want users to be able to uninstall it without limit, even if the users have administrator privileges

**Comment by jguay** [comment]
@nimarezainia Yes the concern is Endpoint security (if this is easier to only implement for this part of the agent - as opposed to entire agent)

**Comment by athanatos64** [comment]
If Elastic Agent is not present (or if the service is stopped/disabled), then Endpoint Security service won't be able to send events to Elasticsearch/Logstash. This is a big concern as anyone with admin rights can simply uninstall the agent using CLI and poof your log forwarding and EDR protection is gone. No logs, no EDR, no security.

**Comment by ITSEC-Hescalona** [comment]
If you are facing a Human Ransonware operator or Human attacker, the first action it's remove security software them we need prevent this.

**Comment by oliver-creed** [comment]
this would be a useful feature is there any timescale for this?

**Comment by B1zanat0r** [comment]
Agreed, virtually every security product out there has some sort of tamper protection policy.  Either by check-in, password or MFA/One-time-code.

**Comment by amitkanfer** [comment]
@kevinlog can you please reference this issue to those in the security repo that will unblock the feature?

**Comment by kevinlog** [comment]
@dasansol92 - see @amitkanfer comment above.  Can you link this issue to our epic?

**Comment by mpg-13** [comment]
We're coming up on 6 months, any updates on this issue?

**Comment by joshdover** [comment]
Hi @mpg-13 implementation of this feature is in progress, but is being tracked and discussed mostly in private issues.

The first iteration of this feature will target protecting Endpoint from being removed without a password, and the next iteration will support protecting the entire Agent from being uninstalled. The first iteration is targeting 8.8, but we can't make any firm commitments until the implementation and testing has been completed.

**Comment by smnschneider** [comment]
Partially solved with 8.11. It is now possible to set tamper protection in agent policies with Elastic Defend integration.

**Comment by hblankers** [comment]
This is not a fix for the problem. Someone with Administrator privileges is still able to simply rename the agent and reboot the laptop. This will disable all the detection capabilities of Elastic Agent and Elastic Defend.

**Comment by nimarezainia** [comment]
tamper protection was introduced in 8.11 - closing this issue. Followup for the open comments.

**Comment by nimarezainia** [comment]
> This is not a fix for the problem. Someone with Administrator privileges is still able to simply rename the agent and reboot the laptop. This will disable all the detection capabilities of Elastic Agent and Elastic Defend.

FYI @roxana-gheorghe
