### ISSUE TITLE
Merge feature-arch-v2 into main

### ISSUE THREAD

**Issue by pierrehilbert** [elastic/elastic-agent#1526]
Having v2 control protocol progress merged into main branch.
First step will be to merge main into feature-arch-v2 to ensure that the current delta won't break anything.

Tasks:
- [x]  Merge main branch into feature-arch-v2
- [x]  Testing to validate that everything is still working
- [x]  Merge feature-arch-v2 branch into main October 26 at 9am PDT 
- [x]  Communicate to other teams that they can merge their PR

**Comment by cmacknz** [comment]
Related, we need to do the same thing for fleet-server: https://github.com/elastic/fleet-server/issues/2060

**Comment by blakerouse** [comment]
#1694 performs another merge.
