### ISSUE TITLE
AWS EKS Cluster name

### ISSUE THREAD

**Issue by ctgdevops** [elastic/elastic-agent#1553]
Running Elastic Agent in EKS, is there a way to get orchestrator.cluster.name?

**Comment by ctgdevops** [comment]
any help would be greatly appreciated.

**Comment by dmhank** [comment]
Having the same issue

**Comment by cmacknz** [comment]
@elastic/obs-cloudnative-monitoring

**Comment by ChrsMark** [comment]
Tracked at https://github.com/elastic/beats/issues/33081

**Comment by cmacknz** [comment]
Closing, tracked separately.

**Comment by dmhank** [comment]
@cmacknz could you share a link where this is being tracked seperatley?
