### ISSUE TITLE
Elastic-agent must be able to manage global variables within a beat

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent#163]
CC @ruflin @jen-huang @joshdover @jlind23 @masci 

# What's this about?

This is a result of me trying to deal with the bug in https://github.com/elastic/beats/pull/28546, where the problem stems for an inability to manage the global `hostfs` from within fleet.  I'm going to be summarizing from an email thread a bit here.

Right now, we have we have no real way for a user to set and update global variables within metricbeat from the fleet UI. In addition, the config system  that manages a beat config from fleet has no way to set or manage global variables. The `OnReload` callbacks that happen only impact config that happens from within a given module. **In addition** libbeat's management of global config and state is highly piecemeal, and not well-suited to clean remote management by something like elastic-agent. These are all interrelated problems, and whatever fix comes out of this needs to deal with all of these problems in some way.

# What do we need?

While there's a handful of use cases for management of global variables, the first and most immediate from a tech debt perspective is the `system.hostfs` variable that's used by various system components to specify an alternate root filesystem, in cases where a user wants to monitor a host system from within a container. Usage of this setting is spread across two metricbeat modules and libbeat, and will probably expand to other modules over time.

While I'm sure we could put something together in a week to fix `hostfs`, I'd like to approach this from a generic perspective, as this need is going to crop up in other areas over time, and we need a generic, scalable way of managing global state from fleet.

At minimum, it seems to me need the following:

- A UI element that sets variables at a Fleet Config Policy Level
- Some component that transmits this config to beats and applies it a global level
- Some component(s) in libbeat that are capable of updating global config variables from fleet inputs

The workaround in the above PR is to set the global variable from the `system` module init, which is not a great solution, but it's the only one I have, considering we just need the bug fixed in the short term.

# Analysis: What are the underlying issues?

When I was considering the requirements for a "proper" `hostfs` fix, I came up with a few requirements (copying here from an email):

- Must work under metricbeat's Initialization Scheme, as well as Fleet
- Must have an API that insures different components are using the HostFS in a consistent manner
- Any component that needs to know the HostFS must not not carry it around in global state, and instead receive it from an API
- It must be able to be updated with a new HostFS during runtime, and that updated value must be viewable to any downstream consumers

It struck me halfway through that I was sort of describing a key-value store. Right now we don't have anything like that in fleet as far as I'm aware, but I think we should consider something like it (at least from an API perspective), as the fundamental problem this issue is trying to address is that global config within beats is done in a rather piecemeal, distributed fashion without any central gatekeeping or management. This makes sense for a CLI-based application like metricbeat/filebeat, but not so much for a remotely managed component of multi-part system like the fleet stack. 

If we want a solution that's more elegant than "append a flag to the `exec` command, restart the process", we'll need to re-evaluate how we utilize libbeat from inside `elastic-agent`.  A meaningful, long-term solution to this problem will probably require a lot of refactoring and new code, but I think it's worth it, as large portions of libbeat were built around the assumption of an independent application that is configured locally via a CLI and yaml file. The longer we go without creating a codebase that treats remote management as a first-class use case, the more tech debt we're gonna build up.

The fleet `data streams -> metricbeat module` architecture we have in place now works because modules within a beat operate in a relatively independent, generic fashion, allowing something like the central management code to come along and re-implement the underlying interface. This isn't really the case with libbeat, as CLI flags, and init functions happen in different places. For example, when one excludes testing flags, there's about four different sub-libraries in libbeat that set and fetch their own CLI flags and (I imagine in some cases) merge them with yml values using their own logic.

There's a lot of potential overlapping solutions to this problem (the KV store, spinning up inputs as independent processes and not a global beat instance, plugging modules directly into elastic-agent without metricbeat, etc, etc), and I'm not pushing for one solution, but more using the KV-store idea as an illustration for the kinds of overarching, big-picture changes I think we should be looking at.

**Comment by jlind23** [comment]
After discussing with @cmacknz and having in mind the current design on the input as part of the Elastic V2, we decided to froze this work for now and rather keep it for later to see if V2 design will fixes these problems.

**Comment by cmacknz** [comment]
Yes, there is some valuable refactoring to be done here but completing all of the refactoring to solve this problem within metricbeat will take a long time. We are shifting focus to V2 implementation and we can hopefully address the root problem with V2 (via separate processes, and agent KV store, etc as suggested in the description).

**Comment by jlind23** [comment]
@cmacknz can this be closed as completed/outdated?

**Comment by therealdwright** [comment]
@cmacknz I have been in discussion with your support team about this exact issue for almost a month now. I think a solution is still required.

**Comment by belimawr** [comment]
That has recently come up on user case about Filebeat's performance where setting a global configuration, [`registry.flush`](https://www.elastic.co/docs/reference/beats/filebeat/configuration-general-options#_registry_flush), would help.

Definitely there is some need to set global options for a specific Beat/Component process, I'm just not sure how widespread it is.
