### ISSUE TITLE
Add changelog entries and update documentation for agent v2 changes that are visible to users

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1687]
We need to ensure we create changelog fragments (entries) for each v2 agent change that will be visible to or impact users. We should also update the agent and fleet documentation where necessary. For reference the agent documentation can be found in https://github.com/elastic/observability-docs/tree/main/docs/en/ingest-management/elastic-agent

1. Removal of the agent's ability to download binaries to execute at runtime. All binaries for every supported integration will be bundled with the agent by default. In 8.6 this increases the agent package size by the size of the auditbeat+packetbeat binaries on most platforms.
2. Changes to the agent's internal directory structure, with the addition of the components directory (and removal of the downloads directory) to contain binaries and their associated artifacts.
3. The switch to a unified agent log file including the logs from each process the agent starts, pending completion of https://github.com/elastic/elastic-agent/issues/221.
4. The updates to the elastic-agent inspect command to allow inspecting the state of the v2 runtime. Particularly the `elastic-agent inspect components` command.
5. The contents of the diagnostics bundle has changed. Explain the new format and note that the `--pprof` argument is removed; always on and provided.
6. Input IDs are now required for all inputs in standalone agent policies. Fleet adds IDs to agent policies automatically: https://github.com/elastic/elastic-agent/issues/1991

Checklist:

- [x] Prepare fragments
- [x] Update docs

**Comment by blakerouse** [comment]
Add 5

**Comment by jlind23** [comment]
@pierrehilbert @cmacknz who will be the one taking care of this change? You @pierrehilbert ?

**Comment by cmacknz** [comment]
The draft 8.6.0 release notes are at https://github.com/elastic/observability-docs/pull/2450. We will have to review them and ensure they only include changes for new features or bug fixes for bugs that existed prior to 8.6. We do not need to include changelog entries for bugs found during 8.6 testing that were never released.
