### ISSUE TITLE
Add support for downloading upgrade artifacts async from checkin/action workflow

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#1706]
We've observed some machines on slow connections downloading the upgrade artifact as slow as 50Kb/s. Our largest artifact size is on linux, clocking in at around 370MB. Because of this upgrades can constantly fail, even if the download could possibly complete if given enough time.

We cannot currently just increase the download timeout (currently 10 minutes) because while processing the upgrade action, Agent will stop checking in with Fleet Server and will not receive other types of actions or policy updates.

We should break the upgrade sequence into two steps to avoid this problem and be able to download the agent binary while the agent continues to check in and receive updates and then resume the upgrade once the download is complete.

Blocks:
- https://github.com/elastic/elastic-agent/pull/1666

**Comment by joshdover** [comment]
cc @cmacknz @pierrehilbert as discussed earlier this week. Dropping into the next sprint, but feel free to move.

**Comment by amitkanfer** [comment]
@jlind23 marking this as P1

**Comment by cmacknz** [comment]
@blakerouse did we address this as part of the changes in V2? The notes on https://github.com/elastic/elastic-agent/issues/2066 suggests we have.
