### ISSUE TITLE
Allow running the agent without sudo on MacOS for development

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1707]
Currently to run the agent on a Mac you need to run it with `sudo` to allow it to encrypt the local agent configuration and store the key in the system keychain. Attempting to run the agent without `sudo` will lead to the following error:

```sh
./elastic-agent run -e
Error: could not load agent info: could not update agent ID on disk store: storing generated agent id: could not get agent key: -25293: The user name or passphrase you entered is not correct.
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.5/fleet-troubleshooting.html
```

1. Improve the error message to more clearly indicate that the source of the problem. For example, `Error: could not load agent info. Did you forget to run the agent with sudo?: ...` would be an improvement.

3. Add a way to disable encrypting the agent configuration for convenience during development. Disabling encryption should be a build time configuration option. It should not be able to disable encryption at runtime via command line options or the agent configuration files. Do not use the existing `DEV=true` flag which is also used to include debug symbols. Use a separate build time configuration flag that is obvious and cannot be used mistakenly.

**Comment by cmacknz** [comment]
As part of this, it likely makes sense to add an `INSECURE=true` flag that 1. disabled local configuration encryption and 2. disables binary signature verification which is currently done by setting DEV=true.

We should create a separation between build time security features and true development features, like the inclusion of debug symbols. We may want to include debug symbols in internal release artifacts, but we never want to disable the security features for anything other than local development. We should make sure these concerns are separate, and obvious in the build invocation.

**Comment by jlind23** [comment]
@cmacknz @ycombinator now that we have the unprivileged agent UX, is this one still required or can it be closed?

**Comment by ycombinator** [comment]
I'm +1 to closing this unless @cmacknz thinks we still need it.

**Comment by cmacknz** [comment]
Yes, this was implemented https://github.com/cmacknz/elastic-agent/blob/de8e4e5de64194f8072f65f3826b3957ec6cfa00/internal/pkg/agent/cmd/run.go#L80
