### ISSUE TITLE
Agent diagnostics size can exceed the default gRPC maximum message size

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1715]
**Kibana version:**  8.6 Snapshot self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
VERSION: 8.6.0 Snapshot Kibana self-managed environment
BUILD: 58205
COMMIT: 8a34465b29c90aa996ff0c4c65a0539b392640f6
```

**Preconditions:**
1. 8.6 Snapshot self-managed environment should be available.
2. Fleet Server should be installed.

**Steps to reproduce:**
1. Navigate to cli location: `C:\Program Files\Elastic\Agent`.
2. Run command: `.\elastic-agent.exe diagnostics collect`.
3. Observe below error:
```
Error: failed to fetch component/unit diagnostics: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (17965059 vs. 4194304)
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.6/fleet-troubleshooting.html
```

**Expected Result:**
zip file should be created on running agent diagnostics collect command.

**Screenshots:**
![image](https://user-images.githubusercontent.com/77374876/201622856-2f353d16-96bf-4200-97a9-5949dadbd6cc.png)

![image](https://user-images.githubusercontent.com/77374876/201623215-945cb5c2-3ba3-4ac8-84b5-050482e2c54d.png)

**Agent Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/10001599/logs.zip)
[endpoint-000000.zip](https://github.com/elastic/elastic-agent/files/10001603/endpoint-000000.zip)

**Comment by karanbirsingh-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
Thanks, there were changes to how diagnostics work in 8.6 that can cause this.

Does this happen every time you run diagnostics? Or only some of the time? This is a real issue, I just want to know how often it occurs for prioritization.

**Comment by cmacknz** [comment]
@pierrehilbert we will need an owner for this in the current sprint.

**Comment by amitkanfer** [comment]
@cmacknz any idea what's the proposed solution here?
Do not use gRPC? split the file into chunks?

**Comment by cmacknz** [comment]
It depends :) The simplest option is to just increase the max message size in the agent from the default 4MB using https://pkg.go.dev/google.golang.org/grpc#MaxMsgSize

We included significantly more information in diagnostics by default in v2, so we could just remove some of it to help this as well. We collect all profile types by default now, while previously that was optional.

Neither of those guarantee this won't happen again, so probably chunking or introducing compression on the wire are better options. We made diagnostics more flexible by allowing developers to include whatever they want from their inputs, but 

I would want @blakerouse's opinion on the best next step once he is back next week. If we confirm this is happening every time in v2 I can just bump up the message size limit as a short term fix.

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 

Thank you for looking into this.
>Does this happen every time you run diagnostics? Or only some of the time?

We have observed this issue every time reproducible while running `elastic-agent diagnostics collect` command.
Further, we have revalidated this today on latest self-managed 8.6 kibana and had same error on running diagnostics command.

**Build details:**
```
VERSION: 8.6.0 Snapshot Kibana self-managed environment
BUILD: 58242
COMMIT: 2e04dac8367f95a986ed0ee32fd030bb3f6d5d0f
```

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/201853835-3280408a-25b0-45ae-87c6-3f3acc93ec03.JPG)

Please let us know if anything else is required from our end.
Thanks

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.6.0 BC1 self-managed kibana environment and found this issue **still reproducible**.

**Observations:**
- Error is observed in cli on running `elastic-agent diagnostics collect` command. 

**Screenshots:**
 
![8](https://user-images.githubusercontent.com/77374876/202654590-c0e90c23-6db9-49a6-8d40-75f8d9aad96f.JPG)

**Agent Logs:**
[logs.zip](https://github.com/elastic/fleet-server/files/10039456/logs.zip)

**elastic-agent.yml:**
[elastic-agent.zip](https://github.com/elastic/fleet-server/files/10039458/elastic-agent.zip)

**Build details:**
VERSION: 8.6.0
BUILD: 58392
COMMIT: 50a7feb0a5eb068d3acccc49c83b9ccb6db6734f

Please let us know if anything else is required from our end.
Thanks

**Comment by michalpristas** [comment]
@cmacknz what about making this configurable? so in case our default is not sufficient we have a way around it.

**Comment by cmacknz** [comment]
We could make it configurable with https://pkg.go.dev/google.golang.org/grpc#MaxMsgSize and default it to a larger number (15 MB?) as a quick work around.

We should really find a way to make this problem impossible in the future though.

**Comment by cmacknz** [comment]
Let's go with the short term fix of increasing the limit and then work out a better long term fix afterwards.

**Comment by cmacknz** [comment]
I get the same result after running `elastic-agent diagnostics collect` on my M1 Mac with the system integration and Elastic defend installed:

```
sudo elastic-agent diagnostics collect
Error: failed to fetch component/unit diagnostics: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (10640069 vs. 4194304)
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.5/fleet-troubleshooting.html
```

We may need to pick a very large number to avoid this problem initially, 15 MB may not be enough. 

@michalpristas I suspect the number of installed integrations affects the size of the resulting diagnostics bundle, primarily because of the profiles that are now collected by default. If we install an integration that starts one of each process we may be able to get an idea of the maximum diagnostics bundle size. 

We can also consider disabling some or all of the profile collection as I suspect this is probably the root cause, getting logs and configuration reliably is much more important.

**Comment by jlind23** [comment]
> We can also consider disabling some or all of the profile collection as I suspect this is probably the root cause, getting logs and configuration reliably is much more important.

I would rather improve the size limit instead of removing potential important informations.

**Comment by blakerouse** [comment]
I believe the proper fix here is to chunk the responses and change the diagnostic GRPC service to a streaming response where it can be chunked. I don’t think we should do any compression client side of the GRPC as that will add requirements for clients to import some compression libraries that the implementation of the input doesn’t natively even use. 

I will look at adjusting the protocol file, we also should support a single file being larger than the 4Mb. So we should handle that properly in the fix. 

We will never know what is large enough to set as the limit, and making users have to adjust limits provides for a bad experience. It should just work.

**Comment by amitkanfer** [comment]
> We will never know what is large enough to set as the limit, and making users have to adjust limits provides for a bad experience. It should just work.

++++++++

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.6 BC4 kibana cloud environment and found it **fixed** now.

**Observations:**
- zip file is created on running agent diagnostics collect command.

**Build details:**
BUILD: 58612
COMMIT: 218162f282314db5b3833c84752dd24395949b3f

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/205065643-9a5973d1-5ee4-41f8-bfde-652f281b06a2.JPG)


Hence, we are marking this issue as **QA:Validated**.
Thanks
