### ISSUE TITLE
Unreliable Administrator detection on windows

### ISSUE THREAD

**Issue by michalpristas** [elastic/elastic-agent#1722]
Currently we detect administrator by checking for `Local System` (`NT AUTHORITY/SYSTEM`) username.
for this we query golangs `user.Current()` this implementation does way more than we need and is buggy. 

We already have many escalations complaining about user profile not found

We have 2 options here:

**Option 1**
Copy implementation of `user.Current` and use just the minimal set of operations/syscalls.
Especially avoid `processToken.GetUserProfileDirectory()` call

**Option 2**
retrieve token and check for admin rights there
something similar to this: https://github.com/golang/go/issues/28804#issuecomment-505326268

choice i leave up to person dealing with this bug

**Comment by pierrehilbert** [comment]
@leehinman keep me honest here but https://github.com/elastic/elastic-agent/pull/3988 is fixing this right?

**Comment by leehinman** [comment]
> @leehinman keep me honest here but #3988 is fixing this right?

Yes

**Comment by pierrehilbert** [comment]
Thx for the confirmation, closing this then.
