### ISSUE TITLE
[Fleet] `fleet.proxy_url` change in the policy is not reloaded

### ISSUE THREAD

**Issue by nchaulet** [elastic/elastic-agent#1728]
## Description 

Related to https://github.com/elastic/kibana/issues/140533 

In Fleet UI we will allow user to change the proxy used for an agent (for the data output, and for the Fleet server connection)

Looks like the agent is not using the new proxy if it's passed after the enrollment.

Related code:
https://github.com/elastic/elastic-agent/blob/0a86c516d86327a4edbe9019126b46a3347fda55/internal/pkg/agent/cmd/enroll_cmd.go#L139

**Comment by joshdover** [comment]
@nimarezainia should we be shipping this feature in beta without this working? This is a pretty big limitation since it means agent can't update it's settings. At the very least this should be documented in the UI as a current limitation, but I'd prefer we hide it completely if we can't get this fixed for 8.6.

**Comment by joshdover** [comment]
cc @jlind23

**Comment by nchaulet** [comment]
@joshdover the proxy feature is not available in Kibana in 8.6 it's been only merged in 8.7 where I hope we get this fixed.

**Comment by jlind23** [comment]
@pierrehilbert Would you be able to find an owner for this?

**Comment by pierrehilbert** [comment]
Currently it's more like a stretch goal for the current sprint. 
We will have a owner for next sprint for sure but not guarantee for this one.

**Comment by joshdover** [comment]
@nchaulet don't we have a similar issue with `fleet.ssl.certificate_authorities` that we support setting from the UI today?
