### ISSUE TITLE
Remote debugger for Elastic-agent

### ISSUE THREAD

**Issue by gsantoro** [elastic/elastic-agent#1750]
Similarly to what we have done in beats at [beats remote-debugger](https://github.com/elastic/beats/pull/31748) we should enable Elastic-agent developers to use an IDE to remote debug Elastic-agent running inside a pod on Kubernetes.

**Comment by AndersonQ** [comment]
Well apart from perhaps a specific docker file or tutorial for VS Code, the agent can be built for debug, just pass `DEV=true` when building it with mage. There is also a [guide](https://github.com/elastic/ingest-dev/blob/main/elastic-agent/dev-guide/guides/debugging-elastic-agent.md) I wrote on how to remote debug the agent. The only thing that isn't there is specific instructions for Kubernetes. 

Is it you're talking about or something else?

**Comment by gsantoro** [comment]
Sorry I forgot to add all the other PRs linked to this topic. Here they are:
- https://github.com/elastic/beats/pull/32326
- https://github.com/elastic/beats/pull/32607
- https://github.com/elastic/beats/pull/32649

In short, it's not just a docker image (with delve debugger), but also a k8s manifest, Tiltfile (to automate the hot reloading). 

I don't think the hot reloading feature is feasible in elastic-agent though. In filebeat/metricbeat recompiling the code takes a couple of seconds so you can hot reload the k8s container when the code changes in real time. With elastic-agent it takes a couple of minutes instead.

**Comment by gsantoro** [comment]
@AndersonQ I haven't managed to build the elastic-agent yet. I get the following errors

```bash
17:06:37 › DEV=true SNAPSHOT=true EXTERNAL=true PLATFORMS='linux/arm64' PACKAGES='tar.gz' mage -v  clean package
Running target: Clean
Running target: Package
WARN[0000] The Elastic artifacts API is not available yet  artifact=auditbeat artifactName=auditbeat-8.7.0-SNAPSHOT-linux-arm64.tar.gz elapsedTime=618.829583ms error="GET request failed with 404" retry=1 statusEndpoint="https://artifacts-api.elastic.co/v1/search/8.7.0-SNAPSHOT/auditbeat?x-elastic-no-kpi=true" version=8.7.0-SNAPSHOT
WARN[0001] The Elastic artifacts API is not available yet  artifact=auditbeat artifactName=auditbeat-8.7.0-SNAPSHOT-linux-arm64.tar.gz elapsedTime=1.286594125s error="GET request failed with 404" retry=2 statusEndpoint="https://artifacts-api.elastic.co/v1/search/8.7.0-SNAPSHOT/auditbeat?x-elastic-no-kpi=true" version=8.7.0-SNAPSHOT
```

**Comment by AndersonQ** [comment]
@gsantoro it's because the 8.7 artefacts aren't there yet. if you have the beats cloned on your machine and in the same level as the elastic-agent folder, you can set `EXTERNAL=false` so the agent will compile the beats instead of downloading them

**Comment by gsantoro** [comment]
@AndersonQ that's the plan but I also realised that the docker image in elastic agent contains more than 1 binary. I'll have a look and keep you posted.

**Comment by AndersonQ** [comment]
If you need any help, let me know :)

**Comment by gsantoro** [comment]
@AndersonQ I'm planning on working on this issue https://github.com/elastic/observability-dev/issues/2457 during the OnWeek. If proven right, it should be a simpler solution to using Tilt

**Comment by gsantoro** [comment]
@AndersonQ I have a working version of the remote debugger for elastic-agent running on a local k8s cluster on my laptop. I managed to reduce the building time from 8 minutes to 3 minutes with the steps from https://github.com/elastic/elastic-agent/issues/2426.

For more info contact me or if I'm not available @gizas
