### ISSUE TITLE
V2: V1 monitoring is unconditionally enabled during fleet server bootstrap 

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1761]
The V1 monitoring flag is enabled by default (see [here](https://github.com/elastic/elastic-agent/blob/67021cfc1b66136e42a1570c559f5da4f11f68fe/internal/pkg/agent/configuration/settings.go#L39)), even during fleet server bootstrap. 

In particular, in ESS during fleet server bootstrap none of the agent monitoring settings are configured so it uses the default setting of enabled with a default output of "localhost:9200" (see the [fleet server bootstrap config](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/application/fleet_server_bootstrap.go#L34)). This leads to confusing messages in the logs about the agent trying to connect to `localhost:9200`.

We should not enable monitoring during fleet server bootstrap.

See related discussion in https://github.com/elastic/elastic-agent/issues/1731#issuecomment-1320965164 where determining the root cause of the connection attempts to `localhost:9200` took significant time.

**Comment by michalpristas** [comment]
i agree with bootstrap but are you sure we should disable monitoring by default? 
it would mean that any user running standalone would need to enable it in a config to get the best experience and see agent logs and metrics in the dashboards.

**Comment by cmacknz** [comment]
Agreed, I believe I wrote this too quickly. Monitoring can be on by default, except during Fleet server bootstrap.
