### ISSUE TITLE
Support RHEL 9 / Alma 9 OSs

### ISSUE THREAD

**Issue by a03nikki** [elastic/elastic-agent#1803]
**Describe the enhancement:**

The [support matrix](https://www.elastic.co/support/matrix#show_compatibility), does not include RHEL 9 or Alma 9.  Please include and support these

**Describe a specific use case for the enhancement or feature:**

[RHEL 9](https://www.redhat.com/en/blog/hot-presses-red-hat-enterprise-linux-9) is the latest [Red Hat Enterprise Linux](https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux) version.  Users are starting to have it deployed in their environments as it was released in May 2022.

[Alma 9](https://almalinux.org/blog/almalinux-9-now-available/) is the latest [Alma Linux](https://almalinux.org/) which was also released in May 2022.

Users who already using Elastic Agent on RHEL 8 or Alma 8 would like to continue to do so when they upgrade their operating systems (OSs).

**Comment by nimarezainia** [comment]
Alma Linux 9 supported in 8.10
