### ISSUE TITLE
V2: Allow easily filtering only the agent logs from the combined agent log file

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1810]
Comment originally made here https://github.com/elastic/elastic-agent/pull/1702#issuecomment-1329694585

After https://github.com/elastic/elastic-agent/issues/221 the spawned components contain message fields to easily allow separating them out when analyzing logs locally:

```json
"component":{"binary":"metricbeat","dataset":"elastic_agent.http_metrics_monitoring","id":"http/metrics-monitoring","type":"http/metrics"},"log.origin":{"file.line":721,"file.name":"instance/beat.go"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

For example we have `component":{"binary":"metricbeat","dataset":"elastic_agent.http_metrics_monitoring","id":"http/metrics-monitoring","type":"http/metrics"}` and `"service.name":"metricbeat"` to allow looking at the monitoring metricbeat logs only.

We are missing these with logs coming from the agent itself:

```json
{"log.level":"info","@timestamp":"2022-11-28T19:59:12.045Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":645},"message":"Updating running component model","ecs.version":"1.6.0"}
```

We should add at least `"service.name":"agent"` to allow filtering for agent specific logs easily e.g. being able to do `rg '"service.name":"agent"'` locally will save a lot of time during SDH analysis. The agent itself isn't a component so it makes sense for those fields to be missing.

**Comment by michalpristas** [comment]
closing as #2044 went in
