### ISSUE TITLE
[Fleet]: No data for added integration under Data Stream for Standalone agent.

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/elastic-agent#1818]
**Kibana version:**  8.6 BC3 Kibana cloud environment 

**Host OS and Browser version:** All, All 

**Build details:** 

``` 
VERSION: 8.6 BC3
Build: 58485
COMMIT: b52b34c2ff5216c395bd49c5fbc97744b646f34d
```

**Preconditions:**
1. 8.6 BC3 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Add integration to the policy say' `Nginx`.
3. Install standalone agent.
4. Navigate to Data stream tab.
5. Observe no data for added integration for Standalone agent.

**Expected Result:**
- Data for added integration under Data Stream for Standalone agent.

**What is working fine:**
- Data for predefined integration (i.e System and elastic-agent) are available under Data Stream tab.

**Screenshot:**
What is not working fine.
![Untitled](https://user-images.githubusercontent.com/102019374/204459863-1b51583a-f2c9-41c9-87d5-8854f8c15750.png)
![image](https://user-images.githubusercontent.com/102019374/204459942-fab5dbc6-66cd-49c5-9db4-5f5e3690ffe3.png)

What is working fine:
![image](https://user-images.githubusercontent.com/102019374/204459659-a0975532-6c32-437f-b708-5acac4a681cc.png)

**elastic-agent.yml:**
[elastic-agent.zip](https://github.com/elastic/elastic-agent/files/10110493/elastic-agent.zip)

**Comment by dikshachauhan-qasource** [comment]
Secondary review is done

**Comment by cmacknz** [comment]
Can you provide agent logs? I only see the agent YAML configuration attached.

**Comment by simranvaseer-qasource** [comment]
Hi @cmacknz 

Below are the LOGS and YML configuration attached.

- **elastic-agent.yml:**
[elastic-agent.zip](https://github.com/elastic/elastic-agent/files/10119773/elastic-agent.zip)

- **Elastic-agent Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/10119808/logs.zip)

Please let us know if anything else is missing from our end.
Thanks

**Comment by cmacknz** [comment]
Thanks. This looks the same as https://github.com/elastic/elastic-agent/issues/1822#issuecomment-1331846805 and should hopefully be fixed now.

Have you retested it already?

**Comment by simranvaseer-qasource** [comment]
Hi @cmacknz 

We have revalidated this issue on latest 8.6 BC4 kibana Cloud environment and found it **fixed**.

- Data for added integration is available under Data Stream for Standalone agent.

**Build Details:**
```
BUILD: 58612
COMMIT: 218162f282314db5b3833c84752dd24395949b3f
Artifacts: https://staging.elastic.co/8.6.0-0f9567fc/summary-8.6.0.html
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/102019374/204977808-f6ded2c5-c38e-4000-8d1e-757b1656927a.png)

Hence, marking this issue as QA:Validated and closing too.
Thanks.
