### ISSUE TITLE
Agents get unhealthy on adding any integration(Nginx/Kafka) to the agent policy.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#1822]
**Kibana version:**  8.6 BC3 kibana cloud environment

**Host OS and Browser version:** Linux & MAC, All
- Windows is already Unhealthy with System integration.

**Build details:**
```
VERSION: 8.6.0 BC3 Kibana cloud environment
BUILD: 58560
COMMIT: d4567dc2eaa4f59503c1822e1f10bf0292b97066
Artifact Link: https://staging.elastic.co/8.6.0-94db6bc6/summary-8.6.0.html#elastic-agent
```

**Preconditions:**
1. 8.6 BC3 kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet tab.
2. Install MAC/Linux agents with Agent policy and observe agents are Healthy.
3. Add any integration say nginx/kafka to the agent policy.
4. Observe agent goes unhealthy on adding these integrations.

**Note:**
- Even on removing System integration the agents remain Unhealthy.

**Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/10111423/logs.zip)

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/204472469-4b731dfe-db3d-41dd-9279-bc7f736501d7.JPG)
![2](https://user-images.githubusercontent.com/77374876/204472482-cb0fcc84-ab14-4c91-8d36-318171e22eaf.JPG)
![6](https://user-images.githubusercontent.com/77374876/204472490-3fb6d21a-51bb-4765-aa9e-bdd61d2baf0a.JPG)

**Expected Result:**
Agents should remain Healthy on adding any integration to the agent policy.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
I can also see the log input started for the nginx integration exiting but I'm not sure why:

```json
{"log.level":"info","@timestamp":"2022-11-28T12:10:46.112Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":325},"message":"Existing component state changed","component":{"id":"log-default","state":"Failed","message":"Failed: pid '786' exited with code '0'","inputs":[{"id":"log-default-logfile-system-cc01eb73-37e1-4c29-b5ac-3bde79b28b82","state":"Failed","message":"Failed: pid '786' exited with code '0'"},{"id":"log-default-logfile-nginx-0a6b2b4d-e92e-47fa-8c7a-df89e82d3551","state":"Failed","message":"Failed: pid '786' exited with code '0'"}],"output":{"id":"log-default","state":"Failed","message":"Failed: pid '786' exited with code '0'"}},"ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment]
I see the kafka and nginx units starting multiple times. Possibly this is caused by https://github.com/elastic/elastic-agent/issues/1738

**Comment by cmacknz** [comment]
We are also missing the Kafka metric input type. Fix tracked in https://github.com/elastic/elastic-agent/issues/1828.

**Comment by cmacknz** [comment]
The NGINX and Kafka integrations should be fixed in the next 8.6.0 snapshot and BC (scheduled to be built today Nov 29th).

**Comment by amolnater-qasource** [comment]
Hi @cmacknz
We have revalidated this issue on latest 8.6 BC4 Kibana cloud-staging environment and found **it fixed**.

**Observations:**
- Agents remains Healthy on adding any integration to the agent policy.

**Build details:**
BUILD: 58612
COMMIT: 218162f282314db5b3833c84752dd24395949b3f

**Agent logs:**
[elastic-agent-diagnostics-2022-11-30T08-38-40Z-00.zip](https://github.com/elastic/elastic-agent/files/10121234/elastic-agent-diagnostics-2022-11-30T08-38-40Z-00.zip)

**Screenshots:**
![6](https://user-images.githubusercontent.com/77374876/204748864-4ab730cb-78b8-415e-bbca-2ac511aca37f.JPG)

![7](https://user-images.githubusercontent.com/77374876/204749206-09684511-0451-426d-8b1b-c6aef4e62023.JPG)

Hence we are **closing** this issue and marking it as **QA:Validated**.
Thanks

**Comment by prachigupta-qasource** [comment]
### `Bug Conversion:`

We have updated **02 testcases** for this scenario in our fleet test suite at:
  - **Nginx:**
    - https://elastic.testrail.io/index.php?/cases/view/15902
  - **Kafka:**
    - https://elastic.testrail.io/index.php?/cases/view/15897

Thanks!
