### ISSUE TITLE
Changing the agent log level does not update running beats

### ISSUE THREAD

**Issue by oren-zohar** [elastic/elastic-agent#1896]
**Description**
When deploying the latest BC5 agent and trying to change the log level using the logs tab on the fleet page, it seems like the agent does not update its running beats log level.

**Expected Behavior**
Agent log level should propagate to other beats, and if I'm not mistaken I would expect them to restart, which I also didn't see (not 100% sure)

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/85433724/205964028-3a35ad0d-8b66-4390-9652-0c36b906d2eb.png">
<img width="903" alt="image" src="https://user-images.githubusercontent.com/85433724/205964037-c96a8b94-e88b-4750-88c5-b0bc19a3718a.png">
<img width="246" alt="image" src="https://user-images.githubusercontent.com/85433724/205964063-f830a263-edde-453b-b706-69fe7f312a8f.png">

For confirmed bugs, please report:
- Version: 8.6.0 [BC5](https://github.com/elastic/elastic-agent/commits/7b1dc64c917b579652739f970b016f98cd1c8899) 
- Operating System: Linux
- Discuss Forum URL: 
- Steps to Reproduce:
1. Deploy the latest 8.6.0 stack (I've used cloud)
2. Deploy agent over ec2 as a daemonset (for example KSPM integration)
3. Go to the agent log tab in the fleet UI 
4. Change the log level and apply

**Comment by cmacknz** [comment]
@blakerouse or @michalpristas any ideas why this would have stopped working in V2?

**Comment by oren-zohar** [comment]
@cmacknz we used this feature many times and it definitely affected the type of logs that were presented in the logs tab in the fleet UI, cloudbeat also didn't have the default log level as debug AFAIK (or any [log level configured in the first place](https://github.com/elastic/elastic-agent/pull/1763))

**Comment by cmacknz** [comment]
Thanks. One thing to note is that Beats (in the Beats repo) currently rely on Elastic agent restarting them for the log level change to take effect. There is a plan to allow changing the log level dynamically without the restart this but it isn't implemented yet https://github.com/elastic/elastic-agent/issues/1137

**Comment by blakerouse** [comment]
I think we should do the filter on the Elastic Agent side, now that we parse the logs from stdout/stderr we could allow the Elastic Agent to do the filtering. This would allow the beats to operating in debug mode all the time and then have Elastic Agent filter out the log level based on the current setting.

I still think that beats should reduce its log-level by reading from the control protocol it should use, but we can think of that as more of an optimization as Elastic Agent can act as the guard for the actual log-level.

**Comment by michalpristas** [comment]
i'm with @oren-zohar on this one. having debug level by default and filtering agent side although possible it could result on higher CPU load both beats side and agent side as we would always had to process ton of logs. 
not sure about the impact of checking log level agent side on the pipeline throughput. having this debug by default could lead to some micro delays on many places when writing logs.

**Comment by cmacknz** [comment]
I think dynamically setting the log level in libbeat (and therefore every input that doesn't already handle it dynamically) will be straight forward to do.

I think all we need to do is use the new atomic `SetLevel` function in the Beats manager client.

Ideally a change in log level can be detected as a unit change in the Beats management code [here](https://github.com/elastic/elastic-agent-client/blob/15881a8e64ef95f32f688c933319cd926ff500b0/elastic-agent-client.proto#L280), and we can make the appropriate call to `SetLevel` to have it take effect.

@blakerouse can you try this and see if it works? APM and Cloudbeat can then pick up the change directly from libbeat.

**Comment by cmacknz** [comment]
@oren-zohar @michalpristas there is a PR in progress to support dynamically changing the log level in libbeat. We don't plan to ship 8.6 with Beats sending debug logs to the agent perpetually.

**Comment by cmacknz** [comment]
Follow up issue to track dynamically changing the log level in beats: https://github.com/elastic/beats/issues/34046
