### ISSUE TITLE
[Fleet]: 'elastic_agent.endpoint_security' option is not shown on the 'Dataset' dropdown on Logs page

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/elastic-agent#1939]
**Kibana version:** 8.6 Kibana Cloud environment

**Host OS and Browser version:** All, All

**Build Details:**

```
Version: 8.6.0 BC6
Build: 58740
Commit: f329a77595950244361736dff7208a810299fd69
```

**Preconditions:**

- 8.6 Kibana Cloud environment should be available.
- Agent Policies should be created.
- Endpoint integration should be added to the Agent policies.
- Agents should be installed.

**Steps to reproduce:**

1. Navigate to `Fleet > Agents tab`.
2. Click on the `Agent`.
3. Click on `Logs` tab.
4. Click on `Datasets` tab.
5. `Datasets` dropdown  is shown.
6. Observe that `elastic_agent.endpoint_security` option is not shown on the `Datasets` dropdown on `Logs` tab for `all OSs`.

**Expected Result:**

- `elastic_agent.endpoint_security` option should be shown on the `Datasets` dropdown on `Logs` tab for `all OSs`.

**Screen Recording:**

https://user-images.githubusercontent.com/97870262/206986415-a6e13e3f-a3d9-4ee0-84a4-e3bd246d2910.mp4

**Agent Logs:**

- **Windows:**

[elastic-agent-diagnostics-2022-12-12T08-06-28Z-00.zip](https://github.com/elastic/kibana/files/10205876/elastic-agent-diagnostics-2022-12-12T08-06-28Z-00.zip)

- **Linux:**

[elastic-agent-diagnostics-2022-12-12T07-57-41Z-00.zip](https://github.com/elastic/kibana/files/10205878/elastic-agent-diagnostics-2022-12-12T07-57-41Z-00.zip)

- **Mac**

[elastic-agent-diagnostics-2022-12-12T08-11-38Z-00.zip](https://github.com/elastic/kibana/files/10205916/elastic-agent-diagnostics-2022-12-12T08-11-38Z-00.zip)

**Comment by clintandrewhall** [comment]
@cmacknz @blakerouse Can I have an update on this issue, please?

**Comment by cmacknz** [comment]
We have been prioritizing more severe blockers with more complex fixes, not sure there has been much progress on this one yet.

**Comment by cmacknz** [comment]
@belimawr we're assigning this to to finish up while Blake tries to wrap up other issues.

The summary of what to do is to add an input to the monitoring filestream in agent that can read the Endpoint security logs files and ship them to Fleet.

This will likely need to be a new input similar for what we use to read the Elastic agent log files: https://github.com/elastic/elastic-agent/blob/f94f9659f05ac2e52859c5a9a37b60c7117f7618/internal/pkg/agent/application/monitoring/v1_monitor.go#L286

The Endpoint security logs are written to known locations on disk. Endpoint security runs as a separate service from the agent so it cannot read its logs from stdout and stderr as is done for the other processes the agent can start. The log paths are defined in the spec file for each operating system:

* Linux:
https://github.com/elastic/elastic-agent/blob/f94f9659f05ac2e52859c5a9a37b60c7117f7618/specs/endpoint-security.spec.yml#L21
* Mac:
https://github.com/elastic/elastic-agent/blob/f94f9659f05ac2e52859c5a9a37b60c7117f7618/specs/endpoint-security.spec.yml#L54
* Windows:
https://github.com/elastic/elastic-agent/blob/f94f9659f05ac2e52859c5a9a37b60c7117f7618/specs/endpoint-security.spec.yml#L69

The easiest way to test Endpoint security will be to use the artifacts from the [most recent 8.6 build candidate,](https://staging.elastic.co/8.6.0-0410b9b5/summary-8.6.0.html) because the Endpoint artifacts will be signed. On Linux this may matter less than it does on Mac and Windows. The agent will also download a snapshot version and package endpoint security if you run `EXTERNAL=true mage package`.

**Comment by prachigupta-qasource** [comment]
Hi @blakerouse @cmacknz,

We have re-validated this issue on the latest **8.6.0 BC9** Kibana Cloud environment and found that it is **"still occurring"**.

**Below are the observations:**

- `elastic_agent.endpoint_security` option is not shown on the `Datasets` dropdown on Logs tab for `all OSs`.
- `"event.dataset: elastic_agent.endpoint-security"` events/logs/metrics is not shown in `Discover tab` for Agents with `endpoint integration` added.

**Screen Recordings:**

https://user-images.githubusercontent.com/97870262/210064586-3008e2ea-f696-4972-a53a-49d052223423.mp4

![image](https://user-images.githubusercontent.com/97870262/210064948-e8a18bd1-7d62-4394-8936-a474dcd1562f.png)

![image](https://user-images.githubusercontent.com/97870262/210064966-65c6bcaf-d6f8-41ba-8a92-b81aafa3d79e.png)

**Build details:**

```
Version: 8.6.0 BC9
Build: 58832	
Commit: 93183bddac40f8a7ee8e566d1651f9f3b586a520
```
**Agent Logs:**

- **Linux:**

[elastic-agent-diagnostics-2022-12-30T11-25-41Z-00.zip](https://github.com/elastic/elastic-agent/files/10324423/elastic-agent-diagnostics-2022-12-30T11-25-41Z-00.zip)

- **Mac:**

[elastic-agent-diagnostics-2022-12-30T11-24-48Z-00.zip](https://github.com/elastic/elastic-agent/files/10324418/elastic-agent-diagnostics-2022-12-30T11-24-48Z-00.zip)

Please let us know if anything else is required from our side.

Thanks!

**Comment by cmacknz** [comment]
The index name is wrong:

```yaml
  data_stream:
    dataset: elastic_agent.endpoint-security
    namespace: li
    type: logs
  id: filestream-monitoring-endpoint-default
  index: logs-elastic_agent.endpoint-security-li
```

**Comment by cmacknz** [comment]
The agent doesn't have index permissions to write to this index:

```json
{\"type\":\"security_exception\",\"reason\":\"action [indices:admin/auto_create] is unauthorized for API key id [DT29YoUBwJ6rI4fZc7no] of user [elastic/fleet-server] on indices [logs-elastic_agent.endpoint-security-li], this action is granted by the index privileges [auto_configure,create_index,manage,all]\"}
```

Full logs:
```json
{"log.level":"warn","@timestamp":"2022-12-30T11:14:51.564Z","message":"Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2022, time.December, 30, 11, 14, 48, 514099930, time.UTC), Meta:{\"input_id\":\"filestream-monitoring-agent\",\"raw_index\":\"logs-elastic_agent.endpoint-security-li\",\"stream_id\":\"filestream-monitoring-endpoint-default\"}, Fields:{\"agent\":{\"ephemeral_id\":\"1358e958-3d01-4c39-8121-a9d1c2080925\",\"id\":\"a331ced7-e8c3-4caa-ba84-85537c6cb6b6\",\"name\":\"ip-172-31-14-36\",\"type\":\"endpoint\",\"version\":\"8.6.0\"},\"component\":{\"binary\":\"endpoint-security\",\"dataset\":\"elastic_agent.endpoint-security\",\"id\":\"endpoint-default\",\"type\":\"endpoint\"},\"data_stream\":{\"dataset\":\"elastic_agent.endpoint-security\",\"namespace\":\"li\",\"type\":\"logs\"},\"ecs\":{\"version\":\"1.11.0\"},\"elastic_agent\":{\"id\":\"a331ced7-e8c3-4caa-ba84-85537c6cb6b6\",\"snapshot\":false,\"version\":\"8.6.0\"},\"event\":{\"dataset\":\"elastic_agent.endpoint-security\"},\"host\":{\"name\":\"ip-172-31-14-36\"},\"input\":{\"type\":\"filestream\"},\"log\":{\"file\":{\"path\":\"/opt/Elastic/Endpoint/state/log/endpoint-000000.log\"},\"level\":\"info\",\"offset\":102175,\"origin\":{\"file\":{\"line\":562,\"name\":\"Comms.cpp\"}}},\"message\":\"Comms.cpp:562     File Events Index        : logs-endpoint.events.file-li\",\"process\":{\"pid\":2926,\"thread\":{\"id\":2958}}}, Private:(*input_logfile.updateOp)(0xc000c6f5c0), TimeSeries:false}, Flags:0x1, Cache:publisher.EventCache{m:mapstr.M(nil)}} (status=403): {\"type\":\"security_exception\",\"reason\":\"action [indices:admin/auto_create] is unauthorized for API key id [DT29YoUBwJ6rI4fZc7no] of user [elastic/fleet-server] on indices [logs-elastic_agent.endpoint-security-li], this action is granted by the index privileges [auto_configure,create_index,manage,all]\"}, dropping event!","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-monitoring","type":"filestream"},"log.logger":"elasticsearch","log.origin":{"file.line":429,"file.name":"elasticsearch/client.go"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment]
In the policy I do see permissions for the `logs-elastic_agent.endpoint-security-li` index:

```yaml
      - names:
        - logs-elastic_agent.endpoint_security-li
        privileges:
        - auto_configure
        - create_doc
```

**Comment by cmacknz** [comment]
I think we lost the index normalization somehow, that is still on the metrics input:

https://github.com/elastic/elastic-agent/blob/2de2cbbcff9c4d9e1aab8f565b19150be701c7a6/internal/pkg/agent/application/monitoring/v1_monitor.go#L592

**Comment by cmacknz** [comment]
@prachigupta-qasource please retest this in the next snapshot build and reopen the issue if it is still not fixed.

**Comment by prachigupta-qasource** [comment]
Hi @cmacknz,

We have re-validated this issue on the latest **8.6.0 BC10** Kibana **Cloud** environment and found the issue is **fixed now**.

**Below are the observations:**

- `elastic_agent.endpoint_security` option is shown on the `Datasets` dropdown on `Logs` tab for `all OSs`.

**Screenshots:**

![image](https://user-images.githubusercontent.com/97870262/210761890-dd6b8984-328e-4b62-8122-e26ec9e90235.png)

**Build details:**

```
Version: 8.6.0 BC10
Build: 58852	
Commit: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47
```
Hence, marking this ticket as QA: Validated.

Thanks!
