### ISSUE TITLE
[Oracle Linux 9]: Agent logs are not shown on Logs page.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/elastic-agent#1953]
**Kibana version:** 8.6 BC 7 Kibana Prod environment

**Browser version:** Chrome
**OS version:** Oracle Linux 9 

**Describe the bug:** Agent logs are not shown on agent Logs tab, when agent is installed on **Oracle Linux 9 AWS vm.**

**Build Details:**
```
Version: 8.6.0 BC7
Build: 58773
Commit: 511e7c66ad8b290feb0af3ea262ab3fb08cc87be
Artifacts: https://staging.elastic.co/8.6.0-75d87829/summary-8.6.0.html
```

**Preconditions:**

- 8.6 BC7 Kibana Prod environment should be available.
- Agent should be installed.

**Steps to reproduce:**

- Navigate to Fleet > Agents tab.
- Click on the Agent.
- Click on Logs tab.
- Observe that 'There are no log messages to display.' message is shown on Logs page.
**Expected behavior:**
Agent logs should be available on Agent logs tab.

**Screenshots :**
![image](https://user-images.githubusercontent.com/72375798/207792301-37b25058-76cf-4d7e-8937-8b30c5c97125.png)
![image](https://user-images.githubusercontent.com/72375798/207792590-c6cbc898-7a1d-4002-97a5-d33046e6b788.png)

**Agent logs :**
[elastic-agent-diagnostics-2022-12-15T06-29-10Z-00.zip](https://github.com/elastic/kibana/files/10234429/elastic-agent-diagnostics-2022-12-15T06-29-10Z-00.zip)

**Comment by cmacknz** [comment]
@dikshachauhan-qasource the link to the logs in the last comment appears to be empty `[Uploading elastic-agent-diagnostics-2022-12-15T10-33-40Z-00.zip…]()`

**Comment by cmacknz** [comment]
I can see that endpoint was reporting its output as DEGRADED at one point but that is the only obvious state change in the logs:

```json
{"log.level":"info","@timestamp":"2022-12-15T10:27:46.807Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":325},"message":"Existing component state changed","component":{"id":"endpoint-default","state":"HEALTHY","message":"Healthy: communicating with endpoint service","inputs":[{"id":"endpoint-default-eb2dc1fd-041c-4526-89ec-ea440c4f27e5","state":"STARTING","message":"Starting: endpoint service runtime"}],"output":{"id":"endpoint-default","state":"DEGRADED","message":"Protecting with policy {eb2dc1fd-041c-4526-89ec-ea440c4f27e5}"}},"ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment]
> However, when agent is installed only with system integration, no logs are available under logs tab.

Likely the default log file paths for the system integration are incorrect on Oracle Linux 9.

**Comment by amolnater-qasource** [comment]
Hi Team,
We have revalidated this issue on latest 8.6 SNAPSHOT kibana cloud environment and found it **fixed** now.
- We are successfully able to view logs for Oracle linux 9 VM.

**Build details:**
BUILD: 58836
COMMIT: c735e9fc6fdf0221cc3134b5fe110e9ae4a0effb
Artifact: https://snapshots.elastic.co/8.6.0-39d183e3/downloads/beats/elastic-agent/elastic-agent-8.6.0-SNAPSHOT-linux-x86_64.tar.gz

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/210351561-c9e0e7e5-02cd-4614-b6b2-481bc291cc9f.JPG)

Hence we are closing this issue and marking it as **QA:Validated**.

Thanks

**Comment by prachigupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/15282
 
Thanks!
