### ISSUE TITLE
V2: Agent debug logs are not visible in diagnostics because logs are flooded with Beat debug log messages

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1955]
In 8.6 the agent merges the logs of each of its sub-processes into a single log file. This makes it very easy to track problems across all of the agent processes, but causes problems when debug logging is enabled.

When debug logging is enabled for the entire agent the Beats in particular will log at least once per event, effectively flooding the combined log with Beat messages making it very difficult or impossible to capture the debug logs of the agent itself.

This is a problem when running only system metric collection. At a fundamental level even just the monitoring Filebeat instance is enough to Flood the logs but this will be a problem in general with this change.

Example messages with debug logging enabled. In the case of the monitoring Filebeat we get a log message that a processor didn't apply, and then a log message emitting that error message.

```json
{
  "log.level": "debug",
  "@timestamp": "2022-12-15T19:40:57.546Z",
  "message": "Failed to copy fields in copy_fields processor: target field data_stream.dataset already exists, drop or rename this field first",
  "component": {
    "binary": "filebeat",
    "dataset": "elastic_agent.filebeat",
    "id": "filestream-monitoring",
    "type": "filestream"
  },
  "service.name": "filebeat",
  "ecs.version": "1.6.0",
  "log.logger": "copy_fields",
  "log.origin": {
    "file.line": 82,
    "file.name": "actions/copy_fields.go"
  }
}
{
  "log.level": "debug",
  "@timestamp": "2022-12-15T19:40:57.545Z",
  "message": "Publish event: {\n  \"@timestamp\": \"2022-12-15T19:40:52.171Z\",\n  \"@metadata\": {\n    \"beat\": \"filebeat\",\n    \"type\": \"_doc\",\n    \"version\": \"8.6.0\",\n    \"raw_index\": \"logs-elastic_agent.filebeat-default\",\n    \"input_id\": \"filestream-monitoring-agent\",\n    \"stream_id\": \"filestream-monitoring-agent\"\n  },\n  \"agent\": {\n    \"version\": \"8.6.0\",\n    \"ephemeral_id\": \"ecdb1350-59d1-4a2f-8873-34a4aac77e65\",\n    \"name\": \"Craigs-MacBook-Pro.local\",\n    \"id\": \"4892bb50-738e-4f02-92c0-8361e3badf9d\",\n    \"type\": \"filebeat\"\n  },\n  \"component\": {\n    \"binary\": \"filebeat\",\n    \"dataset\": \"elastic_agent.filebeat\",\n    \"id\": \"filestream-monitoring\",\n    \"type\": \"filestream\"\n  },\n  \"message\": \"Publish event: {\\n  \\\"@timestamp\\\": \\\"2022-12-15T19:40:28.619Z\\\",\\n  \\\"@metadata\\\": {\\n    \\\"beat\\\": \\\"filebeat\\\",\\n    \\\"type\\\": \\\"_doc\\\",\\n    \\\"version\\\": \\\"8.6.0\\\",\\n    \\\"raw_index\\\": \\\"logs-elastic_agent.filebeat-default\\\",\\n    \\\"input_id\\\": \\\"filestream-monitoring-agent\\\",\\n    \\\"stream_id\\\": \\\"filestream-monitoring-agent\\\"\\n  },\\n  \\\"log.logger\\\": \\\"processors\\\",\\n  \\\"log\\\": {\\n    \\\"offset\\\": 3047337,\\n    \\\"file\\\": {\\n      \\\"path\\\": \\\"/Library/Elastic/Agent/data/elastic-agent-37a15b/logs/elastic-agent-20221215-6.ndjson\\\"\\n    }\\n  },\\n  \\\"log.level\\\": \\\"debug\\\",\\n  \\\"host\\\": {\\n    \\\"name\\\": \\\"Craigs-MacBook-Pro.local\\\"\\n  },\\n  \\\"message\\\": \\\"Publish event: {\\\\n  \\\\\\\"@timestamp\\\\\\\": \\\\\\\"2022-12-15T19:40:11.486Z\\\\\\\",\\\\n  \\\\\\\"@metadata\\\\\\\": {\\\\n    \\\\\\\"beat\\\\\\\": \\\\\\\"filebeat\\\\\\\",\\\\n    \\\\\\\"type\\\\\\\": \\\\\\\"_doc\\\\\\\",\\\\n    \\\\\\\"version\\\\\\\": \\\\\\\"8.6.0\\\\\\\",\\\\n    \\\\\\\"input_id\\\\\\\": \\\\\\\"filestream-monitoring-agent\\\\\\\",\\\\n    \\\\\\\"stream_id\\\\\\\": \\\\\\\"filestream-monitoring-agent\\\\\\\",\\\\n    \\\\\\\"raw_index\\\\\\\": \\\\\\\"logs-elastic_agent.filebeat-default\\\\\\\"\\\\n  },\\\\n  \\\\\\\"input\\\\\\\": {\\\\n    \\\\\\\"type\\\\\\\": \\\\\\\"filestream\\\\\\\"\\\\n  },\\\\n  \\\\\\\"elastic_agent\\\\\\\": {\\\\n    \\\\\\\"version\\\\\\\": \\\\\\\"8.6.0\\\\\\\",\\\\n    \\\\\\\"id\\\\\\\": \\\\\\\"4892bb50-738e-4f02-92c0-8361e3badf9d\\\\\\\",\\\\n    \\\\\\\"snapshot\\\\\\\": true\\\\n  },\\\\n  \\\\\\\"log.origin\\\\\\\": {\\\\n    \\\\\\\"file.line\\\\\\\": 82,\\\\n    \\\\\\\"file.name\\\\\\\": \\\\\\\"actions/copy_fields.go\\\\\\\"\\\\n  },\\\\n  \\\\\\\"event\\\\\\\": {\\\\n    \\\\\\\"dataset\\\\\\\": \\\\\\\"elastic_agent.filebeat\\\\\\\"\\\\n  },\\\\n  \\\\\\\"agent\\\\\\\": {\\\\n    \\\\\\\"id\\\\\\\": \\\\\\\"4892bb50-738e-4f02-92c0-8361e3badf9d\\\\\\\",\\\\n    \\\\\\\"ephemeral_id\\\\\\\": \\\\\\\"ecdb1350-59d1-4a2f-8873-34a4aac77e65\\\\\\\",\\\\n    \\\\\\\"name\\\\\\\": \\\\\\\"Craigs-MacBook-Pro.local\\\\\\\",\\\\n    \\\\\\\"type\\\\\\\": \\\\\\\"filebeat\\\\\\\",\\\\n    \\\\\\\"version\\\\\\\": \\\\\\\"8.6.0\\\\\\\"\\\\n  },\\\\n  \\\\\\\"service.name\\\\\\\": \\\\\\\"filebeat\\\\\\\",\\\\n  \\\\\\\"ecs\\\\\\\": {\\\\n    \\\\\\\"version\\\\\\\": \\\\\\\"8.0.0\\\\\\\"\\\\n  },\\\\n  \\\\\\\"log.logger\\\\\\\": \\\\\\\"copy_fields\\\\\\\",\\\\n  \\\\\\\"log.level\\\\\\\": \\\\\\\"debug\\\\\\\",\\\\n  \\\\\\\"component\\\\\\\": {\\\\n    \\\\\\\"binary\\\\\\\": \\\\\\\"filebeat\\\\\\\",\\\\n    \\\\\\\"dataset\\\\\\\": \\\\\\\"elastic_agent.filebeat\\\\\\\",\\\\n    \\\\\\\"id\\\\\\\": \\\\\\\"filestream-monitoring\\\\\\\",\\\\n    \\\\\\\"type\\\\\\\": \\\\\\\"filestream\\\\\\\"\\\\n  },\\\\n  \\\\\\\"log\\\\\\\": {\\\\n    \\\\\\\"file\\\\\\\": {\\\\n      \\\\\\\"path\\\\\\\": \\\\\\\"/Library/Elastic/Agent/data/elastic-agent-37a15b/logs/elastic-agent-20221215-2.ndjson\\\\\\\"\\\\n    },\\\\n    \\\\\\\"offset\\\\\\\": 6096802\\\\n  },\\\\n  \\\\\\\"message\\\\\\\": \\\\\\\"Failed to copy fields in copy_fields processor: target field data_stream.dataset already exists, drop or rename this field first\\\\\\\",\\\\n  \\\\\\\"data_stream\\\\\\\": {\\\\n    \\\\\\\"type\\\\\\\": \\\\\\\"logs\\\\\\\",\\\\n    \\\\\\\"dataset\\\\\\\": \\\\\\\"elastic_agent.filebeat\\\\\\\",\\\\n    \\\\\\\"namespace\\\\\\\": \\\\\\\"default\\\\\\\"\\\\n  },\\\\n  \\\\\\\"host\\\\\\\": {\\\\n    \\\\\\\"name\\\\\\\": \\\\\\\"Craigs-MacBook-Pro.local\\\\\\\"\\\\n  }\\\\n}\\\",\\n  \\\"component\\\": {\\n    \\\"id\\\": \\\"filestream-monitoring\\\",\\n    \\\"type\\\": \\\"filestream\\\",\\n    \\\"binary\\\": \\\"filebeat\\\",\\n    \\\"dataset\\\": \\\"elastic_agent.filebeat\\\"\\n  },\\n  \\\"elastic_agent\\\": {\\n    \\\"version\\\": \\\"8.6.0\\\",\\n    \\\"id\\\": \\\"4892bb50-738e-4f02-92c0-8361e3badf9d\\\",\\n    \\\"snapshot\\\": true\\n  },\\n  \\\"data_stream\\\": {\\n    \\\"dataset\\\": \\\"elastic_agent.filebeat\\\",\\n    \\\"namespace\\\": \\\"default\\\",\\n    \\\"type\\\": \\\"logs\\\"\\n  },\\n  \\\"event\\\": {\\n    \\\"dataset\\\": \\\"elastic_agent.filebeat\\\"\\n  },\\n  \\\"log.origin\\\": {\\n    \\\"file.line\\\": 210,\\n    \\\"file.name\\\": \\\"processing/processors.go\\\"\\n  },\\n  \\\"input\\\": {\\n    \\\"type\\\": \\\"filestream\\\"\\n  },\\n  \\\"agent\\\": {\\n    \\\"version\\\": \\\"8.6.0\\\",\\n    \\\"ephemeral_id\\\": \\\"ecdb1350-59d1-4a2f-8873-34a4aac77e65\\\",\\n    \\\"id\\\": \\\"4892bb50-738e-4f02-92c0-8361e3badf9d\\\",\\n    \\\"name\\\": \\\"Craigs-MacBook-Pro.local\\\",\\n    \\\"type\\\": \\\"filebeat\\\"\\n  },\\n  \\\"service.name\\\": \\\"filebeat\\\",\\n  \\\"ecs\\\": {\\n    \\\"version\\\": \\\"8.0.0\\\"\\n  }\\n}\",\n  \"event\": {\n    \"dataset\": \"elastic_agent.filebeat\"\n  },\n  \"host\": {\n    \"name\": \"Craigs-MacBook-Pro.local\"\n  },\n  \"ecs\": {\n    \"version\": \"8.0.0\"\n  },\n  \"log\": {\n    \"offset\": 471704,\n    \"file\": {\n      \"path\": \"/Library/Elastic/Agent/data/elastic-agent-37a15b/logs/elastic-agent-20221215-11.ndjson\"\n    }\n  },\n  \"service.name\": \"filebeat\",\n  \"log.level\": \"debug\",\n  \"log.logger\": \"processors\",\n  \"input\": {\n    \"type\": \"filestream\"\n  },\n  \"elastic_agent\": {\n    \"version\": \"8.6.0\",\n    \"id\": \"4892bb50-738e-4f02-92c0-8361e3badf9d\",\n    \"snapshot\": true\n  },\n  \"data_stream\": {\n    \"dataset\": \"elastic_agent.filebeat\",\n    \"namespace\": \"default\",\n    \"type\": \"logs\"\n  },\n  \"log.origin\": {\n    \"file.name\": \"processing/processors.go\",\n    \"file.line\": 210\n  }\n}",
  "component": {
    "binary": "filebeat",
    "dataset": "elastic_agent.filebeat",
    "id": "filestream-monitoring",
    "type": "filestream"
  },
  "service.name": "filebeat",
  "ecs.version": "1.6.0",
  "log.logger": "processors",
  "log.origin": {
    "file.line": 210,
    "file.name": "processing/processors.go"
  }
}
```

In the short term we should consider never setting the monitoring Beat log level higher than info. Longer term we will likely need to expose the ability to set the log level for the agent and each input and output independently in the agent policy and the Fleet UI.

**Comment by belimawr** [comment]
It might be out of the scope for this one, but in the long run I believe it would be interesting to have the possibility to exclude some verbose loggers from debug level. Currently Beats support setting which loggers will be run on debug level, or using `*` for all loggers.

If we could disable some of those more verbose loggers, like the `processors` we'd easily reduce the number of debug logs.

If there was an easy way for the process under agent to communicate their loggers, the Agent could also "filter out" those verbose ones using the current "log selectors" feature.

**Comment by cmacknz** [comment]
The log selectors can be set from the command line so we could just modify the Beat spec files to exclude the per event loggers as a short term work around:

https://github.com/elastic/elastic-agent/blob/ccd56bbc3349506bb35b8c5b9cb0465344a8fda9/specs/filebeat.spec.yml#L20-L35

We should probably also increase the default log rotation and retention thresholds for the new combined to elastic agent log to reflect that it now contains significantly more content. Previously log retention and rotation were per Beat, so the size of the log directory on disk was proportional to the number of started processes. We should be able to increase the default retention settings here and still save disk space overall.

**Comment by belimawr** [comment]
I believe when `logging.level=debug` is set and `logging.selectors` is not set, all loggers are selected.

Unfortunately we only support the "include list" (`logging.selectors`), so to exclude some we'd have to list all of them, but the `processors` one. It's doable, but not ideal as it's a moving target.

> We should probably also increase the default log rotation and retention thresholds for the new combined to elastic agent log to reflect that it now contains significantly more content.

I totally agree with that, we should came up with a 'common number of Beats process' running and increase the log rotation threshold by at least that factor.

**Comment by cmacknz** [comment]
I'm not sure https://github.com/elastic/beats/pull/34391 will fully resolve this. I don't think the Fleet UI knows about the trace level there:

<img width="1392" alt="Screen Shot 2023-01-26 at 11 50 27 AM" src="https://user-images.githubusercontent.com/3466215/214898058-eb3c8ff1-d241-4a1f-be35-82ea57add1bb.png">

I think this is defined here, but not sure if this is all we'd need to change

https://github.com/elastic/kibana/blob/f78236a2e4c1532a9a135444bea95a0f89d1047e/x-pack/plugins/fleet/server/types/models/agent.ts#L32-L42

```typescript
  schema.object({
    type: schema.oneOf([schema.literal('SETTINGS')]),
    data: schema.object({
      log_level: schema.oneOf([
        schema.literal('debug'),
        schema.literal('info'),
        schema.literal('warning'),
        schema.literal('error'),
      ]),
    }),
  })
```

@kpollich if we wanted to be able to select a "trace" log level for the agent in Fleet is there anything else we would need to change besides defining the new log level in the schema object above?

**Comment by kpollich** [comment]
The schema is one piece, as it drives the validation here. But we do have another enum we'd have to update here: https://github.com/elastic/kibana/blob/f78236a2e4c1532a9a135444bea95a0f89d1047e/x-pack/plugins/fleet/public/applications/fleet/sections/agents/agent_details_page/components/agent_logs/constants.tsx#L48-L53

Other than adding a new entry to the schema + enum there should be no other change needed here as far as I'm aware.

**Comment by cmacknz** [comment]
Reopening since we still need to add support for a trace level in Fleet as a follow up.

**Comment by jlind23** [comment]
@cmacknz should we create a follow up on kibana or someone from the agent team is able to do it?

Cc @kpollich

**Comment by cmacknz** [comment]
It seems simple enough that we could just do it ourselves, I also assume that the Fleet team could do it equally quickly. I'll let @kpollich tell us which path to take on this one based on the actual effort involved.

**Comment by blakerouse** [comment]
We will need to do some work to support trace in an action to Elastic Agent as well. I think we should file a new issue for that, being that the issue is technically complete based on the title and description of the issue.

You are describing a different issue where now published event messages don't show unless in trace mode.

**Comment by cmacknz** [comment]
Fair enough, created https://github.com/elastic/elastic-agent/issues/2212 as a follow up.
