### ISSUE TITLE
Add Helm Chart

### ISSUE THREAD

**Issue by jw-maynard** [elastic/elastic-agent#1956]
**Describe the enhancement:**
Add a basic Helm chart that allows easy configuration and deployment without needing to manually edit manifest files as described [here](https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html)

**Describe a specific use case for the enhancement or feature:**
While I agree with the overall choice by the Elastic Team to discontinue use of Helm charts for deployment of an ELK stack on k8s due to the fact the ECK is a much better solution, there are still likely folks who want to simply be able to deploy the agent and have it ship data to a stack hosted elsewhere. In my case, it is SaaS stack hosted with Elastic.co. A helm chart provides a standard way to apply configuration parameters instead of needing to download and either manually edit, or write a custom script to configure the appropriate k8s manifest files.

**Comment by VenturiEffect02** [comment]
I have the same exact use case since a Fleet-managed pool of agents is difficult to manage with gitops tools.
I had to create my own helm chart but it's a pain to maintain when upgrading it

**Comment by joshdover** [comment]
Hi folks, we're currently exploring a new helm chart for Elastic Agent. Closing in favor of the new issue https://github.com/elastic/elastic-agent/issues/3847
