### ISSUE TITLE
[Fleet]: Logs are not generated on 'Discover tab' for Mac Standalone upgrade on upgrading from 8.5.3 > 8.6.0

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/elastic-agent#1959]
**Kibana version:** 8.6 SNAPSHOT Kibana Staging environment

**Host OS and Browser version:** All, All

**Build Details:**

```
Version: 8.6.0 SNAPSHOT
Build: 56060
Commit: a8726a0c551c5d3e8d3bdc8f8cc2a0d88b8d0617
```
**Preconditions:**

- 8.6 SNAPSHOT Kibana Staging environment should be available.
- Agent Policies should be created
- Lower version `8.5.3 Standalone Mac` agent should be installed.

**Steps to reproduce:**

1. Open Terminal
2.  Run the following commands at the following path: Library/Elastic/Agent/data/elastic-agent-56a002/downloads/:

`[curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.4.0-darwin-x86_64.tar.gz] (https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.5.3-darwin-x86_64.tar.gz)`

3. Run the following command at the following path: Library/Elastic/Agent/

`./elastic-agent upgrade 8.6.0-SNAPSHOT`

4. The following output is shown after running the ./elastic-agent upgrade 8.5.0-SNAPSHOT command :

```
The upgrade process of Elastic Agent is currently EXPERIMENTAL and should not be used in production
Upgrade triggered to version 8.6.0-SNAPSHOT, Elastic Agent is currently restarting

```
5. Run the following command at the following path: Library/Elastic/Agent/
`./elastic-agent upgrade version`

6. The following output is shown and Standalone Mac agent is upgraded to 8.6.0

```
Binary:  8.6.0-SNAPSHOT (build: 56a002dc5c96d3a79decbf28bb7994cf49f3a4da at 2022-08-19 22:35:27 +0000 UTC)
Daemon:  8.6.0-SNAPSHOT (build: 56a002dc5c96d3a79decbf28bb7994cf49f3a4da at 2022-08-19 22:35:27 +0000 UTC)
```
7. Navigate to `Discover` tab and select `logs-*`.
8. Observe that `logs` are not shown for the `Standalone Mac agent` on the `Discover` tab after `upgrade`.

**Expected Result:**

- `logs` should be shown for the `Standalone Mac agent` on the `Discover` tab after `upgrade`.

**What's Working:**

- `metrics` is shown for the `Standalone Mac agent` on the `Discover` tab after `upgrade`.
- Data streams are generated for the Standalone Mac agent` on the `Data streams` tab after `upgrade`.
- `logs` are shown for the `Standalone Linux agent`  and `Standalone Windows agent` on the `Discover` tab after `upgrade`.

**Screenshots:**

![image](https://user-images.githubusercontent.com/97870262/208060832-a96b5e98-026b-4a87-8b31-ccbe5582de38.png)

![image](https://user-images.githubusercontent.com/97870262/208060466-9e11d0fd-402b-4d21-98f8-c7a78fed9916.png)

![image](https://user-images.githubusercontent.com/97870262/208060523-9526ba2a-4052-4c01-9e36-d9f1beeea3ed.png)

**Mac Agent Logs:**

- [elastic-agent-diagnostics-2022-12-12T07-57-41Z-00.zip](https://github.com/elastic/elastic-agent/files/10244286/elastic-agent-diagnostics-2022-12-12T07-57-41Z-00.zip)

**Comment by dikshachauhan-qasource** [comment]
Secondary review is done

**Comment by cmacknz** [comment]
There is nothing interesting happening in the attached agent logs. Possibly this is related to https://github.com/elastic/elastic-agent/issues/1924.

**Comment by jlind23** [comment]
@amolnater-qasource @dikshachauhan-qasource could this be retested with the latest snapshot that should be built today?

**Comment by prachigupta-qasource** [comment]
Hi @michalpristas,

We have re-validated this issue on the latest **8.6.0 SNAPSHOT** Kibana Staging environment and had the below observations.

**Observations:**

- `logs` are shown for the `Standalone Mac agent` on the `Discover` tab after upgrade from `8.5.3 > 8.6.0 SNAPSHOT`.
- `host.hostname` filter is `not working` after upgrade from `8.5.3 > 8.6.0 SNAPSHOT` and is showing no `logs` for `8.6.0`.

**Build details:**

```
Version: 8.6.0 SNAPSHOT
Build: 58830   
Commit: 6a5d6d96a534be75fc58acda8f89f2610309d7ff
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/97870262/209626049-37ff5c88-7e70-49a7-a2f9-9a25054eefa9.png)

![image](https://user-images.githubusercontent.com/97870262/209626304-7e375371-0c8f-4c22-8f4c-0e284f542ae9.png)

Please let us know if we are missing anything.

Thanks!

**Comment by michalpristas** [comment]
as logs are present let's close this one. host issue is reported here: https://github.com/elastic/kibana/issues/148091
