### ISSUE TITLE
V2: Agent monitoring is pointlessly trying to collect stats from the endpoint process

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#1965]
When metrics monitoring is enabled, the logs are regularly filled with errors like the one below because the endpoint process does not expose a `stats` endpoint over HTTP.

```
Error fetching data for metricset http.json: error making http request: Get \"http://unix/stats\": dial unix /opt/Elastic/Agent/data/tmp/endpoint-default.sock: connect: no such file or directory" 
```

We should avoid creating an HTTP metrics monitoring configuration for endpoint when setting up agent monitoring to reduce log spam from the monitoring Metricbeat instance: 

https://github.com/elastic/elastic-agent/blob/e11d086949a4f710588b27f3adfd9124986469bd/internal/pkg/agent/application/monitoring/v1_monitor.go#L605

- Relates https://github.com/elastic/elastic-agent/issues/1944

**Comment by cmacknz** [comment]
Fleet server seems to have similar behaviour:

```json
{"log.level":"error","@timestamp":"2022-12-21T05:40:17.022Z","message":"Error fetching data for metricset beat.state: error making http request: Get \"http://npipe/state\": open \\\\.\\pipe\\fleet-server-default: The system cannot find the file specified.","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},"log.origin":{"file.line":256,"file.name":"module/wrapper.go"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

**Comment by michalpristas** [comment]
fleet server should expose metrics on `http.enabled` true. 
we send http.enabled true as command args. this is not respected fleet-server side.
