### ISSUE TITLE
[v2] Agent logs include monitoring fields

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#2002]
8.7.0-SNAPSHOT

Agent logs now contain a lot of `monitoring.metrics` fields that they do not contain on v1. These are not indexed and are likely just taking extra storage space

<img width="920" alt="image" src="https://user-images.githubusercontent.com/1813008/209357403-9409b063-5174-4ea1-a3a7-6210e383bfe8.png">

**Comment by cmacknz** [comment]
These are expected logs from the Beats, they dump a snapshot of their current metrics every 30s.

These logs would have been in the dedicated beat logs files before, and would have been shipper to the Beat datastreams previously.

It is just more obvious that they are there now that everything shares a single log file.

I would be hesitant to just remove them as we do use the libbeat metrics logged here to get a rough plot of the queue size and contents of the event pipeline over time in diagnostics. There are also some useful filebeat specific metrics in here sometimes. Essentially this is the only way we have to view application level metrics in diagnostics. That said there is a lot of rarely used information included here.

**Comment by joshdover** [comment]
After digging further, I am seeing this in the v1 logs as well. Makes sense to leave as-is.
