### ISSUE TITLE
[Self-managed]: Upgraded Fleet Server goes to offline state on restarting agent service for windows.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2017]
**Kibana version:**  8.6.0 BC8 Kibana self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
VERSION: 8.6.0 BC8 Kibana self-managed environment
BUILD: 58807
COMMIT: 335b86a633af9ce1d9c8a92187ed1c8697ab139f
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.5.3-windows-x86_64.zip
```

**Agent Binary Download link:**
https://staging.elastic.co/8.6.0-0410b9b5/downloads/

**Preconditions:**
1. 8.6.0 BC8 Kibana self-managed environment should be available.
2. Lower version 8.5.3 fleet server should be installed.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Trigger upgrade for installed fleet server and observe fleet server is upgraded to latest 8.6.0 version.
3. Restart agent from services.
4. Observe upgraded fleet server agent goes permanently offline.

**Logs:**
[elastic-agent-diagnostics-2022-12-27T08-27-12Z-00.zip](https://github.com/elastic/elastic-agent/files/10307168/elastic-agent-diagnostics-2022-12-27T08-27-12Z-00.zip)

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/209643040-557c4401-cbb5-416a-865b-0aa8f4d31864.JPG)
![7](https://user-images.githubusercontent.com/77374876/209643043-bed25be7-b901-4e8d-acb4-2adad952b4bf.JPG)
![8](https://user-images.githubusercontent.com/77374876/209643034-cfa9c514-e98b-41d2-8dd6-f1f84ac7cdde.JPG)

**Expected Result:**
 Upgraded Fleet Server should get back healthy on restarting agent service for windows.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by michalpristas** [comment]
please attach logs from 8.6 agent as well, only 8.5 are present
from what i see, agent was restarted within grace period, maybe multiple times, watcher decided it is a failure and rolled back. another option is root level agent is not updated. need logs to decide
agent tries to fetch missing components which fails because source URI is modified and it does not start.
if source URI was correct agent would start in previous version

**Comment by michalpristas** [comment]
this is tested agains stale BC.
this BC does not have backward compatible controller, querying state is not possible, hence all update scenarios broken.
please test this against snapshot `https://snapshots.elastic.co/8.6.0-7e55dcb1`

**Comment by amolnater-qasource** [comment]
Hi @michalpristas 
Thank you for looking into this, we have revalidated this issue on latest 8.6 BC9 kibana self-managed environment and found it **fixed now**.

**Observations:**
- Upgraded Fleet Server gets back healthy on restarting agent service for windows.

**Build details:**
BUILD: 58832
COMMIT: 93183bddac40f8a7ee8e566d1651f9f3b586a520

**Screenshot:**
![2](https://user-images.githubusercontent.com/77374876/209934568-a52fecff-19e5-4a55-8f3d-617a16f080b0.JPG)

Hence we are **closing** this issue and marking it as **QA:Validated**.
Thanks
