### ISSUE TITLE
[Windows]: Diagnostics zip gets removed itself on Windows when `debug` log level is set for Agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2027]
**Kibana version:**  8.6 BC9 kibana cloud-staging environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
8.6 BC9
BUILD: 58832
COMMIT: 93183bddac40f8a7ee8e566d1651f9f3b586a520
Artifact: https://staging.elastic.co/8.6.0-43d88470/summary-8.6.0.html#elastic-agent
```

**Preconditions:**
1. 8.6 BC9 cloud-staging environment should be available.
2. Windows Agent should be installed.

**Steps to reproduce:**
1. Navigate to Fleet tab.
2. Update logging level to `debug` for Windows agent under agent logs.
3. Wait for 30 minutes.
4. Navigate to `C:\Program Files\Elastic\Agent` folder and run `.\elastic-agent.exe diagnostics collect`.
5. Observe logs zip is created and deleted itself.

**Note:**
This issue is reproducible on multiple Windows agents with debug logs enabled.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/209943887-0aec4e1b-3917-4e4e-9db9-f5a8653e4563.mp4

**Expected Result:**
Diagnostics zip shouldn't get removed itself on Windows when `debug` log level is set for Agent.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
Hi @cmacknz
We have revalidated this issue on latest 8.6 BC10 Kibana cloud environment and found it **still reproducible**.

**Observations:**
- Diagnostics zip gets removed itself on Windows when debug log level is set for Agent.

**Build details:**
BUILD: 58852
COMMIT: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47
Artifacts: https://staging.elastic.co/8.6.0-b6c773f9/downloads/beats/elastic-agent/elastic-agent-8.6.0-windows-x86_64.zip

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/210757295-db32ac7e-0a9a-4d4a-9f8d-14a29d2c6fea.mp4


Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment]
Does this also happen in versions before 8.6, like 8.5.3?

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 
We have revalidated this issue on 8.5.3 released kibana cloud-production environment and found it **not reproducible** there.

**Observations:**
- Diagnostics zip doesn't get removed itself on Windows when debug log level is set for Agent.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/211262417-c0eef158-4b45-4a5a-891b-3133ed06c813.mp4


https://user-images.githubusercontent.com/77374876/211262448-250c4079-95cc-4641-9d7f-9bf50f469f6c.mp4


**Build details:**
BUILD: 57217
COMMIT: 93852c98d9e9902fe166302fae10bc8c5f3502fb

Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment]
This is a little bit weird but not something that seems urgent.

@blakerouse any idea what change in 8.6 could cause this?

**Comment by blakerouse** [comment]
Nothing comes to top of mind. I know work was being done to allow shipping the diagnostics to Fleet thought an action, maybe that changed something that caused it.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.7 BC2 kibana cloud environment and found it **fixed** now.
- Diagnostics zip doesn't get removed itself on Windows when debug log level is set for Agent.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/219550950-b09a0b8d-01e7-404b-a35d-ccb37bacd752.mp4



**Build details:**
BUILD: 60736
COMMIT: 09c3bd11b121dea18eb84ef32bea4c9ab7915fc0

Hence, we are closing this issue and marking it as **QA:Validated**.
Thanks
