### ISSUE TITLE
Can't set up Jira Audit Logs integration with stand alone elastic-agent 

### ISSUE THREAD

**Issue by Myasnik2000** [elastic/elastic-agent#2073]
We try to  set up   Atlassian Jira integration for Atlassian Cloud and filled all required fields. Also  run a stand alone  elastic-agent in k8s and configure it  like suggested integration but we don't get any logs , also pods crushes and returns this error 
```Error: open /var/log/apt/: no such file or directory
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.5/fleet-troubleshooting.html ```
Pls can anyone help to set up this integration ?

**Comment by jlind23** [comment]
@Myasnik2000 as this is probably linked to Atlassian integration, can you create an issue inside https://github.com/elastic/integrations repository or create a new post on https://discuss.elastic.co/?

**Comment by Myasnik2000** [comment]
Thanks @jlind23
