### ISSUE TITLE
The agent should use a single shipper for regular and monitoring data by default

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2078]
The agent today starts two shippers by default, one for regular data and one for monitoring data regardless of if a separate monitoring output has been configured. Example: https://github.com/elastic/elastic-agent-shipper/issues/161#issuecomment-1318021693

The number of shipper processes started should exactly match the number of outputs defined in the agent policy. A monitoring specific shipper should only be started when a separate output has been configured specifically for monitoring.

One of the design goals of the shipper project is to ensure the agent policy output configuration operates in a "what you see in the policy is what you get" fashion with respect to the number of connections and queues that are created and need to be tuned. Defaulting to two shippers violates this principle.

**Comment by jlind23** [comment]
Closing as not relevant.
cc @ycombinator
