### ISSUE TITLE
Cannot install Agent unless Homebrew is used

### ISSUE THREAD

**Issue by ferullo** [elastic/elastic-agent#2095]
I noticed that you cannot install Elastic Agent if `/usr/local/bin` does not exist. That directory does not exist by default on macOS. My guess is installs always work because everyone happens to also use Homebrew which does create it.

An easy workaround is to create the directory before installing Agent (`sudo mkdir /usr/local/bin`).

**Comment by pierrehilbert** [comment]
Fixed here: https://github.com/elastic/elastic-agent/pull/2490
