### ISSUE TITLE
Update release manager with the M1 artifact

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent#213]
**Describe the enhancement:**

- [x] Add m1 artifact to the release manager code
- [x] Allow artifacts to be uploaded to the website. (require synchronization with the marketing team)
- [x] Add m1 artifact to be signed

**Describe a specific use case for the enhancement or feature:**

Relates: https://github.com/elastic/elastic-agent/issues/151

**Comment by AndersonQ** [comment]
@nimarezainia does https://github.com/elastic/infra/issues/34497 replaces this issue?

**Comment by jlind23** [comment]
@AndersonQ it does!
