### ISSUE TITLE
The elastic-agent diagnostics command should be able to collect CPU profiles

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2140]
The new diagnostics implementation in 8.6 captures memory and goroutine profiles (and several other profile types) by default. We should add a command line option to allow capturing CPU profiles, and allow varying the sample period. CPU profiles take some time to collect (defaulting to 30s per process) so it makes some sense for them to be disabled by default.

**Comment by cmacknz** [comment]
When we implement this, we may need to make collecting CPU profiles optional with a new option for the diagnostics command. If we do, it could also be nice to allow targeting specific components instead of trying to profile all of them at once.

**Comment by fearful-symmetry** [comment]
So, going over this, and I'm wondering how we want to integrate this (specifically the UI element for waiting to collect a CPU diagnostic) into the diagnostic collection UI in Kibana. The CLI interface is simple enough, but the web GUI is backed up by the action API and it's a whole different beast. Do we need to collaborate with someone on the fleet/Kibana team for a new UI element? Should we just do the CLI now?
<img width="905" alt="Screenshot 2023-07-12 at 12 55 21 PM" src="https://github.com/elastic/elastic-agent/assets/8418476/2ad44833-3473-412a-a74e-80b85ac275f0">

**Comment by fearful-symmetry** [comment]
For now just going to work on the CLI until we figure out how the Kibana/actions API changes should work.

**Comment by cmacknz** [comment]
Yes start with the CLI, we can create a separate issue to expose this in Fleet. That will involve changing the diangostics action payload to indicate whether or not CPU profiles should be supported. 

https://github.com/elastic/elastic-agent/blob/8b4ddebda5364e35cf20fd82812595426db180b5/internal/pkg/fleetapi/action.go#L419-L425

**Comment by cmacknz** [comment]
I'm reopening this because we missed updating the documentation explaining the format changes and the new option.

https://github.com/elastic/ingest-docs/blob/main/docs/en/ingest-management/commands.asciidoc#elastic-agent-diagnostics-command

Close this again once there is a PR updating that page in the docs.
