### ISSUE TITLE
Agent gets unhealthy temporary on installation with agent policy having system integration.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2145]
**Kibana version:** 8.7 Snapshot Kibana cloud environment

**Host OS:** Majorly reproducible on AWS Ubuntu 22, also inconsistently on Windows and MAC.

**Build details:**
VERSION: 8.7 Snapshot
BUILD: 59804
COMMIT: 9df7eebeff466b2530d7eb8bb08391ba16494b9e

**Preconditions:**
1. 8.7 Snapshot Kibana cloud environment should be available.
2. Agent Policy should be available with System integration.

**Steps to reproduce:**
1. Install ubuntu agent using Agent policy.
2. Observe agent is installed Unhealthy under Agents tab.
3. Observe agent remain unhealthy for quite a long time and then itself gets Healthy.

**Note:**
- This issue is reproducible multiple times on different builds and fresh VMs.

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/213434102-7fa75dd1-fd94-452d-bdde-900be104bbe1.JPG)
![2](https://user-images.githubusercontent.com/77374876/213434115-22bfb6be-c930-40fe-b559-14bae38fc271.JPG)

**Logs:**
[elastic-agent-diagnostics-2023-01-19T08-29-14Z-00.zip](https://github.com/elastic/elastic-agent/files/10456317/elastic-agent-diagnostics-2023-01-19T08-29-14Z-00.zip)

**Expected Result:**
 Agent should remain healthy on installation with agent policy having system integration.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by cmacknz** [comment]
The agent in the attached diagnostics only shows as healthy. I suspect this behaviour is caused by https://github.com/elastic/elastic-agent/issues/2086 but I would need diagnostics from the period where the agent is unhealthy to confirm.

**Comment by simranvaseer-qasource** [comment]
Hi @cmacknz 
 
Please find diagnostics logs when windows agent is unhealthy.

**Logs:**
**[elastic-agent-diagnostics-2023-01-20T07-10-45Z-00.zip](https://github.com/elastic/elastic-agent/files/10464026/elastic-agent-diagnostics-2023-01-20T07-10-45Z-00.zip)**

Please let us know if we are missing anything.
Thanks

**Comment by cmacknz** [comment]
Hmm. I still don't see any transitions into a DEGRADED or FAILED state in the attached diagnostics. The current state of everything is healthy. I wonder if this problem is transient. This would line up with the behaviour from #2086

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 
While testing on latest 8.7 SNAPSHOT kibana cloud environment, we have found this issue **still reproducible**.

**Observations:**
- Agent gets Unhealthy  temporarily on installation with System integration.
- However, on checking logs we didn't get any Unhealthy agent logs.
- We have observed few error logs for `elastic-agent.metricbeat` dataset.

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/215726566-be2caad7-2581-4e13-ade1-8de6c45dd7e9.JPG)
![3](https://user-images.githubusercontent.com/77374876/215726572-17c4be5a-f7ff-475e-8462-ad56133d82e6.JPG)

**Build details:**
BUILD: 60188
COMMIT: d9f4039ed626777ef792ab9156dcaae46818f04

**Logs:**
[elastic-agent-diagnostics-2023-01-31T09-22-06Z-00.zip](https://github.com/elastic/elastic-agent/files/10545127/elastic-agent-diagnostics-2023-01-31T09-22-06Z-00.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment]
In the most recent diagnostics the current state of every unit is healthy, and there are no state transitions to the degraded and failed state in the logs. I can't tell why the agent might have been unhealthy here unfortunately.

**Comment by mashaikx13** [comment]
Hi @cmacknz I am facing this issue on a clean installation of elastic agent 8.6.1 on Windows 10

```
- id: endpoint-default
  name: endpoint
  state: 2
  message: 'Healthy: communicating with endpoint service'
  units:
  - unit_id: endpoint-default-e3c8051f-6be7-433f-9e91-c162ed82c34f
    unit_type: 0
    state: 3
    message: Applied policy {e3c8051f-6be7-433f-9e91-c162ed82c34f}
    payload:
      error:
        code: -273
        message: Unable to connect to output server
  - unit_id: endpoint-default
    unit_type: 1
    state: 3
    message: Applied policy {e3c8051f-6be7-433f-9e91-c162ed82c34f}
    payload:
      error:
        code: -273
        message: Unable to connect to output server
  version_info:
    name: Endpoint
    version: 8.6.1
```

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.9.0 BC4 kibana cloud environment and found it **fixed now**.

**Observations:**
- Agent remains healthy on installation with agent policy having system integration.

**Screen Recordings:**


https://github.com/elastic/elastic-agent/assets/77374876/ec33fde8-c60c-4cd1-9ba1-60b9eaccd1db


https://github.com/elastic/elastic-agent/assets/77374876/83184b1a-5abd-49c5-b281-7cec82e6f8e1



**Build details:**
VERSION: 8.9.0 BC4
BUILD: 64661
COMMIT: ddf0c1972e43898b6890ddb38f4c016e96538239
Artifact Link: https://staging.elastic.co/8.9.0-c6bb8f7a/summary-8.9.0.html#elastic-agent

Hence we are **closing** this issue and marking as **QA:Validated**.

Thanks!
