### ISSUE TITLE
[Elastic Agent] Report running processes and their health statuses

### ISSUE THREAD

**Issue by jen-huang** [elastic/elastic-agent#2156]
This is related to https://github.com/elastic/kibana/issues/75236 and https://github.com/elastic/kibana/issues/99068, both of which are longer-term efforts around enabling more granular status reporting of "integrations" that are running on Elastic Agent. But Agent has no concept of integrations, only which inputs/processes are running.

Still, reporting that information is useful and would get us closer to our longer-term goals. In the short term, this would enable Endpoint to filter agents by which ones are running Endpoint without doing additional JOIN-like queries.

I'd like to propose that agents:
- [ ] Report what inputs/processes are running
- [ ] Report the health status of each
- [ ] Store the above information in [`local_metadata`](https://github.com/elastic/fleet-server/blob/35f53373d374089d633bbbd615ec6cb62f1a68d1/model/schema.json#L392) field

One thing to consider in deciding the data structure of of how this information should be stored, is that in the future we will want to allow subprocesses to report their own additional meta information, such as Endpoint process reporting an ["isolated" status](https://github.com/elastic/kibana/issues/99071).

**Comment by jen-huang** [comment]
@pierrehilbert @nimarezainia Not sure if we have an appropriate meta issue that can supersede this one, so I am reopening for now but feel free to close and redirect.

**Comment by pierrehilbert** [comment]
We have this one: https://github.com/elastic/ingest-dev/issues/1367

**Comment by jlind23** [comment]
Closing in favour of https://github.com/elastic/ingest-dev/issues/1367

**Comment by jlind23** [comment]
Closing this as done.
cc @ycombinator
