### ISSUE TITLE
Document current use of keys and certificates for authentication & future plans

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent#2166]
1. Document with how PKI, keys & certs are used today, and where they are in the configuration
2. Design document of how we want to use PKI in the future.

**Comment by leehinman** [comment]
Doc here:

https://docs.google.com/document/d/1pb14xxY9EBNCJJnUUwIozOtcUwtM5egxPzznr3t203Y/edit?usp=sharing

**Comment by florianl** [comment]
For visibility: @SeanHeelan this will impact us directly as we write directly to Elasticsearch from our Symbolization and Collection service.

**Comment by cmacknz** [comment]
> For visibility: @SeanHeelan this will impact us directly as we write directly to Elasticsearch from our Symbolization and Collection service.

To potentially clarify, the PKI here is only used to setup mTLS between the agent and the sub-processes it runs. Specifically this is the use of PKI for mTLS on the gRPC control protocol between processes on the same host. The shipper event protocol today does not use mTLS, and the use of TLS on the inter-process gRPC channel there is separate from the TLS configuration of the actual Elasticsearch or Logstash output. The TLS configuration for connections to Elasticsearch or other outputs is controlled separately. https://www.elastic.co/guide/en/fleet/current/elasticsearch-output.html#output-elasticsearch-pki-certs-authentication-settings

I don't think this would directly impact external clients, but I also don't know the profiling service system architecture in detail.

**Comment by florianl** [comment]
Thanks for clearifying @cmacknz :pray: 

It will impact us was we are responsible for three executables that are managed (start, stop, configuration changes and health updates) by Elastic Agent on the same host.

**Comment by SeanHeelan** [comment]
@leehinman @cmacknz We (Profiling team within O11y) have a couple of processes living within the integration server, controlled by Elastic Agent. From what I gather we hardcode some cert paths that are (apparently) guaranteed to remain fixed in Cloud vs QA. 

It **sounds** like this change may impact us, although I can't be sure. Should we have a call to discuss this, or do you guys think this is not a problem for us?

**Comment by leehinman** [comment]
> @leehinman @cmacknz We (Profiling team within O11y) have a couple of processes living within the integration server, controlled by Elastic Agent. From what I gather we hardcode some cert paths that are (apparently) guaranteed to remain fixed in Cloud vs QA.
> 
> It **sounds** like this change may impact us, although I can't be sure. Should we have a call to discuss this, or do you guys think this is not a problem for us?

No, this change shouldn't affect you.  This should just affect the mTLS between elastic-agent and the sub-processes (like filebeat or metricbeat).  If you have something inside the integration server that is communicating with Cloud or QA resources that would be separate.

**Comment by florianl** [comment]
@leehinman I hope I don't mix terminology here.

Can you specify what you see as sub-process (like filebeat or metricbeat)? From my understanding, every component with a spec file in [elastic/elastic-agent:specs](https://github.com/elastic/elastic-agent/tree/main/specs) is a sub-process of Elastic Agent. Is my understanding correct?
At the moment we have three independent components in [elastic/elastic-agent:specs](https://github.com/elastic/elastic-agent/tree/main/specs) - [elastic/elastic-agent:specs/pf-elastic-collector.spec.yml](https://github.com/elastic/elastic-agent/blob/main/specs/pf-elastic-collector.spec.yml) , [elastic/elastic-agent:specs/pf-elastic-symbolizer.spec.yml](https://github.com/elastic/elastic-agent/blob/main/specs/pf-elastic-symbolizer.spec.yml )and [elastic/elastic-agent:specs/pf-host-agent.spec.yml](https://github.com/elastic/elastic-agent/blob/main/specs/pf-host-agent.spec.yml)

If my understanding is wrong, what is the difference between filebeat or metricbeat and other components in [elastic/elastic-agent:specs](https://github.com/elastic/elastic-agent/tree/main/specs) without the `beat` suffix?

**Comment by leehinman** [comment]
> I'm confused as our component [elastic/elastic-agent:specs/pf-host-agent.spec.yml](https://github.com/elastic/elastic-agent/blob/main/specs/pf-host-agent.spec.yml) runs besides every other beat (like filebeat or metricbeat) at the endpoint if configured by the policy.

sorry, the vocabulary here is very confusing.  
You are correct that your component and beats are the same for this conversation.

This change however, should just be about what you receive in the configuration.  Today you get a TLS info for how to communicate with elastic-agent (for things like check-ins).  These changes might change some things like what extended key usage fields are in certs in that TLS info, but it would have no change on the TLS info you receive on how to connect to Elasticsearch (or Logstash).

**Comment by leehinman** [comment]
implementation to be tracked in issues #2671, #2673, #2674, #2675
