### ISSUE TITLE
Fleet Server listens on loopback when TLS is disabled in v8.6.0

### ISSUE THREAD

**Issue by antoineco** [elastic/elastic-agent#2197]
Although the host is [set to `0.0.0.0` in the config](https://github.com/elastic/integrations/blob/8da35ed6365f05d7d5e7d4c3f7f0f7d7795043c8/packages/fleet_server/manifest.yml#L29-L35), fleet-server forcibly listens on `127.0.0.1:8220` since v8.6.0 when configured [without TLS](https://github.com/deviantony/docker-elk/blob/3a3cdd7db830fa8038e9cc3274d111b274dbb305/kibana/config/kibana.yml#L17-L20).

```console
$ ss -tlpn
State     Recv-Q    Send-Q       Local Address:Port        Peer Address:Port    Process                                                                         
LISTEN    0         4096             127.0.0.1:8220             0.0.0.0:*        users:(("fleet-server",pid=167,fd=12))                                         
LISTEN    0         4096             127.0.0.1:8221             0.0.0.0:*        users:(("fleet-server",pid=167,fd=14))                                         
LISTEN    0         4096             127.0.0.1:6789             0.0.0.0:*        users:(("elastic-agent",pid=7,fd=12))                                          
LISTEN    0         4096             127.0.0.1:6791             0.0.0.0:*        users:(("elastic-agent",pid=7,fd=10))                                          
LISTEN    0         4096            127.0.0.11:40239            0.0.0.0:*
```

The only possibly relevant log entries I could find are:

```json
{"log.level":"info","@timestamp":"2023-01-18T11:42:17.160Z","message":"server listening","component":{"binary":"fleet-server","dataset":"elastic_agent.fleet_server","id":"fleet-server-default","type":"fleet-server"},"ecs.version":"1.6.0","service.name":"fleet-server","bind":"localhost:8220","rdTimeout":60000,"wrTimeout":600000,"@timestamp":"2023-01-18T11:42:17.16Z","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-01-18T11:42:17.160Z","message":"Exposed over insecure HTTP; enablement of TLS is strongly recommended","component":{"binary":"fleet-server","dataset":"elastic_agent.fleet_server","id":"fleet-server-default","type":"fleet-server"},"ecs.version":"1.6.0","service.name":"fleet-server","@timestamp":"2023-01-18T11:42:17.16Z","ecs.version":"1.6.0"}
```

When TLS is [enabled](https://github.com/deviantony/docker-elk/blob/89eb08cc07e07b1d27f84705dad08e908b6ee4f0/kibana/config/kibana.yml#L34-L37), the "server listening" log entry shows a binding to `0.0.0.0:8200` as expected:

```json
{"log.level":"info","@timestamp":"2023-01-17T14:13:57.314Z","message":"server listening","component":{"binary":"fleet-server","dataset":"elastic_agent.fleet_server","id":"fleet-server-default","type":"fleet-server"},"wrTimeout":600000,"ecs.version":"1.6.0","service.name":"fleet-server","bind":"0.0.0.0:8220","rdTimeout":60000,"ecs.version":"1.6.0"}
```

Until v8.5 (included), the [`host` input](https://github.com/elastic/integrations/blob/8da35ed6365f05d7d5e7d4c3f7f0f7d7795043c8/packages/fleet_server/manifest.yml#L29-L35) was respected, even if TLS wasn't enabled.

**Comment by michel-laterman** [comment]
The fleet-server's behaviour in
https://github.com/elastic/elastic-agent/blob/da1db715251d8ff0c019672f5dd683f638d0a087/internal/pkg/agent/cmd/enroll_cmd.go#L397-L405
is intentional. 

If the server is started with `--fleet-server-insecure-http` the host is set to `localhost` instead of `0.0.0.0`.
It must be explicitly overridden by using the `--fleet-server-host` flag.

The `host` (and `port`) options that appear in the fleet-server integration settings are always ignored (is this correct @blakerouse )

**Comment by antoineco** [comment]
Closing because working as intended (see discussions in the linked PR).
