### ISSUE TITLE
No debug level logs are generated on changing log level to debug.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2211]
**Kibana version:**  8.7 Snapshot kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.7 Snapshot
BUILD: 60188
COMMIT: d9f4039ed626777ef792ab9156dcaae46818f04
Artifact: https://snapshots.elastic.co/8.7.0-4687ed94/downloads/beats/elastic-agent/elastic-agent-8.7.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Preconditions:**
1. 8.7 Snapshot kibana cloud environment should be available.
2. Agents should be installed with agent policy having only System integration.

**Steps to reproduce:**
1. Navigate to Fleet tab.
2. Update logging level to `debug` for agents under agent logs.
3. Observe no debug level logs gets generated for any of the elastic-agent dataset under Logs tab.

**Logs:**
[elastic-agent-diagnostics-2023-01-31T09-22-06Z-00.zip](https://github.com/elastic/elastic-agent/files/10545527/elastic-agent-diagnostics-2023-01-31T09-22-06Z-00.zip)

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/215738149-c1ce773a-67b2-4a13-bee2-a9ab796a47b2.JPG)

**Expected Result:**
Debug level logs should be generated on changing log level to debug.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
I can see debug logs in the diagnostics logs and the state.yaml in the diagnostics show the agent's current log level is debug.

```
{"log.level":"debug","@timestamp":"2023-01-31T09:22:03.003Z","message":"PublishEvents: 4 events have been published to elasticsearch in 76.576707ms.","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},"log":{"source":"beat/metrics-monitoring"},"log.logger":"elasticsearch","log.origin":{"file.line":247,"file.name":"elasticsearch/client.go"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-01-31T09:22:03.004Z","message":"ackloop: return ack to broker loop:4","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},"log":{"source":"beat/metrics-monitoring"},"log.logger":"publisher","log.origin":{"file.line":81,"file.name":"memqueue/ackloop.go"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-01-31T09:22:03.004Z","message":"ackloop:  done send ack","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},"log":{"source":"beat/metrics-monitoring"},"log.logger":"publisher","log.origin":{"file.line":83,"file.name":"memqueue/ackloop.go"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-01-31T09:22:03.278Z","message":"PublishEvents: 3 events have been published to elasticsearch in 75.445317ms.","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"ecs.version":"1.6.0","log.logger":"elasticsearch","log.origin":{"file.line":247,"file.name":"elasticsearch/client.go"},"service.name":"metricbeat","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-01-31T09:22:03.278Z","message":"ackloop: return ack to broker loop:3","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"log.logger":"publisher","log.origin":{"file.line":81,"file.name":"memqueue/ackloop.go"},"service.name":"metricbeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-01-31T09:22:03.278Z","message":"ackloop:  done send ack","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"service.name":"metricbeat","ecs.version":"1.6.0","log.logger":"publisher","log.origin":{"file.line":83,"file.name":"memqueue/ackloop.go"},"ecs.version":"1.6.0"}
```

@amolnater-qasource can you confirm that the "Log Level" filter in Fleet was set to Debug? I can't see the value in the included screenshot. I can only see the selected Datasets.

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 

Thank you for looking into this.
> @amolnater-qasource can you confirm that the "Log Level" filter in Fleet was set to Debug? I can't see the value in the included screenshot. I can only see the selected Datasets.

Yes, we had debug level logs filter applied with other datasets. It seems like that the new logs are not available on fleet UI. 

Further, we have revalidated this issue on latest 8.7 SNAPSHOT and found it **still reproducible**.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/216541375-c3ee8e73-b20e-4b7b-8ca5-2a3038f754ac.mp4


**Logs:**
[elastic-agent-diagnostics-2023-02-03T07-37-50Z-00.zip](https://github.com/elastic/elastic-agent/files/10576667/elastic-agent-diagnostics-2023-02-03T07-37-50Z-00.zip)

Here, we have also observed that the new debug logs are available: 
![image](https://user-images.githubusercontent.com/77374876/216542252-eff7080c-6385-4e2a-be03-a54c4e12b8a7.png)

- We have waited for more than 15 minutes to reconfirm if the logs get available on Fleet>Agent logs UI.

**Build details:**
BUILD: 60371
COMMIT: bd97ad681cfcf9e1984ed349c12ce93d5fcc3ae0
Artifact link: https://snapshots.elastic.co/8.7.0-a8bf765b/downloads/beats/elastic-agent/elastic-agent-8.7.0-SNAPSHOT-windows-x86_64.zip
Host-OS: Windows

We have also observed that new debug logs are available on UI for Ubuntu 22 agent **inconsistently**.

Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment]
Looking at the beat-rendered-config for the `filestream-monitoring` component I see:

```yaml
inputs: []
outputs:
  elasticsearch:
    api_key: <REDACTED>
    bulk_max_size: 50
    hosts:
    - https://79220aaec2c4481d883637aa99861ed5.us-west2.gcp.elastic-cloud.com:443
    type: elasticsearch
```

This is the same problem as https://github.com/elastic/elastic-agent/issues/2232. Let's revalidate this after https://github.com/elastic/elastic-agent/issues/2232 is resolved.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.7 BC2 kibana cloud environment and found it **fixed** now.
- Debug level logs are generated under Logs tab on changing log level to debug.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/219550269-3a5157f9-4e7b-48b5-b253-923b037a3302.mp4


**Build details:**
BUILD: 60736
COMMIT: 09c3bd11b121dea18eb84ef32bea4c9ab7915fc0

Hence, we are closing this issue and marking it as **QA:Validated**.
Thanks
