### ISSUE TITLE
Warning is shown on running `elastic-agent diagnostics collect` command.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2221]
**Kibana version:**  8.7 Snapshot kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.7 Snapshot
BUILD: 60311
COMMIT: ef00463019c0ebce609070d25cee6eed59a33909
```

**Preconditions:**
1. 8.7 Snapshot kibana cloud environment should be available.
2. Agents should be installed with agent policy.

**Steps to reproduce:**
1. Navigate to CLI, and run command `sudo elastic-agent diagnostics collect`.
2. Observe Warning message: 
`[WARNING] Could not redact state.yaml due to unmarshalling error: yaml: invalid map key: map[interface {}]interface {}{"unitid":"system/metrics-default", "unittype":1}`

**What's working fine:**
zip file is created successfully created on running diagnostics collect command.

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/216288574-90d1f76f-2ff3-4090-84e8-ab68e77ff471.JPG)

**Expected Result:**
zip file should be created without any warnings on running `elastic-agent diagnostics collect` command.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
Known issue, this is a duplicate of https://github.com/elastic/elastic-agent/issues/1907

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 
Thank you for the confirmation, we will keep track of the related issue and will revalidate this, once fixed.
