### ISSUE TITLE
Error communicating with Fleet should result in the local status being an error

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#2230]
Because of the change in https://github.com/elastic/elastic-agent/pull/2203, the 8.6+ now doesn't report a true health status when doing the command `elastic-agent status`.

Communication with Fleet Server should be reported locally, even in the case that we don't report it remotely.

**Comment by cmacknz** [comment]
Agreed, we should report being unable to communicate with Fleet Server locally. 

Ideally we should implement logic similar to what Fleet itself uses to determine that the agent is offline. This was most recently changed in https://github.com/elastic/kibana/pull/147552.

Right now this is in https://github.com/elastic/kibana/blob/60defc5dbde98bd2ee7daa09c9e3562d1c8703b7/x-pack/plugins/fleet/server/services/agents/build_status_runtime_field.ts#L11-L14

```typescript
import { AGENT_POLLING_THRESHOLD_MS } from '../../constants';
import { agentPolicyService } from '../agent_policy';
const MISSED_INTERVALS_BEFORE_OFFLINE = 10;
const MS_BEFORE_OFFLINE = MISSED_INTERVALS_BEFORE_OFFLINE * AGENT_POLLING_THRESHOLD_MS;
```

where `AGENT_POLLING_THRESHOLD_MS` is defined at https://github.com/elastic/kibana/blob/60defc5dbde98bd2ee7daa09c9e3562d1c8703b7/x-pack/plugins/fleet/common/constants/agent.ts#L17

```typescript
export const AGENT_POLLING_THRESHOLD_MS = 30000;
```

That would lead us to report the agent as failed locally after not being able to check in for 300 seconds or 5 minutes which seems reasonable as it allows for several attempts to retry in the main checkin loop:

https://github.com/elastic/elastic-agent/blob/973af90d85dd81aaccfd42a1f81e7ad60f6780db/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go#L175-L192

**Comment by cmacknz** [comment]
@michalpristas let's address this before the 8.6.2 feature freeze, hopefully it is straightforward to restore.

**Comment by michalpristas** [comment]
in this case we need something like you proposed, whatever we report locally is used with upgrade procedure, the reason for that PR is that reporting failures early lead to rollbacks. 
will work on it tomorrow. i'm getting a lot of before feature freeze issues

**Comment by blakerouse** [comment]
@michalpristas I would be open to even reporting the Fleet communication status completely separate from the main health of the Elastic Agent. That might actually be better, as it could be clear that everything is working fine except for communication with Fleet. That separation could then be used by the upgrade watcher to ignore issues with Fleet communication.

```
State: HEALTHY
Fleet State: UNHEALTHY
Message: Healthy
```

**Comment by cmacknz** [comment]
> in this case we need something like you proposed, whatever we report locally is used with upgrade procedure, the reason for that PR is that reporting failures early lead to rollbacks.

In that case I agree with Blake, let's report the Fleet status separately. It definitely shouldn't block upgrades.

I think we may want to think about having a completely separate RPC in the local agent control protocol for checking if an upgrade succeeded so that adding errors that can cause upgrades to rollback is a very intentional decision.

**Comment by michalpristas** [comment]
i don't have anything against making it separate but if we want to push it for tomorrow FF I'm not sure i can make it with full review cycle
