### ISSUE TITLE
[Fleet]: CPU and Memory fields changes to `NA` for Ubuntu agent on changing logging level to `debug`.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2232]
**Kibana version:**  8.7 Snapshot kibana cloud environment

**Host OS and Browser version:** Ubuntu 22, All

**Build details:**
```
VERSION: 8.7 Snapshot
BUILD: 60430
COMMIT: 23e97feccbd3750dbd2c85d521b4893fff651f89
Artifact Link: https://snapshots.elastic.co/8.7.0-1ef3b708/downloads/beats/elastic-agent/elastic-agent-8.7.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Preconditions:**
1. 8.7 Snapshot kibana cloud environment should be available.
2. An Ubuntu .tar agent should be installed with agent policy having System and Endpoint Defend integrations.

**Steps to reproduce:**
1. Navigate to Agents tab and set logging level to debug for Ubuntu agent.
2. Observe after 7-10 minutes, the fields CPU and Memory changes to `NA`.

**Note:**
- Agent is healthy, and the host VM is also accessible.

**What's working fine:**
- This issue is not observed for MAC or Windows agents.
- Before setting to debug, CPU and Memory metrics keeps on updating as expected.

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/216919264-e0ec9c95-cbd3-42c9-8730-d5ea10147238.JPG)
![2](https://user-images.githubusercontent.com/77374876/216919269-d4975bc8-30f6-4a63-8154-3f5cb2bc1e83.JPG)
![3](https://user-images.githubusercontent.com/77374876/216919272-1c4acfc9-5100-4692-adc1-fb2a3a76dad2.JPG)

**Logs:**
[elastic-agent-diagnostics-2023-02-06T08-07-04Z-00.zip](https://github.com/elastic/kibana/files/10660933/elastic-agent-diagnostics-2023-02-06T08-07-04Z-00.zip)

**Expected Result:**
CPU and Memory fields should keep updating for Ubuntu agent on changing logging level to `debug`.

**Comment by cmacknz** [comment]
If we skip updating all the units, I think we might still be calling reload with an empty reload list:

https://github.com/elastic/beats/blob/9e4356fc6f3ed389063da84576926ddaaa0ead22/x-pack/libbeat/management/managerV2.go#L597-L611

```go
		if prevCfg != nil && gproto.Equal(prevCfg, rawConfig) {
			// configuration for the input did not change; do nothing
			cm.logger.Debugf("Skipped reloading input unit %s; configuration didn't change", unit.ID())
			continue
		}

		inputCfg, err := generateBeatConfig(rawConfig, agentInfo)
		if err != nil {
			return fmt.Errorf("failed to generate configuration for unit %s: %w", unit.ID(), err)
		}
		inputCfgs[unit.ID()] = rawConfig
		inputBeatCfgs = append(inputBeatCfgs, inputCfg...)
	}

	err := obj.Reload(inputBeatCfgs)
```

**Comment by cmacknz** [comment]
Yeah the beat-rendered-config for the affected beat/metrics input shows no running inputs this must be what is happening:

```yaml
inputs: []
outputs:
  elasticsearch:
    api_key: <REDACTED>
    bulk_max_size: 50
    hosts:
    - https://2ca27927a0f9420aa4c26bf983abc69a.us-west2.gcp.elastic-cloud.com:443
    type: elasticsearch
```

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.7.0 BC3 Kibana cloud environment and found it **fixed** now.

**Observations:**
- CPU and Memory fields keeps updating for Ubuntu agent on changing logging level to `debug`.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/221087014-82c555fe-5ea5-4607-a37f-b64d5d159cba.mp4


**Build details:**
BUILD: 60804
COMMIT: abbdcf43f4e89f6fc085360252514aed7c032b4b

Hence, we are marking this issue as **QA:Validated**.
Thanks

**Comment by dikshachauhan-qasource** [comment]
### Bug Conversion

Test-Case has been updated as this particular checkpoint in the following testcase:

- https://elastic.testrail.io/index.php?/cases/view/168936

Thanks
