### ISSUE TITLE
Elastic-agent is crashing my windows servers

### ISSUE THREAD

**Issue by Blason** [elastic/elastic-agent#2236]
Hi Team - 

I am struggling with elastic-agent as I observed most of my windows servers are freezing but I am unable to troubleshoot. can someone please share the debug commands or any hints to resolve the issues. Or at least something that I can start with?

TIA

**Comment by cmacknz** [comment]
The [diagnostics command](https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-diagnostics-command) can help you here. Perhaps just looking at the agent logs files would be enough. There isn't enough information to know what you need unfortunately.

Please start a discussion in the Discuss forums and someone will help you there: https://discuss.elastic.co/c/elastic-stack/elastic-agent/91

The issue tracker is for confirmed bugs, not determining if there is a bug.

**Comment by Blason** [comment]
Thanks Appreciate it.
