### ISSUE TITLE
Upgrades that fail and are rolled back can break the elastic-agent command symlink

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2264]
Agent upgrades that fail and rolled back can break the `elastic-agent` command symlink. The agent is  left running but you can no longer interact with it through the `elastic-agent` command. 

This was observed on MacOS Monterey, behaviour may differ per platform in this case.

**Comment by matt-isett** [comment]
I was working with a user with a new install of the elastic agent on MACOS Monterey - M1 chips
both 8.5 and 8.6 aarm fails with a symlink error, but the previous 8.4 AARM version works.
```
Elastic Agent will be installed at /Library/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:Y
Error: failed to create elastic-agent symlink (/usr/local/bin/elastic-agent): symlink /Library/Elastic/Agent/elastic-agent /usr/local/bin/elastic-agent: no such file or directory

```

Possible 8.7 has a fix for symlink - I will verify again after release.

**Comment by cmacknz** [comment]
We have logs for another example of this, this time on a Linux machine after an attempted upgrade from 8.5.1 to 8.8.1.

The user gets the following error running the `elastic-agent status` command:

```
Error: failed to communicate with Elastic Agent daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /opt/Elastic/Agent/data/tmp/elastic-agent-control.sock: connect: no such file or directory"
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.8/fleet-troubleshooting.html 
```

It appears that `elastic-agent.sock` exists under the `data/tmp` directory but not `elastic-agent-control.sock`:

```
root@k8s-host-01:/opt/Elastic/Agent/data/tmp# ls -l
total 4
drwxr-xr-x 4 root root 4096 Jun 21 01:49 default
srwxr----- 1 root root    0 Jun 21 01:49 elastic-agent.sock
```

The top level directory structure of the agent was as follows, with the active commit hash being 4ac18b which is the [v8.8.1](https://github.com/elastic/elastic-agent/commits/v8.8.1) tag.

```
root@k8s-host-01:/opt/Elastic/Agent# ls -l
total 1264
drwxrwx--- 5 root root   4096 Jun 21 02:00 data
lrwxrwxrwx 1 root root     39 Jun 21 02:37 elastic-agent -> data/elastic-agent-4ac18b/elastic-agent
-rw------- 1 root root  56269 Mar 17 22:49 elastic-agent-20230316-1.ndjson
-rw------- 1 root root  39094 Mar 16 18:21 elastic-agent-20230316.ndjson
-rw------- 1 root root  83775 Jun 21 01:48 elastic-agent-20230619.ndjson
-rw------- 1 root root  91562 Jun 22 18:07 elastic-agent-20230621-1.ndjson
-rw------- 1 root root    187 Jun 21 01:57 elastic-agent-20230621-2.ndjson
-rw------- 1 root root   1189 Jun 21 01:48 elastic-agent-20230621.ndjson
-rw-r----- 1 root root   9164 Mar 16 16:45 elastic-agent.reference.yml
-rw------- 1 root root   1947 Mar 16 16:45 elastic-agent.yml
-rw------- 1 root root   9127 Mar 16 16:45 elastic-agent.yml.2023-03-16T16-45-15.9953.bak
-rw------- 1 root root    665 Mar 16 16:45 fleet.enc
-rw------- 1 root root      0 Mar 16 16:45 fleet.enc.lock
-rw-r----- 1 root root  13675 Mar 16 16:45 LICENSE.txt
-rw-r----- 1 root root 929850 Mar 16 16:45 NOTICE.txt
-rw-r----- 1 root root    864 Mar 16 16:45 README.md
drwxr-x--- 2 root root   4096 Mar 16 16:45 vault
-rw------- 1 root root      0 Jun 21 01:47 watcher.lock
```

Looking closer at the logs shows that the 8.5.1 upgrade watcher detected the agent as failed, but did not log the exact reason. It attempts to roll back to the previous version but for unknown reasons this does not actually succeed:

```json
{"log.level":"error","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"upgrade/error_checker.go","file.line":82},"message":"error checker notifying failure of agent","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"upgrade/error_checker.go","file.line":93},"message":"error checker notifying failure of applications","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"cmd/watch.go","file.line":170},"message":"Agent Error detectedagent in a failed state","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"cmd/watch.go","file.line":101},"message":"Error detected proceeding to rollback: %vagent in a failed state","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"upgrade/step_relink.go","file.line":36},"message":"Changing symlink","symlink_path":"/opt/Elastic/Agent/elastic-agent","new_path":"/opt/Elastic/Agent/data/elastic-agent-026915/elastic-agent","prev_path":"/opt/Elastic/Agent/elastic-agent.prev","ecs.version":"1.6.0"}
```

Approximately a day later the upgrade was attempted again, but this time fails because of a missing `downloads` directory for the 8.5.1 agent. This is event more curious because the active commit hash of the agent is for the v8.8.1 version.

```json
{"log.level":"info","@timestamp":"2023-06-22T18:06:17.476Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":111},"message":"Upgrading agent","version":"8.8.1","source_uri":"","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-22T18:06:17.476Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":132},"message":"Unable to clean downloads before update","error":{"message":"unable to read directory \"/opt/Elastic/Agent/data/elastic-agent-026915/downloads\": open /opt/Elastic/Agent/data/elastic-agent-026915/downloads: no such file or directory"},"downloads.path":"/opt/Elastic/Agent/data/elastic-agent-026915/downloads","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-22T18:06:17.476Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2023-06-22T18:06:17Z - message: Application: [ee457d92-653d-40f0-91a8-d024cf0d2eb2]: State changed to UPDATING: Update to version '8.8.1' started - type: 'STATE' - sub_type: 'UPDATING'","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-06-22T18:06:17.476Z","log.origin":{"file.name":"http/downloader.go","file.line":100},"message":"failed to cleanup : remove : no such file or directory","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-22T18:06:17.476Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":149},"message":"Unable to remove file after verification failure","error":{"message":"unable to read directory \"/opt/Elastic/Agent/data/elastic-agent-026915/downloads\": open /opt/Elastic/Agent/data/elastic-agent-026915/downloads: no such file or directory"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-22T18:06:18.587Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2023-06-22T18:06:18Z - message: Application: [ee457d92-653d-40f0-91a8-d024cf0d2eb2]: State changed to FAILED: failed upgrade of agent binary: 2 errors occurred:\n\t* package '/opt/Elastic/Agent/data/elastic-agent-026915/downloads/elastic-agent-8.8.1-linux-x86_64.tar.gz' not found: open /opt/Elastic/Agent/data/elastic-agent-026915/downloads/elastic-agent-8.8.1-linux-x86_64.tar.gz: no such file or directory\n\t* creating package file failed: open /opt/Elastic/Agent/data/elastic-agent-026915/downloads/elastic-agent-8.8.1-linux-x86_64.tar.gz: no such file or directory\n\n - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-22T18:06:18.587Z","log.origin":{"file.name":"handlers/handler_action_upgrade.go","file.line":45},"message":"Upgrade action failed","error":{"message":"failed upgrade of agent binary: 2 errors occurred:\n\t* package '/opt/Elastic/Agent/data/elastic-agent-026915/downloads/elastic-agent-8.8.1-linux-x86_64.tar.gz' not found: open /opt/Elastic/Agent/data/elastic-agent-026915/downloads/elastic-agent-8.8.1-linux-x86_64.tar.gz: no such file or directory\n\t* creating package file failed: open /opt/Elastic/Agent/data/elastic-agent-026915/downloads/elastic-agent-8.8.1-linux-x86_64.tar.gz: no such file or directory\n\n"},"action.version":"8.8.1","action.source_uri":"","action.id":"1e4e2401-f817-4fa7-8b12-5d49d2b7ba91","action.start_timeError":"json: unsupported type: func() (time.Time, error)","action.expiration":"2023-07-22T18:06:16.413Z","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-22T18:06:18.588Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":204},"message":"failed to dispatch actions, error: failed upgrade of agent binary: 2 errors occurred:\n\t* package '/opt/Elastic/Agent/data/elastic-agent-026915/downloads/elastic-agent-8.8.1-linux-x86_64.tar.gz' not found: open /opt/Elastic/Agent/data/elastic-agent-026915/downloads/elastic-agent-8.8.1-linux-x86_64.tar.gz: no such file or directory\n\t* creating package file failed: open /opt/Elastic/Agent/data/elastic-agent-026915/downloads/elastic-agent-8.8.1-linux-x86_64.tar.gz: no such file or directory\n\n","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-22T18:07:42.971Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/watcher.go","file.line":309},"message":"No events received within 10m0s, restarting watch call","ecs.version":"1.6.0"}
```

A zip archive of the `/opt` directory containing the state of the agent while the problem was happening is attached below.

[opt.zip](https://github.com/elastic/elastic-agent/files/11849633/opt.zip)

**Comment by ycombinator** [comment]
I've been trying to reproduce this bug in a couple of different ways and haven't been able to so far.  I essentially tried to make the Upgrade Watcher fail either the crash checker (by making the Agent crash soon after it starts, right after [this block](https://github.com/elastic/elastic-agent/blob/dfd9554406f581660747663d15476c636095fa20/internal/pkg/agent/cmd/run.go#L208-L213)) or the error checker (by upgrading to an Agent build with nothing in the `components/` folder).  My attempts were with the target Agent built off `main`.  

I also looked in the attached `opt.zip` folder but can't figure out what happened.  I almost wish Agent automatically turned on debug-level logging when an Upgrade started and then turned it off once the upgrade or rollback was completed.

**Comment by pierrehilbert** [comment]
@ycombinator when you did your tests, was in on a MacOS Monterey instance? 
Because @cmacknz mentioned he observed it on this platform so maybe it's not happening on other operating system.

**Comment by ycombinator** [comment]
> @ycombinator when you did your tests, was in on a MacOS Monterey instance? Because @cmacknz mentioned he observed it on this platform so maybe it's not happening on other operating system.

Ah yes, I tried it on Linux after seeing the `/opt` folder mentioned in https://github.com/elastic/elastic-agent/issues/2264#issuecomment-1604402705.  But you're right, the original issue does mention MacOS so I will try it on that now.

**Comment by ycombinator** [comment]
Testing on MacOS Ventura, upgrading from Agent built from main (a2b1c15a329595ddc599672ff68d0bb073a67fba) / 8.10.0  is giving me this error:
```
$ sudo elastic-agent upgrade 8.12.0 --skip-verify --source-uri file:///Users/shaunak/development/github/elastic-agent/build/distributions
Error: Failed trigger upgrade of daemon: fork/exec /Library/Elastic/Agent/elastic-agent.app/Contents/MacOS/elastic-agent: no such file or directory
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.10/fleet-troubleshooting.html
``

If I look in the Agent logs, I see a bit more detail on this error:

```

**Comment by cmacknz** [comment]
One thing to watch is that Ventura does not like executables that are not notarized. If you are using a snapshot version make sure the binary is signed, and if it isn't check that this reproduces with an official release.

To check the signature run

```
❯ cd ../elastic-agent-8.6.2-darwin-aarch64
~/Downloads/elastic-agent-8.6.2-darwin-aarch64 ········································ 10:52:05 AM
❯ codesign -dvvvv ./elastic-agent
Executable=/Users/cmackenzie/Downloads/elastic-agent-8.6.2-darwin-aarch64/data/elastic-agent-913c02/elastic-agent.app/Contents/MacOS/elastic-agent
Identifier=co.elastic.elastic-agent
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20500 size=383812 flags=0x10000(runtime) hashes=11987+3 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=721664
Hash type=sha256 size=32
CandidateCDHash sha256=89cb5d1a0429f561d263e5de13186d1ec47f7c60
CandidateCDHashFull sha256=89cb5d1a0429f561d263e5de13186d1ec47f7c6033d8347714b5ac31a4177a22
Hash choices=sha256
CMSDigest=89cb5d1a0429f561d263e5de13186d1ec47f7c6033d8347714b5ac31a4177a22
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=22904832
Executable Segment flags=0x1
Page size=4096
CDHash=89cb5d1a0429f561d263e5de13186d1ec47f7c60
Signature size=8936
Authority=Developer ID Application: Elasticsearch, Inc (2BT3HPN62Z)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Feb 13, 2023 at 12:14:18 PM
Info.plist entries=7
TeamIdentifier=2BT3HPN62Z
Runtime Version=11.3.0
Sealed Resources version=2 rules=13 files=0
Internal requirements count=1 size=184
```

The following lines are the important parts (in this case this was 8.6.2):

```
Signature size=8936
Authority=Developer ID Application: Elasticsearch, Inc (2BT3HPN62Z)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=Feb 13, 2023 at 12:14:18 PM
```

**Comment by ycombinator** [comment]
Thanks @cmacknz.  I ran `codesign -dvvvv ./elastic-agent` on the `8.10.0-SNAPSHOT` version of Agent I built from the latest `main`, and I don't see the lines you mentioned in the output at all.  

```
$ cd /tmp/elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64
$ codesign -dvvvv ./elastic-agent
Executable=/private/tmp/elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64/data/elastic-agent-a2b1c1/elastic-agent.app/Contents/MacOS/elastic-agent
Identifier=a.out
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=516414 flags=0x20002(adhoc,linker-signed) hashes=16135+0 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=721664
Hash type=sha256 size=32
CandidateCDHash sha256=5e719c77ba6d6c2fa0895e43dcd7a21823854396
CandidateCDHashFull sha256=5e719c77ba6d6c2fa0895e43dcd7a21823854396b3d6b7720b6cbe5d5b24309c
Hash choices=sha256
CMSDigest=5e719c77ba6d6c2fa0895e43dcd7a21823854396b3d6b7720b6cbe5d5b24309c
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=31129600
Executable Segment flags=0x1
Page size=4096
Launch Constraints:
	None
CDHash=5e719c77ba6d6c2fa0895e43dcd7a21823854396
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none
```

I'm guessing that means the executable isn't notarized.  In any case, there's a new bug (see https://github.com/elastic/elastic-agent/issues/3210) that affects upgrades on MacOS from Agent's built from the latest `main`.  So I'll continue trying to reproduce this bug here with a released version of Agent instead.

**Comment by cmacknz** [comment]
I've been trying to think of reasons why this might have happened. Looking at the watcher logs we do have:

```json
{"log.level":"error","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"upgrade/error_checker.go","file.line":82},"message":"error checker notifying failure of agent","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"upgrade/error_checker.go","file.line":93},"message":"error checker notifying failure of applications","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"cmd/watch.go","file.line":170},"message":"Agent Error detectedagent in a failed state","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"cmd/watch.go","file.line":101},"message":"Error detected proceeding to rollback: %vagent in a failed state","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"upgrade/step_relink.go","file.line":36},"message":"Changing symlink","symlink_path":"/opt/Elastic/Agent/elastic-agent","new_path":"/opt/Elastic/Agent/data/elastic-agent-026915/elastic-agent","prev_path":"/opt/Elastic/Agent/elastic-agent.prev","ecs.version":"1.6.0"}
```

We see the log line from 8.5.1 indicating that `ChangeSymlink` was called:

https://github.com/elastic/elastic-agent/blob/ebf2fe72ac1e4b589aeee5f5a5fc92bd9acf8e33/internal/pkg/agent/application/upgrade/step_relink.go#L42

We don't see the log line indicating that the watcher is restarting the agent:

https://github.com/elastic/elastic-agent/blob/ebf2fe72ac1e4b589aeee5f5a5fc92bd9acf8e33/internal/pkg/agent/application/upgrade/rollback.go#L47

We also don't see any messages indicating that the watcher failed, however the lack of the `Restarting` message might be a hint that this is in fact what happened. The state of the agent directory indicates that while we did see a log message indicating the symlink was being changed this didn't actually happen. The symlink still points to the v8.8.1 agent:

```
lrwxrwxrwx@  1 cmackenzie  staff      39 Jun 20 22:37 elastic-agent -> data/elastic-agent-4ac18b/elastic-agent
```

If this did fail it probably failed somewhere in this block because the symlink did not actually change and there is no `.prev` link in the directory:

https://github.com/elastic/elastic-agent/blob/ebf2fe72ac1e4b589aeee5f5a5fc92bd9acf8e33/internal/pkg/agent/application/upgrade/step_relink.go#L49-L54

One reason we might not have any error logs is that the zap logger our logging package is based on buffers log messages, and we don't call https://pkg.go.dev/go.uber.org/zap#SugaredLogger.Sync before the logger exits on error. This means there might have been log messages but they were never written to disk.

https://github.com/elastic/elastic-agent/blob/ebf2fe72ac1e4b589aeee5f5a5fc92bd9acf8e33/internal/pkg/agent/cmd/watch.go#L50-L53

At minimum we should start calling the `Sync` method of our logger before exiting from the agent or the watcher. We should probably also start thinking of reasons why changing the symlink would fail.

**Comment by cmacknz** [comment]
It is also possible that the watcher was simply interrupted by a system restart or similar right before changing the symlink and it never resumed.

We should also directly look for reasons in the code that would cause `/opt/Elastic/Agent/data/tmp/elastic-agent-control.sock: connect: no such file or directory`, there probably aren't that many and we must have hit one of them.

**Comment by ycombinator** [comment]
> It is also possible that the watcher was simply interrupted by a system restart or similar right before changing the symlink and it never resumed.

This seems to be the most likely explanation.  

The first log line from the upgrade watcher is around `01:48:11`.  

```
{"log.level":"error","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"upgrade/error_checker.go","file.line":82},"message":"error checker notifying failure of agent","ecs.version":"1.6.0"}
```

Ideally we would have more logs from the Upgrade Watcher to know exactly when it started but, alas, such logging is only at the `DEBUG` level:

https://github.com/elastic/elastic-agent/blob/34ac8f91c5c4046a678afbeac8c471ae2fd50e17/internal/pkg/agent/application/upgrade/rollback.go#L125

But we can take a _guess_ as to when the Upgrade Watcher was started.  It would've been right before the Agent was restarted after upgrade, at around `01:47:41`:

```
{"log.level":"info","@timestamp":"2023-06-21T01:47:41.169Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":204},"message":"Restarting after upgrade","new_version":"8.5.1","prev_version":"8.8.1","hash":"4ac18b","home":"/opt/Elastic/Agent/data/elastic-agent-026915","ecs.version":"1.6.0"}
```

The _last_ log line from the Upgrade Watcher is around `01:48:11`:

```
{"log.level":"info","@timestamp":"2023-06-21T01:48:11.138Z","log.origin":{"file.name":"upgrade/step_relink.go","file.line":36},"message":"Changing symlink","symlink_path":"/opt/Elastic/Agent/elastic-agent","new_path":"/opt/Elastic/Agent/data/elastic-agent-026915/elastic-agent","prev_path":"/opt/Elastic/Agent/elastic-agent.prev","ecs.version":"1.6.0"}
```

And then, in an entirely new log file, `elastic-agent-20230621-2.ndjson`, we see this solitary log entry from the Upgrade Watcher, at around `01:57:41`:

```
{"log.level":"info","@timestamp":"2023-06-21T01:57:41.075Z","log.origin":{"file.name":"cmd/watch.go","file.line":166},"message":"Grace period passed, not watching","ecs.version":"1.6.0"}
```

The timestamp of this log entry, `01:57:41` is exactly 10 minutes after our guess of when the Upgrade Watcher might've been started, around `01:47:41`. 

This could happen because the Upgrade Watcher, after a restart, read the `UpdatedOn` value from the Upgrade Marker file and calculated the grace period as 10 minutes from then: https://github.com/elastic/elastic-agent/blob/34ac8f91c5c4046a678afbeac8c471ae2fd50e17/internal/pkg/agent/cmd/watch.go#L186-L196

And then the Upgrade Watcher would've started monitoring the running Agent, forgetting that it was actually in the midst of a rollback in it's previous life, and that monitoring would've succeeded.  Unfortunately all the informational log messages in the `CrashChecker` and `ErrorChecker` are at the `DEBUG` level so we can't prove from logs that they ran after a restart.

As for why this sequence of events would break the socket, I need to investigate the code paths involved but my guess is it has something to do with how the restarted Upgrade Watcher, which would be running as the _new_ (`8.8.1`) Agent's `watch` sub-command, did the `Cleanup()` step after its grace period elapsed and it "succeeded": https://github.com/elastic/elastic-agent/blob/34ac8f91c5c4046a678afbeac8c471ae2fd50e17/internal/pkg/agent/cmd/watch.go#L117

I'm ending my day here now but I'll update this section or add a comment with what I find.

---

In the longer term, I think we need a project to make the Upgrade Watcher re-entrant, probably by keeping track of its last action in the upgrade marker file and by making all (or at least as many as possible) of its actions idempotent. That'll allow the Upgrade Watcher to survive restarts and pick up where it left off.

In the immediate term, I think we should improve the logging in the Upgrade Watcher. Specifically, I think we should change all `DEBUG` level messages to `INFO` level in the Upgrade Watcher execution path and also over here: https://github.com/elastic/elastic-agent/blob/34ac8f91c5c4046a678afbeac8c471ae2fd50e17/internal/pkg/agent/application/upgrade/rollback.go#L125

I also think, across the board, all Upgrade Watcher logs should include it's own PID.  This would tell us if/when the Upgrade Watcher might've been restarted. 

And perhaps all Upgrade Watcher logs should also include the Agent version / hash it's running from, but this might be unnecessary since we know that, [starting from `8.10.0`](https://github.com/elastic/elastic-agent/pull/3140), Agent will always execute the post-upgrade Agent's `watch` sub-command.

**Comment by ycombinator** [comment]
> We should also directly look for reasons in the code that would cause `/opt/Elastic/Agent/data/tmp/elastic-agent-control.sock: connect: no such file or directory`, there probably aren't that many and we must have hit one of them.

I started looking into this.  There is one place in the production (as in, not testing-related) code where that socket path is created: https://github.com/elastic/elastic-agent/blob/0ba85eaf7265882eec9fe7f3bc9fe21570544e6d/pkg/control/addr.go#L27

That line is part of this function: https://github.com/elastic/elastic-agent/blob/0ba85eaf7265882eec9fe7f3bc9fe21570544e6d/pkg/control/addr.go#L19-L34

As you can see from the logic of that function, we would only get to line 27 if `info.RunningInstalled()` returned `false`.  Looking at `info.RunningInstalled()`: https://github.com/elastic/elastic-agent/blob/0ba85eaf7265882eec9fe7f3bc9fe21570544e6d/internal/pkg/agent/application/info/state.go#L20-L29

Looking under the `/opt/Elastic/Agent` folder (from the `opt.zip` [attached](https://github.com/elastic/elastic-agent/issues/2264#issuecomment-1604402705) to this issue), there is no `.installed` file present. This would cause `info.RunningInstalled()` to return `false`, which would then cause Agent to resolve the socket address to `unix:///opt/Elastic/Agent/data/tmp/elastic-agent-control.sock`, a file that wouldn't exist.

So then the next question is: why is there no `.installed` file present under `/opt/Elastic/Agent`, given that this file is not only created on installation (`elastic-agent install`) but also during an upgrade; see https://github.com/elastic/elastic-agent/blob/0ba85eaf7265882eec9fe7f3bc9fe21570544e6d/internal/pkg/agent/cmd/run.go#L567-L602

Two possibilities are:
* The `8.8.1` Agent was never actually started so this `handleUpgrade()` function never got executed, or
* For some reason the Upgrade Marker file was not present so `handleUpgrade()` returned early, on line 578.

**Comment by ycombinator** [comment]
One other thing I noticed was the last modified time of the `/opt/Elastic/Agent/elastic-agent` symlink file is `Jun 20 19:37` (Pacific time) == `Jun 21 02:37` UTC. 

```
$ ls -l elastic-agent
lrwxr-xr-x@ 1 shaunak  wheel  39 Jun 20 19:37 elastic-agent -> data/elastic-agent-4ac18b/elastic-agent
```

I couldn't find anything in the available logs around this timestamp suggesting the modification of this symlink.

```
$ rg '2023-06-21T02:3' elastic-agent-20230*.ndjson
elastic-agent-20230621-1.ndjson
81:{"log.level":"info","@timestamp":"2023-06-21T02:38:52.971Z","log.logger":"composable.providers.docker","log.origin":{"file.name":"docker/watcher.go","file.line":309},"message":"No events received within 10m0s, restarting watch call","ecs.version":"1.6.0"}
```

This makes me wonder if this symlink was tampered by hand or if some process (Agent or Upgrade Watcher) changed it but didn't write any logs about it for some odd reason.

**Comment by ycombinator** [comment]
Given my last three comments on this issue, I have to admit that I'm having a real hard time trying to piece together what happened. I haven't been able to come up with a single theory that would be consistent with what we can see in the logs and the state of the `/opt/Elastic/Agent` folder. 😞 

As dissatisfying as this is, I have some ideas for making such investigations easier on ourselves going forward. The ideas are all around improving the logging during the upgrade process. Specifically:

- We should change all `DEBUG` level messages to `INFO` level in the upgrade process, whether that's the steps that happen in the Agent or in the Upgrade Watcher.
- When an Agent first starts up (the `elastic-agent run` execution path), we should log it's version (including hash) and PID as early as possible. In the context of an upgrade, this will make it a bit easier to understand which version — pre-upgrade or post-upgrade — of the Agent is actually running at any given time.
- Similarly, when the Upgrade Watcher process (the `elastic-agent watch` execution path), we should log it's version (including hash) and PID as early as possible. I would even go as far as logging the PID in every Upgrade Watcher log entry, since sometimes we seem to get truncated logs from it.
- The Upgrade Watcher is always invoked from the "main" Agent process, either as part of starting an upgrade or if the Agent process gets restarted for some reason during an ongoing upgrade. At this time the Agent should log the PID of the Upgrade Watcher process that it has forked off. This will help correlate the instance of Agent with the instance of the Upgrade Watcher it forked off.
- > At minimum we should start calling the Sync method of our logger before exiting from the agent or the watcher. 
   This has been done as part of https://github.com/elastic/elastic-agent/pull/3245.

I see the above improvements as part of the Agent Upgrade tracking and reporting project. It will help us identify where and how upgrades are failing. 

WDYT @cmacknz @pierrehilbert?

**Comment by pierrehilbert** [comment]
Upgrades are so critical and are not happening everyday so I'm in favor of the log level change and to add some additional useful information when upgrades are performed.
Let's try to make this less difficult to investigate and as smooth as possible to understand what is happening for us and for our users.

**Comment by cmacknz** [comment]
Agreed, all of the suggestions in https://github.com/elastic/elastic-agent/issues/2264#issuecomment-1692542941 are great and should be implemented.

**Comment by ycombinator** [comment]
Thanks @pierrehilbert and @cmacknz.  I will put up a PR with the changes mentioned in https://github.com/elastic/elastic-agent/issues/2264#issuecomment-1692542941.

**Comment by cmacknz** [comment]
We have more or less observed this in our own integration tests, possibly this was caused by https://github.com/elastic/elastic-agent/issues/2706 where a previous instance of the upgrade watcher was still running when a new upgrade was attempted.

**Comment by cmacknz** [comment]
I have a strong suspicion now that the root cause for this is https://github.com/elastic/elastic-agent/issues/2706. Prioritizing that issue along similarly to this one since it is likely the root cause for this. CC @pierrehilbert

**Comment by blakerouse** [comment]
With #2706 being fixed and all the other upgrade improvements. I believe this needs to be validated to see if its still an issue. Very likely that this is no longer an issue.

**Comment by cmacknz** [comment]
The only place we ever managed to reproduce anything like this was in our integration tests when the watcher interpreted an uninstall as a crash.

I'm in favor of closing this and reopening it if we get another occurrence, otherwise it'll be open indefinitely. We have made improvements in this area that we believe should prevent this.
