### ISSUE TITLE
[8.6.2]: Ubuntu agent gets unhealthy on installation temporarily.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2272]
**Similar issue under:** https://github.com/elastic/elastic-agent/issues/2145
 
**Kibana version:** 8.6.2 BC2 Kibana cloud environment

**Host OS:** AWS Ubuntu 22

**Build details:**
VERSION: 8.6.2 BC2 
BUILD: 59020
COMMIT: aabd37e8a9069bed4f63b8c457a6829f4581ab97
Artifact Link: https://staging.elastic.co/8.6.2-ca679c34/downloads/beats/elastic-agent/elastic-agent-8.6.2-linux-x86_64.tar.gz

**Preconditions:**
1. 8.6.2 BC2 Kibana cloud environment should be available.
2. Agent Policy should be available with System integration.
3. Another agent policy with System and Endpoint defend integration should be available.

**Steps to reproduce:**
1. Install ubuntu agents using both the policies.
2. Observe agents are installed Unhealthy under Agents tab.
3. Observe agent remain unhealthy for quite a long time and then itself gets Healthy.

**Note:**
- This issue is reproducible multiple times on different builds and fresh VMs.

**Screenshots:**
![5](https://user-images.githubusercontent.com/77374876/218968974-e444067e-c78a-4c30-b808-0c6fce6deff2.JPG)
![6](https://user-images.githubusercontent.com/77374876/218968980-7027ef09-2fcc-4706-8edc-cf14b255c0c0.JPG)

**Logs:**
**When installed with only System integration:**
[[System]elastic-agent-diagnostics-2023-02-14T17-49-25Z-00.zip](https://github.com/elastic/elastic-agent/files/10740646/System.elastic-agent-diagnostics-2023-02-14T17-49-25Z-00.zip)

**When installed with both System and Endpoint defend integrations:**
[[Endpoint]elastic-agent-diagnostics-2023-02-14T17-45-11Z-00.zip](https://github.com/elastic/elastic-agent/files/10740648/Endpoint.elastic-agent-diagnostics-2023-02-14T17-45-11Z-00.zip)

**Debug level logs:**
[[Debug]elastic-agent-diagnostics-2023-02-15T08-08-24Z-00.zip](https://github.com/elastic/elastic-agent/files/10740744/Debug.elastic-agent-diagnostics-2023-02-15T08-08-24Z-00.zip)

**Expected Result:**
 Agents should remain healthy on installation.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by cmacknz** [comment]
The current state of the agent in all attached diagnostics is healthy, and I can't see any transitions into the Failed or Degraded states in the logs.

Is it possible to try this again and collect diagnostics as soon as the agent reports itself as unhealthy? There is definitely a bug here but I can't tell what it is yet.

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 

Thank you for looking into this.
We have immediately fetched the agent logs when agent was in Unhealthy state.

**Please find below logs:**
[elastic-agent-diagnostics-2023-02-16T06-08-07Z-00.zip](https://github.com/elastic/elastic-agent/files/10752719/elastic-agent-diagnostics-2023-02-16T06-08-07Z-00.zip)

**Screenshot:**
![18](https://user-images.githubusercontent.com/77374876/219283549-d9f964e3-d569-4d59-bc40-252adeb98979.jpg)

Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment]
Thanks. What I see is that every component and unit is healthy except for endpoint, which is in the starting state:

```
  state:
    state: 0
    message: 'Starting: endpoint service runtime'
    units:
      ? unittype: 1
        unitid: endpoint-default
      : state: 0
        message: 'Starting: endpoint service runtime'
      ? unittype: 0
        unitid: endpoint-default-400f2851-fc00-419a-b3f5-65f5038bc978
      : state: 0
        message: 'Starting: endpoint service runtime'
```

The very last log line is the agent marking endpoint as healthy:

```json
{"log.level":"info","@timestamp":"2023-02-16T06:08:21.882Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":855},"message":"Component state changed endpoint-default (STARTING->HEALTHY): Healthy: communicating with endpoint service","log":{"source":"elastic-agent"},"component":{"id":"endpoint-default","state":"HEALTHY","old_state":"STARTING"},"ecs.version":"1.6.0"}
```

I still can't tell why the agent is unhealthy unfortunately.

**Comment by cmacknz** [comment]
I can see from the message in Fleet that we didn't quite catch the agent in the same state, because the agent state is reported as starting in Fleet but Healthy in the diagnostics.

This is the source of the message we can see in the Fleet screenshot:

https://github.com/elastic/elastic-agent/blob/9c6c5ae88001bff1756e31ff679d52456b835fde/internal/pkg/agent/application/coordinator/coordinator.go#L410-L411

@amolnater-qasource as soon as you observe the agent as unhealthy can you run `sudo elastic-agent status --output=json` and provide the output here? That will likely be much faster than diagnostics and will have the information I am looking for.

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 

We have revalidated this issue on 8.6.2 released kibana cloud build and observed agent going unhealthy on installation.
- We have installed agent going unhealthy with and without Endpoint defend integration in the Agent policy.

**Logs when Endpoint integration is not added:**
[elastic-agent-diagnostics-2023-02-17T04-17-52Z-00.zip](https://github.com/elastic/elastic-agent/files/10763187/elastic-agent-diagnostics-2023-02-17T04-17-52Z-00.zip)


<details><summary><B>Output for `sudo elastic-agent status --output=json`:[Every component is HEALTHY]</B></summary>
<p>

``` 
{
    "info": {
        "id": "9cf86f0c-460f-4518-85dd-4adab8efa123",
        "version": "8.6.2",
        "commit": "913c02bea9b13dec4d5c5f3057b5b397344e3298",
        "build_time": "2023-02-13 16:51:45 +0000 UTC",
        "snapshot": false
    },
    "state": 2,
    "message": "Running",
    "components": [
        {
            "id": "system/metrics-default",
            "name": "system/metrics",
            "state": 2,
            "message": "Healthy: communicating with pid '1764'",
            "units": [
                {
                    "unit_id": "system/metrics-default-system/metrics-system-57479aa5-ab66-48de-9588-57070cb67d1e",
                    "unit_type": 0,
                    "state": 2,
                    "message": "Healthy"
                },
                {
                    "unit_id": "system/metrics-default",
                    "unit_type": 1,
                    "state": 2,
                    "message": "Healthy"
                }
            ],
            "version_info": {
                "name": "beat-v2-client",
                "version": "8.6.2",
                "meta": {
                    "build_time": "2023-02-12 04:40:38 +0000 UTC",
                    "commit": "9b77c2c135c228c2eedc310f6e975bb1a76169b1"
                }
            }
        },
        {
            "id": "filestream-monitoring",
            "name": "filestream",
            "state": 2,
            "message": "Healthy: communicating with pid '1771'",
            "units": [
                {
                    "unit_id": "filestream-monitoring-filestream-monitoring-agent",
                    "unit_type": 0,
                    "state": 2,
                    "message": "Healthy"
                },
                {
                    "unit_id": "filestream-monitoring",
                    "unit_type": 1,
                    "state": 2,
                    "message": "Healthy"
                }
            ],
            "version_info": {
                "name": "beat-v2-client",
                "version": "8.6.2",
                "meta": {
                    "build_time": "2023-02-12 04:37:19 +0000 UTC",
                    "commit": "9b77c2c135c228c2eedc310f6e975bb1a76169b1"
                }
            }
        },
        {
            "id": "beat/metrics-monitoring",
            "name": "beat/metrics",
            "state": 2,
            "message": "Healthy: communicating with pid '1782'",
            "units": [
                {
                    "unit_id": "beat/metrics-monitoring-metrics-monitoring-beats",
                    "unit_type": 0,
                    "state": 2,
                    "message": "Healthy"
                },
                {
                    "unit_id": "beat/metrics-monitoring",
                    "unit_type": 1,
                    "state": 2,
                    "message": "Healthy"
                }
            ],
            "version_info": {
                "name": "beat-v2-client",
                "version": "8.6.2",
                "meta": {
                    "build_time": "2023-02-12 04:40:38 +0000 UTC",
                    "commit": "9b77c2c135c228c2eedc310f6e975bb1a76169b1"
                }
            }
        },
        {
            "id": "http/metrics-monitoring",
            "name": "http/metrics",
            "state": 2,
            "message": "Healthy: communicating with pid '1790'",
            "units": [
                {
                    "unit_id": "http/metrics-monitoring-metrics-monitoring-agent",
                    "unit_type": 0,
                    "state": 2,
                    "message": "Healthy"
                },
                {
                    "unit_id": "http/metrics-monitoring",
                    "unit_type": 1,
                    "state": 2,
                    "message": "Healthy"
                }
            ],
            "version_info": {
                "name": "beat-v2-client",
                "version": "8.6.2",
                "meta": {
                    "build_time": "2023-02-12 04:40:38 +0000 UTC",
                    "commit": "9b77c2c135c228c2eedc310f6e975bb1a76169b1"
                }
            }
        },
        {
            "id": "log-default",
            "name": "log",
            "state": 2,
            "message": "Healthy: communicating with pid '1756'",
            "units": [
                {
                    "unit_id": "log-default-logfile-system-57479aa5-ab66-48de-9588-57070cb67d1e",
                    "unit_type": 0,
                    "state": 2,
                    "message": "Healthy"
                },
                {
                    "unit_id": "log-default",
                    "unit_type": 1,
                    "state": 2,
                    "message": "Healthy"
                }
            ],
            "version_info": {
                "name": "beat-v2-client",
                "version": "8.6.2",
                "meta": {
                    "build_time": "2023-02-12 04:37:19 +0000 UTC",
                    "commit": "9b77c2c135c228c2eedc310f6e975bb1a76169b1"
                }
            }
        }
    ],
    "FleetState": 2,
    "FleetMessage": ""
}
```

</p>
</details>

**Build details:**
BUILD: 59020
COMMIT: aabd37e8a9069bed4f63b8c457a6829f4581ab97
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.6.2-linux-x86_64.tar.gz

**Screenshot:**
![19](https://user-images.githubusercontent.com/77374876/219549567-8e6f1b3b-fec3-4a92-a946-015c5be8b8b8.JPG)

Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment]
Thank you. The agent itself looks like it should be healthy from the diagnostics and the status output here. I am beginning to wonder if the unhealthy state here is coming from the UI.

@kpollich I see the status page here shows the agent's initial checkin, which will have the Starting state. Is there any chance the UI is treating an agent in the starting state as unhealthy?

https://github.com/elastic/elastic-agent/blob/9c6c5ae88001bff1756e31ff679d52456b835fde/internal/pkg/agent/application/coordinator/coordinator.go#L410-L411

**Comment by kpollich** [comment]
The UI doesn't track the `starting` state, it would appear: 

https://github.com/elastic/kibana/blob/bb35166fc3b9fdf5d2ab8da9849db0aef253f958/x-pack/plugins/fleet/common/types/models/agent.ts#L20-L37

The mapping of agent statuses to the badges displayed in the UI lives here: 

https://github.com/elastic/kibana/blob/bb35166fc3b9fdf5d2ab8da9849db0aef253f958/x-pack/plugins/fleet/public/applications/fleet/sections/agents/components/agent_health.tsx#L62-L80

Looking at this, if the status is reported as `starting`, we'd fall through to the default cases of displaying "Healthy", so I don't think the UI is mapping this incorrectly. 

The only statuses that map to Unhealthy are `error` and `degraded`.

**Comment by cmacknz** [comment]
I managed to reproduce this locally by building an agent docker container modified to log the contents of each checkin to Fleet server. It seems like there is an initial checkin we can send that marks the agent as degraded. 

```diff
diff --git a/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go b/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
index 9062c9d08..a3be4bee2 100644
--- a/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
+++ b/internal/pkg/agent/application/gateway/fleet/fleet_gateway.go
@@ -322,6 +322,10 @@ func (f *fleetGateway) execute(ctx context.Context) (*fleetapi.CheckinResponse,
        components := f.convertToCheckinComponents(state.Components)

        // checkin
+       f.log.Infow("Checking In", "state", agentStateToString(state.State), "message", state.Message,
+               "fleetState", state.FleetState, "fleetMessage", state.FleetMessage,
+               "components", components,
+       )
        cmd := fleetapi.NewCheckinCmd(f.agentInfo, f.client)
        req := &fleetapi.CheckinRequest{
                AckToken:   ackToken,
```

I don't always observe the degraded state in the UI because it is frequently followed up with a checkin where the agent reports itself as healthy. What I suspect happens is that the initial degraded checkin can be the only checkin, in which case it persists for the 5 minute checkin interval until it is cleared.

```json
{
  "log.level": "info",
  "@timestamp": "2023-02-23T19:37:23.679Z",
  "log.origin": {
    "file.name": "fleet/fleet_gateway.go",
    "file.line": 325
  },
  "message": "Waiting for initial configuration and composable variables",
  "log": {
    "source": "elastic-agent"
  },
  "state": "DEGRADED",
  "fleetState": "STARTING",
  "fleetMessage": "",
  "components": [],
  "ecs.version": "1.6.0"
}
{
  "log.level": "info",
  "@timestamp": "2023-02-23T19:37:26.788Z",
  "log.origin": {
    "file.name": "fleet/fleet_gateway.go",
    "file.line": 325
  },
  "message": "Running",
  "log": {
    "source": "elastic-agent"
  },
  "state": "online",
  "fleetState": "HEALTHY",
  "fleetMessage": "",
  "components": [
    {
      "id": "filestream-monitoring",
      "type": "filestream",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '50'",
      "units": [
        {
          "id": "filestream-monitoring",
          "type": "output",
          "status": "STARTING",
          "message": "Starting: spawned pid '50'"
        },
        {
          "id": "filestream-monitoring-filestream-monitoring-agent",
          "type": "input",
          "status": "STARTING",
          "message": "Starting: spawned pid '50'"
        }
      ]
    },
    {
      "id": "beat/metrics-monitoring",
      "type": "beat/metrics",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '60'",
      "units": [
        {
          "id": "beat/metrics-monitoring-metrics-monitoring-beats",
          "type": "input",
          "status": "STARTING",
          "message": "Starting: spawned pid '60'"
        },
        {
          "id": "beat/metrics-monitoring",
          "type": "output",
          "status": "STARTING",
          "message": "Starting: spawned pid '60'"
        }
      ]
    },
    {
      "id": "http/metrics-monitoring",
      "type": "http/metrics",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '72'",
      "units": [
        {
          "id": "http/metrics-monitoring-metrics-monitoring-agent",
          "type": "input",
          "status": "STARTING",
          "message": "Starting: spawned pid '72'"
        },
        {
          "id": "http/metrics-monitoring",
          "type": "output",
          "status": "STARTING",
          "message": "Starting: spawned pid '72'"
        }
      ]
    },
    {
      "id": "log-default",
      "type": "log",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '31'",
      "units": [
        {
          "id": "log-default",
          "type": "output",
          "status": "STARTING",
          "message": "Starting: spawned pid '31'"
        },
        {
          "id": "log-default-logfile-system-85fd90b5-4329-49b2-bbb1-45155d2ed975",
          "type": "input",
          "status": "STARTING",
          "message": "Starting: spawned pid '31'"
        }
      ]
    },
    {
      "id": "system/metrics-default",
      "type": "system/metrics",
      "status": "HEALTHY",
      "message": "Healthy: communicating with pid '41'",
      "units": [
        {
          "id": "system/metrics-default-system/metrics-system-85fd90b5-4329-49b2-bbb1-45155d2ed975",
          "type": "input",
          "status": "STARTING",
          "message": "Starting: spawned pid '41'"
        },
        {
          "id": "system/metrics-default",
          "type": "output",
          "status": "STARTING",
          "message": "Starting: spawned pid '41'"
        }
      ]
    }
  ],
  "ecs.version": "1.6.0"
}
```

**Comment by pchila** [comment]
The agent was mapping the `STARTING` state to `DEGRADED` for the fleet checkin (on my local env though this would be overwritten by another checkin ~3s later presenting the agent as HEALTHY).
I added a specific case for the starting state to be mapped as `starting` in the fleet checking since the badges displayed in https://github.com/elastic/kibana/blob/bb35166fc3b9fdf5d2ab8da9849db0aef253f958/x-pack/plugins/fleet/public/applications/fleet/sections/agents/components/agent_health.tsx#L62-L80 will display the agent as healthy in such a case (as explained by @kpollich in his comment above).

@cmacknz @kpollich  could you please give a look at the solution and check if there are issues that come with it ?
Could it be interesting to keep a journal of agent checkins (something like the last 7 days or 40 hours or something) so that users can check the health of agents more easily? Maybe @nimarezainia could gauge the usefulness of something like that ?

**Comment by cmacknz** [comment]
> Could it be interesting to keep a journal of agent checkins (something like the last 7 days or 40 hours or something) so that users can check the health of agents more easily?

Yes. The agent only checks in every 5 minutes unless there are new agent policy changes or actions to post. We can just keep the Info log we needed to add to debug this problem, it shouldn't add that much noise to the logs. If we are concerned about it we can put it at the debug level.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.9.0 BC3 Kibana cloud environment and found it **fixed now**.

**Observations:**
- Ubuntu agent now remains Healthy on installation.

**Build details:**
VERSION: 8.9.0 BC3
BUILD: 64584
COMMIT: fc463b96275c55dc44524f79f617b0026b7f8667
https://staging.elastic.co/8.9.0-0d830bd0/downloads/beats/elastic-agent/elastic-agent-8.9.0-linux-x86_64.tar.gz

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/329dac7e-8d40-4d10-a84c-1a73034f5ed5



Hence, we are marking this issue as QA:Validated.
Thanks!
