### ISSUE TITLE
Long shutdown and graceful kills results in faulty upgrade

### ISSUE THREAD

**Issue by michalpristas** [elastic/elastic-agent#2274]
When upgrade is performed and component refuses to shut down it is killed gracefully. 
This results in app state being changed to fault. 
Problem is that watcher is already running and monitoring state which is unhealthy so it decides to perform a rollback. New version was not even tried so far.

**Comment by cmacknz** [comment]
@pierrehilbert this came from an SDH we will need to get this into 8.7 as a bug fix. It's in the current sprint to see if we can fit it in before the next one starts.

**Comment by michalpristas** [comment]
not reproducible on v2 versions. happens pre-V2
