### ISSUE TITLE
[Fleet]: 7.17.9 agent unable to upgrade to 8.6.1 version on released 8.6.1 Kibana build.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/elastic-agent#2284]
**Kibana version:** 8.6.1 Prod Kibana cloud environment

**Host OS:** Ubuntu

**Build details:**
VERSION: 8.6.1 
BUILD: 58934
COMMIT: 4c2492450a50cd000fcd85edf668b75828686196
Artifact Link: https://www.elastic.co/downloads/past-releases/elastic-agent-7-17-9

**Preconditions:**

- 8.6.1 Prod Kibana cloud environment should be available.
- Agent Policy should be available with System and Endpoint defend integrations.

**Steps to reproduce:**

- Install lower version 7.17.9 agents using agent policy.
- Wait for agent to generate logs and data streams properly on Fleet UI.
- Trigger agent upgrade from Fleet-UI and observe agent gets into Updating state.
- Observe Agent gets into offline state after few minutes.
	- later, Agent gets rolled back to 7.17.9 and remains offline.

**Screenshots:**
**Kibana version:** 8.6.1 Prod Kibana cloud environment

**Host OS:** Ubuntu

**Build details:**
VERSION: 8.6.1 
BUILD: 58934
COMMIT: 4c2492450a50cd000fcd85edf668b75828686196
Artifact Link: https://www.elastic.co/downloads/past-releases/elastic-agent-7-17-9

**Preconditions:**

8.6.1 Prod Kibana cloud environment should be available.
Agent Policy should be available with System and Endpoint defend integrations.

**Steps to reproduce:**

- Install lower version 7.17.9 agents using agent policy.
- Wait for agent to generate logs and data streams properly on Fleet UI.
- Trigger agent upgrade from Fleet-UI and observe agent gets into Updating state.
- Observe Agent gets into offline state after few minutes.
	- later, Agent gets rolled back to 7.17.9 and remains offline.

**Screenshots:**
**Kibana version:** 8.6.1 Prod Kibana cloud environment

**Host OS:** Ubuntu

**Build details:**
VERSION: 8.6.1 
BUILD: 58934
COMMIT: 4c2492450a50cd000fcd85edf668b75828686196
Artifact Link: https://www.elastic.co/downloads/past-releases/elastic-agent-7-17-9

**Preconditions:**

8.6.1 Prod Kibana cloud environment should be available.
Agent Policy should be available with System and Endpoint defend integrations.

**Steps to reproduce:**

- Install lower version 7.17.9 agents using agent policy.
- Wait for agent to generate logs and data streams properly on Fleet UI.
- Trigger agent upgrade from Fleet-UI and observe agent gets into Updating state.
- Observe Agent gets into offline state after few minutes.
	- later, Agent gets rolled back to 7.17.9 and remains offline.

**Screenshots:**
- 7.17.9 Agent installed on 8.6.1 Kibana 
![image](https://user-images.githubusercontent.com/72375798/219343844-eba38e7f-dd63-4fbc-affb-e33d702ce965.png)

- Upgrade triggerred
![image](https://user-images.githubusercontent.com/72375798/219343995-ada2fe4c-9b8d-404e-9c39-e07cfb6c73d7.png)

- Agent as updating
![image](https://user-images.githubusercontent.com/72375798/219345891-2f10b3cb-fe0a-41e5-99f9-f91f8b1ddbb2.png)

- Agent after few mins.
![image](https://user-images.githubusercontent.com/72375798/219346006-c4d645f5-b3bd-4f0e-b617-0b3479d36ad0.png)

**Logs:**
[logs-7.17.9-agent.zip](https://github.com/elastic/ingest-dev/files/10755163/logs-7.17.9-agent.zip)
[logs.zip](https://github.com/elastic/ingest-dev/files/10755164/logs.zip)

**Comment by dikshachauhan-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
This should be fixed by https://github.com/elastic/elastic-agent/pull/2256 which should be available in the 8.7 snapshot.

As a work around, upgrading from 7.17.9 to 8.5.3 and then to 8.6.1 should succeed. Can you test if this succeeds?

Also we will need a test case created to capture this to ensure that 7.17.x can always upgrade to the latest 8.x release.

**Comment by dikshachauhan-qasource** [comment]
Hi @cmacknz 

We have validated the issue as per mentioned workaround  steps and found it **working Fine.**

**Observations:**
- Upgrade path: 7.17.9>8.4.3>8.5.3>8.6.1

- Found agent upgraded successfully at each step.

**Build details:**
VERSION: 8.6.1
BUILD: 58934
COMMIT: 4c2492450a50cd000fcd85edf668b75828686196
Artifact Link: https://www.elastic.co/downloads/past-releases/elastic-agent-7-17-9

**Screenshots to refer:**
- 7.17.9 agent installed and initiated to upgrade on 8.4.3 on 8.6.1 kibana
![image](https://user-images.githubusercontent.com/72375798/219604166-99a7de32-6f0e-4a0f-8fd4-ae426079f7cf.png)

- Agent upgraded to 8.4.3
![image](https://user-images.githubusercontent.com/72375798/219604651-f6bedf72-3184-468d-9674-15584b9d82db.png)

- Upgraded to 8.5.3
![image](https://user-images.githubusercontent.com/72375798/219604824-1652644d-1c5b-4660-add2-92696eb7b591.png)
![image](https://user-images.githubusercontent.com/72375798/219604882-1ceab092-8788-433e-8074-fbc5da85ec6b.png)

- Finally upgraded to 8.6.1
![image](https://user-images.githubusercontent.com/72375798/219604977-796e3beb-8070-4cf3-84f0-f0c851358fd5.png)


Further, we will retest this as per the merges available on https://github.com/elastic/elastic-agent/pull/2256.

Thanks!!
