### ISSUE TITLE
[Bug] No data and logs for agent installed with System integration.

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/elastic-agent#230]
**Describe the bug**
No data and logs for agent installed with System integration.

**Build Details:**
```
Version: 8.2.0 SNAPSHOT
Commit: 2a93e80574f9c1052c541bc4083a440a623899e8
Build: 51328
```
**OS**
All

**preconditions**
1. Policy should be exist or created

**Steps to Reproduce**
1. Navigate to fleet tab 
2. Install the agent with policy that contains system integration
3. Observe that endpoint is not displayed under Endpoints tab after successful installation of agent

**Actual Result**
No data and logs for agent installed with System integration.

**Expected Result**
Data and logs should be displayed for agent installed with System integration.

**Screen-Shot**

![image](https://user-images.githubusercontent.com/61860752/159432420-da99aa52-bbef-426e-a581-c18dba8d1582.png)

![image](https://user-images.githubusercontent.com/61860752/159432447-f690a21b-4c17-4a81-b0ba-dd651fb9f5ea.png)

https://user-images.githubusercontent.com/61860752/159431362-0cd17b62-52e0-429f-9c69-d03f0347eef8.mp4

**logs**

[logs.zip](https://github.com/elastic/elastic-agent/files/8322170/logs.zip)

**Comment by deepikakeshav-qasource** [comment]
@manishgupta-qasource please review!!

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by ph** [comment]
This would be linked to an out issue that @lykkin is investigating,  I am going to assign it to you.

**Comment by jlind23** [comment]
@deepikakeshav-qasource Could you test it again as @lykkin reverted the change that was causing this issue.

**Comment by deepikakeshav-qasource** [comment]
Hi Team,

We have validated this issue on latest **8.2.0 SNAPSHOT** and observed that issue is Fixed. 🟢 . 

- Now data and logs for installed agent  is available.

Please find the below testing details:

**Build Details:**
```
Version: 8.2.0 SNAPSHOT
Commit: 130823ac27126f1eca689a186a088f1993fa848a
Build: 51365
```
![image](https://user-images.githubusercontent.com/61860752/159852368-a483f743-5977-4ec1-aa5b-e1b9e3d6f5dd.png)

![image](https://user-images.githubusercontent.com/61860752/159852564-edbebd32-08ac-4b9b-9204-25f5239cf183.png)

Hence, We are closing this issue and marking as QA Validated.

Thanks!!

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  Testcase already exists for this scenario under Fleet test suite at link:
   - [C15282](https://elastic.testrail.io/index.php?/cases/view/15282)

Thanks!
