### ISSUE TITLE
Elastic Agent - Configurable Installation Options

### ISSUE THREAD

**Issue by ScottElastic** [elastic/elastic-agent#2319]
**Configurable Deployment**

Today if someone wants to deploy Elastic Defend, agent install forces installation of beats that will not be used.  Due to disk space concerns, it would be nice to have an RPM or DEB package with only the required beats for the specific integration, for example: just using Elastic Defend.

**Comment by cmacknz** [comment]
The trouble with this is accounting for every possible permutation that could be installed.

As an advanced work around, every binary the agent can run is stored in the components subdirectory. You can delete the ones you never plan to run from this directory before download or distribution and it will still work.

For 8.6.2 we include all of these binaries:

```
~/Downloads/elastic-agent-8.7.0-darwin-aarch64
❯ ls data/elastic-agent-e88a5b/components
LICENSE.txt                     filebeat.spec.yml               module
NOTICE.txt                      filebeat.yml                    modules.d
README.md                       fleet-server                    monitors.d
checksum.yml                    fleet-server.spec.yml           osquery-5.7.0.pkg
elastic-agent-shipper           heartbeat                       osquery-extension.ext
elastic-agent-shipper.spec.yml  heartbeat.reference.yml         osquerybeat
elastic-agent-shipper.yml       heartbeat.spec.yml              osquerybeat.reference.yml
endpoint-security               heartbeat.yml                   osquerybeat.spec.yml
endpoint-security-resources.zip kibana                          osquerybeat.yml
endpoint-security.spec.yml      metricbeat                      packetbeat
fields.yml                      metricbeat.reference.yml        packetbeat.reference.yml
filebeat                        metricbeat.spec.yml             packetbeat.spec.yml
filebeat.reference.yml          metricbeat.yml                  packetbeat.yml
```

If you are confident you will never need heartbeat, you can run `rm data/elastic-agent-e88a5b/components/heartbeat*`. The agent will still install, and you would only get an error if you later installed the synthetics integration. If you wanted to do that would have to restore the files that were deleted.

We used to allow downloading executables on the fly but had frequent problems with agents being temporarily unable to complete the download. Machines that were out of disk space, experiencing temporary DNS or connectivity issues, etc. The agent would appear unhealthy in this case and require someone to investigate to determine why. This has been solved at the cost of an increased installation footprint.

**Comment by jlind23** [comment]
Closing this as won't fix.
Offering different permutation is not the path we took as we rather worked on offering a more lightweight agent : https://github.com/elastic/elastic-agent/issues/3364
