### ISSUE TITLE
Agent gives misleading error message when run without root on mac

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent#2331]
When run without root on Mac OS, agent fails with the message: `Error: could not load agent info: could not update agent ID on disk store: storing generated agent id: failed saving agent info: failed to ensure key: could not get agent key: -25293: The user name or passphrase you entered is not correct.`

This message is confusing and doesn't lead users to the correct solution (which in standalone is typically running with `sudo`). If running as root is a hard requirement then the error message should reflect that.

**Comment by cmacknz** [comment]
Related to https://github.com/elastic/elastic-agent/issues/1707, though fixing the error message here is much easier than allow the agent to run as a non-root user on Mac.

**Comment by nimarezainia** [comment]
@pierrehilbert close this?

**Comment by pierrehilbert** [comment]
I don't think we can: we still need to use the `sudo` command at first when we are passing the Unprivileged parameter to effectively install the Agent without requiring Root privileges.
I will let @blakerouse confirm here.

**Comment by cmacknz** [comment]
I think we can close this, this issue was filed before unprivileged agents for mac was implemented.

Running `./elastic-agent run -e` for 8.15.0 does not give me an error anymore.
