### ISSUE TITLE
[Synthetics] Ensure spec only supports running browser monitors from container

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/elastic-agent#2335]
When going GA, we will only support running browser monitors self-managed (on-prem) through the `elastic-agent-complete` image running a Private Location, and not through Heartbeat / `heartbeat.yml` natively (somewhat related https://github.com/elastic/beats/issues/34506).

ACs:
- Update the [spec file](https://github.com/elastic/elastic-agent/blob/main/specs/heartbeat.spec.yml) to clarify it can only be run from containers

**Comment by emilioalvap** [comment]
Reopening and linking to elastic agent enhancemet: https://github.com/elastic/elastic-agent/issues/2699
