### ISSUE TITLE
Fleet stuck in "Updating..." status when attempting to upgrade agents to v8.6.1 or v8.6.2

### ISSUE THREAD

**Issue by drenze-athene** [elastic/elastic-agent#2343]
# Issue

Since upgrading from Elastic Cloud 8.5.3, I have been unable to manage Elastic Agent integrations through Fleet in Kibana.

I initially upgraded from 8.5.3->8.6.1 and scheduled an Agent upgrade. A few of the agents upgraded as expected, the remaining remained stuck in "Updating..." status in Fleet for more than a week. I later updated to 8.6.2 and continued to experience the same issue.

I cancelled out the "Updating..." status per the instructions [in this post](https://discuss.elastic.co/t/fleet-server-status-stuck-at-updating-but-seems-to-be-working-normally/318193/2), which returned the agents to Healthy status, as promised. A second attempt at upgrading yielded the same results. After cancelling out the "Updating..." status again, I determined that I was able to schedule agents to upgrade immediately and it would usually succeed, as long as they were in "Healthy" status, but if an "Offline" or even a "Not Healthy" agent was included, the upgrade would fail. If I attempted to schedule the update for a later time or with a maintenance window other than "immediately" the upgrade fails.

Additionally, I observed this morning when I checked the "Agent Activity" log in fleet that multiple activities showing "Reassigning X of Y agents to [new policy]" that I executed approximately a week ago are still showing as in progress. However, in this case, when I investigate, all agents have been reassigned to the new policy and are reporting in as expected. I don't know whether the two items are related.

# Deployment

My deployment is:

  * Elastic Cloud 8.6.2
  * Fleet-Managed Elastic Agent in both Windows and Linux
  * Discussion Forum: https://discuss.elastic.co/t/elastic-agents-fail-to-upgrade-from-fleet-shows-updating-status-for-more-than-a-week/325426/12

# Steps to Reproduce

  1. Upgrade Elastic Cloud to 8.6.1 or 8.6.2
  2. Schedule an agent upgrade in Fleet to occur at a specific time.

**Comment by michel-laterman** [comment]
I've added the backport-8.6.0 label even though there is no further 8.6 release planned at this time.

@cmacknz I think we should add this as a known issue to the 8.6 release notes

**Comment by cmacknz** [comment]
To add this as a known issue open a PR against the 8.6 release notes: https://github.com/elastic/observability-docs/blob/main/docs/en/ingest-management/release-notes/release-notes-8.6.asciidoc

Note that you'll need to copy the known issue to each of 8.6.2, 8.6.1, and 8.6.0 if they are all effected. There are plenty of examples there to use as a reference. You can add me as a reviewer.
