### ISSUE TITLE
Allow setting of log level

### ISSUE THREAD

**Issue by honzakral** [elastic/elastic-agent#2345]
**Describe the enhancement:** I would like to be able to set `logging.level` and have it be respected by the agent as well as the *beats processes.

**Describe a specific use case for the enhancement or feature:** the beats `info` log are very chatty, consume a lot of resources, and provide little value. On a kubernetes cluster with a few nodes this can generate thousands of messages per minute.

Possibly a duplicate of  #407 (though that deals with other issues as well)

**Comment by jlind23** [comment]
@honzakral Closing this as done thanks to https://github.com/elastic/elastic-agent/pull/3090

**Comment by honzakral** [comment]
@jlind23 I might be mistaken, but it looks like #3090 only addresses a small part of this issue - setting log level for the agent. It doe not address the bigger issue of controlling the verbosity of filebeat/metricbeat/... logs run by the agent.

**Comment by jlind23** [comment]
@honzakral this log level change will apply to Elastic Agent and the beats running underneath. Where you thinking about applying a different log level to the beats than the Agent one?
