### ISSUE TITLE
[Elastic Agent] Support for Debian 11 platform

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent#235]
Latest Debian and already supported for other stack components.
Linking customer requests here.

**Comment by wakejordan** [comment]
[https://github.com/elastic/elastic-agent/issues/256](url)

**Comment by mdelapenya** [comment]
From e2e standpoint, it would just a matter of running them on Debian 11. Will elaborate a PR including how to add a new platform. In the meantime, @narph you can check this out: https://github.com/elastic/e2e-testing/blob/main/.ci/README.md#available-platforms-file-structure

I will enhance them with more technical details.

**Comment by narph** [comment]
also should add support for Ubuntu 22.04

**Comment by jlind23** [comment]
If e2e tests were added then this can be closed.
