### ISSUE TITLE
Not able to stop the elastic-agent process from service control manager on Windows x64

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#2391]
**Kibana version:** 8.7 BC9 Kibana cloud environment

**Host OS:** 
Windows Server 2022

**Build details:**
VERSION: 8.7.0 BC9
BUILD: 61093
COMMIT: 8eda067283f541c673beb406ae5480da6dab9296
Artifacts: https://staging.elastic.co/8.7.0-1f741fb1/summary-8.7.0.html

**Preconditions:**
1. 8.7 BC9 Kibana cloud environment should be available.
2. Endpoint agent should be installed.

**Steps to reproduce:**
1. Install an endpoint agent 
2. Add Endpoint Defend integration to this policy.
3. Navigate to the service control manager on Windows.
4. Search the Elastic-Agent process and stop it
5. Observe that not able to stop the elastic-agent process from service control manager on Windows x64

**Expected Result:**
 User Should able to stop the elastic-agent process from the service control manager on Windows x64

**Note:** Agent also gets stuck into Stopping state in Services.

**Screen-shot:**

![image (4)](https://user-images.githubusercontent.com/101545338/227457271-c7835a36-9b86-49b5-9551-c2d87536bd1a.png)
![image (6)](https://user-images.githubusercontent.com/101545338/227457511-b27662cc-87f4-429c-8395-07ae1a247211.png)

**Impacted Testcase:**
[#35378](https://elastic.testrail.io/index.php?/cases/view/35378)

**Logs:**
[elastic-agent-diagnostics-2023-03-24T07-40-49Z-00.zip](https://github.com/elastic/elastic-agent/files/11059589/elastic-agent-diagnostics-2023-03-24T07-40-49Z-00.zip)

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource kindly review

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is Done
FYI @jlind23

**Comment by cmacknz** [comment]
Fix will be tracked in https://github.com/elastic/elastic-agent/issues/2394

**Comment by harshitgupta-qasource** [comment]
Hi @cmacknz 

We have revalidated this issue on the latest 8.7.0 BC10 kibana cloud environment and found it **fixed** now.

**Observations:**
- Able to stop the elastic-agent process from the service control manager on Windows x64.

**Build details:**
BUILD: 61093
COMMIT: 8eda067283f541c673beb406ae5480da6dab9296

**Screen-shot**
![image](https://user-images.githubusercontent.com/101545338/228456311-bb926f81-d3e1-4e58-9803-aa97fe87a61c.png)


Hence, we are marking this issue as **QA:Validated**.
Thanks!

**Comment by dikshachauhan-qasource** [comment]
### Bug Conversion

Test-Case not required as this particular checkpoint is already covered in the following testcase:

- https://elastic.testrail.io/index.php?/cases/view/35378

Thanks
