### ISSUE TITLE
Agent Uninstallation got stuck on running uninstallation command on Windows CMD.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#2392]
**Kibana version:** 8.7 BC9 Kibana cloud environment

**Host OS:** 
Windows Server 2022

**Build details:**
VERSION: 8.7.0 BC9
BUILD: 61093
COMMIT: 8eda067283f541c673beb406ae5480da6dab9296
Artifacts: https://staging.elastic.co/8.7.0-1f741fb1/summary-8.7.0.html

**Preconditions:**
1. 8.7 BC9 Kibana cloud environment should be available.
2. Endpoint agent should be installed.

**Steps to reproduce:**
1. Install an endpoint agent 
2. Open the Windows CMD 
3. enter the command `.\elastic-agent.exe uninstall` to uninstall elastic agent
5. Observe that Agent Uninstallation got stuck on running the uninstallation command on Windows CMD.

**Expected Result:**
The agent should be Uninstall on running the uninstallation command on the windows endpoint.

**Screen-shot:**

![image](https://user-images.githubusercontent.com/101545338/227458335-f3dc7921-90ec-4546-8cca-54bcc775546b.png)

**Logs:**
[elastic-agent-diagnostics-2023-03-24T07-40-49Z-00.zip](https://github.com/elastic/elastic-agent/files/11059589/elastic-agent-diagnostics-2023-03-24T07-40-49Z-00.zip)

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is Done
FYI @jlind23

**Comment by harshitgupta-qasource** [comment]
Hi @cmacknz 

We have revalidated this issue on the latest 8.7.0 BC10 kibana cloud environment and found it **fixed** now.

**Observations:**
- Able to Uninstall the agent by running the uninstallation command on the windows endpoint.

**Build details:**
BUILD: 61093
COMMIT: 8eda067283f541c673beb406ae5480da6dab9296

**Screen-shot**
![image](https://user-images.githubusercontent.com/101545338/228462485-a932b80a-b854-421d-b5e3-ea893c4691c0.png)

Hence, we are marking this issue as **QA:Validated**.
Thanks!
