### ISSUE TITLE
Update Docker provider documentation to reflect available keys for condition in docker integration

### ISSUE THREAD

**Issue by gsantoro** [elastic/elastic-agent#2393]
It is very luckily that the available keys at the [doc](https://www.elastic.co/guide/en/fleet/current/docker-provider.html) do NOT correctly reflect what declared in the [code](https://github.com/elastic/elastic-agent/blob/e7419ddc4e492e7e41acd20ec39f570937affe13/internal/pkg/composable/providers/docker/docker.go#L132-L139).

We need to investigate if that's the case and update the documentation accordingly.

**Comment by gsantoro** [comment]
I have verified in a live cluster that the following conditions are working

```
${docker.container.name} != 'elastic-agent-docker'

${docker.container.id} != '05f499cb0c919912b0189462d3d94a4de0ed68d8bf92b9a214fafcaec2af5b66'
```

Here `05f499cb0c919912b0189462d3d94a4de0ed68d8bf92b9a214fafcaec2af5b66` is just an example container id.

**Comment by ChrsMark** [comment]
By looking into the code at https://github.com/elastic/elastic-agent/blob/e7419ddc4e492e7e41acd20ec39f570937affe13/internal/pkg/composable/providers/docker/docker.go#L130-L153

the mapping that the provider will use to populate the dynamic variables will be the following:

```go
{
  mapping: map[string]interface{}{
	  "container": map[string]interface{}{
		  "id":     container.ID,
		  "name":   container.Name,
		  "image":  container.Image,
		  "labels": labelMap,
	  },
}
```
and each field will be prefixed with the `container.` prefix which is the name of the provider. This is how all dynamic providers work.
So @gsantoro  it looks to me that this mapping aligns with what you suggested above, if you also add the `labels` part. 


Then all the events will be enriched with metadata which are coming from the following part:

```go
{
  processors: []map[string]interface{}{
	  {
		  "add_fields": map[string]interface{}{
			  "fields": map[string]interface{}{
				  "id":     container.ID,
				  "name":   container.Name,
				  "image":  container.Image,
				  "labels": processorLabelMap,
			  },
			  "target": "container",
		  },
	  },
  },
}
```
So here the fields will follow the [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-container.html) format like `container.id`, `container.name`, `container.image` and `container.labels`.

What bugs me here is that we use different fields for the dynamic variables (1st mapping) with what we add in the events as metadata. However this comes from the fact that all providers' mapping are prefixed with the name of the provider. @gizas @cmacknz any thoughts on this?

Last but not least @gsantoro I think that unit tests can come handy here to understand the logic. Check https://github.com/elastic/elastic-agent/blob/22231384f80fa5c0bd6a31472808fec9c35e6841/internal/pkg/composable/providers/docker/docker_test.go#L18.

**Comment by tetianakravchenko** [comment]
@ChrsMark 
> and each field will be prefixed with the `container.` prefix which is the name of the provider. This is how all dynamic providers work.

is `container.` prefix is correct here, or should it be `docker.`?

I think instead of `docker.image => docker.container.image` should be `docker.image => docker.container.image.name` according to the [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-container.html)

**Comment by ChrsMark** [comment]
> @ChrsMark
> 
> > and each field will be prefixed with the `container.` prefix which is the name of the provider. This is how all dynamic providers work.
> 
> is `container.` prefix is correct here, or should it be `docker.`?
> 

Yes, you are correct the prefix is the name of the provider hence `docker.`. I managed to mix things there :).

> I think instead of `docker.image => docker.container.image` should be `docker.image => docker.container.image.name` according to the [ECS](https://www.elastic.co/guide/en/ecs/current/ecs-container.html)

You mean to change how the code report this?
