### ISSUE TITLE
agent.logging.level is not respected

### ISSUE THREAD

**Issue by honzakral** [elastic/elastic-agent#2399]
For confirmed bugs, please report:
- Version: 8.6.2
- Operating System: Linux (k8s)
- Steps to Reproduce: set:
```yaml
agent:
  logging:
    level: warning
```

and you still see `info` level logs in the output (both from the agent itself and from the underlying beats - see #2345), for example:
> Updating running component model

**Comment by cmacknz** [comment]
Can you post example logs? We don't switch the logging level until after the log level has been propagated to all the sub-processes so we can debug the process of changing the log level. This will result in a burst of non-warning logs around the time the log level changes, which can be a bit misleading.

**Comment by honzakral** [comment]
@cmacknz I am attaching the diagnostic from a pod that produced over 9k of such messages. I don't see those logs in the diagnostics though - I only see them when I look into Elasticsearch (or `kubectl logs`) for that pod. Could it be I am missing some other configuration?
[diag.tar.gz](https://github.com/elastic/elastic-agent/files/11081518/diag.tar.gz)

**Comment by honzakral** [comment]
Sorry for the noise, I thought removing the `-v` would fix it, but that isn't the case, the logs are still present after it has been removed

**Comment by cmacknz** [comment]
I can confirm that if I set `agent.logging.level: warn` in the configuration of an 8.6.2 agent it doesn't seem to be respected. 

The diagnostics show the same result as the ones that are attached here, the state.yaml omits the overall agent log level and shows each unit at the info level. I can also see info level logs in the log files.

```yaml
    - id: system/metrics-default
      type: 1
      log_level: 2 # This is the info level
```

**Comment by vitalyrychkov** [comment]
Thanks, waiting for the fix, was struggling with the same issue:
https://discuss.elastic.co/t/elastic-agent-ignores-logging-level-setting/332560
