### ISSUE TITLE
Add a new E2E test to confirm that Elastic Agent component logs can be shipped to Fleet

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2402]
## What do we want to do and why? ##

- [x] Depends on https://github.com/elastic/elastic-agent/pull/2292

Implement an E2E test that enrolls an agent in Fleet and ensures that logs are shipped to the expected set of logs datastreams. This tests automates enrolling an agent in Fleet and manually inspect the logs messages in the UI box below.

<img width="1327" alt="Screen Shot 2023-03-27 at 11 09 38 AM" src="https://user-images.githubusercontent.com/3466215/227983563-f95b9c6e-8ed0-4af1-a6cc-0e6c28ca931a.png">

1. Enrolls an Elastic Agent in Fleet. The system integration and agent log monitoring should both be enabled by default.
2. Confirms that log messages are populated for the `logs-elastic_agent-default`, `logs-elastic_agent.filebeat-default` and `logs-elastic_agent.metricsbeat-default` datastreams:
  - Ensure that the log message `"Parsed configuration and determined agent is managed by Fleet"` can be queried from `logs-elastic_agent-default`.
  - Ensure the log message `metricbeat start running.` can be queried from `logs-elastic_agent.filebeat-default`
  -  Ensure the log message `filebeat start running.` can be queried from `logs-elastic_agent.metricsbeat-default`.
4. Confirms that no error level logs or panics can be queried from any of the datastreams above.
5. Unenrolls the Elastic Agent.
6. Uninstalls the Elastic Agent.

The steps in this test touch a large surface area of the agent and Fleet product and would have automatically detected several recent regressions, notably:

- https://github.com/elastic/elastic-agent/issues/2394
- https://github.com/elastic/beats/issues/34716

## Definition of done ##

- [ ] E2E test using our new framework is in place to validate the mentioned scenario.

**Comment by cmacknz** [comment]
This test should also change the agent log level to debug and confirm that each process generates at least one debug log. We'll have to look at some representative logs to find a few that are always generated.

**Comment by amitkanfer** [comment]
Marking this one as P0 as we're keep breaking our debug logs

**Comment by amitkanfer** [comment]
@pierrehilbert what's blocking us here?

**Comment by pierrehilbert** [comment]
Nothing anymore, just updated the status.

**Comment by fearful-symmetry** [comment]
Currently blocked by a handful of bugs and rough edges in the testing framwork. The biggest actual blocker is here: https://github.com/elastic/elastic-agent-libs/issues/127
