### ISSUE TITLE
External=false does not build shipper in the distributions

### ISSUE THREAD

**Issue by alexsapran** [elastic/elastic-agent#2415]
I wanted to build elastic-agent and be able to build everything from HEAD. 

While I was able to have elastic-agent and beats working, I noticed that the shipper component was missing. 
After talking with @leehinman he verified that using the dropin works, but I need to build from source.

For confirmed bugs, please report:
- Version: 8.8.0
- Operating System: 18.04.6 LTS (Bionic Beaver) 
- Steps to Reproduce:

1) Checkout elastic-agent
2) Checkout beats 
3) use `EXTERNAL=false SNAPSHOT=true PACKAGE=tar.gz DEV=true PLATFORMS=linux/amd64 mage package
4) examine the resulted artifact.

**Comment by cmacknz** [comment]
The logic to package beats can be found at:

https://github.com/elastic/elastic-agent/blob/3d73887c9792b5756cdbf053c89d32e6dffc3c23/magefile.go#L804-L825

This assumes that the beats repository has been checked out at the same level as the elastic-agent repository. It then changes to that working directory and invokes `mage package` only if the desired package version doesn't already exist (note that mage is not make and isn't smart enough to know to rebuild the package if it changed).

We can do the exact same thing for the shipper. Assume the repository exists at the same level as the agent and then run the `mage package` command automatically.

The one catch to this is that the agent today works fine without the shipper, so we may want to make building the shipper optional to start. We usually do this with environment variables so something like `SHIPPER=true EXTERNAL=false` to include it. 

I'm not a big fan of the environment variable approach here but this is the fastest path to making this change.

@alexsapran is this something you are planning to try yourself?

**Comment by alexsapran** [comment]
I am following the approach of manually building beats and shipper and then use the drop-in folder to package agent.
I am focusing on supporting the shipper in the benchmark framework. I don't have currently plans to change the build process of elastic-agent.

Another approach would be using the same `EXTERNAL=false` flag but if the shipper repository exists just include it in the build process in that way we don't need to introduce any more new variables to the mix. The downside is that it will build beat and shipper even if you want just one of them.

**Comment by jlind23** [comment]
The shipper project has been cancelled and the binary removed. Closing this issue as won't fix.
