### ISSUE TITLE
[E2E][Linux ][Windows][Mac] Upgrade standalone Elastic Agent 8.X and 7.X 

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent#2430]
## Issue ##

To ensure our upgrade system is working as expected, an E2E test upgrading Agent to the last version available should be in place.
This E2E test should be performed with the System Integration enabled.

## Definition of done ## 

- [ ] An E2E test is testing upgrade for a standalone Elastic from version n-1 to version n.
- [ ] This test should upgrade the stack first (to be similar to our users).
- [ ] Version n-1 should be customizable to let us test different upgrades (for example pre-8.6).

**Comment by faec** [comment]
Edited description to remove Endpoint -- Endpoint presumably doesn't apply to the standalone case since it depends on Fleet.

**Comment by ycombinator** [comment]
Covered by [`TestStandaloneUpgrade`](https://github.com/elastic/elastic-agent/blob/03b5d31eeda94b2f3f7ab83bded45c03738fb5a7/testing/integration/upgrade_standalone_test.go#L25).
