### ISSUE TITLE
8.7.0 and 8.6.2 agents get stuck in the updating state if the osquery.db file cannot be copied to the next version

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2433]
We have observed 8.6.2 agents getting stuck in the updating state. This has so far only been observed on Windows with the OSQuery integration installed.

*Work Around*: Uninstalling the OSQuery integration, performing the upgrade, and then reinstalling is a confirmed work around for this issue.

The primary symptom is an agent that begins an upgrade that never completes. The logs will show that the upgraded started but stops with the final log message being `"Copying run directory"`.

```json
{"log.level":"info","@timestamp":"2023-03-31T12:39:49.527Z","log.origin":{"file.name":"upgrade/step_unpack.go","file.line":42},"message":"Unpacked upgrade artifact","log":{"source":"elastic-agent"},"version":"8.7.0","file.path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-913c02\\downloads\\elastic-agent-8.7.0-windows-x86_64.zip","hash":"fc4a15","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-03-31T12:39:49.527Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":238},"message":"Copying action store","log":{"source":"elastic-agent"},"new_home_path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-fc4a15","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-03-31T12:39:49.527Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":242},"message":"Copying action store path","log":{"source":"elastic-agent"},"from":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-913c02\\action_store.yml","to":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-fc4a15\\action_store.yml","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-03-31T12:39:49.527Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":242},"message":"Copying action store path","log":{"source":"elastic-agent"},"from":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-913c02\\state.yml","to":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-fc4a15\\state.yml","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-03-31T12:39:49.527Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":242},"message":"Copying action store path","log":{"source":"elastic-agent"},"from":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-913c02\\state.enc","to":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-fc4a15\\state.enc","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-03-31T12:39:49.539Z","log.origin":{"file.name":"upgrade/upgrade.go","file.line":264},"message":"Copying run directory","log":{"source":"elastic-agent"},"new_run_path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-fc4a15\\run","old_run_path":"C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-913c02\\run","ecs.version":"1.6.0"}
```

Enabling debug logging reveals that the upgrade is acknowledged as failed because the agent failed to copy one of the files that the osquery integration places in the run directory: `run\\\\osquery-default\\\\osquery\\\\osquery.db\\\\LOCK: The process cannot access the file because it is being used by another process.`

```json
{"log.level":"debug","@timestamp":"2023-03-31T12:39:49.687Z","log.origin":{"file.name":"fleet/fleet_acker.go","file.line":96},"message":"fleet acker: ackbatch, events: []fleetapi.AckEvent{fleetapi.AckEvent{EventType:\"ACTION_RESULT\", SubType:\"ACKNOWLEDGED\", Timestamp:\"2023-03-31T12:39:49.68675+00:00\", ActionID:\"22ab4e04-999d-4dcf-a086-f46115eca4ae\", AgentID:\"3d256348-4c22-43e0-a324-9a37cc8436c1\", Message:\"Action '22ab4e04-999d-4dcf-a086-f46115eca4ae' of type 'UPGRADE' acknowledged.\", Payload:json.RawMessage{0x7b, 0x22, 0x72, 0x65, 0x74, 0x72, 0x79, 0x22, 0x3a, 0x74, 0x72, 0x75, 0x65, 0x2c, 0x22, 0x72, 0x65, 0x74, 0x72, 0x79, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x6d, 0x70, 0x74, 0x22, 0x3a, 0x31, 0x7d}, ActionInputType:\"\", ActionData:json.RawMessage(nil), ActionResponse:map[string]interface {}(nil), StartedAt:\"\", CompletedAt:\"\", Error:\"failed to copy run directory: C:\\\\Program Files\\\\Elastic\\\\Agent\\\\data\\\\elastic-agent-fc4a15\\\\run: open C:\\\\Program Files\\\\Elastic\\\\Agent\\\\data\\\\elastic-agent-913c02\\\\run\\\\osquery-default\\\\osquery\\\\osquery.db\\\\LOCK: The process cannot access the file because it is being used by another process.\"}}","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-03-31T12:39:49.687Z","log.origin":{"file.name":"fleet/fleet_acker.go","file.line":107},"message":"1 actions with ids '22ab4e04-999d-4dcf-a086-f46115eca4ae' acknowledging","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-03-31T12:39:49.687Z","log.origin":{"file.name":"remote/client.go","file.line":162},"message":"Request method: POST, path: /api/fleet/agents/3d256348-4c22-43e0-a324-9a37cc8436c1/acks, reqID: 01GWVTWT5QXFYHPA86H5JPSEG3","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

1. The agent should not consider failures to copy files in the run directory as fatal in the upgrade process. The agent should simply log the failure and continue.
2. The Fleet UI should display the result of the failed upgrade action. This is likely another example of https://github.com/elastic/kibana/issues/154163 and this fix will be tracked in that issue.

**Comment by cmacknz** [comment]
Caused by which is in 8.6.2 and 8.7.0 https://github.com/elastic/elastic-agent/pull/2207

**Comment by cmacknz** [comment]
It may be that an osquery needs to actively be running for this to happen.

I have reworded the description here to specifically mention osquery to reduce the apparent impact of the bug. 

It is theoretically possible for this failure to apply to any file in the run/ directory, but in practice it is likely to only occur with the osquery.db file.

**Comment by cmacknz** [comment]
We believe that the error here might be transient while an upgrade is in progress, and the ideal experience is likely for the agent to retry for a while waiting for any in progress osquery to complete.

We would need to confirm if just waiting for the osquery.db lock to be free is enough to guarantee that any in progress osquery has actually completed.

**Comment by cmacknz** [comment]
@kevinlog do you know if just waiting for the lock to be freed on the osquery.db file is enough to guarantee that any in progress osquery result has succeeded? Does osquerybeat wait to report results to Elasticsearch before exiting when it signalled to shutdown?

**Comment by kevinlog** [comment]
@cmacknz 

> do you know if just waiting for the lock to be freed on the osquery.db file is enough to guarantee that any in progress osquery result has succeeded? Does osquerybeat wait to report results to Elasticsearch before exiting when it signalled to shutdown?

I am not sure about this, would need @aleksmaus to comment.

It's also possible that some queries take quite some time to run, which could leave Agent upgrades pending if we're waiting for locks to be given up.  To me, it seems reasonable that if a user triggers an Agent upgrade, that there will be some interruption of functionality.  It looks like the original PR sought to reduce event duplication on upgrades.  Is it possible to "fall back" in a scenario like this and allow the upgrade to proceed?  If we're looking to get a fix out faster, maybe this is a quicker/safer way to proceed?

Would want @aleksmaus to comment on the above, however.

**Comment by cmacknz** [comment]
@michalpristas let's make sure the implementation here includes test coverage for any errors encountered when attempting to copy the run directory.

**Comment by arvindersingh-qasource** [comment]
Hi @cmacknz 

Thanks for all the information over the ticket.
We have revalidated this issue on upgrading `Kibana v8.7.0` -> `Kibana v8.7.1` and found that issue is still reproducible.

### Please find the below observations
### Build Details
```
VERSION: 8.7.0
BUILD: 61109
COMMIT: 05f12599523732051b84dde0b8d5610e0db2b06d


VERSION: 8.7.1
BUILD: 61183
COMMIT: a499452f20a6fb95ec673d59f20fb9e9185933f5
```

#### Observations
 - Agent was working fine and was in `Healthy` state before upgrading 
![ArvinderTicketBeforeUpgradeTestQuery](https://user-images.githubusercontent.com/106220189/232475074-062e6ed7-c7b5-4e49-8e44-ee6d0f5101bc.PNG)

 - Agent Binary Download URL is Updated to Latest. 
![2](https://user-images.githubusercontent.com/106220189/232475608-dd5aa044-92eb-46bb-a875-1ca5d1d758da.jpg)

 - After Upgrading , Agent went into `Updating` State.
![3](https://user-images.githubusercontent.com/106220189/232475725-8137d6b1-0fa0-4c39-8f1f-6a5f08a4410f.jpg)

 - Agent Logs
![4](https://user-images.githubusercontent.com/106220189/232475829-b024e60e-e986-47cf-95b1-8d95ff2d5585.jpg)


Please let us know, if we are missing anything or if we need to regress this issue on another Kibana versions.

Thanks

**Comment by kevinlog** [comment]
@arvindersingh-qasource thanks for taking another look at the ticket.

It is expected that this issue would still be reproducible when upgrading from 8.7.0 -> 8.7.1 because the upgrade bug would still be present in the 8.7.0 Agent.

We would be able to properly validate this ticket when upgrading from 8.7.1 -> 8.7.2 or 8.8.0.

Let me know if you have any questions.

**Comment by bbs2web** [comment]
I can confirm that we manually re-deployed all agents when updated to 8.7.1 and had to repeat this when subsequently updating to 8.8.0. By this I mean that we had exactly the same issue, whereby agents processing updates will remain in an 'updating' state. This remained the case when us restarting agents a couple of times. Solution was relatively straightforward, running 'elastic-agent uninstall' on either Linux or Windows and then finally re-deploying.

**Comment by yevgenytrcloudzone** [comment]
It's also possible to simply run the install command with force argument (`elastica-agent.exe -install -f ...`).
This will overwrite the current running installation of the agent.

I have also an open ticket in Elastic support regarding this.
