### ISSUE TITLE
Fail to start if the shipper is enabled but the shipper executable cannot be found

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2446]
When starting elastic-agent with a configuration file that enables shipper, but the agent fails to resolve the elastic-agent-shipper component, should fail instead of falling back to Filebeat.

The reason behind this was that when I tried to use the agent with the shipper and I had not previously set up a configured agent to include shipper, it fall back to filebeat giving me the wrong assumption that initially, it worked.
I found that there was a problem with the packaging after doing some investigation as to why I was not seeing the results I was expecting.

Originally reported by @alexsapran

**Comment by pierrehilbert** [comment]
@cmacknz / @leehinman could we close this one with the new shipper plan?

**Comment by cmacknz** [comment]
Still relevant, but the chances this bug is it are significantly reduced. Dropped to P3.

**Comment by blakerouse** [comment]
@cmacknz If the specification file is present and not a binary the Elastic Agent will fail to start. I think the issue here is that packaging doesn't include the specification file unless it can fetch the binary. So this is not really an issue with the Elastic Agent itself.

**Comment by leehinman** [comment]
> I think the issue here is that packaging doesn't include the specification file unless it can fetch the binary. So this is not really an issue with the Elastic Agent itself.

But it would be nice if elastic-agent gave some kind of message that it has a policy that says "start component X" but it doesn't have component X (maybe missing spec file or some other reason).

**Comment by blakerouse** [comment]
It does do that.

**Comment by jlind23** [comment]
@pierrehilbert could this be closed as it is probably not relevant anymore?
