### ISSUE TITLE
[Agent Upgrade]: Agent upgrade fails and goes Unhealthy from 8.1.1>8.2 Snapshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#245]
**Kibana version:**  8.2 Snapshot Kibana cloud environment

**Host OS and Browser version:** Windows,Linux and MAC

**Build details:**
VERSION: 8.2.0 Snapshot
BUILD: 51365
COMMIT: 130823ac27126f1eca689a186a088f1993fa848a
Artifact link for 8.1.1: https://www.elastic.co/downloads/past-releases/elastic-agent-8-1-1

**Preconditions:**
1. 8.2 Snapshot Kibana cloud environment should be available.
2. 8.1.1 lower version agents should be installed.

**Integrations:**
System

**Steps to reproduce:**
1. Login to Kibana environment.
3. Navigate to Fleet>Agents tab.
4. Upgrade lower version agents from the Agents tab.
5. Observe agents gets unhealthy and failed to upgrade to latest version.

**Expected Result:**
Agent should be upgraded to latest version from 8.1.1>8.2 Snapshot.

**Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/8340059/logs.zip)

**Screenshots:**
![10](https://user-images.githubusercontent.com/77374876/159882536-00d4d74e-7165-429e-8455-8a017c7b6605.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by ph** [comment]
Can we retest this scenario?

**Comment by amolnater-qasource** [comment]
Hi @ph 
We have revalidated 8.2 Snapshot Kibana cloud environment and found it **still reproducible**.
- Agent upgrade fails and goes Unhealthy from 8.1.1>8.2 Snapshot.

**Build details:**
VERSION: 8.2.0
BUILD: 51431
COMMIT: a743498436a863e142592cb535b43f44c448851a
Artifact link for 8.1.1: https://www.elastic.co/downloads/past-releases/elastic-agent-8-1-1

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/161003847-19e6096e-4866-4edd-827c-8f9e77c96678.JPG)

**Logs:**
[elastic-agent-diagnostics-2022-03-31T06-52-02Z-00.zip](https://github.com/elastic/elastic-agent/files/8387097/elastic-agent-diagnostics-2022-03-31T06-52-02Z-00.zip)
[logs.zip](https://github.com/elastic/elastic-agent/files/8387111/logs.zip)

Thanks

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on upgraded 8.2 Snapshot kibana cloud-qa environment from 8.1.3 Snapshot kibana.
We attempted to upgraded Windows, Linux .tar and MAC agents on this environment and found this issue **still reproducible**.
- Windows agent stuck in Updating state.
- Linux and MAC agent gets Unhealthy on triggering Agent upgrade.

**Build details:**
VERSION: 8.2.0
BUILD: 51882
COMMIT: 57e5dd6012953e70c822d4dd8d04a6ab9ff3ab6d
Artifact Link: https://snapshots.elastic.co/8.2.0-a99722cc/downloads/beats/elastic-agent/elastic-agent-8.2.0-SNAPSHOT-linux-x86_64.tar.gz

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/163158135-cbb44587-02b5-461b-94b2-8cbf6feb080a.JPG)
![2](https://user-images.githubusercontent.com/77374876/163158145-462b4cca-2c26-4738-9998-fa78adc3117e.JPG)

**Logs:**
[elastic-agent-diagnostics-2022-04-13T07-59-43Z-00.zip](https://github.com/elastic/elastic-agent/files/8480622/elastic-agent-diagnostics-2022-04-13T07-59-43Z-00.zip)

Thanks

**Comment by jlind23** [comment]
@amolnater-qasource This is a network issue and not the upgrade issue we were talking about. Can you check a simple curl please?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this earlier too, to check if there is any internet issue on VMs, however internet was working fine.
Further to be sure, we have revalidated upgrading agent on a Windows and Ubuntu VM and found the issue is still reproducible.
- We are not able to upgrade agents to latest version 8.2 Snapshot.
- Internet on VMs was working fine.

**Build details:**
BUILD: 51911
COMMIT: 3336188cf5cdfa87b4d7f22362159bbad384a072

**Screenshots:**
![17](https://user-images.githubusercontent.com/77374876/163353646-4a18061a-c833-4fad-b166-314aeece4087.JPG)
![18](https://user-images.githubusercontent.com/77374876/163353658-3d8c0aa3-9f8d-4351-9c78-c79a748d72e5.JPG)

Please let us know if we are missing anything.
Thanks

**Comment by jlind23** [comment]
@amolnater-qasource did you succeed calling the exact same url with a curl in order to get the artifact? You got an http 404 in your logs which is definitely something else.

**Comment by jlind23** [comment]
@amolnater-qasource I tried the URL and there is no artifacts to download, that's why it's failing:
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.2.0-SNAPSHOT-linux-x86_64.tar.gz

This one works well: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.1.2-linux-x86_64.tar.gz

Shouldn't we target another registry as the 8.2.0 is not out yet?

**Comment by amolnater-qasource** [comment]
@jlind23 I used below artifact link with curl command to download this 8.1.3 Snapshot artifact: 
https://snapshots.elastic.co/8.1.3-bb164e02/downloads/beats/elastic-agent/elastic-agent-8.1.3-SNAPSHOT-linux-x86_64.tar.gz

Further I tried to run a curl with the url that is available under logs(which agent is trying to download while upgrading), that downloads artifact too:
![image](https://user-images.githubusercontent.com/77374876/163357559-aee68d1e-543d-414e-a69e-232a31b7cd79.png)

Logs from Agent:
[elastic-agent-diagnostics-2022-04-14T09-35-37Z-00.zip](https://github.com/elastic/elastic-agent/files/8488081/elastic-agent-diagnostics-2022-04-14T09-35-37Z-00.zip)

Thanks!

**Comment by jlind23** [comment]
@amolnater-qasource thanks for the update, but as you can see a timeout limit is reached. There should be something else happening.
@blakerouse as you recently work on this, is there any further debug we can do?

**Comment by amolnater-qasource** [comment]
Hi @blakerouse 
As per feedback we have revalidated this issue on latest 8.3 Snapshot by upgrading 8.2 Snapshot agents.
We had below observations:
- Windows and MAC agent upgraded successfully.
- Linux agent gets unhealthy after triggering upgrade from Fleet UI.

**Build details:**
BUILD: 52217
COMMIT: 9430e41eb29640692d2d60ee93178726fdc356b4
Artifact Link: https://snapshots.elastic.co/8.2.0-a7e9513d/downloads/beats/elastic-agent/elastic-agent-8.2.0-SNAPSHOT-linux-x86_64.tar.gz

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/164185406-a85a5ad1-1cc1-458e-bb64-1a98afefe147.JPG)
![2](https://user-images.githubusercontent.com/77374876/164185391-0e84aeb8-e6a3-447f-b426-58f4a4409c43.JPG)

**Ubuntu Agent Logs:**
[elastic-agent-diagnostics-2022-04-20T08-28-47Z-00.zip](https://github.com/elastic/elastic-agent/files/8519720/elastic-agent-diagnostics-2022-04-20T08-28-47Z-00.zip)

Further we will also revalidate this on latest 8.2 Snapshot once it is available.
Please let us know if anything else is required from our end.

Thanks

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.2 Snapshot by upgrading 8.1.3 Snapshot agents.
We had below observations:
- Windows and MAC agent upgraded successfully.
- Linux agent gets unhealthy and fails to upgrade.

**Build details:**
BUILD: 52012
COMMIT: 14a83300ba28df6c7f5318c4f3fe86f29369438d
Artifact Link: https://snapshots.elastic.co/8.1.3-0c4e7b42/downloads/beats/elastic-agent/elastic-agent-8.1.3-SNAPSHOT-linux-x86_64.tar.gz
![image](https://user-images.githubusercontent.com/77374876/164411113-3b4fd317-562c-4ece-a709-a5b74c8444b3.png)

**Screenshots:**
![8](https://user-images.githubusercontent.com/77374876/164410583-5d666a16-2766-4ec3-84cd-468a97087571.JPG)
![9](https://user-images.githubusercontent.com/77374876/164410596-c7236aa7-bdf6-4d11-bb7c-ed43dae623f7.JPG)

**Ubuntu Agent Logs:**
[elastic-agent-diagnostics-2022-04-21T08-14-17Z-00.zip](https://github.com/elastic/elastic-agent/files/8529053/elastic-agent-diagnostics-2022-04-21T08-14-17Z-00.zip)

Please let us know if anything else is required from our end.

Thanks

**Comment by blakerouse** [comment]
Upgrading from 8.2 to 8.3 does use the fix. The fix is only present in 8.3.0-SNAPSHOT. Meaning you must already be on 8.3.0-SNAPSHOT to get the fix. So you need to install 8.3.0-SNAPSHOT and then upgrade to 8.3.0-SNAPSHOT (I assume Kibana allows that).

**Comment by amolnater-qasource** [comment]
Hi @blakerouse 
Yes we have validated this upon 8.3 Snapshot and detailed results are shared above at https://github.com/elastic/elastic-agent/issues/245#issuecomment-1103621142
- Windows-MAC upgraded successfully.
- Linux agent failed to upgrade.

Further as Windows and MAC agent upgrade issue is resolved on 8.2 Snapshot.
We are closing this issue and will be keeping track of failed Linux agent upgrade at https://github.com/elastic/elastic-agent/issues/173

Thanks

**Comment by blakerouse** [comment]
So I miss typed my comment:

8.2 to 8.3 **DOES NOT** use the fix

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  Testcase already exists for this scenario under Fleet test suite at link:
   -  [C34211](https://elastic.testrail.io/index.php?/cases/view/34211)

Thanks
