### ISSUE TITLE
Changing log level to `debug` in Fleet UI does not produce `debug` logs from Agent

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#2450]
For confirmed bugs, please report:
- Version: 8.8.0-SNAPSHOT built from `main`, commit SHA: 2ca71d09b4103c5bf634018912d6d60aad747b52.
   ```
   $ sudo elastic-agent version
   Binary: 8.8.0-SNAPSHOT (build: 2ca71d09b4103c5bf634018912d6d60aad747b52 at 2023-04-04 18:14:12 +0000 UTC)
   Daemon: 8.8.0-SNAPSHOT (build: 2ca71d09b4103c5bf634018912d6d60aad747b52 at 2023-04-04 18:14:12 +0000 UTC)
   ```
- Operating System: Linux
   ```
   $ uname -a
   Linux elastic-agent-dev 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
   ```
- Steps to Reproduce:
1. Build Elastic Agent from `main`.
2. Bring up an Elastic stack deployment.
3. Enroll Elastic Agent in Fleet.
4. Open up Discover, look at `logs-*`, and ensure that `info` logs from Agent and Beats are present.  One way to do this is to set up the following columns: `@timestamp`, `log.source`, `log.level`, `message`.  The `log.source` column will tell you which process is generating that log entry.
5. Go to Fleet > Agents tab and click on your agent's hostname.
6. Go to the Logs tab, scroll to the bottom, and change the Agent logging level to `debug` using the dropdown.  Make sure to apply changes.
7. After a few seconds, go back to Discover and refresh the logs. 
8. Notice that there are no logs from Elastic Agent, at any log level.  A couple of ways to check this:
    - Look at the `log.source` column.  Notice that there is no `elastic-agent` any more in this column across all log entries since changing the log level to `debug`.
    - Find a few logging statements (logging at different log levels) in the Agent codebase and search for words from those statements in Discover's filter bar.

**Comment by cmacknz** [comment]
Likely related to the root cause of https://github.com/elastic/elastic-agent/issues/2399

**Comment by cmacknz** [comment]
I can reproduce this in v8.7.0 as well.
