### ISSUE TITLE
E2E testing stage is constantly failing

### ISSUE THREAD

**Issue by alexsapran** [elastic/elastic-agent#2457]
## Flaky Test

* **Test Name:** e2e testing stage.
* **Branch:** main
* **Notes:** Once we fix the e2e testing stage to be reliable we should reenable it

The main branch should have reliable working stages that when fail should be investigated, having a constantly failing stage leads to cases of folks not taking a look other failures.

**Comment by jlind23** [comment]
E2E testing has been deprecated hence closing this one.
