### ISSUE TITLE
CI - Improve test coverage report for PRs

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#2471]
**Describe the enhancement:**
I would like to have a more detailed code coverage report on PRs so that I can evaluate at a glance where a given change improves or worsens the test coverage.

I would like to see:
- what's the coverage of the diff (so how well tested is the change itself)
- what the change in overall coverage (we already have that)
- coverage detailed by package and files with diff to master
- Maybe be able to see the actual covered/partially covered/uncovered code paths in a file impacted by the PR ?

Something similar to a codecov report (like [this one](https://github.com/keptn/keptn/pull/8456#issuecomment-1188699399) )

![image](https://user-images.githubusercontent.com/96178987/230556128-66f6667e-270b-4855-b815-bbd125648ed7.png)

It does not have to be the same tool but having something offering the same functionality would be nice :) 

**Describe a specific use case for the enhancement or feature:**

The specific use case is to evaluate quickly the test coverage change of a PR (not just 
quantitatively, but being able to understand where the variations happened in the code) while reviewing a PR

**Comment by pazone** [comment]
I'm now implementing sonarqube integration. https://github.com/elastic/elastic-agent/pull/3108

**Comment by blakerouse** [comment]
This was fixed with SonarQube.
