### ISSUE TITLE
[QA] New test case: testing FQDN feature flag on Windows

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#2476]
1. Configure the Windows host to have a fully-qualified domain name (as opposed to just a short hostname, which I believe is the default).
   1. (On Windows Server 2022 Datacenter) Open _Control Panel_ > _System_ > _Rename this PC (advanced)_.  This should open the _System Properties_ window, with the _Computer Name_ tab selected.
   <img width="1306" alt="Screenshot 2023-04-10 at 11 32 59 AM" src="https://user-images.githubusercontent.com/51061/230968999-e5770924-6955-421d-9523-2a4ced571078.png">

   2. Click the _Change..._ button and then the _More..._ button.  This should open the _DNS Suffix and NetBIOS Computer Name_ window.
   <img width="1306" alt="Screenshot 2023-04-10 at 11 35 57 AM" src="https://user-images.githubusercontent.com/51061/230970445-8dea538a-e4ad-4977-b83d-7eb84706c4da.png">

   3. Fill out the _Primary DNS suffix of this computer_ field with a domain name.  For example:
      <img width="394" alt="Screenshot 2023-04-10 at 11 37 42 AM" src="https://user-images.githubusercontent.com/51061/230970525-5b6f0e8d-55bc-419b-a2bc-fb0519b70fb8.png">

   4. Click OK on this window and its parent window.  You should be asked to restart the computer for your changes to take effect.  Click OK to restart.
      <img width="394" alt="Screenshot 2023-04-10 at 11 37 42 AM" src="https://user-images.githubusercontent.com/51061/230970578-70f2d189-592f-43a6-8143-247ebd23b1e7.png">

2. After the host has restarted and you've signed in to it again, install Elastic Agent and enroll it in Fleet.  When assigning a policy to the agent during enrollment, make sure the policy is using the default settings, particularly for the _Host name format_ setting.  The default value of this setting is _Hostname_.
   <img width="748" alt="Screenshot 2023-04-10 at 11 45 27 AM" src="https://user-images.githubusercontent.com/51061/230971839-0bcbb118-3bc6-4c8f-b375-e5b9c044fe8d.png">

3. Ensure that the just-enrolled Agent's name is the short hostname of the Windows host.  For example:
   <img width="1220" alt="Screenshot 2023-04-10 at 11 52 45 AM" src="https://user-images.githubusercontent.com/51061/230972700-800e0656-2f63-47ca-bd56-3e972f66f1ea.png">

4. Edit the policy for that Agent, select the _Fully Qualified Domain Name (FQDN)_ value for the _Host name format_ setting, save and deploy changes.
   <img width="892" alt="Screenshot 2023-04-10 at 11 51 50 AM" src="https://user-images.githubusercontent.com/51061/230972396-025b2018-6530-4938-bc25-d902ca1229ae.png">

5. A few (< 10) seconds later, ensure that the Agent's name is now the FQDN of the Windows host, i.e. the short hostname + '.' + the domain name (DNS suffix) you entered in step 1.iii earlier.  For example:
   <img width="1229" alt="Screenshot 2023-04-10 at 11 56 51 AM" src="https://user-images.githubusercontent.com/51061/230973539-78790820-8355-40b3-bc71-5ccb796abff9.png">

6. Also check the logs (in `logs-*` indices) and metrics (in `metrics-*` indices) for the Agent are reporting the FQDN in the the `host.hostname` field, where previously the short hostname was being reported.
   1. Open Kibana Discover in two new browser tabs. In one tab set the index pattern to `logs-*` and in the other tab, set it to `metrics-*`.
   2. In the bar chart that's shown at the top of Discover, use the _Break down by_ dropdown and select the `host.name` field.  This will show the document counts over time, broken down by `host.name`.  
      <img width="1083" alt="Screenshot 2023-04-10 at 12 06 25 PM" src="https://user-images.githubusercontent.com/51061/230976976-d171a250-9fa3-46d2-8655-80864a961960.png">
   3. Ensure that all earlier documents — before the change in step 4 above — are using the short hostname value.  Likewise, ensure that eventually (~ 5 minutes) all later documents — after the change in step 4 above — are using the FQDN value.  This can be done easily by toggling each of the values in the chart's legend.
      <img width="1121" alt="Screenshot 2023-04-10 at 12 08 22 PM" src="https://user-images.githubusercontent.com/51061/230977062-2e3cce5c-7309-46c2-88ba-0626d061b1a7.png">
      <img width="1304" alt="Screenshot 2023-04-10 at 12 09 05 PM" src="https://user-images.githubusercontent.com/51061/230977145-7d5590b4-a669-4908-a899-0bf195d9d58e.png">

7.  Repeat steps 4-6, but this time selecting the _Hostname_ value for the _Host name format_ setting and ensuring that the short hostname shows up for the Agent's name as well as (eventually) in the Agent's logs and metrics as well.

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 
Thank you for sharing the details.

We have revalidated this feature on latest 8.7.1 SNAPSHOT kibana cloud environment for windows and found it **working fine**.

**Observations:**
- On enabling FQDN, the fqdn of windows host is visible under Agents tab and Agent details tab.
- New Data under discover tab is visible with fqdn host.name.
- On resetting it back to Hostname, the hostname of windows host is again visible.
- New Data under discover tab is visible with hostname.

**Screen Recordings:**


https://user-images.githubusercontent.com/77374876/231116178-f9f173ce-2819-48b4-b2d7-6663c09b7f2e.mp4


https://user-images.githubusercontent.com/77374876/231116051-0f7189ed-ee4a-4b20-88a3-d68e808cd5f1.mp4


**Build details:**
BUILD: 62089
COMMIT: 5a2aafe9f124c646d3ef449114d122eeb0ff4a2c

Please let us know if we are missing anything here.
Could you please confirm if we can validate this feature for Linux and MAC OS's.

Further, we will be creating testcase for the Windows OS.
Thanks!

**Comment by ycombinator** [comment]
@amolnater-qasource @pierrehilbert What is the protocol here - can we close this issue once that the QA team has added a test case?

**Comment by jlind23** [comment]
@ycombinator We can close this as they found it working fine 😄

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

Thank you for the feedback.
We are currently following the below process:
- As we have validated this feature on a Snapshot build, we will create test cases for this feature under testrail.
- When Build Candidate for the 8.7.1 will be available, we will be running Feature test run for the same.
- After that we will mark this Feature with label **QA:Validated**.

Please let us know if anything else is required from our end.

Further we will be creating testcases for this feature on validating on other OS's.

Thanks

**Comment by amolnater-qasource** [comment]
Hi Team,
We have created **06 testcases** for this feature under Fleet test suite at links:
- [Validate data for fqdn host name for Windows agent.](https://elastic.testrail.io/index.php?/cases/view/269606)
- [Validate data for fqdn host name for Linux agent.](https://elastic.testrail.io/index.php?/cases/view/269607)
- [Validate data for fqdn host name for MAC agent.](https://elastic.testrail.io/index.php?/cases/view/269608)
- [Validate data on setting back to hostname type of host name for Windows agent.](https://elastic.testrail.io/index.php?/cases/view/269609)
- [Validate data on setting back to hostname type of host name for Linux agent.](https://elastic.testrail.io/index.php?/cases/view/269610)
- [Validate data on setting back to hostname type of host name for MAC agent.](https://elastic.testrail.io/index.php?/cases/view/269611)

Please let us know if we are missing any scenario to be covered here.

Thanks!

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

Thank you for the feedback.

We have created **03 more testcases** for this feature under our Fleet Test suite at links:
- [Validate data for fqdn host name still generates for Windows agent after agent Upgrade.](https://elastic.testrail.io/index.php?/cases/view/269612)
- [Validate data for fqdn host name still generates for Linux agent after agent Upgrade.](https://elastic.testrail.io/index.php?/cases/view/269613)
- [Validate data for fqdn host name still generates for MAC agent after agent Upgrade.](https://elastic.testrail.io/index.php?/cases/view/269614)

**Query:**
Further could you please confirm if this feature will be working from 8.7.1 version agents onwards or will also be supporting for lower versions like 8.6.x or 8.7.0 agents.

Please let us know if anything else is required from our end.
Thanks!

**Comment by ycombinator** [comment]
> Further could you please confirm if this feature will be working from 8.7.1 version agents onwards or will also be supporting for lower versions like 8.6.x or 8.7.0 agents.

This feature will be released in `8.7.1`.  So only that version and versions after that will support this feature.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have executed test run for this feature on latest 8.7.1 BC3 kibana cloud environment at link:
- [FQDN](https://elastic.testrail.io/index.php?/runs/view/5565&group_by=cases:assigned_to_id&group_order=asc)

**Status:**
PASS: 05
FAIL: 01 Issue under https://github.com/elastic/elastic-agent/issues/2546
SKIP: 03 [Will be executed from 8.8.0 for agent upgrades]

**Build details:**
BUILD: 61211
COMMIT: fde13a9709d0191b3eccee3aa20af50be8ef7e7e

Hence we are marking this feature as **QA:Validated**.
Thanks
