### ISSUE TITLE
Create an integration test for the fleet proxy set by --proxy-url and in the policy

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#2482]
# Issue #

Follow up task from https://github.com/elastic/elastic-agent/pull/2468

**Describe the enhancement:**

Create an integration test to ensure the proxy set by `--proxy-url` on install/enrol isn't overwritten by an empty proxy defined on the fleet policy. However a valid proxy set in the policy should take precedence over a proxy defined by the cli flag.

the test should roughly follow the steps below:

 - Setup a proxy between the agent and a mock fleet-server
 - do not define a proxy in the policy
 - install/enrol the agent using the --proxy-url flag
 - while no proxy is set in the policy, the agent should use the proxy provided by --proxy-url flag
 - set a different (and valid) proxy in the policy
 - check the agent is using the policy provided by the policy
 
Ideas:
 - manually create the proxies within the tests so we can easily see and assert what is going through the proxy 

**Describe a specific use case for the enhancement or feature:**

A proxy set by the cli flag `--proxy-url` is local to the agent, what allows agents in the same policy to use different proxies, what isn't possible when defining the proxy in the policy. The latter case, all agents must use the same proxy.

# Definition of done # 

- [ ] Integration test using our new framework is in place to validate the mentioned scenario.
- [ ] The test also uses SOCKS5 proxy https://github.com/elastic/elastic-agent/issues/2964

**Comment by cmacknz** [comment]
Does this need to be an E2E test? As in do we actually need Fleet server and Kibana involved to test this?

I think all we actually need is an HTTP server implementing the Fleet agent API that allows us to return arbitrary agent policies to the agent. It seems like it would be quite valuable to have that and would simplify this to something more like an integration test.

Our goal here is not to test that the Fleet plugin in Kibana or Fleet server works. We are only interested in testing the agent side of this interaction.

**Comment by AndersonQ** [comment]
agreed

**Comment by cmacknz** [comment]
@pchila had the same idea about implementing a mock Fleet server, it's written up as a separate issue. I would suggest we solve that first as a separate task because it will make writing this test much easier:

- [ ] https://github.com/elastic/elastic-agent/issues/2630
