### ISSUE TITLE
[Fleet]: Data with FQDN host name format is not displayed for Ubuntu agent under Discover tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2497]
**Kibana version:** 8.7.1 Snapshot Kibana cloud environment

**Host OS:**  Ubuntu 22.04

**Build details:**
8.7.1 SNAPSHOT
BUILD: 61177
COMMIT: 89705e86c441f8843c373f6e6fe4e001305650f3

**Preconditions:**
1. 8.7.1 Snapshot Kibana cloud environment should be available.
2. Ubuntu 22.04 linux agent should be installed.

**Steps to reproduce:**
1. Navigate to Agent policy tab.
2. Update the Host name format to FQDN for Ubuntu agent policy.
3. Observe after 10 seconds, the FQDN name is displayed.
4. Navigate to Discover tab, observe data is still visible for regular hostname and not FQDN.
5. Even after waiting for more than 15 minutes data is not visible with FQDN host name.

**Hostname:**
![14](https://user-images.githubusercontent.com/77374876/231692624-b3e48364-8b9a-4b00-8043-2a55ade0dd52.JPG)

**FQDN:**
![15](https://user-images.githubusercontent.com/77374876/231692506-791d8088-2a85-471f-9482-c44ab00ed714.JPG)

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/231691995-85893599-b235-4720-acb2-00945ac39674.mp4

**Expected Result:**
Data with FQDN host name format should be displayed for Ubuntu agent under Discover tab.

**Related Feature:**
https://github.com/elastic/ingest-dev/issues/1398

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by ycombinator** [comment]
Hi @amolnater-qasource @manishgupta-qasource, looking at the screen recording, it looks like you're looking at the `host.hostname` field in Discover.  The field where any FQDN changes are reflected is actually `host.name`.

I realize I caused this confusion because I had mistakenly mentioned the `host.hostname` field in step 6 of https://github.com/elastic/elastic-agent/issues/2476 but used `host.name` field in the screenshots. 🤦 Sorry about that!

Would you mind re-testing and looking at the `host.name` field?  Thanks!

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

Thank you for the update.
We have revalidated this on 8.7.1 BC1 kibana cloud environment and found it working fine with `host.name`.

- Data with FQDN and Host Name both is displayed for ubuntu agent under Discover tab.

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/232038186-1a96b1da-ce2a-4475-ad68-0fb3b1d3e477.mp4


**Build details:**
BUILD: 61183
COMMIT: a499452f20a6fb95ec673d59f20fb9e9185933f5

Hence we are closing this issue and marking as **QA:Validated**.

Thanks
