### ISSUE TITLE
Separate the packaging step from the agent build step

### ISSUE THREAD

**Issue by epixa** [elastic/elastic-agent#2498]
**Describe the enhancement:** The packaging code in the Magefile should be separated from the build code so that we can do these operations independently.

**Describe a specific use case for the enhancement or feature:** This is a requirement for the "Releasing Endpoint Faster / Early Agent releases" effort, which allows for us to create a new package of the agent to include an updated binary without rebuilding all of agent itself. More information about this effort is here: https://github.com/elastic/ingest-dev/issues/1688

A consideration for development: It would be nice to preserve the original build/package alongside the new logic so that we can be absolutely sure it's producing a consistent output before we start shipping any packages created by the new tasks.

**Comment by marc-gr** [comment]
A new `mage packageAgentCore` command has been added to just ship the agent binaries. 

This covers the work scoped in here, and some WIP can be found [here](https://github.com/elastic/elastic-agent/pull/2812) to make use of it as a follow up work to integrate in with DRA.

**Comment by gsantoro** [comment]
I know it's a long shot but I managed to hack the package process with mage to reduce it dramatically. More info at https://github.com/elastic/elastic-agent/issues/2426. Some tips might work for making the build faster
