### ISSUE TITLE
[Fleet] Agent gets stuck in the updating state if the upgrade action fails

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2508]
**Kibana version:**  8.7 BC3 kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.7 BC3
BUILD: 60804
COMMIT: abbdcf43f4e89f6fc085360252514aed7c032b4b
```

**Preconditions:**
1. 8.7 BC3 kibana cloud environment should be available.
2. Lower version 8.6.2 agent should be installed.

**Steps to reproduce:**
1. Navigate to Fleet>Settings and add invalid agent binary: `https://test-artifacts.elastic.co/downloads/`
2. Navigate to Fleet>Agents tab.
3. Trigger agent upgrade for lower version agent.
4. Observe agent never gets failed and remains stuck in `Updating` throughout.

**Expected Result:**
Agent should fail while upgrade with invalid agent binary and should reset agent for  re-upgrade after sometime, say 10 minutes.

**Logs:**
[elastic-agent-diagnostics-2023-02-24T03-37-26Z-00.zip](https://github.com/elastic/elastic-agent/files/10820956/elastic-agent-diagnostics-2023-02-24T03-37-26Z-00.zip)

**Note:**
-  We have observed that agent remained in `Updating` state for over 12 hours.

**Screenshots:**
![image](https://user-images.githubusercontent.com/77374876/221101343-5d6fc93c-d702-4a03-8c05-ee433e1d8ef0.png)
![image](https://user-images.githubusercontent.com/77374876/221101359-b8629ace-7fe2-4a0c-baee-4b4b65e8dff7.png)
![9](https://user-images.githubusercontent.com/77374876/221101395-a9b5371e-03c1-4c69-b960-420dccf35137.JPG)
![image](https://user-images.githubusercontent.com/77374876/221101468-1bd6473a-8099-4ce9-870b-d8d5bbc63b02.png)

**Comment by juliaElastic** [comment]
Repeated the upgrade test this morning with the invalid download source, and seeing the retries finishing in about 2 hours and the agent going back to `Healthy`. Not sure if the previous delay was a one-off, but it seems inconsistent.

```
[90m06:55:46.992[0m [32mINF[0m marking agent upgrade as retrying [36mecs.version=[0m1.6.0 [36mfleet.access.apikey.id=[0mUcLIj4cBBj2648jJnHXy [36mfleet.agent.id=[0m9fae3c0e-0998-4b69-b1a0-dbefe801fa0c [36mhttp.request.id=[0m01GY9JBR0BZBJ9ME0WNJ9VDZYM [36mnEvents=[0m1 [36mretry_attempt=[0m1 [36mserver.address=[0m [36mservice.name=[0mfleet-server
[90m07:00:51.506[0m [32mINF[0m marking agent upgrade as retrying [36mecs.version=[0m1.6.0 [36mfleet.access.apikey.id=[0mUcLIj4cBBj2648jJnHXy [36mfleet.agent.id=[0m9fae3c0e-0998-4b69-b1a0-dbefe801fa0c [36mhttp.request.id=[0m01GY9JN18VB5Q4ETV9D9G0NPKV [36mnEvents=[0m1 [36mretry_attempt=[0m2 [36mserver.address=[0m [36mservice.name=[0mfleet-server
[90m07:05:54.345[0m [32mINF[0m marking agent upgrade as retrying [36mecs.version=[0m1.6.0 [36mfleet.access.apikey.id=[0mUcLIj4cBBj2648jJnHXy [36mfleet.agent.id=[0m9fae3c0e-0998-4b69-b1a0-dbefe801fa0c [36mhttp.request.id=[0m01GY9JY98V8E8TC1086H23QRR3 [36mnEvents=[0m1 [36mretry_attempt=[0m3 [36mserver.address=[0m [36mservice.name=[0mfleet-server
[90m07:15:57.303[0m [32mINF[0m marking agent upgrade as retrying [36mecs.version=[0m1.6.0 [36mfleet.access.apikey.id=[0mUcLIj4cBBj2648jJnHXy [36mfleet.agent.id=[0m9fae3c0e-0998-4b69-b1a0-dbefe801fa0c [36mhttp.request.id=[0m01GY9KGP248AHWJCR7V87Y0YW2 [36mnEvents=[0m1 [36mretry_attempt=[0m4 [36mserver.address=[0m [36mservice.name=[0mfleet-server
[90m07:31:01.500[0m [32mINF[0m marking agent upgrade as retrying [36mecs.version=[0m1.6.0 [36mfleet.access.apikey.id=[0mUcLIj4cBBj2648jJnHXy [36mfleet.agent.id=[0m9fae3c0e-0998-4b69-b1a0-dbefe801fa0c [36mhttp.request.id=[0m01GY9MC8PFFSMX016JCKFHGQH8 [36mnEvents=[0m1 [36mretry_attempt=[0m5 [36mserver.address=[0m [36mservice.name=[0mfleet-server
[90m08:05:17.359[0m [32mINF[0m marking agent upgrade as retrying [36mecs.version=[0m1.6.0 [36mfleet.access.apikey.id=[0mUcLIj4cBBj2648jJnHXy [36mfleet.agent.id=[0m9fae3c0e-0998-4b69-b1a0-dbefe801fa0c [36mhttp.request.id=[0m01GY9PB11M8TJYGKYEYR23PEK1 [36mnEvents=[0m1 [36mretry_attempt=[0m6 [36mserver.address=[0m [36mservice.name=[0mfleet-server
[90m09:05:21.192[0m [32mINF[0m marking agent upgrade as failed, agent logs contain failure message [36mecs.version=[0m1.6.0 [36mfleet.access.apikey.id=[0mUcLIj4cBBj2648jJnHXy [36mfleet.agent.id=[0m9fae3c0e-0998-4b69-b1a0-dbefe801fa0c [36mhttp.request.id=[0m01GY9SS0A3G8RKQ3JJFQPS7MYW [36mnEvents=[0m1 [36mretry_attempt=[0m-1 [36mserver.address=[0m [36mservice.name=[0mfleet-server
```

**Comment by blakerouse** [comment]
@juliaElastic Thanks for the detailed analysis of what the Elastic Agent is doing in the situation. Unless I am reading your analysis incorrectly, it seems that the Elastic Agent is working as designed. I think the confusion is the amount of time that retry can take, which is almost 2 hours before the final try is performed and the Updating is cleared.

I see a couple of possible solutions:

1. Do nothing, keep it how it is. 2 hours for it fail.
2. Catch the DNS lookup error and not mark that as an error to retry. So it will quickly fail to upgrade.
3. Lower the retry configuration to not be so long.

I don't think any one of these are a perfect solution, more visibility into what is happening on the agent for an upgrade might be a better path forward. Adding the ability for the Elastic Agent to say that its going to retry, why it needs to retry, and when it will perform the retry would be an improvement to the visibility of what is happening.

**Comment by juliaElastic** [comment]
I think it would make sense to categorize some errors as unretryable like DNS lookup error.
Also improving the visibility on the retrying status would help. There is already an improvement raised which is related: https://github.com/elastic/ingest-dev/issues/1621

**Comment by blakerouse** [comment]
> I think it would make sense to categorize some errors as unretryable like DNS lookup error, like your option 2.

That error could be transient in the case that the DNS is temporarily down, so marking that not retry-able is still questionable. Another possibility is that the new DNS entry has not fully propagated and a retry in a few minutes would result in it working.

**Comment by WiegerElastic** [comment]
> @juliaElastic Thanks for the detailed analysis of what the Elastic Agent is doing in the situation. Unless I am reading your analysis incorrectly, it seems that the Elastic Agent is working as designed. I think the confusion is the amount of time that retry can take, which is almost 2 hours before the final try is performed and the Updating is cleared.
> 
> I see a couple of possible solutions:
> 
>     1. Do nothing, keep it how it is. 2 hours for it fail.
> 
>     2. Catch the DNS lookup error and not mark that as an error to retry. So it will quickly fail to upgrade.
> 
>     3. Lower the retry configuration to not be so long.
> 
> 
> I don't think any one of these are a perfect solution, more visibility into what is happening on the agent for an upgrade might be a better path forward. Adding the ability for the Elastic Agent to say that its going to retry, why it needs to retry, and when it will perform the retry would be an improvement to the visibility of what is happening.

If the decision is made to go with option 1, I think the 2 hour window should be reflected in the Agent (upgrade) documentation, the Agent upgrade UI and/or both. 

Having worked through multiple bumpy upgrade processes with Agent in the past year, I would very much appreciate such a sanity check while upgrading.

**Comment by cmacknz** [comment]
We need to make it so that the the UI shows that the upgrade is retrying, including when the next retry will occur and why the previous attempt failed. This fix can be included as part of the upgrade state reporting redesign linked earlier.

DNS errors can be transient and are a perfect example of a retryable error that the agent action retry mechanism should be resolving automatically. We do not want the user to have to intervene here. The problem here is that UI doesn't tell the user what is happening or what is wrong.

In the short term it might be best to add more info level logging to indicate that the agent is actually retrying. I don't think we have a way to communicate the retry back to the UI, as far as the UI knows today the agent upgrading is still pending a final result.

We can add something like what Julia added for debugging:

```
17:15:26.571 [elastic_agent][info] Upgrading agent
17:15:27.700 [elastic_agent][error] Unable to download artifact
17:15:27.700 [elastic_agent][info] Schedule retry
17:20:30.793 [elastic_agent][info] Upgrading agent
17:20:32.066 [elastic_agent][error] Unable to download artifact
17:20:32.067 [elastic_agent][info] Schedule retry
```

The scheduled retry log above should include the time of the next scheduled retry and how many retries are remaining.

**Comment by amolnater-qasource** [comment]
Hi @juliaElastic 

We have revalidated this on latest 8.7.1 BC2 kibana cloud environment and found it **still reproducible**.

**Observations:**
- Agent gets stuck in the updating state if the upgrade action fails even after 02 hours.

**Agent Logs:**
[elastic-agent-diagnostics-2023-04-19T06-48-23Z-00.zip](https://github.com/elastic/elastic-agent/files/11269612/elastic-agent-diagnostics-2023-04-19T06-48-23Z-00.zip)

**Hosted Fleet Server Logs:**
[elastic-agent-diagnostics-2023-04-19T06-49-10Z-00.zip](https://github.com/elastic/elastic-agent/files/11269617/elastic-agent-diagnostics-2023-04-19T06-49-10Z-00.zip)

**Build details:**
VERSION: 8.7.1 BC2
BUILD: 61192
COMMIT: e33260d70181feecc89dc4f623c694856de380d8

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/232991712-35d86c77-f656-4882-8d59-e13f018bfced.png)

Please let us know if anything else is required from our end.
Thanks!

**Comment by juliaElastic** [comment]
In the latest diagnostics, I only see the one log indicating that the agent is moved to `retrying` state.
```
{"log.level":"info","@timestamp":"2023-04-19T04:48:42.368Z","message":"marking agent upgrade as retrying","component":{"binary":"fleet-server","dataset":"elastic_agent.fleet_server","id":"fleet-server-es-containerhost","type":"fleet-server"},"log":{"source":"fleet-server-es-containerhost"},"ecs.version":"1.6.0","fleet.agent.id":"f9292ab4-b2fd-4ce8-a77f-65f382ad4d49","fleet.access.apikey.id":"OIjXl4cBJg7YE9ZcGuYA","retry_attempt":1,"service.name":"fleet-server","http.request.id":"01GYBXFSCN629S74HJ4V8YWR16","nEvents":1,"ecs.version":"1.6.0"}
```

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.9.0 BC4 kibana cloud environment and found it **fixed now**.

**Observations:**
- Agent gets Unhealthy and doesn't get stuck in the updating state if the upgrade action fails.
- After sometime gets back Healthy, allowing to restart the agent upgrade.

**Screenshot:**
![23](https://github.com/elastic/elastic-agent/assets/77374876/823bcfee-968d-4710-a2d2-d93a91aa55be)

**Build details:**
VERSION: 8.9.0 BC4
BUILD: 64661
COMMIT: ddf0c1972e43898b6890ddb38f4c016e96538239

Hence we are **closing** this issue and marking as **QA:Validated**.

Thanks!
