### ISSUE TITLE
[Question]: Standalone agent support with Endpoint Integration.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#2525]
**Query Description**

- Install the standalone agent of Windows and Linux OS with endpoint integration in the policy.

- As per the last information, the standalone agents don't support endpoint integration.

- However, we are getting data for endpoint integration for an installed standalone agent.

Could you please confirm if there are any changes in standalone agents?

**Screenshot**
- **Windows Standalone Agent Datastream.**
![image](https://user-images.githubusercontent.com/101545338/233270837-4c0ca648-d474-4c62-8cf4-c56fba25b742.png)

- **Linux Standalone Agent Datastream.**
![image](https://user-images.githubusercontent.com/101545338/233270764-64fc5866-e3d9-4263-958e-10b425a44859.png)

**Build Details**
```
VERSION: 8.7.1
BUILD: 61192
COMMIT: e33260d70181feecc89dc4f623c694856de380d8
```

**Agent Policy:**
[Policy.zip](https://github.com/elastic/elastic-agent/files/11282923/Policy.zip)

**Comment by harshitgupta-qasource** [comment]
Hi @cmacknz

Thanks for looking into this issue.

We have directly installed the standalone agent without converting Fleet based agent.

We have followed

**Steps to reproduce**
- Create an Agent policy without any integration.
- Add the endpoint Integration to the Agent policy.
- Click on the Add agent and Select standalone agent.
- Download the Agent policy for installing the standalone agent
- Replace the `elastic-agent.yml` with newly downloaded elastic-agent.yml file.
- Run install command for the standalone agent.

**Agent Diagnostics reports**

**8.7.1 Logs:**

[elastic-agent-diagnostics-8.7.1.zip](https://github.com/elastic/elastic-agent/files/11293387/elastic-agent-diagnostics-8.7.1.zip)

**8.2.3**

[elastic-agent-diagnostics-8.2.3.zip](https://github.com/elastic/elastic-agent/files/11293389/elastic-agent-diagnostics-8.2.3.zip)

We also revalidated this issue on 8.2.3 release build and we found that the issue is not occurring on the 8.2.3 release build.

- We are not getting endpoint data under data streams on 8.2.3.

**Screenshot**
- 8.2.3
![image](https://user-images.githubusercontent.com/101545338/233572140-3ce4d27b-dfdf-427a-99d8-2c5cd46cbf2b.png)
- 8.7.1
![image](https://user-images.githubusercontent.com/101545338/233572392-7140038d-3aff-4d53-9a66-62e28ce95d4e.png)

Please let us know if anything else is required from our end.

Thanks!

**Comment by blakerouse** [comment]
I believe that running an Elastic Agent in standalone mode should not even allow endpoint to run. I think we need to add something to the runtime protections for endpoint so it cannot run on a standalone Elastic Agent.

Let me know if they use case has changed and I am unaware.

**Comment by cmacknz** [comment]
> I believe that running an Elastic Agent in standalone mode should not even allow endpoint to run. I think we need to add something to the runtime protections for endpoint so it cannot run on a standalone Elastic Agent.
>
> Let me know if they use case has changed and I am unaware.

Correct, we shouldn't allow it to run. The use case is the same, endpoint should only run when the agent is Fleet managed.

Possibly we lost this in 8.6 when the `length(${fleet}) > 0` constraint was dropped from the spec file.

https://github.com/elastic/elastic-agent/blob/0e1a7396f356f8af5ad28c3c8e941256f50c86a2/internal/spec/endpoint.yml#L71

**Comment by jlind23** [comment]
@harshitgupta-qasource @amolnater-qasource is this issue still happening? If not, I think we can close it.

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have re-validated this issue on the latest 8.14.0 BC5 Kibana cloud environment and found it **fixed now**.

Observations:
- We are not getting endpoint data under data streams for standalone agent on 8.14.0 BC5 Build.

**Build details:**
VERSION: 8.14.0 BC5
BUILD: 73931
COMMIT: 7ea00b6178d67183a4def9bdd060b062cced043e

**Screen-Shot:**
![image](https://github.com/elastic/elastic-agent/assets/101545338/62af5842-7368-4668-a5e2-6ec0088256d9)


Kindly let us know if anything else is required form our end.
Thanks.
