### ISSUE TITLE
Escape `${foo}` on strings when computing a unit configuration 

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#2534]
When the Elastic-Agent computes Unit Configs and send them to Beats, there might be some values in the format `${var}` in the config, [Beats tries to process them as environment variables](https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format-env-vars.html) and will fail to start the input if they cannot be resolved.

An example of where this can happen is when using Traeffik HTTP Middleware: https://doc.traefik.io/traefik/middlewares/http/redirectregex/

While the Elastic-Agent itself uses the `${var}` notation for variable replacement, when reading data like Docker container labels, those labels should be escaped.

### 1. Deploy a container with the following docker-compose file
```yaml
version: "3.7"

services:
  flog:
    image: mingrammer/flog
    labels:
        traefik: "http://mydomain/$${1}"
    command:
      - flog
      - "-d"
      - "1"
      - "-s"
      - "1"
      - "-l"
```

### 3. On the host run `elastic-agent status --output=json`
You'll see the error:

```
    "state": 3,
    "message": "1 or more components/units in a failed state",
    "components": [
        {
            "id": "filestream-default",
            "name": "filestream",
            "state": 2,
            "message": "Healthy: communicating with pid '46416'",
            "units": [
                {
                    "unit_id": "filestream-default",
                    "unit_type": 1,
                    "state": 4,
                    "message": "[failed to reloading inputs: 1 error: Unable to hash given config: missing field accessing 'processors']"
                },
                {
                    "unit_id": "filestream-default-filestream-docker-2c170cf0-df96-11ed-9bb4-83c1ad2564eb-docker-900d5d4110961c296621a1944c146b9a86ba3b190ea6e8403b3b0b7460c20a31",
                    "unit_type": 0,
                    "state": 4,
                    "message": "[failed to reloading inputs: 1 error: Unable to hash given config: missing field accessing 'processors']"
                }
            ],
            "version_info": {
                "name": "beat-v2-client",
                "version": "8.7.42",
                "meta": {
                    "build_time": "0001-01-01 00:00:00 +0000 UTC",
                    "commit": "unknown"
                }
            }
        },
```

### 4. If you inspect the container `docker inspect <container name> you'll see the label
```json
            "Labels": {
                "traefik": "http://mydomain/${1}"
            }
```

## Related issues
 - https://github.com/elastic/elastic-agent/issues/2177

For confirmed bugs, please report:
- Version: 8.6.2
- Operating System: Linux, probably all OSes.

**Comment by blakerouse** [comment]
I 100% disagree this is a Elastic Agent issue. How does the Elastic Agent know that this should be escaped? We have use cases where the Elastic Agent should resolve variables, see https://github.com/elastic/elastic-agent/issues/2200.

To me this is a beat issue, I don't understand why beats would resolve something from Elastic Agent with environment variables. That is the Elastic Agent job and is already done before it is sent the to the beat.

If you ask me beat should parse the configuration from the Elastic Agent with `ucfg.Unpack(&dest, ucfg.ResolveNOOP)`.

**Comment by belimawr** [comment]
> I 100% disagree this is a Elastic Agent issue. How does the Elastic Agent know that this should be escaped? 

Let's agree on disagree here ;)

I see it from a different perspective: if the Elastic-Agent is sending configuration to Beats, it should be ready to use, no need for any resolution/replacement, etc. Which on my opinion would include sending all data already escaped as necessary. Theoretically speaking, the Elastic-Agent could use any features from Beats, which would include this config resolution.

> I don't understand why beats would resolve something from Elastic Agent with environment variables. That is the Elastic Agent job and is already done before it is sent the to the beat.

At the moment the code path that handles input initialisation/configuration parsing is not aware of Elastic-Agent, hence doing `ucfg.Unpack(&dest, ucfg.ResolveNOOP)` would not be simple.

However, we could just escape everything the Elastic-Agent sends to Beats on the managerV2, before it reaches the "Elastic-Agent bits of the codebase". I'm not sure whether there is any current use (like by an integration) that would rely on Beats doing config resolution from things sent by the Elastic-Agent. If there are none, then we can fix it on the Beats side as well.

I'm fine with solving it either way. I think it's a question if Beats should expose all its features to the Agent (like this config resolution/env var parsing, etc) or not.

**Comment by blakerouse** [comment]
> However, we could just escape everything the Elastic-Agent sends to Beats on the managerV2, before it reaches the "Elastic-Agent bits of the codebase". I'm not sure whether there is any current use (like by an integration) that would rely on Beats doing config resolution from things sent by the Elastic-Agent. If there are none, then we can fix it on the Beats side as well.

That means that the Elastic Agent needs to understand the beats configuration and know that it should be escaped because it is "beats". That breaks the V2 concepts and contract.

**Comment by cmacknz** [comment]
I agree with Blake here, the agent cannot be required to know the implementation details of the processes it manages. Remember that Beats is just an implementation detail of Agent, not something that we are actively trying to expose in the product (besides unavoidable places like logging).

The agent only understands the agent policy syntax and nothing else. It just routes the relevant parts of the policy to each process it starts. The list of features we support in agent policies is documented in https://www.elastic.co/guide/en/fleet/current/dynamic-input-configuration.html. Inputs must handle anything valid configuration formed from those rules, even if they include `${var}`.

Environment variable resolution isn't a feature supported at the input level, this is handled by https://www.elastic.co/guide/en/fleet/current/env-provider.html. The agent provides this as a feature for all inputs so that they don't need to re-implement it themselves. 

> At the moment the code path that handles input initialisation/configuration parsing is not aware of Elastic-Agent, hence doing ucfg.Unpack(&dest, ucfg.ResolveNOOP) would not be simple.

For Beats there is a global setting we can check to detect if we are running under Agent, so this might not be as hard as it appears: https://github.com/elastic/beats/blob/87e52451f75c751380d5ddc3d07ae0ffe17af368/libbeat/common/fleetmode/fleet_mode.go#L29

**Comment by belimawr** [comment]
I agree with both of you.

I meant to write:
> However, we could just escape everything the Elastic-Agent sends to Beats on the managerV2, before it reaches the "Elastic-Agent-unaware bits of the codebase"

What I meant to say is that when Beats receives configuration from the Elastic-Agent, the ManagerV2 (on Beats) can perform the escaping, so the rest of the codebase that is not aware of Elastic-Agent or Fleet does not need to be modified.

I'll "move" this issue to the Beats repo.

**Comment by belimawr** [comment]
Sorry for the typo/confusion folks!!
