### ISSUE TITLE
Fleet endpoint sending data to itself

### ISSUE THREAD

**Issue by Benji1377** [elastic/elastic-agent#2535]
Hi everyone, i am stuck on this issue for 3 weeks and just gave up on all google searches and chat-gpt for it.
I would really appreciate any help on this matter.

I just installed a fleet server successfully. But When trying to enroll an elastic agent it says no agent is installed so it requires agent installation first. The command of the person asking the question is correct. The problem is in the logs, i have the same problem. It is based in the binaries of the beats. From what I see, the agent is enrolling successfully in install command and contacting the fleet server for acknowledgement of a new agent and shows as healthy although no logs are sent. But when looking in the local logs of the fleet agent (endpoint, no the server) i see the beats are trying to send data to https://127.0.0.1:9200/ instead of https://192.168.29.134:9200/ as stated in the install/enroll command.

I tried to install the agent with no enrollments, then enroll with the enroll command, went successfully but same result as before.

Will appreciate any help!

**Comment by Benji1377** [comment]
Versions are 8.6.2

**Comment by cmacknz** [comment]
> trying to send data to https://127.0.0.1:9200/ 

This is the default destination when it hasn't received a configuration yet. Is the agent output configured properly?

Post your configuration and any logs to https://discuss.elastic.co/c/elastic-stack/elastic-agent/91. It's not clear if this is a bug or a misconfiguration, we only use the issue tracker for confirmed bugs and the discuss forums for help requests.
