### ISSUE TITLE
Increase default elastic agent long poll duration to ~30 minutes

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#2536]
- [ ] Depends on https://github.com/elastic/elastic-agent/issues/2544

In issue #2257 it was requested to increase the poll duration to 35 minutes, however since merging https://github.com/elastic/fleet-server/pull/2491 it's up to the client (elastic agent) to present the poll timeout in the checkin request body.
To ensure a progressive rollout of the feature the PR #2408 introduces a long poll default duration of 12 minutes (so that fleet-server answers in ~ 10 mins) for version 8.8

Starting from 8.9 we would like to increase that default duration to ~30 minutes as originally specified in #2257 

/cc @cmacknz

**Comment by cmacknz** [comment]
Closing as not planned.
