### ISSUE TITLE
Endpoint logs are visible with host name after setting FQDN for MAC agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2546]
**Kibana version:** 8.7.1 BC3 Kibana cloud environment

**Host OS:**  MAC 13

**Build details:**
8.7.1 SNAPSHOT
BUILD: 61177
COMMIT: 89705e86c441f8843c373f6e6fe4e001305650f3
Artifact Link: https://staging.elastic.co/8.7.1-14a43a6a/downloads/beats/elastic-agent/elastic-agent-8.7.1-darwin-x86_64.tar.gz

**Preconditions:**
1. 8.7.1 BC3 Kibana cloud environment should be available.
2. MAC agent should be installed with Endpoint Defend integration.

**Steps to reproduce:**
1. Navigate to Agent policy settings and set FQDN for MAC agent.
2. Observe after 15 minutes too data keep generating for MAC endpoint logs with host name.
3. However, data is also visible with FQDN name too.

**Note:**
The issue is not reproducible for Windows and Linux agents with Endpoint defend integration.

**Agent Diagnostics:**
[elastic-agent-diagnostics-2023-04-25T06-23-53Z-00.zip](https://github.com/elastic/elastic-agent/files/11319487/elastic-agent-diagnostics-2023-04-25T06-23-53Z-00.zip)

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/234193596-4bde28f8-bfeb-4d78-9479-be03e60c188d.mp4

**What's working fine:**

https://user-images.githubusercontent.com/77374876/234193488-15574673-3426-4470-9d2f-9f87294b5101.mp4

**Expected Result:**
Endpoint logs shouldn't be visible with host name when FQDN type is selected for MAC agent.

**Related Feature:**
https://github.com/elastic/ingest-dev/issues/1398

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @ycombinator

**Comment by ycombinator** [comment]
Endpoint has not yet implemented the FQDN feature flag change in their component.  So the behavior observed in this issue is currently expected.

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

Thank you for the confirmation.
We will be validating this on later builds when FQDN will be implemented with Endpoint.

Thanks
