### ISSUE TITLE
Agents remain unhealthy on switching from invalid output to valid output.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2554]
## Issue ##

**Kibana version:**  8.8 Snapshot kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.8.0 SNAPSHOT
BUILD: 62546
COMMIT: f5034e60a501e7b61a3e1bff34e64c9b94c71344
```

**Preconditions:**
1. 8.8 Snapshot kibana cloud environment should be available.
2. Agents should be installed using System integration.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Add any invalid output and make it default.
3. Wait for agents to get Unhealthy.
4. Now, switch the valid output to default.
5. Observe Agents never gets back healthy.

**Note:**
- We waited for more than 12 hours to reconnect agents to the valid output, however it remained unhealthy.

**Agent Diagnostics:**
[elastic-agent-diagnostics-2023-04-26T06-35-15Z-00.zip](https://github.com/elastic/elastic-agent/files/11330018/elastic-agent-diagnostics-2023-04-26T06-35-15Z-00.zip)

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/234496096-01fbb05a-3d59-4cf8-b6ad-fe7d87d3208e.png)
![image](https://user-images.githubusercontent.com/77374876/234497101-c9e4921b-3fb9-4b23-8815-dec9bb796b39.png)

## Definition of done ##

- [ ] Agents should get back healthy on switching from invalid output to valid output.
- [ ] Test are in place to confirm Agent state is conform to what we are expecting when output status changed (in both ways).

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
I think the error is coming from https://github.com/cmacknz/elastic-agent-libs/blob/0c72a0c26eb924dd76dd68d146c597926d5258a5/config/config.go#L298-L300

```go
		if ns.name != "" {
			return errors.New("more than one namespace configured")
		}
```

In Beats "failed to reload output" comes from two places 🤦 

https://github.com/elastic/beats/blob/f4374dce89786b1feb7012b1dc984f2435c5a061/x-pack/libbeat/management/managerV2.go#L575-L579

```go
	if unit == nil {
		// output is being stopped
		err := output.Reload(nil)
		if err != nil {
			return fmt.Errorf("failed to reload output: %w", err)
		}
```

and https://github.com/elastic/beats/blob/f4374dce89786b1feb7012b1dc984f2435c5a061/x-pack/libbeat/management/managerV2.go#L611-L614

I see a `namespace` in the monitoring configuration that I assume is the source of this but I'm not actually sure:

```yaml
  monitoring:
    enabled: true
    logs: true
    metrics: true
    namespace: ubuntu
    use_output: default
```

```go
	err = output.Reload(reloadConfig)
	if err != nil {
		return fmt.Errorf("failed to reload output: %w", err)
	}
```

**Comment by cmacknz** [comment]
@amolnater-qasource what was the invalid output configuration that was used here?

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 
Thank you for looking into this issue.

We have created a logstash output, with filling `test` in all the mandatory fields and set it to default.

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/235411081-2e1e3285-f5f6-4bb5-bdc8-2a26adf3461f.png)

Please let us know if anything else is required from our end.
Thanks!

**Comment by amolnater-qasource** [comment]
Hi Team,
We have executed **12 testcases** under the Feature test run for the 8.8.0 release at the link:
- [Specify base path with elastic-agent install](https://elastic.testrail.io/index.php?/runs/view/5609)

**Status:**
- **PASS: 09**
- **SKIP: 03**[Related to agent upgrades, will be validated from 8.8.1 and further]

**Build details:**
VERSION: 8.8 BC3
BUILD: 62994
COMMIT: 85b22d307ab93fca95c1698ede4cb61d85f3d314

As the testing is completed on this feature, we are marking this as **QA:Validated**.

Please let us know if anything else is required from our end.
Thanks

**Comment by belimawr** [comment]
I haven't managed to reproduce it as described, my Elastic-Agent does not go unhealthy on Fleet UI, however the Elastic-Agent does report degraded when I run the status command. I'm also getting a different error:
```json
        {
            "id": "filestream-monitoring",
            "name": "filestream",
            "state": 2,
            "message": "Healthy: communicating with pid '61996'",
            "units": [
                {
                    "unit_id": "filestream-monitoring-filestream-monitoring-agent",
                    "unit_type": 0,
                    "state": 4,
                    "message": "[failed to reload output: 2 errors: open test: no such file or directory test; open test: no such file or directory reading \u003cnil\u003e]"
                },
                {
                    "unit_id": "filestream-monitoring",
                    "unit_type": 1,
                    "state": 4,
                    "message": "[failed to reload output: 2 errors: open test: no such file or directory test; open test: no such file or directory reading \u003cnil\u003e]"
                }
            ],
            "version_info": {
                "name": "beat-v2-client",
                "version": "8.8.0",
                "meta": {
                    "build_time": "2023-06-06 09:41:20 +0000 UTC",
                    "commit": "1458378ef499c6c9127e29c3f29c4caf244b508f"
                }
            }
        }
```
```json
        {
            "id": "log-default",
            "name": "log",
            "state": 2,
            "message": "Healthy: communicating with pid '62547'",
            "units": [
                {
                    "unit_id": "log-default-logfile-system-dd61b190-03c2-11ee-8e22-9dc60591d68c",
                    "unit_type": 0,
                    "state": 0,
                    "message": "Starting"
                },
                {
                    "unit_id": "log-default-logfile-logs-b66a7440-03c3-11ee-8e22-9dc60591d68c",
                    "unit_type": 0,
                    "state": 0,
                    "message": "Starting"
                },
                {
                    "unit_id": "log-default",
                    "unit_type": 1,
                    "state": 0,
                    "message": "Starting"
                }
            ],
            "version_info": {
                "name": "beat-v2-client",
                "version": "8.8.0",
                "meta": {
                    "build_time": "2023-06-06 09:41:20 +0000 UTC",
                    "commit": "1458378ef499c6c9127e29c3f29c4caf244b508f"
                }
            }
        }
```

Anyway I also cannot get it back to a healthy state, I'm still investigating.

**Comment by belimawr** [comment]
Also, if the output changes the Beat is restarted, so `[failed to reload output: more than one namespace configured]` is really puzzling me.

**Comment by belimawr** [comment]
@amolnater-qasource did you set the output as default *agent integrations*, *agent monitoring* or both?

**Comment by amolnater-qasource** [comment]
Hi @belimawr 

Thank you for looking into this.

We have set both the _Agent integrations, Agent monitoring_ as default and with which the agent became unhealthy.

Further we have revalidated this on latest 8.9 SNAPSHOT Kibana and found this issue **still reproducible**.
- Agents remain unhealthy on switching from invalid output to valid output.

**Build details:**
```
VERSION: 8.9.0 SNAPSHOT
BUILD: 63857
COMMIT: 6cf0c8c5642f4f2f41cd7db524f55c2a35a5bbfb
```

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/d62b7533-0eb8-4560-89f7-cb0b7f17af8c)
![image](https://github.com/elastic/elastic-agent/assets/77374876/0829dd98-ddac-4a06-94fb-61c29f7def11)
![image](https://github.com/elastic/elastic-agent/assets/77374876/5af78ee8-edb4-4474-b364-dcd542a9eead)

**Logs:**
[elastic-agent-diagnostics-2023-06-07T07-11-51Z-00.zip](https://github.com/elastic/elastic-agent/files/11673657/elastic-agent-diagnostics-2023-06-07T07-11-51Z-00.zip)

Please let us know if anything else is required from our end.
Thanks!

**Comment by belimawr** [comment]
Thanks for the answer and logs @amolnater-qasource!
One last question: how log does it take for the agent to go unhealthy? Is it "instantaneous" (less than a minute) or does it take several minutes?

So far I found a sort of deadlock when the log input (used by the system integration) tries to start with an invalid output. Hopefully I'll have more clarity today, maybe even a fix.

**Comment by amolnater-qasource** [comment]
@belimawr If we set both the monitoring fields as default it gets unhealthy very quickly. It doesn't take more than a minute or two.

**Comment by belimawr** [comment]
What I've found is that changing to a policy with a working output configuration will eventually bring the Elastic-Agent back to a healthy state. This might take a while but it will work.

The situation I'm managing to reproduce is:
1. Fleet sends a policy with an invalid output configuration
2. Filebeat starts (it's re-started on any output change, so effectively the output is only configured at startup). Tries to start the log input (from the system integration) and falls into a deadlock: log input is waiting for an output that will never be correctly initialised)
3. Filebeat becomes unresponsive and misses enough check-ins until Elastic-Agent restarts it. This repeats indefinitely if there are not policy changes
4. When a new policy, with a correct output configuration, is sent, Filebeat is in this deadlock state, so it will not apply the policy right away
5. Once Filebeat misses enough check-ins, the Elastic-Agent kills the process and the new one is started with a working output and the Elastic-Agent goes back to a healthy state.

So based on my testing the Elastic-Agent will eventually go back to a healthy state after setting a correct policy. Anyways, I'm working on handling this deadlock/report the output initialisation error correctly.

**Comment by amolnater-qasource** [comment]
Hi @belimawr 

We have revalidated this issue on latest 8.9.0 BC2 Kibana cloud environment and found this **issue still reproducible**.

**Observations:**
- Agent remain unhealthy on switching from invalid output to valid output.

**Build details:**
VERSION: 8.9.0 BC2
BUILD: 64459
COMMIT: 6950a2b8207d8388ee8c842d6c0e2b1e1031fd36

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/1f755f12-1fb1-41f5-8ea4-37cca20d8e53)


**Debug Logs:**
[elastic-agent-diagnostics-2023-06-30T06-01-19Z-00.zip](https://github.com/elastic/elastic-agent/files/11913343/elastic-agent-diagnostics-2023-06-30T06-01-19Z-00.zip)

Hence, we are reopening this issue.

Thanks

**Comment by cmacknz** [comment]
Here's the log line where the invalid output was detected:

```json
{"log.level":"error","@timestamp":"2023-06-30T05:19:18.925Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":991},"message":"Unit state changed http/metrics-monitoring (STARTING->FAILED): could not start output: failed to reload output: 2 errors: open t: no such file or directory t; open t: no such file or directory reading <nil>","log":{"source":"elastic-agent"},"component":{"id":"http/metrics-monitoring","state":"HEALTHY"},"unit":{"id":"http/metrics-monitoring","type":"output","state":"FAILED","old_state":"STARTING"},"ecs.version":"1.6.0"}
```

All of the Beats are still failed with:

```
- id: log-default
  state:
    state: 2
    message: 'Healthy: communicating with pid ''1653'''
    units:
      ? unittype: 0
        unitid: log-default-logfile-system-cff99052-53ef-4be2-9caa-6ee8ac8758df
      : state: 1
        message: Configuring
      ? unittype: 1
        unitid: log-default
      : state: 4
        message: 'could not start output: failed to reload output: more than one namespace
          configured'
```

This is the same error in the original report.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.9.0 BC5 kibana cloud environment and found it **fixed now**.

**Observations:**
- Agents gets back Healthy on switching from invalid output to valid output.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/396a0a7a-f4e8-4377-a625-cda53e152466)

**Agent Logs:**
[elastic-agent-diagnostics-2023-07-24T06-18-03Z-00.zip](https://github.com/elastic/elastic-agent/files/12142417/elastic-agent-diagnostics-2023-07-24T06-18-03Z-00.zip)


**Build details:**
VERSION: 8.9.0 BC5
BUILD: 64661
COMMIT: ddf0c1972e43898b6890ddb38f4c016e96538239

Hence we are marking this issue as **QA:Validated**.

Thanks!
