### ISSUE TITLE
Unable to install agent with `--base-path` location on Ubuntu 22.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2558]
**Kibana version:**  8.8 Snapshot kibana cloud environment

**Host OS and Browser version:** Ubuntu 22

**Build details:**
```
VERSION: 8.8.0 SNAPSHOT
BUILD: 62546
COMMIT: f5034e60a501e7b61a3e1bff34e64c9b94c71344
Artifacts: https://snapshots.elastic.co/8.8.0-fc95a751/downloads/beats/elastic-agent/elastic-agent-8.8.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Preconditions:**
1. 8.8 Snapshot kibana cloud environment should be available.
2. Agent policy should be created with System integration.

**Steps to reproduce:**
1. Run below installation command for ubuntu agent: with `--base-path= /var` flag. [invalid format with space]
2. Observe error while installation.
3. Run installation command with correct path:  `--base-path=/var` and observe same error.

**Screenshot:**
![16](https://user-images.githubusercontent.com/77374876/234612193-2509f617-81c6-47f0-aa0d-110fec0300c9.JPG)
![17](https://user-images.githubusercontent.com/77374876/234612174-b974fe3a-9b82-4544-bb3d-f570e3866659.JPG)

**Expected Result:**
User should be able to install agent with `--base-path` location on Ubuntu 22.

**Comment by manishgupta-qasource** [comment]
Reviewed & assigned to @ycombinator

**Comment by ycombinator** [comment]
There are two bugs covered by this issue.  I'm able to reproduce one of them but not the other.

The one I'm able to reproduce is where a user specifies whitespace as the value of `--base-path`, e.g. `sudo ./elastic-agent install --base-path= /var` or even just `sudo ./elastic-agent install --base-path=`.  In both these cases the default (per-OS) base path must be used.  Instead an empty base path is being used, which is wrong.  I am working on a fix for this bug.

I've not been able to reproduce the second "file name too long" bug so far with the build and the `./elastic-agent install` command parameters mentioned in the issue.  I've tried on Debian 5, Ubuntu 22, and MacOS 13.3.1.  So I have a few questions for the QA team:

1. Are you able to repeatedly reproduce this bug on Ubuntu 22 or is it only happening sporadically? 
2. Is it happening only with the value of `--base-path` being `/var` or does it happen for other values too?
3. Are you able to reproduce it on other OSs or just Ubuntu 22?  If it's just Ubuntu 22, could you please post the output of `uname -a`?
4. Are you able to reproduce it without the `--url` and `--enrollment-token` options?
5. Could you please post the output of running `./elastic-agent version` from within the `elastic-agent-8.8.0-SNAPSHOT-linux-x86_64` folder?

**Comment by ycombinator** [comment]
> The one I'm able to reproduce is where a user specifies whitespace as the value of `--base-path`, e.g. `sudo ./elastic-agent install --base-path= /var` or even just `sudo ./elastic-agent install --base-path=`. In both these cases the default (per-OS) base path should be used, probably. Instead an empty base path is being used, which is wrong. I am working on a fix for this bug.

Thinking about this some more, I have a few questions for @cmacknz on how best to proceed here:

Currently, running `sudo ./elastic-agent install --base-path=` (notice the lack of value for the `--base-path` CLI option) results in the base path defaulting to `Elastic/Agent` (note the lack of a leading `/`).  This means Elastic Agent will get installed in the same folder from where the install command was run.  This is almost certainly not what we want.

So the question is, how should the install command react in this scenario?

1. Return an error saying something to the effect of `--base-path` was used but no value was provided for it.
2. Defaulting to the default base path, e.g. `/opt` on Linux hosts.  Note that in this case the user will still be prompted for confirmation on where Elastic Agent will be installed, so they would have a chance to notice that the path in the confirmation is not the same as the empty value they provided for `--base-path`.
3. Keeping the current behavior.  Again, I don't think this is what we'd want to do but mentioning it here along side the other options for completeness.

**Comment by blakerouse** [comment]
@ycombinator I think we should add validation to ensure that the `--base-path` is always an absolute path. I think that would ensure that we are always a valid path, probably would be good to also validate that the path even exists before continuing. I don't know if we would want the Elastic Agent to create the full path to the `--base-path`.

**Comment by ycombinator** [comment]
> I think we should add validation to ensure that the `--base-path` is always an absolute path.

Yeah, I think this is a good idea.  It's makes things less flexible for a user but it does mean they're less likely to shoot themselves in the foot.  I think it's a worthwhile tradeoff.  Will implement this change.

> probably would be good to also validate that the path even exists before continuing.  I don't know if we would want the Elastic Agent to create the full path to the --base-path.

This one, I'm less sure of.  I don't think we have this strict requirement today for the default base paths, e.g. on Linux systems, we don't validate that `/opt` already exists before installing Agent files under `/opt/Elastic/Agent`. 

Personally, I'd love to be as strict as you're suggesting, but I'm having a harder time justifying this change because it makes users do more work (creating the base path first) instead of us doing it for them.

**Comment by blakerouse** [comment]
> This one, I'm less sure of. I don't think we have this strict requirement today for the default base paths, e.g. on Linux systems, we don't validate that `/opt` already exists before installing Agent files under `/opt/Elastic/Agent`.
> 
> Personally, I'd love to be as strict as you're suggesting, but I'm having a harder time justifying this change because it makes users do more work (creating the base path first) instead of us doing it for them.

That is true, so maybe just the first one will be enough.

**Comment by cmacknz** [comment]
> I don't think we have this strict requirement today for the default base paths, e.g. on Linux systems, we don't validate that /opt already exists before installing Agent files under /opt/Elastic/Agent.

We don't, and when it doesn't exist users generally consider it to be a bug. See https://github.com/elastic/elastic-agent/issues/2487 for example. It is safest to create the path we are told to install in if it doesn't exist, this will cause the least friction for users. We don't want there to be extra steps to using the agent if they aren't absolutely necessary.

> 1. Return an error saying something to the effect of --base-path was used but no value was provided for it. Note that if we go with this option, we might want to consider making this behavior the same for all elastic-agent CLI options, for consistency sake. A blanket approach like that might be tricky, though, because there might be CLI options that legitimately intend to accept empty values.
> 
> 2. Default to the default base path, e.g. /opt on Linux hosts. Note that in this case the user will still be prompted for confirmation on where Elastic Agent will be installed, so they would have a chance to notice that the path in the confirmation is not the same as the empty value they provided for --base-path.

Either one of these is probably valid, but I think 1 is probably right because a user specifying `--base-path` probably intended to specify a non-empty path but did something wrong. Consider a shell variable that unexpectedly evaluates to an empty path. It seems much better for the agent to fail here than it does for it to silently install in a valid but undesired location.

**Comment by ycombinator** [comment]
Thanks @blakerouse and @cmacknz.  Based on both your inputs, I'm going with checking that the value supplied to `--base-path` is an absolute path and returning an error otherwise.

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

We have revalidated this issue on latest 8.8 BC3 kibana cloud environment and found this issue **still reproducible.**

Observations:
- If user accidentally adds space after --base-path flag, user is unable to install agent with correct path.

**Screenshot:**
- **Incorrect base-path:**
![11](https://github.com/elastic/elastic-agent/assets/77374876/f3b6233c-3ea1-477b-9dc0-0112c5361af6)


- **Correct base-path:**
![12](https://github.com/elastic/elastic-agent/assets/77374876/aba4fa6c-13f5-47a6-913d-99f59d72a7eb)

**Build details:**
VERSION: 8.8.0 BC3
BUILD: 62994
COMMIT: 85b22d307ab93fca95c1698ede4cb61d85f3d314
Artifact Link: https://staging.elastic.co/8.8.0-96c3005b/downloads/beats/elastic-agent/elastic-agent-8.8.0-linux-x86_64.tar.gz

Hence we are **re-opening** this issue.

Thanks!

**Comment by ycombinator** [comment]
Very odd that this is still happening.  Will investigate.  Thanks @amolnater-qasource.

**Comment by jlind23** [comment]
@ycombinator is this the fix https://github.com/elastic/elastic-agent/pull/2567 for Amol's issue? If yes, it never was backported to 8.8

**Comment by ycombinator** [comment]
> @ycombinator is this the fix #2567 for Amol's issue? If yes, it never was backported to 8.8

That's it, @jlind23.  Thanks for catching it!  I'm not sure why it wasn't backported - I probably just forgot.  Anyway, the [backport PR is up](https://github.com/elastic/elastic-agent/pull/2689) now and it should get merged within the next couple hours, which means the fix should be available in `8.8.0` BC4.

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

Thank you for backporting the fixes. We will revalidate this issue once BC4 is available.

Thanks!

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.8 BC4 kibana cloud environment and found it **fixed** now.

**Observations:**
- Invalid path installation is now blocked and user is able to install the agent with valid base-path without any errors.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/7d9b4652-7845-4684-8de4-fc69da5d5824)


**Build details:**
```
VERSION: 8.8 BC4 kibana cloud environment
BUILD: 63052
COMMIT: ecb9826ceec5457214bec760fcf049f5614ad3d0
```

Hence we are closing this issue and marking as **QA:Validated**.

Thanks!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/269789
 
Thanks!
