### ISSUE TITLE
Enable a retry after failure for Elastic Agent on Windows

### ISSUE THREAD

**Issue by pierrehilbert** [elastic/elastic-agent#2569]
**Describe the enhancement:**
Enable a retry after failure for Elastic Agent on Windows.

![186334773-e12a216c-1f4d-4d7f-ac11-8147847b2709](https://user-images.githubusercontent.com/806950/235096804-04ab62d1-7db2-4255-b310-e74d343c28a0.png)

**Describe a specific use case for the enhancement or feature:**
After a patching cycle, there might be a lot of services starting and the Elastic Agent fails to start.

**Comment by nimarezainia** [comment]
@pierrehilbert is this widespread? or just a one off issue?
My main concern is that by restarting like this we may end up masking an underlying issue. thoughts?

**Comment by pierrehilbert** [comment]
I think this is a one off issue: it would happen if a lot (and we don't have numbers to define what is a lot) of services to restart in the same time to cause the issue.

**Comment by cmacknz** [comment]
Closing, believe the reason we needed this was the bug that was also causing https://github.com/elastic/elastic-agent/issues/3061 which is now fixed.
