### ISSUE TITLE
[All OS's]: Agent goes unhealthy when some other output is set to Default output.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#257]
**Kibana version:**  8.2 Snapshot Kibana cloud environment

**Host OS:** Windows

**Build details:**
VERSION: 8.2.0 Snapshot
BUILD: 51431
COMMIT: a743498436a863e142592cb535b43f44c448851a
Artifact link: https://artifacts-api.elastic.co/v1/search/8.2-SNAPSHOT

**Preconditions:**
1. 8.2 Snapshot Kibana cloud environment should be available.
2. Windows agent should be installed.

**Integrations:**
System and Endpoint Security.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Fleet>Agent Policy tab.
3. Set output as "default" for agent policy.
4. Create a new output under Fleet Settings and set it to Default.
5. Observe within 60 seconds Windows Agent goes `Unhealthy`.

**Expected Result:**
Agent should not go unhealthy on changing Default output to some other user created output.

**Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/8360803/logs.zip)

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/160353685-6e28dca3-cb1c-4b15-a313-5548fc83346e.mp4

**Windows Output:**
![1](https://user-images.githubusercontent.com/77374876/160354957-7b843b4d-239d-41af-b006-838b8f25323b.JPG)

**Note:**
- Issue is not observed on Linux agent.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by ph** [comment]
@lykkin might be related to you changes?

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.2 BC-4 Kibana cloud environment and found it reproducible on all OS's.
We have updated the title to avoid any confusions.
- We have set another output under policy settings, and it gets Agents Unhealthy.

**Integrations:**
System and Endpoint Security

**Platforms Validated:**
- Windows
- Ubuntu
- Centos
- MAC

**Build details:**
BUILD: 52005
COMMIT: 9a5003d8cf0062bf24ef64d6712b44823888cc03
Artifact Link: https://staging.elastic.co/8.2.0-3b2b9b86/summary-8.2.0.html

**Logs:**
[elastic-agent-diagnostics-2022-04-21T06-36-28Z-00.zip](https://github.com/elastic/elastic-agent/files/8528160/elastic-agent-diagnostics-2022-04-21T06-36-28Z-00.zip)

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/164388819-5292fa18-b601-4507-ac47-88015af9a476.JPG)
![6](https://user-images.githubusercontent.com/77374876/164388822-d66c5e4b-ec4e-4720-a0d2-cd8fdc204bf2.JPG)
![7](https://user-images.githubusercontent.com/77374876/164388816-98950b3a-b6ac-4bfe-899a-3b312f8948ed.JPG)

Please let us know if anything else is required from our end.
Thanks

**Comment by jlind23** [comment]
@lykkin any progress here

**Comment by lykkin** [comment]
In the logs we see
```json
{"log.level":"error","@timestamp":"2022-03-28T08:00:31.761Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2022-03-28T04:00:31-04:00 - message: Application: endpoint-security--8.2.0-SNAPSHOT[3674c80e-9c57-47c2-9f2e-1e967c53b755]: State changed to FAILED: failed to start connection credentials listener: listen tcp 127.0.0.1:6788: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted. - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
```
repeated many times. Out of curiosity, if you remove endpoint from the agent does the issue still occur?

Also pinging @elastic/endpoint in case this is a known issue.

**Comment by intxgo** [comment]
> Also pinging @elastic/endpoint in case this is a known issue.

Trying to start another TCP server on the same port is a well known issue, but not related to any particular product. It's not possible.

I have no idea why or how endpoint-security ends being mentioned in the log. Maybe the server on 6788 is only for ElasticEndpoint, other beats connect directly to 6789?

**Comment by amolnater-qasource** [comment]
Hi @lykkin 
We have revalidated this issue on latest 8.2 BC-4 and yes we have observed that agent goes to unhealthy state only when Endpoint Security is added to it.
**Issue is not reproducible without ES.**

**Build details:**
BUILD: 52005
COMMIT: 9a5003d8cf0062bf24ef64d6712b44823888cc03
Artifact Link: https://staging.elastic.co/8.2.0-3b2b9b86/summary-8.2.0.html

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/165936413-db1e481c-d93d-4078-b53c-ada4ba1f262f.png)

**Logs:**
[elastic-agent-diagnostics-2022-04-29T11-31-28Z-00.zip](https://github.com/elastic/elastic-agent/files/8590434/elastic-agent-diagnostics-2022-04-29T11-31-28Z-00.zip)
[endpoint-000000.zip](https://github.com/elastic/elastic-agent/files/8590435/endpoint-000000.zip)

Thanks

**Comment by ferullo** [comment]
Can you share elastic-endpoint.yaml?

**Comment by amolnater-qasource** [comment]
Hi @ferullo 
Please find below elastic-endpoint.yaml from 8.2 BC-4 Endpoint:
[elastic-endpoint.zip](https://github.com/elastic/elastic-agent/files/8602291/elastic-endpoint.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by intxgo** [comment]
The endpoint log looks fine. Endpoint connects successfully to Agent.

The former log is an Agent log:
```
{"log.level":"error","@timestamp":"2022-03-28T08:00:31.761Z","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2022-03-28T04:00:31-04:00 - message: Application: endpoint-security--8.2.0-SNAPSHOT[3674c80e-9c57-47c2-9f2e-1e967c53b755]: State changed to FAILED: failed to start connection credentials listener: listen tcp 127.0.0.1:6788: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted. - type: 'ERROR' - sub_type: 'FAILED'","ecs.version":"1.6.0"}
```
It looks like the Agent is trying to start duplicate TCP server on `localhost:6788`. This localhost port is used by Endpoint as bootstrap connection port. It's really not related to any stack Output and since it's not possible to run several Endpoints on the same host it would make no sense to use any advanced socket options like SO_REUSEADDR on the TCP server side. Most likely it's a bug in Agent logic.

On a side note, I'm curious what is the purpose of the custom output, how should it work. The only [documentation](https://www.elastic.co/guide/en/fleet/8.1/beats-agent-comparison.html#supported-outputs-beats-and-agent) I was able to find it's rather shallow. Digging deeper from that page, I found the following snippet [here](https://www.elastic.co/guide/en/beats/filebeat/8.1/configuring-output.html)
```
Only a single output may be defined.
```

**Comment by jlind23** [comment]
@intxgo the other output may have been logstash in this case but we need to keep the Elasticsearch one as it is the one used for Elastic Agent API key and so on..

**Comment by intxgo** [comment]
I see, so it's expected to have Endpoint output data (events and alerts) to both Elasticsearch and Logstash at the same time if configured.

**Comment by jlind23** [comment]
Nope, only one should be used then.

**Comment by jlind23** [comment]
@ph shouldn't we change something on Fleet-ui/Elastic  Agent end to avoid having two default outputs?

**Comment by jlind23** [comment]
ping @ph

**Comment by ph** [comment]
@jlind23 This is interesting, I would have expected that is not a possible behavior, because the `default` is a key in a map and the last would have won. We should validate in Fleet UI, and Fleet-Server we shouldn't trust fleet.


@amolnater-qasource Do you have the generated agent policy yml from fleet, please remove any credentials.

**Comment by amolnater-qasource** [comment]
Hi @ph 
Please find below attached `elastic-agent.yml`:
[elastic-agent.zip](https://github.com/elastic/elastic-agent/files/8753397/elastic-agent.zip)

We have revalidated this issue on latest 8.3 Snapshot and found it **fixed** now.
- Agent remains Healthy on changing Default output to some other user created output.

**Build details:**
BUILD: 52935
COMMIT: 5d5603a57237d8fe9cf186916c713b9ddddf039d

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/169791830-59ecc11d-f724-4a15-af79-69b54e5c2a52.JPG)
![4](https://user-images.githubusercontent.com/77374876/169791842-cc85b090-4d83-41f0-acdf-2dcdf692e303.JPG)

Hence we are closing this issue and marking this as **QA:Validated**.

cc: @jlind23 
Thanks
