### ISSUE TITLE
Update the shipper monitoring implementation to be a variant of Beat monitoring

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2580]
The original implementation of shipper monitoring was done with the shipper as a new, non-Beat process. See https://github.com/elastic/elastic-agent/pull/2427

We are now exploring implementing the shipper as a Filebeat input, which means this monitoring implementation can just be a variant of the existing Beat monitoring configuration and the shipper specific monitoring can be removed.

The only shipper specific requirement with this implementation is that we want the monitoring data for the Filebeat instance implementing the shipper to flow to `elastic_agent.shipper-*` indices and not `elastic_agent.filebeat-*` indices. Users should not be able to tell that Filebeat implements the shipper, this is an internal implementation detail we should not leak.

**Comment by jlind23** [comment]
The shipper project has been revisited hence closing this as outdated/not relevant.
