### ISSUE TITLE
Each shipper input unit should have a dedicated unix socket for inter-process communication

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2581]
In https://github.com/elastic/beats/issues/35135#issuecomment-1524014103 the initial design of the shipper Filebeat input was finalized. One of the decisions was that each shipper input unit would implement its own gRPC server provisioned with a separate unix socket. Modify how the agent provisions the shipper to create a unix socket per input unit, instead of a single unix socket per shipper process.

![image](https://user-images.githubusercontent.com/3466215/234694569-6cef1c01-ab6b-4971-a124-0015e2cf7c62.png)

We will need to decide what the naming convention for these unix sockets should be, considering that they must be unique per component that connects to the shipper and also that there can be multiple instances of a shipper. As outputs are added and removed from an agent policy over time the number of running shipper processes changes and the provisioned unix sockets must be removed in sync with this.

**Comment by jlind23** [comment]
@ycombinator @cmacknz is this issue still required now that the shipper project has been revisited?

**Comment by cmacknz** [comment]
Not needed anymore, closing.
