### ISSUE TITLE
Report the version from the elastic agent package instead of agent binary

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#2582]
## Issue ##

We need to be able to repackage Agent without rebuilding the Agent binary, and still have Agent report the updated version number at runtime. The repackaging step will be created as part of https://github.com/elastic/elastic-agent/issues/2498

This requires that agent reads its version from a plaintext file that can be updated as part of the packaging step, rather than written directly into the binary.

## Suggested solution ##

Implement after https://github.com/elastic/elastic-agent/issues/2579 to use the full version number contains in the parent directory.

## Definition of done ##

- [ ] The Agent is reporting the correct version and not a fixed one from building steps.
- [ ] Tests are in place to confirm that the full version is the one reported.

**Comment by cmacknz** [comment]
> This requires that agent reads its version from a plaintext file that can be updated as part of the packaging step, rather than written directly into the binary.

Depending on what we do in https://github.com/elastic/elastic-agent/issues/2579#issuecomment-1529671585, another option could be for the agent to report the version number from its parent directory e.g. `elastic-agent-7ac68h-8.8.1.er1`.

**Comment by jlind23** [comment]
Moving this to a later sprint as the plan changed a bit.

**Comment by joshdover** [comment]
We are moving this back into the sprint. cc @pchila

**Comment by cmacknz** [comment]
> elastic-agent-x.y.z[-SNAPSHOT]+<commithash> which differs from the released version x.y.z[-SNAPSHOT]+<buildid> (the part after the + is a different identifier.

Yes, using <commithash> instead of <buildid> seems preferable here, since the buildid is hard to tie back to a specific set of commits on its own.
