### ISSUE TITLE
Create a new pipeline for building agent binary and publishing to DRA

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent#2595]
## Context

We need to be able to release elastic-agent as part of the DRA process. 
Currently, we are building the artifacts but as part of the unified release and not publishing them into DRA.
This issue is to track the work on publishing those artifacts into DRA. 

```[tasklist]
### Tasks
- [x] We have onboarded elastic-agent to Buildkite
- [ ] Needs build parameters for which artifact versions to assemble
```

**Comment by jlind23** [comment]
> This new pipeline is going to pull the required dependencies from the other projects and then package elastic-agent using those downloaded versions.

You mean that this pipeline will pull the required binaries from the registry and bundled them together?

**Comment by alexsapran** [comment]
Yes. 
One idea, but not limited to it, could be to have some sort of manifest that would define which packages and versions we would pull down before packaging.

**Comment by jlind23** [comment]
@alexsapran this is still marked as a P0 in this sprint, any update here? Any PR to link?

**Comment by alexsapran** [comment]
We were waiting from the release engineering team to add support in the release-manager the ability to have 2 set of artifacts in DRA. 
This is now unblocked and I can resume the work on https://github.com/elastic/elastic-agent/pull/2727
