### ISSUE TITLE
Add elastic_agent.shipper to the list of known monitoring datasets in Fleet

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2654]
We need to add the `elastic_agent.shipper` dataset to the list of known monitoring datasets in Fleet. 

These are defined in https://github.com/elastic/kibana/blob/51f6eeccefca5b927f96727be39181e0c4119275/x-pack/plugins/fleet/common/constants/agent_policy.ts#L15-L30

```typescript
export const AGENT_POLICY_DEFAULT_MONITORING_DATASETS = [
  'elastic_agent',
  'elastic_agent.elastic_agent',
  'elastic_agent.apm_server',
  'elastic_agent.filebeat',
  'elastic_agent.filebeat_input',
  'elastic_agent.fleet_server',
  'elastic_agent.metricbeat',
  'elastic_agent.osquerybeat',
  'elastic_agent.packetbeat',
  'elastic_agent.endpoint_security',
  'elastic_agent.auditbeat',
  'elastic_agent.heartbeat',
  'elastic_agent.cloudbeat',
  'elastic_agent.cloud_defend',
];
```

Without this the the shipper logs and metrics cannot be written to Fleet, each write will fail with an API key error. Fleet only generates API keys for monitoring datasets in this list.

**Comment by jlind23** [comment]
The shipper project has been revisited hence closing this as outdated/not relevant.
