### ISSUE TITLE
Data is visible with host name under `metrics-*` index temporarily after upgrade, if fqdn type is set before upgrade.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2693]
**Kibana Build details:**
```
VERSION: 8.8 BC3 kibana cloud environment
BUILD: 62994
COMMIT: 85b22d307ab93fca95c1698ede4cb61d85f3d314
```

**Host OS and Browser version:** Windows, MAC and Linux, All

**Preconditions:**
1. 8.8 BC3 kibana cloud environment should be available.
2. 8.7.1 Agents should be installed.

**Steps to reproduce:**
1. Set FQDN host name type for all the 8.7.1 agents.
2. Wait for sometime, until only FQDN hostname data is visible.
3. Upgrade the agents and observe post upgrade, data is visible with host name temporarily under Discover tab.

**Expected:**
Data should be visible with fqdn type only under `metrics-*` index after upgrade too, if fqdn type is set before upgrade.

**Screen Recording:**
![7](https://github.com/elastic/elastic-agent/assets/77374876/77f9f963-d1f9-4218-b2b3-8301fcea2865)

https://github.com/elastic/elastic-agent/assets/77374876/5144b60d-b470-4fe0-833c-38dea753ac55

![image](https://github.com/elastic/elastic-agent/assets/77374876/334c9212-2024-4148-9413-6520364b1258)

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @ycombinator

**Comment by ycombinator** [comment]
> Upgrade the agents and observe post upgrade, data is visible with host name temporarily under Discover tab:

Just to clarify, you mean that post-upgrade, you can still see some documents in `metrics-*` still containing the _short_ hostname (as opposed to the longer FQDN)?

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

Thank you for looking into this, yes post-upgrade we observed some entries with `metrics-*` index.
Please let us know if anything else is required from our end.

Thanks!

**Comment by cmacknz** [comment]
@amolnater-qasource does running `elastic-agent restart` produce the same result? Wondering if the agent restart done as part of the upgrade causes this. There will be a period of time where the agent doesn't have the feature flag configuration from the agent yet, and it could perform writes to Elasticsearch in that period.

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 

Thank you for looking into this issue.
We have revalidated this issue on latest 8.8 BC5 Kibana cloud environment and found it  reproducible with **agent restart** too.

**Observations:**
- Both logs-* and metrics-* are available for the upgraded agents with host name if fqdn type is set.
- Even on restart  logs-* and metrics-* are available for the agents with host name.

**Screen Recording:**
**Post upgrade:**

https://github.com/elastic/elastic-agent/assets/77374876/a33abea6-1ae7-4055-ba06-24da85f0e172


**On Restart:**

https://github.com/elastic/elastic-agent/assets/77374876/9d647e34-713e-49a2-ae06-1ceb4e0cca18


https://github.com/elastic/elastic-agent/assets/77374876/c34b84c0-356e-45c5-8840-f76cde0c5b76


**Build details:**
```
VERSION: 8.8.0 BC5 Kibana cloud environment
BUILD: 63092
COMMIT: ba9b182a3422f5e162c1ca74baafb91833eca059
```

Please let us know if anything else is required from our end.

Thanks!

**Comment by jlind23** [comment]
Closed by https://github.com/elastic/beats/pull/35736

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.9.0 BC2 Kibana cloud environment and found it **fixed now**.

**Observations:**
- Data is visible with fqdn type only under `metrics-*` index after upgrade too, if fqdn type is set before upgrade.

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/78172077-9ee1-4ee8-a08d-fa0cd22f8fd8


**Build details:**
BUILD: 64459
COMMIT: 6950a2b8207d8388ee8c842d6c0e2b1e1031fd36
Artifact Link: https://staging.elastic.co/8.9.0-826fd88d/downloads/beats/elastic-agent/elastic-agent-8.9.0-windows-x86_64.zip

Hence, we are marking this issue as **QA:Validated**.

Thanks
