### ISSUE TITLE
Add an integration test for the upgrade rollback proces

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2705]
We need an integration test to verify that the upgrade rollback mechanism works correctly. The test should setup a situation where an attempted upgrade will unconditionally roll back, and verify that:
* Only the original version of the agent that attempted the upgrade is installed and healthy at the end of the test.
* The logs from the new agent version that was rolled back are available along with the upgrade watcher logs.

The test should allow parameterizing how long the upgrade watcher takes to detect the failed agent upgrade to ensure we do not need to wait for several minutes each time the test is run.

**Comment by pierrehilbert** [comment]
Closing in favor of https://github.com/elastic/elastic-agent/issues/2176
