### ISSUE TITLE
[French Windows10]: Agent is not installed on reboot when agent install command is run through `--delay-enroll`.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#2719]
**Kibana Build details:**
```
VERSION: 8.8 BC6 Kibana cloud environment
BUILD: 63115
COMMIT: a4c256b39f7d1ee34abe61109a817ec7f5329009
```

**Host OS and Browser version:** Windows 10 French, All

**Preconditions:**
1. 8.8 BC6 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Run agent install command for Windows 10 French Vm with --delay-enroll.
3. Restart the VM, observe agent is not installed after successful restart too.

**Expected:**
Agent should be installed on reboot on French Windows 10 VM when installed through `--delay-enroll`.

**Note:**
Agent is installed successfully on running install command directly on French Windows10.

**Screenshots:**
![2](https://github.com/elastic/elastic-agent/assets/77374876/586c1ae1-6099-4487-8c2d-1df3108b43be)
![3](https://github.com/elastic/elastic-agent/assets/77374876/87e5df33-2c2b-49e5-84e3-329b6b8b357d)
![4](https://github.com/elastic/elastic-agent/assets/77374876/dd210b15-9321-4d7b-aa22-af84bd897653)
![image](https://github.com/elastic/elastic-agent/assets/77374876/6340cb7b-2597-4b1c-8a7f-7fbc9d490f9a)

**Logs:**
[entire logs.zip](https://github.com/elastic/elastic-agent/files/11530183/entire.logs.zip)

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
Hi Team,
While testing for Korean and Spanish Windows VMs, we have found this issue **reproducible there too**.

**Observations:**
- Agent is not installed on reboot when agent install command is run through `--delay-enroll`.

**Build details:**
```
VERSION: 8.8 BC6 Kibana cloud environment
BUILD: 63115
COMMIT: a4c256b39f7d1ee34abe61109a817ec7f5329009
Artifact: https://staging.elastic.co/8.8.0-375abdf7/downloads/beats/elastic-agent/elastic-agent-8.8.0-windows-x86_64.zip
```

**Entire installed folder:**
[Korean.zip](https://github.com/elastic/elastic-agent/files/11540633/Korean.zip)

**What's working fine:**
- The issue is not reproducible for German Windows 10 VM.

Please let us know if anything else is required from our end.
Thanks!

**Comment by cmacknz** [comment]
```json
{"log.level":"error","@timestamp":"2023-05-22T09:04:37.727Z","log.origin":{"file.name":"cmd/run.go","file.line":150},"message":"failed to perform delayed enrollment: fail to enroll: fail to execute request to fleet-server: status code: 400, fleet-server returned an error: BadRequest, message: apikey auth response HYlLQogB5NXOOIeb1GND: [401 Unauthorized] {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"unable to authenticate with provided credentials and anonymous access is not allowed for this request\",\"additional_unsuccessful_credentials\":\"API key: invalid credentials for API key [HYlLQogB5NXOOIeb1GND]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"unable to authenticate with provided credentials and anonymous access is not allowed for this request\",\"additional_unsuccessful_credentials\":\"API key: invalid credentials for API key [HYlLQogB5NXOOIeb1GND]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}},\"status\":401}","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.9.0 BC4 kibana cloud environment and found it **fixed now**.

**Observations:**
- Agent gets installed successfully on reboot when agent install command is run through --delay-enroll.

**Screenshots:**
![26](https://github.com/elastic/elastic-agent/assets/77374876/14503e9c-8d91-45e3-90db-61b167187989)
![27](https://github.com/elastic/elastic-agent/assets/77374876/a5671aa7-daed-41d7-85b3-87d113cc6a34)

**Build details:**
VERSION: 8.9.0 BC4
BUILD: 64661
COMMIT: ddf0c1972e43898b6890ddb38f4c016e96538239
Artifact Link: https://staging.elastic.co/8.9.0-c6bb8f7a/summary-8.9.0.html#elastic-agent

Hence we are **closing** this issue and marking as **QA:Validated**.

Thanks!
