### ISSUE TITLE
Change Elastic Agent behaviour when the file path is too long

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent#2749]
As of today, filepaths for Elastic Agent input are built from the unit ID, example:
`kubernetes/metrics-60f88f50-c873-11ed-9baf-09fb5640c56a-kubernetes/metrics-kubelet-0d1f291d-9b2e-4f44-a0dc-82ebee865799`

If this ID goes is longer or equals to [104 characters](https://github.com/elastic/elastic-agent/blob/cda5b7e75d080c6be9e9220dfa607c145cf598b4/internal/pkg/agent/application/monitoring/v1_monitor.go#L965) this is not allowed and agent will fall back on `/tmp/elastic_agent/$sha256(path).sock` instead of `unix:///usr/share/elastic-agent/state/data/tmp/kubernetes-metrics-60f88f50-c873-11ed-9baf-09fb5640c56a.sock` where $sha256(path) is the SHA256 hash of the original path that is too long.

But this `tmp` folder might not be accessible by the agent which will result in a failure.

We should fix this problems using three different approaches:
- [x] elastic/ingest-docs#240
- [ ] 2. We should prevent user from entering too long IDs in Kibana
- [ ] 3. Elastic Agent should truncate IDs that are longer than the maximum number of characters allowed.

**Comment by jlind23** [comment]
@cmacknz Any idea on what would be the best solution for 3.? Shall we keep only the last X digits of the input id?!

**Comment by amitkanfer** [comment]
@jlind23 i'm putting this on sprint 13, aiming 8.9. Sounds good?

**Comment by jlind23** [comment]
@amitkanfer we didn't even define what the tech solution is for "3." so no it does not sound good :)

**Comment by blakerouse** [comment]
If we can just use the sha256 of the input ID and keep it `unix:///usr/share/elastic-agent/state/data/tmp/` where it won't be longer than 104 characters then that would be better.

**Comment by cmacknz** [comment]
That was I was thinking as well, but looking at an example SHA256 path like `unix:///usr/share/elastic-agent/state/data/tmp/6cc33ebe6ad93d3476c25a9ea38c4fe5e4c5ffbd8866f26288d86d2f672c1ea7.sock` it is still too long:

```
❯ python
Python 3.10.0 (default, Dec 13 2021, 09:27:34) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> len('unix:///usr/share/elastic-agent/state/data/tmp/6cc33ebe6ad93d3476c25a9ea38c4fe5e4c5ffbd8866f26288d86d2f672c1ea7.sock')
116
```

**Comment by amitkanfer** [comment]
Is there a real concern for collisions here? if not - can we just truncate the hash...?

**Comment by cmacknz** [comment]
We could truncate the SHA256 or just use an alternate hash with a shorter output, there's no particular reason we need to use SHA256 or use a cryptographic hash.

A 160 bit SHA-1 hash works, the SHA-1 of `unix:///usr/share/elastic-agent/state/data/tmp/kubernetes-metrics-60f88f50-c873-11ed-9baf-09fb5640c56a.sock` is `2c9274eb901fae74c947fb18e2c38d3c12959ea9` which gets us to 92 characters.

```
>>> len('unix:///usr/share/elastic-agent/state/data/tmp/2c9274eb901fae74c947fb18e2c38d3c12959ea9.sock')
92
```

**Comment by jlind23** [comment]
With the solution proposed by Craig, I don't see any reason why we should prevent users from inputing long values in fleet UI then.

**Comment by cmacknz** [comment]
Correct, we don't need to modify the UI at all if we make this change in the agent.

**Comment by amitkanfer** [comment]
@jlind23 this will land in 8.9?

**Comment by jlind23** [comment]
We will try, 8.9 FF was yesterday but as this is a bug fix it will depends on Lee's capacity to fix this shortly.

**Comment by pierrehilbert** [comment]
It's in good way to be in 8.9.
