### ISSUE TITLE
Migrate pprof init and mage code to elastic-agent-libs

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent#276]
This is a continuation of an issue here https://github.com/elastic/elastic-agent-shipper/issues/6#issuecomment-1083645009 that I discussed with @ph . 

Basically, as we start work on https://github.com/elastic/elastic-agent-shipper, there's a great deal of overlapping functionality with agent, but a lot of that functionality isn't importable and/or lives in `internal/` Part of that is the pprof HTTP init process, which (among other functions) is `setupMetrics` in `internal/pkg/agent/cmd/run.go`. There's also the various config objects in `internal/pkg/core/monitoring/config/config.go`. It would be relatively nice if we could make these more generic and move them into the `elastic-agent-libs` library, where we can then import them back into agent and the shipper.

**Comment by cmacknz** [comment]
If we want to move https://github.com/elastic/elastic-agent-shipper/issues/6 forward with this path we'll have to do this ourselves.

I've split the mage portion into a separate issue (https://github.com/elastic/elastic-agent/issues/321) which I'll take care of.

**Comment by jlind23** [comment]
@fearful-symmetry is this something you will take care of? Just asking as you are assigned to it.
