### ISSUE TITLE
Coordinator's Run function never retries on error

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent#2789]
`Coordinator.Run` has a `for` loop that dispatches to the internal helper `Coordinator.runner` and checks the result:

```go
func (c *Coordinator) Run(ctx context.Context) error {
  ...
  for {
    c.state.UpdateState(state.WithState(agentclient.Starting, "Waiting for initial configuration and composable variables"))
    err := c.runner(ctx)
    if err != nil {
      ...
```

The checks here return from `Coordinator.Run` if the context is cancelled or the return value is `ErrFatalCoordinator`, otherwise the loop starts again with another call to `c.runner`.

The problem is, `Coordinator.runner` never returns anything except `ErrFatalCoordinator` (unless the parent context in `Coordinator.Run` has already expired, indicating an external shutdown) -- in either case, the `for` loop will never run a second time, so no real retrying is happening here.

This happens because `c.runner's` return value is generated by `Coordinator.handleCoordinatorDone`, a helper function that collects the return values from the three managers (config, runtime, vars) and, if any of them are errors, collects them all into an `ErrFatalCoordinator`. Since `handleCoordinatorDone` is never called in the first place until there has been at least one error, this is in practice the only possible return value until final Agent shutdown.

Discussing this issue @blakerouse confirmed that we want to retry here when possible, so we need a way to decide which errors are considered fatal (currently the possible errors from the various managers are undocumented so this may take some investigation), and when only non-fatal errors are returned from the managers we should do a rate-limited retry in `Coordinator.Run`.

Note: The current form of `handleCoordinatorDone` came out of a [fix for several deadlocks](https://github.com/elastic/elastic-agent/pull/2352), so this change is potentially sensitive -- it is better to be overcautious about which errors are considered fatal than to risk permanently deadlocking the `Coordinator`.

**Comment by faec** [comment]
Reminder since it looks like this is back in the sprint planning: right now we don't have a defined list of what errors the various managers can return, or a way to decide which ones should be fatal. (There was some work on clarifying these earlier this summer but that was deferred for more urgent tasks.) Mistakenly retrying here for a misclassified error could block Agent shutdown.

**Comment by cmacknz** [comment]
If it is dangerous to mistakenly retry, and the only error we know about today is fatal, then is it simpler to remove this misleading retry logic entirely and always exit on error? 

The agent is almost always running in an environment where it is running as a service or k8s pod where it will restart automatically if the process exits unexpectedly.

It seems safer to treat all errors as fatal initially, and then add retry logic once we have a concrete example of a retryable error condition. We will be able to notice an agent restarting unexpectedly, it is much harder to notice and diagnose a deadlocked agent.

**Comment by faec** [comment]
@cmacknz I think I agree, the retry reflects an earlier assumption about the code paths that was possibly never actually invoked -- as far as I'm aware we don't know of any concrete examples where the current behavior (shutting down when any of the three main Managers terminates) is wrong. Unless @blakerouse knows of one, maybe this task could be revised to instead remove the current never-invoked retry loop and simplify / document the associated error propagation so the real behavior is more clear. In that case this would become an immediately feasible sprint task.

**Comment by rodrigc** [comment]
Is this issue present in elastic-agent 8.9.0?  I submitted Elastic case #01491083 where I am seeing:

```
elastic-agent status --output full
```

```
┌─ fleet
│  └─ status: (HEALTHY) Connected
└─ elastic-agent
   ├─ status: (STARTING) Waiting for initial configuration and composable variables
   └─ info
      ├─ id: 3fff2895-604e-45d2-baa6-0546c0e84a8c
      ├─ version: 8.9.0
      └─ commit: dc443bc2427920a26141b05f9c07a52191881af5
```

What scenario would exist where elastic-agent successfully connects to fleet,
but then never gets an inital configuration?

**Comment by cmacknz** [comment]
> What scenario would exist where elastic-agent successfully connects to fleet,
but then never gets an inital configuration?

Hmm, I've never seen this not resolve itself after the next 5 minute checkin error.

The Fleet state gets set to connected in v8.9.0 when there is a configuration change processed without error. So this is a bit weird, but the Fleet state is set separately from the overall agent state.

https://github.com/elastic/elastic-agent/blob/dc443bc2427920a26141b05f9c07a52191881af5/internal/pkg/agent/application/coordinator/coordinator.go#L680-L683

This is on a separate code path from what is happening in this issue though. We'd need to look at the agent diagnostics to be able to tell anymore. If you can post those in a public place you can open a new issue, otherwise the best option might be to go through support.

**Comment by rodrigc** [comment]
I have a system now which is "stuck" for a long time now, where it is connected to Fleet, but is not fetching a config.
Killing the pod running elastic-agent so that it restarts doesn't help.

This is being tracked under Elastic Support Case 01491083, and will most likely be escalated to the dev team, so hopefully we can use that mechanism for further discussion about this.

**Comment by blakerouse** [comment]
The more I think about handling errors from managers I come to this conclusion. Each manager should handle errors that it can recover from itself. If the error is recoverable it should push the error to the coordinator through a `<-Errors()` channel, and send a `nil` error one it has recovered. If the error is a fatal error then it should be returned from `Run()` and it should kill the entire agent.
