### ISSUE TITLE
Integration test runner should accept SNAPSHOT package builds

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#2792]
**Describe the enhancement:**

When Elastic Agent is built with `SNAPSHOT=true mage package`, it produces package files in the `build/distributions` folder like so:

```
$ ls -l build/distributions
total 92352
-rw-r--r--@ 1 shaunak  staff  22144908 Jun  6 14:25 elastic-agent-8.9.0-SNAPSHOT-linux-arm64.tar.gz
-rw-r--r--@ 1 shaunak  staff       177 Jun  6 14:25 elastic-agent-8.9.0-SNAPSHOT-linux-arm64.tar.gz.sha512
-rw-r--r--@ 1 shaunak  staff  24153219 Jun  6 14:33 elastic-agent-8.9.0-SNAPSHOT-linux-x86_64.tar.gz
-rw-r--r--@ 1 shaunak  staff       178 Jun  6 14:33 elastic-agent-8.9.0-SNAPSHOT-linux-x86_64.tar.gz.sha512
```

However, currently, the integration test runner does not accept such SNAPSHOT packages:

```
$ mage integration:test
Error: missing required Elastic Agent package builds for integration runner to execute: build/distributions/elastic-agent-8.9.0-linux-x86_64.tar.gz, build/distributions/elastic-agent-8.9.0-linux-arm64.tar.gz
```

**Describe a specific use case for the enhancement or feature:**

Sometimes it's not possible to build non-SNAPSHOT packages of Elastic Agent, e.g. for the upcoming release version when packages for components managed by Elastic Agent aren't themselves available for download:

```
$ DEV=true EXTERNAL=true PLATFORMS="linux/arm64" PACKAGES="tar.gz" mage package
Error: fetchBinaryFromArtifactsApi failed for auditbeat on linux/arm64: the artifact was not found
```

For such situations, it would be convenient if the integration test runner could accept SNAPSHOT packages of Elastic Agent.

(Yes, it's possible to build Elastic Agent packages for the upcoming release version without `EXTERNAL=true` but that takes a long time as all the component packages need to be built locally first).

**What is the definition of done?**

Running `mage integration:test` should work when the only Elastic Agent packages in the `build/distributions` folder are SNAPSHOT packages.

**Comment by pierrehilbert** [comment]
@blakerouse did you test it? Should we close this issue then?

**Comment by blakerouse** [comment]
Seems that the CI needs to support `-SNAPSHOT` without knowing the version. So I am going to add support for `SNAPSHOT=true` to match packaging and so this works correctly in CI.

@pazone ^
