### ISSUE TITLE
[Elastic-Agent]: No debug level logs generated under logs tab on setting logging level to debug.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#281]
**Kibana version:**  8.2 Kibana cloud-staging environment

**Host OS:** All

**Build details:**
VERSION: 8.2.0 
BUILD: 51685
COMMIT: d18a093a2cf03991b93ea3de6a1054d580d3e82f
Artifact link: https://staging.elastic.co/8.2.0-8ea0c40f/summary-8.2.0.html

**Preconditions:**
1. 8.2 Kibana cloud-staging environment should be available.
2. Few Agents must be installed.

**Integrations:**
System and Endpoint Security.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Fleet>Agents>Agent Logs tab.
3. Set logging level to debug and wait for 10 minutes.
4. Observe no debug level logs generated for agent.

**Expected Result:**
Debug level logs should be generated under logs tab on setting logging level to debug.

**Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/8397173/logs.zip)

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/161254064-3a63f287-5acd-4d59-a4ab-5dde8e7b9f55.JPG)

**Note:**
- Issue is observed for Windows and MAC agents.
- Issue is also reproducible for 1 linux agent and not reproducible for another.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@amolnater-qasource @manishgupta-qasource are debugs logs available directly in the logs files?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue and observed that:
- Issue is reproducible[most of the times] when Endpoint Security integration is added to the Agent Policy.
- However we have observed `debug` level logs in the log files.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/161513517-704688cc-d906-4646-9000-4c588d074f44.JPG)

**Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/8408374/logs.zip)

**Build details:**
BUILD: 51685
COMMIT: d18a093a2cf03991b93ea3de6a1054d580d3e82f
Artifact Link: https://staging.elastic.co/8.2.0-8ea0c40f/summary-8.2.0.html

Please let us know if we are missing anything.
Thanks

**Comment by jlind23** [comment]
@ferullo out of curiosity, can endpoint interfere with the debug logs? Like avoiding debug in order to avoid credentials leaking or something like this?

**Comment by jlind23** [comment]
@amolnater-qasource could you please in discover that you have those logs? Maybe there is some filters in place

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue and checked the `debug` level logs under Discover tab.
Info level logs were available under agent>Logs tab and no new `debug` level logs generated.
Further we didn't see any data for `log.level: "debug"` under discover tab too.

**Screenshot:**
![image (1)](https://user-images.githubusercontent.com/77374876/161745655-763e3cd6-4e21-4b7b-aaa3-2f02abcc9ba8.png)
![image (2)](https://user-images.githubusercontent.com/77374876/161747227-68c813f0-2c67-4df1-b0fc-4e6b78932e5d.png)

Please let us know if anything else is required from our end.
Thanks

**Comment by jlind23** [comment]
@amolnater-qasource It means that info logs are continuously ingested but no debug logs right?
Could you please provide and Elastic Agent diagnostic? I'll check the logs files and format.

**Comment by amolnater-qasource** [comment]
@jlind23 
>It means that info logs are continuously ingested but no debug logs right?

We haven't observed any new logs, those info level logs were pre-generated.
 
Please find below logs from elastic-agent diagnostics:
[elastic-agent-diagnostics-2022-04-05T12-12-38Z-00.zip](https://github.com/elastic/elastic-agent/files/8418030/elastic-agent-diagnostics-2022-04-05T12-12-38Z-00.zip)

Thanks

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on latest 8.2 Snapshot and found this issue still reproducible.
- No debug level logs gets generated under logs tab on setting log level to debug.

**Agents Used:**
VSphere Ubuntu 20
AWS Ubuntu 20.04

**Build details:**
BUILD: 51770
COMMIT: 9bec00d6c37b8b258d10e6f1dea3299f67db7540
Artifact Link: https://snapshots.elastic.co/8.2.0-fdfc79e3/downloads/beats/elastic-agent/elastic-agent-8.2.0-SNAPSHOT-linux-x86_64.tar.gz

**Integrations:**
System

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/161934662-1ece0ab2-082d-4229-8f61-345a4204d253.JPG)

**Logs:**
[filebeat-logs.zip](https://github.com/elastic/elastic-agent/files/8425239/filebeat-logs.zip)

[elastic-agent-diagnostics-2022-04-06T08-41-55Z-00.zip](https://github.com/elastic/elastic-agent/files/8425213/elastic-agent-diagnostics-2022-04-06T08-41-55Z-00.zip)

Please let us know if anything else is required from our end.
cc: @AndersonQ 
Thanks

**Comment by AndersonQ** [comment]
@amolnater-qasource this `[filebeat-logs.zip](https://github.com/elastic/elastic-agent/files/8425239/filebeat-logs.zip)` are the filebeat-monitoring logs from `/opt/Elastic/Agent/data/elastic-agent-*/install/filebeat-8.2.0-linux-x86_64/logs/`?

**Comment by AndersonQ** [comment]
checking the logs, I can find the same behaviour I saw yesterday, filebeat-monitoring does not correctly configure the output when it's restarted to apply the config change to log in debug level.

- on `filebeat-logs.zip/filebeat-20220406-1.ndjson` the ES address _**isn't**_ updated. Thus no log at all (debug, info, and so on) gets reported:
```
cat filebeat-monitoring-logs/filebeat-20220406-1.ndjson| grep -e "elasticsearch url:"         
{"log.level":"info","@timestamp":"2022-04-06T08:25:47.561Z","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":105},"message":"elasticsearch url: http://localhost:9200","service.name":"filebeat","ecs.version":"1.6.0"}
```

- on `filebeat-logs.zip/filebeat-20220406.ndjson` the ES address **_is_** updated. Thus all the logs are reported:
```
cat filebeat-monitoring-logs/filebeat-20220406.ndjson| grep -e "elasticsearch url:" 
{"log.level":"info","@timestamp":"2022-04-06T08:24:56.108Z","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":105},"message":"elasticsearch url: http://localhost:9200","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-04-06T08:24:56.627Z","log.logger":"esclientleg","log.origin":{"file.name":"eslegclient/connection.go","file.line":105},"message":"elasticsearch url: https://31c4eaea48c34ee9ae0a543adcaf799d.us-central1.gcp.foundit.no:443","service.name":"filebeat","ecs.version":"1.6.0"}
```

also on  `filebeat-logs.zip/filebeat-20220406-1.ndjson` it's possible to see it process debug logs from the agent:

```
cat filebeat-monitoring-logs/filebeat-20220406-1.ndjson| grep -e "Publish event:" | grep debug | grep "elastic-agent"

{"log.level":"debug","@timestamp":"2022-04-06T08:44:36.197Z","log.logger":"processors","log.origin":{"file.name":"processing/processors.go","file.line":209},"message":"Publish event: {\n  \"@timestamp\": \"2022-04-06T08:44:35.513Z\",\n  \"@metadata\": {\n    \"beat\": \"filebeat\",\n    \"type\": \"_doc\",\n    \"version\": \"8.2.0\",\n    \"raw_index\": \"logs-elastic_agent-ubuntu_aws\"\n  },\n  \"log.origin\": {\n    \"file.name\": \"remote/client.go\",\n    \"file.line\": 162\n  },\n  \"data_stream\": {\n    \"type\": \"logs\",\n    \"dataset\": \"elastic_agent\",\n    \"namespace\": \"ubuntu_aws\"\n  },\n  \"elastic_agent\": {\n    \"id\": \"5a367d38-cd8e-4dac-8ef7-3e7274b5d98e\",\n    \"snapshot\": true,\n    \"version\": \"8.2.0\"\n  },\n  \"host\": {\n    \"containerized\": false,\n    \"ip\": [\n      \"172.31.91.122\",\n      \"fe80::1050:90ff:feb4:c401\"\n    ],\n    \"mac\": [\n      \"12:50:90:b4:c4:01\"\n    ],\n    \"hostname\": \"ip-172-31-91-122\",\n    \"architecture\": \"x86_64\",\n    \"name\": \"ip-172-31-91-122\",\n    \"os\": {\n      \"codename\": \"focal\",\n      \"type\": \"linux\",\n      \"platform\": \"ubuntu\",\n      \"version\": \"20.04.3 LTS (Focal Fossa)\",\n      \"family\": \"debian\",\n      \"name\": \"Ubuntu\",\n      \"kernel\": \"5.11.0-1022-aws\"\n    },\n    \"id\": \"45c69d9c22e74bc89bb9d9d4544cebeb\"\n  },\n  \"ecs\": {\n    \"version\": \"8.0.0\"\n  },\n  \"log.level\": \"debug\",\n  \"log\": {\n    \"offset\": 49542,\n    \"file\": {\n      \"path\": \"/opt/Elastic/Agent/data/elastic-agent-b813ac/logs/elastic-agent-20220406-2.ndjson\"\n    }\n  },\n  \"input\": {\n    \"type\": \"filestream\"\n  },\n  \"event\": {\n    \"dataset\": \"elastic_agent\"\n  },\n  \"agent\": {\n    \"ephemeral_id\": \"edf923e2-ffab-4055-95f5-0072a9656a75\",\n    \"id\": \"5a367d38-cd8e-4dac-8ef7-3e7274b5d98e\",\n    \"name\": \"ip-172-31-91-122\",\n    \"type\": \"filebeat\",\n    \"version\": \"8.2.0\"\n  },\n  \"cloud\": {\n    \"instance\": {\n      \"id\": \"i-07dbcfcb6f9809a7d\"\n    },\n    \"machine\": {\n      \"type\": \"t2.medium\"\n    },\n    \"region\": \"us-east-1\",\n    \"availability_zone\": \"us-east-1a\",\n    \"service\": {\n      \"name\": \"EC2\"\n    },\n    \"account\": {\n      \"id\": \"946960629917\"\n    },\n    \"image\": {\n      \"id\": \"ami-04505e74c0741db8d\"\n    },\n    \"provider\": \"aws\"\n  },\n  \"message\": \"Request method: POST, path: /api/fleet/agents/5a367d38-cd8e-4dac-8ef7-3e7274b5d98e/checkin, reqID: 01FZZ0R1SSCE3Q75FHK76Y6HSX\"\n}","service.name":"filebeat","ecs.version":"1.6.0"}
```

An interesting test would be to create the policy already logging debug level, that way no restarted will be required from filebeat-monitoring and therefore the output config will be correct.

Another thing, @amolnater-qasource could you double check that after you changed the log level the agent does not report logs at all? Given the above evidence I can only conclude these info logs shown in the image are from before the agent have applied the config changes on the beats. Therefore all the logs are missing, not only debug logs.

**Comment by AndersonQ** [comment]
For the record, this is how I'd validate that filebeat-monitoring isn't harvesting the agent logs at all:

yup, that is what I'd check on a stack showing the problem:

Check is to see if filebeat-monitoring:
- has the correct output configured. Look for a log `elasticsearch url: http://localhost:9200` immediately followed by something like `elasticsearch url: https://a9f389508dfc4c5b81e5801067a5622a.us-central1.gcp.foundit.no:443`
- is processing the events, look for entries like `Publish event: {...` , the JSON object should be the log lines that can be seen on the file system, but not on kibana
- is logging connection errors to ES, logs like: `ES Ping(url=http://localhost:9200)` OR `Error dialing dial tcp 127.0.0.1:9200: connectex: No connection could be made because the target machine actively refused it`. where the ES address is incorrect as we know it should NOT be localhost

if all above are happening, it shows that the output config is broken, but filebeat-monitoring is correctly processing the logs, however they do not get sent to ES, and therefore are not seen in Kibana.

@ph any thoughts on why filebeat-monitoring would not get the correct output config, but the other filebeat is getting and applying it correctly?

**Comment by jlind23** [comment]
@AndersonQ with this PR: https://github.com/elastic/fleet-server/pull/1306/files#diff-85caf77b270865c04855a90fc60468c90130cd83d2218aa66f362b32c178f4e0

@ph fixed the output apiKey when no changes where made on the policy hash. Shouldn't we do that also for the output URL? Because if there is none, then agent will take the default one which is localhost:9200.

**Comment by amolnater-qasource** [comment]
>@amolnater-qasource could you double check that after you changed the log level the agent does not report logs at all? 

Yes @AndersonQ We haven't observed any new logs after setting log-level to debug.

**Screenshot:**
![7](https://user-images.githubusercontent.com/77374876/161983836-4a63bab1-db24-46a9-8c6f-24e5832c23f3.JPG)

**Current Logs:**
[elastic-agent-diagnostics-2022-04-06T13-20-03Z-00.zip](https://github.com/elastic/elastic-agent/files/8427251/elastic-agent-diagnostics-2022-04-06T13-20-03Z-00.zip)
[filebeat-logs.zip](https://github.com/elastic/elastic-agent/files/8427252/filebeat-logs.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.2 Snapshot and found it still reproducible.
-  No debug level logs generated under logs tab on setting logging level to debug.

**Platforms:**
Windows and Linux

**Build details:**
BUILD: 51972
COMMIT: 44f2776a5ece1844358845994c9f4a2dfec4c4a4
![image](https://user-images.githubusercontent.com/77374876/164000082-a09d2eef-09e3-42a0-8625-2e6722e0150e.png)

**Logs:**
[elastic-agent-diagnostics-2022-04-19T12-03-26Z-00.zip](https://github.com/elastic/elastic-agent/files/8512814/elastic-agent-diagnostics-2022-04-19T12-03-26Z-00.zip)

**Screenshot:**
![10](https://user-images.githubusercontent.com/77374876/164000257-1e126da0-4fde-4d34-9b88-138aa455b5e4.JPG)

Hence we are **re-opening** this issue.
Further we will be revalidating this issue on 8.2 BC-4 as soon as it is available.

Thanks

**Comment by AndersonQ** [comment]
@amolnater-qasource to check this issue we'd need the logs from filebeat monitoring, the elastic-agent diagnostics collect command **does not** collect them.
They can be found on `/opt/Elastic/Agent/data/elastic-agent-*/install/filebeat-8.2.0-SNAPSHOT-linux-x86_64/logs`, or `/Library/Elastic/Agent/...` for mac and `C:\Program Files\Elastic\Agent\...` for windows.

Could you provide them so I can have a look?
Also, the problem wasn't about the debug logs, but ALL the logs were missing, could you conform that is the case again? Or indeed only the debug level logs are missing? That's highly unlikely though.

Another thing, it isn't quite a agent issue, it's actually a [filebeat issue](https://github.com/elastic/beats/pull/31240), that is happening when it runs under the agent. Anyway, we used this issue to track the problem, so it's ok to continue doing so.

**Comment by AndersonQ** [comment]
@ph, @nimarezainia should we consider it a blocker for 8.2? We do have the issue on previous versions thought. [The first attempt to fix it
](https://github.com/elastic/beats/pull/31240) was backported to 7.17 and 8.1

**Comment by amolnater-qasource** [comment]
Hi @AndersonQ 
Please find below filebeat logs below:
[logs.zip](https://github.com/elastic/elastic-agent/files/8513397/logs.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by belimawr** [comment]
@AndersonQ, yes it should be backported to 8.2 as well. Let me see if I can get megify to create the backport PR.

**Comment by belimawr** [comment]
Backport PR created: https://github.com/elastic/beats/pull/31346. Now let's wait for CI

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.2 BC-4 Kibana cloud environment and found it fixed now.
- Debug level logs are now available after setting logging level to `debug`.

**Platforms Validated:**
- Windows
- Ubuntu
- Centos
- MAC

**Build details:**
BUILD: 52005
COMMIT: 9a5003d8cf0062bf24ef64d6712b44823888cc03
Artifact Link: https://staging.elastic.co/8.2.0-3b2b9b86/summary-8.2.0.html

**Screenshot:**
![2](https://user-images.githubusercontent.com/77374876/164379068-1ccf8cbf-bdad-44df-bae2-4da7a79fe3df.JPG)

Hence we are **closing** this issue and marking this as **QA:Validated**.
Thanks

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  Testcase already exists for this scenario under Fleet test suite at link:
   -  [C35188](https://elastic.testrail.io/index.php?/cases/view/35188)

Thanks
