### ISSUE TITLE
[Integration Test Runner] Test results should only count "leaf node" tests

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#2822]
Consider the `TestFleetManagedUpgrade` E2E test.   It instantiates the `FleetManagedUpgradeTestSuite` test suite, which contains exactly one test method, `TestUpgradeFleetManagedElasticAgent`.   

When _just_ the `TestFleetManagedUpgrade` E2E test is executed using `mage integration:single TestFleetManagedUpgrade`, the test in the `TestUpgradeFleetManagedElasticAgent` method is executed twice (as of this writing) — once for amd64 Ubuntu 22.04 and once for arm64 Ubuntu 22.04 — as expected.  However, the output of the test runner shows the test as being executed as 4 times:

```
...
>>> (linux/arm64/ubuntu/22.04[17e7]) Test output (sudo) (stdout): ok  	github.com/elastic/elastic-agent/testing/integration	268.841s
>>> (linux/arm64/ubuntu/22.04[17e7]) Test output (sudo) (stdout): DONE 2 tests in 294.503s
>>> (linux/arm64/ubuntu/22.04[17e7]) Test output (sudo) (stdout): >> go test: remote-linux-arm64-ubuntu-2204-sudo.integration Test Passed
>>> (linux/amd64/ubuntu/22.04[17e7]) Test output (sudo) (stdout): ok  	github.com/elastic/elastic-agent/testing/integration	248.345s
>>> (linux/amd64/ubuntu/22.04[17e7]) Test output (sudo) (stdout): DONE 2 tests in 293.203s
>>> (linux/amd64/ubuntu/22.04[17e7]) Test output (sudo) (stdout): >> go test: remote-linux-amd64-ubuntu-2204-sudo.integration Test Passed
>>> Bring down instances through ogc
>>> Testing completed (4 successful)
>>> Console output written here: build/TEST-go-integration.out
>>> Console JSON output written here: build/TEST-go-integration.out.json
>>> JUnit XML written here: build/TEST-go-integration.xml
```

If you look at the XML test results output file, it becomes a bit clearer where the 4 executions (instead of the expected 2 IMO) are coming from:

```
$ cat build/TEST-go-integration.xml
```
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite tests="2" failures="0" time="445.550000" name="github.com/elastic/elastic-agent/testing/integration(linux/arm64/ubuntu/22.04)(sudo)" timestamp="2023-06-08T20:07:19Z">
		<properties>
			<property name="go.version" value="go1.19.9 linux/arm64"></property>
			<property name="batch" value="linux/arm64/ubuntu/22.04"></property>
			<property name="sudo" value="true"></property>
		</properties>
		<testcase classname="github.com/elastic/elastic-agent/testing/integration" name="TestFleetManagedUpgrade/TestUpgradeFleetManagedElasticAgent" time="176.950000"></testcase>
		<testcase classname="github.com/elastic/elastic-agent/testing/integration" name="TestFleetManagedUpgrade" time="268.600000"></testcase>
	</testsuite>
	<testsuite tests="2" failures="0" time="404.820000" name="github.com/elastic/elastic-agent/testing/integration(linux/amd64/ubuntu/22.04)(sudo)" timestamp="2023-06-08T20:09:50Z">
		<properties>
			<property name="go.version" value="go1.19.9 linux/amd64"></property>
			<property name="batch" value="linux/amd64/ubuntu/22.04"></property>
			<property name="sudo" value="true"></property>
		</properties>
		<testcase classname="github.com/elastic/elastic-agent/testing/integration" name="TestFleetManagedUpgrade/TestUpgradeFleetManagedElasticAgent" time="156.490000"></testcase>
		<testcase classname="github.com/elastic/elastic-agent/testing/integration" name="TestFleetManagedUpgrade" time="248.330000"></testcase>
	</testsuite>
</testsuites>
```

Would it be possible to only count the "leaf node" test executions, e.g. `TestFleetManagedUpgrade/TestUpgradeFleetManagedElasticAgent` in this example?

**Comment by blakerouse** [comment]
I believe that is coming from the testify using the `t.Run` internally. I don't think we should be manipulating the test count or anything because of testify. If that is the count in the junit output then I think we should use that.

**Comment by ycombinator** [comment]
Hmm, in that case, is this going to inflate or skew the test numbers artificially in our test reports?  I _think_ we don't really care about the absolute numbers too much and more about the % of tests passing/failing over time.  So I guess it's okay to leave this report as-is?

**Comment by blakerouse** [comment]
I think we have to leave it as it is. There is no requirement to use `testify` for integration suite, and don't like the idea of adjusting test results just because of how it is used.
