### ISSUE TITLE
Allow configuration of Agent(+)Beats Internal queue (on disk queue)

### ISSUE THREAD

**Issue by zez3** [elastic/elastic-agent#284]
**Describe the enhancement:**
Enable the options to configure from Fleet (policy) the Internal Queue of my Agents and/or underlying Beats.

At the moment this is only available for standalone Agents.
https://www.elastic.co/guide/en/beats/filebeat/current/configuring-internal-queue.html

**Describe a specific use case for the enhancement or feature:**

When an Managed Agent dies or gets restarted we loose messages that where not yet consumed by ElasticSearch. 
We would like to have the option to increase the buffer memory or since our disks are NVMe and future ones will be able to achieve even greater IO speeds we want to use the Internal disk queue to make sure that we do not miss messages.

**Comment by nimarezainia** [comment]
@joshdover @zez3 this can't currently be done efficiently for it to make sense. These internal queues are a per beat concept and more closely aligned with writing to an output. Many of these parameters are there for users to modify the throughput they get from the beat. - closely aligned with the output queue parameters like bulk_max_size.


More thought is going into this with the new shippers work and we will provide easier means for the users to manage throughput from the agent itself. IMO would have to be considered as part of the shipper and not an input parameter.

**Comment by zez3** [comment]
@nimarezainia 
>These internal queues are a per beat concept and more closely aligned with writing to an output. Many of these parameters are there for users to modify the throughput they get from the beat.

Is this not what we need? Or am I not missing something here? Also, what do you mean efficiently? Are you referring to the 2 extra fsyncs or some specific fs like btrfs, or spool file locking?

I am asking here for the option to be included in Fleet policy. With the appropriate limitations and page pool warnings, agreed. 
Events are reaching(from syslog streams) the agent(or underlying beats) but the output is too busy or unavailable(down for maintenance/upgrades, or network is down), we need a bigger buffer or local file that can temporarly store the events for some user defined time or max buffer size. The workaround proposed by some(cough Professional Services) was Kafka mq but I think we are beyond that now.
The other additional helpful option, would be throttling.
None available at this moment for enterprise clients in fleet but available on standalone. From my point of view I would like to have in fleet all the standalone options but I can settle for just enough.

**Comment by zez3** [comment]
@joshdover 
Is this is not available or will not be included in the upcoming release then please add the future shipper memory queue
https://github.com/elastic/elastic-agent-shipper/issues/7
on the roadmap

**Comment by nimarezainia** [comment]
@zez3 We are working on providing output level configurations (such as loadbalancing, disk queue and performance tuning). We don't have a timeline as yet when these will be available but needless to say this is prioritized. A lot of the issues to track you have seen already, listing them below. Be aware that these are tracking all the internal architectural work that's on going. It's unknown exactly which release the UI work would be done to expose the configuration parameters to the users.

https://github.com/elastic/elastic-agent-shipper/issues/7
https://github.com/elastic/elastic-agent-shipper/issues/33

**Comment by zez3** [comment]
As long as I have an APl that I can call, I would be happy to test the new shipper on disk queue. The UI part can be later implemented. And hopefully we ca finally solve drops in my deployment. ;)
Regarding queue encryption I think this will slow things down but I suppose that impact will be seen and confirmed in the benchmarks. I'll add my 2 security cents on that issue

**Comment by joshdover** [comment]
> As long as I have an APl that I can call, I would be happy to test the new shipper on disk queue. The UI part can be later implemented. And hopefully we ca finally solve drops in my deployment. ;)

Yep we're discussing having a configuration API to enable this as a first step to enable testing use cases before we rollout the UI

**Comment by andrewkroh** [comment]
Is there a workaround that we can document in this issue? Like is possible to set `queue.mem.events` for the Beats through changes to local files like `elastic-agent.yml`?

**Comment by zez3** [comment]
> is possible to set `queue.mem.events` for the Beats through changes to local files like `elastic-agent.yml`?

Not sure if that would work for an Fleet Managed Agent with its underlying beats.

**Comment by zez3** [comment]
If 8.4 will soon be released perhaps someone could allow a custom policy where we define such options?

**Comment by andrewkroh** [comment]
> there is no way to modify it through an agent policy without modifying the policy to beat config transformation logic.

I found code in elastic-agent for an `InjectQueue` spec rule to derive `queue.mem.*` settings based on `bulk_max_size` and `worker`. It was added in https://github.com/elastic/beats/pull/27429 and then removed from use in https://github.com/elastic/beats/pull/27653 with a reason of "but we aren't ready to include it in an official release yet."

Perhaps we could add that back to spec files for Beats now? 

Or we wanted to be less prescriptive than the `InjectQueue` rule, we could add a different transform that takes any `queue` config from the output settings and moves it to the root of the config for Beats. Then users could manually define their queue settings like

<img width="648" alt="Screen Shot 2022-07-22 at 10 50 23" src="https://user-images.githubusercontent.com/4565752/180465581-c2d63e97-35c2-4ee5-bdd9-55f711bf2f75.png">

**Comment by joshdover** [comment]
> Or we wanted to be less prescriptive than the `InjectQueue` rule, we could add a different transform that takes any `queue` config from the output settings and moves it to the root of the config for Beats. Then users could manually define their queue settings like

I like this idea, but one concern is the same that I raised here: https://github.com/elastic/elastic-agent-shipper/issues/28#issuecomment-1184351261

We're going to be moving to a single shared queue for all integrations with the shipper and if we expose these settings now, how they get applied once there's a single queue will not be the same, making the shipper rollout a breaking change. IMO we should defer on this to provide a good upgrade experience to the shipper once it's GA.

**Comment by cmacknz** [comment]
We are planning to expose the queue parameters (although perhaps not the disk queue initially) as part of the agent output configuration, that work is tracked in https://github.com/elastic/beats/issues/35615

**Comment by gadekishore** [comment]
Customer would like to know the progress of this [comment](https://github.com/elastic/sdh-beats/issues/2679#issuecomment-1334287246).

Here is what customer says:

> I had functionality built for us at BeyondTrust as the Elastic agent was not able to keep up with our VPC flow log ingestion. Your dev added features in 8.6 in the filebeat to allow us to function. We want to know if those features were added to the Elastic agent.
> 
> Please look at my past tickets find the dev escalation and ask them if the functionality that allows the filebeat to work was added to the Agent. If it has not, we want to know when.

Appreciate if you can provide us ETA or the inputs about the progress will help to communicate it with the customer.

Thank you.

**Comment by jlind23** [comment]
Queue configuration has been added hence closing this as done.
