### ISSUE TITLE
Agent discards unhealthy state because of unrelated changes

### ISSUE THREAD

**Issue by faec** [elastic/elastic-agent#2852]
Agent's `Coordinator` is the controller that supervises the various managers and aggregates their state for Fleet and internal/test listeners. Currently, there are four events that can cause `Coordinator`'s internal state to become unhealthy [there are other events that can cause Coordinator to _report_ an unhealthy state to external listeners, but those aren't relevant here]:

- Receiving a new configuration from the config manager that is invalid, or that couldn't be applied or acknowledged
- Receiving a variable update from the vars manager that is invalid or couldn't be applied
- Receiving a log level update that couldn't be applied (which can only happen if there is already a problem with the config and/or vars)
- One of the managers (runtime, config, or vars) terminating before the shutdown signal is sent

Once the internal state becomes unhealthy, the only thing that can make it healthy again is successfully applying a policy change to the runtime manager, which requires successful generation of the component model from the config, vars, and log level, followed by a successful `Update` call to the runtime manager.

The scenario that causes a problem is this: suppose the Coordinator is healthy, with a successfully generated component model and an updated runtime manager. Now suppose a new policy comes in that is invalid, and can't be processed into a component model. `Coordinator` will transition to an error state but will leave its existing internal config and components unchanged. Now suppose an unrelated change comes in on the vars manager (there are various vars listeners that will trigger updates based on ambient context, e.g. applying environment changes from Kubernetes or Docker). The new vars are combined with the original (non-error) config to produce a successful component model, which the runtime manager receives in an `Update` call, which may succeed (it may not even have to change anything). Because of this call, `Coordinator` sets itself as healthy, and any state related to the failed policy change is lost -- if this happens in a short time span, it may not even be obvious that the policy change has been discarded.

We should figure out a more stable error state model, that can separate the immediate running state of the `Coordinator` (i.e. "I have a working component model and it's running ok") from global error state ("the last policy change was discarded because of an error").

**Comment by cmacknz** [comment]
I am tentatively putting this into the next sprint, because this can lead to the agent appearing healthy when it hasn't actually applied the latest policy successfully.

I would expect we are most likely to observe this in Kubernetes 1) because the agent is more likely to be standalone and thus more likely to encounter manually written invalid policies and 2) more likely to be receiving updates from the vars manager from the k8s providers.

> We should figure out a more stable error state model, that can separate the immediate running state of the Coordinator (i.e. "I have a working component model and it's running ok") from global error state ("the last policy change was discarded because of an error").

Even without this specific failure mode, I think it is valid for the agent to clearly tell Fleet that it cannot apply the latest policy but is successfully running the previous one. This is a building block towards a capabilities system that does preventative checks, unlike the spec files which constrain what will actually be run. It is also a building block towards allowing the agent reverting to a previous known good version of the policy, for example being able to roll back the change in https://github.com/elastic/elastic-agent/issues/2304 that broke existing proxy configurations. We need some first class concept where the agent can intentionally refuse to advance to the latest policy revision in Fleet because of an error.

**Comment by faec** [comment]
Fixing this will require decisions about / additions to the state struct that is currently reported. My tentative suggestion is we should add new fields that can persist the following errors:

- a state/message for `Coordinator` itself (right now the main `state.State` has overloaded meaning, sometimes reporting `Coordinator` state but other times overwriting that with other errors/manager states. We should give `Coordinator` its own explicit state value that is still visible when reporting the combined/global error state.)
- An error value for the last attempted policy update (not indicating health of the resulting components, just whether we were able to apply it to our own internal state, cleared only by a successful update)
- An error value for the last attempted vars update (same)
- An error value for the last attempt to generate a component model (this overlaps conceptually with the previous two since vars/policy updates are what trigger component model reloads, but some policy/vars updates fail and cancel before overwriting the active component model, leaving behind valid/healthy components, while others fail after overwriting the previous component model. This ambiguity is what causes the behavior reported in this issue.)

My thought on vars/policy versus component regeneration is that vars/policy updates should report success if they progressed far enough for us to overwrite our previous internal values. Failures that happen after that should be reported as component model errors, since we did persist the values we were given even though we couldn't start healthy components from them. This would show us where errors arise in the current update code -- based on what errors we see in the wild, we could then revisit how we validate / commit to incoming changes.

Notably absent from this list is update-related errors, but we don't yet have a good view of those from inside the Coordinator; that will take more investigation/followup with other components first.

**Comment by faec** [comment]
Actually, one additional note: in the bad state where we commit to the incoming vars/policy and try but fail to regenerate our component model, we might still keep running the old policy components within the runtime manager even though `Coordinator` no longer has a record of how to generate them. I'm not sure how likely this is to happen in practice, it's just one possible order the errors can arise in the code. We would be able to tell this was happening (after the changes in this issue are implemented): we'd see a state with a failed component refresh combined with healthy/running components. I don't have a solid recommendation around this case yet -- we might want to commit more cautiously so we don't lose that information, but on the other hand that information isn't currently used for anything -- but it might deserve more attention if it turns out to be happening in practice.

**Comment by blakerouse** [comment]
> Even without this specific failure mode, I think it is valuable for the agent to clearly tell Fleet that it cannot apply the latest policy but is successfully running the previous one. This is a building block towards a capabilities system that does preventative checks, unlike the spec files which constrain what will actually be run. It is also a building block towards allowing the agent to revert to a previous known good version of the policy, for example being able to roll back the change in #2304 that broke existing proxy configurations. We need some first class concept where the agent can intentionally refuse to advance to the latest policy revision in Fleet because of an error.

The Elastic Agent will not ack a policy change in the case that it cannot process the configuration. Code is here: https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/application/coordinator/coordinator.go#L702

It will keep the current running policy running, as it should until a next revision that fixes the issue on why it would not apply.

**Comment by faec** [comment]
> The Elastic Agent will not ack a policy change in the case that it cannot process the configuration

It won't ack the policy change from the config manager's perspective, but it can still overwrite its previous policy data: https://github.com/elastic/elastic-agent/blob/1aa6977ae16cd8b90c7f5e89c44b3819ea17eb9d/internal/pkg/agent/application/coordinator/coordinator.go#L783

If new vars come in after that it will be unable to apply them.

**Comment by blakerouse** [comment]
> > The Elastic Agent will not ack a policy change in the case that it cannot process the configuration
> 
> It won't ack the policy change from the config manager's perspective, but it can still overwrite its previous policy data:

I see the issue. It's possible for `c.process` to fail but `c.ast` is already set. Got it.

**Comment by pierrehilbert** [comment]
Shouldn't we raise the priority if it's leading our users to think the Agent is healthy when it's not?
