### ISSUE TITLE
Integration testing: suggestions for various performance improvements

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/elastic-agent#2856]
Right now, `mage integration:*` involves some fairly heavy operations, even `mage integration:Single` with the lowest-ping GCP datacenter can take around 16-20 minutes to run a single test, which is a tad long when you're actually trying to develop tests. 

After poking around the code, it seems like there's a few different things we can do to speed up the process:

- Create a pre-built machine image for the tests that's updated via automation. Right now each test run also steps through a setup process:
```
>>> (linux/amd64/ubuntu/22.04[p3sl]) Running apt-get update
>>> (linux/arm64/ubuntu/22.04[p3sm]) Install build-essential and unzip
>>> (linux/amd64/ubuntu/22.04[p3sl]) Install build-essential and unzip
>>> (linux/arm64/ubuntu/22.04[p3sm]) Install golang 1.19.9 (arm64)
>>> (linux/arm64/ubuntu/22.04[p3sm]) Copying repo
>>> (linux/arm64/ubuntu/22.04[p3sm]) Running make mage and prepareOnRemote
```

Ideally we should have some automation or something to create a premade machine image with all the needed dependencies like mage, `unzip`, etc, and the test infrastructure can use/boot to that image.

- Constrain the image types we're running on. Right now by default we seem to run on both x86 and ARM:
```
>>> (linux/arm64/ubuntu/22.04[p3sm]) Copying agent build elastic-agent-8.9.0-linux-arm64.tar.gz
>>> (linux/amd64/ubuntu/22.04[p3sl]) Copying agent build elastic-agent-8.9.0-linux-x86_64.tar.gz
```

Although these steps are run in parallel, it still ends up adding time to the test development process, as you have to rebuild two separate binaries, and one of the two steps will end up taking longer, and blocking (for example, the x86 builds are slightly larger, and thus take longer to upload).

**Comment by cmacknz** [comment]
@blakerouse is running on both Ubuntu arm64 and x86_64 in parallel something we could stop doing easily? At minimum we can't build the packages for both architectures in parallel locally, so it isn't free to do this.

**Comment by fearful-symmetry** [comment]
it looks like the testing tooling decides what to run on based on the response of an ogc query. Perhaps we could just have some filter variable that tells it to only match based on machine architecture, etc.

**Comment by cmacknz** [comment]
Another obvious optimization is to allow us to reuse the cloud resources that were provisioned for previous test runs when iterating on a single test. That would bypass the need to provision VMs at all for some test runs.

**Comment by blakerouse** [comment]
> Right now, `mage integration:*` involves some fairly heavy operations, even `mage integration:Single` with the lowest-ping GCP datacenter can take around 16-20 minutes to run a single test, which is a tad long when you're actually trying to develop tests.
> 
> After poking around the code, it seems like there's a few different things we can do to speed up the process:
> 
> * Create a pre-built machine image for the tests that's updated via automation. Right now each test run also steps through a setup process:
> 
> ```
> >>> (linux/amd64/ubuntu/22.04[p3sl]) Running apt-get update
> >>> (linux/arm64/ubuntu/22.04[p3sm]) Install build-essential and unzip
> >>> (linux/amd64/ubuntu/22.04[p3sl]) Install build-essential and unzip
> >>> (linux/arm64/ubuntu/22.04[p3sm]) Install golang 1.19.9 (arm64)
> >>> (linux/arm64/ubuntu/22.04[p3sm]) Copying repo
> >>> (linux/arm64/ubuntu/22.04[p3sm]) Running make mage and prepareOnRemote
> ```
> 
> Ideally we should have some automation or something to create a premade machine image with all the needed dependencies like mage, `unzip`, etc, and the test infrastructure can use/boot to that image.

I do not like this idea and did not want to even touch the idea of maintaining images. The burden of maintaining those and the notion that they will get out of date quickly. A new Ubuntu image is released almost weekly for each LTS, so using the latest image and installing the very little we need is way better than maintaining images. Maintaining images is a huge burden.

> 
> * Constrain the image types we're running on. Right now by default we seem to run on both x86 and ARM:
> 
> ```
> >>> (linux/arm64/ubuntu/22.04[p3sm]) Copying agent build elastic-agent-8.9.0-linux-arm64.tar.gz
> >>> (linux/amd64/ubuntu/22.04[p3sl]) Copying agent build elastic-agent-8.9.0-linux-x86_64.tar.gz
> ```
> 
> Although these steps are run in parallel, it still ends up adding time to the test development process, as you have to rebuild two separate binaries, and one of the two steps will end up taking longer, and blocking (for example, the x86 builds are slightly larger, and thus take longer to upload).

I am open to the idea of limiting the platforms that the tests run on by adding support for platform filtering using the same `PLATFORMS=""` environment variables that we use for building packages. But by default the integration framework should run on at least one of each os/arch combination to provide good coverage.

**Comment by blakerouse** [comment]
> Another obvious optimization is to allow us to reuse the cloud resources that were provisioned for previous test runs when iterating on a single test. That would bypass the need to provision VMs at all for some test runs.

The problem I have with this idea is that it means that running the tests could mean the host is not in a clean state. Being that a new package and the repository with the latest changes would still need to be copied, how much time was really saved?

**Comment by blakerouse** [comment]
> it looks like the testing tooling decides what to run on based on the response of an ogc query. Perhaps we could just have some filter variable that tells it to only match based on machine architecture, etc.

It determines what to run on from the `define.Require` that is placed on each test. If you are iterating on a single test and you want to limit what it runs on you can easily do the following today.

```
define.Require(define.Requirements{OS: []define.OS{{Type: define.Linux, Arch: define.AMD64}}})
```

Then run that single test:

```
mage integration:single [TestName]
```

**Comment by fearful-symmetry** [comment]
Just do clarify, I agree that it shouldn't really fall on us to randomly own updating GCP machine images, rather that should be something that's owned by some productivity/robots team that can have some kind of Jenkins job responsible for updating the image, etc.

**Comment by cmacknz** [comment]
> The problem I have with this idea is that it means that running the tests could mean the host is not in a clean state. Being that a new package and the repository with the latest changes would still need to be copied, how much time was really saved?

It would save us the provisioning and image setup time, we should be able to measure this. https://github.com/elastic/elastic-agent/issues/2835 would make this easier to do.

@blakerouse curious if you have suggestions for how to speed up the test framework yourself. Running a unit test takes <1s, running a single e2e test takes 15 minutes. They are never going to be the same number, but the faster we can make it to iterate on integration and E2E tests the better our life will be.

Maybe we should focus on making it possible to run all tests locally with reduced platform coverage instead of optimizing the cloud part of this? I wrote up this idea in https://github.com/elastic/elastic-agent/issues/2876.

**Comment by blakerouse** [comment]
> It would save us the provisioning and image setup time, we should be able to measure this. #2835 would make this easier to do.

I do not believe this will save us a considerable amount of time with Ubuntu, but trying to implement Windows I do see it being a huge timesaver as Windows provisioning can take a while (this is all from the cloud setting up Windows).

The thing with provisioning is the time for the image to be SSH-able then there is the time for finishing the image to be setup. Lets look at Ubuntu first.

Ubuntu:
1. Deploy instance with Ubuntu (very quick to SSH in)
2. Setup `build-essential and unzip` (not crazy fast but less than a minute on average)
3. Setup of `go` and `mage` (slower than the first 2)

The 3rd step above should not be baked into the image as we want the golang version and mage version to be synced from our repository (using `.go-version` and `make mage`). That leaves only step 2 being optimized in a pre-build image, the effort involved and maintaining that greatly outweighs the benefits, as its a small amount of time spent.

Now lets look at Windows:
1. Deploy instance with Windows (very very slow to SSH in)
2. Prepare the image for golang and mage to be usable (longer than step 2 in ubuntu but way shorter than step 1 here)
3. Setup of `go` and `mage` (quickest step for Windows)

Building a custom Windows image again is only going to save us on step 2, which in the amount of time it saves its not enough for the burden and management of custom images.

> @blakerouse curious if you have suggestions for how to speed up the test framework yourself. Running a unit test takes <1s, running a single e2e test takes 15 minutes. They are never going to be the same number, but the faster we can make it to iterate on integration and E2E tests the better our life will be.

There will be very little integration tests that will ever take less than <1s to complete. We need to get out of our head now that they are ever going to be super quick. They will always be slower than unit tests.

I always agree that making them faster would be a win, but with most cases we always look to optimize after the fact of implementation. We don't have Windows fully implemented and we don't have macOS even started yet. To me at the moment the focus should be on coverage vs performance.

It would be interesting to look into the idea of re-use of provisioned machines. It would save the time on all steps above, but still require the copying the archive and the packages to those hosts. I do believe this will be great savings on Windows, and some minor savings on Ubuntu.

> 
> Maybe we should focus on making it possible to run all tests locally with reduced platform coverage instead of optimizing the cloud part of this? I wrote up this idea in #2876.

This is a possibly another path, but I believe you will still want the benefit of pre-provisioned machines as even locally with Windows you have the issue of getting pass the initial boot/sysprep time which takes some time. Having them local would really result in faster copy times for packages and archive. I don't believe we would use OGC for this path, so we would need to integrate more control of this into the runner.

**Comment by blakerouse** [comment]
> Allowing us to constrain the tests to only run on x86 instead of x86 and arm might be a shorter term thing we can solve, this eliminates duplicate work.

They run in complete parallel, so its not going to save any time. Not saying we should allow it to be filtered down, and I will at doing it, think its very easy to add. But its not going to save any time, unless we are seeing AMD64 finish way before the ARM64 instance.

> 
> I suspect our tests won't have a strong dependence on the target architecture at all.

I would hope not.

**Comment by cmacknz** [comment]
> They run in complete parallel, so its not going to save any time. 

The main cost I noticed is before you get to running the test, having to package and upload the agent artifacts twice.

**Comment by blakerouse** [comment]
> 1. Creating a faster local test setup for initial test development and debugging the pieces that don't depend on replicating the exact conditions of the cloud runners.

Believe this would be more work that step 2 below.

> 2. Allowing reuse of previously provisioned cloud resources.

I am more interested in this method of saving time, as I think it is a benefit to 1 above as well.

> There are also probably some things we can do to speed up the time it takes to run `mage package` but that is outside the scope of this issue.

If your only iterating on tests, this is not a bottleneck. If we enable re-use we could possible optimize to only copy the package if it has changed as well. That would make a re-use a lot faster.

**Comment by fearful-symmetry** [comment]
As far as upload times, it doesn't really scale perfectly. The most time consuming part of a test run, for me, is the actual artifact upload step. I'm guessing that my home internet just doesn't have the bandwidth to upload around ~2GB data in a reasonable time. Even if the uploads are running in parallel, I assume it would be faster to just upload one file, rather than saturate the network link even further. 

Either way, the build artifact upload is by the the most time-consuming part of the process, and for me, eliminating that would probably cut the run time in half. Unless we come up with something clever, https://github.com/elastic/elastic-agent/issues/2876 is probably our best bet for dealing with this.

**Comment by blakerouse** [comment]
@fearful-symmetry Possible solution for you could be just building the Elastic Agent on the host runner. I don't think in my case it would be faster, but again I haven't tried it. I prefer the way we have it at the moment, but we could possible add a flag that changes it to build on the runner.

Maybe like `REMOTE_PACKAGE=true mage integration:test`? Do you think that would actually be faster than copying it?

**Comment by fearful-symmetry** [comment]
@blakerouse I was actually considering something like that. I suppose it would depend on the machine type that we're building on; building a VM with 2 CPUs would probably be slower. Also means we need to have build-time dependencies.

**Comment by cmacknz** [comment]
Spoke with @blakerouse today, decided the most practical next step is to allow reusing previously created VMs and deployments. This is captured in https://github.com/elastic/elastic-agent/issues/2933.
