### ISSUE TITLE
Replace `ogc:blake` with `ogc:latest` in integration test runner

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#2886]
At the moment the tag used for OGC has been changed to `ogc:blake` to validate a fix for #2806. Once the fix has been validated, the `ogc:blake` will be promoted to `ogc:latest` and this should be switched back to `ogc:latest`.

**Comment by jlind23** [comment]
Closing this as done thanks to https://github.com/elastic/elastic-agent/pull/4740
