### ISSUE TITLE
Diagnostics are not containing logs for Agent in 8.8.0+ on containers.

### ISSUE THREAD

**Issue by pierrehilbert** [elastic/elastic-agent#2899]
### Description

The Elastic Agent diagnostic doesn't collect the logs of Elastic Agent or any other component if Elastic Agent is running as a container (e.g. Kubernetes, Docker).

The problem occurs both running the command line Elastic Agent diagnostic collection and Fleet UI Diagnostic collection feature.

### Environment
It affects Elastic Agents running as containers on version 8.8.0 or latest.

### Cause

To investigate

## Definition of done

To define

**Comment by cmacknz** [comment]
We have this bug because the test framework doesn't support running the agent in a container today: https://github.com/elastic/elastic-agent/issues/2900

**Comment by lucabelluccini** [comment]
Troubleshooting is  impaired by this regression (as it was working ok until 8.7.1 included).
