### ISSUE TITLE
elastic-agent install command hangs indefinitely when run in Windows PowerShell ISE

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2902]
Running `elastic-agent install` in [Windows PowerShell ISE](https://learn.microsoft.com/en-us/powershell/scripting/windows-powershell/ise/introducing-the-windows-powershell-ise?view=powershell-7.3) (Integrated Script Environment) hangs indefinitely. This does not happen in standard Windows PowerShell.

Reproduced using Elastic Agent 8.8.1 on a Windows Server 2022 VM.

**Comment by cmacknz** [comment]
Since using standard Windows PowerShell works, we may want to add a warning to the Fleet generated Windows commands noting that it won't work in Windows PowerShell ISE while we address this. CC @jlind23 

<img width="1220" alt="Screen Shot 2023-06-19 at 1 33 08 PM" src="https://github.com/elastic/elastic-agent/assets/3466215/2a6af693-8220-46a2-9799-7022ed59b584">

**Comment by jlind23** [comment]
@cmacknz after looking at a note on the PowerShell IsE website I wonder if this is really something we would like to fix.. what do you think? ![image](https://github.com/elastic/elastic-agent/assets/43535167/3bc7e156-2a79-482e-8976-1948e3828f46)

**Comment by cmacknz** [comment]
Interesting, I think we should add a note in the auto-generated Fleet command and probably the agent documentation that we don't support PowerShell ISE then with the elastic-agent command.

**Comment by jlind23** [comment]
Doc issue created: https://github.com/elastic/ingest-docs/issues/267
Kibana issue created: https://github.com/elastic/kibana/issues/159974

**Comment by pierrehilbert** [comment]
From my understanding, we should close this old issue too then https://github.com/elastic/elastic-agent/issues/118

**Comment by cmacknz** [comment]
It's not clear skimming #118 if that applies to all PowerShell contexts, or just PowerShell ISE. If it's the latter, then we can close that too.

**Comment by jlind23** [comment]
Closing this as the outcome should be doc only with: https://github.com/elastic/ingest-docs/issues/267
