### ISSUE TITLE
Remove KibanaSetup call as it is not needed anymore

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent#2910]
From 8.0 on the the fleet setup step is done by Kibana itself thus agent do not need to to call `/fleet/api/setup` anymore.

This should be removed: 
https://github.com/elastic/elastic-agent/blob/861154f33c9e2296888cfe014a00bbd883e87424/internal/pkg/agent/cmd/container.go#L516

On out telemetry we can see that more than 90% of the Elastic Agent calls to this API are getting an http `503` 
<img width="1470" alt="Screenshot 2023-06-21 at 15 59 22" src="https://github.com/elastic/elastic-agent/assets/43535167/a0234ebb-6d14-4375-ad17-cad50a2c12d2">

Related kibana issue - https://github.com/elastic/kibana/pull/117552

cc @nchaulet

**Comment by amitkanfer** [comment]
😱

**Comment by jlind23** [comment]
> This is part of the container sub-command, which per its name will only run when the agent is in a container.

So it happens for all Cloud Elastic Agent.
