### ISSUE TITLE
[Elastic Agent] Failed Endpoint installation retry loop

### ISSUE THREAD

**Issue by bjmcnic** [elastic/elastic-agent#292]
In situations where the Elastic Endpoint Security integration installation fails to successfully install, Agent appears to continuously retry the installation. It's not clear whether there is a limitation or cap on the retries, but there does not appear to be.  This results in unnecessary resource utilization, including filling up the `elastic-agent.log` file.

Details:
- Version:  7.12.1 (at least)
- Operating System:  All version of Windows, untested on macOS or Linux.
- Steps to Reproduce: Please reach out directly for logs and steps to reproduce the failure.

**Comment by ph** [comment]
@bjmcnic Have you seen this issue recently? I will close it, feel free to reopen if you see it again.

**Comment by bjmcnic** [comment]
@ph Yes, I have encountered this issue recently.  Specifically while testing an 8.1.1 scenario.

**Comment by ph** [comment]
@jlind23 @pierrehilbert I've moved that back to the inbox, we would need to do some investigation.

**Comment by ph** [comment]
@blakerouse maybe something to keep an eye on when implementing v2.

**Comment by bjmcnic** [comment]
Just noting that this remains an issue.  Saw a log from a failed Endpoint integration upgrade (8.5.1) where the upgrade continued to be retried every second or two for hours.

**Comment by jlind23** [comment]
@bjmcnic worth checking it with an 8.6.X version as a lot of changes were made thanks to the V2 control protocol.
cc @blakerouse @michalpristas @cmacknz

**Comment by bjmcnic** [comment]
@jlind23 I tried out an 8.6.X and it indeed appears to no longer occur.

**Comment by jlind23** [comment]
thanks @bjmcnic for the answer, closing this issue then.
