### ISSUE TITLE
[Fleet] Agent fails when host disk space is full, need better support

### ISSUE THREAD

**Issue by EricDavisX** [elastic/elastic-agent#293]
A user brought this to us and I am logging a quick ticket to capture minimal details.

Apparently the Agent failed to install metricbeat, due to a lack of disk space.

It wasn't clear immediately, but some subsequent log diving shows the reason:

`/var/lib/elastic-agent/logs/elastic-agent-json.log.2:{"log.level":"error","@timestamp":"2020-11-11T11:13:12.997-0500","log.origin":{"file.name":"log/reporter.go","file.line":36},"message":"2020-11-11T11:13:12-05:00: type: 'ERROR': sub_type: 'FAILED' message: Application: filebeat--7.9.3--36643631373035623733363936343635[2ff0699f-4ef0-4d57-84b3-053a760c711e]: State changed to FAILED: TarInstaller: error writing to /var/lib/elastic-agent/install/filebeat-7.9.3-linux-x86_64/NOTICE.txt: write /var/lib/elastic-agent/install/filebeat-7.9.3-linux-x86_64/NOTICE.txt: no space left on device","ecs.version":"1.5.0"}`

What should we expect of Elastic Agent here?  Not sure what it can do... except to purge old log files? what else can we think?  and what should be shown in the Activity log, etc?

Thanks @P1llus for bringing it to us in slack

**Comment by jlind23** [comment]
Closing this as outdated / not relevant anymore. In the meantime we are working on a lightweight Elastic Agent binary to minimize the occurences of such scenarios.
cc @nimarezainia
