### ISSUE TITLE
Allow reusing previously provisioned resources for integration testing

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#2933]
This is a follow up from https://github.com/elastic/elastic-agent/issues/2856. The integration framework works well, but running individual tests can take 10+ minutes. This costs significant time in two common use cases:

1. Developing a test for the first time where unexpected problems are common and the test needs to be re-run many times.
2. Repeatedly running a test to reproduce an intermittent issue.

To speed up these two use cases we should eliminate the need to re-provision the VMs the tests run on, and in the case of E2E tests the Elastic Stack deployment they are tested against.

There are two ways to accomplish this:
1. Split the current `mage integration:test` target into two dependent pieces, one to provision resources and prepare them for test execution and another to actually run the tests. This would allow developers to only run the provisioning step a single time. Developers would need to be given the credentials to SSH or RDP into the created VMs to allow manually executing tests and uploading new elastic agent packages.
2. A simpler option proposed in a discussion with @ycombinator, which is to stop immediately destroying resources after a test executes. We would be default leave VMs and clusters after a test executes and allow targeting them for reuse. We would rely on the QA region's automated cleanup of unused resources to remove them, or as an optimization we could write our own batch job to clean up resources tagged as created by the test framework on a regular scheduled (triggered by Buildkite for example).

**Comment by ycombinator** [comment]
> 2. We would rely on the QA region's automated cleanup of unused resources to remove them

I think I was unclear about the QA region aspect mentioned here, so let me try to clarify. 

I  was referring to the ESS QA environment, where Elastic Cloud deployments are automatically cleaned up after a day or so by an automated job managed by the Cloud team.   It's why the test runner uses the ESS QA environment for provisioning stack deployments.  

AFAIK there's no equivalent QA environment (with auto-cleanup) for VMs.  So we'll need to write our own cleanup job as suggested:

> or as an optimization we could write our own batch job to clean up resources tagged as created by the test framework on a regular scheduled (triggered by Buildkite for example).

**Comment by pierrehilbert** [comment]
@alexsapran / @pazone I would be interested to get your opinion here before we will go into the implementation.

**Comment by blakerouse** [comment]
## Overview

I am more interested in making this work by combining 1 and 2, but without a different target. I original like the idea of having `mage integration:prepare` or something similarly named, but I think that you don't always want to prepare all VM's in the case you are just going to run a single test with `mage integration:single`.

My idea is to change the testing runner to maintaining state of what has been setup, prepared, and copied to each host. No longer have it bring down the VM's after the tests are ran.

## Implementation

### First Run

1. Bring up all VM's
2. Run `Prepare` on each host (sets up golang and mage)
3. Copy Agent package to host (copying sha512 as well)
4. Copy repo (this is very small and fast, needed for the test files)
5. Perform the tests
6. Copy test results
7. Leave VM's running

### Second Run

1. Bring up any missing VM's (none missing, nothing to do)
2. Run `Prepare` on each missing host (nothing missing, nothing to do)
3. Copy Agent package to host only if sha512 changed (if same, nothing to do)
4. Copy repo
5. Perform the tests
6. Copy test results
7. Leave VM's runnig

### Clean target

The `mage integration:clean` will be used to bring down and clean up the VM's.

**Comment by cmacknz** [comment]
> Leave VM's running

Per the comment in https://github.com/elastic/elastic-agent/issues/2933#issuecomment-1603324113 we would need some process to ensure the VMs do deterministically get cleaned up eventually if developers forget to run `mage integration:clean`, which will almost certainly happen.

**Comment by blakerouse** [comment]
I think it would be interesting to see if we could possible place a last used timestamp tag on each deployed cloud instance. If possible we could create a periodic job that removes any instance that is X days old, based on the timestamp.

@pazone Is it possible to create a daily job, that just runs?

@pierrehilbert With the investigation into Terraform, I don't know how well it would handle having instances removed out from underneath it. It would be great if it could notice and just redeploy the missing, but if not the entire terraform state would probably need to be removed and re-created. That's not necessarily a bad thing, as chances all the auto cleanup will remove all the instances anyway.

**Comment by pazone** [comment]
@blakerouse I think it's possible. During the hackathon I tried `elastic-package` for creating stack via docker-compose and it was much faster.

**Comment by pchila** [comment]
For GCP at least (I think that all the major cloud providers have similar functionality), we can schedule termination of a machine at creation https://cloud.google.com/compute/docs/instances/limit-vm-runtime#limit-runtime-new-vm 
Maybe this is an easier solution to guarantee that, if our cleanup goes wrong for whatever reason, the VM will be eventually cleaned up.

**Comment by blakerouse** [comment]
> for GCP at least (I think that all the major cloud providers have similar functionality), we can schedule termination of a machine at creation https://cloud.google.com/compute/docs/instances/limit-vm-runtime#limit-runtime-new-vm Maybe this is an easier solution to guarantee that, if our cleanup goes wrong for whatever reason, the VM will be eventually cleaned up.

^ We should use that for sure!

**Comment by pchila** [comment]
We can do it also after creation but it requires stopping the machine first: https://cloud.google.com/compute/docs/instances/limit-vm-runtime#limit-runtime-existing-vm

**Comment by pierrehilbert** [comment]
I will add this to my terraform module, thx for the suggestion @pchila
