### ISSUE TITLE
elastic-agent status cmd does not show beats components

### ISSUE THREAD

**Issue by olegsu** [elastic/elastic-agent#2976]
Running BC image of Elastic-Agent (8.9.0).
Deployed on local kind cluster, connected to ESS environment.

I have deployed Elastic-Agent and installed KSPM integration. 
🟢  I see in Kibana all the documents.
🟢  I see the Fleet agent view the integration
![image](https://github.com/elastic/elastic-agent/assets/23185631/d52f3946-648f-4280-a245-a64dd2e9195f)

🔴 `elastic-agent status` command does not show cloudbeat process. When running with `--output json` the component is part of the response

![image](https://github.com/elastic/elastic-agent/assets/23185631/d5fa08f3-e9ec-450a-95a9-b07bc49a8942)
![image](https://github.com/elastic/elastic-agent/assets/23185631/c86a59ff-6e43-48c6-ab34-6bda9d74ebe4)

**Comment by jlind23** [comment]
This might by an impact of a recent change to the status command introduced by @leehinman : https://github.com/elastic/elastic-agent/pull/2890
Could you please try the "full" option?

**Comment by olegsu** [comment]
Thank you @jlind23 for a quick response.
Indeed, `--output full` shows all the details.
Closing this, I guess I missed that change somehow.
