### ISSUE TITLE
elastic-agent status shows different fleet status/message after upgrade to 8.9.0-826fd88d

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent#3002]
In 8.8.2 elastic-agent status shows:

```
State: HEALTHY
Message: Running
Fleet State: HEALTHY
Fleet Message: Connected
Components:
  * winlog          (HEALTHY)
                    Healthy: communicating with pid '8916'
  * system/metrics  (HEALTHY)
                    Healthy: communicating with pid '5444'
  * endpoint        (HEALTHY)
                    Healthy: communicating with endpoint service
  * log             (HEALTHY)
                    Healthy: communicating with pid '2436'
  * beat/metrics    (HEALTHY)
                    Healthy: communicating with pid '4776'
  * http/metrics    (HEALTHY)
                    Healthy: communicating with pid '1376'
  * filestream      (HEALTHY)
                    Healthy: communicating with pid '6812'
```

After upgrade to 8.9.0-BC2 the Fleet Status and Message are different:

```
┌─ fleet
│  └─ status: (STARTING)
└─ elastic-agent
   └─ status: (HEALTHY) Running
```

The JSON output is different as well:

8.8.2
```
    "FleetState": 2,
    "FleetMessage": "Connected"
```

8.9.0
```
    "FleetState": 0,
    "FleetMessage": ""   
```

Fleet server was up and healthy.

**Comment by cmacknz** [comment]
@pierrehilbert we should get this fixed for 8.9.0 if we can.

**Comment by pchila** [comment]
@cmacknz Last time it was a [missing mapping of the fleet state and message](https://github.com/elastic/elastic-agent/pull/2643) in the output structure of Status GRPC server call. Here the symptom is similar (zero values of fleet state and message) but the mapping should be fine now :thinking:

**Comment by jlind23** [comment]
@pierrehilbert this was mentioned as an 8.9 issue by @leehinman, can someone take a look at this please?

**Comment by pierrehilbert** [comment]
This one is not a blocker but yes we should do our best to fix it.
@pchila, as you fixed the previous issue, would you mind to have a look here please?

**Comment by pchila** [comment]
Tested straight install from main (8.10.0-SNAPSHOT) on linux and the fleet status is reported correctly.
Test with a straight install with 8.9.0 BC4 is next. If even this tests ok, it leaves the windows os or the upgrade process as a possible cause for the issue

**Comment by pierrehilbert** [comment]
Thx @pchila for your investigations and clarifications here.
For the long poll it can be great, as you mentioned, to have a different value for the first checkin.
