### ISSUE TITLE
Endpoint fails to connect on assigning to a policy without Elastic Defend and then back to policy with Elastic Defend.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3033]
**Kibana Build details:**
```
BUILD: 64584 BC3
COMMIT: fc463b96275c55dc44524f79f617b0026b7f8667
Agent Binary: https://staging.elastic.co/8.9.0-0d830bd0/downloads/
```

**Host OS and Browser version:** Windows, All

**Preconditions:**
1. 8.9.0 BC3 Kibana cloud environment should be available.
2. Windows agent should be installed using Elastic Defend Integration.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Create a policy with System integration and do not add Elastic Defend integration.
3. Assign agent with Elastic defend to the policy without Defend.
4. Wait for agent to get to Healthy state after Updating.
5. Observe Endpoint folder is not removed from `C:\Program Files\Elastic\`.
6. Wait 3-4 minutes, and assign back to agent policy with Elastic Defend integration.
7. Observe after few minutes agent gets Unhealthy and fails to connect Endpoint.

**Expected:**
Endpoint shouldn't fail to connect on assigning to a policy without Elastic Defend and then back to policy with Elastic Defend.

**Screenshot:**
![19](https://github.com/elastic/elastic-agent/assets/77374876/c5e3caa1-3726-4d5b-9a1f-3652fc437b86)

https://github.com/elastic/elastic-agent/assets/77374876/3ffe48fc-af03-437e-9fa1-fe241c91f09a

**Debug Logs:**
[elastic-agent-diagnostics-2023-07-06T14-37-58Z-00.zip](https://github.com/elastic/elastic-agent/files/11974759/elastic-agent-diagnostics-2023-07-06T14-37-58Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by pierrehilbert** [comment]
@cmacknz could we add this scenario to https://github.com/elastic/elastic-agent/issues/2948
@amolnater-qasource was this working in 8.8.2 / 8.7.1?

**Comment by amolnater-qasource** [comment]
Hi @pierrehilbert 

Thank you for looking into this.
We have revalidated this issue on 8.8.2 and 8.7.1 kibana cloud environments and found it **not reproducible** there.

**Observations:**
- Existing Endpoint folder gets removed on assigning to policy without Elastic Defend.
- Agent successfully reconnects on assigning back to policy with Elastic Defend.

**Screenshot 8.8.2:**
![20](https://github.com/elastic/elastic-agent/assets/77374876/5cb7083a-ce9a-4ba6-a18c-ce077be28b2a)

**Logs 8.8.2:**
[elastic-agent-diagnostics-2023-07-07T06-54-24Z-00.zip](https://github.com/elastic/elastic-agent/files/11977187/elastic-agent-diagnostics-2023-07-07T06-54-24Z-00.zip)


**Screenshot 8.7.1:**
![21](https://github.com/elastic/elastic-agent/assets/77374876/6c966730-f510-47d0-96fc-7565b1f5f828)

**Logs 8.7.1:**
[elastic-agent-diagnostics-2023-07-07T07-03-34Z-00.zip](https://github.com/elastic/elastic-agent/files/11977205/elastic-agent-diagnostics-2023-07-07T07-03-34Z-00.zip)

Please let us know if anything else is required from our end.

Thanks!

**Comment by cmacknz** [comment]
> @cmacknz could we add this scenario to https://github.com/elastic/elastic-agent/issues/2948 ?

Yes if this turns out to be an agent bug.

**Comment by cmacknz** [comment]
I've extracted the agent logs for the service command runtime, nothing is jumping out right now.

[service_command.log](https://github.com/elastic/elastic-agent/files/11986228/service_command.log)

**Comment by cmacknz** [comment]
This is likely to be the same problem causing https://github.com/elastic/elastic-agent/issues/3077

**Comment by cmacknz** [comment]
This should be fixed now, closing. Please retest and reopen this if the problem still exists.

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/28390

Thanks
