### ISSUE TITLE
Include agent version in user-agent header for Beats

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#3065]
Today, the user-agent sent by Filebeat, Metricbeat, etc. when running under Elastic Agent is the same as when running the Beat standalone. This prevents us from understanding how much data volume is ingested by Elastic Agent vs. regular Beats, as well as other types of things we'd like to track such as error rates. It would also be helpful to report standalone vs. managed in the user agent.

We should modify Beats to report a different user-agent when running under Elastic Agent to solve this.

We could consider a pattern similar to browsers where some the more detailed information is included in parenthesis: `Metricbeat 8.10.0 (Elastic Agent 8.10.0; Fleet-managed)`.

We may also want to include OS, etc. later, but let's leave that out of scope for now.

**Comment by amitkanfer** [comment]
won't this be easier to resolve after we have the shipper?

**Comment by joshdover** [comment]
I think it's essentially the same work regardless of order 🤷
