### ISSUE TITLE
Collect [filebeat|metricbeat]-monitoring logs and config on diagnostics collect command

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#307]
**Describe the enhancement:**

Collect diagnostics for the monitoring filebeat and metricbeat as well

**Describe a specific use case for the enhancement or feature:**

In order to debug why the elastic-agent or beats logs and metrics aren't as e being collected or seems to be wrong/missing we need these logs

**Comment by jlind23** [comment]
Closing this as fixed, feel free to reopen it if need be.
