### ISSUE TITLE
Possible deadlock when Uninstalling agent

### ISSUE THREAD

**Issue by michalpristas** [elastic/elastic-agent#3082]
There are reported cases of agent uninstall being unresponsive and timing out (CLI Command) 
looking at logs these events are not noticed by agent. behavior is similar to deadlocks/starvation situation we had with high number of events flowing through coordinator

Reported version is 8.7.1+, most of race fixes were already present at 8.7.1

**Comment by pierrehilbert** [comment]
@faec did you see something for this one during your investigation around race conditions?

**Comment by faec** [comment]
> did you see something for this one during your investigation around race conditions?

No, I've mostly been investigating the Coordinator and adjacent, the uninstall code wasn't really on my radar. I will keep it in mind though.

**Comment by cmacknz** [comment]
Believe this is a duplicate of https://github.com/elastic/elastic-agent/issues/3372, closing.
