### ISSUE TITLE
Ubuntu Agent fails to upgrade if shutdown on triggering upgrade and started after 10 minutes.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3083]
**Kibana Build details:**
```
VERSION: 8.9.0 BC4
BUILD: 64661
COMMIT: ddf0c1972e43898b6890ddb38f4c016e96538239
Agent Binary: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.8.2-linux-x86_64.tar.gz
```

**Host OS and Browser version:** Ubuntu, All

**Preconditions:**
1. 8.9.0 BC4 Kibana cloud environment should be available.
2. Lower version 8.8.2 agent should be installed using Elastic Defend Integration.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Trigger upgrade for lower version agent.
3. Observe the log line- Upgrading agent under agent logs tab.
4. Immediately shutdown the Ubuntu machine before the elastic-agent upgrades.
5. Keep the machine off for 10-12 minutes.
6. Turn the machine ON, and observe agent gets to Updating state.
7. Observe agent gets stuck in updating state.

**Note:**
- The issue is reproducible for multiple Ubuntu agents.
- If we waited for 1 minute before shutdown, it upgrades the elastic-agent to the latest version till then and only Endpoint is left to upgrade.
  So in this scenario, we Stopped the agent to upgrade to latest version.

**Expected:**
Ubuntu Agent should upgrade successfully if shutdown on triggering upgrade and started after 10 minutes.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/8cd1fb59-8f38-409e-a5f6-34b86c0ac6f0)

https://github.com/elastic/elastic-agent/assets/77374876/a121a322-d3b7-42a0-8549-457119350388

**Debug Logs:**
[elastic-agent-diagnostics-2023-07-14T08-29-12Z-00.zip](https://github.com/elastic/elastic-agent/files/12048208/elastic-agent-diagnostics-2023-07-14T08-29-12Z-00.zip)

[elastic-agent-diagnostics-2023-07-14T09-01-16Z-00.zip](https://github.com/elastic/elastic-agent/files/12048207/elastic-agent-diagnostics-2023-07-14T09-01-16Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by amolnater-qasource** [comment]
Hi Team,
We have revalidated this issue on latest 8.10.1 BC1 kibana cloud environment and had below observations

**Observations:**
- Ubuntu Agent fails to upgrade if shutdown on triggering upgrade and started after 10 minutes.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/2d2fd928-1c0d-42e1-915d-578862a1f55f)

**Build details:**
VERSION: 8.10.1 BC1
BUILD: 66390
COMMIT: 6957ba896ec80fbaeaa269debfdce1478bdde661

Please let us know if anything else is required from our end.

Thanks!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/269917

Thanks

**Comment by AndersonQ** [comment]
I had a quick look and whereas it seems an issue persisting the upgrade action to disk, I did not find evidence of it being the same as https://github.com/elastic/elastic-agent/issues/3912. but again, I only had a quick look and did not try to reproduce it.

@amolnater-qasource could you please clarify what the diagnostics you shared are?
are they from the same agent?
are they from different agents?
are they from the same test? if so, why there are 2?

**Comment by amolnater-qasource** [comment]
Hi @AndersonQ 

Thank you for looking into this.

> could you please clarify what the diagnostics you shared are?

We shared the logs from two different agents stuck for upgrade and just shared two logs zip if there's any difference in the logs.

Further the issue is reproducible with the above shared steps while upgrading agent from 8.11.4>8.12.1 BC1.

**Build details:**
VERSION: 8.12.1 BC1
BUILD: 70228
COMMIT: 3457f326b763887d154c9da00bd4e489221a2ff3

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/35479270-ab4e-4e82-939b-7cb2cf8a456c)

**Agent Logs:**
[elastic-agent-diagnostics-2024-02-02T11-25-35Z-00.zip](https://github.com/elastic/elastic-agent/files/14139286/elastic-agent-diagnostics-2024-02-02T11-25-35Z-00.zip)


Please let us know if there's any other requirement from our end.
Thanks!

**Comment by AndersonQ** [comment]
It seems to be related to:
 - https://github.com/elastic/elastic-agent/issues/3912
I'll fix it then we check again if this error persists.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.15.0 BC1 kibana cloud environment and had below observations:

**Observations:**
- On triggering upgrade we turned off the host immediately for 15 minutes.
- Restarted the host and observed that agent upgrade gets reset.
- We had to re-trigger upgrade and agent gets upgraded successfully.

**Logs:**
[elastic-agent-diagnostics-2024-07-08T05-30-09Z-00.zip](https://github.com/user-attachments/files/16123085/elastic-agent-diagnostics-2024-07-08T05-30-09Z-00.zip)

**Screenshots:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/aca899f4-1b5b-4db5-a0a4-c9644cb568c7)
![image](https://github.com/elastic/elastic-agent/assets/77374876/c607edca-bd76-4760-aa9f-1d5912f8bab3)
![image](https://github.com/elastic/elastic-agent/assets/77374876/b04d2a3c-ffae-477e-afe2-a581ea7e70e5)


Hence, we are marking this issue as **QA:Validated**.

Please let us know if we are missing anything here.

Thanks!

**Comment by AndersonQ** [comment]
Hello @amolnater-qasource,

Help me to fully understand the current behaviour:

 - an upgrade is issued on Kibana (immediate upgrade, not a scheduled one)
 - then once the agent is on "upgdating" on kibana, the host is shut down
 - once the host is back online, the agent status on kibana is health and it's on the start version
 - now, a new upgrade must be issued for the agent to indeed upgrade. 

Is it the current behaviour?

**Comment by amolnater-qasource** [comment]
@AndersonQ yes, this is the current behaviour.
