### ISSUE TITLE
Track and report upgrade details

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#3119]
**Describe the enhancement:**

Elastic Agent should track details about an ongoing upgrade and report them to Fleet Server.

**Describe a specific use case for the enhancement or feature:**

To understand where upgrades fail or get stuck without progressing.

**What is the definition of done?**

* [x] Elastic Agent is able to track the various upgrade states (defined below) representing details about an ongoing upgrade and correctly transition between these states.
* [x] Elastic Agent is able to report a change in an upgrade state to Fleet Server via a new `upgrade_details` field in the check-in API.
* [ ] For backwards compatibility, Elastic Agent continues to acknowledge the `UPGRADE` action with Fleet Server, via the acknowledgements API, as before.
 
**Details**

In the future, Elastic Agents will send details about an ongoing upgrade to Fleet Server.  These details will be communicated via a new `upgrade_details` field in check-in API requests.  

The proposed structure of the `upgrade_details` field is:

```json
{
  "upgrade_details": { // new field; present when upgrade is in progress
    "target_version": "8.12.0", // version being upgraded to; always present
    "action_id": "xxxxxxxx", // ID of the UPGRADE action
    "state": "UPG_*",
    "metadata": {
      "scheduled_at": "2023-08-09T10:11:12Z", // when state == "UPG_SCHEDULED"
      "download_percent": 16.4, // when state == "UPG_DOWNLOADING"
      "failed_state": "UPG_*" // when state == "UPG_FAILED"
      "error_msg": "" // when state == "UPG_FAILED"
    }
  }
}
```

Where `upgrade_details.state` is expected to hold one of the following values:

| State | Meaning |
| -- | -- |
| `UPG_REQUESTED` | Upgrade requested by user |
| `UPG_SCHEDULED` | Upgrade scheduled for <date/time> |
| `UPG_DOWNLOADING` | Downloading new Agent artifact version <version> |
| `UPG_EXTRACTING` | Extracting new Agent artifact version <version> |
| `UPG_REPLACING` | Replacing old Agent artifact version <version> with new one version <version> |
| `UPG_RESTARTING` | Starting new Agent version <version> |
| `UPG_WATCHING` | Monitoring new Agent version <version> |
| `UPG_ROLLBACK` | Upgrade unsuccessful; rolling back to Agent version <version> |
| `UPG_FAILED` | Upgrade failed due to error <error> from state <state> |

The possible transitions between these states are:

![upgrade_states](https://github.com/elastic/elastic-agent/assets/51061/fbbcacf1-e38d-401d-b3d4-9bb8bf0b6c2f)

The various points in the upgrade workflow at which these state transitions would occur are:

```mermaid
sequenceDiagram
    actor U as User
    participant UI as Fleet UI
    participant ES
    participant FS as Fleet Server
    participant A as Agent
    participant UW as Upgrade Watcher
    participant UM as Upgrader Marker

    U->>UI: Initiate upgrade
    UI->>ES: Update Agent doc in `.fleet-agents`<br />set `upgrade_started_at`
    UI->>UI: Show Agent status as "updating"
    UI->>ES: Create new doc in `.fleet-actions` for `UPGRADE` action
    A->>FS: Check-in request
    FS->>ES: Read pending actions from .fleet-actions
    FS->>A: Check-in response
    A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_REQUESTED`
    A->>A: Queue upgrade action
    alt If upgrade is scheduled for future
        A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_SCHEDULED`
    end
    alt If upgrade start fails
       A->>FS: Ack failed upgrade
       A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_ERROR` with `upgrade_details.failed_state_id` = `UPG_REQUESTED` or `UPG_SCHEDULED`
       FS->>ES: Update Agent doc in `.fleet-agents`<br />set `upgrade_status` = "failed"
       FS-->>ES: Set `upgrade_details` = value of `upgrade_details` from check-in request
       UI-->>UI: Agent status = "upgrade failed"
       UI->>UI: Agent status remains as "updating" (bug) (fallback)
    else
       opt If previous upgrades found
          A->>FS: Ack previous upgrades
          A->>A: Remove previous upgrades from queue
       end
       A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_DOWNLOADING`
       A->>A: Download new Agent artifact
       opt If download fails
          A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_ERROR` with `upgrade_details.failed_state_id` = `UPG_DOWNLOADING`
          FS-->>ES: Set `upgrade_details` = value of `upgrade_details` from check-in request
          UI-->>UI: Agent status = "upgrade failed"
       end
       A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_EXTRACTING`
       A->>A: Extract new Agent artifact
       opt If extraction fails
          A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_ERROR` with `upgrade_details.failed_state_id` = `UPG_EXTRACTING`
          FS-->>ES: Set `upgrade_details` = value of `upgrade_details` from check-in request
          UI-->>UI: Agent status = "upgrade failed"
       end
       A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_REPLACING`
       A->>A: Replace current Agent artifact with new one
       opt If extraction fails
          A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_ERROR` with `upgrade_details.failed_state_id` = `UPG_REPLACING`
          FS-->>ES: Set `upgrade_details` = value of `upgrade_details` from check-in request
          UI-->>UI: Agent status = "upgrade failed"
       end
       A->>UM: Create
       A->>UW: Start
       A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_RESTARTING`
       A->>A: Rexec to start new Agent artifact
       opt If restart fails
          A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_ERROR` with `upgrade_details.failed_state_id` = `UPG_RESTARTING`
          FS-->>ES: Set `upgrade_details` = value of `upgrade_details` from check-in request
          UI-->>UI: Agent status = "upgrade failed"
       end
       A-->>FS: Check-in request: `upgrade_details.state_id` = `UPG_WATCHING`
       UI-->>UI: Show Agent status as "upgrade watching"
       UW->>UW: Watch new Agent
   end
   opt Success
       A->>FS: Ack successful upgrade
       FS->>ES: Write successful ack in `.fleet-actions-results`
       FS->>ES: Update Agent doc in `.fleet-agents`<br />set `upgrade_status` = null<br />`upgraded_at` = <now><br />`upgrade_started_at` = null
       UI->>UI: Show Agent status as "healthy" (fallback)
       UW->>UM: Remove
       A-->>UM: Watch for removal
       A-->>FS: Check-in request: remove `upgrade_details` field
       FS-->>ES: Update Agent doc in `.fleet-agents`<br />remove `upgrade_details` field
       UI-->>UI: Show Agent status as "healthy"
   end
   opt Rollback
       UW->>UM: Write `upgrade_details.state_id` = `UPG_ROLLBACK`
       UW->>A: Start
       A-->>UM: Read `upgrade_details.state_id`
       A-->>FS: Check-in request: `upgrade_details.state_id` = value from UM
       A->>FS: Ack failed upgrade
       FS-->>ES: Set `upgrade_details` = value of `upgrade_details` from check-in request
       FS->>ES: Update Agent doc in `.fleet-agents`<br />set `upgrade_status` = null<br />`upgraded_at = <now> (fallback)
       UI->>UI: Show Agent status as "healthy" (fallback)
       UW->>UM: Remove
       A-->>UM: Watch for removal
       A-->>FS: Check-in request: remove `upgrade_details` field
       FS-->>ES: Update Agent doc in `.fleet-agents`<br />remove `upgrade_details` field
       UI-->>UI: Show Agent status as "healthy"
   end
```

**Comment by ycombinator** [comment]
I'm going to start implementing this enhancement now.  I'm breaking it down into the following sub-tasks with the idea of each sub-task resulting in a single PR, to make it easier to review this feature and also track incremental progress.

- [ ] Create state machine in Elastic Agent to model upgrade states and allow various parts of Agent to perform transitions between states
- [ ] Log state transitions in Agent log at `INFO` level
- [ ] When in Fleet-managed mode, whenever there is a state transition, call check-in API call to Fleet, with upgrade details in new `upgrade_details` field
- [ ] Include the current upgrade state, and possibly any details about it, in the output of `elastic-agent status`
- [ ] Include the current upgrade state, and possibly any details about it, in the output of `elastic-agent diagnostics` and diagnostics requests from Fleet
- [ ] For backwards compatibility, ensure that Elastic Agent continues to acknowledge the `UPGRADE` action with Fleet Server via the acknowledgements API

**Comment by cmacknz** [comment]
> When in Fleet-managed mode, whenever there is a state transition, call check-in API call to Fleet, with upgrade details in new upgrade_details field.

The impact of the increased check ins will need to go through scale testing, so you'll need to update Horde or perhaps take on some of https://github.com/elastic/elastic-agent/issues/2169.

I would suggest you make this possible but don't actually change the check in frequency so we can release this without impacting the system stability, and increase the checkin frequency separately.

**Comment by blakerouse** [comment]
Tracking and reporting upgrade details is completed in 8.12.

**Comment by amitkanfer** [comment]
well done team! Happy to see this getting closed. 🚀
