### ISSUE TITLE
Remove dependencies on beats in favor or elastic-agent-libs

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent#314]
We are moving the libs to [elastic-agent](https://github.com/elastic/elastic-agent-libs)
The list below was generated using "rg "beats/v7 -l"

- [ ] dev-tools/mage/check.go
- [ ] internal/pkg/basecmd/version/cmd_test.go
- [ ] internal/pkg/core/process/process.go
- [ ] internal/pkg/core/plugin/process/start.go
- [ ] internal/pkg/core/monitoring/server/stats.go
- [ ] internal/pkg/core/monitoring/server/process.go
- [ ] internal/pkg/core/monitoring/server/server.go
- [ ] internal/pkg/core/monitoring/config/config_test.go
- [ ] internal/pkg/capabilities/capabilities_test.go
- [ ] internal/pkg/remote/client.go
- [ ] internal/pkg/remote/config_test.go
- [ ] internal/pkg/artifact/download/http/elastic_test.go
- [ ] internal/pkg/artifact/download/http/verifier.go
- [ ] internal/pkg/artifact/download/http/downloader.go
- [ ] internal/pkg/artifact/download/snapshot/downloader.go
- [ ] internal/pkg/artifact/download/fs/verifier_test.go
- [ ] internal/pkg/artifact/config.go
- [ ] internal/pkg/remote/config.go
- [ ] internal/pkg/composable/registry.go
- [ ] internal/pkg/agent/operation/common_test.go
- [ ] internal/pkg/agent/control/control_test.go
- [ ] internal/pkg/agent/control/client/dial_windows.go
- [ ] internal/pkg/agent/control/server/listener_windows.go
- [ ] internal/pkg/agent/configuration/fleet_server.go
- [ ] internal/pkg/agent/transpiler/vars_test.go
- [ ] internal/pkg/agent/cmd/uninstall.go
- [ ] internal/pkg/agent/cmd/enroll_cmd.go
- [ ] internal/pkg/agent/cmd/enroll.go
- [ ] internal/pkg/agent/cmd/container.go
- [ ] internal/pkg/agent/cmd/common.go
- [ ] internal/pkg/agent/cmd/inspect.go
- [ ] internal/pkg/agent/cmd/run.go
- [ ] internal/pkg/agent/install/uninstall.go
- [ ] internal/pkg/agent/transpiler/vars.go
- [ ] internal/pkg/composable/controller.go
- [ ] internal/pkg/composable/providers/docker/docker_test.go
- [ ] internal/pkg/composable/providers/docker/docker.go
- [ ] internal/pkg/composable/providers/kubernetes/config.go
- [ ] internal/pkg/composable/providers/kubernetes/node_test.go
- [ ] internal/pkg/composable/providers/kubernetes/node.go
- [ ] internal/pkg/config/operations/inspector.go
- [ ] internal/pkg/composable/providers/kubernetes/pod_test.go
- [ ] internal/pkg/composable/providers/kubernetes/service.go
- [ ] internal/pkg/composable/providers/kubernetes/pod.go
- [ ] internal/pkg/composable/providers/kubernetes/kubernetes.go
- [ ] internal/pkg/composable/providers/kubernetes/service_test.go
- [ ] internal/pkg/composable/providers/docker/config.go
- [ ] internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets_test.go
- [ ] internal/pkg/composable/providers/kubernetesleaderelection/kubernetes_leaderelection.go
- [ ] internal/pkg/composable/providers/kubernetesleaderelection/config.go
- [ ] internal/pkg/composable/providers/kubernetessecrets/config.go
- [ ] internal/pkg/composable/providers/kubernetessecrets/kubernetes_secrets.go

**Comment by jlind23** [comment]
@ph shouldn't we close this PR as it will be fixed by : https://github.com/elastic/elastic-agent/pull/344 ?

**Comment by kvch** [comment]
There is one more small dependency on Metricbeat as well. I will address that in a new PR today.

**Comment by jlind23** [comment]
@kvch can i close this issue then?

**Comment by jlind23** [comment]
Closing this as fixed, feel free to reopen it if need be.
