### ISSUE TITLE
Collecting diagnostics in 8.10 takes 3 minutes if Elastic Defend is installed

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#3197]
Collecting diagnostics now takes almost exactly 3 minutes every time when using the default configuration with the system integration on main (8.10).

```sh
❯ time sudo elastic-agent diagnostics
[WARNING] Could not redact state.yaml due to unmarshalling error: yaml: invalid map key: map[interface {}]interface {}{"unitid":"log-default-logfile-system-ee627672-4cb2-49fd-8a56-6406b056490a", "unittype":0}
Created diagnostics archive "elastic-agent-diagnostics-2023-08-04T18-09-42Z-00.zip"
***** WARNING *****
Created archive may contain plain text credentials.
Ensure that files in archive are redacted before sharing.
*******************
sudo elastic-agent diagnostics  0.12s user 0.06s system 0% cpu 3:00.21 total
```

Using the official 8.9 release this takes 40s, which is still long but much faster than 3 minutes:

```sh
 time sudo elastic-agent diagnostics
[WARNING] Could not redact state.yaml due to unmarshalling error: yaml: invalid map key: map[interface {}]interface {}{"unitid":"log-default", "unittype":1}
Created diagnostics archive "elastic-agent-diagnostics-2023-08-04T18-17-29Z-00.zip"
***** WARNING *****
Created archive may contain plain text credentials.
Ensure that files in archive are redacted before sharing.
*******************
sudo elastic-agent diagnostics  0.13s user 0.03s system 0% cpu 40.364 total
```

Reverting https://github.com/elastic/elastic-agent/pull/3118 brings the time back down to 40s, so it looks like something in that change caused this regression.

**Comment by cmacknz** [comment]
@fearful-symmetry FYI

**Comment by fearful-symmetry** [comment]
looking into this. @cmacknz what was the config? What were the enabled components/units?

**Comment by fearful-symmetry** [comment]
Perhaps unsurprisingly, my normal agent set-up-and-test isn't reproducing this. Trying to figure out what I missed.

**Comment by cmacknz** [comment]
I installed the agent using the default configuration, then enrolled it into Fleet where the agent policy had monitoring enabled and the system integration installed.

**Comment by cmacknz** [comment]
```sh
sudo elastic-agent status --output=full
┌─ fleet
│  └─ status: (HEALTHY) Connected
└─ elastic-agent
   ├─ status: (HEALTHY) Running
   ├─ info
   │  ├─ id: 84f3e138-0a62-4ad4-b0f5-b4aa36c8bf71
   │  ├─ version: 8.10.0
   │  └─ commit: 382b8eb8a8b53f873c08c95cdb95447fb5815d56
   ├─ beat/metrics-monitoring
   │  ├─ status: (HEALTHY) Healthy: communicating with pid '12701'
   │  ├─ beat/metrics-monitoring
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ beat/metrics-monitoring-metrics-monitoring-beats
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
   ├─ endpoint-default
   │  ├─ status: (STARTING) Starting: endpoint service runtime
   │  ├─ endpoint-default
   │  │  ├─ status: (STARTING) Starting: endpoint service runtime
   │  │  └─ type: OUTPUT
   │  └─ endpoint-default-9ad62f51-d7af-4027-9dd2-b8114fab88a0
   │     ├─ status: (STARTING) Starting: endpoint service runtime
   │     └─ type: INPUT
   ├─ filestream-monitoring
   │  ├─ status: (HEALTHY) Healthy: communicating with pid '12697'
   │  ├─ filestream-monitoring
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ filestream-monitoring-filestream-monitoring-agent
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
   ├─ http/metrics-monitoring
   │  ├─ status: (HEALTHY) Healthy: communicating with pid '12706'
   │  ├─ http/metrics-monitoring
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ http/metrics-monitoring-metrics-monitoring-agent
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
   ├─ log-default
   │  ├─ status: (HEALTHY) Healthy: communicating with pid '12661'
   │  ├─ log-default
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  └─ log-default-logfile-system-ee627672-4cb2-49fd-8a56-6406b056490a
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
   └─ system/metrics-default
      ├─ status: (HEALTHY) Healthy: communicating with pid '12690'
      ├─ system/metrics-default
      │  ├─ status: (HEALTHY) Healthy
      │  └─ type: OUTPUT
      └─ system/metrics-default-system/metrics-system-ee627672-4cb2-49fd-8a56-6406b056490a
         ├─ status: (HEALTHY) Healthy
         └─ type: INPUT
```

**Comment by cmacknz** [comment]
Ah apparently I have endpoint installed and forgot about it.

**Comment by fearful-symmetry** [comment]
Yah, still can't reproduce this. I wonder if it's something to do with Endpoint...

**Comment by cmacknz** [comment]
If I remove endpoint, diagnostics collection completes almost immediately (135ms).

So prior to the CPU profiling change, having endpoint installed made this go from instant to 40s. After the CPU profiling change that goes up to 3m.

One key here is that endpoint security doesn't handle our diagnostics request right now, if we have a timeout on those requests we are probably hitting them.

**Comment by cmacknz** [comment]
Yeah https://github.com/elastic/elastic-agent/pull/3118/files increased the default timeout from `20*time.Second` to `time.Minute`.

* Before: we time out on the input+output unit diagnostics requests, 2x20s = 40s
* After: we time out on the component+input+output unit diagnostics requests, 3x1m = 3m

**Comment by cmacknz** [comment]
In the v2 client the action RPC is a bidirectional stream:

```protobuf
    // Called by the client on connection to the GRPC allowing the Elastic Agent to stream action
    // requests to the application and the application stream back responses to those requests.
    //
    // Request and response is swapped here because the Elastic Agent sends the requests in a stream
    // to the connected process. The order of response from the process does not matter, it is acceptable
    // for the response order to be different then the request order.
    rpc Actions(stream ActionResponse) returns (stream ActionRequest);
```

This means there is no way for us to detect an unimplemented error immediately, since all clients must implement this RPC. They will just ignore actions they don't support, meaning we hit the timeout every time.

**Comment by fearful-symmetry** [comment]
yah, tried to install Elastic Defend, but getting an `input not supported` error.

@cmacknz the timeout is to accommodate for the CPU profiling; we can look into making different timeouts depending on if we have CPU profiling selected, but I assume the _actual_ problem is why it's timing out. If I remember, endpoint has its own implementation of the elastic-agent-client, and I wonder if there's a compatibility issue here

**Comment by fearful-symmetry** [comment]
ah, yah, there we go, `Actions` is probably where this is coming from

**Comment by cmacknz** [comment]
@blakerouse any thoughts on a nice way to deal with this?

We could add an UNIMPLEMENTED status to `ActionResponse` and try to get all the clients to return that instead of ignoring actions they don't support.

```protobuf
// An action response is streamed from the application back to the Elastic Agent to provide a result to
// an action request.
message ActionResponse {
    // Status result of the action.
    enum Status {
        // Action was successful.
        SUCCESS = 0;
        // Action has failed.
        FAILED = 1;
    }
```

I don't know that this is guaranteed to solve the problem though, because someone can always forget to do this but it's better than being unable to tell the difference between "this actually took to long" and "no response possible because this isn't supported".

**Comment by fearful-symmetry** [comment]
So, it seems like there's three separate issues here:
- We probably want different timeouts for CPU profiling and non-CPU profiling diagnostic runs
- endpoints needs to update their client
- We need a way to handle unsupported responses in Actions.
