### ISSUE TITLE
[Flaky Test] TestRemovePath (internal/pkg/agent/install)

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#3221]
## Flaky Test

* **Test Name:** TestRemovePath (internal/pkg/agent/install).
* **Link:** [Link to file/line number in github.](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/install/uninstall_windows_test.go#L54)
* **Branch:** Git branch the test was seen in. If a PR, the branch the PR was based off.
   - https://github.com/elastic/elastic-agent/pull/3214
   - main
* **Artifact Link:** https://fleet-ci.elastic.co/blue/organizations/jenkins/elastic-agent%2Felastic-agent-mbp/detail/PR-3214/4/pipeline/1973
* **Notes:** Perhaps the time between starting the binary and trying to remove it is, sometimes, so short windows considers other process is using it.

### Stack Trace

```
[2023-08-10T08:08:27.569Z] === Failed

[2023-08-10T08:08:27.569Z] === FAIL: internal/pkg/agent/install TestRemovePath (0.62s)

[2023-08-10T08:08:27.569Z]     uninstall_windows_test.go:54: 

[2023-08-10T08:08:27.569Z]         	Error Trace:	C:/Users/jenkins/workspace/_agent_elastic-agent-mbp_PR-3214/src/github.com/elastic/elastic-agent/internal/pkg/agent/install/uninstall_windows_test.go:54

[2023-08-10T08:08:27.569Z]         	Error:      	Received unexpected error:

[2023-08-10T08:08:27.569Z]         	            	failed to open handle for "C:\\Users\\jenkins\\AppData\\Local\\Temp\\TestRemovePath1878842873\\001\\subdir\\main.exe": The process cannot access the file because it is being used by another process.

[2023-08-10T08:08:27.569Z]         	Test:       	TestRemovePath

[2023-08-10T08:08:27.569Z] 

```

**Comment by blakerouse** [comment]
I ran this test in isolation for over 12 hours in an endless loop with no failures before merging, so either something changed to cause this to start failing or the runner is just way too slow and the times need to be adjusted on the test.

**Comment by cmacknz** [comment]
> I ran this test in isolation for over 12 hours in an endless loop with no failures before merging, so either something changed to cause this to start failing or the runner is just way too slow and the times need to be adjusted on the test.

Likely this is the case, the Windows 8 (the OS for the failure here) and Windows 10 workers seem to frequently cause timing related test failures.

**Comment by cmacknz** [comment]
Reopening, this is still happening. Example of a recent failure: https://fleet-ci.elastic.co/job/elastic-agent/job/elastic-agent-mbp/job/main/1342/testReport/junit/github/com_elastic_elastic-agent_internal_pkg_agent_install/extended_windows___Matrix___PLATFORM____windows_8____Test___TestRemovePath/

```
=== RUN   TestRemovePath
    uninstall_windows_test.go:54: 
        	Error Trace:	C:/Users/jenkins/workspace/tic-agent_elastic-agent-mbp_main/src/github.com/elastic/elastic-agent/internal/pkg/agent/install/uninstall_windows_test.go:54
        	Error:      	Received unexpected error:
        	            	failed to open handle for "C:\\Users\\jenkins\\AppData\\Local\\Temp\\TestRemovePath2024579767\\001\\subdir\\main.exe": The process cannot access the file because it is being used by another process.
        	Test:       	TestRemovePath
--- FAIL: TestRemovePath (0.66s)
```
