### ISSUE TITLE
IDs are required for filestream inputs on Filebeat monitoring

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#323]
When Elastic-Agent sets up the monitoring Filebeat, every filestream input used needs to have a unique and stable ID.

If unique IDs are not set, every Filebeat restart will lead to data duplication. If the IDs are not stable, files will be re-read from the beginning on a Filebeat (or input) restart.

The best way to ensure there are no issues with the filestream inputs is to watch out for the error logs as described in the related issue.

## Related issues
- https://github.com/elastic/beats/issues/31239

**Comment by jlind23** [comment]
@cmacknz can I close this one in favour of https://github.com/elastic/beats/issues/31512
cc @ph
