### ISSUE TITLE
[Windows]: Agent with debug logs set gets unhealthy on removing Elastic Defend when Agent tamper protection is enabled.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3233]
**Kibana Build details:**
```
VERSION: 8.10.0 SNAPSHOT
BUILD: 65900
COMMIT: 384a1f16c0b54acf6b501ac084024cf84b9abb5a
```

**Host OS and Browser version:** Windows, All

**Preconditions:**
1. 8.10.0 SNAPSHOT Kibana cloud environment should be available.
2. A Windows agent should be installed.
3. Feature flag should be enabled for Tamper Protection feature.
4. Agent Tamper protection should be enabled under Agent Policy.

**Steps to reproduce:**
1. Navigate to Agent>Logs tab and set logging level to `debug`.
2. After few minutes navigate to agent policy and remove Elastic Defend integration.
3. Observe Windows agent gets stuck in `Out of date` state.
5. After 5 minutes agent goes offline(time varies everytime, roughly 2-5 minutes).
6. Then observe agent gets back Unhealthy for sometime.
7. After more 1-2 minutes agent gets back Healthy.

**Agent.json:**
[ec2amaz-58nvcvs-agent-details.zip](https://github.com/elastic/elastic-agent/files/12333867/ec2amaz-58nvcvs-agent-details.zip)

**Agent Logs:**
[elastic-agent-diagnostics-2023-08-14T10-23-31Z-00.zip](https://github.com/elastic/elastic-agent/files/12333868/elastic-agent-diagnostics-2023-08-14T10-23-31Z-00.zip)

**Expected Result:**
`Agent tamper protection` should be enabled in the duplicate policy also, when enabled in the original policy.

**Note:**
- The issue is consistently reproducible for Windows agent.

**Screenshot:**
![6](https://github.com/elastic/elastic-agent/assets/77374876/6d830b3b-d080-4c04-b90c-f01749e0457f)
![image](https://github.com/elastic/elastic-agent/assets/77374876/951e362d-23a9-40fe-9ac1-134c2bd7ff20)
![image](https://github.com/elastic/elastic-agent/assets/77374876/f1100e14-fcd3-4123-a0b7-a460c5b04590)

**Related Feature:**
https://github.com/elastic/elastic-agent/pull/2781

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by pierrehilbert** [comment]
@aleksmaus would you mind to have a look here please?

**Comment by kevinlog** [comment]
This sounds similar to a bug that @aleksmaus merged a fix for at the end of last week: https://github.com/elastic/elastic-agent/pull/3203

We should ensure that the snapshot Agent in this test includes the fix.  If not, we should ask to test again with a later Agent.

**Comment by aleksmaus** [comment]
According to the diags attached 
```
build_time: 2023-08-14T03:03:55Z
commit: af31709ed6d1d249235e2745eb3cc314d3a7f464
snapshot: true
version: 8.10.0
```
So this specific build was from the commit that was after the fix. 

The symptoms where slightly different, the unhealthy state was usually around 10 mins. Curious if there something else going on windows, maybe Endpoint unprotect is taking longer.
Trying to figure out access to Windows platform here to get this tested. I have Mac with M2, this makes things more complicated, no access to ARM windows image.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.11.0 BC9 kibana cloud environment and found it **fixed now**:

**Observations:**
- Agent with debug logs set remains healthy on removing Elastic Defend when Agent tamper protection is enabled.

**Screen Recording:**


https://github.com/elastic/elastic-agent/assets/77374876/86b14273-5152-417b-ae14-6ad755164fa9



**Build details:**
VERSION: 8.11.0 BC9
BUILD: 68160
COMMIT: f2ea0c43ec0d854259d63d926b97e5c556b5f6b2

Hence we are marking this issue as **QA:Validated**.

Thanks!
