### ISSUE TITLE
GPG key - Add a second fallback URL

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent#3264]
If https://artifacts.elastic.co/GPG-KEY-elastic-agent is unavailable or failed to be reached, Elastic Agent should have a second fallback URL that will download the key from a path hosted by Fleet Server itself.

Related PR - https://github.com/elastic/elastic-agent/pull/2980/files

**Comment by cmacknz** [comment]
The path here doesn't need to be configurable, although we could do that if it is easy. The default value should be the Fleet URL with the path as described in the Fleet server issue.

We will need to add adequate logging so we can tell this is happening, and add a new test or an extension to the GPG fallback upgrade test that already exists at https://github.com/elastic/elastic-agent/blob/65ac6d5793018b10b3489f18da21e3201f910404/testing/integration/upgrade_test.go#L220

**Comment by nimarezainia** [comment]
I concur that the path need not be configurable. Let's reduce the scope. a fixed path relative to the installation layout of the fleet-server would suffice. [the user can modify the install location of the fleet server anyway when deployed on prem]

**Comment by pchila** [comment]
Reopening as we rolled back the merge of this in main and 8.10

**Comment by michalpristas** [comment]
@pchila  can you describe repro steps?
