### ISSUE TITLE
Error initializing version information: reading package version from file....package.version: no such file or directory

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#3285]
For confirmed bugs, please report:
- Version: `8.10.0-SNAPSHOT`
- Operating System: MacOS Ventura 13.5.1
- Steps to Reproduce:

1. Install or upgrade to Elastic Agent version `8.10.0-SNAPSHOT`.
2. Run any `elastic-agent` subcommand.  Examples below.

```
$ elastic-agent version
Error initializing version information: reading package version from file "/Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version": open /Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
Binary: 8.10.0-SNAPSHOT (build: 923c98b0b336d30adaa6e4d650ffbcde450e45cd at 2023-08-23 02:46:23 +0000 UTC)
Daemon: 8.10.0-SNAPSHOT (build: 923c98b0b336d30adaa6e4d650ffbcde450e45cd at 2023-08-23 02:46:23 +0000 UTC)
```

```
$ elastic-agent status
Error initializing version information: reading package version from file "/Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version": open /Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   └─ status: (HEALTHY) Running
```

```
$ elastic-agent uninstall
Error initializing version information: reading package version from file "/Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version": open /Library/Elastic/Agent/data/elastic-agent-923c98/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
Elastic Agent will be uninstalled from your system at /Library/Elastic/Agent. Do you want to continue? [Y/n]:y
Elastic Agent has been uninstalled.
```

All the above commands succeeded. It's just annoying or misleading to print out this error, I think, especially since we do fallback to the default binary version when we can't read the package version file: https://github.com/elastic/elastic-agent/blob/5fe4fcda84ae9e915e5b734077e5db256860c808/version/helper.go#L43-L48

Looks like the error message is being emitted from here: https://github.com/elastic/elastic-agent/blob/5fe4fcda84ae9e915e5b734077e5db256860c808/internal/pkg/agent/cmd/common.go#L44-L48

**Comment by ycombinator** [comment]
@cmacknz @pierrehilbert Probably something we should fix before the `8.10.0` final BC?

**Comment by cmacknz** [comment]
Yes definitely. This is likely a problem with the build or install process.

**Comment by cmacknz** [comment]
That file should exist.

**Comment by pchila** [comment]
The error message exists so that we don't fallback silently to the beats version .
As @cmacknz said the file should exist both in the package and in the installed agent directory: it should be located side-by-side with the elastic-agent binary.
The initialization of the package version happen once for the agent service at startup, and every time the CLI is invoked: from the looks of your output it seems that the CLI is complaining about not finding the package version file anymore.
Could you check if the `.package.version` file is present in the package you used for install ? This should already giving us a hint if the issue is at packaging or install/upgrade step...

**Comment by ycombinator** [comment]
> Could you check if the .package.version file is present in the package you used for install ? This should already giving us a hint if the issue is at packaging or install/upgrade step...

When I created this issue, I was testing an upgrade from `8.9.1` to `8.10.0-SNAPSHOT`.  I saw the errors after the upgrade completed successfully. 

Just now, however, I _downloaded_ `8.10.0-SNAPSHOT` and installed it from scratch (so, NOT an upgrade from a previous version). I saw the error even at the install step:

```
$ sudo ./elastic-agent install
Error initializing version information: reading package version from file "/private/tmp/elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version": open /private/tmp/elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
Elastic Agent will be installed at /Library/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:y
Do you want to enroll this Agent into Fleet? [Y/n]:n
Elastic Agent has been successfully installed.
```

And then, of course, I saw it with subsequent sub-commands as well (as reported originally in this issue):

```
$ elastic-agent version
Error initializing version information: reading package version from file "/Library/Elastic/Agent/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version": open /Library/Elastic/Agent/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
Binary: 8.10.0-SNAPSHOT (build: 2a3dfaa4fd1bb0e0da48801b37dda570763dc1aa at 2023-07-24 12:30:44 +0000 UTC)
Daemon: 8.10.0-SNAPSHOT (build: 2a3dfaa4fd1bb0e0da48801b37dda570763dc1aa at 2023-07-24 12:30:44 +0000 UTC)
```

```
$ elastic-agent status
Error initializing version information: reading package version from file "/Library/Elastic/Agent/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version": open /Library/Elastic/Agent/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   └─ status: (HEALTHY) Running
```

```
$ elastic-agent uninstall
Error initializing version information: reading package version from file "/Library/Elastic/Agent/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version": open /Library/Elastic/Agent/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
Elastic Agent will be uninstalled from your system at /Library/Elastic/Agent. Do you want to continue? [Y/n]:y
Elastic Agent has been uninstalled.
```

> Could you check if the .package.version file is present in the package you used for install ? 

The file is not present.

```
$ pwd
/tmp/elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64
$ find . -iname .package.version | wc -l
       0
$ ./elastic-agent version --binary-only
Error initializing version information: reading package version from file "/private/tmp/elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version": open /private/tmp/elastic-agent-8.10.0-SNAPSHOT-darwin-aarch64/data/elastic-agent-2a3dfa/elastic-agent.app/Contents/MacOS/.package.version: no such file or directory
Binary: 8.10.0-SNAPSHOT (build: 2a3dfaa4fd1bb0e0da48801b37dda570763dc1aa at 2023-07-24 12:30:44 +0000 UTC)
```

**Comment by pchila** [comment]
I just tried to reproduce this by packaging from source on both main and 8.10 branches but in those tests the `.package.version` file is correctly included in the archive and the error does not show up when launching `elastic-agent version --binary-only` from the extracted archive or `elastic-agent --version` after installing agent.

After downloading 8.10.0 BC2 from https://staging.elastic.co/8.10.0-049269aa/downloads/beats/elastic-agent/elastic-agent-8.10.0-darwin-x86_64.tar.gz I can see that in that package the package version file is indeed missing so I will try and have a look at what happened during that specific build

**Comment by pchila** [comment]
Just tested again on commit 923c98b0b (8.10.0 BC2) and packaging works as expected (.package.version file is present and `elastic-agent version` works as expected.

Had a look at 8.10.0 BC1 package and it has the same problem as BC2: this makes me think that there's a problem when packaging is invoked in the unified release

**Comment by pchila** [comment]
We are going to keep this open as we can properly verify it (manually) only after a unified release snapshot build or a BC (since we need signed MacOS artifacts)
/cc @ruflin @pierrehilbert @jlind23
