### ISSUE TITLE
Collected diagnostics zip gets removed itself when logging level is set to debug for Windows agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3286]
**Kibana Build details:**
```
VERSION: 8.10.0 BC2
BUILD: 66107
COMMIT: fa3473f42d7c5e7a3c2d66026a153e01002f5d3c
```

**Host OS and Browser version:** Windows, All

**Preconditions:**
1. 8.10.0 Kibana cloud environment should be available.
2. Windows agent should be installed.

**Steps to reproduce:**
1. Set Windows agent logs to the debug level.
2. After 5-10 minutes, navigate to windows CLI and run `.\elastic-agent.exe diagnostics collect`.
3. Observe collected zip gets removed itself from `C:\Program Files\Elastic\Agent`

**Expected Result:**
Collected diagnostics zip should not get removed itself when logging level is set to debug for Windows agent.

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/71e384bc-be5a-4d62-b837-011312d74616

**Earlier reported under: https://github.com/elastic/elastic-agent/issues/2027**

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by pierrehilbert** [comment]
@cmacknz could you have a first investigation look here?

**Comment by cmacknz** [comment]
This has been reported before https://github.com/elastic/elastic-agent/issues/2027

No idea what would be causing this.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.11.0 BC9 kibana cloud environment and found it **fixed now**:

**Observations:**
- Collected diagnostics zip not gets removed itself now when logging level is set to debug for Windows agent.


**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/13dba618-1f00-4c12-a71d-f773606cece0)


**Build details:**
VERSION: 8.11.0 BC9
BUILD: 68160
COMMIT: f2ea0c43ec0d854259d63d926b97e5c556b5f6b2

Hence we are marking this issue as **QA:Validated**.

Thanks!
