### ISSUE TITLE
Add queue metrics to agent metrics dashboard

### ISSUE THREAD

**Issue by joshdover** [elastic/elastic-agent#3315]
We often have to help users debug the output and input queues inside Beats. We should enable customers to be able to view this monitoring data in our existing Agent Metrics dashboard.

Our plan was to wait until we complete the shipper project to expose this since it simplifies some parts of it, but we already have this data and this is a frequent support issue so we should solve it sooner in the existing `elastic_agent` package's dashboards.

### Input queue

We already collect this metric on the `Non-zero metrics in the last 30s` logs in `logs-elastic_agent.*` data streams the field is not mapped: `monitoring.metrics.libbeat.pipeline.events.total`.

Ideally this would be on a metrics data stream instead of Logs, but that would require more changes and not be BWC. I think it'd be fine to implement this on the existing logs data so we can release a package upgrade for previous versions.

This needs to be split by `component.id` field since the metric is per component.

### Output queue

This is already available on `metrics-elastic_agent.*` in the `beat.stats.libbeat.output.events.active`. This should also be split by component.id.

**Comment by joshdover** [comment]
For the output metrics, there is no component.id identifier. We only have beat.type which means we can only show the maximum queue across all components of the same beat type. This is still useful for tuning since you generally want to optimize for the component with the maximum queue size.

**Comment by nimarezainia** [comment]
is it possible to show this data in the agent details page also?
