### ISSUE TITLE
[Flaky test]: TestFleetManagedUpgrade - `failed to fix permissions: [...]: no such file or directory`

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#3331]
## Flaky Test

* **Test Name:** `TestFleetManagedUpgrade/Upgrade_managed_agent_from_7.17.12_to_8.11.0-SNAPSHOT` it might as well be any test installing the agent or the `TestFleetManagedUpgrade` tests in general.

* **Link:** [upgrade_test.go#L149](https://github.com/elastic/elastic-agent/blob/main/testing/integration/upgrade_test.go#L149)

* **Branch:** main, others

* **Artifact Link:** 
   - [artefactz.tar.gz](https://github.com/elastic/elastic-agent/files/12474219/artefactz.tar.gz)
   - https://buildkite.com/elastic/elastic-agent/builds/2860#018a42f4-c32d-41fc-a258-f11a578ac475

* **Notes:** 
I think the problem might be the cleanup function running while another agent install is happening

### Stack Trace

```
    upgrade_test.go:132: Enrolling Elastic Agent...
    fixture.go:365: >> running agent with: [/tmp/TestFleetManagedUpgradeUpgrade_managed_agent_from_7.17.12_to_8.11.0-SNAPSHOT2609877102/001/elastic-agent-7.17.12-linux-x86_64/elastic-agent install --force --url https://c366f9b35d7e47d6a7d4a04a7878fb8b.fleet.us-central1.gcp.qa.cld.elstc.co:443 --enrollment-token MUlZYlE0b0JZWWRaQ3A5YlE2WFE6bnNoYXhKeFlTVGV2NHRkaUVOeVFMdw==]
    upgrade_test.go:147: 2023-08-29T21:02:59.842Z	INFO	cmd/enroll_cmd.go:454	Starting enrollment to URL: https://c366f9b35d7e47d6a7d4a04a7878fb8b.fleet.us-central1.gcp.qa.cld.elstc.co:443/
        Error: failed to fix permissions: chown /opt/Elastic/Agent/elastic-agent: no such file or directory
        For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/7.17/fleet-troubleshooting.html
        Error: enroll command failed with exit code: 1
        For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/7.17/fleet-troubleshooting.html
        
    upgrade_test.go:149: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/upgrade_test.go:149
        	            				/home/ubuntu/agent/testing/integration/upgrade_test.go:99
        	Error:      	Received unexpected error:
        	            	error running agent install command: exit status 1
        	Test:       	TestFleetManagedUpgrade/Upgrade_managed_agent_from_7.17.12_to_8.11.0-SNAPSHOT
--- FAIL: TestFleetManagedUpgrade/Upgrade_managed_agent_from_7.17.12_to_8.11.0-SNAPSHOT (119.80s)
```

**Comment by blakerouse** [comment]
The tests are not flaky, the tests have discovered an actual bug in the Elastic Agent. I have filed the issue that is causing the tests failures here - https://github.com/elastic/elastic-agent/issues/3371

**Comment by AndersonQ** [comment]
> The tests are not flaky, the tests have discovered an actual bug in the Elastic Agent. I have filed the issue that is causing the tests failures here - #3371

Closing this issue then. Thank you!
