### ISSUE TITLE
Remove the `internal` folder

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#334]
**Describe the enhancement:**

Remove the `internal` package, moving `pkg` and `spec` to the repo's root.
 
A `internal` folder has got a quite specific meaning and usage in Go. Since Go 1.4 a `internal` folder will limit the scope os exported names to only the packages in the same directory as the `internal` folder and its sub-directories.

**Describe a specific use case for the enhancement or feature:**

Our current usage of the `internal` folder/package does not reflect the intended use of it in Go. It's more acting as a `src` folder, where all the code should go. The `pkg` folder already does that well, besides there are some code we want to share with other projects. As an example, we already needed [to move some code out of `internal`.
](https://github.com/elastic/elastic-agent/pull/273)

If there is code we want to ensure isn't imported by other projects, or we want to limit some API surface, we can add `internal` folders where and when needed.

**Comment by jlind23** [comment]
@ycombinator Not sure this is something we really want to address, better to close it right?

**Comment by ycombinator** [comment]
> If there is code we want to ensure isn't imported by other projects, or we want to limit some API surface, we can add `internal` folders where and when needed.

My instinct is to actually go the other way — start by restricing the API surface by default and then promoting symbols out of `internal` as needed.   So I'd be in favor of closing this issue for now.  @AndersonQ @cmacknz WDYT?

**Comment by cmacknz** [comment]
+1, I don't want to accidentally create external API contracts.
