### ISSUE TITLE
Windows uninstall can fail with `Error: failed to remove installation directory` or `Access is denied`

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3342]
**Kibana Build details:**
```
VERSION: 8.10.0 BC3
BUILD: 66261
COMMIT: 56348fa0ed0719679e24d6c58dc3dbee03928c4e
Artifact Link: https://staging.elastic.co/8.10.0-091ff659/downloads/beats/elastic-agent/elastic-agent-8.10.0-windows-x86_64.zip
```

**Host OS and Browser version:** Windows, All

**Preconditions:**
1. 8.10.0 BC3 Kibana cloud environment should be available.
2. Windows agent should be installed.

**Steps to reproduce:**
1. Navigate to CLI.
2. Under Elastic\Agent run `.\elastic-agent.exe uninstall`.
3. `Error: failed to remove installation directory` on running uninstall command.
4. Observe a log file gets retained in the installation directory.

**Expected Result:**
No errors should be observed on running agent uninstall command.

**Screen Recording:**
![32](https://github.com/elastic/elastic-agent/assets/77374876/013f9ac7-7423-42a9-b0f6-84c70f7b98aa)
![33](https://github.com/elastic/elastic-agent/assets/77374876/41822217-547c-463c-b06c-378f4f1435cf)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by amolnater-qasource** [comment]
Uninstall command issue for BC2 reported at https://github.com/elastic/fleet-server/issues/2935

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@pierrehilbert @cmacknz worth looking at this.

**Comment by pierrehilbert** [comment]
@AndersonQ you worked on two PR related to this problem in the past days. Can you see where the problem could come from?

**Comment by harshitgupta-qasource** [comment]
Hi Team

While testing on 8.9.2 BC1 build, we observed this issue reproducible there too.

**Observations:**

- Error `failed to remove installation directory` is observed on running agent uninstall command.

**Build details:**
VERSION: 8.9.2 BC1
BUILD: 64883
COMMIT: 21f3ebd6e951d102f41b0299c35e030c3c9e8eb6
Artifacts: https://staging.elastic.co/8.9.2-e4235bb7/summary-8.9.2.html

**Screenshot**
![image](https://github.com/elastic/elastic-agent/assets/101545338/495c22e6-f968-44be-8e58-3cb5c8830bb9)

Please let us know if anything else is required from our end.

Thanks!

**Comment by AndersonQ** [comment]
hey, sorry for the delay. The problem is the same, now at least we know the retry is happening and how it's happening.
The retry strategy comes from here https://github.com/golang/go/blob/master/src/testing/testing.go#L1257. However I think by now we need to rethink it. 

Even though the logs are cut, the problem seems to be with the log file. I wonder if it's the agent or filebeat which is accessing the logfile.

@harshitgupta-qasource do you have those logs? Preferably in text form and in full. This screenshot cut out a rather important part of the error.

**Comment by amolnater-qasource** [comment]
Hi @AndersonQ 

Thank you for looking into this.
Please find the details here:
![image](https://github.com/elastic/elastic-agent/assets/77374876/f99a96f6-c682-426c-bae6-2f199b673311)
After uninstall is complete below log file retains 
![image](https://github.com/elastic/elastic-agent/assets/77374876/dbc622fc-4bc3-463b-880e-1ce2e60873b4)

**Pending Log file in the installed directory:**
[elastic-agent-20230904-5.ndjson.zip](https://github.com/elastic/elastic-agent/files/12512916/elastic-agent-20230904-5.ndjson.zip)

Please let us know if anything else is required from our end.
Thanks!

**Comment by AndersonQ** [comment]
@amolnater-qasource another question. Can you easily reproduce this error? If yes, could you explain how?

**Comment by amolnater-qasource** [comment]
@AndersonQ yes, it's reproducible every time.
- We install the agent on Windows 2022 server.
- On running uninstall command from the installed directory, this error appears in CLI.

Thanks!

**Comment by fearful-symmetry** [comment]
Not sure what the process is for declaring a release blocker? I assume @cmacknz would know.

**Comment by cmacknz** [comment]
We have already fixed this in the latest BC, we just forgot to update the issue here.

@elastic/fleet-qasource-external please re-test this.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.10.0 BC6 kibana cloud environment and had below observations:

**Observations:**
- No errors are observed on running agent uninstall command from the parent directory.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/1e30c85a-8b13-480b-b9e5-40e96b91ed52)

**Build details:**
VERSION: 8.10.0 BC6
BUILD: 66340
COMMIT: 1b2de6dcb1eb017347a61372e209ec5211242ed5

Hence we are marking this issue as **QA:Validated**.

Thanks!

**Comment by harshitgupta-qasource** [comment]
Hi @AndersonQ @cmacknz

While testing the 8.10.3 BC1 build, we have found this issue **reproducible** there.

**Observations:**
- We observed the error: `failed to remove installation directory` on running agent uninstall command and also a log file gets retained in the installation directory.
- We have run the agent installation command outside the directory.

**Build details:**
VERSION: 8.10.3 BC1
BUILD: 66480
COMMIT: 5aee3c4fba328838fcf0be6a3ff2248a4c0120dd
Artifacts: https://staging.elastic.co/8.10.3-a569781f/summary-8.10.3.html

**Screen-shot**
![image](https://github.com/elastic/elastic-agent/assets/101545338/037b14e0-8079-4283-bcda-e154a0fa9d93)
![image](https://github.com/elastic/elastic-agent/assets/101545338/2db4ceb2-86e2-4530-98d8-0711002f4bea)


Hence, we are re-opening this issue.
Please let us know if anything else is required from our end.

Thanks!

**Comment by AndersonQ** [comment]
I'm looking at it

**Comment by cmacknz** [comment]
This is actually an expected error, see discussion in https://github.com/elastic/elastic-agent/issues/3479#issuecomment-1743758271

You can't remove a directory on Windows that you are executing from. The difference here is that a single log file gets left behind, probably because we were writing to it at the time the uninstall was attempted. We just detect this error now, the parent directory was never actually removed in previous versions.

If you execute `elastic-agent uninstall` outside of the `C:\Program Files\Elastic\Agent` directory it should work as expected.

**Comment by cmacknz** [comment]
I think what we should do here is detect when `elastic-agent uninstall` is being executed from the installation directory (usually `C:\Program Files\Elastic\Agent` but not necessarily with the new custom base path feature) and exit with an error indicating this isn't supported on Windows.

Even if we removed the log file we couldn't remove the `C:\Program Files\Elastic\Agent` directory without executing the binary from a different directory.

**Comment by leehinman** [comment]
> I think what we should do here is detect when `elastic-agent uninstall` is being executed from the installation directory (usually `C:\Program Files\Elastic\Agent` but not necessarily with the new custom base path feature) and exit with an error indicating this isn't supported on Windows.
> 
> Even if we removed the log file we couldn't remove the `C:\Program Files\Elastic\Agent` directory without executing the binary from a different directory.

Maybe we should switch to [MoveFileExA](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexa?redirectedfrom=MSDN) with `MOVEFILE_DELAY_UNTIL_REBOOT` flag on Windows.   That way the file is deleted on next reboot.  It's ugly, but it is the "Windows way" of dealing with the problem (windows installers do this).

**Comment by cmacknz** [comment]
> If dwFlags specifies MOVEFILE_DELAY_UNTIL_REBOOT and lpNewFileName is NULL, MoveFileEx registers the lpExistingFileName file to be deleted when the system restarts. If lpExistingFileName refers to a directory, the system removes the directory at restart only if the directory is empty.

Nice! Hopefully that works for removing files that are inside directories that are also marked for deletion so it can handle the case where there is a log file left behind in a directory we are trying to remove.

That is a better solution, my suggestion wasn't really a solution just making the problem obvious to users.

**Comment by harshitgupta-qasource** [comment]
Hi Team

While testing on 8.11.0 BC3 build, we observed this issue reproducible there too. **We have run the agent uninstallation command outside the directory.**

**Observations:**

- We observed the `error: failed to remove installation directory` on running agent uninstall command and also a log file gets retained in the installation directory.

**Build details:**
VERSION: 8.11.0
BUILD: 67923
COMMIT: 714189fa2b0f0a4d9f3865a8fce08261211570c8
Artifacts: https://staging.elastic.co/8.11.0-873a5855/summary-8.11.0.html

**Screenshot**
- Windows 11
![image (8)](https://github.com/elastic/elastic-agent/assets/101545338/18dac616-b9e6-4604-9235-e8da829c03be)

- Windows 8.1
![image (10)](https://github.com/elastic/elastic-agent/assets/101545338/3b9c14e8-3b74-43f7-86e9-bf857f50c6e3)


**Impacted OS's**
- Windows 11
- Windows 10
- Windows 8.1
- Windows Server 2022
- Windows Server 2019
- Windows Server 2016
- Windows Server 2012-r2

**Note:** This issue is reproducible only on GCP machines only and not observed on Windows OS setup from AWS.

Please let us know if anything else is required from our end.

Thanks!

**Comment by cmacknz** [comment]
Our integration tests are now hitting a slightly different version of this problem: https://buildkite.com/elastic/elastic-agent/builds/4689#018baa4d-67aa-49c6-b48c-9c4a782499a3

```
Error: error uninstalling agent: failed to remove installation directory (C:\\Program Files\\Elastic\\Agent): timed out while removing \"C:\\\\Program Files\\\\Elastic\\\\Agent\". Last error: remove C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-7c6b87\\elastic-agent.exe: Access is denied.\nFor help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.12/fleet-troubleshooting.html\n
```

Full log of where the uninstall happened:

```
fixture_install.go:119: [test TestMonitoringLogsShipped] Inside fixture cleanup function
    fixture.go:505: >> running binary with: [C:\Program Files\Elastic\Agent\elastic-agent.exe uninstall --force]
    fixture_install.go:169: 
        	Error Trace:	C:/Users/windows/agent/pkg/testing/fixture_install.go:169
        	            				C:/Program Files/Go/src/testing/testing.go:1150
        	            				C:/Program Files/Go/src/testing/testing.go:1328
        	            				C:/Program Files/Go/src/testing/testing.go:1570
        	Error:      	Received unexpected error:
        	            	error running uninstall command: exit status 1
        	Test:       	TestMonitoringLogsShipped
        	Messages:   	uninstalling agent failed. Output: "\r[    ] Stopping service  [0s] \r                              \r\r[  ==] Successfully stopped service  [0s] \r                                          \r\r[ ===] Stopping upgrade watcher; none found  [0s] \r                                                  \r\r[=   ] Removing service  [0s] \r                                                  \r\r[=   ] Successfully uninstalled service  [0s] \r                                                  \r\r[=   ] Removing install directory  [0s] \r                                                  \r\r[ ===] Failed to remove install directory  [9s] \r                                                  \r\r[ ===] Failed to uninstall agent  [9s] Error: error uninstalling agent: failed to remove installation directory (C:\\Program Files\\Elastic\\Agent): timed out while removing \"C:\\\\Program Files\\\\Elastic\\\\Agent\". Last error: remove C:\\Program Files\\Elastic\\Agent\\data\\elastic-agent-7c6b87\\elastic-agent.exe: Access is denied.\nFor help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.12/fleet-troubleshooting.html\n"
--- FAIL: TestMonitoringLogsShipped (154.72s)
```

**Comment by lucabelluccini** [comment]
Hello @pierrehilbert, is this also under the radar?

**Comment by pierrehilbert** [comment]
@lucabelluccini yes it is but not planned yet

**Comment by amolnater-qasource** [comment]
Hi Team,

While testing on 8.12.0 BC1 kibana cloud environment, we have found **this issue reproducible** there.

**Observations:**
- Windows uninstall failed with `Error: failed to remove installation directory` or `Access is denied`.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/3bb1189d-835c-4d7b-9772-99f51fa9a478)

**Build details:**
8.12.0 BC1
BUILD: 69840
COMMIT: 93cff0aacd70bd0835cd244348f742ba3cafc4aa
Artifact Link: https://staging.elastic.co/8.12.0-6eaefdbf/downloads/beats/elastic-agent/elastic-agent-8.12.0-windows-x86_64.zip

Please let us know if anything else is required from our end.
Thanks!

**Comment by strawgate** [comment]
I do think there are two issues here, one is uninstalling from the directory but there is also this: https://github.com/elastic/elastic-agent/issues/3342#issuecomment-1778884507

Which occurs outside of the directory and I am able to reproduce on GCP. This is also blocking  https://github.com/elastic/elastic-stack-installers/pull/220

**Comment by leehinman** [comment]
> And seems to imply the `elastic-agent uninstall` command is writing a log file at the root of the agent folder (CreateFile/WriteFile), keeping the log file open, and then trying to delete the log file (SharingViolation), which is stopping it from being uninstalled. Once the uninstall fails it closes the log file (CloseFile) and exits.

This might be a good reason to look at logging to the EventLog on Windows instead of to a File.

**Comment by cmacknz** [comment]
We should be logging the output of the uninstall command to the console and not a file. We can log to the event log, but then we'll need to instruct everyone on how to get the events back out of it for troubleshooting.

**Comment by leehinman** [comment]
> We should be logging the output of the uninstall command to the console and not a file. We can log to the event log, but then we'll need to instruct everyone on how to get the events back out of it for troubleshooting.

I like logging to stdout/stderr, but I really think we should do EventLog too.  The default buffer size on cmd.exe is 50 lines, so I really don't want to get in the situation where the debug line we need has rolled off and we don't have "permanent" storage somewhere, even if it is a pain to get at.  (although `elastic-agent diagnostics` should be able to pull from EventLog)

**Comment by cmacknz** [comment]
My proposal would be:

1. Change this logger to write to console instead of a file. Also we need to document that uninstall can't log to file at all in the code for this reason.
2. Create a follow up issue to start writing to the event log and have a command for dumping the contents to a file to make reading it easy.

**Comment by leehinman** [comment]
> My proposal would be:
> 
>     1. Change this logger to write to console instead of a file. Also we need to document that uninstall can't log to file at all in the code for this reason.

we [currently](https://github.com/elastic/elastic-agent/blob/17f048008fcea105d0b86cc90743c7bfb8ce2a41/internal/pkg/agent/cmd/uninstall.go#L82) have the progress bar for uninstall on stdout.  If we log to stderr this is going to get messy.

couple of other options

1. file in system temp dir, and print where that file is during uninstall, successful uninstall could delete it.
2. Use the [Observer Output](https://github.com/elastic/elastic-agent-libs/blob/be95ccab81f44833cf150962da3003394c13c6ea/logp/options.go#L38-L40) during uninstall, and only print the logs to stderr when there is an error. (we do this with some integration tests)

**Comment by cmacknz** [comment]
Initial preference is option 2 because it puts the error where we want to see it. I don't have anything against option 2 though.

**Comment by leehinman** [comment]
So implemented the Observer Output, and it doesn't quite fix the problem, we can't delete the "Agent" directory because we are in the Agent directory.  You get the same error on Windows if you try `rmdir .`

```
c:\Program Files\Elastic\Agent>elastic-agent.exe uninstall
Elastic Agent will be uninstalled from your system at C:\Program Files\Elastic\Agent. Do you want to continue? [Y/n]:y
[    ] Failed to uninstall agent  [5s] Error: error uninstalling agent: failed to remove installation directory (C:\Program Files\Elastic\Agent): timed out while removing "C:\\Program Files\\Elastic\\Agent". Last error: remove C:\Program Files\Elastic\Agent: The process cannot access the file because it is being used by another process.
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.13/fleet-troubleshooting.html

c:\Program Files\Elastic\Agent>dir
 Volume in drive C has no label.
 Volume Serial Number is 88EE-D48A

 Directory of c:\Program Files\Elastic\Agent

01/17/2024  11:34 PM    <DIR>          .
01/17/2024  11:34 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  108,212,609,024 bytes free

c:\Program Files\Elastic\Agent>
```

**Comment by strawgate** [comment]
> So implemented the Observer Output, and it doesn't quite fix the problem, we can't delete the "Agent" directory because we are in the Agent directory. You get the same error on Windows if you try `rmdir .`
> 
> ```
> c:\Program Files\Elastic\Agent>elastic-agent.exe uninstall
> Elastic Agent will be uninstalled from your system at C:\Program Files\Elastic\Agent. Do you want to continue? [Y/n]:y
> [    ] Failed to uninstall agent  [5s] Error: error uninstalling agent: failed to remove installation directory (C:\Program Files\Elastic\Agent): timed out while removing "C:\\Program Files\\Elastic\\Agent". Last error: remove C:\Program Files\Elastic\Agent: The process cannot access the file because it is being used by another process.
> For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.13/fleet-troubleshooting.html
> 
> c:\Program Files\Elastic\Agent>dir
>  Volume in drive C has no label.
>  Volume Serial Number is 88EE-D48A
> 
>  Directory of c:\Program Files\Elastic\Agent
> 
> 01/17/2024  11:34 PM    <DIR>          .
> 01/17/2024  11:34 PM    <DIR>          ..
>                0 File(s)              0 bytes
>                2 Dir(s)  108,212,609,024 bytes free
> 
> c:\Program Files\Elastic\Agent>
> ```

Yeah, that will always be a (different) problem as the command prompt holds a lock on the directory preventing it from being deleted.

The solutions for this that I'm aware of are:
1. Document that you should not invoke the agent uninstall command with the working directory set to any directory within Elastic\Agent
2. Delete that directory on next startup via your recommendation here: https://github.com/elastic/elastic-agent/issues/3342#issuecomment-1750778013
3. Warn the user when we detect that the uninstall command is running from the agent directory and that we won't be able to delete the root directory.
4. Warn the user when we detect an active lock on files in the Agent directory

**Comment by amitkanfer** [comment]
@leehinman - does it mean that with the current implementation, if a user calls `uninstall` from a different folder - there's no issue? This unblocks the MSI installer issue we thought we had (as we have full control of where we call the command)

**Comment by leehinman** [comment]
> @leehinman - does it mean that with the current implementation, if a user calls `uninstall` from a different folder - there's no issue? This unblocks the MSI installer issue we thought we had (as we have full control of where we call the command)

I'm taking "current implementation" to mean without the Observer Output that leaves a log file behind in the agent dir.  In that case I __think__ there is a race condition where you could run into the use by another process on the log file it is generating.  With the Observer Output, we shouldn't have that race condition.

I'm going to try number 3 that @strawgate mentioned.  I should be able to detect the current working dir during uninstall, and if that is within the agent install path immediately error out before any actual uninstall activity.  That way the user would know immediately that it wouldn't work, and they don't end up with something half uninstalled.  Unless there are objections?

**Comment by amitkanfer** [comment]
> Unless there are objections?

SGTM

**Comment by jlind23** [comment]
> Unless there are objections?

Looks like the right way to move forward here.

**Comment by strawgate** [comment]
I think I have a preference for this:

> Delete that directory on next startup via your recommendation here: https://github.com/elastic/elastic-agent/issues/3342#issuecomment-1750778013

i.e. have Windows schedule the deletion of the `Elastic/Agent` directory itself on next startup 

But am okay with the proposed path forward

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.13.0-SNAPSHOT kibana cloud environment and found it **fixed now**:

**Observations:**
- No errors are observed on running agent uninstall command.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/98b8bebb-9c6e-4da6-a2a3-70db6b62fe0d)


**Build details:**
VERSION: 8.13.0
BUILD: 71179
COMMIT: b4d93fc145c3c09eb1096c610b7cd736f19f6a3a
Artifact Link: https://snapshots.elastic.co/8.13.0-por0bbe1/downloads/beats/elastic-agent/elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip

Hence we are marking this issue as **QA:Validated**.

Thanks!
