### ISSUE TITLE
[Agent-Logs]: Agent gets Unhealthy temporarily and later no new logs under Fleet>agent Logs tab on adding endpoint security.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#335]
**Kibana version:**  8.2 BC-3 Kibana cloud environment

**Host OS:** Windows, Linux and MAC

**Build details:**
VERSION: 8.2.0 BC-3
BUILD: 51885
COMMIT: 2ea6dc82752506d6f7aa34bda747f99c6fbfd152
Artifact link: https://staging.elastic.co/8.2.0-0295c2db/summary-8.2.0.html

**Preconditions:**
1. 8.2 BC-3 Kibana cloud environment should be available.
2. Install few agents with policy having only System integration.

**Integrations:**
System and Endpoint Security.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Fleet>Agent Policy tab.
3. Add Endpoint Security to Agent policy.
4. Observe Agent goes to unhealthy state for 3-5 minutes.
5. Then agent gets back Healthy, however no new logs gets generated under Agent>Logs tab.

**Expected Result:**
Agent should not go unhealthy and new logs should be generated under Fleet>agent Logs tab on adding endpoint security.

**Logs Windows agent:**
[logs.zip](https://github.com/elastic/elastic-agent/files/8489054/logs.zip)

**Endpoint Logs from Windows Agent:**
[endpoint-000000.zip](https://github.com/elastic/elastic-agent/files/8489072/endpoint-000000.zip)

**Logs for MAC agent observations from approximately 5 hours:**
[elastic-agent-diagnostics-2022-04-14T12-17-50Z-00.zip](https://github.com/elastic/elastic-agent/files/8489036/elastic-agent-diagnostics-2022-04-14T12-17-50Z-00.zip)

**Screenshots:**
![19](https://user-images.githubusercontent.com/77374876/163388428-06bd37bf-5e50-46c5-bec1-a0bac2e89ebd.JPG)
![20](https://user-images.githubusercontent.com/77374876/163388438-e8a3f140-645c-4832-a9a1-fc0dc2ef999c.JPG)
![21](https://user-images.githubusercontent.com/77374876/163388445-9348712f-d08b-4210-b20a-be23f0d044be.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We are facing this issue on Centos 8 if we add the ES integration after installing he agent. Also, the policy goes to failure state with the error message 'failed to enable protection in policy configuration' for Malware.

**Screenshot**
![image](https://user-images.githubusercontent.com/101545338/163776863-20a2d13f-cb0d-4384-a77b-7dc33f2d1a60.png)

Please let me know if any other information is required from our end.
Thank You!

**Comment by AndersonQ** [comment]
it seems a duplicate of #281

**Comment by AndersonQ** [comment]
Let's wait https://github.com/elastic/beats/pull/31346 to get merged and published and test again. If the problem persists, we'll investigate further.

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.2 BC-4 Kibana cloud environment and found it fixed now.
- Agent doesn't go unhealthy and new logs are generated under Fleet>agent Logs tab on adding endpoint security.

**Platforms Validated:**
- Windows
- Ubuntu
- Centos
- MAC

**Build details:**
BUILD: 52005
COMMIT: 9a5003d8cf0062bf24ef64d6712b44823888cc03
Artifact Link: https://staging.elastic.co/8.2.0-3b2b9b86/summary-8.2.0.html

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/164386634-5791ab83-5a74-4c9f-8076-7da22c16a9c7.JPG)

Hence we are **closing** this issue and marking this as **QA:Validated**.
Thanks

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  Testcase already exists for this scenario under Fleet test suite at link:
   -  [C150209](https://elastic.testrail.io/index.php?/cases/view/150209)

Thanks
