### ISSUE TITLE
Agent cannot be uninstalled from its own directory on Windows

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#3353]
If the `uninstall` command is invoked from the Agent's directory it "fails to uninstall" with 
>`failed to remove installation directory (C:\Program Files\Elastic\Agent): could not remove path, timeout exeeded after 69 tries during 7s. Last error: remove C:\Program Files\Elastic\Agent: The process cannot access the file because it is being used by another process.`

The "fails to uninstall" actually means everything works, but the removal of `C:\Program Files\Elastic\Agent`

It started in 8.10-BC3 which has https://github.com/elastic/elastic-agent/pull/3317 and https://github.com/elastic/elastic-agent/pull/3249 which were backported to fix https://github.com/elastic/elastic-agent/issues/3221.

For confirmed bugs, please report:
- Version: 8.10-BC3, 8.11/main
- Operating System: Windows
- Discuss Forum URL: N/A
- Steps to Reproduce:

Install a fleet-managed agent, then:
```
cd C://Program Files/Elastic/Agent/
./elastic-agent.exe uninstall
```

[BC3](https://staging.elastic.co/8.10.0-091ff659/summary-8.10.0.html):
![image](https://github.com/elastic/elastic-agent/assets/203669/98829281-1d66-4a2b-8ff1-839b060de186)

[BC2](https://staging.elastic.co/8.10.0-049269aa/summary-8.10.0.html):
![image](https://github.com/elastic/elastic-agent/assets/203669/10355500-f40c-4760-9302-910464cc49e5)

**Comment by cmacknz** [comment]
This was fixed in the latest 8.10 build, closing.
