### ISSUE TITLE
When the GPG URL is unreachable, the upgrade should continue if the embedded GPG key still works

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#3368]
We have a report in https://github.com/elastic/fleet-server/issues/2887#issuecomment-1710016052 that the upgrade process fails in air gapped environments if the fallback GPG key URL is unreachable.

If the embedded GPG key for verification still works, then this is not a fatal error and the upgrade process should still succeed. 

Acceptance Criteria:

* A test exists proving that a GPG verification method that fails does not affect the upgrade process if an alternative verification method suceeds.

**Comment by jlind23** [comment]
@pierrehilbert - I just assigned this to @michalpristas as he is the one who worked on this code base.

**Comment by pierrehilbert** [comment]
Perfect, I would have done the same :-)

**Comment by cmacknz** [comment]
I wrote https://github.com/elastic/elastic-agent/issues/3403 describing how to implement an integration test for this case. While this specific fix can likely be verified purely with unit testing, we should consider the integration test part of the scope of this issue since it is necessary to prevent this problem from happening again.
