### ISSUE TITLE
[Inconsistent]: No logs under Agents>Logs tab for long time after installation.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#337]
**Kibana version:**  8.2 BC-1 Kibana cloud environment

**Host OS and Browser version:** 
Ubuntu
Inconsistently on: Windows

**Build details:**
```
VERSION: 8.2.0
BUILD: 51685
COMMIT: d18a093a2cf03991b93ea3de6a1054d580d3e82f
Artifact Link: https://staging.elastic.co/8.2.0-8ea0c40f/summary-8.2.0.html
```

**Preconditions:**
1. 8.2 BC-1 Kibana cloud environment should be available.
2. Windows and Ubuntu agents must be installed.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Fleet>Agents>Agent logs tab.
3. Observe no logs available for (approximately)30 mins for the installed agents.
_(Sometimes logs appears after approximately 30 mins.)_

**Expected Result:**
Logs should be available under Agents>Logs tab after agent installation.

**Logs:**
[elastic-agent-diagnostics-2022-04-04T10-27-52Z-00.zip](https://github.com/elastic/kibana/files/8409000/elastic-agent-diagnostics-2022-04-04T10-27-52Z-00.zip)

**Screenshot:**
![image (3)](https://user-images.githubusercontent.com/77374876/161530173-bd67cdba-15d0-4b03-9f6a-01266e41e8c7.png)

**Comment by jen-huang** [comment]
@jlind23/@ph This still seems to be flaky on the latest BC. Endpoint-related?

**Comment by ph** [comment]
@jen-huang  I would think it's linked to https://github.com/elastic/beats/pull/31346 @belimawr

**Comment by jen-huang** [comment]
@vipulsrivastava-qasource Looks like a possible fix was just merged, could you re-test on the next snapshot or BC (BC4)?

**Comment by amolnater-qasource** [comment]
Hi @jen-huang 
We have revalidated this issue on latest 8.2 BC-4 Kibana cloud environment and found it fixed now.
- Logs are available under Agent>Logs tab for installed agents.

**Platforms Validated:**
- Windows
- Ubuntu
- Centos
- MAC

**Build details:**
BUILD: 52005
COMMIT: 9a5003d8cf0062bf24ef64d6712b44823888cc03
Artifact Link: https://staging.elastic.co/8.2.0-3b2b9b86/summary-8.2.0.html

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/164377879-49025c5b-2389-47c7-9ee6-579837febf1b.JPG)

Hence we are **closing** this issue and marking this as **QA:Validated**.
Thanks

**Comment by jen-huang** [comment]
Thanks @amolnater-qasource for validating, this is a relief!

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  Testcase already exists for this scenario under Fleet test suite at link:
   - [C15282](https://elastic.testrail.io/index.php?/cases/view/15282)

Thanks!
