### ISSUE TITLE
occasional uninstall hang on Windows 8.8.1

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent#3372]
Windows elastic-agent version 8.8.1

occasionally running `elastic-agent uninstall` will hang indefinitely or report error "service did not respond in a timely fashion".  Running `elastic-agent restart` will break the hang and allow the uninstall to complete.  Also stopping the service prior to running uninstall will allow the uninstall to complete without hanging.

likely related to https://github.com/elastic/elastic-agent/issues/3061

**Comment by cmacknz** [comment]
I bet we aren't handling stop events properly looking at some of the related issues, particularly https://github.com/elastic/elastic-agent/issues/3307

**Comment by cmacknz** [comment]
The root cause has been identified and fixed: https://github.com/elastic/elastic-agent-libs/pull/155
