### ISSUE TITLE
[Fleet]: No data and logs available for installed agent under Fleet tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3407]
**Kibana Build details:**
```
VERSION: 8.11.0 SNAPSHOT
BUILD: 66942
COMMIT: 6526280785d585e495a827dee46c08c160461a83
```

**Host OS and Browser version:** All, All

**Preconditions:**
1. 8.11.0 SNAPSHOT Kibana cloud environment should be available.
2. Agent should be installed using Agent policy having System integration.

**Steps to reproduce:**
1. Navigate to Fleet>Agents>Logs tab.
3. Observe no logs available.
4. Navigate to data streams tab and observe no data for System integration.

**Expected Result:**
Data and logs should be available for installed agent under Fleet tab.

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/63d6598f-3168-48cb-87bf-116a6ca16815

**Logs:**
[elastic-agent-diagnostics-2023-09-13T08-59-45Z-00.zip](https://github.com/elastic/elastic-agent/files/12595598/elastic-agent-diagnostics-2023-09-13T08-59-45Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
Is this reproducible? I don't see anything in the logs that would explain this, and I see the monitoring Filebeat start, process the log level change, and then have diagnostics collected within a 2 minute span. I wonder if the logs would have shown up eventually if you just waited longer.

**Comment by cmacknz** [comment]
You will need a snapshot with https://github.com/elastic/beats/pull/36610 included for this to work, I believe this is currently broken for unrelated reasons on main that did not impact the original report here.

**Comment by amolnater-qasource** [comment]
Hi @cmacknz 

Thank you for the update. 
The latest 8.11.0 Snapshot available is created before the shared PR was merged and the issue is still reproducible there.

>  I wonder if the logs would have shown up eventually if you just waited longer.

We continued testing the same environment for multiple days, the logs were not available even after 2-3 days of agent installation.

**Observations:**
- No data and logs available for installed agent under Fleet tab.

**Build details:**
VERSION: 8.11.0 SNAPSHOT
BUILD: 67091
COMMIT: e00aa75631961fa7bbe061291472d3a63ab19502

**Screenshots:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/5fe17dc5-776b-4250-8814-6e9d3ea135a5)
![image](https://github.com/elastic/elastic-agent/assets/77374876/12115010-abd3-40d0-a9d4-39981e93f4d6)

We will revalidate this issue once a new SNAPSHOT will be available with the merges of shared PR.

Please let us know if anything else is required from our end.
Thanks!

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.11.0 SNAPSHOT kibana cloud environment and found it **fixed now**:

**Observations:**
- Data and logs are now available for installed agent under Fleet tab.


**Screen Recording:**


https://github.com/elastic/elastic-agent/assets/77374876/7b22f838-8f4e-415b-9233-3e17add5ca43


**Build details:**
VERSION: 8.11.0 SNAPSHOT
BUILD: 67293
COMMIT: a940b28461fb604c47bab31336ec3664bbfe10ea

Hence we are closing and marking this issue as **QA:Validated**.

Thanks!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/15282
 
Thanks!
