### ISSUE TITLE
Misguiding information- `Uninstalling current Elastic Agent` is shown under CLI while installing elastic-agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3414]
**Kibana Build details:**
```
VERSION: 8.11.0 SNAPSHOT
BUILD: 66942
COMMIT: 6526280785d585e495a827dee46c08c160461a83
```

**Host OS and Browser version:** All, All

**Preconditions:**
1. 8.11.0 SNAPSHOT Kibana cloud environment should be available.
2. No agent should be installed.

**Steps to reproduce:**
1. Navigate to CLI.
2. Run agent install command and observe CLI shows: `Uninstalling current Elastic Agent`, even when no agent is installed
3. Now observe agent is installed.
4. Rerun the same command and observe command still fails to execute as the agent is already installed.

**Expected Result:**
Misguiding information- `Uninstalling current Elastic Agent` should not be shown under CLI while installing elastic-agent.
- It doesn't uninstall existing installed agent.
- If no agent is already installed, there is nothing to uninstall.

**Screenshots:**
![4](https://github.com/elastic/elastic-agent/assets/77374876/feb7664a-94b9-4ab1-9229-7c628897bfd9)
![5](https://github.com/elastic/elastic-agent/assets/77374876/17f7828d-9695-4f6c-8c6a-4ba7e3d46edb)
![6](https://github.com/elastic/elastic-agent/assets/77374876/6a18bf3c-1fd3-4b89-a3ae-535b974d3ae4)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by pierrehilbert** [comment]
@ycombinator could you please have a look to get this fixed?

**Comment by ycombinator** [comment]
There are two separate (but related) issues with installing Elastic Agent being discussed here:

> It doesn't uninstall existing installed agent.

This behavior is working as expected.  Elastic Agent will only uninstall the existing installed Agent if `--force/-f` is provided. This is documented (but not too clearly IMHO) in the output of `elastic-agent install --help`:

>`   -f, --force           Force overwrite the current and do not prompt for confirmation`

I will improve this help text so it mentions the current "installation".

> If no agent is already installed, there is nothing to uninstall.

This is a legitimate issue.  We need a check around the uninstall step during installation to only perform that step if Agent is currently installed AND `--force` was supplied.  I will add this.

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

Thank you for the fixes.
We have revalidated this issue on latest 8.11.0 SNAPSHOT kibana cloud environment and found it **fixed now**:

**Observations:**
- If no agent is installed `Uninstalling current Elastic Agent` is not visible on running elastic-agent install command under CLI.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/d83b824f-8f25-41fa-87ed-5917c16b21b6)

**Build details:**
VERSION: 8.11.0 SNAPSHOT
BUILD: 67332
COMMIT: c20d177a036be73d7b1180dc17e644afa260994f

Hence we are marking this issue as **QA:Validated**.

Thanks!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/150206

Thanks
