### ISSUE TITLE
Mage: Create cleanup target for integration tests resources

### ISSUE THREAD

**Issue by pazone** [elastic/elastic-agent#3456]
### Prerequisites
Currently integration tests leave stale deployments and cloud resources when a CI command is interrupted or forcibly restarted.

### The solution
We need a cleanup target to be executed in `pre-exit` buildkite hook. We already have `.integration-cache/state.yml` produced by integration target containing all created resources during the tests execution.
The state file should be consumed my the `mage integration:cleanup` target to delete the stack and could resources.
In this case the cleanup will be always executed by buildkite and no stale resources will be left behind

**Comment by cmacknz** [comment]
https://github.com/elastic/elastic-agent/blob/main/docs/test-framework-dev-guide.md#failures-on-reused-resources

> The integration framework tries to re-use resource when it can. This improves the speed at which the tests can run, but also means its possible for a failed test to leave state behind that can break future runs.

> Run mage integration:clean before running mage integration:test to ensure the tests are being run with fresh instances and stack.

We already have the `mage integration:clean` target and Buildkite doesn't call it so we can reuse previously provisioned resources.

I think what we'd want to move out of the QA region where automated cleanup is our own automated cleanup process to delete resources that are older than a certain age or are going unused without disrupting currently running tests. I see we added something like this in https://github.com/elastic/elastic-agent/pull/3238 which may or may not be enough.

**Comment by cmacknz** [comment]
Actually we are explicitly cleaning resources after each CI run, reusing resources is only the default for local tests.

https://github.com/elastic/elastic-agent/blob/735a8fbc52c94b78f9b893b761e4a373df46c2e3/.buildkite/scripts/steps/integration_tests.sh#L11

That `TEST_INTEG_CLEAN_ON_EXIT=true` adds `mage integration:clean` as a dependency of `mage integration:test` automatically so it should always execute as long as `mage` doesn't crash.

**Comment by blakerouse** [comment]
I think the issue Pavel is highlighting is that if the job is interrupted and the mage command is killed then the resources will be left behind.

I think pre-exit allows us to always clean the resources no matter what.

**Comment by cmacknz** [comment]
Yes I apparently only remembered the title when I wrote those comments, the description also points this out. 🤦‍♂️

**Comment by pchila** [comment]
It seems we don't keep track of created deployments as well as we should https://github.com/elastic/elastic-agent/issues/3463
