### ISSUE TITLE
Integration test framework should save created deployments in state even if provisioning fails

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#3463]
While working on creating a pre-exit hook for cleaning up integration tests resources I came across a [build](https://buildkite.com/elastic/elastic-agent/builds/3457#018abbb6-9cf8-4fef-9fa5-09ac878339b3) where the deployment did not get ready in time.
The deployment was leaked anyways (deployment is still visible in qa admin console)  and clean did not reap it because [the framework doesn't write the deployments in the state in case provisioning fails](https://github.com/elastic/elastic-agent/blob/0ad7b4e00637838821b05bc661c8792eeab8bbb5/pkg/testing/runner/runner.go#L617-L634) (the ess provisioner [does not even return them](https://github.com/elastic/elastic-agent/blob/0ad7b4e00637838821b05bc661c8792eeab8bbb5/pkg/testing/ess/provisioner.go#L65-L117))

If we rely on `mage integration:clean` to clean up resources the state.yml must keep track of all the created deployments, regardless of the usability of those or if the deplyments became healthy in time

**Comment by cmacknz** [comment]
Let's switch to the production CFT region along with this change https://github.com/elastic/elastic-agent/issues/3459
