### ISSUE TITLE
Move agent upgrade tests to official snapshots to a scheduled job

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#3475]
Currently the elastic agent upgrade tests use a mixture of locally built and official snapshot as target versions for upgrade tests.
Such upgrade tests are run for PR and commits on branches.

The purpose of this PR is to move the tests that use official snapshot in a separate, scheduled job instead of running for each commit.

**Comment by blakerouse** [comment]
Actually with my PR #3477 I don't believe we need to do this. I original thought that it made sense to move these, but the more I thought about it as long as the does does one or the other then its a valid test and should remain.

- Start version is the build version, upgrading to another version
- Start version is another version, upgrading to build version

**Comment by pierrehilbert** [comment]
@pchila any objection on @blakerouse point of view or could we close this one?

**Comment by pchila** [comment]
The idea behind this issue was run the upgrade where we upgrade from a released version to a SNAPSHOT version that has been built by a nightly job (mostly to cover Fleet managed upgrades).
If those usecases are covered by #3477 as @blakerouse says I have no problem closing this issue

**Comment by pierrehilbert** [comment]
Closing for now and will reopen if necessary
