### ISSUE TITLE
Agents Not Disappearing in Fleet

### ISSUE THREAD

**Issue by AliciaKell** [elastic/elastic-agent#3487]
Please post all questions and issues concerning the Elastic Agent on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 8.8.1
- Operating System: Linux
- Steps to Reproduce: Deploy the agent within a containerized environment ->  As daemonset goes up and down, new agents appear within the fleet management console -> the old agent goes offline and never disappears.  
<img width="1271" alt="MicrosoftTeams-image" src="https://github.com/elastic/elastic-agent/assets/107881084/2605916b-6e30-4fd3-aaa5-39ada6138f98">

**Comment by cmacknz** [comment]
To avoid this you can store the agent state on the node in a hostPathVolume. We updated our default Kubernetes manifests to do this by default in https://github.com/elastic/elastic-agent/pull/2550. You can take the relevant changes there and apply them to your DaemonSet to prevent this.

The offline agents can be moved to inactive by configuring the inactivity timeout, described in https://www.elastic.co/guide/en/fleet/current/set-inactivity-timeout.html.

I don't think this is actually a bug, just configuration that can be improved. I'm going to close this.
