### ISSUE TITLE
elastic agent custom install path

### ISSUE THREAD

**Issue by aniketpant1** [elastic/elastic-agent#3506]
Hi Team,

We are using ELK platinum version 8.x. We want to use elastic agent but in the documentation of elastic agent they have mention  ** You cannot override these installation paths because they are required for upgrades.** But in some organization they have security policy that application cannot install at root path. In our organization we cannot install any application `/opt` they have given separate mount point /appadmin/elk so we need to use this path for installing and running elastic agent.

**Comment by nimarezainia** [comment]
@aniketpant1 thanks for spotting this. We will be amending the documentation. (@kilfoyle )

**Comment by aniketpant1** [comment]
Can we install , configure and run elatic agent as non root ?

**Comment by nimarezainia** [comment]
No you can't. Not at the moment.

I thought you were referring to the installation path of the agent.

**Comment by aniketpant1** [comment]
So we cannot install elastic agent at this moment? We need to wait for future release?

**Comment by jlind23** [comment]
Closing this as done thanks to - https://github.com/elastic/elastic-agent/pull/3517
