### ISSUE TITLE
[Flaky Test] -  TestDownloadBodyError

### ISSUE THREAD

**Issue by narph** [elastic/elastic-agent#352]
## Flaky Test

* **Test Name:** TestDownloadBodyError
* **Link:** [Link to file/line number in github.](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/artifact/download/http/downloader_test.go#L28)
* **Branch:** main
* **Notes:** It happens quite often, can be reproduced locally (Windows 11) 9/10 times

### Stack Trace

```
=== RUN   TestDownloadBodyError
    downloader_test.go:69: 
        	Error Trace:	downloader_test.go:69
        	Error:      	"[{download progress from %s has fetched %s @ %sps [http://127.0.0.1:65283/beats/filebeat/filebeat-7.5.1-linux-x86_64.tar.gz 0B NaNB]} {download from %s failed at %s @ %sps: %s [http://127.0.0.1:65283/beats/filebeat/filebeat-7.5.1-linux-x86_64.tar.gz 0B NaNB %!s(*errors.errorString=&{unexpected EOF})]}]" should have 1 item(s), but has 2
        	Test:       	TestDownloadBodyError
        	Messages:   	download error not logged at info level
--- FAIL: TestDownloadBodyError (0.00s)

FAIL

Process finished with the exit code 1

```

Line https://github.com/elastic/elastic-agent/blob/6df928dd1c1d8e36008bf54f624d8174f7a86c19/internal/pkg/artifact/download/http/downloader.go#L165 does not return an error or failing status code as it should.

**Comment by ph** [comment]
@blakerouse seems related to the download change?
