### ISSUE TITLE
TestProgress test is flaky in CI, sometimes produces more '.' than expected

### ISSUE THREAD

**Issue by leehinman** [elastic/elastic-agent#3520]
## Flaky Test

* **Test Name:** TestProgress
* **Link:** https://github.com/elastic/elastic-agent/blob/8bf732e097e42e736988b49155483ef4110889d4/internal/pkg/agent/install/progress_test.go#L79
* **Branch:** main
* **Artifact Link:** 
* **Notes:** In CI the test can take longer so you get more '.' than expected.  Just changing the regext from `.\{3}` to `.\{3,}` should fix the issue.  That way we check for at least `...` but more is fine if CI takes longer to run the test.
* 

### Stack Trace

```
=== FAIL: internal/pkg/agent/install TestProgress/nested_step_delayed_success (0.09s)
    progress_test.go:136: 
        	Error Trace:	/Users/runner/work/elastic-agent/elastic-agent/internal/pkg/agent/install/progress_test.go:136
        	Error:      	Expect "step starting...
        	            	   substep 1 starting... DONE
        	            	   substep 2 starting...... DONE
        	            	   DONE
        	            	" to match "step starting\.{3}\n   substep 1 starting\.{3}\.+ DONE\n   substep 2 starting\.{3}\.+ DONE\n   DONE\n"
        	Test:       	TestProgress/nested_step_delayed_success


```

**Comment by cmacknz** [comment]
Related: https://github.com/elastic/elastic-agent/pull/3493
