### ISSUE TITLE
Elastic fleet agent tags in event metadata

### ISSUE THREAD

**Issue by Alphayeeeet** [elastic/elastic-agent#3582]
Fleet agent tags (#149) should be added to the event metadata on every event sent by the agent (e.g. like hostname or agent-id). 
This could be configurable to enable or disable.

With tags added to event metadata and indexed in every document, users could use those metadata as a filter in dashboards or searches to monitor specific environments (e.g. development or production). This would also simplify the whole namespacing process, as you do not need to setup different policy-namespaces for different environments.
I know this is possible by configuring processors in integration policies, but managing additional tags by agent and adding them to events as tags would be way more end user friendly.

This issue would be resolved, if every event sent by the agent has its tags (optionally: can be configurable) as a metadata field.

**Comment by cmacknz** [comment]
This is the correct place, this is currently blocked on support for global processors in general.

CC @nimarezainia

**Comment by Alphayeeeet** [comment]
@cmacknz Thanky for the reply. Is there any planned release date for global processors? We think about migrating to fleet, but only if this feature would be available.

**Comment by cmacknz** [comment]
There is no planned release date for global processors, but we do plan to support them as they are a frequent feature request. I just can't promise a specific date.

**Comment by kocotj** [comment]
It would be good to at least have an option to add Elastic Agent tags to event data. Without being able to tag individual VMs it's really difficult to create any meaningful dashboards especially in large infrastructures.

**Comment by cmacknz** [comment]
Yes we are working to prioritize including tags to event data. As before I can't promise a specific date, but we know this is a problem and plan to address it.

**Comment by cmacknz** [comment]
@nimarezainia

**Comment by Alphayeeeet** [comment]
Are there any updates regarding the release date and the feature in general?

**Comment by nimarezainia** [comment]
> Are there any updates regarding the release date and the feature in general?

it's a high priority on the list of items to address, but we don't have a date as such.

**Comment by djkproj** [comment]
Hello, is there any update on this? Thanks

**Comment by nimarezainia** [comment]
No sorry, not set release data as yet.

**Comment by liladler** [comment]
Hi @nimarezainia, Is there an update on this feature?

**Comment by nimarezainia** [comment]
> Hi @nimarezainia, Is there an update on this feature?

High priority but I don't have a release date for you as yet.

**Comment by nimarezainia** [comment]
@Alphayeeeet the ability to add a field at a policy level is currently being worked on. Until we know more can't commit to a release. You can follow it all here: https://github.com/elastic/kibana/issues/179915

**Comment by Alphayeeeet** [comment]
@nimarezainia As the issue https://github.com/elastic/kibana/issues/179915 has been merged, I wanted to ask, if there is a proposed release date? Is it expected to get released in 8.15?

**Comment by jlind23** [comment]
@Alphayeeeet it should be available from 8.15 onwards, I'll close this issue as completed but feel free to reopen it afterwards if required.

**Comment by sebastien-prudhomme** [comment]
Hi @jlind23 I don't see the link between https://github.com/elastic/kibana/issues/179915 and this issue.

Fleet agent tags are defined per agent. The other issue will allow to add tags per agent policy.

My use case is to define a fleet tag on a agent, for instance a "env-production" tag and have it included in every data collected by the agent. Will it be possible to do it with Fleet in 8.15 version?

**Comment by jlind23** [comment]
@sebastien-prudhomme So what you are trying to achieve is that you will have a policy containing multiple agents but tags should be apply only to one Agent or a subset of them not all. Am I correct?
cc @nimarezainia

**Comment by nimarezainia** [comment]
@sebastien-prudhomme what you are asking for won't be possible unless the tag is defined as a variable.
What we do allow is for the user to define the tag when the agent is installed. This tag will identify the agent in Fleet UI. The user can also modify the tag in the fleet ui (or add/delete). This tag however is not included in the metadata.

What @jlind23 pointed you to allows you to add a tag in to teh event data at a policy level. So all agents in the policy will get the tag added to their events. Sounds like you are asking for a more per-agent granular tags to be added, which this doesn't do.

@cmacknz do you think that local environment variables (local providers) could be used here? so the user can add a tag whose value is a variable substitution.

**Comment by sebastien-prudhomme** [comment]
@nimarezainia that's exactly what I want to do: include the tags defined at the Fleet level as metadata in logs, metrics, traces.

As you suggested I will try this provider: https://www.elastic.co/guide/en/fleet/current/env-provider.html maybe with this processor: https://www.elastic.co/guide/en/fleet/current/add_tags-processor.html

**Comment by cmacknz** [comment]
> @cmacknz do you think that local environment variables (local providers) could be used here? so the user can add a tag whose value is a variable substitution.

This makes sense to me. We'll have to do some refinement on the syntax to support (is the variable all tags? specific tags?) but this should be the way to solve this problem.

**Comment by Alphayeeeet** [comment]
@nimarezainia or @cmacknz In that case, could you please reopen the issue, as the original proposed change is not possible by this provided feature. Thank you in advance

**Comment by djkproj** [comment]
Can we not have it in both places i.e.: tags on the policy level meaning any new agent added to the policy will get the tags applied and in addition each agent can be individually tagged as well (existing functionality) the all the tags assigned to the agent will be populated in all the integration(s) logs collected. If the Elastic Agent run a metricbeat/filebeat/heartbeat under the bonnet then this should be achievable as the Beats have an option to add tags on the YML level. we did something similar when we tried to automate Beats deployments before moving to agents. We'd have a variable defined in the tags field e.g.:
`
tags: [{{mytags}}]`

and in the deployment pipeline we would replace it with the tags defined in the pipeline.

Quite surprised this functionality hasn't been in place since day one as it's crucial for efficient aggregation of resources.

**Comment by cmacknz** [comment]
> If the Elastic Agent run a metricbeat/filebeat/heartbeat under the bonnet then this should be achievable as the Beats have an option to add tags on the YML level

Just for context, you are right that handling Beats is relatively straightforward, but Elastic Agent also runs things that are not Beats like Elastic Defend which is implemented in a completely different language. The extra time and complexity comes from having to deal with these non-Beats in a reasonable way, a significant amount of people asking for this feature want it to also work with things that are not implemented with Beats.

We also don't like that things that appear simple like this are hard to support in our current architecture and are working on some changes to make this easier to deal with.

**Comment by djkprojects** [comment]
Hello,

Has there been any progress on this please?

Thanks

**Comment by nimarezainia** [comment]
@djkprojects and @MattCyberoo, I wanted to clarify that we already have the ability to add tags to the data collected on a per-policy basis: https://www.elastic.co/guide/en/fleet/current/agent-policy.html#add-custom-fields

This issue specifically is about having the tag read a local provider for the value that needs to be added.

**Comment by daviesi1975** [comment]
Is there any progress on this? We want the documents sent by Elastic Agent (Custom Logs) to contain tags set at Host level. As above, I appreciate that we can add hard coded tags to Agent Policies, but this would mean that we'd need a policy per Agent. Is there any variable we can set on the individual hosts which would get copied through to the documents sent to Elasticsearch?

**Comment by getkub** [comment]
Rather than waiting on this fix for more than 3 years, we went and did ourselves ! This enhancement should have been done by Elastic 3 years ago as it is so much important for enterprise customers.

So tag in 'Fleet' api for each host (multiple tags). Few options then (We went with option 1)
1.  Do at 'ESQL' search-time by doing a lookup join with `.fleet-servers `. (What we did is using  Elastic workflows to create a lookup index from `.fleet-servers` for hostname & tags.
2. Use the enrich processor in ingest-pipeline using the above lookup dataset on a daily basis
3. Export the lookup into logstash if its in the chain. Then logstash can do using `translate` filter

**Comment by buzzdeee** [comment]
is there any progress here?
Using Custom Fields per policy could be a way around it, half way, but since there are integrations that don't support custom fields, i.e. defend, and cloudbeat related, this is also not a proper solution/workaround the issue.

Sebastian

**Comment by Alphayeeeet** [comment]
@nimarezainia Any updates on this issue by now?

**Comment by nimarezainia** [comment]
> [@nimarezainia](https://github.com/nimarezainia) Any updates on this issue by now?

this is currently in progress: https://github.com/elastic/kibana/issues/271551
