### ISSUE TITLE
Run only providers that have references in the policy

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#3609]
**Describe the enhancement:**

Currently the Elastic Agent runs all of its providers all the time. Context providers are rather low overhead, but dynamic providers are not and when they are not even being used its adding load for no benefit to the running policy.

We should adjust the Elastic Agent to only run providers that are referenced in the policy. Variable referencing is always prefixed with a provider name aka `${kubernetes.*}` that means its rather easy to identify which providers should be enabled based on what is in the policy.

This also removes the need to add any configuration to Fleet to disable or enable a provide for the Elastic Agent. If the policy from Fleet doesn't use a provider then the Elastic Agent will not run it.

**Describe a specific use case for the enhancement or feature:**

Reduce load of an Elastic Agent, prevents it from trying to communicate with Docker or Kubernetes in the case that its not even running a Docker or Kubernetes inputs in the policy.

**What is the definition of done?**

I propose the following change:

1. Parse the policy into the AST.
2. Read the AST to determine the providers that are referenced.
3. Start/stop the providers that are referenced or no longer referenced.

**Comment by cmacknz** [comment]
An additional problem we discovered recently is that the `.enabled` configuration for a provider is only read once at startup when the controller is first created:

https://github.com/elastic/elastic-agent/blob/be04fba8e3797607dcf5f7eaa238050a711d99a7/internal/pkg/composable/controller.go#L52-L71

This means disabling a provider in the policy has no effect unless you also restart the agent. The change proposed here would also fix this problem.

For context we were attempting to disable the k8s leader election provider with a Fleet policy override and found this wasn't possible without restarting the agent manually afterwards.
