### ISSUE TITLE
Why did Elastic Agent successfully connect to Fleet Server but Elasticsearch did not receive data?

### ISSUE THREAD

**Issue by yunhoang2708** [elastic/elastic-agent#3643]
Hi,
First of all, I would like to wish everyone a good day.

The current problem I am facing is about Elastic Agent. Although I followed the instructions and successfully installed the Agent on my machine, I don't understand what error I encountered that "status: Healthy" cannot receive the Agent data sent to Elasticsearch.

I had a lot of difficulty finding more information about this issue but there aren't many articles online about this. So I look forward to hearing from everyone.

Once again, I wish everyone joy and happiness.
Thank you very much!

![Screenshot from 2023-10-23 09-15-51](https://github.com/elastic/elastic-agent/assets/115698486/75a1123d-4f17-43f4-8d2b-0f3678ad5c73)
![Screenshot from 2023-10-23 09-16-05](https://github.com/elastic/elastic-agent/assets/115698486/2b134fc4-c0ee-480d-bdf4-bdb4f447f00e)
![Screenshot from 2023-10-23 09-16-41](https://github.com/elastic/elastic-agent/assets/115698486/bb88e05f-9935-4649-8203-6f302c906fd5)
![Screenshot from 2023-10-23 09-17-03](https://github.com/elastic/elastic-agent/assets/115698486/fa051707-16e2-4f66-bc0d-acb68eb94d4c)

**Comment by pierrehilbert** [comment]
Hello,
Is your monitoring output correctly configured to send data to this elasticsearch and not another one?

**Comment by yunhoang2708** [comment]
Hi @pierrehilbert ,
The problem I'm having is that I configured the monitoring screen incorrectly, right? Because I installed ELK via Docker on  the server. I want to collect data from Elastic Agent on the client to send data back to Elasticsearch on the receiving server.

**Comment by pierrehilbert** [comment]
If you are going on the discover tab, are you able to see datas in your indices?

**Comment by yunhoang2708** [comment]
Hi @pierrehilbert,
I logged in, but there is no data or log

**Comment by pierrehilbert** [comment]
Could you please verify your output configuration then?

**Comment by yunhoang2708** [comment]
Hi @pierrehilbert ,
This is my configuration
![image](https://github.com/elastic/elastic-agent/assets/115698486/c924c905-72aa-4e09-afc1-c12b5474c146)

**Comment by pierrehilbert** [comment]
And you don't have anything in `metrics-*` index when you are looking into discover?

**Comment by pierrehilbert** [comment]
Closing for now as I didn't get more informations.

**Comment by Nicat1991** [comment]
Hi everyone. Can you resole this problem? I have same problem too.
