### ISSUE TITLE
Skip integration tests for changes that do not modify Go source files

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#3674]
We should skip running integration tests (or unit tests but integration tests are the most expensive) for changes in PRs that modify files that are unused in tests and cannot affect them:

Current examples are:
- Changes to https://github.com/elastic/elastic-agent/tree/main/changelog
- Changes to https://github.com/elastic/elastic-agent/tree/main/docs
- Changes to https://github.com/elastic/elastic-agent/blob/main/README.md
- Changes to https://github.com/elastic/elastic-agent/blob/main/sonar-project.properties

**Comment by cmacknz** [comment]
https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin might be the easiest way to implement this.

**Comment by pazone** [comment]
That's relatively easy. Can raise a PR today

**Comment by jlind23** [comment]
@pazone am I right to assume that this one will be definitely close once https://github.com/elastic/elastic-agent/pull/4739 land?

**Comment by cmacknz** [comment]
I don't see anything related to skipping the extended pipeline based on the files that changed in a commit, but maybe I am misunderstand how this works.

If someone commits a changelog fragment or changes the README, how are we avoiding running the integration tests?

**Comment by cmacknz** [comment]
Reopening, we are still running integration tests in situations where it makes no sense to do so.

For example a dependabot configuration change was blocked by failing integration tests https://github.com/elastic/elastic-agent/pull/4802

**Comment by rowlandgeoff** [comment]
Reopening since the change had to be partially reverted: https://github.com/elastic/elastic-agent/pull/4866

https://elastic.slack.com/archives/C0522G6FBNE/p1717677463888959

Need to decide how to handle scenarios where the integration tests are skipped as unnecessary, but the integration tests are a required check in Github PRs.

**Comment by pazone** [comment]
https://github.com/elastic/elastic-agent/pull/4943
