### ISSUE TITLE
[Integration Test Framework] Cleanup Serverless projects

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#3675]
When Serverless integration tests are executed, a Serverless project is spun up.  At the moment, we're not cleaning up such projects all the time. This results in our organization ending up with too many projects, which then prevents future builds from being able to run Serverless integration tests.  Those builds start failing in CI with errors like this one:

> Error: error running test: ogc-linux-arm64-ubuntu-2204-1aea unable to continue because stack never became ready: error deploying stack for request 8120-SNAPSHOT: Non-201 status code returned by server: 400, body: Bad request, caused by: organization has reached the project limit: the organization currently has 94 projects, with a limit of 50 projects

**Comment by ycombinator** [comment]
Okay, now I'm not convinced that there isn't some sort of auto-cleanup of Serverless projects happening already.  This [build](https://buildkite.com/elastic/elastic-agent/builds/4477) successfully executed the "Serverless integration test" step and I'm not seeing a Serverless project lingering around from it in the [Staging ESS Serverless UI](https://admin.staging.foundit.no/projects?organization_id=3838378299&sort=-metadata.created_at). 🤔

**Comment by ycombinator** [comment]
Talking to @pchila, it appears we are not leaking projects all the time.  When Serverless integration tests execute successfully, we do perform cleanup.  The leakage seems to happen only when something goes awry during the execution of this step.  So we likely do still need an out-of-band cleanup process for old/stale Serverless projects.

**Comment by cmacknz** [comment]
Fixed with https://github.com/elastic/elastic-agent/pull/3701, closing.

**Comment by belimawr** [comment]
I've just hit what seems to be the same issue:
```
Error: error running test: error deploying stack for request 910-SNAPSHOT: Non-201 status code returned by server: 403, body: {"errors":[{"code":"projects.create_project.forbidden","message":"create request validation failed: limit reached: organization has reached the project limit [50]"}]}
```

Should we re-open this one or create a new issue?

BK link: https://buildkite.com/elastic/elastic-agent/builds/20567/summary/annotations?sid=01966de4-1ac6-4f07-a44b-604d35ae897a#01966e10-6e8b-4189-bf8f-e33d38301240/1745603394989/Running%20commands-364

cc: @cmacknz
