### ISSUE TITLE
The Elastic Agent packaging job does not run integration tests

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#3686]
The Elastic Agent package job in https://fleet-ci.elastic.co/job/elastic-agent/job/elastic-agent-mbp/ does not currently run the agent integration tests and is separate from our Buildkite pipelines.

These packages are currently not used in the release process, but when they are they should be running our integration tests before uploading the final artifact. Possibly it would be better to have the DRA artifact uploaded automatically whenever a commit is merged to main and each release branch, which does run the complete set of tests.

**Comment by jlind23** [comment]
@pazone with the recent changes you did on the CI part is this one still relevant?

**Comment by cmacknz** [comment]
This isn't fixed, the packaging job still has no tests, but we do run tests for each commit to main so every commit that gets packaged is tested at least once.

We can close this.
