### ISSUE TITLE
[Integration] Add support for Docker runner

### ISSUE THREAD

**Issue by pierrehilbert** [elastic/elastic-agent#3732]
# Issue

**Describe the enhancement:**

Some users are running Elastic Agent on Docker and we are not currently able to tests our different scenarios on this environment.

**Describe a specific use case for the enhancement or feature:**

To support testing on Docker.

# Definition of done

- [ ] Create a OSRunner for Docker
- [ ] Update the OS support list for the runner
- [ ] Ensure that already in place tests are working on Dockers

**Comment by ycombinator** [comment]
@blakerouse Would we be able to implement this issue by implementing a new `InstanceProvisioner`?

https://github.com/elastic/elastic-agent/blob/3fe574119e8f0729fa2338afb6f1b350f3e6743f/pkg/testing/common/instance.go#L46-L47

**Comment by cmacknz** [comment]
I think the kind runner probably covers this, unless we specifically want to test containers separate from k8s.

**Comment by cmacknz** [comment]
(I don't think there's much value in testing docker separate from k8s)

**Comment by ycombinator** [comment]
Thanks @cmacknz.  Closing for now.
