### ISSUE TITLE
All applicable integration tests should run with an unpriveledged agent installation

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#3736]
Now that we are adding support for running the agent as an unpriveledged user (i.e. not root or admin) in https://github.com/elastic/elastic-agent/pull/3598 we need to ensure we have adequate test coverage for it.

The best path is to parameterize the tests to clearly indicate whether a test supports running as an unprivileged user. For example, tests that install Elastic Defend must run as root or admin so can't run with an unprivileged installation. Although perhaps in this case the tests should still run but change the success criteria to ensuring the runtime prevention for root prevents package installation.

This would lead to us running every integration test twice, ideally in parallel. This will consume more test resources but give us the best test coverage.

If the resource cost or time taken to run every test twice in both installation modes becomes too much, we should prefer testing unprivileged installations for every test and only use privileged tests in cases where it is required or cases that are essential (upgrading, enrolling with Fleet, etc).

**Comment by cmacknz** [comment]
@pierrehilbert pulled into the current sprint as a follow up from https://github.com/elastic/elastic-agent/pull/3598, which only adds a basic installation test.

We can't release non-root/unprivileged support without integration tests for important scenarios like upgrades, enrolling with Fleet, shipping logs, etc.

**Comment by amitkanfer** [comment]
important.

**Comment by nimarezainia** [comment]
Made this a p0 for now due to its importance.

**Comment by pierrehilbert** [comment]
Agree, this is crucial to test things properly before officially support it BUT I wouldn't make it as a P0: I don't want us to rush the official support of this feature.

We still have a lot to test and to put in place before being ready to have this use in production:

- Defining every integration / behavior that won't work as expected
- How to handle properly upgrades triggered from Fleet and therefore without root/sudo permissions

Anyway, more important to me to add tests than supporting other OS but would like to keep P0 for urgent things.
