### ISSUE TITLE
[Integration Test Framework] does not keep track of the stack type (statefull/serverless)

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#3756]
When the framework creates a stack deployment it does not save it's type (statefull/serverless), so when re-using existing stacks, it will use whatever stack from the required version exists, regardless of the stack provisioned selected.

This makes statefull tests run against serverless and vice versa depending on which one was run first.

**How to reproduce:**
1. Make sure there is not existing stack, run: `mage integration:clean`
2. Run a test against serverless: `STACK_PROVISIONER=serverless TEST_PLATFORMS="linux/amd64" SNAPSHOT=true mage -v integration:single TestLogIngestionFleetManaged`
3. Everything works, a serverless project is created.
4. Run the same test against statefull: `TEST_PLATFORMS="linux/amd64" SNAPSHOT=true mage -v integration:single TestLogIngestionFleetManaged`
5. The serverless project is used, see the logs:
```
>>>> Using ogc instance provisioner
>>>> Using stateful stack provisioner
>>> Creating zip archive of repo to send to remote hosts
>>> Reusing stack 8.12.0-SNAPSHOT (8120-SNAPSHOT)
```

**Comment by AndersonQ** [comment]
it's seems to be the same I'm fixing here https://github.com/elastic/elastic-agent/pull/3734

**Comment by AndersonQ** [comment]
actually, I was looking better at it, this issue isn't the same as the one I'm fixing on https://github.com/elastic/elastic-agent/pull/3734. However they're similar, so I think they can be the same PR
