### ISSUE TITLE
[Enhancement]: Installation percentage bar can be added with details while installing agent. 

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#3795]
**Kibana Build details:**
```
VERSION: 8.12.0
BUILD: 69191
COMMIT: 37bf74b0d8f03b2c2ec2c036926c3b0ba3f78fed
```

**Host OS:**  All

**Preconditions:**
1. 8.12.0 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet tab.
2. Open Add agent flyout.
3. Run Agent install command.
4. Observe installation time bar is available however installation percentage bar is not available with details while installing agent.

**Screen-shot:**
![image](https://github.com/elastic/elastic-agent/assets/101545338/0406730f-e17c-46a4-a288-5473eeb1b39e)

**Enhancement:**

- It is challenging for the user to determine whether the agent is installing or is stucked because time lapsed is displayed with installation process.
- It would be helpful if we can show the percentage done with time lapsed.

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource kindly review

**Comment by amolnater-qasource** [comment]
Secondary Review for this ticket is done.

**Comment by pierrehilbert** [comment]
I don't think this is possible to get % as this one doesn't exist properly.
@ycombinator / @fearful-symmetry what is your opinion here?

**Comment by ycombinator** [comment]
@pierrehilbert Showing a progress percentage would require knowing the expected completion target (expected time for completion, # of total bytes to be written, etc.) for each step in the installation. I think we might be able to figure this out for some steps (e.g. the file copying step) but perhaps not for other steps (e.g. the Fleet enrollment step).  So we could do some sort of best effort here, pretending that the latter type of steps don't count towards the progress percentage calculation.

**Comment by pierrehilbert** [comment]
That's what I thought.
Let's keep it that way for now then.

**Comment by jlind23** [comment]
According to @ycombinator I don't think we are ready yet to work on this nor if this really is something we want to achieve. I'll close this for now as won't fix but leave it to @nimarezainia to reopen if required.
