### ISSUE TITLE
Test that the agent.download settings are respected for Fleet enrolled agents

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#3820]
- Relates https://github.com/elastic/elastic-agent/issues/3560

To start configure and invalid source URI and then use the Kibana Dev Tools to override the `agent.download.timeout` parameter in Fleet to `1s`. For example:

```
PUT kbn:/api/fleet/agent_policies/65df03d7-5d26-490c-a24a-ae05095c1a4a
{
   "name": "Agent policy 1",
    "namespace": "default",
    "overrides": {
         "agent": {
              "download": {
                "timeout": "1s"
              }
            }
    }
}
```

This result in the follow agent policy:
```
~/Downloads ··········································································· 03:21:23 PM
❯ sudo elastic-agent inspect
agent:
  download:
    sourceURI: https://artifacts.elastic.co/notdownloads/
    timeout: 1s
```

Instruct the agent to upgrade and observe that the agent continues to stay in the downloading state for more than 1s (note the current time jumping from 03:53:41 to 03:53:43). The same is observable in the logs.

```
~/Downloads ················································································· 03:53:41 PM
❯ sudo elastic-agent status
┌─ fleet
│  └─ status: (HEALTHY) Connected
├─ elastic-agent
│  └─ status: (UPGRADING) Upgrading to version 8.11.1
└─ upgrade_details
   ├─ target_version: 8.11.1
   ├─ state: UPG_DOWNLOADING
   ├─ action_id: 5f0d1b8c-fe05-4b0e-a44d-b872946b1294
   └─ metadata
      └─ download_percent: 0.00%

~/Downloads ················································································· 03:53:43 PM
❯ sudo elastic-agent status
┌─ fleet
│  └─ status: (HEALTHY) Connected
├─ elastic-agent
│  └─ status: (UPGRADING) Upgrading to version 8.11.1
└─ upgrade_details
   ├─ target_version: 8.11.1
   ├─ state: UPG_DOWNLOADING
   ├─ action_id: 5f0d1b8c-fe05-4b0e-a44d-b872946b1294
   └─ metadata
      └─ download_percent: 0.00%
```

Possible this is the same problem as https://github.com/elastic/elastic-agent/issues/3560, which now has a PR with a fix https://github.com/elastic/elastic-agent/pull/3803

In this case the timeout should be controlled from the context in the download function:

https://github.com/elastic/elastic-agent/blob/97e82175953af75fbe29fccc3cfcc5688a96dc8f/internal/pkg/agent/application/upgrade/step_download.go#L238-L265

**Comment by AndersonQ** [comment]
fixed by https://github.com/elastic/elastic-agent/pull/3803

**Comment by cmacknz** [comment]
We should add a test to specifically verify that it stays fixed for the timeout, increasing the download timeout is one of the only ways to fix failing upgrades on slow networks. We need to make sure it keeps working.

Reopening to make sure this happens.

**Comment by blakerouse** [comment]
@cmacknz Can you please file a different issue or update the title of this issue? The title of the issue makes it seem like it is still a bug, when it has been fixed. I agree a test should be added, but lets make that clear.
