### ISSUE TITLE
Watcher does not consider build hash when determining if upgrade was rolled back

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#3821]
With the introduction of the tracking of `UPG_ROLLBACK` state the watcher compares the new version of the agent with the previous one. However when comparing it only uses the major.minor.path[-SNAPSHOT], ignoring the build hash.

If the agent is upgraded from an SNAPSHOT version to another the watcher considers they as being the same version and therefore it marks the upgrade as `UPG_ROLLBACK` and neither logs why it changed the upgrade status nor adds any information to the new state.
This leads to an successful upgrade, a healthy agent but marked as `UPG_ROLLBACK` as shown below. Without any log or information explaining why the agent is on an `UPG_ROLLBACK` state.

![Screenshot from 2023-11-24 15-35-48](https://github.com/elastic/elastic-agent/assets/203669/4eb900c7-5724-4d6b-892d-e49fb0160d84)

The culprit seems to be here:

https://github.com/elastic/elastic-agent/blob/d58ac9cb9183317ea0bc58bc6d1e38244000b5a3/internal/pkg/agent/application/upgrade/marker_watcher.go#L117-L123

The `UpgradeMarker` has both hashes, it just need to be used when comparing the versions

https://github.com/elastic/elastic-agent/blob/d58ac9cb9183317ea0bc58bc6d1e38244000b5a3/internal/pkg/agent/application/upgrade/step_mark.go#L27-L43

For confirmed bugs, please report:
- Version: main
- Operating System: all
- Discuss Forum URL: N/A
- Steps to Reproduce: Upgrade from a snapshot build to another from the same version.

**Comment by pchila** [comment]
Reopening as it needs fixes from PRs #3827 #3837
