### ISSUE TITLE
Restarting Endpoint service while Agent is running causes segmentation fault

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#3843]
Please post all questions and issues concerning the Elastic Agent on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 8.11.1
- Operating System: Linux
- Discuss Forum URL:
- Steps to Reproduce: 
  - Install elastic-agent enrolled in fleet using a policy with Elastic Defend
  - Wait until agent and all the units are healthy
  - Restart endpoint service with `systemctl restart ElasticEndpoint`
  - elastic-agent crashes and gets restarted by systemd
  Contents of `journalctl -u elastic-agent`
  ```
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]: panic: runtime error: invalid memory address or nil pointer dereference
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x55d359403346]
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]: goroutine 147 [running]:
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]: github.com/elastic/elastic-agent/pkg/component/runtime.(*ComponentState).syncCheckin(0xc0002320a8, 0xc00091b260)
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]:         github.com/elastic/elastic-agent/pkg/component/runtime/state.go:365 +0xa26
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]: github.com/elastic/elastic-agent/pkg/component/runtime.(*serviceRuntime).processCheckin(0xc000232000, 0xc00091b260, {0x55d35acad4a0, 0xc0002082a0}, 0xc000765d20)
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]:         github.com/elastic/elastic-agent/pkg/component/runtime/service.go:438 +0x2f4
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]: github.com/elastic/elastic-agent/pkg/component/runtime.(*serviceRuntime).Run(0xc000232000, {0x55d35acba880, 0xc000266050}, {0x55d35acad4a0, 0xc0002082a0})
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]:         github.com/elastic/elastic-agent/pkg/component/runtime/service.go:257 +0xa45
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]: github.com/elastic/elastic-agent/pkg/component/runtime.(*componentRuntimeState).runLoop.func1({0x55d35acba880?, 0xc000266050?})
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]:         github.com/elastic/elastic-agent/pkg/component/runtime/runtime.go:137 +0x90
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]: github.com/elastic/elastic-agent/internal/pkg/runner.Start.func1()
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]:         github.com/elastic/elastic-agent/internal/pkg/runner/runner.go:69 +0x37
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]: created by github.com/elastic/elastic-agent/internal/pkg/runner.Start
  Nov 29 11:05:20 pchila-elastic elastic-agent[423667]:         github.com/elastic/elastic-agent/internal/pkg/runner/runner.go:68 +0x14a
  Nov 29 11:05:20 pchila-elastic systemd[1]: elastic-agent.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
  ░░ Subject: Unit process exited
  ░░ Defined-By: systemd
  ░░ Support: http://www.ubuntu.com/support
  ░░
  ░░ An ExecStart= process belonging to unit elastic-agent.service has exited.
  ░░
  ░░ The process' exit code is 'exited' and its exit status is 2.
  Nov 29 11:05:20 pchila-elastic systemd[1]: elastic-agent.service: Failed with result 'exit-code'.
  ░░ Subject: Unit failed
  ░░ Defined-By: systemd
  ░░ Support: http://www.ubuntu.com/support
 
  ```

**Comment by cmacknz** [comment]
In the v8.11.1 branch this looks to be the problematic line `pkg/component/runtime/state.go:365`:

https://github.com/elastic/elastic-agent/blob/03ef9d8d6a894af61a77d78983a735d263b414ac/pkg/component/runtime/state.go#L360-L365

**Comment by cmacknz** [comment]
Missing check that `checkin.Features.Fqdn` isn't `nil` looking at it.

This code is deleted on main:

https://github.com/elastic/elastic-agent/blob/8a8abd046a1f549557d006031223919d71314f96/pkg/component/runtime/state.go#L360-L364

Does it reproduce for 8.12?

This would have been removed by https://github.com/elastic/elastic-agent/pull/3689 which contains https://github.com/elastic/elastic-agent-client/pull/84 deleting the field that was being set here as it was never used.

**Comment by pchila** [comment]
Just tested using an agent 8.12.0-SNAPSHOT (commit 8a8abd046a1f549557d006031223919d71314f96)  : the agent doesn't crash and detects endpoint correctly once it's restarted.

**Comment by pchila** [comment]
Tested using agent 8.11.2-SNAPSHOT (commit e0128e888743399637f75beb31eeb957cac81b91 ) and I cannot reproduce the issue anymore: the agent does not crash and picks up the new endpoint process correctly.
Issue is fixed
