### ISSUE TITLE
[OTel] Create `README.md` in `otel` package folder

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#3851]
At minimum the README should cover:
- short introduction mentioning that this is the Elastic Distribution of the OTel Collector.
- which components (receivers, etc.) are bundled in the distribution, including their versions.
- how to use the Elastic Distribution of the OTel Collector

Nice to have:
- how to develop the Elastic Distribution of the OTel Collector (could also be in a separate `CONTRIBUTING.md`)

**Comment by michalpristas** [comment]
thinking about using similar approach to what we have with Notice file.
Dependencies extracted from go.mod and versions updated from there as well with check on each CI build (mage update/check).
