### ISSUE TITLE
Agent is not able to send messages to kafka broker with authentication.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#3864]
**Kibana Build details:**
```
VERSION: 8.12.0 SNAPSHOT
BUILD: 69599
COMMIT: 3aac9bd56d2e1af5fd1b39fdb81b69214453746b
```

**Host OS:**  All

**Preconditions:**
1. 8.12.0 SNAPSHOT Kibana cloud environment should be available.
2. Agents should be installed using agent policy.
3. Add Kafka output configuration under agent output.

**Steps to reproduce:**
1. Select the kafka output under Agent policy settings.
2. Observe no data is pushed as a message on kafka topic.

**NOTE:**
- No errors are also observed on agent, when Elastic Defend integration is not added.
- On adding Elastic Defend integration, only then error message is visible under Agent details page.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/0cf622fc-65c0-47ab-80d8-31b29ad61b2d)

**Expected Result:**
Agent should be able to send messages to kafka broker with authentication.

**Agent.json:**
[ip-172-31-73-91-agent-details.zip](https://github.com/elastic/elastic-agent/files/13559850/ip-172-31-73-91-agent-details.zip)

**Logs:**
[elastic-agent-diagnostics-2023-12-05T12-03-42Z-00.zip](https://github.com/elastic/elastic-agent/files/13559842/elastic-agent-diagnostics-2023-12-05T12-03-42Z-00.zip)
[elastic-agent-diagnostics-2023-12-05T12-07-19Z-00.zip](https://github.com/elastic/elastic-agent/files/13559843/elastic-agent-diagnostics-2023-12-05T12-07-19Z-00.zip)

**Comment by amolnater-qasource** [comment]
FYI @cavokz 

Broker setup: https://github.com/elastic/security-team/issues/7408

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@amolnater-qasource Endpoint looks degraded here. Shall we ask @nfritts and team to look at this first?

**Comment by brian-mckinney** [comment]
Just FYI, I took a look at the logs.  Endpoint failing during the SSL handshake

**from endpoint logs:**
```
KafkaClient.cpp:54 Kafka Error: Local: SSL error [-181] | sasl_ssl://34.16.40.176:9092/bootstrap: SSL handshake failed: error:0A000126:lib(20)::reason(294) (after 127ms in state SSL_HANDSHAKE)
```

However, it appears that agent was having a similar problem:

**from agent logs:**
```
Kafka (topic=qatest): kafka: couldn't write SASL handshake (make sure SASL is enabled on the target broker port)
```

I tried connecting to the provided broker IPs myself and was unable to.  Are we sure the brokers are up and configured properly?

**Comment by cmacknz** [comment]
> is it right that the agent remains healthy if communications errors happen with the kafka broker?

Right no, expected yes. The Beats run by Elastic Agent does not yet report errors when it can't communicate with the output (for all outputs). This is tracked in https://github.com/elastic/elastic-agent/issues/3889 and is something we plan to fix. The implementation for Elastic Defend is separate but may have a similar limitation.

> Is there any documentation about the supported auth configurations?

It should be documented at https://www.elastic.co/guide/en/fleet/current/kafka-output-settings.html#_authentication_settings. If that isn't clear enough best thing to do is file an issue in https://github.com/elastic/ingest-docs to get it improved.

**Comment by cmacknz** [comment]
>  is therefore a bug or a feature that authenticating with username/password switches the underlying communication to encrypted? The documentation does not make this clear.

It's a feature to prevent users from sending credentials in plaintext, so we'll need to update the docs to clarify this.

**Comment by amolnater-qasource** [comment]
Hi @cavokz 

We have revalidated this with the latest instance on 8.12.0 BC2 kibana cloud environment and had below observations:

- Agent sends the data to the Kafka broker topic with username/password auth(at port 9093) and without auth(at port 9092).
- Further, on restarting too, we are able to reconnect to the same broker and agent is able to send the data.
- We are also able to send agent data with dynamic-topics too.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/26ac553a-c69d-4d7d-8b04-9b60ab73b42e)


**Build details:**
VERSION: 8.12.0 BC2
BUILD: 69899
COMMIT: 15a6cc8236b4828b97da733746ec36bd33f03bba

Hence, we are **closing** this issue and marking as **QA:Validated**.

Thanks!!
