### ISSUE TITLE
[Unprivileged] Enable `--unprivileged` on macOS

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#3867]
**Describe the enhancement:**

Current support for `--unprivileged` is isolated to Linux, this needs to be expanded to support macOS.

**Describe a specific use case for the enhancement or feature:**

To allow Elastic Agent to run on macOS without requiring root privileges.

**What is the definition of done?**

When `install --unprivileged` installs and Elastic Agent works running on macOS in this mode.

**Comment by cmacknz** [comment]
> I've never heard about --unprivileged flag. Is it something new, as it's not mentioned for 8.12 https://www.elastic.co/guide/en/fleet/current/elastic-agent-cmd-options.html#elastic-agent-install-command ?

It is being developed and not considered ready for users yet.

> I wonder what is the intended use case. I guess that this mode should explicitly disable Elastic Defend support to avoid confusion. Elastic Defend won't talk to Agent running under unprivileged account.

People don't want to install agent as root/admin unless they have to (to access data protected by root permissions, to run Elastic Defend, etc). We won't allow installing Elastic Defend on an unprivileged agent so this isn't something the defend team has to account for.
