### ISSUE TITLE
[Unprivileged] Enable `--unprivileged` on Windows

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#3868]
**Describe the enhancement:**

Current support for `--unprivileged` is isolated to Linux, this needs to be expanded to support Windows.

**Describe a specific use case for the enhancement or feature:**

To allow Elastic Agent to run on Windows without requiring Administrator privileges.

**What is the definition of done?**

When `install --unprivileged` installs and Elastic Agent works running on Windows in this mode.

**Comment by nicpenning** [comment]
Will this allow a service account or managed user to do this?

For example, if I have a service account in active dieectory that works on the system already, can I use that or is elastic creating an account and group locally?

The use case is integrations that need network access from specific service accounts in active directory to be the service context for filebeat (api, file shares, etc).

Today system is the only option but this gives me hope for 1 non system which is great, but having custom users would be excellent. 

In the past you could simply install filebeat or winglogbeat with the service account you needed as a service and it would use that user context when it runs.
