### ISSUE TITLE
[OTel Collector] Support for `validate` subcommand

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#3871]
Otel collector contains a subcommand for validating configuration 
https://github.com/open-telemetry/opentelemetry-collector/blob/cefe1b7d647cd5859f10a7de4e18b46eb3378c5d/service/README.md?plain=1#L148

We should support `validate` subcommand with all flags

DoD:
- `elastic-agent validate` command exists
- `otelcorecol validate` can be fully replaced by `elastic-agent validate` without any manual script changes

**Comment by michalpristas** [comment]
Fixed https://github.com/elastic/elastic-agent/pull/4023
