### ISSUE TITLE
[OTel Collector] `elastic agent status` command should work

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#3872]
At the moment, when Agent is running in OTel mode, `elastic-agent status` reports the following:
```
$ ./elastic-agent -c otel.yml status
Error: failed to communicate with Elastic Agent daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix /private/tmp/elastic-agent-8.12.0-SNAPSHOT-darwin-aarch64/elastic-agent.sock: connect: no such file or directory"
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.12/fleet-troubleshooting.html
```

We should enhance this output so it at least reports whether the OTel collector is running. Reporting the status of each running receiver and exporter is out of scope for this issue and can be implemented as a follow up.

**Comment by joshdover** [comment]
@michalpristas is there more remaining here?

**Comment by ycombinator** [comment]
> @michalpristas is there more remaining here?

With https://github.com/elastic/elastic-agent/pull/4047 merged, `elastic-agent status` will report _Agent_ status even if Agent is running the embedded OTel collector.  So what's remaining now is this part:

> We should enhance [the status] output so it at least reports whether the OTel collector is running. Reporting the status of each running receiver and exporter is out of scope for this issue and can be implemented as a follow up.
