### ISSUE TITLE
[Elastic Agent] Enhance local_metadata to convey information about the agent's privilege mode

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/elastic-agent#3906]
**Describe the enhancement:**

The Diagnostics details regarding the unprivileged mode will be tracked under: https://github.com/elastic/elastic-agent/issues/4439

## Enhancement Request for this issue:
- Use the local_metadata to send information about the local agent's privilege mode to Fleet.

**Comment by cmacknz** [comment]
Created a separate issue to track indicating the privilege mode, since that feature is still under active development. https://github.com/elastic/elastic-agent/issues/4439

**Comment by pierrehilbert** [comment]
Thx Craig, it should indeed be tackled later.

**Comment by blakerouse** [comment]
With the Windows work I had to add `unprivileged` to the control protocol output, so the integration tests can confirm that its installed in unprivileged mode.

https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/application/info/agent_info.go#L39

Using that information to send to Fleet, should be as simple as adding that same field to https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/application/info/agent_metadata.go#L39

**Comment by pierrehilbert** [comment]
Thx @blakerouse for updating us on this!

**Comment by nimarezainia** [comment]
Thanks @blakerouse. @pierrehilbert let's keep this in sp28 and if its completed early in the cycle Fleet team can begin their work in the same sprint.

**Comment by jlind23** [comment]
> Using that information to send to Fleet, should be as simple as adding that same field to https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/application/info/agent_metadata.go#L39

@blakerouse If you want a put up a PR for this you are more than welcome 😅

**Comment by blakerouse** [comment]
@jlind23 Okay, okay.... ;-)

https://github.com/elastic/elastic-agent/pull/4524
