### ISSUE TITLE
[Error Logs]: Filebeat and Metricbeat failed error logs on rebooting Ubuntu tar.gz agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#396]
**Kibana version:**  8.2 BC-4 Kibana cloud environment

**Host OS:**  Ubuntu tar.gz

**Build details:**
VERSION: 8.2.0 BC-4
BUILD: 51431
COMMIT: a743498436a863e142592cb535b43f44c448851a
Artifact link: https://staging.elastic.co/8.2.0-3b2b9b86/downloads/beats/elastic-agent/elastic-agent-8.2.0-linux-x86_64.tar.gz

**Preconditions:**
1. 8.2.0 BC-4 Kibana cloud environment should be available.
2. Ubuntu .tar.gz agent should be installed

**Integrations:**
System

**Steps to reproduce:**
1. Reboot Ubuntu agent.
2. Observe agent logs after 120 seconds of reboot under Agent>Logs tab.
3. Select filter `error` and observe Filebeat and Metricbeat failed error logs.

**Expected Result:**
Filebeat and Metricbeat failed error logs should not be generated on rebooting Ubuntu tar.gz agent.

**Logs:**
[elastic-agent-diagnostics-2022-05-02T06-53-57Z-00.zip](https://github.com/elastic/elastic-agent/files/8601301/elastic-agent-diagnostics-2022-05-02T06-53-57Z-00.zip)
[filebeat logs.zip](https://github.com/elastic/elastic-agent/files/8601302/filebeat.logs.zip)
[metricbeat logs.zip](https://github.com/elastic/elastic-agent/files/8601303/metricbeat.logs.zip)

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/166196785-f7184565-a4e4-410b-be83-9f59767ff288.JPG)

**Note:**
- **These error logs are not observed on rebooting Windows, centos 8 (.rpm) and MAC agents.**
- This issue is reproducible on various attempts on different Ubuntu 20 machines.
- No other impact of these error logs is observed.
- Few extra error logs are also observed on Debian 10 agent:
![6](https://user-images.githubusercontent.com/77374876/166200556-793e2be9-cf60-423e-9005-d01abb6c839d.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by jlind23** [comment]
Lets fix the fleet server issue first.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@amolnater-qasource @manishgupta-qasource does this behaviour affects also 8.3?
@pierrehilbert could you find someone to work on it if this is affecting 8.3 please

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on latest 8.3 BC3 Kibana cloud environment and found it **fixed**.
- No Filebeat and Metricbeat failed error logs gets generated on rebooting Ubuntu tar.gz agent.

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/172842093-65d180fb-0f67-436f-a73f-ae42aaec2087.JPG)

**Build details:**
BUILD: 53272
COMMIT: 7a0df2bca36ced2a898420cbb193a9dba0782a7a
Artifact Link: https://staging.elastic.co/8.3.0-a70058df/downloads/beats/elastic-agent/elastic-agent-8.3.0-linux-x86_64.tar.gz

Hence we are closing this issue and marking it as QA:Validated.

Thanks
