### ISSUE TITLE
Flaky Test TestMarkerWatcher

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#3981]
## Flaky Test

* **Test Name:** TestMarkerWatcher
* **Link:** https://github.com/elastic/elastic-agent/blob/1ee9cc7ca9d88d676ab3124f1f57b2013ed17a9c/internal/pkg/agent/application/upgrade/marker_watcher_test.go#L25
* **Branch:** https://github.com/elastic/elastic-agent/pull/3929
* **Artifact Link:** https://buildkite.com/elastic/elastic-agent/builds/5878

### Stack Trace

```

=== Failed
--
  | === FAIL: internal/pkg/agent/application/upgrade TestMarkerWatcher (unknown)
  | panic: send on closed channel
  |  
  | goroutine 61 [running]:
  | github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.watchFileNotEmpty.func1()
  | C:/buildkite-agent/builds/bk-agent-prod-gcp-1704207293125079587/elastic/elastic-agent/internal/pkg/agent/application/upgrade/marker_access_test.go:124 +0x3ae
  | created by github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.watchFileNotEmpty
  | C:/buildkite-agent/builds/bk-agent-prod-gcp-1704207293125079587/elastic/elastic-agent/internal/pkg/agent/application/upgrade/marker_access_test.go:91 +0x20f


```

**Comment by ycombinator** [comment]
> * **Artifact Link:** https://buildkite.com/elastic/elastic-agent/builds/5878

Looking at this build, I'm not seeing `TestMarkerWatcher` failing.  

I also ran it locally on my Mac with 5000 iterations, a couple of times, and I wasn't able to get it to fail.

```
$ go test ./internal/pkg/agent/application/upgrade/... -test.run TestMarkerWatcher -test.count 5000
?   	github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/artifact/download/localremote	[no test files]
ok  	github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade	75.885s
ok  	github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/artifact	1.031s [no tests to run]
ok  	github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/artifact/download	1.089s [no tests to run]
ok  	github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/artifact/download/composed	0.930s [no tests to run]
ok  	github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/artifact/download/fs	1.368s [no tests to run]
ok  	github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/artifact/download/http	1.035s [no tests to run]
ok  	github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/artifact/download/snapshot	0.273s [no tests to run]
ok  	github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade/details	1.642s [no tests to run]
```

Looking at the stack trace in the issue description, it's possible this test is only flaky on Windows.  Also, it's possibly a clue towards the flakiness that the test failing is `TestMarkerWatcher` but the goroutine shown as running in the stack trace is from a different test, `TestWriteMarkerFileWithTruncation` (it's the only test that calls the `watchFileNotEmpty` function mentioned in the stack trace).

> ### Stack Trace
> ```
> 
> === Failed
> --
>   | === FAIL: internal/pkg/agent/application/upgrade TestMarkerWatcher (unknown)
>   | panic: send on closed channel
>   |  
>   | goroutine 61 [running]:
>   | github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.watchFileNotEmpty.func1()
>   | C:/buildkite-agent/builds/bk-agent-prod-gcp-1704207293125079587/elastic/elastic-agent/internal/pkg/agent/application/upgrade/marker_access_test.go:124 +0x3ae
>   | created by github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade.watchFileNotEmpty
>   | C:/buildkite-agent/builds/bk-agent-prod-gcp-1704207293125079587/elastic/elastic-agent/internal/pkg/agent/application/upgrade/marker_access_test.go:91 +0x20f
> ```

**Comment by aleksmaus** [comment]
> Looking at this build, I'm not seeing `TestMarkerWatcher` failing.

think you see the ```TestMarkerWatcher``` failing because the panic in Go routine that started in ```TestWriteMarkerFileWithTruncation``` just happens when the ```TestMarkerWatcher``` started running.

**Comment by aleksmaus** [comment]
Can catch the race easily if you change the code to send the error later in the ```watchFileNotEmpty```

https://github.com/aleksmaus/elastic-agent/blob/main/internal/pkg/agent/application/upgrade/marker_access_test.go#L92

for example:
```
	// Watch file
	go func() {
		defer func() {
			errCh <- fmt.Errorf("misc err")
		}()
		defer watcher.Close()
		for {
```

This shows that the Go routine is still running while main the test exited closing the ```errCh``` at the end
