### ISSUE TITLE
Flaky Test TestWatcher_AgentErrorQuick

### ISSUE THREAD

**Issue by blakerouse** [elastic/elastic-agent#3983]
## Flaky Test

* **Test Name:** TestWatcher_AgentErrorQuick
* **Link:** https://github.com/elastic/elastic-agent/blob/1ee9cc7ca9d88d676ab3124f1f57b2013ed17a9c/internal/pkg/agent/application/upgrade/watcher_test.go#L272
* **Branch:** https://github.com/elastic/elastic-agent/pull/3929
* **Artifact Link:** https://buildkite.com/elastic/elastic-agent/builds/5878#018ccaab-6c69-4278-bc10-75b8addcc2d2

### Stack Trace

```
=== Failed
--
  | === FAIL: internal/pkg/agent/application/upgrade TestWatcher_AgentErrorQuick (0.44s)
  | watcher_test.go:316:
  | Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1704207293125543414/elastic/elastic-agent/internal/pkg/agent/application/upgrade/watcher_test.go:316
  | Error:      	Received unexpected error:
  | agent reported failed state: force failure
  | Test:       	TestWatcher_AgentErrorQuick
  | Messages:   	error should not have been reported
```

**Comment by AndersonQ** [comment]
I've been trying to reproduce the issue, but no luck so far. I even let it running, just this test, for 12h straight (see below) and not even a single time i failed.

I was looking at the code and I don't see any logical error. It can happen the 2nd status arrives after the checkinInterval, and therefore the error is reported:

https://github.com/elastic/elastic-agent/blob/b4fe634d7091c6fa114822b7de075ec26328ac09/internal/pkg/agent/application/upgrade/watcher.go#L113-L119

however, 1) it's expected 2) it needs a rather slow run of the test for that to happen.

My test runs

```
❯ go test -count 2 -run TestWatcher_AgentErrorQuick -timeout=0
PASS
ok      github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade 2.697s
 ~/devel/github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade   3983-falky-T…ntErrorQuick !1 ?4  16:01:37                                      5.145s ainsoph@mac 
❯ go test -count 1000 -run TestWatcher_AgentErrorQuick -timeout=0
PASS
ok      github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade 1003.159s
 ~/devel/github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade   3983-falky-T…ntErrorQuick !1 ?4  16:18:33                                     16m 44s ainsoph@mac 
❯ go test -count 5000 -run TestWatcher_AgentErrorQuick -timeout=0
PASS
ok      github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade 5014.285s
 ~/devel/github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade   3983-falky-T…ntErrorQuick !1 ?4  18:11:06                                  1h 23m 37s ainsoph@mac 
❯ go test -count 43200 -run TestWatcher_AgentErrorQuick -timeout=0
PASS
ok      github.com/elastic/elastic-agent/internal/pkg/agent/application/upgrade 43320.474s
```

So, all in all, I believe printing the watcher logs on failure and improving the logs on the watcher run and waiting for another failure is the best option here
