### ISSUE TITLE
[Fleet]:Windows Agent is terminated after taskkill command and agent goes Unhealthy

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/elastic-agent#404]
**Kibana version**: 8.2 BC-4 Kibana cloud environment

**Host OS and Browser version**: All, All

**Build details:**

VERSION: 8.2.0
BUILD: 52005
COMMIT: 9a5003d
Artifact Link: https://staging.elastic.co/8.2.0-3b2b9b86/summary-8.2.0.html

**Preconditions:**

- 8.2 BC4 Kibana cloud environment should be available.
- Windows Agent should be installed with policy having System and Endpoint Security

**Steps to reproduce:**
1. Login to Kibana environment.
2. Open CMD in Admin mode.
3. Trigger tasklist command.
4. Run `taskkill /f /pid <elastic-agent_pid>.
5. Observe Agent is terminated.

**Expected Result:**
-Windows Agent should not be terminated after taskkill command and agent should remain healthy

**Screenshots:**
![image](https://user-images.githubusercontent.com/102019374/166453587-9aa2d782-1976-4d16-8069-cafedb919109.png)
![image](https://user-images.githubusercontent.com/102019374/166453668-051fa857-c45e-4d39-a1f3-e0e995002cd3.png)

**Note:**
- This issue is not reproducible on latest 8.2 Snapshot
![image](https://user-images.githubusercontent.com/102019374/166454368-94902ad9-7ac5-46e6-9f1d-f70dfdd5a3fb.png)

Build Details for 8.2 Snapshot
BUILD: 52069
COMMIT: 88821b0c5d705511c63827de6927e3bf8936c4ae

**Comment by simranvaseer-qasource** [comment]
Hi @bjmcnic 
Thanks for the required information. We will implement this information in the future while reporting such type of bugs.

**Comment by simranvaseer-qasource** [comment]
Hi @bjmcnic 

Thanks for the required information. We will implement this information in the future while reporting such type of bugs.

**Comment by simranvaseer-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on 7.17.4 BC-1, 8.2.1 BC-1 and 8.3 snapshot and had below observations:

- For 7.17.4 BC-1 and 8.3 Snapshot, this issue is not reproducible. `Access denied` error is observed on killing agent service.
- For 8.2.1 BC-1, this issue is still reproducible.

**Build details:**
For 7.17.4 BC1
BUILD: 46909
COMMIT: a408358a8fc5671f5eb7985678a1733684441b37

For 8.2.1 BC1
BUILD: 52170
COMMIT: 88889128ccda6f7e13983b0087e9aaa183818473

**Screenshots:**
7.17.4 BC1
![image](https://user-images.githubusercontent.com/102019374/169280650-de10bfb5-e155-44cd-99df-f56e9c1a2c7b.png)

8.3 Snapshot
![image (1)](https://user-images.githubusercontent.com/102019374/169280701-ae0597f1-0257-4aa4-b73e-1149e6eb33ef.png)

8.2.1 BC1
![image](https://user-images.githubusercontent.com/102019374/169286342-8099d04e-1b70-4898-82db-f7cb4364d308.png)

Please let us know if anything required from our end.
Thanks

**Comment by bjmcnic** [comment]
Grabbing the [Agent](https://staging.elastic.co/8.2.1-be579146/downloads/beats/elastic-agent/elastic-agent-8.2.1-windows-x86_64.zip) off this [page](https://staging.elastic.co/8.2.1-be579146/summary-8.2.1.html), it appears it's the same situation as I documented above.  Agent is not signed, Endpoint is signed:

![Screen Shot 2022-05-19 at 8 52 43 AM](https://user-images.githubusercontent.com/3613004/169297756-ac57a35d-db37-458e-adab-8cf78fcdfebf.png)
.

**Comment by ph** [comment]
@mgreau or @mdelapenya the elastic agent from staging should be signed too no?

**Comment by dikshachauhan-qasource** [comment]
Hi @jlind23 

As per us, there is a bug and **only reproducible on 8.2.0 released  and latest patch 8.2.1 BC build**. However, its working fine on other agent versions such as 7.17.x or latest 8.3.0 Snapshot.

So, we are expecting a fix for this on 8.2.0 released and latest patch 8.2.1 BC build.

We just only need a signed agent artifact on 8.2.0 released and latest patch 8.2.1 BC build, as @bjmcnic has confirmed about issue. This might fix the above. 

Could you please check with this.

Thanks
QAS

**Comment by jlind23** [comment]
Hi @dikshachauhan-qasource 
I may have missed something, the problem is coming from the agent binary not being signed which means that the "bug" fix is a ci fix instead, correct?

**Comment by jlind23** [comment]
@mgreau @mdelapenya could you please answer ph comment: https://github.com/elastic/elastic-agent/issues/404#issuecomment-1131679191

**Comment by simranvaseer-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.3 BC3 Kibana cloud staging environment and found it **fixed** now.
- `Access denied` error is observed on killing agent service.

**Build details:**
Version: 8.3.0 BC3
BUILD: 53272
COMMIT: 7a0df2bca36ced2a898420cbb193a9dba0782a7a

**Screenshot:**
![Capture](https://user-images.githubusercontent.com/102019374/172603673-67ab6477-700c-46b1-ad54-2e3b8ca6a8d7.PNG)

Hence, we are closing this issue and marking it as QA:Validated.

Further we will keep track of this issue in future builds.

Thanks
