### ISSUE TITLE
Cannot send `+Inf` download rate to Fleet API in `upgrade_details.metadata.download_rate` double JSON field in check-in API request

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#4041]
When upgrading Agent via Fleet, I noticed the following warning in the Elastic Agent logs:

```
{"log.level":"warn","@timestamp":"2024-01-08T17:30:45.639Z","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":193},"message":"Possible transient error during checkin with fleet-server, retrying","log":{"source":"elastic-agent"},"error":{"message":"status code: 500, fleet-server returned an error: BadRequest, message: failed to update upgrade_details: elastic fail 400: document_parsing_exception: [1:3872] failed to parse field [upgrade_details.metadata.download_rate] of type [double] in document with id '92df91f9-aa51-4279-9d9c-cef6dabb3f04'. Preview of field's value: '+Inf bps': number_format_exception: For input string: \"+Inf bps\""},"request_duration_ns":1072107250,"failed_checkins":2,"retry_after_ns":217255338807,"ecs.version":"1.6.0"}
```

**Comment by cmacknz** [comment]
That looks like an ES mapping error, I don't think the ES mapping for double accepts +Inf as implied by the "restricted to finite values" in: https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html

> A double-precision 64-bit IEEE 754 floating point number, restricted to finite values.

Is `download_rate` optional? If so when we hit `+Inf` the easiest fix might be to just omit it. Once we hit `+Inf` I don't think we are actually downloading anymore, correct? `+Inf` doesn't mean anything useful to a user here anyway.

**Comment by ycombinator** [comment]
Yes, `download_rate` is optional.  We hit `+Inf` when the download completes very fast. So yes, the download is complete at that point and reporting the download rate to the user as a progress indicator is not useful. ++ to detecting `+Inf` and just omitting it.

**Comment by cmacknz** [comment]
Will put a PR with that change shortly. Looks like this causes the checkin to fail so want to avoid releasing this problem.
