### ISSUE TITLE
Mac: Multiple images of the same machine are displayed when the mac machine reboots after installing agent with --delay-enroll parameter

### ISSUE THREAD

**Issue by muskangulati-qasource** [elastic/elastic-agent#4077]
**Kibana Build details:**
```
VERSION: 8.12.0 BC5
BUILD: 70053
COMMIT: db9b8921b37139cbb1e11d23f6381f655edeb72b
```

**Host OS:**  MacOS

**Preconditions:**
1. 8.12.0 BC5 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Run agent install command with `--delay-enroll` on MacOS
2. Restart the VM and re-access the VM.
3. Observe that multiple images of the same machine are displayed when the machine reboots after installing agent with --delay-enroll parameter

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/60252716/1e1d88de-8b1f-4422-83c2-6bd71aec0a51

**Expected Result:**
Agent service should get started and only a single host should be available under Agents tab on reboot when installed with `--delay-enroll` with healthy status

**Previously observed:**
https://github.com/elastic/elastic-agent/issues/3961

**Logs:**
No agent logs are available.

**Comment by cmacknz** [comment]
BC6 should have the commit that fixes this, https://github.com/elastic/elastic-agent/commit/3ba0362952dcb002b126ad744bbfe3ecee9496d5

This is not in BC5 which is at https://github.com/elastic/elastic-agent/commits/8744ca087b3908495b0204e6c80dd9b4de92ccf5

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.12.0 BC6 kibana cloud environment and found it **fixed now**.

**Observations:**
-  Agent gets installed successfully under Fleet when installed with `--delay-enroll`.

**Build details:**
VERSION: 8.12.0 BC6
BUILD: 70088
COMMIT: e9092c0a17923f4ed984456b8a5db619b0a794b3
Artifact Link: https://staging.elastic.co/8.12.0-3eba7f46/summary-8.12.0.html

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/80d81b68-bb24-4346-b022-8b38a2d81797)


Hence we are **closing** this issue and marking as **QA:Validated**.

Thanks!

**Comment by harshitgupta-qasource** [comment]
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/149945

Thanks
