### ISSUE TITLE
Agent should collect and report CPU and memory usage of monitoring components 

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#4082]
Currently, Agent is only collecting and, therefore, reporting CPU and memory usage for itself and it's non-monitoring Beats components.  It is not collecting and reporting CPU and memory usage for the monitoring Beats, leading to undercounting.

So, for a default Fleet policy with the system integration and monitoring (logs and metrics both) enabled, Agent runs:
* 1 metricbeat instance for the system integration: `system/metrics-default`, 
* 1 filebeat instance for the system integration: `log-default`,
* 2 metricbeat instances for metrics monitoring: `http/metrics-monitoring` and `beat/metrics-monitoring`, and 
* 1 filebeat instance for logs monitoring: `filestream-monitoring`.

In the above scenario, Agent is currently only collecting and reporting CPU and memory usage for the metricbeat and filebeat instances for the system integration: `system/metrics-default` and `log-default`.  It is not collecting and reporting CPU and memory usage for the metricbeat and filebeat instances for monitoring: `http/metrics-monitoring`, `beat/metrics-monitoring`, and `filestream-monitoring`.

**Comment by ycombinator** [comment]
> @ycombinator when you say "collect and report" what are you imagining? We make sure metrics for these end up in the `last 30s` log lines? Something else?

I meant collect and report monitoring metrics of the monitoring beats' resource usage the same way we do today for any non-monitoring beats.  The issue description has an example that should help clarify things further, but let me know if it doesn't.

**Comment by fearful-symmetry** [comment]
@ycombinator I think we're on different pages here. So, the `last 30s` metrics for the monitoring beats are exposed via the agent logs:
```
grep -rh "last 30s" . | jq .component.id
"filestream-monitoring"
"system/metrics-default"
"beat/metrics-monitoring"
"http/metrics-monitoring"
"filestream-monitoring"
"system/metrics-default"
"beat/metrics-monitoring"
"http/metrics-monitoring"
"filestream-monitoring"
"system/metrics-default"
"beat/metrics-monitoring"
"http/metrics-monitoring"
"filestream-monitoring"
"system/metrics-default"
"beat/metrics-monitoring"
"http/metrics-monitoring"
"filestream-monitoring"
```

What specific monitoring interface or UX are you thinking of here? The Kibana/fleet agent resource usage GUI? Something else?

**Comment by ycombinator** [comment]
> What specific monitoring interface or UX are you thinking of here? The Kibana/fleet agent resource usage GUI? Something else?

<img width="1277" alt="Screenshot 2024-02-13 at 10 22 39" src="https://github.com/elastic/elastic-agent/assets/51061/2a421017-6b0d-4906-aefa-7814fb48b42b">

Currently, the circled metrics do not include resource usage for the monitoring beats themselves.  This results in undercounting the resources being used by Agent and all it's component processes. See https://github.com/elastic/elastic-agent/pull/4005#discussion_r1449239237 for background discussion that led to this (and a few other) issues.

**Comment by cmacknz** [comment]
Re-opening, this was reverted because the test was failing https://github.com/elastic/elastic-agent/pull/4451

**Comment by pierrehilbert** [comment]
@fearful-symmetry I think we can close this one now that https://github.com/elastic/elastic-agent/pull/4462 is merged right?
