### ISSUE TITLE
HTTP Downloader leaves a file even when the download fails

### ISSUE THREAD

**Issue by belimawr** [elastic/elastic-agent#409]
When the HTTP donwloader is downloading a file it first creates the file (and defers the file.Close()), then it tries to download it. The problem is that if the download fails (e.g status code != 200), the file is left empty in the filesystem.

You can see this behaviour on this small snippet: https://github.com/elastic/elastic-agent/blob/552a87d2760297ba2fe9b80e2dfb503d891e8ea4/internal/pkg/artifact/download/http/downloader.go#L159-L173

This generates a small problem because the `operationFetch` tries to find out if the file already exists, it only checks if the file exists, if so it skips downloading: https://github.com/elastic/elastic-agent/blob/552a87d2760297ba2fe9b80e2dfb503d891e8ea4/internal/pkg/agent/operation/operation_fetch.go#L56-L62

I believe it is not causing any major problems because later on trying to unzip or check its integrity will fail (probably leading to a re-download). Nevertheless we should look into fixing this issue.

**Comment by matschaffer** [comment]
I ran into this attempting an upgrade of my local (macOS) 8.3.1 agent to 8.3.3. My log was:

```
11:57:12.926
elastic_agent
[elastic_agent][info] 2022-08-18T11:57:12+09:00 - message: Application: [e2ca571c-fa82-47f6-ae5d-d207e229e434]: State changed to UPDATING: Update to version '8.3.3' started - type: 'STATE' - sub_type: 'UPDATING'
11:57:14.035
elastic_agent
[elastic_agent][error] 2022-08-18T11:57:14+09:00 - message: Application: [e2ca571c-fa82-47f6-ae5d-d207e229e434]: State changed to FAILED: failed verification of agent binary: 2 errors occurred:
	* checksum for "elastic-agent-8.3.3-darwin-x86_64.tar.gz" was not found in "/Library/Elastic/Agent/data/elastic-agent-190a5b/downloads/elastic-agent-8.3.3-darwin-x86_64.tar.gz.sha512"
	* checksum for "elastic-agent-8.3.3-darwin-x86_64.tar.gz" was not found in "/Library/Elastic/Agent/data/elastic-agent-190a5b/downloads/elastic-agent-8.3.3-darwin-x86_64.tar.gz.sha512"

 - type: 'ERROR' - sub_type: 'FAILED'
11:57:14.035
elastic_agent
[elastic_agent][error] failed to dispatch actions, error: failed verification of agent binary: 2 errors occurred:
	* checksum for "elastic-agent-8.3.3-darwin-x86_64.tar.gz" was not found in "/Library/Elastic/Agent/data/elastic-agent-190a5b/downloads/elastic-agent-8.3.3-darwin-x86_64.tar.gz.sha512"
	* checksum for "elastic-agent-8.3.3-darwin-x86_64.tar.gz" was not found in "/Library/Elastic/Agent/data/elastic-agent-190a5b/downloads/elastic-agent-8.3.3-darwin-x86_64.tar.gz.sha512"

11:57:14.036
elastic_agent
[elastic_agent][error] Elastic Agent status changed to: 'error'
12:02:01.426
elastic_agent
[elastic_agent][info] Elastic Agent status changed to: 'online'
```

The upgrade just failed at that point. The validation failure didn't seem to trigger a re-download.

To work around it I did this (as root):

```
rm /Library/Elastic/Agent/data/elastic-agent-190a5b/downloads/elastic-agent-*
```

**Comment by jlind23** [comment]
Closing this as fixed, feel free to reopen it if need be.
