### ISSUE TITLE
Elastic agent version 8.11.2 upgrade with agent binary download through proxy failed

### ISSUE THREAD

**Issue by DysonHo** [elastic/elastic-agent#4151]
**Kibana Build details:**
```
VERSION: 8.11.3
```
**note:**
- IP: `192.168.1.115:9330` is my lab fleet server and service port
- the host OS which elastic agent install: Windows 10 pro

**Describe the bug:**
following the official doc：https://www.elastic.co/guide/en/fleet/current/fleet-agent-proxy-managed.html
I simulate a environment that the Elastic agent can only communicate to fleet、elasticsearch and upgrade through proxy,
control and data traffic is fine, I can manage elastic agent with fleet, and receive data, also.
but when I try to upgrade elastic agent(v8.11.2), it failed.

I configure the elastic agent log level to "debug" and re-upgrade to find out what's going on:
- upgrade test 1, I got 2 error：
```
11:16:04.214 elastic_agent [elastic_agent][warn] Skipped remote PGP located at "https://192.168.1.115:9330/api/agents/upgrades/8.11.3/pgp-public-key" because it's unavailable: 2 errors occurred:
* Get "https://192.168.1.115:9330/api/agents/upgrades/8.11.3/pgp-public-key": tls: failed to verify certificate: x509: certificate signed by unknown authority
* Remote PGP download failed
11:16:04.687 elastic_agent [elastic_agent][error] upgrade to version 8.11.3 failed: failed verification of agent binary: 2 errors occurred:
* fetching asc file from 'C:\Program Files\Elastic\Agent\data\elastic-agent-1c21b0\downloads\elastic-agent-8.11.3-windows-x86_64.zip.asc': open C:\Program Files\Elastic\Agent\data\elastic-agent-1c21b0\downloads\elastic-agent-8.11.3-windows-x86_64.zip.asc: The system cannot find the file specified.
* fetching asc file from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.11.3-windows-x86_64.zip.asc: failed loading public key: Get "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.11.3-windows-x86_64.zip.asc": dial tcp: lookup artifacts.elastic.co: no such host
```
accroding to official doc：https://www.elastic.co/guide/en/fleet/8.11/release-notes-8.11.0.html#bug-fixes-8.11.0
I know there is a mechanism elastic agent will download pgp key from fleet if the GPG URL is unreachable, and also it seems a name lookup problem, therefore I install the root CA on the host which I install elastic agent, and also resolve name lookup problem, and go on the second upgrade test.
- upgrade test 2, I got 1 error：
```
12:10:50.431 elastic_agent [elastic_agent][error] upgrade to version 8.11.3 failed: failed verification of agent binary: 2 errors occurred:
  * fetching asc file from 'C:\Program Files\Elastic\Agent\data\elastic-agent-1c21b0\downloads\elastic-agent-8.11.3-windows-x86_64.zip.asc': open C:\Program Files\Elastic\Agent\data\elastic-agent-1c21b0\downloads\elastic-agent-8.11.3-windows-x86_64.zip.asc: The system cannot find the file specified.
  * fetching asc file from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.11.3-windows-x86_64.zip.asc: failed loading public key: Get "https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.11.3-windows-x86_64.zip.asc": dial tcp: lookup artifacts.elastic.co: getaddrinfow: The requested name is valid, but no data of the requested type was found.
```
this is where I got stuck now, seems the lookup problem is solved, but got no data, and still download failed,
to make sure there is no misconfigured with network, 
I run powershell cmdlet: invoke-webrequest on the same host which I install elastic agent to download pgp key, it success.

---

I understand this functionality is in beta, but still try to figure out is this my problem or a bug,
if anyone want more detail, please let me know,
sincerely,

**Comment by FlorianHeigl** [comment]
for the record, i had the opportunity to run into what appears the same issue.

```
{"log.level":"warn","@timestamp":"2024-06-30T18:32:20.635+0200","log.origin":{"file.name":"composed/verifier.go","file.line":53},"message":"Verifier failed!","log":{"source":"elastic-agent"},"verifier":"http.verifier","error":{"message":"fetching asc file from https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.12.2-linux-x86_64.tar.gz.asc: failed loading public key: Get \"https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.12.2-linux-x86_64.tar.gz.asc\": context deadline exceeded"},"ecs.version":"1.6.0"}
```

The commonality seems the 8.11.2. version. I'm sure i had previously upgraded those VM's agents from a lower version, but then they just didn't want to make the jump anymore.
I wonder if there's a misleading element in this, the downloads work just the gpg involved stuff seems to not seeing the internetz... I dimly remember that GPG needs to be properly told how to get to the a keyserver through a proxy.

I don't know *if* it needed to access a GPG keyserver or import a new key. It says something like using default key. but it seems *very* likely.

FTR:
The same system can download via proxy using wget and the file + hash work.
