### ISSUE TITLE
[Flaky Test]: TestStandaloneUpgradeUninstallKillWatcher / TestStandaloneDowngradeToSpecificSnapshotBuild / TestStandaloneUpgradeRetryDownload – target version has the same commit hash

### ISSUE THREAD

**Issue by pierrehilbert** [elastic/elastic-agent#4152]
### Failing test case

TestStandaloneUpgradeUninstallKillWatcher / TestStandaloneDowngradeToSpecificSnapshotBuild / TestStandaloneUpgradeRetryDownload

### Error message

target version has the same commit hash

### Build

https://buildkite.com/elastic/elastic-agent/builds/6583

### OS

Linux, Windows

### Stacktrace and notes

```markdown
Stacktrace: 
=== RUN   TestStandaloneUpgradeUninstallKillWatcher
    fetcher.go:91: Using existing artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip
    fixture.go:261: Extracting artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUninstallKillWatcher2473922599\001
    fixture.go:274: Completed extraction of artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUninstallKillWatcher2473922599\001
    fixture.go:829: Components were not modified from the fetched artifact
    fixture.go:624: >> running binary with: [C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUninstallKillWatcher2473922599\001\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\elastic-agent.exe version --binary-only --yaml]
    fetcher.go:91: Using existing artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip
    fixture.go:261: Extracting artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUninstallKillWatcher2473922599\002
    fixture.go:274: Completed extraction of artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip to C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUninstallKillWatcher2473922599\002
    fixture.go:829: Components were not modified from the fetched artifact
    fixture.go:624: >> running binary with: [C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUninstallKillWatcher2473922599\002\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\elastic-agent.exe version --binary-only --yaml]
    fixture.go:624: >> running binary with: [C:\Users\windows\AppData\Local\Temp\TestStandaloneUpgradeUninstallKillWatcher2473922599\001\elastic-agent-8.13.0-SNAPSHOT-windows-x86_64\elastic-agent.exe version --binary-only --yaml]
    upgrade_uninstall_test.go:67: 
        	Error Trace:	C:/Users/windows/agent/testing/integration/upgrade_uninstall_test.go:67
        	Error:      	Received unexpected error:
        	            	target version has the same commit hash "5f578c5d4cc65371d9a6cee31fb22edf6150960d"
        	Test:       	TestStandaloneUpgradeUninstallKillWatcher
--- FAIL: TestStandaloneUpgradeUninstallKillWatcher (29.37s)
```

**Comment by rdner** [comment]
`TestStandaloneDowngradeToSpecificSnapshotBuild` should have been fixed by https://github.com/elastic/elastic-agent/pull/4095

I'll investigate why it didn't work.

**Comment by rdner** [comment]
Interesting, I'm looking at the `TestStandaloneDowngradeToSpecificSnapshotBuild` test case and there is a log line:

```json
{
  "Time": "2024-01-26T09:36:35.485254967Z",
  "Action": "output",
  "Package": "github.com/elastic/elastic-agent/testing/integration(linux-amd64-ubuntu-2204-upgrade)(sudo)",
  "Test": "TestStandaloneDowngradeToSpecificSnapshotBuild",
  "Output": "    upgrade_downgrade_test.go:105: Testing Elastic Agent upgrade from 8.13.0-SNAPSHOT to 8.13.0-SNAPSHOT+l534sdis...\n"
}
```

So, the target version was `8.13.0-SNAPSHOT+l534sdis` which [according to the artefact API](https://artifacts-api.elastic.co/v1/versions/8.13.0-SNAPSHOT/builds/8.13.0-l534sdis) (`elastic-agent-package` project) has the commit hash `249430b3493fe2ca9ebfde9e72b91b9dd49b2d2e` and the [CI build](https://buildkite.com/elastic/elastic-agent/builds/6583) was triggered for `5f578c5d4cc65371d9a6cee31fb22edf6150960d`

So, the check I introduced in https://github.com/elastic/elastic-agent/pull/4095 passed because of that, but in the upgrader itself here https://github.com/elastic/elastic-agent/blob/b39b9af521fcbf1fcae6bab14762b0a120febdb7/testing/upgradetest/upgrader.go#L220-L222 the hashes are already matching. Something replaced the value on the way. I'll keep looking into it.

**Comment by pierrehilbert** [comment]
Maybe this can be related to our work for releasing Agent faster as we are adding the +buildID there

**Comment by rdner** [comment]
I found 2 possible problems:

### 1. Our fetcher discards the build ID unless `f.snapshotOnly` is `true`:

https://github.com/elastic/elastic-agent/blob/b39b9af521fcbf1fcae6bab14762b0a120febdb7/pkg/testing/fetcher_artifact.go#L66-L84

On line 72 we remove the build suffix and further we use only the version prefix.

We use the fetcher in the fixture like this:

https://github.com/elastic/elastic-agent/blob/b39b9af521fcbf1fcae6bab14762b0a120febdb7/testing/integration/upgrade_downgrade_test.go#L98-L103

### 2. Our artefact cache inside the fixture does not account for the build ID:

For each artefact download we have a log line like this:

```json
{
  "Time": "2024-01-26T09:12:47.267365303Z",
  "Action": "output",
  "Package": "github.com/elastic/elastic-agent/testing/integration(linux-amd64-ubuntu-2204-fleet-airgapped-privileged)(sudo)",
  "Test": "TestFleetAirGappedUpgradePrivileged",
  "Output": "    fetcher_artifact.go:213: Downloading artifact from https://snapshots.elastic.co/8.13.0-ous7zk9j/downloads/beats/elastic-agent/elastic-agent-8.13.0-SNAPSHOT-linux-x86_64.tar.gz\n"
}
```

but there is no log line for downloading `8.13.0-l534sdis` and for `TestStandaloneDowngradeToSpecificSnapshotBuild ` we always have 

```json
{
  "Time": "2024-01-26T09:32:57.4664485Z",
  "Action": "output",
  "Package": "github.com/elastic/elastic-agent/testing/integration(windows-amd64-2022-upgrade)(sudo)",
  "Test": "TestStandaloneDowngradeToSpecificSnapshotBuild",
  "Output": "    fetcher.go:91: Using existing artifact elastic-agent-8.13.0-SNAPSHOT-windows-x86_64.zip\n"
}
```

The test fixture has its own cache for artefacts:

https://github.com/elastic/elastic-agent/blob/b39b9af521fcbf1fcae6bab14762b0a120febdb7/pkg/testing/fixture.go#L799-L807

and it's using a result of the `Name()` function as a cache key:

https://github.com/elastic/elastic-agent/blob/b39b9af521fcbf1fcae6bab14762b0a120febdb7/pkg/testing/fetcher.go#L86-L99

which is just a path of the artefact https://github.com/elastic/elastic-agent/blob/b39b9af521fcbf1fcae6bab14762b0a120febdb7/pkg/testing/fetcher_artifact.go#L99-L101

which is eventually just a filename built here:

https://github.com/elastic/elastic-agent/blob/b39b9af521fcbf1fcae6bab14762b0a120febdb7/pkg/testing/fetcher_artifact.go#L83

**Comment by rdner** [comment]
To summarise: our fetcher and cache don't support a build suffix. This means that every test that requests a certain build version would fetch the latest version snapshot instead.

I suppose the tests reported by this issue are such tests that work with build IDs.

I'm working on a fix.

**Comment by rdner** [comment]
`TestStandaloneUpgradeRetryDownload` and `TestStandaloneUpgradeUninstallKillWatcher` are still failing because they don't select a proper snapshot as `TestStandaloneDowngradeToSpecificSnapshotBuild` does. Working on the fix.
