### ISSUE TITLE
how can i change the log level of fleet-managed agent to debug?

### ISSUE THREAD

**Issue by wawa8900** [elastic/elastic-agent#4162]
how can i change the log level of fleet-managed agent to debug?
i changed the local elastic-agent.yml, added [agent.logging.level: debug], but didn't work.
thanks very much.

**Comment by pierrehilbert** [comment]
Hello,
You need to change that through the Fleet UI https://www.elastic.co/guide/en/fleet/8.12/monitor-elastic-agent.html#change-logging-level
When the Elastic Agent is managed, we are not taking into account the local config file as the config is now defined through the Fleet Policy.

**Comment by wawa8900** [comment]
thanks very much for your reply.
