### ISSUE TITLE
Elaspic not working

### ISSUE THREAD

**Issue by fernandezl0102** [elastic/elastic-agent#4197]
Elaspic (http://elaspic.kimlab.org/) is not working now. The message listed below shows up all the times I tried to get in.
{"detail":"Not Found"}

**Comment by cmacknz** [comment]
I think you possibly want https://github.com/elaspic/elaspic

**Comment by fernandezl0102** [comment]
"For a small number of mutations, you can try running ELASPIC using our webserver<http://elaspic.kimlab.org/>.". It does not work, but I have used this recently with no problems.

?

Jose L Fernandez-Luna

Head, Genetics Department

Valdecilla University Hospital

Santander, Spain

________________________________
De: Craig MacKenzie ***@***.***>
Enviado: martes, 6 de febrero de 2024 15:21
Para: elastic/elastic-agent
Cc: FERNANDEZ LUNA, JOSE LUIS; Author
Asunto: Re: [elastic/elastic-agent] Elaspic not working (Issue #4197)

ATENCIÓN: Este correo es externo al Servicio Cántabro de Salud. No haga click en enlaces, ni abra archivos adjuntos, ni mande información sin confirmar que el remitente es seguro.

I think you possibly want https://github.com/elaspic/elaspic

-

**Comment by pierrehilbert** [comment]
Hello @fernandezl0102,
You are not on the correct repository as @craig-abbott highlighted it.
You should open an issue on https://github.com/elaspic/elaspic

**Comment by fernandezl0102** [comment]
The search for mutations in the elaspic webserver was fast and intuitive and gave you rapid visual results. Unfortunately, this is not working and I find the way you mention too complicated. It is a pity.

?

________________________________
De: Pierre HILBERT ***@***.***>
Enviado: miércoles, 7 de febrero de 2024 8:12
Para: elastic/elastic-agent
Cc: FERNANDEZ LUNA, JOSE LUIS; Mention
Asunto: Re: [elastic/elastic-agent] Elaspic not working (Issue #4197)

ATENCIÓN: Este correo es externo al Servicio Cántabro de Salud. No haga click en enlaces, ni abra archivos adjuntos, ni mande información sin confirmar que el remitente es seguro.

Hello @fernandezl0102<https://github.com/fernandezl0102>,
You are not on the correct repository as @craig-abbott<https://github.com/craig-abbott> highlighted it.
You should open an issue on https://github.com/elaspic/elaspic

-

**Comment by pierrehilbert** [comment]
Please consider reading our messages if you are expecting to get some answer from the product's developers.
