### ISSUE TITLE
Datasets `system.auth` and `system.syslog` are not available for AL2023 under Data streams tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#4250]
**Kibana Build details:**
```
VERSION: 8.13.0 SNAPSHOT
BUILD: 71393
COMMIT: 4f3bc35472dfeb88c02466790bd3c96dcc98f4de
Artifact Link: https://snapshots.elastic.co/8.13.0-e2cda7bd/downloads/beats/elastic-agent/elastic-agent-8.13.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Host OS:**  Amazon Linux 2023(AL2023)

**Preconditions:**
1. 8.13.0 SNAPSHOT Kibana cloud environment should be available.

**Steps to reproduce:**
1. Install agent on AL2023 with agent policy having System integration.
2. Navigate to Data streams tab and observe no data available for `system.auth and system.syslog` datasets.

**Screenshots:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/e24645a6-bbe8-44b7-a0dc-d17d0953baf8)

**Expected Result:**
Datasets `system.auth and system.syslog` should be available for AL2023 under Data streams tab.

**Testing Under:**
https://github.com/elastic/ingest-dev/issues/2942

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by pierrehilbert** [comment]
Will be covered by https://github.com/elastic/beats/issues/37086

**Comment by belimawr** [comment]
While https://github.com/elastic/beats/issues/37086 paves the path to close this issue, it is also needed to update the system integration to use the journald input on hosts that have moved away from traditional log files.

**Comment by nimarezainia** [comment]
@belimawr is this also resolved by https://github.com/elastic/integrations/pull/11618 ?  I would like to get the AL2023 qualified.

**Comment by amolnater-qasource** [comment]
Hi Team,
We have revalidated this issue on latest 8.17.0 BC6 kibana cloud environment and found it **fixed now**.

**Observations:**
- Datasets `system.auth` and `system.syslog` is available for AL2023 under Data streams tab.

**Screenshots:**
![Image](https://github.com/user-attachments/assets/00715036-0c39-470f-9ad1-7a0cbbfc7c4d)

**Build details:**
VERSION: 8.17.0 BC6
BUILD: 80521
COMMIT: e8a820624a03a412433584d3e3df951838e4c63c
Artifact Link: https://staging.elastic.co/8.17.0-6b31e673/downloads/beats/elastic-agent/elastic-agent-8.17.0-linux-x86_64.tar.gz

Hence we are **closing** and marking this issue as **QA:Validated**.

Thanks!
