### ISSUE TITLE
The versions used in upgrade integration tests should be driven by a configuration file

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#4296]
The available set of versions for use in our upgrade integration tests is currently discovered dynamically using the artifacts API. https://github.com/elastic/elastic-agent/blob/b425e4fc8cc1b5f2ef9a4bac74055927ca14b4a4/testing/upgradetest/versions.go#L38-L53

This approach has been a common source of problems for several reasons:

1. The set of available versions changes relatively frequently as new minor and patch releases move from feature freeze to official release.
2. The artifacts API will return release build candidates as upgradable, but they are only available  from staging.elastic.co which is not and should not be a source URI that is supported by default in the agent. See https://github.com/elastic/elastic-agent/issues/3944.
3. Dynamically discovering the version creates the risk that a bug in the version discovery logic or the artifacts API causes us to unintentionally skip or change the set of versions we test against. The worst case scenario would be accidentally skipping the 7.17 upgrade tests leading to a broken upgrade process for older agents. Today our versions are selected dynamically in several places without assertions that the expected set of versions was returned, for example https://github.com/elastic/elastic-agent/blob/b425e4fc8cc1b5f2ef9a4bac74055927ca14b4a4/testing/integration/upgrade_standalone_test.go#L36-L37.

We should instead define the versions available for use in upgrade tests in a static configuration file so that running the tests has no dependency on dynamic version discovery or the artifacts API. 

We should move the version discovery logic into a periodic GitHub action or buildkite job that creates a PR to update the set of upgradable versions as new versions are made available. The file content should at minimum include:
* The release version number e.g. 8.12.0, 8.13.0-SNAPSHOT
* The source URI the artifacts can be downloaded from e.g. artifacts.elastic.co, staging.elastic.co, etc.
* Including the snapshot build ID should be possible but implementation can be left as a future exercise, where we automatically bump the snapshot build ID to use in tests as new snapshots become available.

**Comment by rdner** [comment]
@pchila how would it affect your work on https://github.com/elastic/elastic-agent/issues/2579 ?

Should I start making these changes now or should I wait until the transition is over?

**Comment by pchila** [comment]
While I don't like the idea of one more file we need to bump periodically, this should not affect my work on #2579 since it's already been merged and it will work like all the other upgrade tests

**Comment by rdner** [comment]
I found 14 tests that perform an upgrade/downgrade:

Here is a one-liner that you can run in the `./testing` directory:

```bash
(find . -type f -name '*.go' -exec grep -oh --null -e 'Test.*Upgrade\w*' \{\} + && find . -type f -name '*.go' -exec grep -oh --null -e 'Test.*Downgrade\w*' \{\} +) | sort -u
```


| Test Case | Used versions | Relative to 8.13-SNAPSHOT |
|-----------|---------------|------------------|
| [TestFleetAirGappedUpgradePrivileged](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_fleet_test.go#L118) | `define.Version() => define.Version()` | `8.13-SNAPSHOT => 8.13-SNAPSHOT` |
| [TestFleetAirGappedUpgradeUnprivileged](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_fleet_test.go#L106) | `define.Version() => define.Version()` | `8.13-SNAPSHOT => 8.13-SNAPSHOT` |
| [TestFleetManagedUpgradePrivileged](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_fleet_test.go#L56) | `define.Version() => define.Version()-SNAPSHOT` | `8.13-SNAPSHOT => 8.13-SNAPSHOT` |
| [TestFleetManagedUpgradeUnprivileged](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_fleet_test.go#L42) | `define.Version() => define.Version()-SNAPSHOT` | `8.13-SNAPSHOT => 8.13-SNAPSHOT` |
| [TestStandaloneDowngradeToSpecificSnapshotBuild](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_downgrade_test.go#L27) | `define.Version() => define.Version()-SNAPSHOT+<lastBuildID~2>` | `8.13-SNAPSHOT => 8.13-SNAPSHOT+buildID` |
| [TestStandaloneUpgrade](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_standalone_test.go#L26) | `GetUpgradableVersions(ctx, define.Version(), 2, 1) => define.Version()` | |
| [TestStandaloneUpgradeFailsWhenUpgradeIsInProgress](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_standalone_inprogress_test.go#L28) | `PreviousMinor => define.Version()` | `8.12.2 => 8.13.0-SNAPSHOT` |
| [TestStandaloneUpgradeRetryDownload](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_standalone_retry_test.go#L32) | `define.Version() => define.Version()-SNAPSHOT+<lastBuildID>` | `8.13-SNAPSHOT => 8.13-SNAPSHOT+buildID` |
| [TestStandaloneUpgradeRollback](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_rollback_test.go#L42) | `PreviousMinor=>define.Version()` | `8.12.2 => 8.13.0-SNAPSHOT` |
| [TestStandaloneUpgradeRollbackOnRestarts](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_rollback_test.go#L157) | `PreviousMinor => define.Version()` | `8.12.2 => 8.13.0-SNAPSHOT` |
| [TestStandaloneUpgradeUninstallKillWatcher](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_uninstall_test.go#L27) | `define.Version()-SNAPSHOT+<buildID> => define.Version()` | `8.13-SNAPSHOT+buildID => 8.13-SNAPSHOT` |
| [TestStandaloneUpgradeWithGPGFallback](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_gpg_test.go#L25) | `define.Version() => define.Version()-SNAPSHOT` | `8.13-SNAPSHOT => 8.13-SNAPSHOT` |
| [TestStandaloneUpgradeWithGPGFallbackOneRemoteFailing](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_gpg_test.go#L89) | `define.Version() => PreviousMinor` | `8.13.0-SNAPSHOT => 8.12.2` |
| [TestUpgradeBrokenPackageVersion](https://github.com/elastic/elastic-agent/blob/2eecafb1ad273623257d3b51604091bce5d1f169/testing/integration/upgrade_broken_package_test.go#L28) | `define.Version() => PreviousMinor` | `8.13.0-SNAPSHOT => 8.12.2` |

So, the common patterns are:

* `define.Version() => define.Version()`
* `define.Version() => define.Version()-SNAPSHOT`
* `define.Version() => PreviousMinor`
* `PreviousMinor => define.Version()`
* `define.Version() => define.Version()-SNAPSHOT+<lastBuildID>`
* `define.Version() => define.Version()-SNAPSHOT+<lastBuildID~2>`
* `GetUpgradableVersions(ctx, define.Version(), 2, 1) => define.Version()`

**Comment by rdner** [comment]
We had a discussion with the team and agreed on the following points:

* We create a Github flow that creates a PR that updates a version configuration file
* We start with release versions (the file does not contain buildID versions)
