### ISSUE TITLE
Review agent's upgrade tests and change used versions if necessary

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4320]
All the preliminary research was done here https://github.com/elastic/elastic-agent/issues/4296#issuecomment-1959624832

We should review all our current upgrade tests and decide whether using the versions they use actually makes sense.

The goal is to minimize the amount of different versions used for testing, we currently have:

* `define.Version() => define.Version()`
* `define.Version() => define.Version()-SNAPSHOT`
* `define.Version() => PreviousMinor`
* `PreviousMinor => define.Version()`
* `define.Version() => define.Version()-SNAPSHOT+<lastBuildID>`
* `define.Version() => define.Version()-SNAPSHOT+<lastBuildID~1>`
* `GetUpgradableVersions(ctx, define.Version(), 2, 1) => define.Version()`

FYI: versions returned from `GetUpgradableVersions()` and `PreviousMinor()` are stable/deterministic and configured by a file.

**Comment by rdner** [comment]
I noticed that the following test cases request a build version:

### TestStandaloneUpgradeRetryDownload

https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/testing/integration/upgrade_standalone_retry_test.go#L51-L53

### TestStandaloneUpgradeUninstallKillWatcher

https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/testing/integration/upgrade_uninstall_test.go#L51-L55

From the name of the tests I don't think they should use build versions, what do you think 
@pchila ?

We're trying to minimize the use of the artifact API due to https://github.com/elastic/elastic-agent/issues/4268 so I'd just use the current snapshot and skip the test when commit hashes match.

**Comment by pchila** [comment]
> I noticed that the following test cases request a build version:
> ### TestStandaloneUpgradeRetryDownload
> 
> https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/testing/integration/upgrade_standalone_retry_test.go#L51-L53
> 
> ### TestStandaloneUpgradeUninstallKillWatcher
> 
> https://github.com/elastic/elastic-agent/blob/ddd832b4c3a16296ff6d0b2693629de42a375446/testing/integration/upgrade_uninstall_test.go#L51-L55
> 
> From the name of the tests I don't think they should use build versions, what do you think @pchila ?
> 
> We're trying to minimize the use of the artifact API due to #4268 so I'd just use the current snapshot and skip the test when commit hashes match.

I think those test can be changed to use regular snapshots/released versions without any loss of functionality. If the build lookup is just to avoid hash collision we can change them after implementing #4380 and have those tests try to upgrade to latest snapshot for the given version

**Comment by rdner** [comment]
I think further adjustments are no longer necessary. Closing now.
