### ISSUE TITLE
Use snapshot API to download latest snapshot package in integration test and in agent

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#4346]
**Describe the enhancement:**

Instead of using artifact api to get the latest snapshot package we can access it from the same place used in the [DRA report](https://artifacts-staging.elastic.co/dra-info/index.html) which looks like `https://snapshots.elastic.co/latest/master.json` and points to the [manifest of the latest snapshot version](https://snapshots.elastic.co/8.14.0-ca4c9a13/manifest-8.14.0-SNAPSHOT.json) .

We should also convert the call to artifact api `search` in the agent snapshot downloader (we use to download the latest snapshot version)  to the same snapshot-api we use in integration tests
**Describe a specific use case for the enhancement or feature:**

TODO

**What is the definition of done?**
TODO

/cc @rdner @cmacknz

**Comment by rdner** [comment]
Resolved by https://github.com/elastic/elastic-agent/pull/4693
