### ISSUE TITLE
Agent only restarts failed applications once

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#437]
The elastic-agent should restart any application that stays too long on a `FAILED` state. However it's happening only once, on the 1st failure.

When an application goes into `FAILED` state the agent starts a [_failed timer_](https://github.com/elastic/elastic-agent/pull/436/files#diff-b7d30769aecf71cb66dbfb9d8753b0764c1a9fc8f3fcb2c1239893dd0e08b5d0R56), which waits until time is out to restart the application or the timer gets cancelled. From my observations after the first failed-reset cycle the timer gets cancelled "forever", never again reaching its timeout to restart the application.

I did some digging, added some debug logs and it seems that the context used to cancel the timer is reused after its cancellation, therefore from the 2nd application's failure onward the _failed timer_ is always considered cancelled.

- Version: 8.2 / main
- Operating System: All
- Discuss Forum URL: N/A

### Steps to Reproduce:
 - Elastic Agent is running any beat
 - make the beat enter a failed state. A `kill -9` should do the trick. I used [this modified filebeat](https://github.com/elastic/beats/compare/agent-88-collest-beats-stdout-stderr?expand=1#diff-f6a5070af0201945a21fe2fdde7afe7a3203f42b262d4a77c4e8cb34cc9c5b60R27) that "accepts a panic command" and then panics.
 - the agent should restart the application when it first fails, then it won't. You should be able to see [this log entry](https://github.com/elastic/elastic-agent/pull/436/files#diff-b7d30769aecf71cb66dbfb9d8753b0764c1a9fc8f3fcb2c1239893dd0e08b5d0R69) from the 2nd failure onward

**Comment by cmacknz** [comment]
@blakerouse is the behaviour here the same with v2? Or do we still need to consider changing this?

**Comment by blakerouse** [comment]
This is not the case in V2 it will keep restarting it.
