### ISSUE TITLE
[Flaky Test]: TestWaitForWatcher/Runaround_path:_marker_is_jumping_around_and_landing_on_watching  – Received unexpected error: watcher did not start in time  context deadline exceeded

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#4385]
### Failing test case

TestWaitForWatcher

### Error message

watcher did not start in time:  context deadline exceeded

### Build

https://buildkite.com/elastic/elastic-agent/builds/7644#018e1da8-4fc5-495e-8922-98f4a839d52f

### OS

Mac

### Stacktrace and notes

```shell
=== FAIL: internal/pkg/agent/application/upgrade TestWaitForWatcher/Runaround_path:_marker_is_jumping_around_and_landing_on_watching (0.69s)
    upgrade_test.go:856:
        	Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1709894562206733848/elastic/elastic-agent/internal/pkg/agent/application/upgrade/upgrade_test.go:856
        	Error:      	Received unexpected error:
        	            	watcher did not start in time
        	            	context deadline exceeded
        	Test:       	TestWaitForWatcher/Runaround_path:_marker_is_jumping_around_and_landing_on_watching
        	Messages:   	waitForWatcher /tmp/TestWaitForWatcherRunaround_path_marker_is_jumping_around_and_landing_on_watching576010915/001/.update-marker, [UPG_REQUESTED UPG_SCHEDULED UPG_DOWNLOADING UPG_EXTRACTING UPG_REPLACING UPG_RESTARTING UPG_WATCHING], 1ms, 500ms)
=== FAIL: internal/pkg/agent/application/upgrade TestWaitForWatcher (1.78s)
```

It seems that sometimes Mac runner is too slow to manage the update marker within 500ms, will extend the timeout

**Comment by rdner** [comment]
Failed again in https://buildkite.com/elastic/elastic-agent/builds/7660#018e2084-a489-40fb-a47b-b383aa7bcafc

**Comment by pchila** [comment]
Reopening after a new failure on https://buildkite.com/elastic/elastic-agent/builds/7777#018e3c04-3833-49e0-8b69-477f7cff4ae7

**Comment by rdner** [comment]
It's not just Mac OS this time, also Windows https://buildkite.com/elastic/elastic-agent/builds/7778#018e3c3e-af58-4d57-bea6-0b53859aacbf

**Comment by rdner** [comment]
Another failure https://buildkite.com/elastic/elastic-agent/builds/7800#018e5237-9bb2-46ee-919e-a48dd36b4e24

**Comment by rdner** [comment]
Also failed in https://buildkite.com/elastic/elastic-agent/builds/7806#018e5259-864e-4723-b8ba-ad1c4fc0bd28
