### ISSUE TITLE
[Flaky Test]: TestLogIngestionFleetManaged – unable to create policy: Agent Policy '<redacted>' already exists with name 'test-policy-enroll-1710143889'

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4393]
### Failing test case

TestLogIngestionFleetManaged

### Error message

unable to create policy: Agent Policy '<redacted>' already exists with name 'test-policy-enroll-1710143889'

### Build

https://buildkite.com/elastic/elastic-agent/builds/7667#018e2c73-6325-4b6d-a6e7-5e4c99314aff

### OS

Linux

### Stacktrace and notes

```markdown
=== RUN   TestLogIngestionFleetManaged
    logs_ingestion_test.go:58: Enrolling agent in Fleet with a test policy
    logs_ingestion_test.go:89: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/logs_ingestion_test.go:89
        	Error:      	Received unexpected error:
        	            	unable to create policy: Agent Policy 'd9698871-b94d-41ba-9cda-a6cd1d613f02' already exists with name 'test-policy-enroll-1710143889'
        	Test:       	TestLogIngestionFleetManaged
--- FAIL: TestLogIngestionFleetManaged (4.24s)
```

**Comment by rdner** [comment]
Happens on main too https://buildkite.com/elastic/elastic-agent/builds/7763#018e3960-7db8-47ab-830b-56cd7e6e3e3e

```
=== RUN   TestDebLogIngestFleetManaged
    logs_ingestion_test.go:126: Enrolling agent in Fleet with a test policy
    logs_ingestion_test.go:157: 
        	Error Trace:	/home/ubuntu/agent/testing/integration/logs_ingestion_test.go:157
        	Error:      	Received unexpected error:
        	            	unable to create policy: Agent Policy '5b612cdc-040d-42c2-b3fe-98222d73bf24' already exists with name 'test-policy-enroll-1710361822'
        	Test:       	TestDebLogIngestFleetManaged
--- FAIL: TestDebLogIngestFleetManaged (4.36s)
```

**Comment by cmacknz** [comment]
https://github.com/elastic/elastic-agent/blob/6135d60613964712ae7b574f04b4ad112acecba7/testing/integration/logs_ingestion_test.go#L127-L128

We are using the time since epoch in seconds as the policy name, which is not unique if there are two concurrent requests in the same second, which is not unlikely in our test framework given we run multiple tests concurrently on different VMs.

This test should probably use a proper UUID for the policy name.

**Comment by rdner** [comment]
@cmacknz good point, I'll make the change.
