### ISSUE TITLE
AMD64 error is displayed when Elastic Defend added to Windows 2012 R2.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#4395]
**Kibana Build details:**
```
VERSION: 8.13.0
BUILD: 71907
COMMIT: a44ba7e18a1b025d98f9a789f8177c1f5774d04e
ARTIFACT: https://staging.elastic.co/8.13.0-6a2fcd0a/downloads/beats/elastic-agent/elastic-agent-8.13.0-windows-x86_64.zip
```

**Impacted Host:**
- Windows 2012 R2
- Windows 2016
**Preconditions:**
1. 8.13.0 BC4 Kibana Cloud environment should be available.
2. 8.13.0 Windows agent should be installed
3. Elastic Defend should be added to the policy.

**Steps to reproduce:**

1. Navigate to Agents tab.
2. Wait for sometime until agent goes Unhealthy.
3. Navigate to Agent Details tab.
4. Observe that AMD64 error is displayed when Elastic Defend added Windows 2012 R2.

**Expected:**

- AMD64 error is displayed when Elastic Defend is added to Windows 2012 R2 and Windows 2016

**Screenshot:**
![image](https://github.com/elastic/kibana/assets/101545338/b4b6a2d5-86ac-420e-912c-9444ddfc80fe)

**Agents Logs:**
[elastic-agent-diagnostics-2024-03-11T10-50-01Z-00.zip](https://github.com/elastic/kibana/files/14557355/elastic-agent-diagnostics-2024-03-11T10-50-01Z-00.zip)

**Comment by intxgo** [comment]
Hello, Windows 2012 R2 is out of support for 8.13. The last supported on Windows 2012 R2 was Elastic Defend 8.10.x

Regarding the rest of the ticket. Please indicate the testing environment. What was the native Windows architecture, ADM64 or ARM (did you tested it on Apple silicon MacBook, perhaps?)

Does the issue happens for Windows 2016 (supported OS)? Your message is not clear
> Expected:
>
> - AMD64 error is displayed when Elastic Defend is added to Windows 2012 R2 and Windows 2016

**Comment by intxgo** [comment]
Further investigation confirms a bug on Windows 2016.
We cannot reliably detect the native architecture on older systems, before `IsWow64Process2` was introduced, so we return empty string
https://github.com/elastic/go-sysinfo/pull/201/files

The condition in `endpoint-security.spec.yaml` has to account for possible empty `runtime.native_arch` (or check the `runtime.major/minor/build` like in go-sysinfo) to bypass the prevention condition.

For Windows 2012 R2 the incompatibility error would solve it, but the PR didn't make it to 8.13 from what I see
https://github.com/elastic/elastic-agent/pull/4201

**Comment by harshitgupta-qasource** [comment]
Hi @intxgo 

Thank you for looking into this issue.

We have validated this issue on 8.13.0 BC4 Kibana cloud build and also we are getting the same error on windows 2016 VMs.
Kindly find the attached logs 

**Agents Logs:**

[elastic-agent-diagnostics-2024-03-11T12-15-42Z-00.zip](https://github.com/elastic/elastic-agent/files/14558456/elastic-agent-diagnostics-2024-03-11T12-15-42Z-00.zip)

**Screenshot**
- **VM Architecture** 
![image (1)](https://github.com/elastic/elastic-agent/assets/101545338/5621e12c-87d4-4d95-afac-b249257318b0) 

- **Agent Details**
![image](https://github.com/elastic/elastic-agent/assets/101545338/e63b3888-d47d-43ec-8848-48bf479a3f38)

Please let us know if anything else is required from our end.
Thanks

**Comment by intxgo** [comment]
by the way, for reference, the `64-bit` info doesn't say if it's AMD64 or ARM64. To query the relevant information, there are better PS functions, such as `Get-CimInstance -Class CIM_Processor`

The Error which you observe was meant to explain that Elastic Defend cannot be installed for example on ARM64 even if AMD64 processes emulation is provided on that platform.

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have re-validated this issue on the latest 8.13.0 BC7 Kibana cloud environment and found it **fixed now** for both windows 2012 R2 and Window 2016.

Observations:
- AMD64 error is not displayed when Elastic Defend is added to Windows 2012 R2 and Windows 2016

**Build details:**
VERSION: 8.13.0 BC7
BUILD: 72069
COMMIT: 2e3a5cd43e835baa1d596b1aa54735992259ecb9
Artifact: https://staging.elastic.co/8.13.0-6adc3d5d/summary-8.13.0.html#elastic-agent-package

**Screen-Shot:**
- Window 2016
![image](https://github.com/elastic/elastic-agent/assets/101545338/79ce812b-d1da-4c92-9e59-86fd864a42a1)
![image](https://github.com/elastic/elastic-agent/assets/101545338/66f24d2f-1e89-4db3-9511-c3cc7804fb2d)

- Windows 2012 R2
![image](https://github.com/elastic/elastic-agent/assets/101545338/4499e25e-eb1c-4bc0-9dd2-9444f72dd6e5)
![image](https://github.com/elastic/elastic-agent/assets/101545338/d62b4913-bfb6-4b3d-9a6e-6821c4cae6c7)

**Agent Logs**
- Window 2016
[elastic-agent-diagnostics-2024-03-26T07-09-58Z-00.zip](https://github.com/elastic/elastic-agent/files/14754011/elastic-agent-diagnostics-2024-03-26T07-09-58Z-00.zip)

- Windows 2012 R2
[elastic-agent-diagnostics-2024-03-26T07-08-51Z-00.zip](https://github.com/elastic/elastic-agent/files/14753992/elastic-agent-diagnostics-2024-03-26T07-08-51Z-00.zip)


Hence, we are marking this issue as **QA: Validated**.

Thanks
