### ISSUE TITLE
[Flaky Test]: TestCloseChannel/EqualJitterBackoff – Should be false

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#4415]
### Failing test case

TestCloseChannel/EqualJitterBackoff

### Error message

Should be false

### Build

https://buildkite.com/elastic/elastic-agent/builds/7764#018e3888-360a-47b4-b8f1-04255d95d697

### OS

Mac

### Stacktrace and notes

```markdown
=== FAIL: internal/pkg/core/backoff TestCloseChannel/EqualJitterBackoff (0.01s)
    backoff_test.go:35:
        	Error Trace:	/Users/admin/builds/bk-agent-prod-orka-1710345447011028072/elastic/elastic-agent/internal/pkg/core/backoff/backoff_test.go:35
        	Error:      	Should be false
        	Test:       	TestCloseChannel/EqualJitterBackoff
=== FAIL: internal/pkg/core/backoff TestCloseChannel (0.01s)
```

**Comment by cmacknz** [comment]
The initial wait is a random integer in the range (0, 2E9) where the units are ns as those are the underlying units of time.Duration. So the initial wait is plausibly 1 ns some of the time.

https://github.com/elastic/elastic-agent/blob/6135d60613964712ae7b574f04b4ad112acecba7/internal/pkg/core/backoff/equal_jitter.go#L33

The channel is closed before the test executes: https://github.com/elastic/elastic-agent/blob/6135d60613964712ae7b574f04b4ad112acecba7/internal/pkg/core/backoff/backoff_test.go#L31-L36

but it is in the same select as the wait on the initial duration which means the choice of which one executes:

https://github.com/elastic/elastic-agent/blob/6135d60613964712ae7b574f04b4ad112acecba7/internal/pkg/core/backoff/equal_jitter.go#L60-L66

Making the init time longer isn't enough without modifying the code, we'd have to call `NextWait()` a few times or be able to inject the function that selects the initial wait so we can just make it longer.
