### ISSUE TITLE
No data for Standalone agent installed on Centos 9.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#4435]
**Kibana Build details:**
```
VERSION: 8.13.0 BC5
BUILD: 72025
COMMIT: d04713ae6c5fd43086bc488edd406ca50d4b9709
Artifact Link: https://staging.elastic.co/8.13.0-f75ccb77/downloads/beats/elastic-agent/elastic-agent-8.13.0-linux-x86_64.tar.gz
```

**Host OS:**  Centos 9

**Preconditions:**
1. 8.13.0-BC5 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Update elastic-agent.yml.
2. Run elastic-agent install command `sudo ./elastic-agent install`.
3. Observe no data for standalone agent installed on Centos 9.

**Expected Result:**
Data for Standalone agent installed on Centos 9 should be available under Data Streams.

**Logs:**
Unable to collect logs due to error:
![image](https://github.com/elastic/elastic-agent/assets/77374876/f7432cb4-4220-4a08-901a-09fcbcb6bbc3)

We manually copied the Agent.zip available here:
`curl -L -H 'Authorization: b4af88d86816e8bb' -o 'Agent.zip' https://upload.elastic.co/d/64384a2f3317241efb8b6388c69dcb38109806f06ad2911a7a8a64b0fed42ea0`

**Note:**
- Issue is consistently reproducible on different Centos 9 VMs

**What's working fine:**
- No issue is observed on standalone agent installed on SLES15 and data is available under Data Streams tab.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by pierrehilbert** [comment]
Hey @amolnater-qasource
Could you please send us the logs from the Agent?
I'm under the impression the Agent is not running and this is the reason why you can't get the diagnostics.

**Comment by amolnater-qasource** [comment]
Hi @pierrehilbert 

Thank you for looking into this issue.

No agent logs folder is generated under `/home/ec2-user/Elastic/Agent/data/elastic-agent-8.13.0-533443` rest we have copied the possible Elastic/Agent zip is available here:
 `curl -L -H 'Authorization: b4af88d86816e8bb' -o 'Agent.zip' https://upload.elastic.co/d/64384a2f3317241efb8b6388c69dcb38109806f06ad2911a7a8a64b0fed42ea0`

Thanks!

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by pierrehilbert** [comment]
According to me, the Agent is not running.
Could you please check the running processes to verify if the Agent is running?

**Comment by pierrehilbert** [comment]
Glad to have been helpful here and that we don't have any issue at the end.
Thanks @amolnater-qasource
