### ISSUE TITLE
7.17.20 agent remain stuck in Updating state on installing on 8.13.2.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#4537]
**Kibana Build details:**
```
VERSION: 7.17.20
Artifact Link: https://staging.elastic.co/7.17.20-5ef7b3be/summary-7.17.20.html
```

**Note:**
- Issue is consistently reproducible.
- Unable to test this on 7.17.20 due to unavailability of hosted fleet server: https://github.com/elastic/fleet-server/issues/3440

**Host OS:**  Windows, Linux and MAC

**Preconditions:**
1. 8.13.2-BC1 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Install Windows agent running the agent install command.
2. Observe agent remains stuck in updating state under Agents tab.

**Screenshots:**
![3](https://github.com/elastic/elastic-agent/assets/77374876/5fc5cc82-42fa-4056-a0ae-964672bb1f15)
![image](https://github.com/elastic/elastic-agent/assets/77374876/c2c5b924-8e43-41f3-9993-fc99600d2363)

**Expected Result:**
7.17.20 agent should get healthy on installation on 8.13.2.

**Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/14901808/logs.zip)

**Agents.zip:**
[Agent.zip](https://github.com/elastic/elastic-agent/files/14901831/Agent.zip)

**Comment by amolnater-qasource** [comment]
@pierrehilbert Thank you for looking into this.

Please find below agent status screenshot:

![image](https://github.com/elastic/elastic-agent/assets/77374876/550afe55-f79a-4a00-a28b-3f7ec8642291)
![image](https://github.com/elastic/elastic-agent/assets/77374876/fd7d5f4d-9d9e-4c68-981e-a7ec1aec776a)

Please let us know if anything else is required from our end.
Thanks!

**Comment by ycombinator** [comment]
This looks like a legitimate bug.  Agent is trying to download an older version of Filebeat (`7.17.20`) from a newer version URL (`https://staging.elatic.8.13.2-a9f1d716/...`).

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by pierrehilbert** [comment]
@jlind23 Keep me honest here but this has been fixed right?

**Comment by pierrehilbert** [comment]
I just tested it myself and I'm unable to reproduce.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.14.0 SNAPSHOT and found this issue not reproducible.

**Observations:**
- 7.17.20 agent gets Healthy on installing on 8.14.0-SNAPSHOT.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/6b921876-cc79-466d-9eb7-5745dae44675)

**Build details:**
VERSION: 8.14.0 SNAPSHOT
BUILD: 73332
COMMIT: 3f75f6aa5da418e85d03a43e89f0dbb89afe75a2
Artifact version: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-7.17.20-linux-x86_64.tar.gz


Hence, we are closing and marking this issue as **QA:Validated**.
Thanks!
