### ISSUE TITLE
Add an upgrade integration test upgrading to the PR build

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#4560]
**Describe the enhancement:**

The integration test should install and enroll the latest official release Elastic Agent, then upgrade it to the agent built from the PR.

The following is required:
 - Sing the agent package built from the PR. (use [`pgptest.Sing`](https://github.com/elastic/elastic-agent/blob/main/testing/pgptest/pgp.go#L19)
 - Setup a http server serving the ASCII armoured public key used to sign the agent artifact.
   - the agent downloads it from `https://artifacts.elastic.co/GPG-KEY-elastic-agent`.
   - See [PGP fallback URL in air-gapped environment workaround](https://github.com/elastic/elastic-agent/blob/26947871957102cd972210202f15217789ff5cb9/docs/pgp-workaround.md) for details.
 - setup a http server to serve the agent binary, its signature and checksum file for the upgrade
 - configure the policy to use the custom agent download binary URL

**Describe a specific use case for the enhancement or feature:**

To test [the migration of the state store](https://github.com/elastic/elastic-agent/pull/4441) during upgrade

**What is the definition of done?**

The test is created and successfully runs together with the current integration tests

**Comment by AndersonQ** [comment]
@pierrehilbert, @cmacknz as we discussed in the weekly, I created this issue for the new upgrade test

**Comment by jlind23** [comment]
@AndersonQ this has been moved to implementation a couple weeks ago but I do not see any draft PR, what is the current state of it?

**Comment by AndersonQ** [comment]
Change of priorities, it can be put as ready again
