### ISSUE TITLE
Disable automatic reload of the agent monitoring HTTP server until handling of default values is figured out 

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#4582]
In https://github.com/elastic/elastic-agent/pull/4499 we added a liveness probe and had the agent properly support reloading the HTTP monitoring server settings so that Fleet managed agents that defaulted to having the server off can turn it on.

This however has caused several unexpected problems, because there are agents (including the agent used to run Fleet Server in ESS) that have enabled HTTP monitoring in the initial agent configuration expecting it to stay enabled. When we enabled reload, what happened is the agent began respecting the default fleet policy which has HTTP monitoring disabled by default, thus turning off the HTTP server with no simple way in Fleet to turn it back on.

As a short term solution while we figure out how to make the default settings work correctly (I believe for ESS we need a way for the default fleet policy used to specify HTTP monitoring server settings), we need to keep the new liveness probe but disable reloading the HTTP monitoring server settings again.

**Comment by cmacknz** [comment]
Another alternative would be to treat an unset HTTP configuration as equivalent to a no-op, falling back to what the agent was installed at. We would only turn it off if we get an explicit set of settings from Fleet. This is similar to what we have to do with proxy settings which have the exact same problem.

That is we interpret configuration from fleet being missing as no-op, the problem is our config unpacking doesn't represent this unset state and likely unpacks into default values of empty strings and false booleans.

**Comment by cmacknz** [comment]
While we work this out let's revert https://github.com/elastic/elastic-agent/pull/4499 and then we can bring it back with a fix in case it takes longer to fix than we realize.

Also all the integration tests will fail until we get this reverted.

**Comment by cmacknz** [comment]
Revert PR https://github.com/elastic/elastic-agent/pull/4583

**Comment by fearful-symmetry** [comment]
Alright, just so I'm clear on the chain of events, it's something like this:

1) An initial `elastic-agent.yml` text config sets the monitoring enabled flag
2) We then get a fleet policy
3) the fleet policy has no `http.monitoring` section, so we default to off
4) Now that reloading works properly, we reload, and disable monitoring

I agree that the best way to handle this is to is to treat an unset config as effectively a no-op, and leave it enabled. That shouldn't be too difficult to implement. 

Also agree that we really need https://github.com/elastic/elastic-agent/issues/3511 ....

**Comment by cmacknz** [comment]
Yes your understanding is correct.

I think we need a global solution to this default values problem, every time we go add a new parameter to the Fleet UI that wasn't there before or make a new configuration reloadable on the agent we have this problem.
