### ISSUE TITLE
How to adjust the number of primary shards for all indexes that are made by elastic agent?

### ISSUE THREAD

**Issue by al-ah** [elastic/elastic-agent#460]
How to adjust the number of primary shards for all indexes that are made by elastic agent?

I do not want to use the component templates because there are so many templates that need to be changed. Does Elastic Agent have settings like index.number_of_shards like filebeat?

thanks

**Comment by jlind23** [comment]
Hasn't show up in a while / outdated. Closing. Feel free to reopen it if it is still required.
