### ISSUE TITLE
Vulnerabilities in 8.13.2 image

### ISSUE THREAD

**Issue by rgarcia89** [elastic/elastic-agent#4603]
Hi elastic-agent maintainers,

trivy currently detects in image v8.13.2 a total of 59 vulnerabilities. Can this topic please be given some attention.

```
REPOSITORY                                   TAG      SCANNER   AGE     CRITICAL   HIGH   MEDIUM   LOW   UNKNOWN
beats/elastic-agent                          8.13.2   Trivy     86m     4          4      51       0     0
```

**Comment by cmacknz** [comment]
Report this through security@elastic.co (per https://www.elastic.co/community/security) and it will be looked at.
