### ISSUE TITLE
Add integration test for downgrading to the previous minor release

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#4606]
- Relates https://github.com/elastic/kibana/issues/172745

We want to add the ability to downgrade to the previous release in the Fleet UI. As part of doing this, we need to an an integration ensuring we can downgrade to the most recently released minor version.

For example, 8.14.0-SNAPSHOT must be able to downgrade to 8.13.x. 8.13.0-SNAPSHOT must be able to downgrade to 8.12.x. When there are multiple patch releases available for a given minor, the test should test against the latest to avoid discovering bugs that are already fixed.

**Comment by cmacknz** [comment]
We are currently planning to model this after our existing rollback mechanism instead. This test isn't relevant with that model.

**Comment by nimarezainia** [comment]
can we close this then and concentrate on addressing the original issue? (since that issue is marked as being blocked by this)
