### ISSUE TITLE
Elastic Agent deployed with a https URL sets the protocol to HTTP instead of HTTPS.

### ISSUE THREAD

**Issue by jdixon-86** [elastic/elastic-agent#461]
Support ticket: #00961223

When deploying Elastic Agent's via fleet it appears that regardless of the URL it is setting the protocol to HTTP leading to unencrypted traffic. In my tests I have installed Elastic Agent on a Windows 11 laptop with the following command:

```
wget https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.2.0-windows-x86_64.zip -OutFile elastic-agent-8.2.0-windows-x86_64.zip

Expand-Archive .\elastic-agent-8.2.0-windows-x86_64.zip cd elastic-agent-8.2.0-windows-x86_64\elastic-agent-8.2.0-windows-x86_64

.\elastic-agent.exe install --url=https://fleet.domain.com/ --enrollment-token=aGRUQ2osdfsdfasdfasdfm46Y3NyQjFSVWRRb2EasdfasdfasdfasdfQQ==
```

Furthermore the logs state it started enrollment using HTTPS instead of HTTP
`{"log.level":"info","@timestamp":"2022-05-21T08:42:54.993-0500","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":461},"message":"Starting enrollment to URL: https://fleet.domain.com/%22,%22ecs.version%22:%221.6.0%22%7D {"log.level":"info","@timestamp":"2022-05-21T08:42:58.858-0500","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":261},"message":"Successfully triggered restart on running Elastic Agent.","ecs.version":"1.6.0"} Successfully enrolled the Elastic Agent. Elastic Agent has been successfully installed.`

You can see in the log it enrolls to https://fleet.domain.com/ (I do a PAT on the firewall for port 443 to port 8220). However it results in this configuration:
![image](https://user-images.githubusercontent.com/5861587/169671182-8e5db850-0c42-49fe-b217-274a747e2c6c.png)

Taking a look at the traffic I only see TCP traffic until I enable protocol: https which then starts producing TLSv1.2 traffic when doing a packet capture on my firewall.

Unless I am missing something, this is a pretty big issue and could lead to traffic not being secured between the client and the server while giving the impression to the admin installing the agent is it.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 8.2.0
- Operating System: Windows 11
- Discuss Forum URL: https://www.reddit.com/r/elasticsearch/comments/uunrq1/elastic_agent_deploys_with_http_even_though_https/
- Steps to Reproduce: Install Elastic Agent through fleet using https

**Comment by davidchoi-aus** [comment]
Further update from the customer:

After digging into this further and involving some others on my side, I believe it actually is communicating with TLS even when the protocol is HTTP.

**Comment by jlind23** [comment]
Closing this as fixed, feel free to reopen it if need be.
