### ISSUE TITLE
`system.security` dataset is not generated for Windows agent installed with unprivileged flag.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#4647]
**Kibana Build details:**
```
VERSION: 8.14.0 BC2
BUILD: 73626
COMMIT: bcf6960778ae270d0894a8aab07f10197ee9b97f
```

**Preconditions:**
1. 8.14.0-BC2 Kibana cloud environment should be available.
2. Agent should be installed with unprivileged flag.

**Steps to reproduce:**
1. Navigate to Data Streams tab.
2. Observe logs for system integration and `system.security` dataset is not generated.

**Expected Result:**
`system.security` dataset should be generated for Windows agent installed with unprivileged flag.

**What's working fine:**
- `system.security` dataset is generated for Windows agent installed without unprivileged flag.

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/56650419-b320-4fc5-8587-ceb2e91568a7)

**Comment by amolnater-qasource** [comment]
@karanbirsingh-qasource Please review.

**Comment by karanbirsingh-qasource** [comment]
secondary review is done

**Comment by cmacknz** [comment]
I suspect this will be related to the permissions of the new unprivileged user.

Can you upload diagnostics when this happens?

**Comment by leehinman** [comment]
odds are really good that the new unprivileged user needs to be a member of the "Event Log Readers" group.

**Comment by blakerouse** [comment]
It was agreed that the Administrator performing the installation will add the `elastic-agent-user` to the groups that they want the Elastic Agent to have access to.

I don't know exactly which group is needed to read that data, so I would try @leehinman suggestion.

**Comment by amolnater-qasource** [comment]
Hi Team,

Thank you for looking into this issue.

Please find below agent diagnostics for the installed agent:
[elastic-agent-diagnostics-2024-05-02T06-10-30Z-00.zip](https://github.com/elastic/elastic-agent/files/15185263/elastic-agent-diagnostics-2024-05-02T06-10-30Z-00.zip)

Please let us know if anything else is required from our end.
Thanks!!

**Comment by nimarezainia** [comment]
> It was agreed that the Administrator performing the installation will add the `elastic-agent-user` to the groups that they want the Elastic Agent to have access to.
> 
> I don't know exactly which group is needed to read that data, so I would try @leehinman suggestion.

@blakerouse are there any other steps during installation that the user needs to perform? not just for this issue but generally speaking. I want to make sure we can comprehensively document these.

cc: @kilfoyle

**Comment by ycombinator** [comment]
@amolnater-qasource Did you get a chance to try @leehinman's [suggestion](https://github.com/elastic/elastic-agent/issues/4647#issuecomment-2088856392)? If it works, we can document it as a pre-requisite for running Agent in unprivileged mode.

**Comment by nimarezainia** [comment]
thank you @ycombinator. We would need instructions on how the user could change the privilege level (that are OS specific) for some of the major operating systems. 

**the use case**: In Fleet, we inform the user that an input is not working due to privilege. The idea was to provide them some instructions on how to change the priv level to be able to read the data source.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated the docs for Unprivileged mode agent installation under https://www.elastic.co/guide/en/fleet/current/elastic-agent-unprivileged.html#unprivileged-integrations and found it documented there.

**Screenshot:**
![Image](https://github.com/user-attachments/assets/95b53a63-fb0d-43d7-9730-b5f204e94265)

Further, on testing the Resolution on latest 8.18-SNAPSHOT: `Add the elastic-agent-user user to the Event Log Users group to fix this error.` and found it **working fine** now.

**Observations:**
- `system.security` dataset is generated for Windows agent installed with unprivileged flag.

**Screenshot:**

![Image](https://github.com/user-attachments/assets/84947c66-a5ea-4028-be3c-9c117232b9c4)
![Image](https://github.com/user-attachments/assets/533ac99e-ec52-4601-8c4d-63dd32cc99b4)


Hence, we are marking this issue as **QA:Validated**.

Thanks!!
