### ISSUE TITLE
Image docker.elastic.co/beats/elastic-agent:8.13.3 does not exists

### ISSUE THREAD

**Issue by cesarqdt** [elastic/elastic-agent#4651]
The current official documentation pointing to download this manifest for elastic agents `curl -L -O https://raw.githubusercontent.com/elastic/elastic-agent/8.13/deploy/kubernetes/elastic-agent-managed-kubernetes.yaml` pulls the wrong image 8.13.3, which does not exist.

The website link: https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html

**Comment by cmacknz** [comment]
The documentation update seems to have happened ahead of the actual release process. The image will exist very soon. Use 8.13.2 if you need something that exists immediately.
