### ISSUE TITLE
User is unable to uninstall mac agent completely on running uninstall command when installed with `--unprivileged` flag.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#4655]
**Kibana Build details:**
```
VERSION: 8.14.0 BC2
BUILD: 73626
COMMIT: bcf6960778ae270d0894a8aab07f10197ee9b97f
```
Artifact Link: https://staging.elastic.co/8.14.0-2bf292f8/downloads/beats/elastic-agent/elastic-agent-8.14.0-darwin-aarch64.tar.gz

**Preconditions:**
1. 8.14.0-BC2 Kibana cloud environment should be available.
2. MAC Agent should be installed with unprivileged flag.

**Steps to reproduce:**
1. Under CLI run `sudo elastic-agent uninstall` command.
2. Observe errors under CLI:
```
[ ===] Failed to uninstall agent [0s] Error uninstalling. Printing logs
2024-05-02T11:49:55.004Z	DEBUG	[uninstall.state_migration]	state store /Library/Elastic/Agent/data/elastic-agent-8.14.0-372976/state.enc already exists
Error: error uninstalling agent: error uninstalling components: error loading agent config: error obtaining fleet config: yaml: input error: fail to decode bytes: cipher: message authentication failed
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.14/fleet-troubleshooting.html
```

**Expected Result:**
User should be able to uninstall mac agent completely on running uninstall command when installed with `--unprivileged` flag.

**Logs:**
[elastic-agent-diagnostics-2024-05-02T11-53-41Z-00.zip](https://github.com/elastic/elastic-agent/files/15187921/elastic-agent-diagnostics-2024-05-02T11-53-41Z-00.zip)

**Screenshot:**

![image](https://github.com/elastic/elastic-agent/assets/77374876/90f431f1-6258-4d13-8387-35480a29989e)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by pchila** [comment]
While reproducing I discovered an interesting behaviour:
- standalone agent works fine
- managed agent uninstall in unprivileged works correctly *if there's no co.elastic.elastic-agent in the system keychain*
- after reproducing the error, removing the elastic-agent entry in system keychain solves the issue.

It seems that during some part of uninstall for a managed agent we are loading the wrong key, hence the error reported in this issue. Will keep debugging trying to understand where agent try to default to the system keychain vault when installed as unprivileged

**Comment by pchila** [comment]
Root cause identified: state store migration is called during the uninstall but it does not used the `unprivileged` flag passed down from the `uninstall`command. Since the `uninstall` command is running with root privileges elastic-agent loads a key from the system keychain (if it finds one) instead of loading the correct key from the file vault located in `/Library/Elastic/Agent/vault`.
Loading the wrong key makes decoding fleet.enc error out with the listed error.

The PR related to the issue propagates the correct value of `unprivileged` flag determined in the `uninstall` command so that the EncryptedKeystore for fleet.enc is instantiated with the correct key

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.14.0 BC4 kibana cloud environment and found it **fixed now**:

**Observations:**
- User is able to uninstall mac agent completely on running uninstall command when installed with --unprivileged flag.


**Screenshot:**

![image](https://github.com/elastic/elastic-agent/assets/77374876/a486ec5f-ce35-4cd8-8f77-89b13e92ca97)


**Build details:**
VERSION: 8.14.0 BC4
BUILD: 73836
COMMIT: 23ed1207772b3ae958cb05bc4cdbe39b83507707

Hence we are marking this issue as **QA:Validated**.

Thanks!
