### ISSUE TITLE
Windows agent is not available on Fleet UI on restart when installed with `--delay-enroll` and `--unprivileged`.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#4678]
**Kibana Build details:**
```
VERSION: 8.14.0 BC3
BUILD: 73762
COMMIT: 2a492e1625f24336f3259b2b8df62b2b18127e81
```
Artifact Link: https://staging.elastic.co/8.14.0-7c638435/downloads/beats/elastic-agent/elastic-agent-8.14.0-windows-x86_64.zip

**Preconditions:**
1. 8.14.0-BC3 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Run agent install command with  `--delay-enroll` and `--unprivileged`.
2. Observe agent is successfully installed.
3. Restart the Windows host.
4. Observe agent is not visible on Fleet UI and the Elastic Agent service is not started.

**Note:**
Issue is consistently reproducible on multiple Windows Hosts.

**Expected Result:**
Windows agent should be available on Fleet UI on restart when installed with `--delay-enroll` and `--unprivileged`.

**Logs:**
[logs.zip](https://github.com/elastic/elastic-agent/files/15218565/logs.zip)
[logs2.zip](https://github.com/elastic/elastic-agent/files/15218569/logs2.zip)

**Screenshot:**
![image](https://github.com/elastic/elastic-agent/assets/77374876/0184aaa2-b81e-45f4-957b-9de015f7ce4c)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
```json
{"log.level":"info","@timestamp":"2024-05-06T07:27:41.736Z","log.origin":{"file.name":"cmd/run.go","file.line":180},"message":"Elastic Agent started","log":{"source":"elastic-agent"},"process.pid":3400,"agent.version":"8.14.0","agent.unprivileged":true,"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-05-06T07:27:41.771Z","log.origin":{"file.name":"cmd/run.go","file.line":147},"message":"failed to perform delayed enrollment: could not create new vault: The operation completed successfully.","log":{"source":"elastic-agent"},"ecs.version":"1.6.0"}
```

**Comment by amolnater-qasource** [comment]
Hi Team,
We have revalidated this issue on latest 8.17.0 BC5 kibana cloud environment and found it **fixed now**.

**Observations:**
- Windows agent should be available on Fleet UI on restart when installed with --delay-enroll and --unprivileged.

**Screenshots:**
![Image](https://github.com/user-attachments/assets/10907104-6a56-45d1-aa0f-7e54c3ce29a4)
![Image](https://github.com/user-attachments/assets/9e9f5efe-6f6c-4155-873d-20030acbbf4c)


**Build details:**
VERSION: 8.17.0 BC5
BUILD: 80495
COMMIT: 5c78fb5e4e9b5063bd83ae9bd1e5b32c63f5cc34
Artifact Link: https://staging.elastic.co/8.17.0-a18e6540/downloads/beats/elastic-agent/elastic-agent-8.17.0-windows-x86_64.zip

Hence we are marking this issue as **QA:Validated**.

Thanks!
