### ISSUE TITLE
[Discuss] Keeping `CHANGELOG.next.asciidoc` or considering alternatives

### ISSUE THREAD

**Issue by narph** [elastic/elastic-agent#47]
I am sure everyone has struggled with the `CHANGELOG.next.asciidoc` file, having to commit a second time in order to add the PR number or forgetting to add a comment , the file is also prone to merge conflicts and not isolated.
We had several discussions on alternative solutions inside beats but I am not aware if we committed already to anything yet, also noticed https://github.com/elastic/elastic-agent-changelog-tool not sure what the status is on this repo.

Can we consider any of the alternatives:

- same as fleet-server, plan was to use the Kibana changelog system (automatically extracts changes from the merged PR’s and builds the changelog for release)
- wait for https://github.com/elastic/elastic-agent-changelog-tool 
- build some functionality around this, at each PR merge, a new PR will be automatically created to update the `CHANGELOG` file, if a second PR is merged while this generated PR is still open then a new commit is added to the generated PR (not sure how clear I am here)
- open to other alternatives

@andresrc, you have driven the conversation here, what are the plans with https://github.com/elastic/elastic-agent-changelog-tool?
@ruflin , @jlind23 , @ph , @elastic/elastic-agent-control-plane  any preference here?

**Comment by jlind23** [comment]
Closing this as outdated as we now rely on fragments - https://github.com/elastic/elastic-agent/tree/main/changelog/fragments and https://github.com/elastic/elastic-agent-changelog-tool
