### ISSUE TITLE
Elastic Agent service configured with delayed enrollment exits when it cannot connect.

### ISSUE THREAD

**Issue by ajoliveira** [elastic/elastic-agent#4716]
After installing Elastic Agent to use delayed enrollment, when service is (re)started and it fails to enroll, the service simply exists and does not continue to automatically retry.  Services panel message is:
"The Elastic Agent service on Local Computer started and then stopped.  Some services stop automatically if they are not in use by other services or programs."

The 2 scenarios I used to test this were:
- no network (ie: wi-fi disabled, errors is DNS failure)
- with network & wrong DNS (failed connection to Fleet server)

Both log outputs indicate that it is attempting a delayed enrollment and that the 1st enrollment failed and would be retried for 10 mins, every 1 min to specified Fleet server URL but the process/services just exits after that.

For confirmed bugs, please report:
- Version: 8.13.3
- Operating System: Windows 10 Home
- Discuss Forum URL:
- Steps to Reproduce:
1) Install Elastic Agent with `--delay-enroll` option
2) Confirm service is created with 'Automatic' startup
3) Disable network or override DNS resolution to replicate a failed connection
4) Attempt to start the service manually
5) Confirm service/process continues to run and retry enrollment

Step 5 always fails since the service/process exits immediately after reporting a connectivity issue.

**Comment by cmacknz** [comment]
https://github.com/elastic/elastic-agent/blob/fdacc6c5156e1d77f0d3df5315cca561747ab74e/internal/pkg/agent/cmd/run.go#L185-L188

The current behavior seems to be that the agent process exits if delayed enrollment fails after a few retries. I think there is an assumption that the service manager is going to automatically restart the process so it can try again. If that isn't valid in all circumstances this logic needs to change.

**Comment by strawgate** [comment]
Shared this in Slack:

it looks like the issue is due to the manual starting of the service and if you rebooted you wouldnt see the issue?

automatic startup on the service takes effect on boot, not when you manually start the service

**Comment by ajoliveira** [comment]
Following up on above - same thing occurs after rebooting.  The log indicates the same behavior, startup is attempted but since connection fails, Elastic Agent exits.

This brings up a good question - when retries are working as expected will they also stop after the noted "10 mins, every 1 min" as noted in the logs?  Are there any other options, for example, to retry indefinitely and not rely on user to have to reboot or some other 'watchdog' service?

**Comment by strawgate** [comment]
Looks like the service fails to start so its restarts don't get managed by the service manager:
```
net start "Elastic Agent"
The Elastic Agent service is starting.
The Elastic Agent service could not be started.

The service did not report an error.

More help is available by typing NET HELPMSG 3534.

PS C:\Users\bill_easton\elastic-agent-8.12.2-windows-x86_64>
```

**Comment by cmacknz** [comment]
Interesting, I wonder at what point it considers us started enough to be restarted.

We should be sending the StartPending and Running service control events asynchronously to the delayed enrollment, but those happen asynchronously in a goroutine and perhaps they aren't actually happening in time.

https://github.com/elastic/elastic-agent/blob/49745a790762ac84c3954ba090939992da841668/internal/pkg/agent/cmd/run.go#L139-L188

**Comment by cmacknz** [comment]
CC @leehinman in case you know what the exact problem is off the top of your head.

**Comment by leehinman** [comment]
> Interesting, I wonder at what point it considers us started enough to be restarted.

yeah, you have to get to https://github.com/elastic/elastic-agent-libs/blob/2c654640b6d541a1054930d956f23261dbe64288/service/service_windows.go#L48 and that is in another go routine.
