### ISSUE TITLE
Make `hostmetricsreceiver` available in `otel` mode

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#4724]
**Describe the enhancement:**

Include the `hostmetricsreceiver` in the OTel Collector [components](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/otel/components.go) we bundle with Elastic Agent.

**Describe a specific use case for the enhancement or feature:**

Users of Elastic Agent in OTel mode (`elastic-agent otel ...`) would like to be able to use the `hostmetricsreceiver` in their OTel Collector pipeline configurations.  

**What is the definition of done?**

* [ ] A test that runs Elastic Agent in OTel mode (`elastic-agent otel ...`) includes the `hostmetricsreceiver` in it's test OTel Collector configuration and the test passes.

**Comment by ycombinator** [comment]
Note that an attempt was already made to try and bundle the `hostmetricsreceiver` with Elastic Agent in https://github.com/elastic/elastic-agent/pull/4706 but CI failed Serverless tests 🤷 on the following error:

```
>>> (windows-amd64-2022-fleet) Test output (sudo) (stdout): Error: error starting service: failed to start service (Elastic Agent): The service did not respond to the start or control request in a timely fashion.
```

**Comment by ycombinator** [comment]
Please remember to backport this issue's PR to the `8.14` branch.

**Comment by jlind23** [comment]
> Please remember to backport this issue's PR to the 8.14 branch.

@ycombinator @andrzej-stencel this is because it has to be available for 8.14.2 right?

**Comment by ycombinator** [comment]
@cmacknz This issue came up for discussion in today's OTel Weekly sync meeting, specifically the [Windows failures](https://github.com/elastic/elastic-agent/issues/4724#issuecomment-2101868627) we were seeing the last time we tried to include the `hostmetricsreceiver` in Elastic Agent.  @strawgate mentioned you suggested some way to exclude tihs receiver only on Windows.  I was curious how we'd go about this, considering we'd still need the `require` in `go.mod` and the `import` in https://github.com/elastic/elastic-agent/blob/main/internal/pkg/otel/components.go.  Were you thinking something like adding a `if runtime.GOOS == "windows"` conditional around https://github.com/elastic/elastic-agent/blob/d2d88caf63a49396498c38762d4b7d72ab0a588d/internal/pkg/otel/components.go#L41-L44 or something else?

**Comment by cmacknz** [comment]
I didn't have any specific way of doing this in mind, but a conditional on `runtime.GOOS` would work.

I don't think we've spent much time actually investigating why it fails, so I'd prefer we put a day into that first, and only make it conditional if we can't figure out what is wrong.
