### ISSUE TITLE
[Agent Upgrade]: Agents gets upgraded automatically after user abort the agent upgrade.

### ISSUE THREAD

**Issue by ghost** [elastic/elastic-agent#473]
**Describe the bug:**
Agents gets upgraded automatically even after user abort the agent upgrade.

**Build Details:**
VERSION: 8.3.0-SNAPSHOT
COMMIT: c993ff2a4fa10898d5a6e15aeb1d0848534ae48e
BUILD: 53035
ARTIFACT LINK: https://snapshots.elastic.co/8.3.0-a497a6ef/summary-8.3.0-SNAPSHOT.html

**Preconditions:**
1. Elastic 8.3.0-SNAPSHOT environment should be deployed.
2. 8.2.0 or lower version agents should be installed.

**Steps to Reproduce:**

1. Navigate to the Fleet tab under Management.
3. Now, under Agents tab select the Agents which are available for upgrade.
4. Click on Action button and select the upgrade version and upgrade schedule and click on upgrade agents.
5. Now, click on Abort upgrade and wait for 2 minutes.
6. Observe that agents gets upgraded automatically after user abort the agent upgrade.

**Expected Result:**
Agents should not get upgraded automatically after user abort the agent upgrade.

**Screenshot:**
![Screenshot (460)](https://user-images.githubusercontent.com/84007952/170211662-58166b02-c0a4-4fd5-aa8a-9398e5158c87.png)
![Screenshot (461)](https://user-images.githubusercontent.com/84007952/170211760-b99dd814-a831-421c-b769-505749a436ae.png)
![Screenshot (462)](https://user-images.githubusercontent.com/84007952/170211830-86039f3c-f26d-47f3-a05a-9f42d11e583f.png)
![Capture](https://user-images.githubusercontent.com/84007952/170211876-f1617959-fa70-4c3e-8fcd-6beb145b4134.PNG)

**Logs:**
Windows:
[Winlogs.zip](https://github.com/elastic/elastic-agent/files/8769066/Winlogs.zip)
MAC:
[elastic-agent-diagnostics-2022-05-25T07-09-21Z-00.zip](https://github.com/elastic/elastic-agent/files/8768813/elastic-agent-diagnostics-2022-05-25T07-09-21Z-00.zip)

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by joshdover** [comment]
@samratbhadra-qasource What options did you use for the scheduling? I'm curious if this may actually be the same bug as https://github.com/elastic/kibana/issues/136022

**Comment by prachigupta-qasource** [comment]
Hi @joshdover,

Earlier, we have used 'Immediately' option at Maintenance Window on 'Upgrade Agent' modal.

Further, we have re-investigated it with below scenarios:
**Scenario 1:** Maintenance Window is selected 'Immediately' on 'Upgrade Agent' modal on selecting more than one Agents

- Agents get upgraded automatically even after user has aborted the agent upgrade.
![image](https://user-images.githubusercontent.com/97870262/178459527-f7a8326c-0482-4c83-9484-50fd11a3bf0f.png)

**Scenario 2:** Scheduled Date and Time is set to next available active time slot from the current time on 'Upgrade Agent' modal.

- Agents get upgraded automatically i.e. within 3-4 minutes though user has aborted the agent upgrade action.
![image](https://user-images.githubusercontent.com/97870262/178451881-b0902b55-974e-4675-8ca7-e2cdc84bab35.png)

**Scenario 3:** Maintenance Window is selected '1 hour' on 'Upgrade Agent' modal on selecting more than one Agents

- Agents did not get upgraded automatically after user aborted the agent upgrade. **Found, It working Fine**
![image](https://user-images.githubusercontent.com/97870262/178451376-ab52f19d-cecb-4f04-bcf6-3d89023ae71d.png)

**Build details:**
```
Version: 8.4.0 SNAPSHOT
Build: 54378
Commit: 17a2bcc82856ea7720f684a5f0e2ab0664517401
```

**Logs:**
Windows:
[logs.zip](https://github.com/elastic/elastic-agent/files/9091361/logs.zip)
[elastic-agent-diagnostics-2022-07-12T09-58-01Z-00.zip](https://github.com/elastic/elastic-agent/files/9091780/elastic-agent-diagnostics-2022-07-12T09-58-01Z-00.zip)

Mac:
[elastic-agent-diagnostics-2022-07-12T09-48-41Z-00.zip](https://github.com/elastic/elastic-agent/files/9091756/elastic-agent-diagnostics-2022-07-12T09-48-41Z-00.zip)

We will re-validate this ticket once the fixes are available.

Thanks!

**Comment by amolnater-qasource** [comment]
### `Bug Conversion:`

We have updated **01 testcase** for this scenario in our fleet test suite at:
  - https://elastic.testrail.io/index.php?/cases/view/166784

Thanks

**Comment by jlind23** [comment]
Closing this as fixed, feel free to reopen it if need be.

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have re-validated this issue on the latest 8.14.0 BC5 Kibana cloud environment and found it **fixed now**.

Observations:
- Agents doesn't get upgraded automatically after user abort the agent upgrade.

**Build details:**
VERSION: 8.14.0 BC5
BUILD: 73931
COMMIT: 7ea00b6178d67183a4def9bdd060b062cced043e

**Screen-Shot:**
![image](https://github.com/elastic/elastic-agent/assets/101545338/bcf7046e-f250-4d7c-96b3-2cd8cf2ea30d)




Hence, we are marking this issue as **QA: Validated**.

Thanks
