### ISSUE TITLE
`log_level` metadata is not accurate

### ISSUE THREAD

**Issue by jen-huang** [elastic/elastic-agent#4747]
Follow up to the discussion in https://github.com/elastic/kibana/issues/180778

Reproduction: 
1. Enroll a new agent into a policy that already has log level set to `debug`
2. Observe that the agent successfully sent debug logs
3. View agent document, observe that `local_metadata.elastic.agent.log_level` is reporting `info` even though it is running at `debug` level from its policy

**Comment by nchaulet** [comment]
FYI where it's used in kibana 
<img width="1490" alt="Screenshot 2024-05-16 at 11 29 16 AM" src="https://github.com/elastic/elastic-agent/assets/1336873/b7d1dcaa-92d3-4647-98d3-62b49efa7483">

**Comment by jen-huang** [comment]
> FYI where it's used in kibana

Also displayed on the details tab :

<img width="772" alt="image" src="https://github.com/elastic/elastic-agent/assets/1965714/279f63d6-87b9-43ae-a3d4-a38b9011aed9">

**Comment by pchila** [comment]
Change has been reverted via #4938 reopening
