### ISSUE TITLE
[Question]: Confirmations on `Feature: Agent rolling upgrades`.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#475]
**Description:**
While testing on Agent rolling upgrades on latest 8.3 Snapshot we had few queries.

### Queries:

1. Agent can be downgraded from 8.2.1>8.1.1 However failed when upgraded from 8.2.1>7.17.3 and 8.1.1>7.17.3
Could you please confirm if this is expected?

2. If agent is downgraded from 8.2.1>8.1.1 and then attempted to downgrade to 7.17.3. Rather than staying on 8.1.1 on failure it gets back to 8.2.1 and also gets Unhealthy.
As per our understanding if agent fails a downgrade it should remain on 8.1.1.
Could you please confirm if this is an issue?

3. Lower version agents(not same as that of kibana) can be downgraded to many lower versions however on attempting to downgrade the same version agent as that of kibana it shows a failure.
Could you please confirm if this is expected?

![13](https://user-images.githubusercontent.com/77374876/170267398-1fcedb01-bd98-4889-aaa3-97a59d76a9d3.JPG)
![4 - Copy](https://user-images.githubusercontent.com/77374876/170267555-053a8ad5-1ad2-475f-ad12-f230814561b9.JPG)

**Reference Ticket:**
https://github.com/elastic/obs-dc-team/issues/739

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
FYI @jlind23 @joshdover

**Comment by michel-laterman** [comment]
I wasn't aware that the agent supported downgrades 😅.
Have we tested these workflows before? None of the upgrade action logic has changed with this feature on the fleet-server or elastic-agent side

**Comment by nchaulet** [comment]
> I wasn't aware that the agent supported downgrades 😅.
Have we tested these workflows before? None of the upgrade action logic has changed with this feature on the fleet-server or elastic-agent side

I do not think we should support downgrade neither it's probably a bug we introduced when allowing to select the version. This should be a bug to fix in Kibana.

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman

Thanks for the looking into our queries and providing your views.

Further, we would like to suggest that in above reported scenarios, as downgrading is not supported, so we should only display versions that are higher from the agent we are trying to upgrade.

@nchaulet
Please, let us know we we need to log a separate issue for this.

Thanks

**Comment by nchaulet** [comment]
> @nchaulet
Please, let us know we we need to log a separate issue for this.

Thanks @amolnater-qasource I think that issue https://github.com/elastic/kibana/issues/132909 is already good enough

**Comment by criamico** [comment]
I'm closing this issue since the bug is already tracked in https://github.com/elastic/kibana/issues/132909

**Comment by amolnater-qasource** [comment]
Hi Team
Thanks for the feedback and resolving our queries.
Further we will be tracking this issue under https://github.com/elastic/kibana/issues/132909 and will validate the agent upgrades on the same.

Thanks
