### ISSUE TITLE
[Integration test] Agent, running in unprivileged mode, can run the `nginx` integration

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#4818]
We need to have confidence that Agent, running in `--unprivileged` mode, can successfully collect data for an integration that doesn't require privileged access to the system, e.g. the `nginx` integration.  

## Definition of done
* [ ] An integration test that installs an Agent in `--unprivileged` mode, uses a policy that contains the `nginx` integration, and verifies that data is being collected for this integration without any errors.

**Comment by VihasMakwana** [comment]
@ycombinator I'm currently [following the guide](https://www.elastic.co/guide/en/integrations-developer/current/index.html) to test the integrations locally. Nginx integration already includes [system tests](https://github.com/elastic/integrations/tree/main/packages/nginx/data_stream/stubstatus/_dev/test/system) with [stubstatus](https://github.com/elastic/integrations/blob/main/packages/nginx/_dev/deploy/docker/nginx.conf) enabled.
I don't think we need separate tests in integrations repo as the [manifest.yaml](https://github.com/elastic/integrations/blob/main/packages/nginx/manifest.yml) doesn't require the user to be a root.

These tests are already present in `elastic/integrations` repository and they're run in unprivileged mode. https://github.com/elastic/elastic-agent/pull/5398#discussion_r1744513073

**Comment by ycombinator** [comment]
@VihasMakwana I agree, now that we've switched to Wolfi-based images for system testing the integrations.  Closing this issue.
