### ISSUE TITLE
Windows agent uninstall

### ISSUE THREAD

**Issue by Cody7172** [elastic/elastic-agent#4827]
The very first time I try, I received the following error:
> C:\Program Files\Elastic\Agent>elastic-agent.exe uninstall -f
Error: yaml: line 6: did not find expected key
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.10/fleet-troubleshooting.html

I didn’t bother to figure it out and decided to delete folder according to the guide to which I was given a link in the cmd (stop services and delete the entire folder)
So when trying to install the new agent, the following error appears:

> Elastic Agent installed but currently broken: service exist but installation path is missing
[...]
 "Failed to install service (Elastic Agent): service Elastic Agent already exists.

So now I still unable to install/reinstall or delete agent
"sc stop ElasticAgent", "sc delete ElasticAgent" commands stops service but do not delete it
I don’t delete service through the registry because a reboot is still will be required, but this is prod env
I also tried the --force commands on install and uninstall, but without success.
How can I remove the service or force the agent to reinstall properly?

**Comment by pierrehilbert** [comment]
Hello,
Is it a standalone Agent?
It seems that you have an error in your yaml file that needs to be first fixed.

If this is managed agent, I would advice to change the policy to remove every integrations and that should make the situation better.
