### ISSUE TITLE
[Elastic Agent] Qualify the latest Ubuntu operating system (24.04)

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent#4830]
Please qualify Elastic Agent running on Ubuntu 24.04 operating system for inclusion into our support matrix. Target 8.15

### Definition of Done
* [ ] Elastic Agent integration tests run on Ubuntul 24.04

cc; @nick-alayil

**Comment by jlind23** [comment]
@amolnater-qasource Can we get your help in order to manually test this? 8.15 seems to be the target here, @nimarezainia do you confirm?
@ycombinator Can we make sure this new OS is added as part of our integration test matrix?

**Comment by ycombinator** [comment]
> Can we make sure this new OS is added as part of our integration test matrix?

Added a Definition of Done to this issue to reflect this and added the issue to the next sprint (last one before 8.15).

**Comment by amolnater-qasource** [comment]
Hi Team,

We have tested new OS Ubuntu 24.04 on 8.15.0 SNAPSHOT and found it **working fine**.

**Test Plan:**
- [Fleet new OS- Ubuntu 24.04 Smoke Test Plan](https://elastic.testrail.io/index.php?/runs/view/6764)

**Status:**
PASSED: 51

**Scenarios Tested:**
- Agent install, Uninstall, Reinstall. ✅ 
- Compatibility with Elastic Defend. ✅ 
- Data for various core integrations: System, Elastic Defend, Linux and Custom Logs. ✅ 
- Other integrations: MySQL, Kafka, Nginx, Redis, RabbitMQ. ✅ 
- Agent Tamper protection. ✅ 
- Output tests with Remote Elasticsearch and Kafka output. ✅ 
- Custom path installation tests including agent upgrade. ✅ 
- Standalone agent installation. ✅ 
- Standalone agent upgrade: 8.14.0>8.15.0-SNAPSHOT. ✅ 
- Fleet Based agent upgrade: 8.14.0>8.15.0-SNAPSHOT. ✅ 
- Agent Logs. ✅ 

Please let us know if any other scenario needs to be tested for this.
Thanks!
