### ISSUE TITLE
Fleet server tries elasticsearch connection via localhost instead of configured elasticsearch url.

### ISSUE THREAD

**Issue by Alphayeeeet** [elastic/elastic-agent#4873]
This is my installation command:
sudo ./elastic-agent install --url=https://<fleet_server_url_load_balancer>:8220 \
  --fleet-server-es=https://<es_url-load_balancer>:9200 \
  --fleet-server-service-token=TOKEN \
  --fleet-server-policy=ID \
  --certificate-authorities=CA \
  --fleet-server-es-ca=CA \
  --fleet-server-cert=cert \
  --fleet-server-cert-key=KEY \
  --fleet-server-port=8220

For confirmed bugs, please report:
- Version: 8.14.0
- Operating System: RHEL 9
- Steps to Reproduce: Reinstall fleet server

My Elasticsearch does not allow connections from localhost.
Why is it trying to connect via localhost instead of the right URL?

I cannot grant access via localhost as both my ES Certificate and my Fleetserver certificate do not allow localhost in SAN.

**Comment by Alphayeeeet** [comment]
This is the frequent log:
`{"log.level":"info","@timestamp":"2024-06-06T19:06:57.169Z","message":"Attempting to reconnect to backoff(elasticsearch(http://localhost:9200)) with 4 reconnect attempt(s)","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"service.name":"metricbeat","ecs.version":"1.6.0","log.logger":"publisher_pipeline_output","log.origin":{"file.line":139,"file.name":"pipeline/client_worker.go","function":"github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*netClientWorker).run"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-06-06T19:06:57.169Z","message":"Error dialing dial tcp 127.0.0.1:9200: connect: connection refused","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"http/metrics-monitoring","type":"http/metrics"},"log":{"source":"http/metrics-monitoring"},"network":"tcp","address":"localhost:9200","service.name":"metricbeat","ecs.version":"1.6.0","log.logger":"esclientleg","log.origin":{"file.line":38,"file.name":"transport/logging.go","function":"github.com/elastic/elastic-agent-libs/transport/httpcommon.(*HTTPTransportSettings).RoundTripper.LoggingDialer.func1"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-06-06T19:07:00.890Z","message":"Failed to connect to backoff(elasticsearch(http://localhost:9200)): Get \"http://localhost:9200\": dial tcp 127.0.0.1:9200: connect: connection refused","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},"log":{"source":"beat/metrics-monitoring"},"ecs.version":"1.6.0","log.logger":"publisher_pipeline_output","log.origin":{"file.line":148,"file.name":"pipeline/client_worker.go","function":"github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*netClientWorker).run"},"service.name":"metricbeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2024-06-06T19:07:00.890Z","message":"Attempting to reconnect to backoff(elasticsearch(http://localhost:9200)) with 4 reconnect attempt(s)","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},"log":{"source":"beat/metrics-monitoring"},"service.name":"metricbeat","ecs.version":"1.6.0","log.logger":"publisher_pipeline_output","log.origin":{"file.line":139,"file.name":"pipeline/client_worker.go","function":"github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*netClientWorker).run"},"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2024-06-06T19:07:00.891Z","message":"Error dialing dial tcp 127.0.0.1:9200: connect: connection refused","component":{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},"log":{"source":"beat/metrics-monitoring"},"address":"localhost:9200","ecs.version":"1.6.0","log.logger":"esclientleg","log.origin":{"file.line":38,"file.name":"transport/logging.go","function":"github.com/elastic/elastic-agent-libs/transport/httpcommon.(*HTTPTransportSettings).RoundTripper.LoggingDialer.func1"},"network":"tcp","service.name":"metricbeat","ecs.version":"1.6.0"}
`

**Comment by ycombinator** [comment]
Hi @elastic/licensing-portal , we use GitHub issues in this repository for bug reports and enhancement requests. For questions such as yours, please use https://discuss.elastic.co/c/elastic-stack/elastic-agent/91. Thank you!

**Comment by ycombinator** [comment]
Hi @Alphayeeeet, we use GitHub issues in this repository for bug reports and enhancement requests. For questions such as yours, please use https://discuss.elastic.co/c/elastic-stack/elastic-agent/91. Thank you!

**Comment by Alphayeeeet** [comment]
This is a bug as my production system is currently affected. https://discuss.elastic.co/t/please-help-fleetserver-reinstall-is-not-working-after-8-14-0-upgrade/360995

**Comment by Alphayeeeet** [comment]
@ycombinator I wouldnt have opened an issue if I wasnt sure it is an Elastic issue. I can provide you even more logs.

**Comment by Alphayeeeet** [comment]
I upgraded to 8.14.0 and had problems during fleet server upgrade. After trying to reinstall the agent multiple times it never starts up fleet-server correctly.

**Comment by Alphayeeeet** [comment]
@ycombinator
