### ISSUE TITLE
Improve test proxy/mock fleet server to proxy HTTPS connections

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#4903]
During development of #4770 it was not possible to test a scenario where elastic-agent installs and enrolls to an http mock fleet server using TLS going through an https proxy because:
- Using an http fleet endpoint requires specifying `--insecure` at install even when we have a correctly configured https proxy (no TLS validation would then happen) (see #4896)
- I tried having the proxy support https requests doing tunneling similar to [goproxy](https://github.com/elazarl/goproxy/blob/7cc037d33fb57d20c2fa7075adaf0e2d2862da78/https.go#L127-L156), it didn't work but here's the [code](https://github.com/elastic/elastic-agent/commit/ea748115e579dfd8326f58de563ae4021ded26f6) for reference

The testcase is [`TLSEnrollProxy-mTLSProxyInThePolicy`](https://github.com/elastic/elastic-agent/pull/4770/files#diff-1fbc90643f8ebd353bb15ab983de102a2d80a949dffdb9e5ba118548341c6bc6R523-R666) where we try to test this scenario.

In order to test such scenario we would need at least one of 2 things:
- an https proxy that can terminate TLS and forward plain http requests to the mock fleet server (either extend proxy test or swap out for some other proxy implementation)
- have an https fleet endpoint (either mocked or the real thing in a cloud deployment), ideally where we can set up (m)TLS with custom CAs (this is not possible at the moment on ESS)

### Conclusion:
[testproxy](https://github.com/elastic/elastic-agent/tree/main/testing/proxytest) needs to proxy HTTPS requests. 
Once https://github.com/elastic/elastic-agent/issues/5715 is completed, implement the chosen solution on [testproxy](https://github.com/elastic/elastic-agent/tree/main/testing/proxytest)

**Comment by AndersonQ** [comment]
I might be worth looking at how [Caddyserver](https://caddyserver.com/) [does that](https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/reverseproxy.go#L391) as well
