### ISSUE TITLE
crash when logging empty line

### ISSUE THREAD

**Issue by seanstory** [elastic/elastic-agent#4907]
- Version: 8.13.2
- Operating System: OSX 14.5
- Steps to Reproduce:
  1. create a new component binary or modify one
  2. have your component log an empty line. In python, I did: 
    ```
    print(f"""
    This line has text
    this line too. But not the next
    
    """)
    ```
  3. modify `elastic-agent.yml` to use your new/modified component
  4. run `./elastic-agent`

It crashes with an error like:
```
$ sudo ./elastic-agent
panic: runtime error: index out of range [0] with length 0

goroutine 186 [running]:
github.com/elastic/elastic-agent/pkg/component/runtime.(*logWriter).Write(0x140003de320, {0x14000684000, 0xf0, 0x8000})
	github.com/elastic/elastic-agent/pkg/component/runtime/log_writer.go:110 +0x490
io.copyBuffer({0x106cf8620, 0x140003de320}, {0x106cf4538, 0x140001a8230}, {0x0, 0x0, 0x0})
	io/io.go:432 +0x1a8
io.Copy(...)
	io/io.go:389
os/exec.(*Cmd).writerDescriptor.func1()
	os/exec/exec.go:560 +0x44
os/exec.(*Cmd).Start.func2(0x0?)
	os/exec/exec.go:717 +0x34
created by os/exec.(*Cmd).Start in goroutine 184
	os/exec/exec.go:716 +0x7bc
```

**Comment by ycombinator** [comment]
Hi @seanstory, please share your complete `elastic-agent.yml`.  Also, what do you mean by "component" in this context?

**Comment by cmacknz** [comment]
Component is a process run by agent, this issue was discovered in the process of writing a new agent sub-process.

This should be reproducible with [our fake-component](https://github.com/elastic/elastic-agent/tree/2e09c338649956f697a820c9d2602a20461a7e36/pkg/component/fake/component)

**Comment by ycombinator** [comment]
Ah, thanks @cmacknz, sounds like you had the additional context I was missing for triage.
