### ISSUE TITLE
"Network Packet Capture" v0.9.0 integration, no logs in dashboards

### ISSUE THREAD

**Issue by rusqq** [elastic/elastic-agent#491]
**- Version:** Elastic 8.2.0, basic license, test environment, x-pack security enabled
**- Operating System:** Ubuntu 20.04 LTS
**- Discuss Forum URL:** https://elasticstack.slack.com/archives/C02J2JBS0FP/p1653995022687149
**- Steps to Reproduce:**

1. Add "Network Packet Capture" integration, version 0.9.0,
2. create a new policy or add it to existing one, enable "Packet Capture" and add some protocols to capture: dhcp, dns, flows, http/https
3. deploy the integration to agents (on windows 10) through Fleet,
4. **update: integration with elastic agent on linux machine works correctly!**
5. you should see any logs in preconfigured dashboards or in discover tab, but no logs has appeared

**- Additional information:**
1. Inges pipeline has been created, index templates as well:
![image](https://user-images.githubusercontent.com/96235374/171354066-687da9f9-c356-412f-a444-884a47c944cc.png)
2. data stream for the integration **has not been** created:
![image](https://user-images.githubusercontent.com/96235374/171354215-b79c8645-4871-4b7b-8097-bc44ddbe3034.png)
3. packetbeat is probably running:
`{"log.level":"info","@timestamp":"2022-05-31T11:40:23.820Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-05-31T13:40:23+02:00 - message: Application: packetbeat--8.2.0[...]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}`
4. I changed agent logging level to "debug", you see that some plugins has been registered, but mostly you see timeouts
![image](https://user-images.githubusercontent.com/96235374/171354553-a63590d1-b538-4ac8-bc58-842cec5c05a4.png)
![image](https://user-images.githubusercontent.com/96235374/171354707-e06235dc-b2f9-46ab-abe6-3ba9fa82d2b4.png)
6. Also I would like to confirm that other integrations works correctly including suricata, elastic security, windows logs etc

**Comment by buzzdeee** [comment]
I created a elastic cloud trial instance just yesterday, and ran into the same issue. I am mostly interested in DNS, so I took a closer look there. The visuals in the dashboard use the "[Network Packet Capture] DNS Protocol" saved search. The agent is a Windows agent. When I look closer, I see DNS requets logged from that host, but of: 

```
data_stream.dataset: endpoint.events.network
network.protocol: dns
```

agent is 8.2.3.

A linux agent with same version properly reports DNS requests, they show up in the saved search.

**Comment by rusqq** [comment]
@buzzdeee I updated today the integration to the newest version and it works with windows already

**Comment by rusqq** [comment]
Hi @buzzdeee, could you please show where I can define the interface I would like to listening on? I don't see this option anywhere.

Regarding the bug, it is very weird but this integration is listening on my L2VPN interface. I noticed it today. But still I dont' see an option to change it

**Comment by buzzdeee** [comment]
@rusqq 

answering late, but the option to set the interface ID (number) you get from running "packetbeat devices" is hidden behind the advanced options in the general settings of the integration, see attached screenshot.

![image](https://user-images.githubusercontent.com/8383396/182815411-b2ee0765-b40d-4695-afd5-d997a9f1ef8f.png)

**Comment by jlind23** [comment]
[Clean up] This hasn't been looked up nor haven't any traction for the past two years hence closing. I am happy to reopen if need be.
cc @ycombinator
