### ISSUE TITLE
8.3.0-SNAPSHOT Docker image is failing

### ISSUE THREAD

**Issue by barkbay** [elastic/elastic-agent#492]
The [ECK CI pipeline detected](https://github.com/elastic/cloud-on-k8s/issues/5720) that the last `8.3.0-SNAPSHOT` Docker image (`sha256:40fb58829895eb07f7c16df1788639a715ba28cd8cc40ef5b4f7d3393522cbc7`) is failing.
I can reproduce the error with `docker run`:

```
docker run --rm docker.elastic.co/beats/elastic-agent:8.3.0-SNAPSHOT
Error: could not load agent info: storing generated agent id: open /usr/share/elastic-agent/state/data/vault/2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b: no such file or directory
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.3/fleet-troubleshooting.htm
```

I would like to know if the problem comes from the image itself, or from the way the image is started by the operator.
Thanks!
🙇

**Comment by barkbay** [comment]
Might be related to https://github.com/elastic/elastic-agent/pull/495

**Comment by jlind23** [comment]
Hasn't show up in a while / outdated. Closing.
