### ISSUE TITLE
QA test: State Store migrations

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#4962]
Test scenarios:
 - Action store -> JSON state store
 - State Store (YAML) -> JSON state store

### Action store -> JSON state store
 - Install and enroll a 7.17 Elastic Agent
 - upgrade to s build containing https://github.com/elastic/elastic-agent/pull/4441
 - ensure the agent is healthy, connected to fleet and with a valid configuration
   - use the agent status command to check it's healthy and connected to fleet
   - check on fleetUI the agent is healthy
   - use the inspect command to ensure the agent's local copy of the policy is correct

### State Store (YAML) -> JSON state store
 - Install and enroll the latest released Elastic Agent
 - upgrade to s build containing https://github.com/elastic/elastic-agent/pull/4441
 - ensure the agent is healthy, connected to fleet and with a valid configuration
   - use the agent status command to check it's healthy and connected to fleet
   - check on fleetUI the agent is healthy
   - use the inspect command to ensure the agent's local copy of the policy is correct

**Comment by AndersonQ** [comment]
@amolnater-qasource if you have any question, let me know or ping me on slack.

**Comment by amolnater-qasource** [comment]
Hi @AndersonQ 

We have revalidated this issue on latest 8.15.0-SNAPSHOT kibana and had below observations:

**Observations:**
- On upgrading 7.17.22 and 8.14.1 running Agent status command- All the components remain in Running state.
- Post upgrade agents remain Healthy.
- On running Inspect command, agent policy is correct.

**Steps followed:**
1. Install 7.17.22 and 8.14.1 agent.
2. Upgrade both the agents to latest 8.15.0 SNAPSHOT : `https://snapshots.elastic.co/8.15.0-f2f3669f/downloads/`.
3. Run `sudo elastic-agent status`.
4. Observe agent status under Fleet>Agents tab.
5. Run `sudo elastic-agent inspect`.

**7.17.22 status and inspect command before upgrade:**
[beforeUpgrade717.txt](https://github.com/user-attachments/files/16051062/beforeUpgrade717.txt)

**7.17.22 status and inspect command after upgrade:**
[afterUpgrade717.txt](https://github.com/user-attachments/files/16051141/afterUpgrade717.txt)

**8.14.1 status and inspect command before upgrade:**
[beforeUpgrade8141.txt](https://github.com/user-attachments/files/16051375/beforeUpgrade8141.txt)

**8.14.1 status and inspect command after upgrade:**
[afterUpgrade8141.txt](https://github.com/user-attachments/files/16051557/afterUpgrade8141.txt)

**Build details:**
VERSION: 8.15.0 SNAPSHOT
BUILD: 75836
COMMIT: 28cad8dff93db87cc8045c5871d77a7936a8b0d2
Artifact Link: https://snapshots.elastic.co/8.15.0-f2f3669f/downloads/beats/elastic-agent/elastic-agent-8.15.0-SNAPSHOT-linux-x86_64.tar.gz

Please let us know if we are missing anything here.

Thanks!

**Comment by jlind23** [comment]
Thanks @amolnater-qasource! Closing this issue as done then.

**Comment by amolnater-qasource** [comment]
Thank you for confirming! @jlind23
