### ISSUE TITLE
[Fleet]: Multiple logs: `[elastic_agent][info] got checkin with pid 0` are generated for installed agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#4974]
**Kibana Build details:**
```
VERSION: 8.15.0 SNAPSHOT
BUILD: 73762
COMMIT: 2a492e1625f24336f3259b2b8df62b2b18127e81
```
Artifact Link: https://staging.elastic.co/8.14.0-7c638435/downloads/beats/elastic-agent/elastic-agent-8.14.0-darwin-aarch64.tar.gz

**Preconditions:**
1. 8.15.0-SNAPSHOT Kibana cloud environment should be available.
2. Linux agent should be installed.

**Steps to reproduce:**
1. Navigate to Fleet>Agents> Logs tab.
2. Observe multiple logs: `[elastic_agent][info] got checkin with pid 0` are generated.

**Expected Result:**
Multiple logs: `[elastic_agent][info] got checkin with pid 0` should not be generated for installed agent.

**Logs:**
[elastic-agent-diagnostics-2024-06-21T06-21-13Z-00.zip](https://github.com/user-attachments/files/15923565/elastic-agent-diagnostics-2024-06-21T06-21-13Z-00.zip)

**Screen Recording:**

https://github.com/elastic/elastic-agent/assets/77374876/305d82dd-784c-4e8a-b1aa-81a1aefc6f0b

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by pierrehilbert** [comment]
@fearful-symmetry this is coming from your change here: https://github.com/elastic/elastic-agent/pull/4789/files#diff-4e32865414ba3059d62335e030cac16c6c68a01134ce4ef03076e75da18b5fa9

Could you please fix it? We shouldn't spam that many logs especially in info level.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.15.0 BC2 kibana cloud environment and found it fixed now.

**Observations:**
- No spamming logs: [elastic_agent][info] got checkin with pid 0 are generated for installed agent. 

**Logs:**
[elastic-agent-diagnostics-2024-07-18T11-11-54Z-00.zip](https://github.com/user-attachments/files/16282440/elastic-agent-diagnostics-2024-07-18T11-11-54Z-00.zip)


**Screenshot:**
![image](https://github.com/user-attachments/assets/20403132-3a51-47a4-b1ad-7c2786373fd6)

**Build details:**
```
VERSION: 8.15.0 BC2
BUILD: 76111
COMMIT: 8d6510f30e7a52246ccebbf7d913a59b498c3bc2
```
Artifact Link: https://staging.elastic.co/8.15.0-a47a2107/summary-8.15.0.html#elastic-agent-package

Hence we are marking this issue as QA:Validated.

Thanks!
