### ISSUE TITLE
Regarding Standalong elastic agent

### ISSUE THREAD

**Issue by Anu-Ra-g** [elastic/elastic-agent#5114]
I'm using elastic cloud and I'm trying to install an standalone elastic agent on a server. The agent gets installed on the system with this below message but it is not showing on the elastic cloud dashboard.
```
elastic-agent-8.13.4-linux-x86_64$ sudo ./elastic-agent install
[sudo] password for anurag: 
Elastic Agent will be installed at /opt/Elastic/Agent and will run as a service. Do you want to continue? [Y/n]:Y
Do you want to enroll this Agent into Fleet? [Y/n]:n
[ ===] Service Started  [2s] Elastic Agent successfully installed, starting enrollment.
[ ===] Done  [2s]                        
Elastic Agent has been successfully installed.
```

**Comment by pierrehilbert** [comment]
Hello,
The main difference between a standalone agent and a managed agent is that the second one is managed by Fleet and therefore visible in your Elastic Cloud Dashboard. 
You should now enroll your enjoy in Fleet if you want to have it there.
