### ISSUE TITLE
Automatically verify links in OTel README file

### ISSUE THREAD

**Issue by andrzej-stencel** [elastic/elastic-agent#5117]
it looks good, i was wondering if we should do some kind of validation to check remote part exists, but this could be problematic in CI in case if there are traffic filters.

_Originally posted by @michalpristas in https://github.com/elastic/elastic-agent/pull/5087#pullrequestreview-2168896679_
            
The [OTel README file](https://github.com/elastic/elastic-agent/blob/47e87690bf5134aa60c1c6b99ac2b364363ab9fb/internal/pkg/otel/README.md) has links to components that are created automatically by the `mage otel:readme` command. We should have a tool to automatically check that the links are valid (point to something that exists).

We could use https://github.com/tcort/markdown-link-check/ or similar solution for this.

**Comment by ycombinator** [comment]
> The [OTel README file](https://github.com/elastic/elastic-agent/blob/47e87690bf5134aa60c1c6b99ac2b364363ab9fb/internal/pkg/otel/README.md) has links to components that are created automatically by the mage otel:readme command. We should have a tool to automatically check that the links are valid (point to something that exists).

Would it make sense for `mage otel:readme` to itself to perform this check before it creates the link?  Additionally, it might be good for `mage check` to perform the same check as well, in case links that used to work at creation time have since stopped working for some reason.

**Comment by mauri870** [comment]
A pure Go alternative that we can use is https://github.com/rednafi/link-patrol.
