### ISSUE TITLE
[MAC 12]: Two `elastic-agent-` folders with different hash under `Elastic/Agent/data` folder.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#517]
**Kibana version:**  8.3 BC2 Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.3.0
BUILD: 53231
COMMIT: 25476b531ba9f32292bde85508d342aa5e1c29eb
Artifact Link: https://staging.elastic.co/8.3.0-fcd43da7/downloads/beats/elastic-agent/elastic-agent-8.3.0-darwin-x86_64.tar.gz
```

**Preconditions:**
1. 8.3 BC2 Kibana cloud environment should be available.
2. MAC agent must be installed using policy having System integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to installed location at `/Library/Elastic/Agent/data/`.
3. Observe two different hash elastic-agent folders available under data folder:

**Screenshot:**
![8](https://user-images.githubusercontent.com/77374876/172150085-307f8a35-5868-4b5a-8270-115470c36c94.JPG)

**Expected Result:**
Single folder with hash- `elastic-agent-8907dd` should exist for mac agent under `Elastic/Agent/data`.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
Not relevant anymore.
