### ISSUE TITLE
E2E Test: escaping secrets in policy

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#5320]
Add an E2E test for https://github.com/elastic/kibana/issues/188377, wherein the test should create a policy containing the custom logs integration with a custom configuration like so:
```
custom.key: $$$$
```

The test should enroll Agent in Fleet using the created policy and ensure that the configuration sent to the relevant Beat contains `custom.key: $$$$` as well.

**Comment by kaanyalti** [comment]
Blocked due to the error mentioned in the following thread 
https://elastic.slack.com/archives/C01QQ449KE1/p1730105993673769
