### ISSUE TITLE
Windows Agent shows missed check-ins and degraded status after NTP Sync and manual time adjustments.

### ISSUE THREAD

**Issue by harshitgupta-qasource** [elastic/elastic-agent#5363]
**Kibana Build details:**
```
VERSION: 8.16.0 SNAPSHOT
BUILD: 77679
COMMIT: 6b091fe3b410eaae9d4805c0a3c0ea6168bf66b0

VERSION: 8.15.1 SNAPSHOT
BUILD: 76479
COMMIT: d3293f748cb6d5a16fcc398cf0253fa2c4cc1552
```
**Host OS** Windows Server 2022

**Preconditions:**
1. 8.16.0 SNAPSHOT Kibana Cloud environment should be available.
2. 8.15.1 / 8.16.0 Windows agent should be installed.

**Steps to reproduce:**

1. On the Windows VM, navigate to Windows settings and turn on NTP sync.
2. Install the elastic-agent on the Windows machine.
3. Every 10 seconds, manually increase the system time by 1 minute.
4. Continue this process for 2 minutes.
5. Observe the logs for missed check-ins and notice the component status changes from Healthy to Degraded.

**Expected:**
Windows Agent shouldn't display missed check-ins and degraded status after NTP Sync and manual time adjustments.

**Screenshot:**
**8.15.1**
![Image](https://github.com/user-attachments/assets/87fd332a-377a-4d0b-b63d-aaaa3820c72b)

**8.16.0**
![Image](https://github.com/user-attachments/assets/91e62b49-06ad-4faa-ba64-260106f35ee1)

**Agents Logs**
[elastic-agent-diagnostics-2024-08-27T11-06-19Z-00.zip](https://github.com/user-attachments/files/16761236/elastic-agent-diagnostics-2024-08-27T11-06-19Z-00.zip)

**Feature Ticket:**
https://github.com/elastic/elastic-agent/pull/5284

**Comment by harshitgupta-qasource** [comment]
@amolnater-qasource Kindly review

**Comment by amolnater-qasource** [comment]
Secondary review for this ticket is done.

**Comment by pierrehilbert** [comment]
@leehinman could it be related to your lately changes?

**Comment by leehinman** [comment]
can we re-test?

1 missed check-in isn't a problem, if we are getting multiple such that we hit lines like:

```
{"log.level":"error","@timestamp":"2024-08-27T20:20:40.278Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":624},"message":"Unit state changed winlog-default (HEALTHY->FAILED): Failed: pid '3792' missed 3 check-ins and will be killed","log":{"source":"elastic-agent"},"component":{"id":"winlog-default","state":"FAILED"},"unit":{"id":"winlog-default","type":"output","state":"FAILED","old_state":"HEALTHY"},"ecs.version":"1.6.0"}
```

That is the real problem.

I tested on 8.14.3 with NTP enabled and if I enroll and start agent, and then in a PowerShell run as Admin run the following script:

```
while (1 -eq 1) {
    Set-Date -Date (Get-Date).AddSeconds(97)
	start-sleep -seconds 11
}
```

We will see lots of lines about 1 missed check-ins in the logs, and usually within 10 minutes I will see the "missed 3 check-ins" and the process is restarted.

When I switch to 8.16.0 that is newer than `commit 129c8c458f231b97d66af860a3dfe2b7a5113d03` I don't see any missed check-ins

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.16.0 SNAPSHOT and 8.14.3 kibana cloud environment and has below observations

**Observations:**
- We ran the same script in our Powershell admin for both 8.14.3 and 8.16.0 agents.

- Observed error logs for both the agents: `[elastic_agent][error] Component state changed log-default (DEGRADED->FAILED): Failed: pid '1632' missed 3 check-ins and will be killed`

- We have shared the logs below for your reference:

**Agents Logs**
- 8.14.3:
[elastic-agent-diagnostics-2024-08-29T14-36-05Z-00.zip](https://github.com/user-attachments/files/16797953/elastic-agent-diagnostics-2024-08-29T14-36-05Z-00.zip)

- 8.16.0-SNAPSHOT:
[elastic-agent-diagnostics-2024-08-29T14-17-16Z-00.zip](https://github.com/user-attachments/files/16797939/elastic-agent-diagnostics-2024-08-29T14-17-16Z-00.zip)


**Screen Shot:**
- 8.14.3
![Image](https://github.com/user-attachments/assets/e968aafc-3707-4e78-9c24-a3311b3cf079)

- 8.16.0 
![Image](https://github.com/user-attachments/assets/9d6d4873-f6d0-45a1-a1a5-f0352c901cd3)


**Build details:**
VERSION: 8.16.0
BUILD: 77768
COMMIT: ecec57ca52a3b00c6a2ab2cf36b2ec9a7c4d1981
ARTIFACT: https://snapshots.elastic.co/8.16.0-4647f73c/downloads/beats/elastic-agent/elastic-agent-8.16.0-SNAPSHOT-windows-x86_64.zip

Please let us know if we are missing anything here.

Thanks!

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have re-validated this issue on the latest 8.16.0 SNAPSHOT Kibana cloud environment and had below observation:

Observations:
- No new check-in errors were observed on the latest artifact.
- After approximately 5 minutes, we stopped the time forwarding script and then updated the logging level to debug, but no new debug logs were generated.

Could you please confirm if this is expected?

**Build details:**
VERSION: 8.16.0 SNAPSHOT
BUILD: 77913
COMMIT: f2aba4624160124344e98dac19d5eefd83fa79ce

**Screen-Shot:**
![Image](https://github.com/user-attachments/assets/4b2d67ef-569d-424e-aaf4-27ab61425c35)
![Image](https://github.com/user-attachments/assets/ec14eb4a-9177-40f4-8cf3-d6f7d31af14a)

**Agent Logs**
[elastic-agent-diagnostics-2024-09-03T12-40-44Z-00.zip](https://github.com/user-attachments/files/16848597/elastic-agent-diagnostics-2024-09-03T12-40-44Z-00.zip)

Kindly let us know if we are missing anything here.

Thanks

**Comment by leehinman** [comment]
diagnostics look normal to me.  I think the issue with the logs showing up is that the time has been increased, so the log is in the future as far as the log viewer is concerned.

**Comment by harshitgupta-qasource** [comment]
Thanks for the update.
We are Closing this issue and marking this as QA:Validated
