### ISSUE TITLE
[Elastic Agent] Add a new Custom Filestream integration

### ISSUE THREAD

**Issue by nimarezainia** [elastic/elastic-agent#5370]
Our current Custom log integration is based on the log input which is now being deprecated. We therefore need to introduce a Custom Filestream integration so users can migrate over to using this integration instead.

**Comment by ycombinator** [comment]
@nimarezainia Should this issue be moved to the https://github.com/elastic/integrations/ repo as that's where the [custom log integration](https://github.com/elastic/integrations/tree/main/packages/log) is defined?

**Comment by nimarezainia** [comment]
> [@nimarezainia](https://github.com/nimarezainia) Should this issue be moved to the https://github.com/elastic/integrations/ repo as that's where the [custom log integration](https://github.com/elastic/integrations/tree/main/packages/log) is defined?

No I believe that this is owned by the data plane team. (fyi @flexitrev )

**Comment by nimarezainia** [comment]
Linking these here for record keeping:

https://github.com/elastic/integrations/pull/4609
https://github.com/elastic/ingest-dev/issues/1384

**Comment by belimawr** [comment]
Could we migrate the Custom Logs integration to use Filestream instead? We have the take-over mode in Filestream that is capable of getting the state from a file being harvested by the Log input and use it in the Filestream input, the only thing missing is an automated way to convert the configuration (specially the custom configuration field). It might also need some extra work because the way the Elastic-Agent divides the integrations per input type when starting component.s

Just adding a new integration might make it harder to migrate the state and confusing for users finding both when searching.

**Comment by nimarezainia** [comment]
@belimawr would you be merging this [PR](https://github.com/elastic/integrations/pull/4609) again as part of this issue?

**Comment by belimawr** [comment]
> [@belimawr](https://github.com/belimawr) would you be merging this [PR](https://github.com/elastic/integrations/pull/4609) again as part of this issue?

Do you mean reverting it? That's an option and it's an interesting starting point. My first idea was to just copy the Custom Logs integration, edit it to use filestream and update the docs, but I can start from reverting this PR as well.

**Comment by belimawr** [comment]
Folks, I create a [draft PR](https://github.com/elastic/integrations/pull/11332), there are I'd like your opinion on (@nimarezainia, @jlind23)
**1. Should we expose file identities other than fingerprint?**
File identity docs: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html#_file_identity_2

Currently I'm using fingerprint as the only option and allowing to configure the offset and length. I believe that is the best option because this is the file identity we implemented to solve the issues we were having with inode reuse and the one we recommend to our users.

The reason I did not add any of the other ones is because while I can define a variable/input field as a selection from a list, the template language used is somehow limited and there is no way to use this selection values to render the correct policy. Having all options a boolean/toggle is very confusing because only one can be used at a time. I asked on slack for some suggestions/help, if there is a way

**2. Which name do we want for the integration?**
Currently it's "Custom Filestream Logs" (from "reverting" and updating the [PR](https://github.com/elastic/integrations/pull/4609)  removing it), however having "Custom logs" and "Custom Filestream Logs" can be confusing... Even the description is not very helpful in answering which one should be used.
![Image](https://github.com/user-attachments/assets/ae1f6f99-15ed-4d98-ab16-a5941c8ff96a)

I was thinking about something like "Custom Logs V2","Custom Logs enhanced", something that makes it clear this one should be used instead of the "Custom Logs".

**3. Is there any preference for the initial version?**
Currently I put `0.0.1` because it is the very first release, the old one had `1.0.0` as the initial release. I'm not 100% sure what is the standard we use for integrations.

**4. When do we need to release the first version?**
I'm asking because if question 1., one way to solve is is to get a small change in Kibana to add template helpers that will allow me to implement the logic I need. my JS foo is rusty, but I could even give it a shot, but I don't know how long it would take to get the change in and it will make the integration require the newest version of Kibana, which might not be ideal.

**Comment by cmacknz** [comment]
> Currently I'm using fingerprint as the only option and allowing to configure the offset and length. I believe that is the best option because this is the file identity we implemented to solve the issues we were having with inode reuse and the one we recommend to our users.

If people want to use the take over mode to migrate from custom logs one day, do we want to give them the option to do that with the same file identity? I think this might actually be a requirement of the take over mode (once it actually works for Elastic Agent).

**Comment by jlind23** [comment]
> Currently it's "Custom Filestream Logs" (from "reverting" and updating the https://github.com/elastic/integrations/pull/4609 removing it), however having "Custom logs" and "Custom Filestream Logs" can be confusing... Even the description is not very helpful in answering which one should be used.

IIRC we spoke with @nimarezainia  and @strawgate  about renaming "Custom logs" to "Custom logs (Legacy)" so naming this one "Custom Filestream Logs" would make sense.

**Comment by belimawr** [comment]
> > Currently it's "Custom Filestream Logs" (from "reverting" and updating the [elastic/integrations#4609](https://github.com/elastic/integrations/pull/4609) removing it), however having "Custom logs" and "Custom Filestream Logs" can be confusing... Even the description is not very helpful in answering which one should be used.
> 
> IIRC we spoke with [@nimarezainia](https://github.com/nimarezainia) and [@strawgate](https://github.com/strawgate) about renaming "Custom logs" to "Custom logs (Legacy)" so naming this one "Custom Filestream Logs" would make sense.

Would this rename happen at the same time/version where we release the Custom Filestream logs?

**Comment by belimawr** [comment]
> > Currently I'm using fingerprint as the only option and allowing to configure the offset and length. I believe that is the best option because this is the file identity we implemented to solve the issues we were having with inode reuse and the one we recommend to our users.
> 
> If people want to use the take over mode to migrate from custom logs one day, do we want to give them the option to do that with the same file identity? I think this might actually be a requirement of the take over mode (once it actually works for Elastic Agent).

That makes sens. Then we need to find the best way to help users not to create an invalid configuration for their Filestream integration. I'll look into this.

**Comment by jlind23** [comment]
> Would this rename happen at the same time/version where we release the Custom Filestream logs?

Once the Custom Filestream logs integration is published we would have to create a new PR that will update the Custom Log title, yes.

**Comment by nimarezainia** [comment]
> > Would this rename happen at the same time/version where we release the Custom Filestream logs?
> 
> Once the Custom Filestream logs integration is published we would have to create a new PR that will update the Custom Log title, yes.

@belimawr 
Yes this can happen at some other point. the idea is that at some point the whole "Custom Log" integration will be deprecated (and that would show in the title).

Regarding configurations available: all the options available to configure filestream should be configurable. e need to accommodate a user migrating from Custom Logs integration to Custom Filestream Logs.

**Comment by belimawr** [comment]
> If people want to use the take over mode to migrate from custom logs one day, do we want to give them the option to do that with the same file identity? I think this might actually be a requirement of the take over mode (once it actually works for Elastic Agent).

I did some testing and looked at the code for the take over mode, currently it only works if the file identity used is the same for the log and filestream inputs.


> Regarding configurations available: all the options available to configure filestream should be configurable. e need to accommodate a user migrating from Custom Logs integration to Custom Filestream Logs.

@nimarezainia, I made all configurations available, however for the [file_identity](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html#_file_identity_2) I only added an option for fingerprint. My reasoning is:
- The fingerprint is our current recommended file identity, it solves the inode reuse from the native file identity and is much more versatile than the path.
- Only one file identity can be enable
- Our current policy template features does not allow for a drop down menu that can be used to implement the more complex template logic required by file identity
- I'm having a hard time thinking about any scenario where the fingerprint file identity cannot be used/replace the others.

Here is how this part of the configuration looks like:
![Image](https://github.com/user-attachments/assets/bd15549c-5581-4b0e-a3cb-cc9d9d8527d4)

**Comment by nimarezainia** [comment]
@belimawr don't think about it too much :-) - file identity is fine. We can capture requirements if they come up.

**Comment by belimawr** [comment]
> > The fingerprint is our current recommended file identity, it solves the inode reuse from the native file identity and is much more versatile than the path.
> 
> The fingerprint identity will be enabled by default, right?

At the moment it's not on the draft PR, but that's a very good point, I'll enable it by default.

**Comment by mbudge** [comment]
https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html

Will the parsers section be included to configure multiline messages?

**Comment by belimawr** [comment]
> https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html
> 
> Will the parsers section be included to configure multiline messages?

Yes, the parsers will be there, the goal is to support all configuration options from Filestream.

**Comment by mbudge** [comment]
Would be useful to remove/clean the registry file through Fleet UI.

I've got to re-process the previous 3 months of 5 log files from several servers.

I don't have access to the servers.

**Comment by belimawr** [comment]
> Would be useful to remove/clean the registry file through Fleet UI.
> 
> I've got to re-process the previous 3 months of 5 log files from several servers.
> 
> I don't have access to the servers.

At the moment, the state folder (where the registry resides) is per process Elastic-Agent is running, each process runs a single type of input, so one process might run inputs from different integrations. If you have a policy with multiple integrations, that might trigger re-ingestion of more data than you want. Anyways, here are some options to accomplish that today via Fleet UI:
- Change the output of the integration (as long as it's a different output entry on Fleet settings, it will work), it can be the same ES cluster.
- Delete and re-add the integration

Nevertheless, that's an interesting feature request.

**Comment by strawgate** [comment]
Mentioned this in the PR but I believe users migrating from a log integration can temporarily use `ignore_inactive: since_first_start` to set the offset in the registry to the end of discovered files and avoid reingestion.

Similarly ignore_older can help as well

**Comment by mbudge** [comment]
Looks like the dataset option is fleet overrides the event.dataset value I set in the filebeat processors section. 

I want to avoid creating too many data streams for some application logs we're collecting.

**Comment by nimarezainia** [comment]
@flexitrev and @belimawr would you know if this is possible?

**Comment by belimawr** [comment]
@nimarezainia, @Alphayeeeet , unfortunately, this is not supported under Elastic-Agent yet. The Elastic-Agent runs different process with different state folders for the `log` and `filestream` inputs, so the Filebeat running the `filestream` input does not have access to the states from the Filebeat running the `log` input.

We have an internal ticket to implement this and we expect to start working on this soon.

**Comment by Alphayeeeet** [comment]
@belimawr Thank you for the info. Could you keep me posted on this thread for any future updates regarding the migration or is there a public issue as well, which gets updates on the topic?

**Comment by mbudge** [comment]
Just an FYI I noticed there isn't an option to read from the beginning of the file. I think the custom log integration supported that.

**Comment by belimawr** [comment]
> Just an FYI I noticed there isn't an option to read from the beginning of the file. I think the custom log integration supported that.

@mbudge, what do you mean by "an option to read from the beginning of the file"? Both, the log and filestream integrations will always start reading new files from the beginning.

**Comment by belimawr** [comment]
> [@belimawr](https://github.com/belimawr) Thank you for the info. Could you keep me posted on this thread for any future updates regarding the migration or is there a public issue as well, which gets updates on the topic?

I'll do my best to post updates. At the moment we do not have a public issue to track this.

**Comment by Alphayeeeet** [comment]
@belimawr Any updates on the migration support for Elastic Agent by now?

**Comment by belimawr** [comment]
> [@belimawr](https://github.com/belimawr) Any updates on the migration support for Elastic Agent by now?

Hi @Alphayeeeet, I've been working on it, you can follow some of the progress on my [draft PR](https://github.com/elastic/beats/pull/46587). I cannot make any promises about when it will be released. It takes a while to ensure all corner cases are covered and there is no issue with the state migration.
