### ISSUE TITLE
Download Elastic Agent auto select platform

### ISSUE THREAD

**Issue by ruflin** [elastic/elastic-agent#545]
When I go on my Mac with the Chrome browser to the [elastic-agent download page](https://www.elastic.co/downloads/elastic-agent) it shows me to download it for Linux 64-bit as selected option. It would be nice if by default it would auto select for me macOS with the correct arch to make getting started.

Interesting enough, if I go to the Kibana or Elasticsearch download pages, it has Windows as the default platform selected and macOS as the second option instead of having it at the bottom like with Elastic Agent. Not sure what the logic shared is between these different download pages.

**Comment by ph** [comment]
@sylvie777 I am not sure where this auto-select feature is developed I would assume this fall under the website team but I don't know? Should we create the issue there? 

@pierrehilbert Low priority but if you can find where this should be done.

**Comment by sylvie777** [comment]
@ph The order of the packages listed in the dropdown is set by the `download-page-publisher`, which is managed by the Engineering team.

**Comment by sylvie777** [comment]
@ph Web team can look into auto-selecting packages based on OS, as long as no content blockers are in use. :) If this is a feature you'd like to have set up, please submit a ticket in the [Website Requests repo](https://github.com/elastic/website-requests/issues/new/choose) with all the details.

**Comment by ph** [comment]
I've moved the request to the website repo and I will close this one.
