### ISSUE TITLE
Mark the Elastic Agent Helm Chart as beta

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#5485]
**Describe the enhancement:**

In https://github.com/elastic/elastic-agent/pull/5331, we added a Helm Chart for Elastic Agent.  For the moment, we would like to mark this chart as beta.

**Describe a specific use case for the enhancement or feature:**

To set appropriate expectations around stability and supportability of the Helm Chart with its users.

**What is the definition of done?**

TBD — we need to first decide how best to mark the chart as beta.

Related: https://github.com/elastic/elastic-agent/issues/5486

**Comment by ycombinator** [comment]
_Copied from https://github.com/elastic/elastic-agent/pull/5331#issuecomment-2338320617, where @pkoutsovasilis said:_

Just thinking out loud the available options here:

1. I assume that we can push the helm chart with a beta suffix at the version and update the NOTES.txt accordingly here https://helm.elastic.co/
2. Somebody that wants to try this helm chart can clone the repo and install the helm chart from the folder `deploy/helm/elastic-agent`
3. We could utilise github pages on this repo and commit directly the helm chart package.tgz (that points to the SNAPSHOT agent image)  [my least favourite option]

that's why a discussion about the Helm chart release process is wise to have before any next step 🙂

**Comment by ycombinator** [comment]
_Copied from https://github.com/elastic/elastic-agent/pull/5331#issuecomment-2338484088, where @swiatekm said:_

Helm Charts use [semver 2.0](https://semver.org/) for versioning, so it's simple enough to just designate our releases as betas by setting it to `va.b.c-beta.d` or something similar. This makes Helm automatically treat it as a prerelease. This will cause them not to show up in searches without the `--devel` flag, amongst other consequences.

**Comment by ycombinator** [comment]
cc: @cmacknz

**Comment by swiatekm** [comment]
I like @pkoutsovasilis's option 1. I don't see any reason to make things complicated if we already have a Helm repo we can push to.

**Comment by ycombinator** [comment]
Seems like we have consensus on this option:

> push the helm chart with a beta suffix at the version and update the NOTES.txt accordingly here https://helm.elastic.co/

@pkoutsovasilis Could you please close this issue when the above is done?
