### ISSUE TITLE
Replace Ubuntu 20.04 with 24.04 for Docker base images

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#5501]
**Describe the enhancement:**

Ubuntu 20.04's standard support [ends](https://ubuntu.com/about/release-cycle) in April 2025.  Before then, we should change our Docker base images to use Ubuntu 24.04 instead.

**Describe a specific use case for the enhancement or feature:**

To use a supported base image for our Docker images.

**What is the definition of done?**

Elastic Agent's Ubuntu-based Docker images use Ubuntu 24.04

**Comment by jlind23** [comment]
FWIW looks like Elastic-Agent changes have to happen in two different places:
- https://github.com/elastic/elastic-agent/blob/main/pkg/testing/define/batch_test.go
- https://github.com/elastic/elastic-agent/blob/main/dev-tools/packaging/packages.yml

**Comment by jlind23** [comment]
@cmacknz would 22.04 be the right call or shall we directly jump to 24.04?

**Comment by ycombinator** [comment]
Discussed in a leads meeting today and the decision was to jump directly to 24.04.  Updated the issue title and description accordingly.
