### ISSUE TITLE
Allow to configure the Fleet Server internal host

### ISSUE THREAD

**Issue by AndersonQ** [elastic/elastic-agent#5554]
**Describe the enhancement:**

Allow to configure the Fleet Server host used by the Elastic Agent when bootstrapping Fleet Server

**Describe a specific use case for the enhancement or feature:**

When using mTLS the Elastic Agent and Fleet Server should be able to use TLS certificate issued to unique names/IPs, without the need to have either certificate issued to `localhost`

**What is the definition of done?**

It's possible to bootstrap a Fleet Server using mTLS where neither Fleet Server's certificate nor the Elastic Agent's certificate are issued to `localhost`

**Comment by nimarezainia** [comment]
If there are other options, please avoid having the user add yet another certificate here.

**Comment by AndersonQ** [comment]
Yeah, also the fix o how fleet-server validates client certificate should cover what this issue intended to fix

**Comment by AndersonQ** [comment]
> Basically if we just did everything we did for the control protocol checkins for this special case of a checkin with a supervised fleet server this would work out much nicer, and the the encryption and security story is the same for all of our connections to supervised processes.

I agree it'd be the best end goal. fleet-server would need to be changed to receive another set of certificate/ca but it'd be an internal thing, the users would not have to deal with it.

As I said, since https://github.com/elastic/fleet-server/pull/4042 has been merged, changing the internal host isn't necessary anymore   to have the certificates being valid for the internal host. So it's less pressing to have those changes implemented.

Do you wanna me to go ahead and create the issues?

**Comment by pierrehilbert** [comment]
Thanks @AndersonQ.
Should we close this issue then?

**Comment by pierrehilbert** [comment]
Closing for now and I will let you reopen if that shouldn't be closed.
cc @AndersonQ
