### ISSUE TITLE
Agent 8.3.0 doesn't uninstall cleanly: The osquerybeat process is left behind orphaned.

### ISSUE THREAD

**Issue by aleksmaus** [elastic/elastic-agent#556]
The Agent doesn't uninstall cleanly, leaving osquerybeat process running orphaned.

- Version: 8.3.0
- Operating System: Mac OSX 
- Steps to Reproduce: 
1. Install the agent normally for the policy that has "osquery manager" enabled
2. Verify that the agent is running including the child "osquerybeat" process
3. Uninstall the agent.
4. Observe osquerybeat process still running orphaned.

Some observations:
1. The agent seems to be existing before the osquerybeat shutdown process is completed. This code is never executed
https://github.com/elastic/elastic-agent/blob/07a476d591353f9b20dbe17a9f05ed6353741b33/internal/pkg/core/plugin/process/app.go#L310
2. Osquerybeat shutdowns normally on SIGTERM while running standalone(without agent)
3. The Osquerybeat beater.Run() loop exits nominally and shuts down it's own child processes on receiving SIGTERM
4. The ```x-pack/libbeat/management/manager.go``` ```Stop()``` is blocked on ```cm.client.Stop()``` forever
https://github.com/elastic/beats/blob/6b156e6766379a510ec4739e4e3d59446fe8d41a/x-pack/libbeat/management/manager.go#L140 in Osquerybeat process. 
Looks like possibly because the agent is no longer running.
5. The ```cm.client.Stop()``` https://github.com/elastic/elastic-agent-client/blob/main/pkg/client/client.go#L137 causes the client to block forever on ```c.wg.Wait()```
6. Commenting out the ```cm.client.Stop()``` call https://github.com/elastic/beats/blob/6b156e6766379a510ec4739e4e3d59446fe8d41a/x-pack/libbeat/management/manager.go#L140 allows osquerybeat process exit cleanly. No orphaned processes.

@ph @AndersonQ I added you as assignees for now. Please reassign as needed.

I think this needs to be a blocker for 8.3. 

I'll add the watcher for the parent process to osquerybeat for now as a fallback plan and then can dig further in the agent to see what is happening with the agent shutdown.
We also have this errors reported on uninstall from filebeat and metricbeat, which needs to be cleaned up as well: ```panic: close of closed channel```

```
{"log.level":"error","@timestamp":"2022-06-13T09:50:24.218-0400","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"filebeat stderr: \"panic: close of closed channel\\n\\ngoroutine 194 [running]:\\ngithub.com/elastic/beats/v7/filebeat/beater.(*Filebeat).Stop(0xc000be3b30)\\n\\t/go/src/github.com/elastic/beats/filebeat/beater/filebeat.go:428 +0x3f\\ngithub.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch.func5\"","agent.console.name":"filebeat","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-13T09:50:24.218-0400","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"filebeat stderr: \"()\\n\\t/go/src/github.com/elastic/beats/libbeat/cmd/instance/beat.go:461 +0x55\\nsync.(*Once).doSlow(0x0, 0x0)\\n\\t/usr/local/go/src/sync/once.go:68 +0xd2\\nsync.(*Once).Do(...)\\n\\t/usr/local/go/src/sync/once.go:59\\ngithub.com/elastic/elastic-agent-libs/service.HandleSignals.func1()\\n\\t/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.5/service/service.go:60 +0x19c\\ncreated by github.com/elastic/elastic-agent-libs/service.HandleSignals\\n\\t/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.5/service/service.go:49 +0x198\\n\"","agent.console.name":"filebeat","agent.console.type":"stderr","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-06-13T09:50:24.218-0400","log.origin":{"file.name":"process/stdlogger.go","file.line":54},"message":"metricbeat stderr: \"panic: close of closed channel\\n\\ngoroutine 2037 [running]:\\ngithub.com/elastic/beats/v7/metricbeat/beater.(*Metricbeat).Stop(0xc00043f980)\\n\\t/go/src/github.com/elastic/beats/metricbeat/beater/metricbeat.go:276 +0x1c\\ngithub.com/elastic/beats/v7/libbeat/cmd/instance.(*Beat).launch.func5()\\n\\t/go/src/github.com/elastic/beats/libbeat/cmd/instance/beat.go:461 +0x55\\nsync.(*Once).doSlow(0x0, 0x0)\\n\\t/usr/local/go/src/sync/once.go:68 +0xd2\\nsync.(*Once).Do(...)\\n\\t/usr/local/go/src/sync/once.go:59\\ngithub.com/elastic/elastic-agent-libs/service.HandleSignals.func1()\\n\\t/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.5/service/service.go:60 +0x19c\\ncreated by github.com/elastic/elastic-agent-libs/service.HandleSignals\\n\\t/go/pkg/mod/github.com/elastic/elastic-agent-libs@v0.2.5/service/service.go:49 +0x198\\n\"","agent.console.name":"metricbeat","agent.console.type":"stderr","ecs.version":"1.6.0"} 
```

**Comment by ph** [comment]
fyi @pierrehilbert I have added this to our weekly.

**Comment by aleksmaus** [comment]
@ph I can dig further in the agent code after I check the upgrade 8.2->8.3 issue

**Comment by jlind23** [comment]
Removing impact:critical as it is not a blocker anymore because there is already a workaround provided by @aleksmaus.
