### ISSUE TITLE
Implement custom JSON marshaller that omits secrets from the component model

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#5675]
- Relates https://github.com/elastic/elastic-agent/pull/5201/files

The `Components` slice in the component model will contain secrets that could be logged if the model is used in a log statement. We should implement a custom JSON or logp/zap marshaller that redacts or omits secrets (or just the entire input configuration) to avoid leaking secrets in logs.

The code should also be audited for similar places where secrets could be leaked in logs.

**Comment by michel-laterman** [comment]
We should also do this for yaml marshellers so it can be used in the diagnostics bundle.

We may need to pass the list of keys to redact to an encoder if it's a secret that fleet injects. The keys in this case would look like `inputs.0.some_secret`

**Comment by cmacknz** [comment]
+1 to making it harder for us to leak credentials anywhere

**Comment by andrzej-stencel** [comment]
Created https://github.com/elastic/elastic-agent/pull/6329 that should fix this.
