### ISSUE TITLE
elastic-agent installed as Fleet server remains stuck in uninstalling with retry errors for over 4-5 minutes.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#5752]
**Kibana Build details:**
```
VERSION: 8.16.0 SNAPSHOT
BUILD: 78993
COMMIT: 6eb8471c3124046eca03cccf20e0cc4f9706bcd5
```
Artifact: https://snapshots.elastic.co/8.16.0-106cdbc2/downloads/beats/elastic-agent/elastic-agent-8.16.0-SNAPSHOT-windows-x86_64.zip

Host: Windows Server 2022- Test Signing ON

**Preconditions:**
1. 8.16.0 SNAPSHOT Kibana self-managed environment should be available.
2. Agent should be installed using Quickstart or Production mode of security.

**Steps to reproduce:**
1. Observe Fleet Server is installed.
2. Run `.\Elastic\Agent\elastic-agent.exe uninstall`.
3. Observe notify: Fleet network error[retry] error is stuck for more than 4 minutes.
4. Observe folder is already blank before the completion.

**Expected Result:**
elastic-agent installed as Fleet server should not remain stuck in  uninstalling with retry errors for over 4-5 minutes.

**Screenshots:**
![Image](https://github.com/user-attachments/assets/f9d4e23c-9349-457a-bb90-c1577970a0aa)
![Image](https://github.com/user-attachments/assets/2306373f-9640-48a4-b459-91d604e0bd06)
![Image](https://github.com/user-attachments/assets/c64e113d-7233-4954-8bdc-344bed86a550)
![Image](https://github.com/user-attachments/assets/c9db42bd-2d46-4065-9af8-41ffce466a6c)
![Image](https://github.com/user-attachments/assets/be83c182-6a74-46b0-bbd4-5e907346f9a9)

**Comment by amolnater-qasource** [comment]
@muskangulati-qasource Please review.

**Comment by muskangulati-qasource** [comment]
Secondary review is Done for this ticket!

**Comment by cmacknz** [comment]
@michel-laterman this is probably from the uninstall notification, at minimum there should be better error messages here if Fleet Server was legitimately unavailable.

**Comment by amolnater-qasource** [comment]
Hi Team,
We have revalidated this issue on latest 8.16.0 BC1 kibana cloud environment and had below observations:

**Observations:**
- Multiple error logs are observed consistently on running uninstall command for installed fleet-server.


**Screen Recording:**

https://github.com/user-attachments/assets/7f4ebc44-2690-4ec9-b21b-ad4cffcee8d7


https://github.com/user-attachments/assets/bf57f6b7-972f-48d7-9e99-4b9006ab7e8b


**Build details:**
VERSION: 8.16.0 BC1
BUILD: 79314
COMMIT: 5575428dd3aef69366cddb4ccf07a2a26d30ce48
Artifact Link: https://staging.elastic.co/8.16.0-e8d5928a/downloads/beats/elastic-agent/elastic-agent-8.16.0-windows-x86_64.zip

Hence, we are reopening this issue.

Thanks!!

**Comment by michel-laterman** [comment]
Hi @amolnater-qasource,

For the failures you posted:

Did you destroy the ES deployment before uninstalling the agent instance? If so the 1st instances failure messages are expected; it should have taken a shorter amount of time then 4m as originally reported. do you recall how long it took?

Is the panic that occured in the 2nd scenario common? Do you have steps on how to recreate? I would like to recreate this with a binary where the symbols are still present because the failure when trying to marshall json seems strange to me.

**Comment by amolnater-qasource** [comment]
Hi @michel-laterman 

Thank you for looking into this issue.

>Did you destroy the ES deployment before uninstalling the agent instance? If so the 1st instances failure messages are expected; it should have taken a shorter amount of time then 4m as originally reported. do you recall how long it took?

Please find below steps for this:
- Install Fleet Server on kibana cloud environment.
- Keep it running for sometime.
- Simply run uninstall command: `C:\"Program Files"\Elastic\Agent\elastic-agent.exe uninstall`
- Observe multiple log lines in the powershell.
- Note: ES deployment isn't destroyed.

The issue is reproducible for 8.17.0-SNAPSHOT agent.

**Screen Recording:**

https://github.com/user-attachments/assets/59b5399a-0beb-4225-b24d-1ec0154ca93c


>Is the panic that occured in the 2nd scenario common? Do you have steps on how to recreate? I would like to recreate this with a binary where the symbols are still present because the failure when trying to marshall json seems strange to me.

This issue is inconsistently observed when VM is shut down for a long time and then agent is uninstalled.
This issue is reproduced multiple times, however no consistent steps are available.

**Build details:**
VERSION: 8.17.0 SNAPSHOT
BUILD: 80188
COMMIT: fdb16ae8cbdf4236db3696aa00d0bb98c943d864
Artifact Link: https://snapshots.elastic.co/8.17.0-0c51e25e/downloads/beats/elastic-agent/elastic-agent-8.17.0-SNAPSHOT-windows-x86_64.zip

Please let us know if anything else is required from our end.
Thanks!

**Comment by michel-laterman** [comment]
panics are being tracked in their own issue: https://github.com/elastic/elastic-agent/issues/5952

**Comment by michel-laterman** [comment]
For clarification: 
> Install Fleet Server on kibana cloud environment.
Does this mean you install a local agent with the fleet-server integration? (fleet-server runs on the test VM)

**Comment by blakerouse** [comment]
> 1. move uninstall notification before components are stopped (and have an edge case where the notification goes through, but the uninstall fails)

I would go with this except I would change the logic of performing it before only in the case that this Elastic Agent is running the Fleet Server. That means the rare case that it notifies before uninstall actually happens only occurs on hosts that are running on Fleet Server. This reduces the likely hood of a failure after notify to only occur on hosts that are running a Fleet Server which is few.

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.18.0 SNAPSHOT and found it **fixed now**.

**Observations:**
- elastic-agent installed as Fleet server gets uninstalled without any errors.

**Screenshot:**
![Image](https://github.com/user-attachments/assets/52a0c25b-c900-460b-974b-bfcc953da782)


**Build details:**
VERSION: 8.18.0 SNAPSHOT
BUILD: 81228
COMMIT: 9d6cc0792e538a076d68ffcfabbf6551912fb24e
Artifact Link: https://snapshots.elastic.co/8.18.0-94ccacd2/downloads/beats/elastic-agent/elastic-agent-8.18.0-SNAPSHOT-windows-x86_64.zip

Hence, we are marking this issue as **QA:Validated**.

Thanks!!
