### ISSUE TITLE
Prevent users from upgrading standalone agents in container, deb, and rpm environments

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#5832]
**Describe the enhancement:**

Standalone Elastic Agents that are running in a container or deployed via DEB or RPM packages should not be upgradable using the `elastic-agent upgrade ...` CLI command.

**Describe a specific use case for the enhancement or feature:**

**What is the definition of done?**
Running `elastic-agent upgrade` for standalone Elastic Agents should fail with a descriptive message when Elastic Agent is deployed:
* [ ] in a container
* [ ] via a DEB package
* [ ] via an RPM package

**Comment by cmacknz** [comment]
We already have detection for most (all?) of these cases: https://github.com/elastic/elastic-agent/blob/49579aea2c4bb9901e5212695249af63cc02c074/internal/pkg/agent/application/upgrade/upgrade.go#L69-L74

When we do this, we should consider including a `--force` flag or similar as an escape hatch in case this logic ever has a bug. We report the `upgradable` state to Fleet and it is used to block upgrades from the UI, but there is an underlying API with a similar force flag in Fleet.

**Comment by pchila** [comment]
I was more thinking about introducing a placeholder/marker file like `upgrades.disabled` file in the agent main directory and only add it to the packages where the update is off by default. This should be pretty simple to implement

**Comment by cmacknz** [comment]
I like it, much more reliable. We should replace the existing upgradeable check with that.

**Comment by swiatekm** [comment]
I agree is as well. Whether the agent is upgradable this way is really a property of the package, and so should be part of it in some way. A marker file is straightforward enough, and can only be wrong due to packaging bugs.

**Comment by michalpristas** [comment]
maybe we should make it more generic and future proof and handle it in a similiar fashion as beat modules
https://github.com/elastic/beats/blob/main/libbeat/cfgfile/glob_manager.go#L50

**Comment by kaanyalti** [comment]
I have some questions to clarify what needs to be done.
- The issue specifically mentions standalone agents. I was under the impression that agents running in a container, or installed by a package manager are not upgradeable regardless of whether they are standalone or fleet managed. Is this correct?
- Is this implementation supposed to be restricted to the cli?

**Comment by pierrehilbert** [comment]
I tend to agree with @michalpristas, the main goal is to highlight the reason why we can't upgrade the Agent through the CLI (the way it has been installed first).

**Comment by cmacknz** [comment]
Fleet enrolled agents on these platforms should already be prevented from upgrading in the Fleet UI via the upgrade action. The agents should be marked as non-upgradable. If this isn't the case we need to fix it. 

+1 that the `elastic-agent upgrade` command shouldn't special case Fleet enrolled agents. You cannot use the agents own upgrade process on any of these package types, it will not work. The container filesystem is immutable, the DEB and RPM package structures are different and agent's upgrade process isn't aware of that.

**Comment by cmacknz** [comment]
Using the `elastic-agent upgrade` command or a Fleet initiated upgrade will never work for RPM and DEB agents, their directory layout is different and incompatible with agent's built in upgrade process.

Containerized agents would do the upgrade and switch the symlink but revert back to the previous version when they restart because the initial file system is immutable.

There is logic to try to catch these cases already in the agent:
https://github.com/elastic/elastic-agent/blob/434986ed9fa6fbed6257557a4c6773d519742f66/internal/pkg/agent/application/coordinator/coordinator.go#L530-L537

https://github.com/elastic/elastic-agent/blob/434986ed9fa6fbed6257557a4c6773d519742f66/internal/pkg/agent/application/upgrade/upgrade.go#L69-L74

The installed check should catch RPM and DEB agents, and the under supervisor check should catch containers.

This looks like it should cover the CLI use case as well, so perhaps before we do any work we should test, or just adds automated tests, to check that this behaves the way we think it does.

**Comment by kaanyalti** [comment]
I already have created a PR for this, I can close it if it is unnecessary. @cmacknz

**Comment by cmacknz** [comment]
The way to tell is to check if the tests in https://github.com/elastic/elastic-agent/pull/6168 pass without the code changes. I did not have a chance to test this myself, only to read the code and see there is an attempt to handle this already.

I think we'd want the new tests to enforce this regardless of if the code changes turn out to be necessary.

**Comment by kaanyalti** [comment]
When manually testing, the IsUpgradable check works, I get the following error 
```
Error: Failed trigger upgrade of daemon: cannot be upgraded; must be installed with install sub-command and running under control of the systems supervisor
```
for deb, rpm and docker

I used 8.16.1

**Comment by pkoutsovasilis** [comment]
hey @cmacknz, @pchila 👋  although I do see sense in the `upgrades.disabled` file marker approach, after syncing with @kaanyalti , I think there are some fragile points of making this approach to work in a k8s deployment of elastic-agent. First and foremost, paths.Top() and paths.Install() ([here](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/cmd/container.go#L824) point inside the state dir of elastic-agent. When we are talking about the elastic-agent k8s deployment most of the times this state path is mounted as hostPath which mean that nothing from our image will be in it. About the `RunningUnderSupervisor()`, I think that this is not a viable solution as well, as it checks the ppid() of the running process and the `elastic-agent upgrade ...` cmd will be a different process that won't have a parent of pid 1. My ideas to support this feature for elastic-agent in k8s are:

1. the path of `upgrades.disabled` to be constantly at `/usr/share/elastic-agent/upgrades.disabled`; for k8s this works but for deb and rpm I am not 100% sure that this is always the case
2. have an env var specified in the dockerfile that based on its existence the upgrading is disabled; still the user can unset this env var but even with the file the user can delete it 
3. if we wanna stick with utilising the agent state path then we could make the container entrypoint of elastic-agent use the check os.ppid()==1 and if it is true then write the file `/usr/share/elastic-agent/state/data/upgrades.disabled` and thus we maintain the same check with deb and rpm

Any thoughts? 🙂 cc @kaanyalti

**Comment by michalpristas** [comment]
i don't think paths.{ANY} is a strong requirement. i can imagine `/usr/share` for this as well. we would not pack this file for any other pacakge such as normal linux targz so this should be fine. we already place some files there for these package types such as LICENSE, NOTICE... for rpm/deb

we can also think about placing it next a a binary and use `BinaryPath()`. I think i'm more in favor of `/usr/share` in this case although a bit unconventional path for feature flag

@pkoutsovasilis what you're saying here
> About the RunningUnderSupervisor(), I think that this is not a viable solution as well, as it checks the ppid() of the running process and the elastic-agent upgrade ... cmd will be a different process that won't have a parent of pid 1. My ideas to support this feature for elastic-agent in k8s are ...

is that RunningUnderSupervisor will always report false in container? But it is not upgrade command that executes this. upgrade command communicates intent after initial basic checks with running agent and that is the one executing the actual logic.

**Comment by pkoutsovasilis** [comment]
>is that RunningUnderSupervisor will always report false in container? But it is not upgrade command that executes this. upgrade command communicates intent after initial basic checks with running agent and that is the one executing the actual logic.

No @michalpristas , I said that if we call directly `RunningUnderSupervisor()` under `elastic-agent upgrade ...` this check won't be true because this is true only when process runs under `tini`  which is the image entrypoint (pid 1), namely `elastic-agent container ...`. Now tell me more about the intent and what you mean 🙂

**Comment by kaanyalti** [comment]
I created a new [PR](https://github.com/elastic/elastic-agent/pull/6212) that validates that the current `IsUpgradeable` show in the [comment above](https://github.com/elastic/elastic-agent/issues/5832#issuecomment-2504795565). Given that these tests pass I am not sure how necessary this implementation is.

cc: @michalprista @pkoutsovasilis @cmacknz @ycombinator

**Comment by pkoutsovasilis** [comment]
Thanks for the PR @kaanyalti and now I see what @michalpristas meant by communication intent; elastic-agent upgrade cmd communicates with the existing and running elastic-agent instance (TIL ty @michalpristas). Then should we consider that  is already done for the containerised agents and not implement `upgrades.disabled` logic for them?!

**Comment by ycombinator** [comment]
My 2c: let's just add the [tests](https://github.com/elastic/elastic-agent/pull/6212) for now.

**Comment by cmacknz** [comment]
+1 to just adding the tests to enforce that this doesn't break in the future.
