### ISSUE TITLE
Make the update version automation run on schedule for all release branches

### ISSUE THREAD

**Issue by rdner** [elastic/elastic-agent#5897]
**Describe the enhancement:**
Currently, the ["update versions" automation](https://github.com/elastic/elastic-agent/blob/main/.github/workflows/bump-agent-versions.sh) runs on a daily schedule: 

https://github.com/elastic/elastic-agent/blob/0cdfef580e28e0488ae2bfa9e1372e083e3712c0/.github/workflows/bump-agent-versions.yml#L7C14-L7C23 

Github allows to set a schedule only for the `main` branch. This means we have to manually run this automation for the rest of the release branches.

We should modify the script on `main` so it checks out all active release branches and runs the version updates for every branch creating corresponding PRs.

**Describe a specific use case for the enhancement or feature:**

Without this maintenance, the CI would start failing on release branches at some point and we would have to spend time on maintaining it manually.

**What is the definition of done?**

1. We have a daily Github workflow that runs version updates for each active release branch
2. We should have a way to configure what active release branches are, so we don't run this automation for branches we no longer release from.

**Comment by v1v** [comment]
There is already an implementation you can use for GitHub actions:
- https://github.com/elastic/oblt-actions/tree/main/elastic/active-branches

Or directly use https://storage.googleapis.com/artifacts-api/snapshots/branches.json - if you prefer or use Buildkite or something else.

**NOTE**: Only for `Elastic` employees:

There are a couple of backstage entries that explain those 'API' endpoints:
- https://backstage.elastic.dev/catalog/default/component/active-branches
- https://backstage.elastic.dev/catalog/default/component/current-releases

Let me know if you need further details

**Comment by rdner** [comment]
Thank you, @v1v !
I'll try it out and will get back to you if I have any questions.
