### ISSUE TITLE
[META] Create build pipelines and packaging steps for all Elastic Agent subcomponents

### ISSUE THREAD

**Issue by jlind23** [elastic/elastic-agent#592]
Purpose of this issue is to design and implement CI pipelines for all the components below:
- Elastic Agent Shipper: https://github.com/elastic/elastic-agent-shipper
- Elastic Agent Inputs: https://github.com/elastic/elastic-agent-inputs

Revisit [the proposal](https://docs.google.com/document/d/1ZZmAtrMBT9NlDUAlw22BuwQWAMS4sZp9p0kufuNTXpw/edit?usp=sharing) to improve the agent build system. Ensure the agent build and packaging system can scale with the agent V2 architecture and make it easier to use. In particular, consider that in the new architecture there may be many more inputs that live in separate repositories, written in different languages.

This ticket will considered as done as soon as the following actions are working:
- Each component can be individually built
- Each component are tested through unit, integration, and end to end tests that are part of the CI steps.
- A release process exists for each component. Each build generate artifacts that are stored and made available to be downloaded and packaged with the agent.
- Each component is appropriately packaged and distributed with the agent
- Builds must be a runnable on a PR basis

Elastic Agent shipper work - https://github.com/elastic/elastic-agent-shipper/issues/74

**Comment by cmacknz** [comment]
Added some more detail to the description.

**Comment by mdelapenya** [comment]
> Each component are tested through unit, integration, and end to end tests that are part of the CI steps.

I'd like to share my two cents about the different types of testing for each repository/component here. IIUC, there will be libraries (shipper, inputs) that will be consumed by the elastic-agent. For me, the libraries should contain a great coverage on unit tests, but no e2e or integration tests, unless they communicate to other system, which I think it's not the case (please correct me if I'm wrong 🙏 ).

Regarding the elastic-agent, which for me is the central piece here, it consumes the libraries to perform certain actions and send data to an output (elasticsearch). This is the project where, apart form the mandatory unit tests, I'd put integration tests. But for that I'd require first to define the boundaries for all possible interactions:
- agent + shipper
- agent + inputs
- agent + shipper + inputs
- agent + input > output 1 (i.e. elasticsearch)
- agent + shipper > output 1 (i.e elasticsearch)
- ... 

It would be of great help having a dependency graph where we can identify consumers and providers of the functionality, so that we can correlate the relationships with those boundaries that I mentioned before, and with that, write the right type of tests for each interaction.

**Comment by cmacknz** [comment]
At a high level I agree that the agent is the place that aggregates all of this functionality together, and we could write all tests at the agent level.

At an organizational level most of these pieces are by developed by separate teams in separate repositories, so I'm not sure making the agent the place where all integration testing happens would make sense. If we wanted to do that it would probably be easiest to just have an agent monorepo.

I think we will want agent components (inputs, shipper) to have some form of integration testing local to their own repositories that ensures they are highly likely to run under agent without issue.

**Comment by narph** [comment]
Based on the information above and @ph' s proposal, I took a stab at creating some broad and concrete tasks separated by repo. This should help us estimate on how much effort is involved and prioritize for the next releases.
Let me know if I am missing anything else. 


Elastic Agent

- clean up current build in preparation for the new way of sourcing binaries (will follow up with detailed proposal)
    - re-evaluate/scrub dev-tools to a bare minimum, decide if anything can be brought to a new solution
    - implement new solution for build (will no longer attempt to build dependencies)
    - reduce complexity, make everything explicit, no longer rely on env variables, strict validation, create migration plan from `make` to `mage`, rearchitect to strict set of common targets
- make sure elastic agent can still work with established artifacts from other teams (cloudbeat, apm-server, endpoint-security) for now
- update infra repo elastic-agent templates to reflect the new setup


Beats 
 - add new `magefile` containing the new build target that should produce the new beats binaries in the desired format
 - update infra repo beats related templates to also publish the new binaries in the new directory 

Shipper
- expand build implementation to generate platform based binaries
- align to stack versioning
- update/expand .CI setup
- update infra repo, add shipper as new unified release manager artifact

Inputs 
- add to fleet-ci
- same step list as shipper above

Fleet Server 
- update build to produce build binaries 
- update infra repo fleet server related templates to publish the new binaries

Shared
- ensure tests are run if present
- ensure e2e tests are running

**Comment by cmacknz** [comment]
> Shipper

> expand build implementation to generate platform based binaries
> align to stack versioning
> update/expand .CI setup
> update infra repo, add shipper as new unified release manager artifact

Do we need the shipper to be part of the unified release manager? It will only run as part of the agent. It and the new inputs (from elastic-agent-inputs) can probably be treated the same way fleet-server is from the perspective of releasing the binaries.

**Comment by ph** [comment]
@cmacknz It need to be in some part, the macOS or Windows binary need to be signed.

**Comment by cmacknz** [comment]
There is a draft PR adding support for the shipper to the DRA process: https://github.com/elastic/elastic-agent-shipper/pull/100
