### ISSUE TITLE
EDOT Collector should guarantee at least once delivery of logs

### ISSUE THREAD

**Issue by ycombinator** [elastic/elastic-agent#5922]
**Describe the enhancement:**

The Elastic distribution of the OpenTelemetry Collector (aka Elastic Agent) should guarantee at least once delivery of logs.

**Describe a specific use case for the enhancement or feature:**

At the moment, Elastic Agent collects and ships logs using Filebeat.  And Filebeat [guarantees](https://www.elastic.co/guide/en/beats/filebeat/current/how-filebeat-works.html#at-least-once-delivery) at least once delivery of logs.

**What is the definition of done?**

An end-to-end test proving that Elastic Agent running with an OTel Collector configuration — and therefore running an OTel Collector pipeline in the embedded OTel Collector — can collect logs from a file and ship them to Elasticsearch with an at least once delivery guarantee.  That is, every log line present in the file should be indexed into Elasticsearch.

**Comment by cmacknz** [comment]
At minimum this will always be dependent on the user correctly configuring a storage extension so the filelog receiver can persist offsets. https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/35013#issuecomment-2442331010

**Comment by ycombinator** [comment]
Closing as duplicate (of a private issue).
