### ISSUE TITLE
`Versions below 10.15 are not supported: exit status 157` error is displayed on installing 8.14.3 agent with Elastic Defend on mac v15.1

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#5951]
**Kibana Build details:**
```
VERSION: 8.16.0 BC3
BUILD: 79556
COMMIT: f02d1303b5230c357ac7e4c49c8adadd5f66af38
```
**Artifact Link 8.14.3:** 
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.14.3-darwin-x86_64.tar.gz
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.14.3-darwin-aarch64.tar.gz

**Preconditions:**
1. 8.16.0-BC3 Kibana cloud environment should be available.
2. Mac v15.1 should be available.

**Steps to reproduce:**
1. Install mac agent using agent policy having Elastic Defend integration.
2. Observe error below error is displayed for Elastic Defend integration:
```
failed install endpoint service: 2024-11-06 08:09:09: info: InstallLib.cpp:164 Versions below 10.15 are not supported: exit status 157
No policy response available
Policy response failure

The Endpoint did not apply the Policy correctly. Expand the Policy response above for more details.
```

**Expected Result:**
No errors should be displayed on installing 8.14.3 agent with Elastic Defend on mac v15.1 

**Screen Recording:**

https://github.com/user-attachments/assets/42b57973-b32d-4676-bd9b-4b9bd0e5dbdc

**Working fine for 7.17.25:**

https://github.com/user-attachments/assets/bf8afdac-de50-45fc-8aad-0173190a6da8

**Agent Logs:**
[elastic-agent-diagnostics-2024-11-06T08-03-56Z-00.zip](https://github.com/user-attachments/files/17644536/elastic-agent-diagnostics-2024-11-06T08-03-56Z-00.zip)

**What's working Fine:**

- No errors are observed on installing and upgrading 7.17.25 mac agent to 8.15.4 or 8.16.0 on macOS Sequoia v15.1
- No errors are observed on installing and upgrading 8.14.3 mac agent to 8.15.4 on macOS v14
- No errors are observed on installing 8.15.4 and 8.16.0 agents on macOS Sequoia

**Comment by muskangulati-qasource** [comment]
Secondary review is Done for this ticket!

**Comment by cmacknz** [comment]
MacOS 10.15 was dropped from Defend's support matrix in 8.13.x https://www.elastic.co/support/matrix

This is expected.

**Comment by pierrehilbert** [comment]
I think they are testing macOS 15.1 and not 10.15 that doesn't seem to be supported yet.
