### ISSUE TITLE
User is unable to uninstall mac agent if x86_64 architecture agent is installed using Elastic Defend integration on mac with ARM architecture.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#5966]
**Kibana Build details:**
```
VERSION: 8.16.0 BC3
BUILD: 79556
COMMIT: f02d1303b5230c357ac7e4c49c8adadd5f66af38
```
Artifact Link: https://staging.elastic.co/8.16.0-485065f1/downloads/beats/elastic-agent/elastic-agent-8.16.0-darwin-x86_64.tar.gz

**Preconditions:**
1. 8.16.0-BC3 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Install mac x86_64 architecture agent is installed using Elastic Defend integration on mac with ARM architecture.
2. Run agent uninstall command- `sudo elastic-agent uninstall`.
3. Observe user is not able to uninstall agent.

**Expected Result:**
User should be able to uninstall mac agent if x86_64 architecture agent is installed using Elastic Defend integration on mac with ARM architecture.

**Screenshot:**
![Image](https://github.com/user-attachments/assets/1d3f3dce-fdcc-4bc0-bf43-9345b67cff03)

**Agent Logs:**
[\[aarch uninstall\]elastic-agent-diagnostics-2024-11-06T08-56-14Z-00.zip](https://github.com/user-attachments/files/17656407/aarch.uninstall.elastic-agent-diagnostics-2024-11-06T08-56-14Z-00.zip)

**What's working fine:**
- On removing Elastic Defend integration user is able to uninstall elastic-agent.

**Comment by amolnater-qasource** [comment]
@muskangulati-qasource Please review.

**Comment by muskangulati-qasource** [comment]
Secondary review is Done for this ticket!

**Comment by ycombinator** [comment]
@amolnater-qasource Is this bug reproducible with Elastic Agent `8.15.3`?  Just wondering if it's a regression.

**Comment by amolnater-qasource** [comment]
Hi @ycombinator 

We have revalidated this issue for Elastic Agent- v8.15.3 and found it reproducible there too.

**Observations:**
- User is unable to uninstall mac agent if x86_64 architecture agent is installed using Elastic Defend integration on mac with ARM architecture.

**Logs:**
[elastic-agent-diagnostics-2024-11-12T04-33-14Z-00.zip](https://github.com/user-attachments/files/17711583/elastic-agent-diagnostics-2024-11-12T04-33-14Z-00.zip)


**Screenshot:**
![Image](https://github.com/user-attachments/assets/59f679df-97ad-4d16-b9ed-5e976a2ef555)

**Artifact Link:**
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.15.3-darwin-x86_64.tar.gz

Please let us know if anything else is required from our end.

Thanks!!

**Comment by cmacknz** [comment]
I don't think defend supports running x86 emulated binaries on arm, we probably should never have let defend install at all. Then we wouldn't have to deal with uninstalling it.

**Comment by swiatekm** [comment]
Wasn't this already resolved by https://github.com/elastic/elastic-agent/pull/6095 @cmacknz ?

**Comment by cmacknz** [comment]
It should be yes but it would be worth sanity checking.

**Comment by amolnater-qasource** [comment]
Hi Team,

Thank you for sharing the update.
We have revalidated this issue on 8.17.0 kibana cloud environment and found it **fixed now**.

**Observations:**
- User is able to uninstall mac agent if x86_64 architecture agent is installed using Elastic Defend integration on mac with ARM architecture.

**Screenshot:**
![Image](https://github.com/user-attachments/assets/a55603fb-4125-481c-85eb-e4d0d242cee1)

**Build details:**
VERSION: 8.17.0
BUILD: 80539
COMMIT: 86cbc85e621f4f3f701ed230f4e859ac5a80145b
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.17.0-darwin-x86_64.tar.gz

Hence, we are **closing** and marking this issue as **QA:Validated**.

Thanks!!
