### ISSUE TITLE
Fleet deprecated `list` property when retrieving enrollment api keys

### ISSUE THREAD

**Issue by nchaulet** [elastic/elastic-agent#6023]
The `list` property in `GET /api/fleet/enrollment_api_keys` as been deprecated since 8.0.0 in favor of the `items` property

This should be changed in:

https://github.com/elastic/elastic-agent/blob/4b15e1afa8de457fe34ce35d2215180d625b4fe0/internal/pkg/agent/cmd/container.go#L954`

Related to https://github.com/elastic/ingest-dev/issues/4459

**Comment by ycombinator** [comment]
@nchaulet Is the `list` property going to go away starting with `9.0.0`?
