### ISSUE TITLE
Fix failure_threshold parsing when value is coming from fleet

### ISSUE THREAD

**Issue by pchila** [elastic/elastic-agent#6152]
While investigating https://github.com/elastic/elastic-agent/issues/6049 I tried to set the `failure_threshold` using fleet override API, however this is parsed as a float64 by agent which is not supported at the moment, for example:

```
PUT kbn:/api/fleet/agent_policies/<policy_id>
{
   "name": <policy_name>,
   "namespace": "default",
   "overrides": {
       "agent": {
            "monitoring": {
                "failure_threshold": 5
            }
       }
   }
}
```

Optionally figure out how to reset the failure_threshold to default from fleet, agent should probably check if there's a `monitoring` section coming from fleet but no `failure_threshold` key and reset its monitoring failure_threshold

**Comment by cmacknz** [comment]
I think this is probably a case of https://github.com/elastic/elastic-agent/issues/2522

**Comment by pchila** [comment]
> I think this is probably a case of [#2522](https://github.com/elastic/elastic-agent/issues/2522)

Yes it is very similar to what described in a comment of the same issue https://github.com/elastic/elastic-agent/issues/2522#issuecomment-2030410861

My idea here is to maintain the flexibility in input by adding support for the `float64` type (I am not using validation from ucfg or anything of the sort so I can switch on the type of the value...
