### ISSUE TITLE
[CI] Move the integration tests stage right after the unit tests stage

### ISSUE THREAD

**Issue by mdelapenya** [elastic/elastic-agent#64]
I would see convenient to run the integration tests right after the unit tests, not after the e2e tests, like it's done now.

@v1v @narph thoughts?

**Comment by v1v** [comment]
No issues, bear in mind, there are no ITs yet, the CI stage is pretty much a NOOP, https://github.com/elastic/elastic-agent/blob/c09bd77404da087ace182594c69098817748a0fc/.ci/Jenkinsfile#L237-L248

**Comment by narph** [comment]
we can move them after the unit test step now so we won't forget once we have something running

**Comment by narph** [comment]
done in the pr linked
