### ISSUE TITLE
[Fleet]: Error log on running `elastic-agent diagnostics collect` on Non-English French Windows10.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#687]
**Kibana version:**  8.4 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.4.0 Snapshot
BUILD: 54194
COMMIT: f94d5ff26bf1f14f9992e426d9a56ac6c5d48fb0
```

**Preconditions:**
1. 8.4 Snapshot Kibana cloud environment should be available.
2. Agent should be installed on Non-English French Windows10.

**Steps to reproduce:**
1. Navigate to admin powershell `C:\Program Files\Elastic\Agent>`
2. Run `.\elastic-agent.exe diagnostics collect`
3. Observe error log on running above command.

**Expected Result:**
No error log should be observed on running `elastic-agent diagnostics collect` on Non-English French Windows10.

**Screenshot:**
![8](https://user-images.githubusercontent.com/77374876/177762126-a65975d4-4f2a-42ea-babf-5f350ec75a93.JPG)

**What's Working:**
Working fine on English Windows10 VM.
![10](https://user-images.githubusercontent.com/77374876/177762178-3a54038e-7f8f-4368-b040-e79a28b8bded.JPG)

**Reference Ticket:**
Observed during testing https://github.com/elastic/elastic-agent/issues/150

**Logs:**
[elastic-agent-diagnostics-2022-07-07T10-16-38Z-00.zip](https://github.com/elastic/elastic-agent/files/9068822/elastic-agent-diagnostics-2022-07-07T10-16-38Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by ph** [comment]
If I understand the issue, is we do no have localized string in Elastic Agent for different locales? AFAIK we do not have on our radar to add i18n to Elastic Agent. I don't know how much is requested by our customer. But I do believe some country or region have some regulation in place to enforce or require localization of software.

@nimarezainia

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on 8.6.0 release kibana cloud-production environment and found it **fixed** now.

**Host:**
French Windows 10

**Observations:**
-  No errors are observed on running `elastic-agent diagnostics collect` command on Non-English French Windows10.

**Build details:**
BUILD: 58852
COMMIT: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47
Artifact Link: https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.6.0-windows-x86_64.zip

**Screenshot:**
![8](https://user-images.githubusercontent.com/77374876/212033273-9375275a-7012-497a-bcf7-1f73a59560f7.JPG)


Hence we are **closing** this issue and marking it as **QA:Validated**.

Thanks
