### ISSUE TITLE
[Fleet]: Data under Data Streams tab gets removed on running live query under OSQuery tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#721]
**Kibana version:**  8.4 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
8.4 Snapshot
BUILD: 54479
COMMIT: 8a945789baa48244340cdff5fdf45fc9f67d3ad3
```

**Preconditions:**
1. 8.4 Snapshot Kibana cloud environment should be available.
2. An agent should be installed.

<details><summary>Steps followed:</summary>
<p>

1. Create 3 certs ca, client and logstash with below commands:

```
elasticsearch-certutil ca --pem
elasticsearch-certutil cert --name logstash --ca-cert C:\elk\elasticsearch\ca\ca.crt --ca-key C:\elk\elasticsearch\ca\ca.key --pem
elasticsearch-certutil cert --name client --ca-cert C:\elk\elasticsearch\ca\ca.crt --ca-key C:\elk\elasticsearch\ca\ca.key --pem

```
2. Convert the logstash key to pkcs8 as it is the only format supported by logstash:

`openssl pkcs8 -inform PEM -in logstash.key -topk8 -nocrypt -outform PEM -out logstash.pkcs8.key
`

3. Create logstash output-`My Logstash Output`(could be any):

Add logstash hosts: 10.10.10.10:5044 (machine ip)

Add below certs:

In Server SSL certificate we added- ca certificate.
In Client SSL certificate we added- client certificate.
In Client SSL certificate SSL key we added- client certificate key.

4. Added required configuration in pipelines.yml and created elastic-agent-pipeline.conf.

pipelines.yml:

```
- pipeline.id: elastic-agent-pipeline
  path.config: "C:\elk\logstash\config\elastic-agent-pipeline.conf"

```
**elastic-agent-pipeline.conf:**

```
input {
  elastic_agent {
    port => 5044
    ssl => true
    ssl_certificate_authorities => ["C:\elk\elasticsearch\ca\ca.crt"]
    ssl_certificate => "C:\elk\elasticsearch\logstash\logstash.crt"
    ssl_key => "C:\elk\elasticsearch\logstash\logstash.pkcs8.key"
    ssl_verify_mode => "force_peer"
  }
}

output {
  elasticsearch {
    hosts => ["https://10.10.10.10:9200"](https://10.10.10.10:9200/)
    api_key => "zorYA4ABQH2oZOWhPX_Q:_Y00OErrQGCRr5tJBE1_zQ"
    data_stream => true
    ssl => true
   # cacert => 
  }
}

```

5. Run logstash from bin using below command:

` logstash -f  C:\elk\logstash\config\elastic-agent-pipeline.conf `

6. Create new policy with integrations output selected as- `My Logstash Output`.
7. Run Agent install command for second agent.
8. Observe data for System integration for this installed agent under Data Streams tab.
9. Add OSQuerybeat integration and observe data for OSQuerybeat data too.
10. Navigate to OSquery tab and run a new live query: `select * from acpi_tables`
11. Observe all data gets removed from Fleet>Data Streams tab.

</p>
</details>

**Expected Result:**
Data under Data Streams tab should not get removed on running live query under OSQuery tab.

**Screenshot:**
**Before Running live query:**

https://user-images.githubusercontent.com/77374876/178959776-750b3031-2ced-4329-ae53-765f178acc5f.mp4

**After Running live query:**
![7](https://user-images.githubusercontent.com/77374876/178960062-64e1558a-8ba6-4c8f-8e6d-61fc2d07ae0f.JPG)

![6](https://user-images.githubusercontent.com/77374876/178959138-27d0e34b-6e44-42c2-b16c-a2fcee69df3a.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by amolnater-qasource** [comment]
FYI @joshdover @kpollich We have shared the 8.4 Snapshot environment over slack.

cc: @aleksmaus

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by kpollich** [comment]
I am hopeful that this will be fixed by the latest changes in https://github.com/elastic/kibana/pull/136114

**Comment by kpollich** [comment]
@amolnater-qasource - It looks like the PR referenced above should be in the [latest snapshot](https://artifacts-api.elastic.co/v1/versions/8.4-SNAPSHOT/builds/latest/projects/kibana). Could you revalidate this? Thank you.

**Comment by amolnater-qasource** [comment]
Hi @kpollich 
While revalidating this issue we have encountered another issue related to logstash output reported at https://github.com/elastic/elastic-agent/issues/738

Hence we are currently blocked to test this issue.
We will be retesting this once this issue will be resolved.


Thanks

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on latest 8.4 BC5 Kibana cloud environment and found it **fixed** now.

**Observations:**
- Data under Data Streams tab doesn't get removed on running live query under OSQuery tab.

**Build details:**
BUILD: 55374
COMMIT: f12954223a8ad66bbbf77becc4f0557ffd1c92c3

**Screenshots/Screen Recording:**
![12](https://user-images.githubusercontent.com/77374876/185893657-e8756ffe-b13f-48c6-bc11-95659a3656b4.JPG)
![13](https://user-images.githubusercontent.com/77374876/185893670-1d76ce84-9329-4048-96b7-3f86841387fd.JPG)
![11](https://user-images.githubusercontent.com/77374876/185893696-5232a174-faa1-4d83-9775-c2e7ce86b89c.JPG)

https://user-images.githubusercontent.com/77374876/185896321-e6a6f44d-1b89-4613-aaaf-ea2dd8cda5fc.mp4


Hence we are closing this issue and marking it as **QA:Validated**.

Thanks!

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

-  **01 new testcase** is created under the 'Fleet Test Suite' at:
   - https://elastic.testrail.io/index.php?/cases/view/167869

Thanks!
