### ISSUE TITLE
[Error logs]: Error logs on adding Endpoint Security to Ubuntu .tar agent.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#729]
**Kibana version:**  8.4.0 Snapshot Kibana cloud environment

**Host OS:**  Ubuntu tar.gz

**Build details:**
VERSION: 8.4.0
BUILD: 54571
COMMIT: f53c703c4e8851adc51da800a0965eaaae4136fe
Artifact Link: https://snapshots.elastic.co/8.4.0-a324b98b/downloads/beats/elastic-agent/elastic-agent-8.4.0-SNAPSHOT-linux-x86_64.tar.gz

**Preconditions:**
1. 8.4.0 Snapshot Kibana cloud environment should be available.
2. Ubuntu .tar.gz agent should be installed with policy having only System integration.

**Integrations:**
System

**Steps to reproduce:**
1. Navigate to Fleet>Agent policy.
2. Add Endpoint Security to Ubuntu .tar agent policy.
3. Observe error logs under Agent>Logs tab.

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/179490757-4a445d20-7166-4963-898b-aa59c1a9ce3f.JPG)
![image](https://user-images.githubusercontent.com/77374876/179491711-376e0c64-911e-415f-8b83-63342b582497.png)

**Expected Result:**
No error logs should be there on adding Endpoint Security to Ubuntu .tar agent.

**Logs:**
[elastic-agent-diagnostics-2022-07-18T10-00-12Z-00.zip](https://github.com/elastic/elastic-agent/files/9131121/elastic-agent-diagnostics-2022-07-18T10-00-12Z-00.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on latest 8.4 BC6 Kibana cloud environment and found **this issue still reproducible.**

**Observations:**
- Error logs are available under Logs tab for Linux agent on adding Endpoint Security or an agent restart.

**Build details:**
BUILD: 55395
COMMIT: 1922ab0b6f8dc2906ef10f3fb65fc4d0e0076f90

**Logs:**
**Linux:**
[elastic-agent-diagnostics-Linux1.zip](https://github.com/elastic/elastic-agent/files/9400742/elastic-agent-diagnostics-Linux1.zip)
[elastic-agent-diagnostics-Linux2.zip](https://github.com/elastic/elastic-agent/files/9400743/elastic-agent-diagnostics-Linux2.zip)

However we are closing this issue and tracking the same error logs under https://github.com/elastic/elastic-agent/issues/522
Thanks
