### ISSUE TITLE
Add `hostPath` to standalone elastic agent on k8s manifest

### ISSUE THREAD

**Issue by narph** [elastic/elastic-agent#736]
Elastic agent doesn't seem to have an option to store information it can use across pod/container restarts
https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml#L628, although it looks like other beats like Filebeat already have this.
Goal would be persisting state.

cc  @ChrsMark , @jsoriano

**Comment by ChrsMark** [comment]
cc: @elastic/obs-cloudnative-monitoring

**Comment by gizas** [comment]
@narph just for our information can you point us to the path that Agent is reading persistent information from?

**Comment by jlind23** [comment]
Has been fixed by https://github.com/elastic/elastic-agent/pull/2550 hence closing.
