### ISSUE TITLE
[Logstash]: Bad certificates errors on running logstash and no data for logstash output.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#738]
**Kibana version:**  8.4 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.4.0
BUILD: 54571
COMMIT: f53c703c4e8851adc51da800a0965eaaae4136fe
```

**Preconditions:**
1. 8.4 Snapshot Kibana cloud environment should be available.

<details><summary>Steps followed:</summary>
<p>

1. Create 3 certs ca, client and logstash with below commands:

```
elasticsearch-certutil ca --pem
elasticsearch-certutil cert --name logstash --ca-cert C:\elk\elasticsearch\ca\ca.crt --ca-key C:\elk\elasticsearch\ca\ca.key --pem
elasticsearch-certutil cert --name client --ca-cert C:\elk\elasticsearch\ca\ca.crt --ca-key C:\elk\elasticsearch\ca\ca.key --pem

```
2. Convert the logstash key to pkcs8 as it is the only format supported by logstash:

`openssl pkcs8 -inform PEM -in logstash.key -topk8 -nocrypt -outform PEM -out logstash.pkcs8.key
`

3. Create logstash output-`My Logstash Output`(could be any):

Add logstash hosts: 10.10.10.10:5044 (machine ip)

Add below certs:

In Server SSL certificate we added- ca certificate.
In Client SSL certificate we added- client certificate.
In Client SSL certificate SSL key we added- client certificate key.

4. Added required configuration in `pipelines.yml` and created `elastic-agent-pipeline.conf`.

**pipelines.yml:**

```
- pipeline.id: elastic-agent-pipeline
  path.config: "C:\elk\logstash\config\elastic-agent-pipeline.conf"

```
**elastic-agent-pipeline.conf:**

```
input {
  elastic_agent {
    port => 5044
    ssl => true
    ssl_certificate_authorities => ["C:\elk\elasticsearch\ca\ca.crt"]
    ssl_certificate => "C:\elk\elasticsearch\logstash\logstash.crt"
    ssl_key => "C:\elk\elasticsearch\logstash\logstash.pkcs8.key"
    ssl_verify_mode => "force_peer"
  }
}

output {
  elasticsearch {
    hosts => ["https://10.10.10.10:9200"](https://10.10.10.10:9200/)
    api_key => "zorYA4ABQH2oZOWhPX_Q:_Y00OErrQGCRr5tJBE1_zQ"
    data_stream => true
    ssl => true
   # cacert => 
  }
}

```

5. Run logstash from bin using below command:

` logstash -f  C:\elk\logstash\config\elastic-agent-pipeline.conf `

Observe errors on running above command.
6. Create new policy with integrations output selected as- `My Logstash Output`.
7. Run Agent install command for second agent.
8. Observe no data for System integration for this installed agent under Data Streams tab.

</p>
</details>

**Screenshot:**
![14](https://user-images.githubusercontent.com/77374876/179739647-308c9971-8385-4fbc-83c0-9329b885cffd.JPG)

**Logstash Logs:**

[Logstash Logs.txt](https://github.com/elastic/elastic-agent/files/9140607/Logstash.Logs.txt)

<details><summary>Screenshots for data:</summary>
<p>

![15](https://user-images.githubusercontent.com/77374876/179740948-8a0930c7-e4bc-4bef-b7fb-684405c7d814.JPG)

![16](https://user-images.githubusercontent.com/77374876/179740953-ae7e75e6-91ec-4dff-9f5e-0083bbe137af.JPG)

![17](https://user-images.githubusercontent.com/77374876/179740955-bfe19192-9019-4fe7-993b-a1f6540e8fd8.JPG)

</p>
</details>

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by amolnater-qasource** [comment]
FYI @nchaulet @jlind23

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by jlind23** [comment]
@amolnater-qasource @manishgupta-qasource it seems to be a logstash issue and not an Agent issue, am i wrong?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
Thank you for looking into this. Yes this issue is with Logstash output.

Thanks!

**Comment by pierrehilbert** [comment]
@roaksoax: we should probably move this one on your project board right?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on latest 8.4 BC5 Kibana cloud environment and found it working fine now.

**Observations:**
- We are now successfully able to run logstash without any errors under CLI.

**Build details:**
BUILD: 55374
COMMIT: f12954223a8ad66bbbf77becc4f0557ffd1c92c3

**Screenshots:**
![12](https://user-images.githubusercontent.com/77374876/185893657-e8756ffe-b13f-48c6-bc11-95659a3656b4.JPG)
![13](https://user-images.githubusercontent.com/77374876/185893670-1d76ce84-9329-4048-96b7-3f86841387fd.JPG)
![11](https://user-images.githubusercontent.com/77374876/185893696-5232a174-faa1-4d83-9775-c2e7ce86b89c.JPG)

Hence we are closing this issue and marking it as **QA:Validated**.

Thanks!
