### ISSUE TITLE
[Fleet]: Ubuntu agent goes unhealthy after sometime of installation.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#775]
**Kibana version:**  8.4.0 Snapshot Kibana cloud environment

**Host OS:**  Ubuntu tar.gz

**Build details:**
BUILD: 54789
COMMIT: af3a3cba9a7fa3b3e0d2e4766a1db11a5ff4f192
Artifact Link: https://snapshots.elastic.co/8.4.0-d058e92f/downloads/beats/elastic-agent/elastic-agent-8.4.0-SNAPSHOT-linux-x86_64.tar.gz

**Preconditions:**
1. 8.4.0 Snapshot Kibana cloud environment should be available.
2. Ubuntu .tar.gz agent should be installed with policy having only System integration.

**Integrations:**
System

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Observe after sometime, agent gets Unhealthy.

**Issue is reproducible on:**
- _Keeping it idle after installation for many hours._
- _On restarting it and after sometime._
- _On upgrading successfully and then after sometime._
- _On Adding Endpoint Security integration._

**Screenshot:**
![14](https://user-images.githubusercontent.com/77374876/180992760-fe69196d-05ae-454c-bc14-be768963ff73.JPG)
![15](https://user-images.githubusercontent.com/77374876/180993513-8bc18889-d783-4124-ac5d-18271b56505f.JPG)

**Expected Result:**
Ubuntu agent should not go unhealthy after sometime of installation.

**Logs:**
[elastic-agent-diagnostics-2022-07-26T09-06-42Z-00.zip](https://github.com/elastic/elastic-agent/files/9189181/elastic-agent-diagnostics-2022-07-26T09-06-42Z-00.zip)

**elastic-agent.yml:**
[elastic-agent.zip](https://github.com/elastic/elastic-agent/files/9189256/elastic-agent.zip)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by amolnater-qasource** [comment]
Hi Team
We have revalidated this issue on latest 8.4 BC6 Kibana cloud environment and found it working fine now.

**Observations:**
- Agent doesn't go unhealthy after sometime of installation due to any reason.

**Build details:**
BUILD: 55395
COMMIT: 1922ab0b6f8dc2906ef10f3fb65fc4d0e0076f90

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/186106983-711f1bb9-122b-49e7-ba85-e296e995f1f9.JPG)

Hence we are closing this issue and marking it as **QA:Validated**.
Thanks

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/167380
   - https://elastic.testrail.io/index.php?/cases/view/167381
 
Thanks!
