### ISSUE TITLE
elastic-agent linux service file

### ISSUE THREAD

**Issue by michel-laterman** [elastic/elastic-agent#78]
Currently when the elastic-agent is installed through `rpm`/`deb` and initv script is installed to manage the service.
However, when installing from an archive the agent provides a systemd unit file.

Do we need to continue to provide initv scripts for 8.x releases? Or should we provide unit files for all possible installations going forward?

cc @ruflin

**Comment by jlind23** [comment]
[Clean up] This hasn't been looked up nor haven't any traction for the past two years hence closing. I am happy to reopen if need be.
cc @ycombinator
