### ISSUE TITLE
[Fleet]: Single Agent is upgraded before the scheduled time

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/elastic-agent#783]
**Kibana version:** 8.4 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build Details:**

```
8.4 Snapshot
BUILD: 54789
COMMIT: af3a3cba9a7fa3b3e0d2e4766a1db11a5ff4f192
```

**Preconditions:**

- 8.4 Snapshot Kibana cloud environment should be available.
- Lower version agent should be installed.

**Steps to reproduce:**

1. Navigate to Fleet>Agents tab.
2. Select 1 agent
3. Click `Schedule upgrade for 1 agent` under Actions.
4. Click on Schedule date and time option
5. Schedule upgrade time **(say 4:00 PM)**
6. Click on 'Schedule' button.
7. Upgrading 1 agent callout is shown.
8. Agent goes into the Updating state.
9. Observe that the Agent gets upgraded before the scheduled time **(i.e. within 5 minutes at 3:28 PM)**.

**Expected Result:**

- Agent should be upgraded at the scheduled time.

**What's working:**

- Agents get upgraded at the schedule time when more than one agent are selected.

**Screen Recording:**

https://user-images.githubusercontent.com/97870262/181228281-8996dda9-56ce-4548-8a12-3e0c11807755.mp4

![image](https://user-images.githubusercontent.com/97870262/181229383-47bae533-eeec-403c-92a7-f0db61a96e85.png)

**Related issue:** 

https://github.com/elastic/kibana/issues/137269

**Comment by prachigupta-qasource** [comment]
Please review @manishgupta-qasource

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by prachigupta-qasource** [comment]
Hi Team,

We are tracking this issue under this ticket [#144583](https://github.com/elastic/kibana/issues/144583) 

Hence, we are `closing` this issue.

Thanks!
