### ISSUE TITLE
Allow Elastic Agent to run endpoint into a separate container

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent#787]
Today `Elastic Agent` take care of the installation and the management of endpoint, this require everything to be run in the same container, it would be nice to be able to run Agent and Endpoint in a different container see the following architecture diagram.

<img width="657" alt="Screen Shot 2022-07-27 at 9 46 19 AM" src="https://user-images.githubusercontent.com/640/181263040-2edf596c-a1e6-4023-a2f8-9508ca4b771d.png">

This would requires us to add a `sidecar` execution mode in our specification file in https://github.com/elastic/elastic-agent/blob/feature-arch-v2/specs/endpoint-security.spec.yml#L3 @blakerouse and I have discussed this in the past.
We could detect that we run under k8s by either having an new environment variable defined or by detecting the k8s infra.

When Agent is run under `kubernetes` or with the right option it will open the right ports and wait for a remote endpoint connection skipping installing and uninstalling part of running endpoint.

**Comment by jlind23** [comment]
Not a priority at the moment, closing for now and will reopen later if need be.
