### ISSUE TITLE
[Fleet]: Enroll command failed for RPM and DEB agent installation

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/elastic-agent#803]
**Kibana version:** 8.4 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build Details:**

```
Version: 8.4.0 SNAPSHOT
Build: 54932
Commit: 0645a3ba388f81fc6b43136e64ad53614101e947
```

**Preconditions:**

- 8.4 Snapshot Kibana cloud environment should be available.
- Agent Policy should be created

**Steps to reproduce:**

1. Navigate to Fleet>Agents tab
2. Click on 'Add Agent' > Select RPM or DEB platform
3. Run below commands for RPM:

```
curl -L -O https://snapshots.elastic.co/8.4.0-60171339/downloads/beats/elastic-agent/elastic-agent-8.4.0-SNAPSHOT-x86_64.rpm
sudo rpm -vi elastic-agent-8.4.0-SNAPSHOT-x86_64.rpm
sudo elastic-agent enroll --url=https://f52c5826f86a4b258a6eb766ec7bf914.fleet.us-west2.gcp.elastic-cloud.com:443 --enrollment-token=WXlxX1E0SUJXbTdoeWh2T1lfdVE6SFpIQWdwTlVTWGlzV1FSUkx6ajFHUQ== 
```
4. Observe that the error is shown while running enroll command

**Expected Result:**

- User should be able to install RPM and DEB agents

**What's not working:** 

- **Enroll command also failed for DEB agent installation**

**Screenshots:**

![image](https://user-images.githubusercontent.com/97870262/181498252-79872324-78ba-4718-88a0-7b88c9354486.png)

**Comment by prachigupta-qasource** [comment]
Please review @manishgupta-qasource

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by ph** [comment]
@elastic/elastic-agent-control-plane Anything we have change recently in our artefact?
@prachigupta-qasource Is this also happening on Build candidate?

**Comment by aleksmaus** [comment]
we added the post install script the should create the symlink 
https://github.com/elastic/elastic-agent/pull/701/files#diff-44f36381f1d27390fa33105c4cb4adb73800d433e78cfddd20aceeb4fe892018

**Comment by aleksmaus** [comment]
there is a bug in the post install script for the completely clean install. this affects the 8.4.0 and 8.3.4 releases. looking for a fix.

**Comment by prachigupta-qasource** [comment]
Hi @ph,

We have re-validated this issue on the latest **8.4.0 BC1** Kibana Cloud environment and found that the issue is **reproducible**.

**Build details:**

```
Version: 8.4.0 BC1
Build: 54999
Commit: 58f7eaf0f8dc3c43cbfcd393e587f155e97b3d0d
```

**Below are the observations**

- Enroll command failed for RPM and DEB agent installation

**RPM**

![image](https://user-images.githubusercontent.com/97870262/182074568-434e618b-318b-419e-b943-386fe204ace3.png)

**DEB**

![image](https://user-images.githubusercontent.com/97870262/182074639-964ce995-04a9-4602-a880-86f2cb0146dc.png)

Thanks!

**Comment by aleksmaus** [comment]
The latest officially posted RPM/DEB distros are broken as well:
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.3.3-x86_64.rpm
https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.3.3-amd64.deb

The fix is here: https://github.com/elastic/elastic-agent/pull/816

**Comment by ph** [comment]
@aleksmaus we should add the above to our known issues for 8.3.3 @dedemorton @pierrehilbert

**Comment by dedemorton** [comment]
@ph I've created a docs issue to track this work: https://github.com/elastic/observability-docs/issues/2054. Don't want this to get lost in github comments....

**Comment by prachigupta-qasource** [comment]
Hi @ph,

We have re-validated this issue on the latest **8.4.0 BC2** Kibana Cloud environment and found that the issue is **fixed**.

**Below are the observations:**

- Enroll command is working fine for `RPM` and `DEB` agent installation and user is able to install both the agents

**RPM**

![image](https://user-images.githubusercontent.com/97870262/182767476-d30b2744-5f08-4af0-a242-8dee5969f670.png)

**DEB**

![image](https://user-images.githubusercontent.com/97870262/182767547-56da1682-6284-491f-877f-598cb456e62d.png)

**Screenshots:**

![image](https://user-images.githubusercontent.com/97870262/182767297-fa6238d0-3de5-4ca8-9f87-b1822c377b1c.png)

**Build details:**

```
Version: 8.4.0 BC2
Build: 55166
Commit: 9e9e0d6a685cbc2858a85a357f93dcb76259fdee
```

Hence, marking this ticket as QA: Validated

Thanks!

**Comment by amolnater-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/15906
   - https://elastic.testrail.io/index.php?/cases/view/15907
 
Thanks!

**Comment by christophercutajar** [comment]
We have experienced the same issue when upgrading our agent from 8.3.3 to 8.4.1. The following command was required to get the agent running back again.

```
 sudo ln -s /var/lib/elastic-agent/data/elastic-agent-8d7885/elastic-agent /usr/share/elastic-agent/bin/elastic-agent
```

A reboot was required using `systemctl restart elastic-agent`.

This time `sudo unlink /usr/share/elastic-agent/bin/elastic-agent` was not necessary as this returned the below error:

```
unlink: cannot unlink '/usr/share/elastic-agent/bin/elastic-agent': No such file or directory
```
