### ISSUE TITLE
Allow the Agent<->Endpoint local relay port to be changed

### ISSUE THREAD

**Issue by ferullo** [elastic/elastic-agent#817]
Users sometimes find that they cannot get Agent and Endpoint to connect to each other because one or both of the ports used for the Agent<->Endpoint connection (6788 and 6789) are already taken. This enhancement request is to solve that problem.

Possible solutions to this enhancement request would be:
* A way to change it explicitly. This is hard (but not unsolvable) because Endpoint wouldn't have a way to know of the changed port until it connected over port 6788 in the first place!
* Agent opens a much higher port in a randomized range and Endpoint "finds" the port via some local scanning
* Use a Unix domain socket/Windows pipe to replace the 6788 port. The information sent over that port can relay what port to use for the 6789 purpose.
* Anything else that solves the core problem 😄

**Comment by ph** [comment]
We are looking to move to npipe/unix socket for internal communication so that should fix that problem, cc @blakerouse

**Comment by blakerouse** [comment]
We need to see how this affects running Elastic Agent in one container and Endpoint in another. They will probably need to share a emptyDir to place the unix socket in.

I don't see any issues on physical hosts.

**Comment by lucabelluccini** [comment]
Actually, we can extend this to "allowing users to configure the Management & Monitoring ports" in Elastic Agent via the Fleet UI, on a Fleet EA Policy basis.
