### ISSUE TITLE
Elastic Agent commands not working in Windows 10 in German

### ISSUE THREAD

**Issue by crisdarocha** [elastic/elastic-agent#857]
When installing Elastic Agent on a machine running Windows 10 in German actions `status`, `diagnostics`, `restart` and `version` always provide a permissions error, similar to the one below:

```
Error: failed to communicate with Elastic Agent daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open [\\\\.\\pipe\\elastic-agent-system](file:///pipe//elastic-agent-system): Zugriff verweigert"
```
<img width="1171" alt="Screenshot 2022-08-04 at 11 41 45" src="https://user-images.githubusercontent.com/36699845/182817689-f6406531-a790-4ab6-bbee-b9e3055c812b.png">

Version provides the binary version, but fails to provide the Daemon with `<failed to communicate>` then a similar message as above.

Status fails completely with a similar message.

Diagnostics fails completely.

Diagnostics collect will generate the content (at least partially), including error messages in file and in screen.

Restart fails completely.

The exact same setup on a Windows 10 in English machine works normally, so it seems a localization problem.

Even though data seems to be flowing, I'm not sure it's complete and the lack of "administrative" tasks makes the use of Elastic Agent mostly impossible.

This behaviour is independent of integrations, or being installed with Fleet or standalone.

For confirmed bugs, please report:
- Version: Elastic Agent 8.2.3
- Operating System: Windows 10 Home
- Steps to Reproduce:
  1. Spin a machine (or VM) with Windows 10 in German
  2. Install Elastic Agent following the instructions from Fleet (or from Elastic docs)
  3. Run `./elastic-agent.exe status` (or the other commands) and see it fail

@ckauf @jstrassb FYI

**Comment by crisdarocha** [comment]
For tracking @mdelapenya @jlind23 @dikshachauhan-qasource

**Comment by jlind23** [comment]
@pierrehilbert adding this to the control plane project board as it belongs to you.

**Comment by charlie-pichette** [comment]
Is this problem specific to the German language version of Windows or generic to any version of Windows where the users, groups, commands, etc are localized and different than the English version of Windows?  I know we have had issues with other language versions, specifically the Korean language version of Windows.

**Comment by crisdarocha** [comment]
@charlie-pichette it seems we already had issues with Korean, Spanish and French (https://github.com/elastic/elastic-agent/issues/150#issuecomment-1060815226). Now German, so we probably need a more systematic approach to localization.

**Comment by jlind23** [comment]
@charlie-pichette this seems to be a german problem only. As far as I remember we didn't experience the same behaviour with other languages. So far now, testing a germand localized Windows is the way to go.

**Comment by ph** [comment]
This problem would be present in any localized environment, we are simply in this case returning the operating system error. We are wrapping the original error with the intern us version. We could better handle error and reword the message from german to english. 

But I think we actually need to research if we need to localized the Elastic Agent, this would be a really big undertaking because we never considerer to localized agents or beats. But in some country or region, like mine, there are rules in place to force users to purchase software that are localized in the region official language. But this will need to be prioritized. Also Kibana is localized, I am not sure how fleet or the integration behave in other language like french.

**Comment by ckauf** [comment]
> We could better handle error and reword the message from german to english.
I just want to clarify that the issue is not about the error message not being localized, but the error(s) happening in the first place :)

**Comment by crisdarocha** [comment]
Adding to @ckauf comment, it's not the language of the message, it's an error that only occurs in the german version (and eventually in other languages also).

As we are talking about edge devices. It's pretty limiting if we go "You can only monitor your edge devices running OS's in English". Public sector in any country does use the local language (by legal requirement or not), but also companies do the same. Not every worker is comfortable working in English.

**Comment by charlie-pichette** [comment]
Microsoft used to publish the localized administrator user account name.  I would expect it is possible to identify the administrator account via SID or identify the language pack being used and select the appropriate account from a list.

**Comment by jlind23** [comment]
@pierrehilbert do you think we can investigate this during our 8.6 cycle?

**Comment by amolnater-qasource** [comment]
Hi Team
While testing on German Windows 10 VM on 8.5 SNAPSHOT kibana cloud environment, we have observed this issue reproducible:
- Elastic Agent commands not working on windows 10 German VM.

**Build details:**
BUILD: 56016
COMMIT: a93f5d9986a19277826c9e35a37ccb984caeabcc

**Screenshots:**
![11](https://user-images.githubusercontent.com/77374876/189102677-5916a845-29cc-4031-a07b-7e54272c5daa.JPG)
![12](https://user-images.githubusercontent.com/77374876/189102687-49c6ebf9-bb86-4586-adfd-30b012b055a6.JPG)

Thanks

**Comment by insukcho** [comment]
Hi, team.

I'm not sure this is related with language pack.

In my case, I installed Elastic Agent 8.4.2 in my Mac book and found the same error message as below:

```
insuk@insuks-mbp-2 elastic-agent-8.4.2-darwin-x86_64 % sudo ./elastic-agent status
Error: failed to communicate with Elastic Agent daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/elastic-agent/904896a48318d0d12ca0ce8744f83096fe5254c32c2c75ed0e56d23bbedceb9b.sock: connect: no such file or directory"
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.4/fleet-troubleshooting.html
```

But when I changed the elastic agent path to absolute path, I can get the response as below:
```
insuk@insuks-mbp-2 elastic-agent-8.4.2-darwin-x86_64 % sudo /usr/local/bin/elastic-agent status
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
Status: HEALTHY
Message: (no message)
Applications:
  * filebeat_monitoring    (HEALTHY)
                           Running
  * metricbeat_monitoring  (HEALTHY)
                           Running
  * filebeat               (HEALTHY)
                           Running
```

I guess this is a kind of symbolic link issue when installing/enrolling elastic agent to fleet server.
Check the list of my files under the elastic agent installation root directory:

```
insuk@insuks-mbp-2 elastic-agent-8.4.2-darwin-x86_64 % ls -al
total 1952
drwxr-xr-x  12 insuk  staff     384 Oct  5 11:58 .
drwxr-xr-x   4 insuk  staff     128 Oct  5 11:58 ..
-rw-r--r--   1 insuk  staff      41 Sep 14 12:36 .build_hash.txt
-rw-r--r--   1 insuk  staff      41 Sep 14 12:36 .elastic-agent.active.commit
-rw-r--r--   1 insuk  staff   13675 Sep 14 12:32 LICENSE.txt
-rw-r--r--   1 insuk  staff  943764 Sep 14 12:32 NOTICE.txt
-rw-r--r--   1 insuk  staff     861 Sep 14 12:36 README.md
drwxr-xr-x   5 insuk  staff     160 Oct  5 11:59 data
lrwxr-xr-x   1 insuk  staff      39 Sep 14 12:36 elastic-agent -> data/elastic-agent-d3eb3e/elastic-agent
-rw-r--r--   1 insuk  staff    9164 Sep 14 12:32 elastic-agent.reference.yml
-rw-------   1 insuk  staff    9127 Sep 14 12:32 elastic-agent.yml
-rw-------   1 root   staff       0 Oct  5 11:58 fleet.enc.lock
```

**Comment by kaishenelastic** [comment]
Under Windows there are no symbolic links. I just tested it on my German Windows 10 notebook and get the same error
![image](https://user-images.githubusercontent.com/73703788/195785805-389bc32a-864b-4f69-a956-da7870e1bdd8.png)

**Comment by michalpristas** [comment]
@kaishenelastic this is a bit something else, you're executing elastic agent binary in an unpacked archive, it lacks information about running instance.
try running `'C:\Program Files\Elastic\Agent\elastic-agent.exe' status`

**Comment by michalpristas** [comment]
found a root cause probably.
we add permissions to pipe if we're is running as `NT AUTHORITY/SYSTEM` (admin rights)
the thing is this name is localized in older windows versions so our check fails. working on a fix

**Comment by crisdarocha** [comment]
Thanks @michalpristas ! I hope you find a nice solution!

**Comment by kaishenelastic** [comment]
Result:
[image: image.png]
-----------------------
*Kai Shen*
*Senior Solution Architect*

Email: ***@***.***
Mobile: +49 172 4691896

Elasticsearch GmbH
www.elastic.co / XING Gruppe
<https://www.xing.com/communities/groups/elasticsearch-logstash-kibana-4ba5-1074269>

**Comment by jaebongim** [comment]
Hi Team 
I also tested this issue. (standalone)
In my case, I installed Elastic Agent 8.5.0 on my Mac book and found the same error message as below:
<img width="2555" alt="스크린샷 2022-11-15 오전 10 34 29" src="https://user-images.githubusercontent.com/13758417/201797256-c60f67a7-cada-49ea-92c8-972cd6c4fa4f.png">

I think it is not related to the only symbolic that @insukcho  mentioned.
I tried both types, but all failed.

<img width="1251" alt="스크린샷 2022-11-15 오전 10 33 11" src="https://user-images.githubusercontent.com/13758417/201797104-454b5324-af9a-4533-bc40-346921be7b2d.png">

**Comment by amolnater-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.10.0 BC7 kibana cloud environment and had below observations:

**Observations:**
- Elastic Agent commands are working in Windows 10 in German

**Screenshot:**
![1](https://github.com/elastic/elastic-agent/assets/77374876/4989f0bd-f7f7-4c49-ae71-1738c30389a2)

**Build details:**
VERSION: 8.10.0 BC7
BUILD: 66350
COMMIT: 824bcbfd9972c61e79ca9def6d43b550c5ff2999

Hence we are marking this issue as **QA:Validated**.

Thanks!
