### ISSUE TITLE
Elastic-agent should not swallows stderr and panics

### ISSUE THREAD

**Issue by mtojek** [elastic/elastic-agent#88]
Hi Team,

this [issue](https://github.com/elastic/integrations/issues/2602#issuecomment-1023268069) proved that we need a more user-friendly method to collect all panics. Otherwise we won't be able to grab anything from customers.

In the mentioned case I used `strace` to listen what `filebeat` is sending to `/dev/null`, but we need a more trival method.

**Comment by AndersonQ** [comment]
jotting down ideas:
 - do we have panics (stderr) logged to systemd/jornald?
 - could we collect systemd/jornald using the agent's `diagnostics collect` command?
 - if the logger is set up when the agent panics, we could recover and properly log the panic
 - is there any trade-off for always collecting systemd/jornald logs for the agent on the `diagnostics collect`?

**Comment by ph** [comment]
Funny thing is, if Agent recover and we are running journald input  I presume we would get that information.

**Comment by mtojek** [comment]
Awesome, thanks @AndersonQ!
