### ISSUE TITLE
[Elastic Agent] Allow beats subprocess to define custom configuration.

### ISSUE THREAD

**Issue by ph** [elastic/elastic-agent#90]
**Motivation**

**Use case 1:** Subprocess doesn't load specific custom beats configuration, this means that the beats will start with the default configuration that is defined in the **go-ucfg** structs from the source code. As an example, the **k8s processors** are enabled by default in the context of elastic-agent [when they should not](https://github.com/elastic/beats/pull/29809#issue-1100101810). 

**Use case 2:** Seccomp is on by default, with the default options and it's not currently possible to overrides these default and prevent [forking java-attacher](elastic/elastic-agent#95).

**Possible solution:**

Allow subprocess to load custom `{process_name}.elastic-agent.yml` when it starts, this could be added as part of the specs and the developer would be able to define a configuration that should be used.

Something like this in the spec:

```yml
args: [
  "-c", "{process_name}.elastic-agent.yml"
  "-E", "management.enabled=true",
  "-E", "gc_percent=${APMSERVER_GOGC:100}"
]
```

**Questions:**

Is this introduce a security issue?

**Comment by sgtsnooky** [comment]
Hi all, 
I am still experiencing this issue on 8.1.2. 

[elastic_agent.filebeat][error] Error extracting container id

**Comment by WoodyWoodsta** [comment]
As per https://github.com/elastic/beats/issues/27216#issuecomment-1232871229, I was going to open a new issue about the error `Error extracting container id`, but after doing a bit more testing, I'm not entirely sure it's a separate case. So I thought I would add my case here:

I have kubernetes container logs enabled in the `kubernetes` integration. I also have the `system` integration. The following cases present:

1. If I **enable** `Collect... system syslog logs` but the `syslog` file **is not present** in the configured directory, I get **no errors** ✅ 
2. If I **disable** `Collect... system syslog logs` but the `syslog` file **is present** in the configured directory, I get **no errors** ✅ 
3. If I **enable** `Collect... system syslog logs` and the `syslog` file **is present** in the configured directory, I get **errors** ❌ 

Is this related to offending default config or is this a separate issue?

**Comment by gmontoro** [comment]
Same for agent 8.4.2  with a cluster running containerd. I think the use of containerd is the issue as therefor the libs from docker are not available also:
"Docker is no longer supported as of September 2022. For more information about this deprecation, see the [AKS release notes](https://github.com/Azure/AKS/releases)." https://learn.microsoft.com/en-us/azure/aks/cluster-configuration

Can you please provide some update to that issue.

**Comment by fludo** [comment]
This will by a no-go to use ElasticSearch for observability if containerd is not supported correctly. Any clue when this will be adressed ? @cmacknz ?

**Comment by cmacknz** [comment]
Please open a separate enhancement request to add containerd support so it can be triaged appropriately, the original description of this issue is unrelated as far as I can tell.

**Comment by Happycoil** [comment]
@cmacknz I opened a separate issue: https://github.com/elastic/elastic-agent/issues/1614

**Comment by WoodyWoodsta** [comment]
@cmacknz @Happycoil Sorry - why is this considered a separate issue?

@gmontoro's comment was the one about `containerd` but nowhere does it suggest that this issue is scoped to just `containerd`? I thought this was a configuration issue, as per the original description?

**Comment by Happycoil** [comment]
@WoodyWoodsta I'm not sure, there's some confusion here among the myriad of different issues and threads. As far as I can tell this issue describes part of the solution to the problem being described by AKS users, but it doesn't appear to be triaged properly. This shouldn't have been a problem for over a year if there was a clear understanding of the consequences. Signing up to Elastic Cloud and connecting it to AKS just doesn't work properly, and Elastic is potentially losing sales because of what is apparently a small config problem.

**Comment by WoodyWoodsta** [comment]
I'm not a cloud customer so it's not just that market. My stack is bare-metal kubeadm + `containerd`, so I can see how it might appear to be `containerd`-related but to me sounds like a red-herring.

**Comment by cmacknz** [comment]
Thanks for the comments everyone, it seems there is a real bug here with the agent running on AKS which we are not tracking properly. 

The original purpose of this issue was to add a feature to the agent to enable configuration overrides for processes that the agent starts, which I suppose could possibly been a work around for the problem here but the issue description does not read as a bug affecting many customers or all of AKS.

https://github.com/elastic/elastic-agent/issues/1614 clarifies this and the scope of impact.

**Comment by endorama** [comment]
Hello, to add to the Use case 1 mentioned in the description, it seems also the `add_cloud_metadata` processor is enabled by default (if my understanding of [this piece of code is correct](https://github.com/elastic/beats/blob/94b14693796dd70704caec76e785329319118445/x-pack/metricbeat/cmd/agent.go#L42)) even in cases where this lead to misleading data.

**Comment by cmacknz** [comment]
Controlling global processors will be addressed with https://github.com/elastic/elastic-agent-shipper/issues/160

**Comment by jlind23** [comment]
Closing this as not aligned with our long term strategy, will reopen later if required.
