### ISSUE TITLE
elastic-agent: KIBANA_FLEET_{USERNAME,PASSWORD} listed twice, once with reference to unused env vars

### ISSUE THREAD

**Issue by axw** [elastic/elastic-agent#91]
KIBANA_FLEET_USERNAME and KIBANA_FLEET_PASSWORD are mentioned twice in the help output of `elastic-agent container`:

https://github.com/elastic/beats/blob/e61a3656cd70e18099db4ef4d20397e0c237a959/x-pack/elastic-agent/pkg/agent/cmd/container.go#L112-L113

https://github.com/elastic/beats/blob/e61a3656cd70e18099db4ef4d20397e0c237a959/x-pack/elastic-agent/pkg/agent/cmd/container.go#L126-L127

One mentions `$KIBANA_USERNAME` and `$KIBANA_PASSWORD` as a fallback, and the other mentions `$ELASTICSEARCH_USERNAME` and `$ELASTICSEARCH_PASSWORD`. In reality, only the latter is honoured:

https://github.com/elastic/beats/blob/e61a3656cd70e18099db4ef4d20397e0c237a959/x-pack/elastic-agent/pkg/agent/cmd/setup_config.go#L111-L112

**Comment by jlind23** [comment]
@pierrehilbert any progress here?

**Comment by Valkyrie00** [comment]
I was looking for a task to contribute, I found this one but during my checks I noticed that this activity had already been completed. I would suggest closing 🙂

**Comment by pierrehilbert** [comment]
Thanks for catching this.
I'm closing following your comment.
