### ISSUE TITLE
agent on cloud starts monitoring processes

### ISSUE THREAD

**Issue by michel-laterman** [elastic/elastic-agent#915]
We have seen instances where the agent on cloud starts the mericbeat/filebeat monitoring sidecar processes.
The policy it's running indicates that monitoring is disabled (and metrics and log collection are both set to false).

The agent should not be starting the monitoring processes when this is the case.

**Comment by ph** [comment]
I see two possibilities for this to happen:
1. The unpack logic is wrong around monitoring.
2. The way cloud is settings that to false by default is wrong.

**Comment by jlind23** [comment]
Closing this until further occurences are being reported
