### ISSUE TITLE
[elastic-agent] apm-server permissions for forking java-attacher

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/elastic-agent#95]
Recent `apm-server` releases now come with the `java-attacher.jar` bundled along, so that an `apm-server` can fork and run a configured `java-attacher`.

In standalone mode, this requires that the user provide permissions to the `apm-server` to fork a process, otherwise the operation errors:

```
{"log.level":"error","@timestamp":"2021-12-29T08:53:47.771Z","log.logger":"beater","log.origin":{"file.name":"beater/beater.go","file.line":439},"message":"failed to run java attacher: fork/exec /usr/bin/java: operation not permitted","service.name":"apm-server","ecs.version":"1.6.0"}
```

Currently, when running `apm-server` in managed mode (under the `elastic-agent`), these permissions are not set, even though the user has the ability to configure the `java-attacher` from kibana.

Are there plans for how to address this?

@felixbarny @ruflin

**Comment by felixbarny** [comment]
@stuartnelson3 can this be closed now that we have decided to remove seccomp from APM Server?

**Comment by stuartnelson3** [comment]
yep! this is no longer needed.
