### ISSUE TITLE
[Agents]: Artifact link is not selected from the agent binary under Fleet Settings during Agent upgrade.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/elastic-agent#952]
**Kibana version:**  8.4.0 BC4 Kibana cloud environment

**Host OS:**  All

**Build details:**
VERSION: 8.4.0 BC4
BUILD: 55323
COMMIT: 0011c16d2b4b19b169bd801766cb4db8792a2adc

**Preconditions:**
1. 8.4.0 BC4 Kibana cloud environment should be available.

**Steps to reproduce:**
1. Navigate to Fleet>Settings.
2. Edit default Agent binary download link to `https://hello.my.download/downloads`.
3. Create a policy and install lower version agent say 8.3.3 version to this policy.
4. Trigger upgrade.
5. Observe error logs under Agent>Logs with trying to download from the incorrect default source:
` call to 'https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.4.0-linux-x86_64.tar.gz' `

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/185382397-4b381d7b-fc0b-4e71-9e19-4e9faafb295f.JPG)
![2](https://user-images.githubusercontent.com/77374876/185382389-c27d9a67-711d-4bf9-8b5e-29aba001e69a.JPG)

**Expected Result:**
Artifact link should be selected from the agent binary under Fleet Settings during Agent upgrade.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by amolnater-qasource** [comment]
FYI @jlind23 @michalpristas

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by michalpristas** [comment]
source uri reloading was fixed/added in 8.4 so to test it properly you need update process starting from 8.4 to some new version. 8.3 does not include a fix

**Comment by amolnater-qasource** [comment]
Hi @michalpristas 
Thank you for the feedback.
We have revalidated upgrading agent on latest 8.5 Snapshot with updated agent binary source and found it **working fine**.

**Observations:**
- Artifact link is selected from the agent binary under Fleet Settings during Agent upgrade. 
- Appropriate link is available in the agent error logs.

**Build details:**
BUILD: 55675
COMMIT: 1e14da0aa66908296203f1f83b33c70876b7698c

**Screenshots:**
![5](https://user-images.githubusercontent.com/77374876/185852358-6595a6a4-9fce-4c4f-ae24-1b6e1c4ff7f4.JPG)
![7](https://user-images.githubusercontent.com/77374876/185852352-b2c4e6ac-6583-49ec-bcac-62e4cae06b14.JPG)

Hence, we are closing this issue and marking it as **QA:Validated**.

Thanks!
