### ISSUE TITLE
The Elastic agent standalone reference manifests should document persisting the state path

### ISSUE THREAD

**Issue by cmacknz** [elastic/elastic-agent#953]
To persist the state of the agent and integrations on a node the agent state path can be mounted to a [host path persistent volume](https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume). Our ECK operator does this by default but I don't believe we document it in the standalone agent Kubernetes manifests.

We should:

- Document the STATE_PATH environment variable and the default path of `/usr/share/elastic-agent/state`
- Include mounting the STATE_PATH to a host path persistent volume claim in our reference self-managed K8S YAML. Persistent the state path almost always the desired behaviour, particularly when using integrations that ingest log files as the ingestion progress is check pointed to disk.

**Comment by jlind23** [comment]
Closing this as done by https://github.com/elastic/elastic-agent/issues/4611
