### ISSUE TITLE
Tracking: current metrics monitoring with V2

### ISSUE THREAD

**Issue by michalpristas** [elastic/elastic-agent#954]
Idea was to do the same thing as is performed today
- expose metrics on http endpoint (each process)
- configure metricbeat or some slim form of it (if existing( to collect metrics from this endpoint
- idea: if we specify metrics -> specific monitoring output we should get process isolation based on current state of v2 implementation

**Comment by joshdover** [comment]
@michalpristas were you able to come up with a ballpark estimate of this effort? It sounds fairly straightforward from my understanding but I want to confirm

**Comment by michalpristas** [comment]
sound about right. assuming we dont run into any issues 1W if we run into something 2W

**Comment by cmacknz** [comment]
1W to 2W is exactly how much time we have until 8.5 feature freeze after ON week. I don't think we can merge the agent V2 feature branch without completing this. @michalpristas prioritize this over anything else you have assigned and if you can't, let us know. CC @pierrehilbert 

We will be de-prioritizing supporting the shipper in agent for 8.5 to ensure we can get the V2 control protocol finished, I will send out an email soon. You can stop work on those issues.

**Comment by michalpristas** [comment]
i'm starting working on this tomorrow, i dont do ON week so I can fit it in

**Comment by michalpristas** [comment]
Closed by #1487
