### ISSUE TITLE
[Fleet]: Information for integrations running by elastic agent not available in local metadata

### ISSUE THREAD

**Issue by ghost** [elastic/elastic-agent#965]
**Kibana version:**  8.4.0 BC5 Kibana cloud environment 

**Host OS and Browser version:** All, All 

**Build details:** 

``` 
VERSION: 8.4.0
BUILD: 55374
COMMIT: f12954223a8ad66bbbf77becc4f0557ffd1c92c3
ARTIFACT LINK: https://staging.elastic.co/8.4.0-f8287a32/summary-8.4.0.html
```

**Preconditions:**
1. 8.4.0 BC5 Kibana cloud environment should be available.
2. Agent should be installed with policy having few integrations.

**Steps to reproduce:**
1. Login to Kibana Cloud environment.
2. Get agent id from agent details page.
3. Navigate to Dev tools under stack management.
4. Run command to check metadata: `GET .fleet-agents/_doc/{agent_id}.`
5. Observe that the integration information is not available.

**Expected Result:**
-  Information for integrations running by elastic agent should be available in local metadata.

**Screen Recording:**

https://user-images.githubusercontent.com/102019374/185849304-26a9c2c6-b69c-45f1-9de6-552135673a2e.mp4

**Related ticket:**
https://github.com/elastic/beats/pull/25070

**Comment by simranvaseer-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Secondary review for this ticket is Done

**Comment by harshitgupta-qasource** [comment]
Hi Team,

We have revalidated this issue on latest 8.10.0 SNAPSHOT kibana cloud environment and found it **still reproducible**.

**Observations:**
- Information for integrations running by elastic agent not available in local metadata

**Screen-Cast:**

https://github.com/elastic/elastic-agent/assets/101545338/4a2ab22a-770f-416a-a3c8-2f27479b6270

**Build details:**
VERSION: 8.10.0 SNAPSHOT
BUILD: 65561
COMMIT: 4dadcbb91136a3e7d39e4b419aa12e21a37e4918

Please let us know if anything else is required from our end.

Thanks!

**Comment by cmacknz** [comment]
This functionality was either never implemented or removed, see the latest comment on https://github.com/elastic/beats/issues/24901.

This test case can be deleted.
