### ISSUE TITLE
elastic-agent container output API key support

### ISSUE THREAD

**Issue by michel-laterman** [elastic/elastic-agent#97]
**Describe the enhancement:**

When running the elastic-agent in a container, in standalone mode, there is currently no way to specify an API key as a credential instead of username/password.

The `elastic-agent.docker.yml` file only shows username/password:
https://github.com/elastic/elastic-agent/blob/5664fa47b8103942136b3d8f18632020a4356f66/elastic-agent.docker.yml#L4-L10

**Comment by jlind23** [comment]
@ph @michel-laterman what would be the solution here? Simply updating the yaml file to be able to handle API Key parameter instead of username and password?

**Comment by michel-laterman** [comment]
Yes, but we also need to make sure that the containers are able to read them from env vars as well.

**Comment by swiatekm** [comment]
There's a bit of a problem here. `api_key` and `username/password` are mutually exclusive, so in order to set `api_key`, the latter have to be unset. But the docker template has defaults for username and password, and as far as I can tell, these are impossible to unset just via environment variables - if the user sets them to empty strings, the defaults kick in.

So, even if we were to add `api_key` here, it'd be impossible to actually use. We need a way to not have username and password set. Removing the defaults would be the simplest solution, but I believe that's technically a breaking change.

**Comment by swiatekm** [comment]
A simple and dirty solution would be to set all the values to be empty by default:

```yaml
    username: '${ELASTICSEARCH_USERNAME:}'
    password: '${ELASTICSEARCH_PASSWORD:}'
    api_key: '${ELASTICSEARCH_API_KEY:}'
```

This produces the right behaviour, as empty string is equivalent to unset as far as the config parser is concerned.

**Comment by swiatekm** [comment]
I believe the defaults here were originally set long ago to align with Elasticsearch defaults. However, this doesn't apply to any of the currently supported versions. Elasticsearch has an initial bootstrap password that is either randomly generated or set via an environment variable instead. So by changing the defaults, we're not losing out on ease of setup for testing or local dev.

We may break some users who not only use the `elastic` user in their agent configuration, but also rely on the fact that it's the default. These would necessarily be non-production use cases. Doing this in production is a very bad security practice that we highly discourage, and it's probably to their ultimate benefit that we break this, harsh as that may sound.

**Comment by nimarezainia** [comment]
@jlind23 @pierrehilbert should this be added to the 9.0 list of breaking changes? as in, 9.0 will use the API key as the default.

@swiatekm for now I would say that the default behavior should not be changed. Just to clarify, are you saying that even if the user sets the API key, there's no way to unset the user/password combo?

**Comment by jlind23** [comment]
Adding @ycombinator instead of @pierrehilbert to chime in here.

**Comment by swiatekm** [comment]
> @swiatekm for now I would say that the default behavior should not be changed. Just to clarify, are you saying that even if the user sets the API key, there's no way to unset the user/password combo?

Yes, that's exactly it. There's no way to unset them just by changing environment variables. They could provide their own config file, but that's more friction, and they can do so right now without any changes needed from us.

**Comment by nimarezainia** [comment]
@cmacknz any thoughts on [this](https://github.com/elastic/elastic-agent/issues/97#issuecomment-2312793588) approach?

**Comment by cmacknz** [comment]
LGTM
