### ISSUE TITLE
[BUG] Install Error in 8.3.3 for Elastic Agent RPM deployment

### ISSUE THREAD

**Issue by ScottElastic** [elastic/elastic-agent#974]
Describe the bug
An Installation error occurs when using the install scripts for RPM based deployments of the Elastic Agent in Linux

Endpoint Version
8.3.3, was unable to repro in earlier versions.

To Reproduce

Using Fleet, Click "Add Agent" in the cloud console
Use RPM install option (I tried tarball and had same issue as well)
Install on CentOS server ( I tried Stream9 and CentOS 7)
Install Error
Expected behavior
Installs Elastic Agent

Screenshots / Messages Sent
Error message on install:

scott_holt@scotth-centos7 ~]$ sudo elastic-agent enroll --url=[https://30005658853845528c8799c96b857f47.fleet.us-central1.gcp.cloud.es.io:443](https://30005658853845528c8799c96b857f47.fleet.us-central1.gcp.cloud.es.io/) --enrollment-token=amxFT1o0QUIxbVRLM0YwS2RFT2M6YWtNZENqMTlSOUNvNkJvVjRhUFlpQQ==
/bin/elastic-agent: line 6: /usr/share/elastic-agent/bin/elastic-agent: No such file or directory
[scott_holt@scotth-centos7 ~]$ sudo systemctl enable elastic-agent
Created symlink from /etc/systemd/system/multi-user.target.wants/elastic-agent.service to /usr/lib/systemd/system/elastic-agent.service.

Host

OS: CentOS 7, CentOS Stream 9

**Comment by fionera** [comment]
Its also broken in Debian

**Comment by ScottElastic** [comment]
For what it's worth I tried the install process with 8.4.0 on CentOS 7 after upgrading my cluster and that worked fine.

**Comment by jlind23** [comment]
Outdated/already resolved issue hence closing.
