### ISSUE TITLE
[Fleet]: No data available under Data Streams tab for lower version Standalone agent for RPM/DEB agents

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/elastic-agent#980]
**Kibana version:** 8.4 Kibana cloud environment

**Host OS and Browser version:** All, All

**Build Details:**

```
Version: 8.4.0 BC6
Build: 55395
Commit: 1922ab0b6f8dc2906ef10f3fb65fc4d0e0076f90
```

**Preconditions:**

- 8.4 Kibana cloud environment should be available.
- Agent Policies should be created
- Lower version 8.3.3 Standalone agent should be installed

**Steps to reproduce:**

1. Navigate to Fleet > Agent tab
2. Click on 'Add Agent' button
3. Agent flyout gets opened
4. Select the `Policy`, `Run Standalone`, download `elastic-agent.yml`
5. Edit the `username` and `password` in the `elastic-agent.yml` file
6. Run below commands in the Putty:
```
curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.3.3-x86_64.rpm
sudo rpm -vi elastic-agent-8.4.0-x86_64.rpm 
```
7.  Copy the above `elastic-agent.yml` file in the elastic-agent folder
8. Run below commands in the Putty:
```
sudo systemctl enable elastic-agent 
sudo systemctl start elastic-agent
```
9. Navigate to Fleet > Data Streams tab
10. Observe that the no data is available for lower version Standalone agent for RPM/DEB agents

**Expected Result:**

- Data should be available for lower version (i.e. 8.3.3) Standalone agent for RPM/DEB agents

**What's Working:** Data is available under Data Streams tab for same version (i.e. 8.4.0) Standalone agent for RPM/DEB agents

**Logs/Screenshots:**

- No logs available under `/var/lib/elastic-agent/data/elastic-agent-0ffbed`

![image](https://user-images.githubusercontent.com/97870262/186079318-8b7ff992-1114-4527-9968-bd607931b4b4.png)

- No logs are collected with `elastic-agent diagnostics collect` command

![image](https://user-images.githubusercontent.com/97870262/186081599-7d58eda1-6919-4350-9633-592e408dff17.png)

**Comment by dikshachauhan-qasource** [comment]
Secondary Review is done.

**Comment by prachigupta-qasource** [comment]
Hi Team,

As per our understanding the above issue also reproducible due to the https://github.com/elastic/elastic-agent/issues/803#issuecomment-1200906217

Could you please confirm if we can close this standalone agent issue if it is due to the above stated reason.

Thanks!

**Comment by prachigupta-qasource** [comment]
Hi Team,

This issue was occurring due to the [https://github.com/elastic/elastic-agent/issues/80](https://github.com/elastic/elastic-agent/issues/803#issuecomment-1200906217)3 which is **fixed now**.

Further, on BC8, we have observed that datastreams are now available for standalone lower version i.e. **8.5.3** `RPM` and `DEB `agents.

**Screenshot:**

![image](https://user-images.githubusercontent.com/97870262/209320001-a1639a3e-cba4-4ef9-8cd9-6beeebab2669.png)

![image](https://user-images.githubusercontent.com/97870262/209320492-c501e807-b4ab-4015-a16e-3c7f6ae851c0.png)

**Build details:**

```
Version: 8.6.0 BC8
Build: 58807	
Commit: 335b86a633af9ce1d9c8a92187ed1c8697ab139f
```
Hence, we are closing this issue as QA: Validated.

Thanks!
