### ISSUE TITLE
V2: Agent doesn't stop cleanly on SIGINT

### ISSUE THREAD

**Issue by aleksmaus** [elastic/elastic-agent#995]
Agent doesn't stop cleanly on SIGINT.
Running off of the latest V2 branch:
https://github.com/elastic/elastic-agent/tree/feature-arch-v2

Steps to reproduce:
1. Enroll the agent from the command line
2. Run the agent from the command line
3. Press Ctrl+C, observe the agent doesn't exist requires SIGKILL for each of the running processes.

**Comment by cmacknz** [comment]
Fixed by https://github.com/elastic/elastic-agent/pull/1258
