### ISSUE TITLE
V2: Agent starting multiple instances of filebeat or metricbeat and goes into tight restart loop for the beat process

### ISSUE THREAD

**Issue by aleksmaus** [elastic/elastic-agent#997]
Agent starting multiple instances of filebeat or metricbeat and goes into tight restart loop for the beat process.
More than 50% of agent runs fail while starting multiple beats processes due to the conflict on data path, which results in the tight restart loop for the beat.
```
Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
Exiting: data path already locked by another beat. Please make sure that multiple beats are not sharing the same data path (path.data).
```

This is documented here as well:
https://github.com/elastic/beats/pull/32673#issuecomment-1224863904

Running off of the latest V2 branch:
https://github.com/elastic/elastic-agent/tree/feature-arch-v2

Steps to reproduce:
1. Enroll the agent from the command line
2. Run the agent from the command line

**Comment by cmacknz** [comment]
Let's wait for the fix to https://github.com/elastic/beats/issues/31670 before addressing this. 

That will remove the data path locking failure, but I think that is just a symptom here where the real problem is likely that the V2 agent is rapidly starting and stopping the Filebeat and Metricbeat.

**Comment by cmacknz** [comment]
@blakerouse reports we've fixed this particular bug already, closing. If we struggle to reproduce the locking issue separately (which I don't think will be a problem) we can try reverting the fix for this on the agent V2 branch.
